### ISSUE TITLE
Project claims to be open source but doesn't share the source

### ISSUE THREAD

**Issue by philcryer** [RestyaPlatform/board#1]
This project looks interesting, but on [http://restya.com/board/](http://restya.com/board/) it says, *"Open source. Trello like kanban board. Based on Restya platform."* but then on the GitHub project page, [RestyaPlatform/board](https://github.com/RestyaPlatform/board), it says *"Source code will be pushed once AWS AMI is ready for sale (One of our revenue options)"* I don’t think open source means what you think it does. Can you fix this issue?

**Comment by jfklingler** [comment]
+1

**Comment by defmacro-jam** [comment]
+1

**Comment by valkyr9991234** [comment]
I pay 10$. Just push the source here.

**Comment by ayoung012** [comment]
+1 hardly in the spirit of open source projects. I came here hoping to make contributions, but I doubt with this model that I will even be about to make so much as a pull request

**Comment by rrjanbiah** [comment]
@philcryer Are you saying that open source projects shouldn't make money (to survive)? If so, can you share little more information on this? We have mentioned our monetization policy here http://restya.com/

From our understanding, Magento adopts similar strategy. In case, if there's any misunderstanding on our end, we'll take appropriate course of action (either to close it down or not to monetize it). Sorry.

Thanks

**Comment by marcpires** [comment]
It's, at best, a misdirection. When a company says it hosts its products on github, it makes developers believe that the source code will be available for better understanding, enhancing, forking and getting contributions back from the community. When a company says it hosts products on github it shows engagement with the software and open source community, and it's clearly not the case.

**Comment by rrjanbiah** [comment]
@marcpires How's that different from Magento?

**Comment by marcpires** [comment]
I have access to magento source code, that's available on github. https://github.com/magento/magento2

**Comment by rrjanbiah** [comment]
@marcpires What are you trying to convey here? I'm quite confused. Please read above. We're saying that we'll push code along with making AWS AMI available for sale--so that we don't miss revenue option.

**Comment by philcryer** [comment]
> @rrjanbiah "@philcryer Are you saying that open source projects shouldn't make money (to survive)? If so, can you share little more information on this?"

I'm absolutely not saying that, you can make money off of open source software, but if you want to claim your work is open source it needs to be licensed properly, and then you need to follow the constraints laid out in that license. Details: http://opensource.org/faq#commercial

I appreciate your responses, it looks like you have some good software, I wish you good luck with it!

**Comment by philcryer** [comment]
> @rrjanbiah "@marcpires How's that different from Magento?"

So this project is different from Magento because Magento has:
* the source code is available: [magento/magento2](https://github.com/magento/magento2)
* an open source [license](https://github.com/magento/magento2/blob/develop/LICENSE.txt) posted with the source code
* (additionally, though not required) documentation showing how to build and run your own version of the software: [install guide](http://devdocs.magento.com/guides/v1.0/install-gde/install/composer-clone.html#instgde-prereq-compose-clone)

**Comment by marcpires** [comment]
+1

**Comment by rrjanbiah** [comment]
Thanks everyone for your interest and patience. We'll push code along with license, etc.

**Comment by MrJoy** [comment]
So....  Any ETA?

**Comment by rrjanbiah** [comment]
Approx 22nd. Thanks for your patience.

**Comment by rrjanbiah** [comment]
Released now, FYI

**Comment by actuallymab** [comment]
congratz @rrjanbiah it looks pretty!

**Comment by rrjanbiah** [comment]
Thank you
