### ISSUE TITLE
White page on administration user page

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#1006]
Error in console Chrome : 
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at default.cache.285e392e.js:57
    at o (default.cache.285e392e.js:12)
    at Object.d.error (default.cache.285e392e.js:12)
    at l (default.cache.285e392e.js:1)
    at Object.fireWith [as rejectWith] (default.cache.285e392e.js:1)
    at d (default.cache.285e392e.js:3)
    at XMLHttpRequest.d (default.cache.285e392e.js:3)

Error in nginx error.log :
PHP message: PHP Warning:  pg_fetch_object() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1361
PHP message: PHP Notice:  Trying to get property of non-object in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1368
PHP message: PHP Notice:  Trying to get property of non-object in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1369
PHP message: PHP Notice:  Trying to get property of non-object in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1369
PHP message: PHP Notice:  Trying to get property of non-object in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1372
PHP message: PHP Warning:  pg_query_params(): Query failed: ERREUR:  la relation « admin_users_listing » n'existe pas
LINE 1: SELECT row_to_json(d) FROM (SELECT * FROM admin_users_listin...
                                                  ^ in /usr/share/nginx/html/restyaboard/server/php/R/r.php on line 230
PHP message: PHP Warning:  Header may not contain more than a single header, new line detected in /usr/share/nginx/html/restyaboard/server/php/bootstrap.php on line 168" while reading response header from upstream, client: 192.9.200.169, server: restyaboard, request: "GET /api/v1/users.json?page=1&token=585f7634a246e80efde7ed04692fbebfae69a401&_=1486039179625 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "restyaboard", referrer: "http://restyaboard/"

**Comment by lmarikannan** [comment]
@morphos88 Can you please run this sql queries `https://github.com/RestyaPlatform/board/blob/master/sql/upgrade-0.4-0.4.1.sql` and try again?

**Comment by morphos88** [comment]
It's works.

It's a fresh install and i use sh script available on your website.

**Comment by lmarikannan** [comment]
@morphos88 Thanks for your confirmation. It was missed in `zip` file and we are going to merge it.
