### ISSUE TITLE
Import Trello Json

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#1008]
When i try to import board from trello i have an error on Nginx error.log :

2017/02/02 15:36:12 [error] 22122#22122: *3741 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function utf8_encode() in /usr/share/nginx/html/restyaboard/server/php/R/r.php:2293
Stack trace:
#0 /usr/share/nginx/html/restyaboard/server/php/bootstrap.php(123): r_post('/boards', Array, Array, Array)
#1 /usr/share/nginx/html/restyaboard/server/php/R/r.php(5362): main()
#2 {main}
  thrown in /usr/share/nginx/html/restyaboard/server/php/R/r.php on line 2293" while reading response header from upstream, client: 192.9.151.22, server: restyaboard, request: "POST /api/v1/boards.json?token=2b3918c717bcdce0718443fba6ab864974600857 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "restyaboard", referrer: "http://restyaboard/"

**Comment by rrjanbiah** [comment]
*Internal note*

Looks like the install script needs to be updated for necessary dependencies http://stackoverflow.com/questions/35701730/utf8-endecode-removed-from-php7

**Comment by morphos88** [comment]
It work !

**Comment by morphos88** [comment]
i have an other problem :

2017/02/03 14:14:34 [error] 22121#22121: *20934 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: list in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1176
PHP message: PHP Notice:  Undefined index:  in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1176
PHP message: PHP Notice:  Undefined index: list in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1176
PHP message: PHP Notice:  Undefined index:  in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1176
PHP message: PHP Notice:  Undefined index: closed in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1128
PHP message: PHP Notice:  Undefined index: card in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1177
PHP message: PHP Notice:  Undefined index:  in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1177
PHP message: PHP Notice:  Undefined index: card in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1177
PHP message: PHP Notice:  Undefined index:  in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1177
PHP message: PHP Notice:  Undefined index: card in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1177
PHP message: PHP Notice:  Undefined index:  in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1177
PHP message: PHP Notice:  Undefined index: card in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1177
PHP message: PHP Notice:  Undefined index:  in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1177
PHP message: PHP Notice:  Undefined index: closed in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1128
PHP message: PHP Notice:  Undefined index: card in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1177
PHP message: PHP Notice:  Undefined index:  in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1177
PHP message: PHP Notice:  Unde

**Comment by morphos88** [comment]
No response ?

**Comment by lmarikannan** [comment]
@morphos88 Sorry for the delay. We are working on it. Will update you tomorrow.

**Comment by morphos88** [comment]
Ok great thank you

**Comment by lmarikannan** [comment]
@morphos88 Update your `server/php/libs/core.php` file with this https://raw.githubusercontent.com/RestyaPlatform/board/3f839ae0fc0b9331be71acf63d6203b7f03fb5f2/server/php/libs/core.php

**Comment by morphos88** [comment]
there is another problem : 
PHP message: PHP Notice:  Undefined index: 5875e967f099767135b3f443 in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1210
PHP message: PHP Notice:  Undefined index: 58751176d3cf2b5b936e6526 in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1210
PHP message: PHP Warning:  pg_query_params(): Query failed: ERREUR:  séquence d'octets invalide pour l'encodage « UTF8 » : 0xe9 0x20 0x31 in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1203
PHP message: PHP Warning:  pg_fetch_assoc() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1203
PHP message: PHP Warning:  pg_query_params(): Query failed: ERREUR:  séquence d'octets invalide pour l'encodage « UTF8 » : 0xe9 0x20 0x31 in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1215
PHP message: PHP Warning:  pg_fetch_assoc() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1215
PHP message: PHP Warning:  pg_query_params(): Query failed: ERREUR:  séquence d'octets invalide pour l'encodage « UTF8 » : 0xe9 0x20 0x31 in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1215
PHP message: PHP Warning:  pg_fetch_assoc() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1215
PHP message: PHP Warning:  pg_query_params(): Query failed: ERREUR:  séquence d'octets invalide pour l'encodage « UTF8 » : 0xe9 0x20 0x31 in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1215
PHP message: PHP Warning:  pg_fetch_assoc() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1215
PHP mess
2017/02/07 08:16:56 [error] 10262#10262: *18 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: closed in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1128
PHP message: PHP Notice:  Undefined index: closed in /usr/share/nginx/html/restyaboard/server/php/libs/core.php on line 1128" while reading upstream, client: 192.9.200.169, server: restyaboard, request: "POST /api/v1/boards.json?token=7b02dd61a95762072c6f836547a0eeee0d2ca354 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "restyaboard", referrer: "http://restyaboard/"

**Comment by lmarikannan** [comment]
@morphos88

We have fixed the initial warning errors, but to check encoded related warnings please attach a sample Trello json to reproduce it.

https://raw.githubusercontent.com/RestyaPlatform/board/65728b29065c8a4694134fb5417a635b0209276e/server/php/libs/core.php

**Comment by morphos88** [comment]
There is export 
[QlikView.txt](https://github.com/RestyaPlatform/board/files/756935/QlikView.txt)

**Comment by lmarikannan** [comment]
@morphos88 Update your `server/php/libs/core.php` file with this and try again?

https://raw.githubusercontent.com/RestyaPlatform/board/0e619b69d9faf4b16ebc9b30ef9de7446e72408e/server/php/libs/core.php

**Comment by morphos88** [comment]
Ok import work and there is no error message !

**Comment by lmarikannan** [comment]
@morphos88 Thanks for your confirmation.
