### ISSUE TITLE
White screen at start 

### ISSUE THREAD

**Issue by adnanmitf09** [RestyaPlatform/board#101]
Hi,

I have installed the board successfully, however when I hit the url, a white screen appras. I got following response by inspecting the element.

``
<br />
<b>Notice</b>:  Undefined index: CONTENT_TYPE in <b>/home/domain/public_html/server/php/R/token.php</b> on line <b>18</b><br />

**Comment by adnanmitf09** [comment]
Fixed the issue, actually debugging was on in config.inc.php (define('R_DEBUG', true);) in server/php/R/ directory. Setting it to false fixed the issue.

**Comment by rrjanbiah** [comment]
Reopened for Undefined index notice

**Comment by ssivachidambaram** [comment]
Fixed in v0.1.6.
