### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by theriverman** [RestyaPlatform/board#1010]
Hi

I downloaded the script to ~/kanban
then added chmod +x to it and issued by "sudo ./restyaboard.sh"
Answered the questions then it failed.
See my log attached.

br,
Chris

[restyaboard_install.txt](https://github.com/RestyaPlatform/board/files/755755/restyaboard_install.txt)

**Comment by lmarikannan** [comment]
Can you please run the below command and try again with install script?

`chmod 755 /usr/bin/dpkg`

**Comment by rrjanbiah** [comment]
@theriverman Were you able to get it resolved? Closing this now. If the issues is not resolved or getting any other issues, please feel free to reopen

**Comment by theriverman** [comment]
Hi,

Tried the chmod modification, still the same error, no difference.
I'm giving manual installation a shot later today.

Thanks!

**Comment by theriverman** [comment]
Update: I tried installing manually and I found the following lines in the log which might answer my problem:

> invoke-rc.d: initscript nginx, action "start" failed.
> ● nginx.service - A high performance web server and a reverse proxy server
>    Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Thu 2017-02-09 15:28:52 CET; 13ms ago
>      Docs: man:nginx(8)
>   Process: 2596 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=1/FAILURE)
>   Process: 2588 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
> 
> Feb 09 15:28:51 riverman nginx[2596]: nginx: [emerg] listen() to [::]:80, backlog 511 failed (98: Address already in use)
> Feb 09 15:28:51 riverman nginx[2596]: nginx: [emerg] listen() to 0.0.0.0:80, backlog 511 failed (98: Address already in use)
> Feb 09 15:28:51 riverman nginx[2596]: nginx: [emerg] listen() to [::]:80, backlog 511 failed (98: Address already in use)
> Feb 09 15:28:52 riverman nginx[2596]: nginx: [emerg] listen() to 0.0.0.0:80, backlog 511 failed (98: Address already in use)
> Feb 09 15:28:52 riverman nginx[2596]: nginx: [emerg] listen() to [::]:80, backlog 511 failed (98: Address already in use)
> Feb 09 15:28:52 riverman nginx[2596]: nginx: [emerg] still could not bind()
> Feb 09 15:28:52 riverman systemd[1]: nginx.service: Control process exited, code=exited status=1
> Feb 09 15:28:52 riverman systemd[1]: Failed to start A high performance web server and a reverse proxy server.
> Feb 09 15:28:52 riverman systemd[1]: nginx.service: Unit entered failed state.
> Feb 09 15:28:52 riverman systemd[1]: nginx.service: Failed with result 'exit-code'.
> dpkg: error processing package nginx-full (--configure):
>  subprocess installed post-installation script returned error exit status 1

I suppose the root cause of my issue is that I already have an apache2 server running to serve my wordpress site and this nginx (which is maybe a webserver, right?) conflits with it, as they're are trying to listen on the very same port.

I'm not exactly sure how to solve this issue and I'm also not sure whether is this the source of the problem or not. 

Any suggestions or comments?

**Comment by rrjanbiah** [comment]
@theriverman Can you try changing your nginx port to something like 8080 or so.. and access it through that port?

**Comment by theriverman** [comment]
@rrjanbiah I could not find a way to change the port of nginx permamently.
So, for the purpose of testing, I removed apache2 and every related package from my server.

I executed the install script again, it has made it way forward than before, but failed again.

See my latest log attached.

[I can confirm that a running instance of any webserver, such as apache2, conflicts with restyaboard installation]

**Comment by baskar383** [comment]
Sorry for the delayed response. First please run below three commands
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update
Then please run the installation script one more time it will be working

**Comment by lmarikannan** [comment]
@theriverman Please feel free to reopen if you have any issues related to installation.
