### ISSUE TITLE
Nginx Server cannot start

### ISSUE THREAD

**Issue by odac25thka** [RestyaPlatform/board#1012]
Hi I followed the instructions on : http://restya.com/board/docs/windows

However, I cannot get the nginx server to start. The error in the log is 2017/02/07 14:32:06 [emerg] 11000#8532: the unix domain sockets are not supported on this platform in upstream "unix:/run/php/php7.0-fpm.sock" in C:/server/bin/nginx/conf/domains-enabled/restyaboard.conf:35

Do you know what to do? I tried googling and reading every single thread but cannot find any solution. 

I am using windows 7, 64-bit.

I downloaded WPNXM-0.8.6-Full-Setup-php55-w64

**Comment by lmarikannan** [comment]
@odac25thka Can you please try with changing like this?

`fastcgi_pass    127.0.0.1:9000;`

**Comment by odac25thka** [comment]
Hi  lmarikannan, thank you for the change! Nginx Server can start now. However, I followed the rest of the instructions : 

- D:\server\bin\pgsql\bin>createuser -s -d -r postgres D:\server\bin\pgsql\bin>createdb -h localhost -U postgres restyaboard D:\server\bin\pgsql\bin>psql -h localhost -U postgres
- CREATE USER restya WITH PASSWORD 'hjVl2!rGd';ALTER DATABASE restyaboard OWNER TO restya;GRANT ALL PRIVILEGES ON DATABASE restyaboard TO restya;GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO restya;GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO restya;
- D:\server\bin\pgsql\bin>psql -h localhost -d restyaboard -U restya -W < d:\server\www\restyaboard\sql\restyaboard_with_empty_data.sql
- Visit http://localhost/tools/webinterface/index.php?page=config#php-ext to enable curl, gd2, ldap, mobstring, pdo_pgsql, pgsql extensions.
- Start nginx, php, postgresql through WPN-XM Service Control Panel. If they're already running, restart them.
- Restyaboard is up and running at http://localhost:8084/

However, I don't see anything at http://localhost:8084/ or http://localhost:80/. It just redirects me to the WPN-XM overview page.

Not sure how can I proceed. Really appreciate your help so far!

**Comment by odac25thka** [comment]
Update: 

I tried the attached conf file from https://github.com/RestyaPlatform/board/issues/224#issuecomment-184898987

I installed in C drive not D drive tho.

I got this error in the nginx log: 2017/02/08 14:13:16 [error] 10472#10756: *35 CreateFile() "D:/server/www/restyaboard/client/index.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost:8084"
2017/02/08 14:13:44 [notice] 12028#12032: signal process started

I guess the createfile() is the problem but I dunno where that line is

**Comment by odac25thka** [comment]
This is the contents of the conf file:

server {
	listen 80 default_server;
	server_name _;

	root /usr/share/nginx/html;
	index  index.html index.php;

	gzip on;
	gzip_disable "msie6";

	gzip_comp_level 6;
	# gzip_comp_level 9;
	gzip_min_length  1100;
	gzip_buffers 16 8k;
	gzip_proxied any;
	# gzip_http_version 1.1;
	gzip_types       text/plain application/xml text/css text/js text/xml application/x-javascript text/javascript application/json application/xml+rss;

	client_max_body_size 300M;

	rewrite ^/oauth/authorize$ /server/php/authorize.php last;
	rewrite ^/oauth_callback/([a-zA-Z0-9_\.]*)/([a-zA-Z0-9_\.]*)$ /server/php/oauth_callback.php?plugin=$1&code=$2 last;
	rewrite ^/download/([0-9]*)/([a-zA-Z0-9_\.]*)$ /server/php/download.php?id=$1&hash=$2 last;
	rewrite ^/ical/([0-9]*)/([a-z0-9]*).ics$ /server/php/ical.php?id=$1&hash=$2 last;
	rewrite ^/api/(.*)$ /server/php/R/r.php?_url=$1&$args last;
	rewrite ^/api_explorer/api-docs/$ /client/api_explorer/api-docs/index.php last;
		
	location / {
		root /usr/share/nginx/html/client;
	}

	location ~ \.php$ {
		try_files $uri =404;
		include fastcgi_params;
		fastcgi_pass 127.0.0.1:9000;
		fastcgi_index   index.php;
		fastcgi_param	SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PHP_VALUE "upload_max_filesize=9G \n post_max_size=9G \n max_execution_time=200 \n max_input_time=200 \n memory_limit=256M";
	}

	location ~* \.(css|js|less|html|ttf|woff|jpg|jpeg|gif|png|bmp|ico) {
		root /usr/share/nginx/html/client;
		if (-f $request_filename) {
			break;
		}
		rewrite ^/img/([a-zA-Z_]*)/([a-zA-Z_]*)/([a-zA-Z0-9_\.]*)$ /server/php/image.php?size=$1&model=$2&filename=$3 last;
		add_header        Cache-Control public;
		add_header        Cache-Control must-revalidate;
		expires           7d;
	}
}

**Comment by odac25thka** [comment]
Hi,

After restarting the servers a few times, I managed to get to the login page but I cannot log in with "admin" and "restya"

Is there another login or a way to reset the user and password?

**Comment by baskar383** [comment]
Sorry for the delayed response. Login as root using ftp then go to  /etc/nginx/nginx.conf - comment the default server code or please attach your nginx.conf, we will change and update you

**Comment by baskar383** [comment]
Sorry for the delayed response. Here we attach p.txt file please change the filename to p.php then upload in to your project patch then run the file. Your password has been reset then the try username : admin Password : restya
[p.txt](https://github.com/RestyaPlatform/board/files/783252/p.txt)

**Comment by lmarikannan** [comment]
@odac25thka Please feel free to reopen if you have any issues related to installation.

**Comment by Cell20** [comment]
@lmarikannan  I'm on windows 10, using django in venv. I've nginx.conf in the config dir of the project which has this problematic code:
```
upstream educa {
    server      unix:///tmp/educa.sock; 
}
...
```
When I run `.\nginx -s reload` I get the following:
`nginx: [emerg] the unix domain sockets are not supported on this platform in upstream "unix:///tmp/educa.sock" in E:/web development/django/educa/educa/config/nginx.conf:3`

What should i replace for `unix:///tmp/educa.sock`  which works on windows (I've already tried `fastcgi_pass 127.0.0.1:9000;`) :)

**Comment by sridhar391** [comment]
@Cell20 We are not officially supporting the Django and please refer to the below documentation on how to configure the Restyaboard on your windows

- https://restya.com/board/docs/windows/
- https://restya.com/board/docs/manual-installation-windows-wpn-xm/
- https://restya.com/board/docs/windows-iis/
