### ISSUE TITLE
Attachment through camera and sound recorder doesn't work in iPhone

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1016]
Especially in iPhone 6 plus.. file picker works, but not recording (Seems to work in Android phones though)

**Comment by baskar383** [comment]
Sorry for the delayed response. Tested working fine.

**Comment by rrjanbiah** [comment]
Can we arrange recorded video or animated GIF to prove it?

**Comment by baskar383** [comment]
Please check the video url
URL : https://drive.google.com/file/d/0B8b_0XlmnvxjOVc4VXVXZzhMWUU/view
