### ISSUE TITLE
application doesnt appear the login page

### ISSUE THREAD

**Issue by naubergois** [RestyaPlatform/board#102]

**Comment by mishio** [comment]
Same for me in v0.1.5. In the browser debug I notice the following two issues:

api/v1/oauth.json:  502 Bad Gateway

http://www.telize.com/geoip?callback=jQuery18304945791436266769_1449210056454: 404 Not Found

The api/v1/oauth.json path does not exist in the document root and I'm not sure where it is meant to come from.

Also not sure why it is trying to access telize.com but I did notice they have shut down their public api as of November 2015.

**Comment by rrjanbiah** [comment]
@mishio For telize, I have filed different ticket #103 

For your error, can you please check #95? (php-fpm isn't running?) If that's not the case, please add more information about your setup. If you have used our setup script, please attach log file.

**Comment by rrjanbiah** [comment]
@mishio @naubergois Were you able to check #95? Are you able to resolve it?

**Comment by mishio** [comment]
@rrjanbiah thanks for your advice. I am still investigating the nginx / php-fpm status. They appear to be configured and running so I need to dig deeper to find out what is wrong. For reference, the only error in the nginx log is:

2015/12/04 17:20:46 [error] 23716#0: *32 connect() failed (111: Connection refused) while connecting to upstream, client: 172.xx.xxx.93, server: 172.xx.xxx.16, request: "GET /api/v1/oauth.json?_=1449210056482 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "172.xx.xxx.16", referrer: "http://172.xx.xxx.16/"

I did not use your setup script as I am attempting to install on Ubuntu (Debian based). I am manually performing the install using your script as a guide.

**Comment by mishio** [comment]
Yes, your are correct, there was a problem with the php-fpm. This is resolved by modifying the fpm configuration as instructed at the link below, ie:

/etc/php5/fpm/pool.d/www.conf
listen = 9000
listen.allowed_clients = 127.0.0.1

http://stackoverflow.com/questions/21524373/nginx-connect-failed-111-connection-refused-while-connecting-to-upstream

I now get error 404 Not Found instead of 502 Bad Gateway, however I suspect this is a separate issue related to my PostGres set up.

**Comment by mishio** [comment]
FYI 404 issue resolved too.  The problem was permissions on the config.inc.php file resulted in the edits not being allowed. I forced the changes into the file, restarted the postgresql service and the login screen now appears!

**Comment by chonsanova** [comment]
Hi guys,
Any simpler instructions for fixing this? I'm getting 404 error when I going to domain/restyaboard, and getting a white 'login' page going to domain/restyaboard/client.
What are the steps to fix?
Thanks

**Comment by mishio** [comment]
@chonsanova, there are many reasons why you might get 404.  In my case the lines in the restyaboard.sh script could not update config.inc.php (/usr/share/nginx/html/server/php/R/config.inc.php) so I edited the file myself, changing the following lines:

define('R_DB_HOST', '');
define('R_DB_USER', '');
define('R_DB_PASSWORD', '');
define('R_DB_NAME', '');
define('R_DB_PORT', '');

to something like this:

define('R_DB_HOST', 'localhost');
define('R_DB_USER', 'user_name');
define('R_DB_PASSWORD', 'password');
define('R_DB_NAME', 'database_name');
define('R_DB_PORT', '5432');

Once saved, restart php and Bob's your uncle:
sudo service php5-fpm restart

**Comment by rrjanbiah** [comment]
@mic704b @chonsanova @naubergois 


Closing this now. If you are still facing issue, please feel free to reopen.
