### ISSUE TITLE
Install failed on CentOS 6.8 

### ISSUE THREAD

**Issue by vClouds** [RestyaPlatform/board#1021]
lsb-release issue at the beginning
solved by manual install, yum install redhat-lsb-core

and ended with the default nginx page with the below error,
Starting php-fpm: [10-Feb-2017 07:51:26] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/geoip.so' - /usr/lib64/php/modules/geoip.so: cannot open shared object file: No such file or directory in Unknown on line 0
[restyaboard_install2.log.txt](https://github.com/RestyaPlatform/board/files/765658/restyaboard_install2.log.txt)

**Comment by baskar383** [comment]
Sorry for the delayed response. Login as root using ftp then go to /etc/nginx/nginx.conf - comment the default server code or please attach your nginx.conf, we will change and update you

**Comment by lmarikannan** [comment]
@vClouds Please feel free to reopen if you have problem again in installation.
