### ISSUE TITLE
Email notification not working

### ISSUE THREAD

**Issue by aleromano89** [RestyaPlatform/board#1027]
I don't receive email notification about new cards added.
How can I debug this issue?

this is my content template, that is the default template --> [html code]( http://txt.do/d1zhl)

EDIT: furthermore, notification about new board users are correctly sent and received.

**Comment by baskar383** [comment]
login as root using putty or terminal. Enter crontab -l the cron listing shown please check the give below two url is present or not, if not present please enter crontab -e and paste the two url and save then check.
*/5 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/instant_email_notification.sh
0 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/periodic_email_notification.sh

**Comment by aleromano89** [comment]
the two url you have written are already present

**Comment by aleromano89** [comment]
I have tried just now to manually execute instant_email_notification.sh and I received the email.
Could be it depend on wrong cron configuration?

**Comment by rrjanbiah** [comment]
@aleromano89 Perhaps your cron user doesn't have permission to execute it?

**Comment by aleromano89** [comment]
the cron was assigned to root user and not executed.
Instead if a try to copy cronjob to a simple user, there is a permissions issue
`mkdir: cannot create directory ‘/usr/share/nginx/html/restyaboard/server/php/shell/instant_email_notification_sh.lock’: Permission denied
`

**Comment by rrjanbiah** [comment]
@aleromano89 Does it mean that you're able to get it working now?

**Comment by aleromano89** [comment]
I solved by changing sh owner and shell directory owner to non-root user

**Comment by rrjanbiah** [comment]
@aleromano89 Thanks. Glad to know that.

**Comment by rrjanbiah** [comment]
@lmarikannan Please add it for fixing install script

**Comment by baskar383** [comment]
Sorry for the delayed response. we already given all permission only for root users some rare cases this error will occur better way if the permission issue occur put in to manually to fix the issue.
