### ISSUE TITLE
Unable to find user to add to Organization

### ISSUE THREAD

**Issue by DeviantEng** [RestyaPlatform/board#1028]
New user, new install, manual install (not with the script -- couldn't get that working on CentOS 7).  I'm using CentOS 7, latest version of Nginx, PHP 7.1, postgres 9.5.  

Everything seems to be working great, except for 1 small issue (only thing I've noticed so far).  

I have 2 users, user1 and user2.  user1 is an admin, user2 is a user.  

As user1, I've created a new organization (called test_org), created a board within that org, and user1 is the only member (and owner) of the org. 

So I want to add user2 to the org, so I browse to the organizations, click on my org, and go to the `Members` tab.  I click `+ Add Member` and start typing the username.  The username never pops up.  Even if I type the full name and hit enter, nothing happens.  So far I have been completely unable to add a member to an organization (or even a board).  

No errors in my browser console (Chrome), nothing in my nginx error log, and I'm not sure where else to look.

Any ideas?  Possible that I'm missing a php module or some sort?

**Comment by baskar383** [comment]
Kindly please check  whether the user2 is active and email is confirmed. Then only the user will show in add member search box otherwise it will show "no users available". If already activated please check in network tab enter the username in search box copy the search.json API call response give to us we will check and update you.

**Comment by DeviantEng** [comment]
Thanks @baskar383, sounds like I found my issue.  In my initial setup (for testing), I did not configure email notifications.  I manually approved each user, but they are still listed as unconfirmed.  

Is there a manually way to change this?  I assume it could be manually changed in the database, but is there another way?  I won't have email setup in my testing environment.

**Comment by DeviantEng** [comment]
As a test, I've changed `is_emailed_confirmed` to `true` in the database for both of these users, but in the Users page in the UI, it still shows that both are `Unconfirmed`.  What do?

**Comment by baskar383** [comment]
Added this email confirmed feature in this commit 5232159 we will release this feature in next update.
