### ISSUE TITLE
Webserver configuration error

### ISSUE THREAD

**Issue by virtualCHgeek** [RestyaPlatform/board#1038]
Hi,

I tried the auto install script now 3 times. I've made a snapshot on my Ubuntu 16.

Everytime i face the default webserver page after the script. Is this a normal behaviour and do i have to configure NGINX manually ?

[restyaboard_install.txt](https://github.com/RestyaPlatform/board/files/789462/restyaboard_install.txt)

**Comment by lmarikannan** [comment]
@virtualCHgeek Login as root in SSH then run this command `vi /etc/nginx/nginx.conf` and comment the default server code or please attach your `nginx.conf`, we will change and update you.

**Comment by virtualCHgeek** [comment]
Here my nginx.conf.

Thank you very much for your help
[nginx.conf.txt](https://github.com/RestyaPlatform/board/files/789734/nginx.conf.txt)

**Comment by lmarikannan** [comment]
@virtualCHgeek We have checked your there is no default server configuration in `nginx.conf`.

Can you please check whether any other configuration files available in the below folder except `restyaboard.conf`?

1. `/etc/nginx/conf.d`
2. `/etc/nginx/sites-enabled/`

**Comment by virtualCHgeek** [comment]
In /etc/nginx/conf.d i have : nginx.conf
In /etc/nginx/sites-enabled/ i had a default which i deleted after the install

[nginx.conf.txt](https://github.com/RestyaPlatform/board/files/789825/nginx.conf.txt)

**Comment by lmarikannan** [comment]
> In /etc/nginx/conf.d i have : nginx.conf

Means can you please confirm `nginx.conf` available in two folders in your server?

1. `/etc/nginx`
2. `/etc/nginx/conf.d`

**Comment by virtualCHgeek** [comment]
in /etc/nginx -> there is nginx.conf
in /etc/nginx/conf.d -> there is restyaboard.conf

![image](https://cloud.githubusercontent.com/assets/25195817/23161862/059f369a-f82c-11e6-8205-ada96bb07b3b.png)
![image](https://cloud.githubusercontent.com/assets/25195817/23161875/158d597e-f82c-11e6-95fb-a7f63f9e25e3.png)

**Comment by baskar383** [comment]
Are still facing restyaboard installation issue. If yes means feel free to contact this page : http://restya.com/contact?category=free-installation
