### ISSUE TITLE
Bug in elasticsearch and search result

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1040]
We use last restyaboard version 4.2.1

We use elasticsearch 5.2.1, and don't work with your plugin, after some var_dump, I find that :

$data['aggs']['board']['terms']['size'] = 0;  // can't be zero in 5.2.1 (give me error)
$data['aggs']['board']['terms']['size'] = 999; // change for this, work great

Also, in search "Matched in x cards", I can click one result, open modal. But second click on card result receive json result, but don't open (maybe async problem).

**Comment by baskar383** [comment]
Fixed our local server
