### ISSUE TITLE
[QA] Confirmation mail is not coming after create the new user.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1041]
http://boarddev.demo.restya.com/

1.View the Register page.
2.Create one new user.
3.After create the user Activation mail is not coming.
4.After activate via admin also not able to login the site with registered user.
5.User is showing like Unconfirmed.
![confirmation mail](https://cloud.githubusercontent.com/assets/25973905/23248598/1c0a9b18-f9c6-11e6-9d49-ded22cab12ae.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
