### ISSUE TITLE
[QA] Private Board view page details is not coming properly before login.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1042]
1.Login as sridevi/agriya.
2.Add one private board.
3.View that board before login.
4.Private Board view page details is not coming properly before login.

Refer the screenshot.
![private board](https://cloud.githubusercontent.com/assets/25973905/23254317/a0926610-f9dd-11e6-8bfb-acd053e60863.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
