### ISSUE TITLE
[QA] After view the card if we view the Apps means that time Apps details is not coming properly.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1043]
http://boarddev.demo.restya.com/

1.Login as sridevi/agriya.
2.View the Card view page.
3.In the Card view page click the Footer Apps.
4.Here the Apps details is not coming properly.

Refer the screenshot.
![apps](https://cloud.githubusercontent.com/assets/25973905/23255075/3d591370-f9e0-11e6-8a00-2d0b9b295cb5.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb

**Comment by baskar383** [comment]
https://github.com/RestyaPlatform/board/issues/1067

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
