### ISSUE TITLE
[QA] Activation popups coming more than one time for every actions.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1044]
http://boarddev.demo.restya.com/

1.Login as sridevi/agriya.
2.Do some process like comment,Move list,...
3.Activation popups coming more than one time for every actions.

Refer the screenshot
![activation popup](https://cloud.githubusercontent.com/assets/25973905/23255174/90ce6c3a-f9e0-11e6-9057-85b64bdb01e2.png)

**Comment by baskar383** [comment]
This is not an issue. This popup made on browser action.
