### ISSUE TITLE
[QA] User information is not coming properly while view the user logo.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1045]
http://boarddev.demo.restya.com/

1.Login as sridevi/agriya.
2.View one Card.
3.From card view page click the user logo.
4.User information is not coming properly while view the user logo.

Refer the screenshot.
![user info](https://cloud.githubusercontent.com/assets/25973905/23256101/0bf0f560-f9e4-11e6-93a3-0ad18a3a5415.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
