### ISSUE TITLE
[QA] After delete the members "Add Members" option is not coming.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1046]
http://boarddev.demo.restya.com/

1.login as sridevi/agriya.
2.View the members listing place.
3.Delete the members.
4.After Delete "Add members" option is not coming.

Refer the screenshot.
![add member](https://cloud.githubusercontent.com/assets/25973905/23256435/78a06636-f9e5-11e6-9d54-ea2bc1b92382.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
