### ISSUE TITLE
[QA] Members list is displaying after remove from the list.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1047]
http://boarddev.demo.restya.com/

1.login as sridevi/agriya.
2.View the members listing place.
3.Delete the members.
4.And Refresh the page.
5.Now deleted members is displaying after remove from the list.

Refer the screenshot.
![members list](https://cloud.githubusercontent.com/assets/25973905/23256863/492ea2d0-f9e7-11e6-9c0e-14bed4d9d58a.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
