### ISSUE TITLE
[QA] Need Margin space between setting list.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1048]
http://boarddev.demo.restya.com/

1.Login as sridevi/agriya.
2.View one board details page.
3.Click the list settings.
4.Need Margin space between setting list.

Refer the screenshot.
![margin space](https://cloud.githubusercontent.com/assets/25973905/23257612/a82e0926-f9ea-11e6-8ee1-601db29d1963.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
