### ISSUE TITLE
[QA] Card Alignment is not coming properly.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1049]
http://boarddev.demo.restya.com/

1.Login as sridevi/agriya.
2.View the Card.
3.Here the alignment is not coming properly.

Refer the screenshot.
![alignment](https://cloud.githubusercontent.com/assets/25973905/23257759/336a0468-f9eb-11e6-8113-60e21666285e.png)

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/d9fe36a421f283a3dfe51ec3e4686db3d873c4f4
