### ISSUE TITLE
[QA] Start date details is not coming here.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1052]
http://boarddev.demo.restya.com

1.Login as sridevi/agriya.
2.View the Board view page.
3.Here the Start date details is not coming properly.

Refer the screenshot.
![start time](https://cloud.githubusercontent.com/assets/25973905/23259464/3a66c3e8-f9f3-11e6-9401-e49ca2c7ce07.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
