### ISSUE TITLE
[QA] Estimated time is not updated properly.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1053]
1.Login as sridevi/agriya.
2.View the Board view page.
3.Here add the Estimated time for that Board.
4.Added time is not updated properly while view after add.

Refer the screenshot.
![estimated time](https://cloud.githubusercontent.com/assets/25973905/23259677/38d75370-f9f4-11e6-98b7-f4e3f2353bd1.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
