### ISSUE TITLE
[QA] Smiley is not updated properly after add.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1054]
http://boarddev.demo.restya.com/

1.Login as sridevi/agriya.
2.View the Board view page.
3.Add checklist for that board.
4.Add Emoji's for that checklist.
5.Added Emoji is not updated immediately.

Refer the screenshot.
![smiley](https://cloud.githubusercontent.com/assets/25973905/23260129/6560679a-f9f6-11e6-83cb-7d1c5b46691d.png)

**Comment by baskar383** [comment]
Fixed in this commit f17bbd8
