### ISSUE TITLE
[QA] Alignment is not coming properly.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1055]
http://boarddev.demo.restya.com/

1.Login as sridevi/agriya.
2.View the Board listing page and view the checklist.
3.Add member for that checklist.
4.Here the alignment is not coming properly.

Refer the screenshot.
![alignment1](https://cloud.githubusercontent.com/assets/25973905/23260273/fd3b6d4e-f9f6-11e6-92c7-4758902a9d85.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
