### ISSUE TITLE
[QA] Copied list details is not coming properly.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1056]
http://boarddev.demo.restya.com/

1.Login as sridevi/agriya.
2.View the Board view page.
3.Copy the list.
4.Copied list details is not coming properly.

Refer the screenshot.
![copied list details](https://cloud.githubusercontent.com/assets/25973905/23261362/e6acc7f8-f9fb-11e6-9fbf-5910080948d3.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
