### ISSUE TITLE
[QA] Space is not coming properly.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1057]
http://boarddev.demo.restya.com/

1.Login as sridevi/agriya.
2.View the Board details page.
3.Here the Date and time space alignment is not coming properly.

Refer the screenshot.
![space](https://cloud.githubusercontent.com/assets/25973905/23261479/4caf1cf4-f9fc-11e6-9876-6f46472590ca.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
