### ISSUE TITLE
[QA] After refresh the page deleted list's are again displaying.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1058]
1.Login as sridevi/agriya.
2.View the Board view page.
3.Copy the list.
4.Delete the Copied lists.
5.After refresh the page deleted list's are again displaying.

Refer the screenshot.
![deleted list](https://cloud.githubusercontent.com/assets/25973905/23291960/0df3f710-fa82-11e6-9f40-95c70ef93c54.png)

**Comment by banandam** [comment]
fixed

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
