### ISSUE TITLE
[QA] While copy the list,that time card count is increasing.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1059]
1.Login as sridevi/agriya.
2.View the board view page.
3.Copy the list-> While copy the list,that time card count is increasing.

Refer the screenhsot.
![card count](https://cloud.githubusercontent.com/assets/25973905/23292876/ab5b4f48-fa88-11e6-87ae-30b64b086f75.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
