### ISSUE TITLE
The 'Add a card' link at bottom of list disappears

### ISSUE THREAD

**Issue by mic704b** [RestyaPlatform/board#106]
To reproduce in v0.1.5:

Click "Add a card" at the bottom of a list
Enter some text into the new card
Click the "Add" button
Click directly on the card just added
Add a label to the card

Result: the "Add a card" link at the bottom of the list disappears. The page must be reloaded to get it back.

Expected: the "Add a card" link at the bottom of the list remains visable.

**Comment by ssivachidambaram** [comment]
Fixed in v0.1.6.
