### ISSUE TITLE
[QA] Gantt view page design is not coming properly.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1060]
1.Login as sridevi/agriya.
2.View  the Gantt view page.
3. Here the page design is not coming properly.

Refer the screenshot.
![gantt view page](https://cloud.githubusercontent.com/assets/25973905/23292921/f8a1d27c-fa88-11e6-9a03-a96f71ca79b5.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
