### ISSUE TITLE
[QA] while add the productivity beats it is allowing blank space as input.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1061]
1.Login as sridevi/agriya.
2.In board view page==>click corner setting icon==>select change back ground menu
3.In that menu click "Productivity Beats" add page==>Enter the empty space and click submit button
4.Got an successfully updated message.

Refer the screenshots.
![beat1](https://cloud.githubusercontent.com/assets/25973905/23293202/eb3817ca-fa8a-11e6-8d5a-daa34a913887.png)
![beat2](https://cloud.githubusercontent.com/assets/25973905/23293201/eb31f6d8-fa8a-11e6-943d-24212fc7f243.png)

**Comment by baskar383** [comment]
Fixed in this commit f17bbd8
