### ISSUE TITLE
[QA] Delete popup alignment is not coming properly.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1062]
1.Login as sridevi/agriya.
2.view the Board list activities.
3.Add emoji for that list.
4.click the Emoji Delete button.
5.Delete popup alignment is not coming properly.

Refer the screenshot.
![delete popup](https://cloud.githubusercontent.com/assets/25973905/23294994/4ceb111c-fa94-11e6-81af-375a209d2af2.png)

**Comment by lmarikannan** [comment]
Fixed on this commit d9fe36a
