### ISSUE TITLE
[QA] Emoji alignment is not coming properly.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1063]
1.Login as sridevi/agriya.
2.view the Board list activities.
3.Add emoji for that list.

Refer the screenshot.
![emoji alignment](https://cloud.githubusercontent.com/assets/25973905/23295124/f1c4617a-fa94-11e6-965a-1ddd10a8be85.png)

**Comment by lmarikannan** [comment]
Fixed on this commit d9fe36a
