### ISSUE TITLE
[QA] Labels add option is not coming properly while view the card.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1064]
1.Login as sridevi/agriya.
2.View the card details page.
3.Here the Labels add option is not coming properly.

Refer the screenshot.
![labels add](https://cloud.githubusercontent.com/assets/25973905/23295336/11f17b8a-fa96-11e6-9ce2-3fe9aaeac140.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
