### ISSUE TITLE
[QA] After close the board if we add the instant card means that time it is accepting to add.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1065]
1.Login as sridevi/agriya.
2.Add one card by using "Instant card add" with closed Board.
3.After close the board if we add the instant card means that time it is accepting to add.
![instant card add](https://cloud.githubusercontent.com/assets/25973905/23301577/9b001890-fab0-11e6-81c4-ab8a287c65a6.png)
![instant card add1](https://cloud.githubusercontent.com/assets/25973905/23301608/c44132de-fab0-11e6-9ef6-b5acefbb42fd.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
