### ISSUE TITLE
[QA] Instant add card accepting white space as a input.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1066]
1.Login as sridevi/agriya.
2.View "Instant card add".
3.Give the inputs as space.
4.That time Instant add card accepting white space as a input.
![instant card add2](https://cloud.githubusercontent.com/assets/25973905/23301696/2d35af72-fab1-11e6-9191-20de426a3368.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
