### ISSUE TITLE
[QA] From Closed Board ->Reopen popup design is not showing properly.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1067]
1.Login as sridevi/agriya.
2.From Closed Board ->Reopen popup design is not showing properly.
![reopen](https://cloud.githubusercontent.com/assets/25973905/23301737/657e422c-fab1-11e6-9310-1faa39841efa.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
