### ISSUE TITLE
[QA] Closed Board names also displaying in the "Instant add card" page.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1068]
1.Login as sridevi/agriya.
2.View the "Instant Add Card" option.
3.Here from Select Board->Closed Board names also displaying.

![instant card add](https://cloud.githubusercontent.com/assets/25973905/23301808/cc314e06-fab1-11e6-8819-509be18bc1e2.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
