### ISSUE TITLE
[QA] After close the board page should redirect to Home page.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1069]
1.Login as sridevi/agriya.
2.Create one Board.
3.Delete the Board from list.
4.After delete it is showing the "Reopen the board" option.
5.If we are not Reopen means,after some time page should redirect to Home page.

![close board](https://cloud.githubusercontent.com/assets/25973905/23302688/cb3e5102-fab5-11e6-9f2a-94b7755330fe.png)

**Comment by baskar383** [comment]
In trello they are not redirect after board close redirect to home page
