### ISSUE TITLE
[QA] Load more card design is not coming properly.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1070]
1.login as sridevi/agriya.
2.View the Home page Unassigned option.
3.Unassigned page "Load more" option design is not coming properly.

Refer the screenshot.
![load more](https://cloud.githubusercontent.com/assets/25973905/23303892/c2f59a62-fabc-11e6-85f3-1e5f135b7212.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
