### ISSUE TITLE
[QA] Not able to view the organization from home page.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1071]
1.Login as sridevi/agriya.
2.From Home page click the organization list.
3.view the organization.
4.That time not able to view the organization.
![organization](https://cloud.githubusercontent.com/assets/25973905/23304487/147965e6-fac0-11e6-94c0-5150208d9693.png)

**Comment by baskar383** [comment]
Fixed in this commit f17bbd8
