### ISSUE TITLE
[QA] We can able to create with empty space in name field while copy the board.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1073]
1.login as sridevi/agriya.
2.select any board from dashboard==>In card list page==>click the corner setting icon
3.select the copy board option==>enter the space in name field and click create button
4.Its successfully created.

![empty space-board](https://cloud.githubusercontent.com/assets/25973905/23350275/7cc06246-fcdf-11e6-8b3f-29f39179ad68.png)
![empty space-board1](https://cloud.githubusercontent.com/assets/25973905/23350276/7cc1a8cc-fcdf-11e6-90e1-36989718d6f1.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
