### ISSUE TITLE
[QA] While view the organization corresponding view page is not coming properly.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1074]
1.Login as sridevi/agriya.
2.From organization listing page view one organization.
3.While view the organization corresponding view page is not coming properly.

Refer the screenshot.
![organization](https://cloud.githubusercontent.com/assets/25973905/23350479/de2b0e68-fce0-11e6-9f81-8244a23c78cf.png)

**Comment by baskar383** [comment]
Fixed in this commit f17bbd8
