### ISSUE TITLE
[QA] While hover Tooltip is not coming properly in the organization page.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1075]
1.Login as sridevi/agriya.
2.View the organization list page.
3.Hover the organization list.
4.While hover Tooltip is not coming properly in the organization page.

Refer the screenshot.
![tooltip](https://cloud.githubusercontent.com/assets/25973905/23350984/585b5208-fce4-11e6-8312-d0f4a5100589.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
