### ISSUE TITLE
[QA] After add the organization page should redirect to organization listing page.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1076]
1.Login as sridevi/agriya.
2.Add one new organization.
3.After add the organization page should redirect to organization listing page.
4.But the page is redirecting into board listing page.

Refer the screenshot.

![org list](https://cloud.githubusercontent.com/assets/25973905/23351117/3357a9ba-fce5-11e6-8dfd-438fb2af43ed.png)

**Comment by baskar383** [comment]
Fixed in this commit f17bbd8
