### ISSUE TITLE
[QA] Alignment is not coming properly for Add Emoji and Mention a member option.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1077]
1.Login as sridevi/agriya.
2.View the Board.
3.And add the comment for that board.
4.From comment page-> Add Emoji and Mention a member.
5.Here the alignment is not coming properly.

Refer the screenshot.

![alignment](https://cloud.githubusercontent.com/assets/25973905/23356626/8ae08f42-fd00-11e6-92ea-3e9c7e6dbc6a.png)

**Comment by lmarikannan** [comment]
Fixed on this commit d9fe36a
