### ISSUE TITLE
[QA] While copy the list if we give the empty space means that time page  accepting the space as input.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1078]
1.Login as sridevi/agriya.
2.View the Board listing page.
3.Copy the Board.
4.While copy the list if we give the empty space means that time page  accepting the space as input.

Refer the screenshot.

![space input](https://cloud.githubusercontent.com/assets/25973905/23356831/5f4b4f1a-fd01-11e6-917e-eded0dab11d7.png)

**Comment by baskar383** [comment]
Fixed in this commit 1311f83
