### ISSUE TITLE
[QA] Copy list details is not coming properly and  not able to delete the copied list.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1079]
1.Login as sridevi/agriya.
2.View the Board listing page.
3.Copy the list.
4.Click the copied list settings.
5.Not able to delete the copied list.

Refer the screenshot.
![delete copy list](https://cloud.githubusercontent.com/assets/25973905/23357293/32dc530a-fd03-11e6-9267-3018e39e209c.png)

**Comment by baskar383** [comment]
Fixed in this commit  d0c6b9c
