### ISSUE TITLE
can share calendar from my server (restyaboard) to my friend?

### ISSUE THREAD

**Issue by manuelsongokuh** [RestyaPlatform/board#108]
hello
i will install restyaboard on my server (opensuse).

it's can shares
from the calendar of Tom (account of restyaboard)
to Ross (account of restyaboard)?

2 accounts are from same server (opensuse).

**Comment by ssivachidambaram** [comment]
Can you please provide more details?

**Comment by manuelsongokuh** [comment]
ok, my poor english sorry me.

first i did go to site demo of restyaboard: i cant add my event to calendar, this is problem? maybe it's read only from google calendar?

i dont want to use to google calendar...i want to calendar original from restyaboard, this will be can share my friends (account of restyaboard) (permission: read, write, full editable)

maybe will needs new feature for restyaboard? so need:
icalendar (ics)and use the protocol of caldav, right?

**Comment by ssivachidambaram** [comment]
Currently we have an option to import boards card in Google calendar. We don't have an option to import existing ical feeds into the board.

**Comment by rrjanbiah** [comment]
@manuelsongokuh Closing this for now. If above reply is not helpful, please reopen with more details.
