### ISSUE TITLE
[QA] While add the Productivity beat that time it is accepting the space as input.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1080]
1.Login as sridevi/agriya.
2.View one board.
3.From settings view the Productivity settings add productivity beat.
4.While add the Productivity beat that time it is accepting the space as input.
![pro input-space](https://cloud.githubusercontent.com/assets/25973905/23360957/28ad5eea-fd14-11e6-9635-2919fa61d6c5.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
