### ISSUE TITLE
[QA] We can able to create organization with out description.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1081]
1.login as sridevi/agriya.
2.Create one organization ==>while creating do not enter the data in description field and click add button
3.It successfully added.
![description](https://cloud.githubusercontent.com/assets/25973905/23447679/8f5801fe-fe72-11e6-868d-5bb703a49426.png)

**Comment by baskar383** [comment]
Fixed in this commit 7a004a2
