### ISSUE TITLE
[QA] Card accepting the Empty space.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1082]
1.Login as sridevi/agriya.
2.View the Board view page.
3.Edit the card -> While edit give the empty space as input.
4.Card accepting the Empty space.

Refer the screenshot.
![empty space](https://cloud.githubusercontent.com/assets/25973905/23448246/cef7c378-fe75-11e6-80e6-74a36ead0c42.png)

**Comment by baskar383** [comment]
Fixed in this commit d0c6b9c
