### ISSUE TITLE
[QA] After delete the copied list,not able to copy the previous list.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1083]
1.Login as sridevi/agriya.
2.View the Board view page.
3.Copy the list-> Delete the copied list.
4.After delete the copied list,not able to copy the previous list.

Refer the screenshot.

![copy list](https://cloud.githubusercontent.com/assets/25973905/23449136/f1626652-fe7a-11e6-872a-1f56cc13a46d.png)

**Comment by baskar383** [comment]
Fixed in this commit d0c6b9c
