### ISSUE TITLE
[QA] Spelling is not coming correctly after subscribe.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1084]
1.Login as sridevi/agriya.
2.View the Board view page.
3.Click the list settings-> Subscribe the list.
4.Spelling is not coming correctly after subscribe.

Refer the screenshot.
![spelling](https://cloud.githubusercontent.com/assets/25973905/23449208/5e63a36a-fe7b-11e6-9305-dfd8c3870508.png)

**Comment by baskar383** [comment]
Fixed in this commit 1333a7f
