### ISSUE TITLE
[QA] Empty space accepting in change password fields.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1085]
1.login as sridevi/agriya
2.Go to change password==>enter the space in "enter a new password" and "confirm password" and click change password button==>It is accepting.

Refer the screenshot.
![change password](https://cloud.githubusercontent.com/assets/25973905/23453043/cdd77580-fe8c-11e6-9f5f-5c3f6bb470c9.png)

**Comment by baskar383** [comment]
Fixed in this commit bed2340
