### ISSUE TITLE
[QA] "Undo" option is not coming after update card name.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1086]
1.Login as sridevi/agriya.
2.View the Board view page->And view the card.
3.Edit and update the card name.
4."Undo" option is not coming after update card name.

Refer the screenshot.

![undo](https://cloud.githubusercontent.com/assets/25973905/23456145/437dd936-fe98-11e6-9438-cbf9cecc79b2.png)

**Comment by baskar383** [comment]
Fixed in this commit d0c6b9c
