### ISSUE TITLE
[QA] Due date accepting the past dates.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1087]
1.Login as sridevi/agriya.
2.View the Board view page ->View the card page.
3.Add Due date with past dates.
4.That time Due date accepting the past dates.

Refer the screenshot.

![due date](https://cloud.githubusercontent.com/assets/25973905/23456372/30cfae30-fe99-11e6-81f5-fac9e427e2f6.png)

**Comment by baskar383** [comment]
This not an issue trello also as same feature
