### ISSUE TITLE
 [QA] If we try to click user details or Instant card or Activities on card view page, design is not displaying Properly.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1088]
1. Login as User.
2. Select any board from dashboard page.
3. Now select any card from the list.
4. Now clicky the activities icon.
5. If we try to click user details or Instant card or Activities on card view page, design is not displaying Properly.

Refer the screenshot.

![design1](https://cloud.githubusercontent.com/assets/25973905/23456790/ea0abe8e-fe9a-11e6-8679-7fc12ee04758.png)
![design2](https://cloud.githubusercontent.com/assets/25973905/23456791/ea0bb924-fe9a-11e6-981a-e76e9336a50a.png)

**Comment by lmarikannan** [comment]
Fixed on this commit d9fe36a
