### ISSUE TITLE
Cannot edit text of checklist item

### ISSUE THREAD

**Issue by mic704b** [RestyaPlatform/board#109]
In v0.1.5 using Firefox browser, to reproduce:

Open a card with a check list
Click on the text of a check list item
A text box is presented containing the checklist item text and a Save button below.
Click in the text box and enter more characters

Result: Nothing happens, the text cannot be edited

Expected: The new characters appear in the text box and the checklist item is updated when Save is clicked.

**Comment by ssivachidambaram** [comment]
Fixed in v0.1.6.
