### ISSUE TITLE
[QA] Tooltip is not coming properly while we hover the user icon in the board view page.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1091]
1.Login as sridevi/agriya.
2.View the Board view page-> View the card details page.
3.Tooltip is not coming properly while we hover the user icon in the board view page.

Refer the screenshot.

![tooltip](https://cloud.githubusercontent.com/assets/25973905/23460776/07ac4996-fead-11e6-99c0-f4335f41dce8.png)

**Comment by baskar383** [comment]
Fixed in this commit b1688eb
