### ISSUE TITLE
[QA] Close button is not working properly in settings share and More option.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1092]
1.Login as sridevi/agriya.
2.View the Board view page-> View the card details page.
3.View the settings-Share and More option.
4.Close button is not working properly.

Refer the screenshot.

![close button](https://cloud.githubusercontent.com/assets/25973905/23460930/ad7c2436-fead-11e6-8744-2bce3362ed5f.png)

**Comment by baskar383** [comment]
Fixed in this commit d0c6b9c
