### ISSUE TITLE
[QA] Share option is not showing properly in the Share and More Field.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1093]
1.Login as sridevi/agriya.
2.View the Board view page-> View the card details page.
3.View the settings-Share and More option.
4.For share No Option is displaying here.

Refer the screenshot.

![share option](https://cloud.githubusercontent.com/assets/25973905/23461137/a44542e8-feae-11e6-814e-7192f8c1c2f9.png)

**Comment by baskar383** [comment]
This not an issue
