### ISSUE TITLE
[QA] While add the SEO checklist failed message is coming 

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1094]
1.Login as sridevi/agriya.
2.View the Footer Apps.
3.From Footer Apps choose the SEO checklist ->Then add the SEO checklist.
4.While add the SEO checklist failed message is coming.

Refer the screenshot.
![seo checklist](https://cloud.githubusercontent.com/assets/25973905/23495005/4aa4ffa6-ff3c-11e6-9d81-7e41c1714885.png)

**Comment by baskar383** [comment]
Fixed
