### ISSUE TITLE
[QA] While add the Website QA checklist failed message is coming.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1095]
1.Login as sridevi/agriya.
2.View the Footer Apps.
3.From Footer Apps choose the Website QA checklist ->Then add the Website QA checklist.
4.While add the Website QA checklist failed message is coming.

Refer the screenshot.
![website qa checklist](https://cloud.githubusercontent.com/assets/25973905/23495206/5cfd8c26-ff3d-11e6-83c7-efe4697119e1.png)

**Comment by baskar383** [comment]
Fixed.
