### ISSUE TITLE
[QA] LDAP option is not working properly after Enable.

### ISSUE THREAD

**Issue by sriagriya** [RestyaPlatform/board#1096]
1.Login as sridevi/agriya.
2.After Enable the LDAP from admin side,it is not working in user End.

Refer the screenshot.
![ldap login](https://cloud.githubusercontent.com/assets/25973905/23496393/ee958dfe-ff43-11e6-8e2d-26a91f2ef14c.png)

**Comment by lmarikannan** [comment]
Fixed on this commit ee265f7.
