### ISSUE TITLE
Unable to install the restyaboard using the installation steps.(http://restya.com/board/install) in Ubuntu 16.04.1 LTS

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#1098]
In ubuntu os, unable to install the restyaboard. 

ahsan@ahsan:/usr/share/nginx/html$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

I have attached the  restyaboard.sh log file. Installation not done successfully. It displayed error as "428: ./restyaboard.sh: cannot open 9.3: No such file
+ [[ 9.5 ]]
./restyaboard.sh: 428: ./restyaboard.sh: [[: not found
./restyaboard.sh: 449: ./restyaboard.sh: cannot open /etc/postgresql/9.4/main/pg_hba.conf: No such file
+ sed -e s/peer/trust/g -e s/ident/trust/g
+ cd /etc/postgresql/9.4/main
./restyaboard.sh: 450: cd: can't cd to /etc/postgresql/9.4/main
+ exit
"

Refer the attachment.

[restyaboard_install_issue.txt](https://github.com/RestyaPlatform/board/files/820346/restyaboard_install_issue.txt)

**Comment by baskar383** [comment]
Fixed in this commit 9cb4527
