### ISSUE TITLE
Undefined variable: is_beyond_original

### ISSUE THREAD

**Issue by ericchu630** [RestyaPlatform/board#110]
2015/12/17 10:46:27 [error] 1873#0: *1607 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: is_beyond_original in /usr/share/nginx/html/server/php/R/image.php on line 72" while reading response header from upstream, client: xxxx, server: xxxx, request: "GET /img/normal_thumb/User/1.d0540a414364f7ffa6dab1da492d4e74.jpg HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:"

**Comment by ssivachidambaram** [comment]
Fixed in v0.1.6.
