### ISSUE TITLE
Standard login/register settings not working

### ISSUE THREAD

**Issue by lmarikannan** [RestyaPlatform/board#1106]
I'm looking for a way to disable the "Register" function in Restyaboard or atleast Remove the button from the login page. Under Admin/Settings/System i see a tickbox "Standard login/register", but it does nothing and upon reloading the page it gets activated

**Comment by theriverman** [comment]
Hi,

Untick Register under Admin/Roles -- Guest column. See picture attached:

![register](https://cloud.githubusercontent.com/assets/22156894/23674964/08267764-0378-11e7-9a40-47cae1ce574e.jpg)

/Riverman

**Comment by lmarikannan** [comment]
@theriverman Thanks for your notes. Currently we have posted this issue to understand about this settings, but already its posted here #1030. So closing this issue.
