### ISSUE TITLE
psql: unable to connect to server (psql) under fresh iCentOS7

### ISSUE THREAD

**Issue by dugravot6** [RestyaPlatform/board#1108]
Hi,
On a fresh update centos7, the install script failed when it have to : 
+ psql -U postgres -c '\q'
psql: n'a pas pu se connecter au serveur : Aucun fichier ou dossier de ce type
	Le serveur est-il actif localement et accepte-t-il les connexions sur la
 	socket Unix « /var/run/postgresql/.s.PGSQL.5432 » ?
+ '[' 2 '!=' 0 ']'
+ echo 'PostgreSQL Changing the permission failed with error code 40'
PostgreSQL Changing the permission failed with error code 40
+ exit 1

See attach file.
[restyaboard_install.log.zip](https://github.com/RestyaPlatform/board/files/827891/restyaboard_install.log.zip)

**Comment by baskar383** [comment]
We are check your restyaboard install log your postgress sql is not started. 
commands
>> systemctl status postgresql
>> systemctl start postgresql

**Comment by dugravot6** [comment]
Hi,
a simple start is not sufficient, because it never start : 

`systemctl start postgresql-9.5
Job for postgresql-9.5.service failed because the control process exited with error code. See "systemctl status postgresql-9.5.service" and "journalctl -xe" for details.
`


`systemctl status postgresql-9.5
● postgresql-9.5.service - PostgreSQL 9.5 database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql-9.5.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since ven. 2017-03-10 14:32:16 CET; 8min ago

mars 10 14:32:16 localhost.localdomain systemd[1]: Starting PostgreSQL 9.5 database server...
mars 10 14:32:16 localhost.localdomain systemd[1]: postgresql-9.5.service: control process exited, code=exited status=1
mars 10 14:32:16 localhost.localdomain systemd[1]: Failed to start PostgreSQL 9.5 database server.
mars 10 14:32:16 localhost.localdomain systemd[1]: Unit postgresql-9.5.service entered failed state.
mars 10 14:32:16 localhost.localdomain systemd[1]: postgresql-9.5.service failed.`

`journalctl -xe
-- L'unité (unit) postgresql-9.5.service a commencé à démarrer.
mars 10 14:42:22 localhost.localdomain postgresql95-check-db-dir[20149]: "/var/lib/pgsql/9.5/data/" is missing or empty.
mars 10 14:42:22 localhost.localdomain postgresql95-check-db-dir[20149]: Use "/usr/pgsql-9.5/bin/postgresql95-setup initdb" to initialize the database cluster.
mars 10 14:42:22 localhost.localdomain postgresql95-check-db-dir[20149]: See /usr/share/doc/postgresql95/README.rpm-dist for more information.
mars 10 14:42:22 localhost.localdomain systemd[1]: postgresql-9.5.service: control process exited, code=exited status=1
mars 10 14:42:22 localhost.localdomain systemd[1]: Failed to start PostgreSQL 9.5 database server.
-- Subject: L'unité (unit) postgresql-9.5.service a échoué
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- L'unité (unit) postgresql-9.5.service a échoué, avec le résultat failed.
mars 10 14:42:22 localhost.localdomain systemd[1]: Unit postgresql-9.5.service entered failed state.
mars 10 14:42:22 localhost.localdomain systemd[1]: postgresql-9.5.service failed.
mars 10 14:42:22 localhost.localdomain polkitd[602]: Unregistered Authentication Agent for unix-process:20143:208781 (system bus name :1.32, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale fr_FR.UTF-8) (disconnected from bus)
`



So for postgresql to start, we have to initdb, but for initdb to work, we have to empty /var/lib/pgsql/9.5/data : 
`[root@localhost ~]# /bin/rm -r /var/lib/pgsql/9.5/data/*
[root@localhost ~]# /usr/pgsql-9.5/bin/postgresql95-setup initdb
Initializing database ... OK
`

And at the end, restart restyaboard.sh script to reinstall. It finally work.
Stephane.
