### ISSUE TITLE
v4.2 Install Fix Ubuntu 14.04 nginx and php modules

### ISSUE THREAD

**Issue by vClouds** [RestyaPlatform/board#1110]
1) Installation is aborting during nginx install asking for nginx-full, nginx-* packages

Solved by manually adding latest nginx repo
wget https://nginx.org/keys/nginx_signing.key
nano /etc/apt/sources.list
deb http://nginx.org/packages/ubuntu/ trusty nginx
deb-src http://nginx.org/packages/ubuntu/ trusty nginx
apt-get update
Please find away to add the latest nginx repos.
AND yet ending with 403 Forbidden error after install; please advise on permissions

1) Installation is aborting during php7.0-imagick install (line 362).
Solved by edit and re-run again.
There's no php7.0-imagick package, just php-imagick.

**Comment by baskar383** [comment]
Thanks you. Fixed in this commit 7bca35e
