### ISSUE TITLE
App: Collaborate/TogetherJS does not work

### ISSUE THREAD

**Issue by theriverman** [RestyaPlatform/board#1113]
Hi,

I'm trying to experience with Collaborate/TogetherJS, I set it to Enabled under the Admin settings, then clicked it on the bottom but does not bring up anything. 
Do I need any special plugin for it to work or change some sort of settings to use it?

I tried starting it with two unindividual users at the same time in two different browsers, but no lucky - no connection.
I found the [Restyaboard > Apps > Collaborate/TogetherJS](http://restya.com/board/apps/r_togetherjs) sub-page, but no useful information there for me.

Any ideas?

Thanks!

![togetherjs](https://cloud.githubusercontent.com/assets/22156894/23835370/47ebcbb4-0766-11e7-8ffe-859aae066108.png)

**Comment by lmarikannan** [comment]
@theriverman Could not reproduce this issue on our demo server. Can you please open your browser console and see if there's any errors?

Also, please try to enable debug mode https://github.com/RestyaPlatform/board/blob/master/server/php/config.inc.php#L15 and look up HTTP header. Post HTTP header response if you get any error.

**Comment by theriverman** [comment]
Hello, I'm not able to do this now, maybe early next week.
I close this issue now and will open+comment again later.
