### ISSUE TITLE
v4.2 Installation bug - Ubuntu 14.04

### ISSUE THREAD

**Issue by vClouds** [RestyaPlatform/board#1115]
Although the php7 repo were added and some packages php7.0-XXXX were installed with no issue, only installation of php7.0 package is keep aborting with the below output,

> Get:9 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main php7.0 all 7.0.16-4+deb.sury.org~trusty+1 [46.4 kB]
> Preconfiguring packages ...
> Fetched 4,764 kB in 10s (471 kB/s)
> Setting up sysv-rc (2.88dsf-41+deb7u1) ...
> info: Reordering boot system, log to /var/lib/insserv/run-20170314T0405.log
> error: Something failed while migrating.
> 
> error: Unable to migrate to dependency based boot sequencing.
> 
> See http://wiki.debian.org/LSBInitScripts/DependencyBasedBoot for
> more information about dependency based boot sequencing. To
> reattempt the migration process run 'dpkg --configure sysv-rc'.
> 
> dpkg: error processing package sysv-rc (--configure):
>  subprocess installed post-installation script returned error exit status 1
> Errors were encountered while processing:
>  sysv-rc
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> + '[' 100 '!=' 0 ']'
> + echo 'PHP installation failed with error code 3'
> PHP installation failed with error code 3
> + exit 1

**Comment by rrjanbiah** [comment]
@vClouds Many thanks for your bug report. We'll fix it as soon as possible.

**Comment by lmarikannan** [comment]
@vClouds Sorry for the inconvenience. We have checked install script, and did some changes. Can you please restart your installation with this file [restyaboard.txt](https://github.com/RestyaPlatform/board/files/847832/restyaboard.txt)
