### ISSUE TITLE
nginx: [emerg] invalid number of arguments in "root" directive 

### ISSUE THREAD

**Issue by kirtangajjar** [RestyaPlatform/board#113]
This is what i get when i tried to setup restyaboard from command line in Ubuntu.

`nginx: [emerg] invalid number of arguments in "root" directive in /etc/nginx/conf.d/restyaboard.conf:5`

**Comment by ssivachidambaram** [comment]
We think your folder contains spaces and its not enclosed within double quotes for root in restyaboard.conf. Can you please confirm?

**Comment by rrjanbiah** [comment]
@kirtangajjar Are you still facing this issue? Was above reply helpful?

**Comment by kirtangajjar** [comment]
Actually i don't know. I just gave up trying after some time.

**Comment by rrjanbiah** [comment]
@kirtangajjar Sorry to know that. When you get it again, please feel free to reopen.

**Comment by cubbuk** [comment]
You may have forgotten to put semicolon at the end of your expression

**Comment by seronline** [comment]
I can confirm this problem when using the restyaboard.sh bash script. When starting nginx manually the error reads:

`nginx[4432]: nginx: [emerg] invalid number of arguments in "root" directive in /etc/nginx/conf.d/restyaboard.conf:5`

The corresponding line number 5 in restyaboard.conf is

`root ;`

I had to manually amend it to:

`root /usr/share/nginx/html/;`

I'm running Debian 8.

Hope that helps,
Sebastian

**Comment by Gump8** [comment]
> We think your folder contains spaces and its not enclosed within double quotes for root in restyaboard.conf. Can you please confirm?

Thanks.  It works for me!

**Comment by ssivachidambaram** [comment]
@Gump8 You are welcome :)
