### ISSUE TITLE
Feature request: Set the color of labels individually

### ISSUE THREAD

**Issue by ChrisDeChef** [RestyaPlatform/board#1132]
Unfortunately it's not possible to set the color of each label individually. So it happens that you type a label like "Important" or "Warning" and it gets colors like **lime** or **green** which confuses me more instead of helping me out of my brain salad ;)

**Comment by rrjanbiah** [comment]
@lmarikannan #712

**Comment by lmarikannan** [comment]
Fixed in this commit d9fe36a
