### ISSUE TITLE
Email notification

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#1133]
We do not have any notification when user add/edit/delete card on restyaboard.

We have Email notification on user creation.

**Comment by theriverman** [comment]
In my opinion, receiving an e-mail for every user action on cards would be a massive "over-kill".
Imagine the amount of spam for a board with 10+ members and with over 50 tasks.

However, Restyaboard supports in-browser push notifications [Safari, Chrome, Firefox, ...?]. 
If you allow that, that will notify you about all sorts of user actions.

/riverman

**Comment by morphos88** [comment]
I understand but I thought mail notifications worked like trello

**Comment by lmarikannan** [comment]
@morphos88 Can you please check your crontab that instant_email_notification and periodic_email_notification crons are exist or not?

**Comment by morphos88** [comment]
i have edit Crontab and now i have receive mail notification !

**Comment by lmarikannan** [comment]
Great to hear. Closing this issue.
