### ISSUE TITLE
[Major] Non-Admin users cannot remove assignee from Card

### ISSUE THREAD

**Issue by theriverman** [RestyaPlatform/board#1134]
Hi,

Just found this bug. I installed Restyaboard with the install-script, then added a new user from Admin menu.
I did not change anything under Admin settings, I did not touch Roles.

I can assign members to cards [both with admin and casual users], but if I try removing an assignee from a card, then Restyaboard crashes and technicaly I lose my access to the board until next refresh.

If you can't reproduce it in your test environment, I can provide you with a video on request.

/riverman

**Comment by lmarikannan** [comment]
@theriverman can you please execute the below query manually, and check again?

 UPDATE "acl_board_links" SET "url" = '/boards/?/lists/?/cards/?/cards_users/?' WHERE "name" = 'Remove card member';

**Comment by rrjanbiah** [comment]
@theriverman Please feel free to reopen if you're still facing the issue
