### ISSUE TITLE
SSL rewrite URL

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#1141]
I want to install SSL on restyaboard with Nginx.

I have a problem with jpg GET URL was on http not in https.

JS want get a http :
![2017-03-27_14h04_16](https://cloud.githubusercontent.com/assets/25505555/24355478/56d307be-12f6-11e7-8900-4dbe13f8f4fa.jpg)

**Comment by lmarikannan** [comment]
@morphos88 Script will cache the site URL in this file `tmp/cache/site_url_for_shell.php`. So can you please delete this file and it will recreate with `https` URL.

**Comment by lmarikannan** [comment]
@morphos88 Change `https` inside the file or can you please attach the generated file here?

**Comment by morphos88** [comment]
join

[site_url_for_shell.zip](https://github.com/RestyaPlatform/board/files/872434/site_url_for_shell.zip)

**Comment by lmarikannan** [comment]
@morphos88 Can you please clear cache and check? Also please attach `boards.json` output from developer console network tab?

**Comment by morphos88** [comment]
clear cache on my navigator ?

**Comment by morphos88** [comment]
i try to clear cache on my navigator it's do nothing.

I try to upload new photo and now there is no error but there is no font.

**Comment by lmarikannan** [comment]
Can you please check console and send if there is any other error?
