### ISSUE TITLE
Zip file for download v0.4.2 seems broken

### ISSUE THREAD

**Issue by asrita** [RestyaPlatform/board#1143]
While trying out Restya, I was not able to add labels to tasks. When I tried to figure out why, I realized that release tree in Github for v0.4.2 had lot more files than the download packaged version (board-v0.4.2.zip) @ https://github.com/RestyaPlatform/board/releases. For e.g., the folder /client/css had only two files as compared to a huge number in the branch tree.

Can you please check the zip file?

**Comment by lmarikannan** [comment]
@asrita Yes, one is source code of restyaboard and another one is compressed mode zip of restyaboard. In Compressed version zip file have /client/css folder, in that we minified and compressed the all css files into two files. And there is no other issues from any other users. Could you please explain what kind of issues are you've faced?

**Comment by asrita** [comment]
Oh I did not realize that. However, the problem I faced is that I was not able to add any labels to cards. But I just rechecked now, and it is working. I guess it was my mistake. Apologies..
