### ISSUE TITLE
Mail notification

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#1145]
In mail.log mail destination (TO:) every time is root@DomainName.

**Comment by lmarikannan** [comment]
@morphos88 Can you please check `SMTP` enabled. If `SMTP` enabled, check your smtp configuration

**Comment by morphos88** [comment]
# See /usr/share/postfix/main.cf.dist for a commented, more complete version


# Debian specific:  Specifying a file name will cause the first
# line of that file to be used as the name.  The Debian default
# is /etc/mailname.
#myorigin = /etc/mailname

#smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
smtpd_banner = RestyaBoard
biff = no

# appending .domain is the MUA's job.
append_dot_mydomain = no

# Uncomment the next line to generate "delayed mail" warnings
#delay_warning_time = 4h

readme_directory = no

# TLS parameters
smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
smtpd_use_tls=yes
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache

# See /usr/share/doc/postfix/TLS_README.gz in the postfix-doc package for
# information on enabling SSL in the smtp client.

myhostname = SrvRestyaBoard.ad.clauger.fr
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
myorigin = /etc/mailname
#mydestination = srv_exch.ad.clauger.fr, nagios.ad.clauger.fr, localhost.ad.clauger.fr, localhost
mydestination =
relayhost = srvexch2010.ad.clauger.fr
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
mailbox_size_limit = 0
recipient_delimiter = +
#inet_interfaces = loopback-only
inet_interfaces = all
#default_transport = error
default_transport = smtp
relay_transport = smtp
#relay_transport = error

**Comment by morphos88** [comment]
Log mail.log
`Mar 29 16:10:02 SrvRestyaBoard postfix/qmgr[858]: 1289F813A8: from=<root@ad.clauger.fr>, size=820, nrcpt=1 (queue active)
Mar 29 16:10:02 SrvRestyaBoard postfix/smtp[15320]: F1C8C813A5: to=<root@ad.clauger.fr>, orig_to=<root>, relay=srvexch2010.ad.clauger.fr[192.9.100.11]:25, delay=0.24, delays=0.06/0.01/0/0.16, dsn=2.6.0, status=sent (250 2.6.0 <20170329141001.F1C8C813A5@SrvRestyaBoard.ad.clauger.fr> [InternalId=17925974] Queued mail for delivery)
Mar 29 16:10:02 SrvRestyaBoard postfix/qmgr[858]: F1C8C813A5: removed
Mar 29 16:10:02 SrvRestyaBoard postfix/smtp[15324]: 1289F813A8: to=<root@ad.clauger.fr>, orig_to=<root>, relay=srvexch2010.ad.clauger.fr[192.9.100.11]:25, delay=0.14, delays=0.01/0/0/0.12, dsn=2.6.0, status=sent (250 2.6.0 <20170329141002.1289F813A8@SrvRestyaBoard.ad.clauger.fr> [InternalId=17925975] Queued mail for delivery)
Mar 29 16:10:02 SrvRestyaBoard postfix/qmgr[858]: 1289F813A8: removed
Mar 29 16:10:02 SrvRestyaBoard postfix/pickup[14956]: A70B4813A5: uid=0 from=<root>
Mar 29 16:10:02 SrvRestyaBoard postfix/cleanup[15317]: A70B4813A5: message-id=<20170329141002.A70B4813A5@SrvRestyaBoard.ad.clauger.fr>
Mar 29 16:10:02 SrvRestyaBoard postfix/qmgr[858]: A70B4813A5: from=<root@ad.clauger.fr>, size=782, nrcpt=1 (queue active)
Mar 29 16:10:02 SrvRestyaBoard postfix/smtp[15320]: A70B4813A5: to=<root@ad.clauger.fr>, orig_to=<root>, relay=srvexch2010.ad.clauger.fr[192.9.100.11]:25, delay=0.18, delays=0.01/0/0/0.17, dsn=2.6.0, status=sent (250 2.6.0 <20170329141002.A70B4813A5@SrvRestyaBoard.ad.clauger.fr> [InternalId=17925978] Queued mail for delivery)
Mar 29 16:10:02 SrvRestyaBoard postfix/qmgr[858]: A70B4813A5: removed`

**Comment by lmarikannan** [comment]
@morphos88 We will check and update you

**Comment by morphos88** [comment]
thanks

**Comment by lmarikannan** [comment]
@morphos88 Could you please check, mail notification is only log on mail.log and you didn't receive any mails from restyaboard?

**Comment by morphos88** [comment]
Yes is only log on mail.log and users receive only welcome message

**Comment by morphos88** [comment]
In welcome message ##ACTIVATON_URL## is not the same like ##SITE_URL## there is http and not https

**Comment by lmarikannan** [comment]
@morphos88 we'll check and update you

**Comment by morphos88** [comment]
Ok thanks

**Comment by lmarikannan** [comment]
@morphos88 Now that http and https related issue fixed on this commit 6ffda3b. You can find and replace `'http://' . $_SERVER['HTTP_HOST']` as `$_server_domain_url`  in `/server/php/R/r.php` file and check again.

**Comment by morphos88** [comment]
You solve problem about http to https in welcome activation mail but we still do not receive mail notification about delete/create/modifcation card.

**Comment by lmarikannan** [comment]
@morphos88 In restyaboard, email notifications are not coming immediately. It may come after 5 minutes or an hour, it's depending on user settings (Periodically or Instantly). Can you please check on this page `https://YOUR_DOMAIN_NAME/#/user/1/settings` on your restyaboard site for notifications are enabled or not. And also please refer #1133

**Comment by morphos88** [comment]
Notifications are configured immediately and i don't receive any notification.

Also in mail.log destination still root@DomainName

**Comment by lmarikannan** [comment]
@morphos88 as per this issue #1133 you've mentioned that crontab edited, and you've received mail notification. Can you please check again crontab that instant_email_notification and periodic_email_notification crons are exist or not.

**Comment by morphos88** [comment]
I think it works because in mail.log i see mail going out but the mail destination is false

![2017-03-31_16h22_47](https://cloud.githubusercontent.com/assets/25505555/24554542/4bc79f7a-162e-11e7-99c5-9047d88d14a6.jpg)

**Comment by morphos88** [comment]
Mail notification is OK.

Now i receive mails notification but there are problem in mail with accent : 
![image](https://cloud.githubusercontent.com/assets/25505555/24611477/7f820106-1882-11e7-85f7-917248c137ae.png)

**Comment by lmarikannan** [comment]
@morphos88 Please update your Email content from `Here's what you missed…` to `Here's what you missed...` on 'Email Notification' Email template page `http://YOUR_DOMAIN_NAME/#/email_templates/6` . Also replace this file [core.php.txt](https://github.com/RestyaPlatform/board/files/892174/core.php.txt) on this folder path `/server/php/libs/`, then replace the file format `core.php.txt` to `core.php`. And check again.

**Comment by morphos88** [comment]
we have already problem in mail notification with accent

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/99bf6741e9f843a62462e339591ba2f0b3360cbc
