### ISSUE TITLE
Installation issue in Ubuntu 12-16

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1149]
_From one of our customers_

**Failure to install on Ubuntu 12-16**

Unfortunately I didn't keep the VMs around as they were occupying space on premium SSD storage (I built the VMs for the express purpose of using restyaboard) and the space has since been reclaimed (long before you first e-mailed me as a matter of fact). Since I don't have logs (or the time to re-deploy a VM then re-install restya again) you can consider this issue closed. If you would like to reproduce, simply download the respective VM from my repository and you can test. If it works for you with this same image, you can know that the issue must have been something with my deployment, and not your installer. (Repository here: https://sourceforge.net/projects/osimages/files/Linux/Ubuntu/ ) 

**Missing dependencies**

The manual installation instructions ( http://restya.com/board/install#Manualsetup ) do not detail the fact that geoip is required as is described in the installation script on line 59 ( https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh ). I'm also not able to find that in the binary ( https://github.com/RestyaPlatform/board/releases/download/v0.4.2/board-v0.4.2.zip ) so this should be corrected. (The manual instructions should be the same as the shell script, no?)

**Packages installed out of order**

The installer ( https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh ) does not install php7.0-fpm first, this causes Apache to be installed when another subsequent package is installed (I can't recall which right now, sorry)

**Comment by lmarikannan** [comment]
@rrjanbiah 

> The manual installation instructions ( http://restya.com/board/install#Manualsetup ) do not detail the fact that geoip is required as is described in the installation script on line 59 ( https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh ). I'm also not able to find that in the binary ( https://github.com/RestyaPlatform/board/releases/download/v0.4.2/board-v0.4.2.zip ) so this should be corrected. (The manual instructions should be the same as the shell script, no?)

Now we're adding missing dependencies on manual installation instructions 

> The installer ( https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh ) does not install php7.0-fpm first, this causes Apache to be installed when another subsequent package is installed (I can't recall which right now, sorry)

In installation script, packages will be install proper order only, so no need to change the installation order
