### ISSUE TITLE
pgdg-centos94 installation stalled

### ISSUE THREAD

**Issue by psyfi** [RestyaPlatform/board#115]
Using the restyaboard.sh installer script, pgdg-centos94 installation gets stalled. I'm using CentOS 6.7. Any help is much appreciated.

**Comment by rrjanbiah** [comment]
Please attach the log file, that will help us to identify the issue.

**Comment by rrjanbiah** [comment]
@psyfi Are you still having this issue? If so, can you attach the log file?

**Comment by psyfi** [comment]
@rrjanbiah thanks for the follow-through. I was able to resolve it myself. I install pgdg-centos94 separately and did the manual config of postgresql. Then I ran the script again. 

Later I had some issues with php-fpm and db permissions, despite grant all for restya db user. I changed the user to postgre and things worked out. 

Thanks!

**Comment by rrjanbiah** [comment]
@psyfi Thanks for the reply. We'll also check from our end on this. Thanks.
