### ISSUE TITLE
Reset demo instance language to English

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1151]
_From one of our customers_

If you go to your demo site and change the language to say mandarin, it is not reset to English like the password is, I was forced to use Google Translate. This should be corrected (and from a UX point of view, the language should show the language in the native language, but that has nothing to do with the demo site.) I may not have waited enough time, so this could be my fault.

**Comment by lmarikannan** [comment]
@rrjanbiah Already this work has been done

**Comment by rrjanbiah** [comment]
@lmarikannan I don't think it works. I still find random language. Please redo QA and close.

**Comment by lmarikannan** [comment]
@rrjanbiah due to cookie, language selection changes will be update after logout
