### ISSUE TITLE
Automatic language selection based on browser & IP

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1152]
For the first time, show the language based on the browser user agent value or based on GeoIP data. Once the user sets the language in cookie, it should give priority to cookie.

Once this is done, we can revert #1151

**Comment by baskar383** [comment]
Above issue are fixed in this commit (https://github.com/RestyaPlatform/board/pull/2583/commits/a9f5850a878a3df344b0031e4fb6f12aa50d496a)

**Comment by baskar383** [comment]
Duplicate issue of #2467. Hence closed.
