### ISSUE TITLE
Slowliness in Internet Explorer 11

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1155]
_From forum https://groups.google.com/d/msg/restya/mjbGELhb7F8/77ZTjqr2CwAJ_

I have Restyaboard v0.3 install on Centos 6.8. The app works great on Opera, Chrome, Mozilla but on Internet Explorer 11 it take forever to load the page /#/boards. The pie chart just render real slow and internet explorer eventually crash. Please help me !

**Comment by sridhar391** [comment]
For chat plugin only, the issue produced and fixed in `local commit`
