### ISSUE TITLE
restyaboard.sh script could not update config.inc.php

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#116]
From #102, note by @mic704b

> In my case the lines in the restyaboard.sh script could not update config.inc.php (/usr/share/nginx/html/server/php/R/config.inc.php)

**Comment by tmikaeld** [comment]
Might be related to this issue: https://github.com/RestyaPlatform/board/issues/123

Does the folder even exist?

**Comment by rrjanbiah** [comment]
@tmikaeld I suppose it is access related issue as the script needs root.

@mic704b Can you please confirm that?

**Comment by mic704b** [comment]
The target folder and file existed.

Yes, I think it is the same root cause as #123. I resolved it at the time by manually editing the file as root.

**Comment by rrjanbiah** [comment]
@mic704b Many thanks for your note.

We have added root check in script https://github.com/RestyaPlatform/board/commit/eceb11b96b4ccc23b5c08e108893bdeceeb42c4e So, it should be OK now.
