### ISSUE TITLE
Images are being squashed

### ISSUE THREAD

**Issue by MarcelloTheArcane** [RestyaPlatform/board#1160]
When you upload an image, it forces it to resize to a 4/3 aspect ratio.  This leads to images being squashed and looking wrong.  

There's two options, either a crop - which would leave some parts of the image chopped out, particularly for long or wide images, or not resizing at all.  I don't see the latter being a problem, as longer cards wouldn't really look bad - unless there's other reasons? are they of a specific height?

**Comment by rrjanbiah** [comment]
Duplicate of #1416
