### ISSUE TITLE
Mail will be garbled in some languages(V0.4.2)

### ISSUE THREAD

**Issue by sun4p** [RestyaPlatform/board#1164]
I change the language to Japanese, the body of the mail will be garbled.

I modyfied the following program.
/restyaboard/server/php/libs/core.php

sendMail function
        $headers.= "Content-Type: text/html; charset=ISO-2022-JP" . PHP_EOL;

Character-encoding "ISO-8859-1" is used throughout the Americas, Western Europe, Oceania, and much of Africa.

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/99bf6741e9f843a62462e339591ba2f0b3360cbc
