### ISSUE TITLE
New feature: Template for cards

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1171]
From one of our customers:

Are you considering making it possible to create Templates for Cards? Right now it is only possible to have template boards. Today we are using the project tool for development, bugs, internal customer handling and much more. And what I see a great need for is the option for ‘Save card as template’, and then you will be allowed to create a card based on your templates later on. Right now we copy/paste a lot. I am thinking choosing Card Template could be either when creating the card or as a part of the ‘instant add card’ function

**Comment by lmarikannan** [comment]
Implemented as new Plugin - http://restya.com/board/apps
