### ISSUE TITLE
Linux script install: nginx did not install.

### ISSUE THREAD

**Issue by amunizp** [RestyaPlatform/board#1176]
This probably is an error on my end. I only just know what I'm doing. I think that since I have LAMP installed there is a conflict. But just incase:

(...)
dpkg: error processing package nginx (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.19-18+deb8u9) ...
Processing triggers for systemd (215-17+deb8u7) ...
Errors were encountered while processing:
 nginx-full
 nginx
E: Sub-process /usr/bin/dpkg returned an error code (1)
+ '[' 100 '!=' 0 ']'
+ echo 'nginx installation failed with error code 2'
nginx installation failed with error code 2
+ exit 1

I then tried again :

(...)
NOTICE: To enable PHP 7.0 FPM in Apache2 do:
NOTICE: a2enmod proxy_fcgi setenvif
NOTICE: a2enconf php7.0-fpm
NOTICE: You are seeing this message because you have apache
 package installed.
Setting up nginx-full (1.10.3-1~dotdeb+8.1) ...
Job for nginx.service failed. See 'systemctl status nginx.s
rvice' and 'journalctl -xn' for details.
invoke-rc.d: initscript nginx, action "start" failed.
dpkg: error processing package nginx-full (--configure):
 subprocess installed post-installation script returned err
r exit status 1
dpkg: dependency problems prevent configuration of nginx:
 nginx depends on nginx-full (>= 1.10.3-1~dotdeb+8.1) | ngi
x-light (>= 1.10.3-1~dotdeb+8.1) | nginx-extras (>= 1.10.3-
~dotdeb+8.1); however:
  Package nginx-full is not configured yet.
  Package nginx-light is not installed.
  Package nginx-extras is not installed.
 nginx depends on nginx-full (<< 1.10.3-1~dotdeb+8.1.1~) |
ginx-light (<< 1.10.3-1~dotdeb+8.1.1~) | nginx-extras (<< 1
10.3-1~dotdeb+8.1.1~); however:
  Package nginx-full is not configured yet.
  Package nginx-light is not installed.
  Package nginx-extras is not installed.

dpkg: error processing package nginx (--configure):
 dependency problems - leaving unconfigured
Setting up php7.0-curl (7.0.18-1~dotdeb+8.1) ...

Creating config file /etc/php/7.0/mods-available/curl.ini w
th new version
Processing triggers for php7.0-fpm (7.0.18-1~dotdeb+8.1) ..
NOTICE: Not enabling PHP 7.0 FPM by default.
NOTICE: To enable PHP 7.0 FPM in Apache2 do:
NOTICE: a2enmod proxy_fcgi setenvif
NOTICE: a2enconf php7.0-fpm
NOTICE: You are seeing this message because you have apache
 package installed.
Errors were encountered while processing:
 nginx-full
 nginx
E: Sub-process /usr/bin/dpkg returned an error code (1)
+ '[' 100 '!=' 0 ']'
+ echo 'php7.0-curl installation failed with error code 5'
php7.0-curl installation failed with error code 5
+ exit 1

**Comment by theshades** [comment]
Yeah, the install script is meant only for nginx install.  This is why I am working with them to remake their install script. Feel free to check out https://github.com/ShadeySecurity/restyaboard-ansible and use the install script there after you update the variables.

**Comment by lmarikannan** [comment]
@amunizp If possible, can you please share the install log (remove sensitive details)?

**Comment by amunizp** [comment]
Sure but, Sadly I don't know what the sensitive data is. Thanks for warning me that there is.

**Comment by amunizp** [comment]
[restyaboard_install.txt](https://github.com/RestyaPlatform/board/files/1044780/restyaboard_install.txt)

**Comment by lmarikannan** [comment]
@amunizp Can you please uninstall all the pre installed php, nginx, LAMP and php modules like php-mbsting, php-cli, php-common. And run again the installation script?

**Comment by amunizp** [comment]
Sorry, can't as it is used on other services that I do not wishto affect. This is no longer a priority for me so I am happy to close this issue.
