### ISSUE TITLE
blank screen - api missing

### ISSUE THREAD

**Issue by theshades** [RestyaPlatform/board#1178]
I have been working my way through fixes, etc. for all the things I have found, but this one takes the cake for me, and I cannot find out why it is doing this. There are no entries in any of the logs which appear relevant.
However, the developer console in chrome reports this:
default.cache.e4bf7a8e.js:58 GET https://172.19.130.237/api/v1/oauth.json?_=1494458472237 404
Same site:
https://shadeysecurity.com
Build:
https://github.com/ShadeySecurity/restyaboard-ansible/tree/94c2ece2bdff227117ae8c3bf5be420a7f59fab2

**Comment by lmarikannan** [comment]
@theshades  From your previous issue #1177 it looks like you got the login screen but while checking this issue the API call getting 404 error. Did you changed anything in nginx configuration? Also can you please attach your nginx configuration to check this?

**Comment by theshades** [comment]
https://github.com/ShadeySecurity/restyaboard-ansible/blob/94c2ece2bdff227117ae8c3bf5be420a7f59fab2/defaults/nginx.conf
All of my configurations (including the restyaboard.conf) are in the defaults folder in the project.
I managed to fix many of the issues myself by modifying files, etc. to correct bugs.

**Comment by lmarikannan** [comment]
@theshades Here you can find our nginx configuration file https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf. Can you please use this configuration and try?

**Comment by theshades** [comment]
Greetings, 
I tried just your config (with only updating my servername) and same thing.
Still no errors anywhere except the missing API location.

Thanks,

Justin

**Comment by lmarikannan** [comment]
@theshades 

Can you please restart nginx and check the error log file? Also can you please attach your `nginx.conf` and `restyaboard.conf` file?

**Comment by theshades** [comment]
nginx conf was default, and no errors in the nginx error log after restart.  However I was able to get your install script working with a couple of fixes. So I will double back and check it out to see what is different between the installs,

**Comment by lmarikannan** [comment]
@theshades Closing this for now. If you get any issues, please feel free to reopen.
