### ISSUE TITLE
mixed text in card uncomfortable to read

### ISSUE THREAD

**Issue by llavall** [RestyaPlatform/board#1179]
Hey,
when I open a card I see a lot of text explaining when I (or someone else) did what with that specific card. In the same layout in between I see some posted text. It is pretty hard to filter the interesting stuff. I would like to see  an option to activate the status text inside a card if I need it, otherwise it is hidden and I see just the posted text. On top it would be great to have another style for that text.

Thank you!
Bw
Lars

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/77d4cad190a0d830b4ad0c0d9dabf259449ac4eb
