### ISSUE TITLE
LDAP plugin - Some bugs

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1182]
There are some errors within the LDAP login plugin (version 0.1.1) code.

When saving LDAP plugin settings, the bind password is saved in plain text without encryption. Then, in functions.php code, it is used like if it was encoded before, so it never binds to AD when using $t_password.

r_ldap_login_root_dn is not explained on the client view. r_ldap_login_base_dn is not used in the code. But they are actually the same thing.

g_ldap_uid_field is not explained on the client view, but it is actually the same from Account Filter.

On code, when setting ldap protocol version, you are not using LDAP_OPT_PROTOCOL_VERSION nor LDAP_OPT_REFERRALS, so there will be problems when executing ldap_search().

**Comment by lmarikannan** [comment]
Fixed on our local server

**Comment by zhhwdev** [comment]
HOW CAN I install the ldap plugin

**Comment by rrjanbiah** [comment]
@zhhwdev You can buy here from plugin page http://restya.com/board/apps/r_ldap_login
