### ISSUE TITLE
Install Scipt Update

### ISSUE THREAD

**Issue by theshades** [RestyaPlatform/board#1184]
Greetings,
For you install script, I recommend you update the restyaboard.conf to have listen line changed to:

`listen default_server 80;`

Also, ensure before restarting nginx the install directory (ie: /usr/share/nginx/html/restyaboard) is owned by www-data:www-data, with those two updates I got your install script working.

**Comment by rrjanbiah** [comment]
@theshades Thanks for your note & help

**Comment by theshades** [comment]
Another thing I highly recommend is making it an SSL by default server.

**Comment by rrjanbiah** [comment]
@theshades Thanks. Someone already suggested `letsencrypt`. We're yet to add that and will do that in upcoming milestones

**Comment by lmarikannan** [comment]
@theshades 

> Also, ensure before restarting nginx the install directory (ie: /usr/share/nginx/html/restyaboard) is owned by www-data:www-data, with those two updates I got your install script working.

Most of the users are using with root permission only. So there is no need to add www-data:www-data for users and groups permission for nginx.
