### ISSUE TITLE
Logout goes to blank page

### ISSUE THREAD

**Issue by theshades** [RestyaPlatform/board#1188]
Greetings, after a while I see the page flip to https://servername/#/users/logout, but the page is blank. IF I try and reload, even with a ctrl+R in chrome, it brings me back to the above url and a blank page

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/d9fe36a421f283a3dfe51ec3e4686db3d873c4f4

**Comment by morbificagent** [comment]
Hi there,
have the same problem too...
My only solution for now is to clear my browser cookies and reload the page, than i can login again.
