### ISSUE TITLE
Lists disappear when switching to gantt layout

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#119]
In certain cases, lists are getting disappear when switching to gantt layout. Had to reload page to fix.

**Comment by rrjanbiah** [comment]
Another note that it is **not** always reproducible

**Comment by ssivachidambaram** [comment]
Fixed. https://github.com/RestyaPlatform/board/commit/5ae52493d87e19a40e207c13f7dcfa461fc91145
