### ISSUE TITLE
It's not possible to move card to other board

### ISSUE THREAD

**Issue by MaDie** [RestyaPlatform/board#120]
When i move a card from one board to another i get following error:

Uncaught TypeError: Cannot read property 'lists' of undefined

It seems that the field "is_closed" and "is_archived" is missing, i fixed it locally by customizing the javascript query but i am not sure if thats the right way.

**Comment by rrjanbiah** [comment]
@MaDie As this seems to work good in our demo and internal installations... Can you please provide little more information?

*  What is your version?
*  What is your setup? (Have you used our new install script?)
*  Is this a fresh installation? (or have you upgraded from previous version?)

**Comment by MaDie** [comment]
@rrjanbiah I can reproduce the error in your demo:

Im authorized as "restya" and chose the board "TEST PROJECT a", next I select a task and click on the little gear -> action -> move. As soon as i change the board the GUI isnt refreshed with the new lanes.
It works within the same board, but not with diffrent boards.

![restyaboard](https://cloud.githubusercontent.com/assets/4627758/12320859/4b3335d6-baab-11e5-8919-a0e61b1023b6.PNG)

We also use 0.1.6, but with docker installation at 0.1.4 and upgrade to 0.1.5 and finally 0.1.6. But as i said, the error is also in the demo installation.
 i am using Google Chrome 47.

**Comment by rrjanbiah** [comment]
@MaDie Thanks a lot for explaining the issue very clearly. We really misunderstood your previous note. Thanks again. We'll fix it soon.

**Comment by Struki84** [comment]
Hello, I'm using restya 0.6.7 within a docker container, and I'm having the same issue. Wehn trying to move the card to another board a get an error in console. 

![Screenshot 2019-11-25 at 13 19 10](https://user-images.githubusercontent.com/1117750/69540121-33f5c300-0f86-11ea-957c-dbab54cad8a5.png)
