### ISSUE TITLE
"Create New Board" not translated in the French

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1205]

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/fb806ef9656d521d042f382d9257d7f285c8b4b3

**Comment by morphos88** [comment]
Script restyaboard.sh does not work to update ?

**Comment by rrjanbiah** [comment]
Reopening to reply @morphos88

**Comment by lmarikannan** [comment]
@morphos88 

> Script restyaboard.sh does not work to update ?

It will work for upgrade Restyaboard version. Can you please download the latest `wget https://github.com/RestyaPlatform/board/raw/master/restyaboard.sh --no-check-certificate` file and try?

**Comment by morphos88** [comment]
It works for v0.5 but not for last commit

**Comment by lmarikannan** [comment]
@morphos88 Install script will upgrade files based on releases/versions only (it will not update file commits based).

**Comment by morphos88** [comment]
There is a procedure to merge commits on restyaboard install ?

**Comment by lmarikannan** [comment]
@morphos88 You have to build it from source file. Please find the commands here https://github.com/RestyaPlatform/board#build.
