### ISSUE TITLE
Install script fails on Debian 9 Stretch / whenever postgresql-9.4 cannot be installed

### ISSUE THREAD

**Issue by wf-r** [RestyaPlatform/board#1207]
# Observation

Install script fails when trying to set up postgresql

# Explanation

Script tries to install postgresql-9.4 and copy files to current version. However, Debian 9 does not have postgresql-9.4, therefore install fails and we end up with a postgresql-9.6 installation where pg_hba.conf has been renamed.

(Will fill in further details later on...)

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/27bf95f233c5b410f3b6a54bd36084209ff14b21
