### ISSUE TITLE
Setting the system to utf-8 is necessary for install script to work in Ubuntu 16.04

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1208]
From one of our customers Herold:

First communication:

> on a clean 16.04 ubuntu the install script linux fails when nginx is not previously installed, due to the apt-key verification.
> There were unauthenticated packages and -y was used without --allow-unauthenticated

Second communication:

>  The apt-key error I sent in earlyer was easily resolved setting the system to utf-8 as the ondrej repo has a special character in its name.

**Comment by lmarikannan** [comment]
Prem told, tat issue is only on tat client machine, so no need to update locale in our script. And also he told, If any other user get this issue, please refer this url : https://askubuntu.com/questions/89976/how-to-change-the-default-locale-in-ubuntu-10-10-server
