### ISSUE TITLE
Dashboard charts are awfully stretched in v0.5 in desktop view

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1209]
Refer screenshot...

Previous version:

![screencapture-board-demo-restya-1498646841437](https://user-images.githubusercontent.com/4907427/27634678-d4ffa2fe-5c21-11e7-9144-a84d69c57f9a.png)

v0.5:

![screencapture-board-demo-restya-1498646923915](https://user-images.githubusercontent.com/4907427/27634687-e020417a-5c21-11e7-970c-e089acd6f431.png)

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/2dc775a2c8b0b3411293c2ebf3d28c047c6b3754
