### ISSUE TITLE
Too much spacing in admin users listing table row

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1210]
Refer screenshot

![restyaboard-users-listing-spacing](https://user-images.githubusercontent.com/4907427/27634951-ef73c38a-5c22-11e7-83d5-6d92121c7c41.png)

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/2dc775a2c8b0b3411293c2ebf3d28c047c6b3754
