### ISSUE TITLE
Color palettes are not sorted by colors

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1211]
It is somewhat OK for board level background colors. But, completely random for list and card colors.

**Comment by lmarikannan** [comment]
Board level background colors, list and card colors orders are in same. Need to change to any other order?

**Comment by rrjanbiah** [comment]
Refer attachments

![board-color](https://user-images.githubusercontent.com/4907427/28026616-45367fe8-65b4-11e7-8719-6f9c03b784d3.png)

![card-color](https://user-images.githubusercontent.com/4907427/28026617-45476d6c-65b4-11e7-920b-3d4f0cc41e7e.png)

**Comment by lmarikannan** [comment]
Now we are ordering all colors in Horizontal wise, not in vertical ordering.

**Comment by rrjanbiah** [comment]
Check screenshots closely and see how similar colors (say, red or purple) are placed apart

**Comment by lmarikannan** [comment]
Fixed on this commit 5de5d2e
