### ISSUE TITLE
Board background color change is not reflecting in boards listing

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1212]
If we add photo, it is updating. But, if we add background color, it is not reflecting in boards listing

**Comment by lmarikannan** [comment]
Fixed on this commit - https://github.com/RestyaPlatform/board/commit/9877219b02927c8e373bfadf8b069f540e69331e

**Comment by rrjanbiah** [comment]
Commit has so many changes. Please explain how this issue was fixed

**Comment by lmarikannan** [comment]
These two changes will be fix this issue 
1. https://github.com/RestyaPlatform/board/commit/9877219b02927c8e373bfadf8b069f540e69331e#diff-674c2df082a9688fcf3fe459577244c9R1436
2. https://github.com/RestyaPlatform/board/commit/9877219b02927c8e373bfadf8b069f540e69331e#diff-674c2df082a9688fcf3fe459577244c9R1835

**Comment by rrjanbiah** [comment]
Explain / document the changes (changes are already linked)

**Comment by lmarikannan** [comment]
In existing code, We updated background color to that particular board model using this.model.set() or self.model.set(), but we didn't update it on that particular board in App.boards. So now we updated the background color on that board in App.boards also.
