### ISSUE TITLE
Some dropdown menus are unnecessarily lengthy

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1213]
Dropdown menus like "Today Todo" are having unnecessary whitespace. 

Important Note: Have to take care in terms of multi language support too.

**Comment by lmarikannan** [comment]
Fixed on local

**Comment by rrjanbiah** [comment]
Where is the commit?

**Comment by lmarikannan** [comment]
These changes are done in chart plugin, So we are not commit these changes in github
