### ISSUE TITLE
postgres error at end of install using linux install script

### ISSUE THREAD

**Issue by the1poet** [RestyaPlatform/board#1215]
I have attempted installing restyaboard on a Linux Hyper-V virtual machine with little success.
I installed Ubuntu 16.04.1 64bit server, did an upgrade to ensure all the latest updates were installed leaving me with Ubuntu 16.04.2 running.
I then followed the instructions on the install page. I downloaded the install script, made it executable, then ran the script.
See attached log.

[restyaboard_install.zip](https://github.com/RestyaPlatform/board/files/1114189/restyaboard_install.zip)

**Comment by lmarikannan** [comment]
@the1poet This issue is related to https://github.com/RestyaPlatform/board/issues/1253. And this issue is fixed on this commit https://github.com/RestyaPlatform/board/commit/b3936885e63ed5f2270c04d4a57aa72e59bb7f5f
