### ISSUE TITLE
Attachment view & download leads to oAuth error

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1216]
Steps to reproduce:

1. View http://board.demo.restya.com/#/board/15/card/744
2. Click view or download attachment

Getting:

`{"username":"admin","expires":"2017-06-30 07:14:21","scope":"read write","client_id":"7742632501382313","error":{"type":"OAuth"}}`

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/18d3f3a6addaa7b5ee4df60ec95847e4b4c92fdc
