### ISSUE TITLE
Logon iOS app

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#1217]
Cannot connect with iOS application log in nginx : 
"POST /oauth/authorize?response_type=code&client_id=6664115227792148&state=1456750015553&redirect_uri=restyaboards://XXXXXX/&scope=read%20write HTTP/1.0" 200 2152 "https://XXXXX/oauth/authorize?response_type=code&client_id=6664115227792148&state=1456750015553&redirect_uri=restyaboards://XXXXXXXX/&scope=read%20write" "Mozilla/5.0 (iPad; CPU OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Mobile/14E304"

Different error in app : 
![img_0037](https://user-images.githubusercontent.com/25505555/27730674-675d612c-5d8a-11e7-96d7-d2aef2af2ed9.PNG)
![img_0036](https://user-images.githubusercontent.com/25505555/27730675-67629fb6-5d8a-11e7-92cf-4ad3bbbaeb5e.PNG)

**Comment by rrjanbiah** [comment]
Update: We were able to reproduce the issue finally. Happens with "https only" sites. We somehow missed that use case and working on the fix.

**Comment by rrjanbiah** [comment]
Update: Still under appstore process

**Comment by rrjanbiah** [comment]
App is now approved. Kindly check again and share your feedback.
