### ISSUE TITLE
Translated strings in Transifex are not bundled

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1219]
On Transifex site is possibile to see some locales that are missing on the released .zip (v0.5.1). For example: pt_BR is not included, only pt (portuguese from Portugal).

**Comment by lmarikannan** [comment]
@flashfs 

Actually in the release version zip file, we will provide translated files for other languages using Google Translation, so it will not 100% correct.

For each release, we will upload latest English version strings in Transifex. You can review and update in Transifex here https://www.transifex.com/restya/restyaboard/language/pt_BR/. Finally download and use it in Restyaboard.

**Comment by rrjanbiah** [comment]
*Internal note*

This is a bug. We should sync Transifex translations; otherwise, there is no use for the contributors contributing to translation

**Comment by rrjanbiah** [comment]
*Internal note*

Check how others are doing it and refer to Transifex documents:

* https://github.com/odoo/odoo/wiki/Translations
* https://docs.transifex.com/integrations/github/
* https://docs.transifex.com/integrations/github-txgh
* https://github.com/mustafayuceel/transifex-javascript-client/blob/master/api
* https://www.transifex.com/blog/2013/github-transifex-integration/

**Comment by lmarikannan** [comment]
Now transifex translations are sync with using transifex client.
