### ISSUE TITLE
Activation link

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#1220]
Activation link was in http and not in https

**Comment by lmarikannan** [comment]
Please refer this commit https://github.com/RestyaPlatform/board/commit/6ffda3b3fc77d60f817c28d994c25b7fdf5930d6. (It looks code was reverted in current version). We will merge it upcoming release.

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/781cb5664ee6df4481dd6748f588acf608d708d0
