### ISSUE TITLE
Wrong password variable in imap.php

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1223]
On imap_open() function, in file /server/php/shell/imap.php, you are using the variable IMAP_EMAIL_PASSWORD, but I do think the correct one should be $imap_email_password.

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/b9f7a5e1b1ff16a7f167af5c708609465134fa4d
