### ISSUE TITLE
Always return list 0 on imap.php

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1224]
Testing the functionality of imap.php, I've discovered that
`$list_id = $board['default_email_list_id'];`
is always giving me 0, and there isn't a list with ID 0 on lists table, so the card is inserted on the right board on the database, but never shows up on website, because that list doesn't exists.

Doing the select manually
`SELECT default_email_list_id, is_default_email_position_as_bottom, user_id FROM boards_users_listing WHERE board_id = 8`
all the default_email_list_id are 0.

Am I doing something wrong or is that really a bug?

**Comment by lmarikannan** [comment]
@flashfs 

Actually it will select first list as default but currently its not working according to your statement. You can also change the list in "Email to board settings". Please refer this screenshot.

![email-to-board-settings](https://user-images.githubusercontent.com/17758064/27942998-2cf2b90a-62f9-11e7-91cd-d46a0cd0dff1.png)

**Comment by flashfs** [comment]
Yeah, if I manually change that setting, it works and I can see on table boards the column default_email_list_id changes too. But when I create a board, the first list is showing as the default on website, but on table boards that column is still 0, and this is not the correct id of the first list.

**Comment by lmarikannan** [comment]
Fixed on this commit - 272b543
