### ISSUE TITLE
iOS Application

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#1225]
Load board lag to display ring.

When i comment a card the window take half screen and come back after few second in full screen

**Comment by rrjanbiah** [comment]
*Internal note*

Since the board is getting loaded in webview, performance issue is there in some iPhone devices. Perhaps prefetch or show some loading images to enhance user experience?

**Comment by baskar383** [comment]
This issue fixed in the dev branch, it will available on upcoming RestyaBoard version v0.6.7 (Boney M)
