### ISSUE TITLE
Install script is failing when system locale is not set

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1227]
*Internal note*: Refer Leo & Prem about issues in handling `/etc/default/locales`

**Comment by lmarikannan** [comment]
Prem told, tat issue is only on tat client machine, so no need to update locale in our script. And also he told, If any other user get this issue, please refer this url : https://askubuntu.com/questions/89976/how-to-change-the-default-locale-in-ubuntu-10-10-server
