### ISSUE TITLE
imap_fetchbody() not showing the message

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1228]
On file \server\php\shell\imap.php the line
`$body = imap_fetchbody($connection, $counter, 1.1);`
is forcing the 3rd parameter to be 1.1, but this isn't always true. Using this, on my tests, $body returned empty. But when I changed 1.1 to only 1, it captured the message. So maybe you should detect the message type and define that 3rd parameter according?

**Comment by lmarikannan** [comment]
Fixed on this commit - c0f1790
