### ISSUE TITLE
nginx: [emerg] invalid number of arguments in "root" directive

### ISSUE THREAD

**Issue by tmikaeld** [RestyaPlatform/board#123]
This has been posted before but was closed.

When running the script on Ubuntu 14.04 the root directive is not set at all.

The script tries to create the root folder but fails 
"mkdir: cannot create directory `': No such file or directory"

So the copying of restyaboard to the root folder also fails.

**Comment by tmikaeld** [comment]
The default value is /usr/share/nginx/html but should be /usr/share/nginx/www

**Comment by rrjanbiah** [comment]
@tmikaeld Many thanks for your fix and input.

**Comment by rrjanbiah** [comment]
@tmikaeld We're not using any default value here; we have only given example. Now, we have added empty check--so that users cannot move to next line without specifying the root path.
