### ISSUE TITLE
Allowing HTML input is causing unnecessary side effects 

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1230]
Though there are some security precautions are done, it is still not perfect.

1. Some tags still accept `class`
2. Some tags like `iframe` are accepted
3. Canceling edit (of HTML content) is breaking 

*Internal note*: For test cases, compare with GitLab

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/b88716e3e6686abb62632daf5610f8b790749a04
