### ISSUE TITLE
User timezone handling is broken in some places

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1231]
It is not clear, how user timezone setting is currently handled.

1. It seems to me that it is overriding global timezone setting and so it is breaking "time ago"
2. If we adjust the user timezone to global timezone, it is breaking time in email notification

So, we may not have to override the global timezone with user timezone (This looks like a fix for now)

**Comment by rrjanbiah** [comment]
Related #1117

**Comment by lmarikannan** [comment]
Fixed on this commit 3aef8ab
