### ISSUE TITLE
Organization/board title not using all the empty space

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1232]
Even when there is plenty of empty space, there is a tiny max width for organization/board titles.
I've attached an image so you can see what I'm talking about.
![not using empty space](https://user-images.githubusercontent.com/2033838/28065782-9458104e-6610-11e7-801b-98fa8584c700.jpg)

**Comment by lmarikannan** [comment]
Fixed on this commit - https://github.com/RestyaPlatform/board/commit/4ec30f4075c789e54e8f39cba06c2cc978491d0b
