### ISSUE TITLE
FR Translation

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#1234]
Some texte are not translate or not correctly translate in french.

Exemple : 
- "Créer un nouveau conseil" instead of "Créer un nouveau tableau"
- "Unst" instead of "Favoris"
- "Conseil fermer" instead of "Fermer le tableau"
...

**Comment by lmarikannan** [comment]
Related to https://github.com/RestyaPlatform/board/issues/1219

**Comment by lmarikannan** [comment]
Now transifex translations are sync with using transifex client.
