### ISSUE TITLE
Restya app Android

### ISSUE THREAD

**Issue by moonantonio** [RestyaPlatform/board#1238]
Develop an app for android users.

**Comment by hex-m** [comment]
There is something that looks "official" on the [play store](https://play.google.com/store/apps/details?id=com.restya.board). I didn't find the source code though.

**Comment by sridhar391** [comment]
@hex-m Yes, we have published the Restyaboard Android app in the Google Play Store

**Comment by hex-m** [comment]
Thanks! In that case this issue can be closed imo.
