### ISSUE TITLE
Debian/ubuntu install script shouldn't use the default template (ASCII) for postgresql

### ISSUE THREAD

**Issue by tmikaeld** [RestyaPlatform/board#124]
This line: https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh#L251

Should be:
`psql -U postgres -c "CREATE DATABASE ${POSTGRES_DBNAME} OWNER ${POSTGRES_DBUSER} ENCODING 'UTF8'  TEMPLATE template0"`

Or the creation of the database will fail with this error:
`ERROR:  new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)`

**Comment by rrjanbiah** [comment]
@tmikaeld Thanks for your contribution

**Comment by tmikaeld** [comment]
Thank you for being so responsive on issues, this will be an interesting app to try out.

**Comment by rrjanbiah** [comment]
@tmikaeld Thanks for your kind words. Please feel free to share your feedback once you try out.
