### ISSUE TITLE
Card informations

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#1241]
Add informations in card about who as created and when.

**Comment by rrjanbiah** [comment]
Internal note: We may provide some template kind of solution.

**Comment by Yasharah** [comment]
To see the creation time of the card would be awesome. We had the problem already that somebody created a task with the info that he stopped the automysql-backup on a server and we should check later if no backups are created anymore and that would have been easier if we knew when he stopped the backup/created the card

**Comment by lmarikannan** [comment]
@Yasharah We're done card creation time of the card. Now we're working on card created user informations related tasks

**Comment by morphos88** [comment]
Yes thanks
