### ISSUE TITLE
Hide Change Password of a LDAP user on administration

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1244]
## Expected Behavior
On Administration Panel shouldn't exist the Change Password button if a user comes from LDAP.

## Current Behavior
There's a Change Password button on administration panel for LDAP users. When trying to change, it says it was changed, but that isn't true.

## Possible Solution
So I think there shouldn't exist that button on the Administration Panel.

## Your Environment
* Version used: 0.5.1

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/c88235fa27ed7b1d6abc4a84e1a9fbb71bd9fe29
