### ISSUE TITLE
Bug: Add organization button keeps disabled

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1249]
## Expected Behavior
Trying to create an Organization with empty description throws an error (Whitespace alone not allowed). Then, typing the description corrects the error and we can add the organization.

## Current Behavior
After the empty error, the 'Add' button keeps disabled, even if we write the title and description, and we have to close and open that little window again so we can create the organization.

## Screenshots (if appropriate):
![add-button](https://user-images.githubusercontent.com/2033838/28172502-167f8860-67c2-11e7-81c6-3c76a38e354b.jpg)

## Possible Solution
Detect if the user typed something and hide the error and enable the Add button.

## Your Environment
* Version used: 0.5.1

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/8472a2228eef35a497ebe4eac5987011c03034b0
