### ISSUE TITLE
Card settings - UI suggestions.

### ISSUE THREAD

**Issue by tmikaeld** [RestyaPlatform/board#125]
(This is on Chrome Version 47.0.2526.111 (64-bit) OS X)

On the Card settings/chat/content/members etc it is hard to see a clear seperation on the left-side, I'd suggest seperating the boxes just by a couple of pixels.

Like this:

![screenshot_2016-01-18_05-57-52_pm](https://cloud.githubusercontent.com/assets/907195/12397457/96c1c052-be0d-11e5-9b4b-7c61338c4de6.jpg)

Also the "Add an attachment" should be a button not text, it's not clear that it's even clickable.

After clicking it, the dropdown list is not looking good:

![screenshot_2016-01-18_06-01-55_pm](https://cloud.githubusercontent.com/assets/907195/12397471/af363208-be0d-11e5-943b-5b94fd65ccd7.jpg)

**Comment by rrjanbiah** [comment]
@tmikaeld Thanks for your valuable suggestion.

**Comment by ssivachidambaram** [comment]
Fixed.
