### ISSUE TITLE
Bug: User Activation on Guest role doing nothing

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1251]
## Expected Behavior
Check/uncheck 'User Activation' on Guest role on admin panel should change the need of the activation.

## Current Behavior
Checking or unchecking the option does the same thing. After a user registers, the site says that an email was sent with the activation link.

## Steps to Reproduce (for bugs)
1. Login with admin credentials, go to Roles > Users, and check/uncheck the 'User Activation' on the Guest role.
2. Logout and try to register yourself as a new user.
3. You always get a popup saying an email was sent.

## Your Environment
* Version used: 0.5.1

**Comment by rrjanbiah** [comment]
@flashfs Many thanks for your detailed report

**Comment by lmarikannan** [comment]
Fixed on this commit b6ed885
