### ISSUE TITLE
Install script run into PostgreSQl error 36

### ISSUE THREAD

**Issue by soerenk** [RestyaPlatform/board#1253]
I use Debian 9 and just run restyaboard.sh. Then I get the Error "PostgreSQL database creation failed with error code 36". This was already fixed in fb2f4ff, but the commit a2e0926 removed the fix.

After manually changed the two lines in restyaboard.sh the installation worked.

**Comment by lmarikannan** [comment]
@soerenk  Thanks for your information. We'll check and update you.

**Comment by lmarikannan** [comment]
@soerenk Fixed on this commit b393688
