### ISSUE TITLE
Import from Trello not working

### ISSUE THREAD

**Issue by darko190** [RestyaPlatform/board#1255]
I have the newest build, and Ubuntu 16.04

When i press import from Trello, I can select the file, but than nothing happens.

I've tried disabling adblock and using different system and exporting another (smaller) board

**Comment by lmarikannan** [comment]
@darko190 Sorry for the issue you're facing. We'll check and will update you.

**Comment by darko190** [comment]
Tried reinstall, still not working....

**Comment by soerenk** [comment]
@darko190 how did you export the JSON file from Trello? I had an issue with exporting but there was a notification from Restya, that the file was corrupt. Try exporting from Trello again. Hope thats helps you.

**Comment by lmarikannan** [comment]
@darko190 we tried to reproduce this issue on our demo server (http://board.demo.restya.com/) using with trello welcome board json. But we could not reproduce this issue. Can you please check your JSON file? or share your JSON file here.

Note: 
- imported JSON : [trello.json.txt](https://github.com/RestyaPlatform/board/files/1167180/trello.json.txt)
- created board : http://board.demo.restya.com/#/board/251

**Comment by lmarikannan** [comment]
@darko190 Please reopen if you are still facing this issue with your Trello exported json file.

**Comment by darko190** [comment]
[KTlojaxD.json.txt](https://github.com/RestyaPlatform/board/files/1182361/KTlojaxD.json.txt) 
Still not working, tried installing to another server, when i press import, absolutely nothing happens; on your live demo, I can import any .json i export from Trello, and it works...

**Comment by lmarikannan** [comment]
@darko190 We checked with your json file, but we couldn't reproduce this issue. Also your json file is working fine on our live demo server too. So can you share your nginx error log file? and please enable debug mode in https://github.com/RestyaPlatform/board/blob/master/server/php/config.inc.php#L15 and post HTTP response header and response (In Firebug or Chrome's Developer tool)

**Comment by dadarko** [comment]
This was solved with installing php7.0-fpm
