### ISSUE TITLE
Enhancement: better decoding on imap.php

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1256]
## Expected Behavior
When using the imap.sh script to read emails and create cards, the enconding should be better guessed based on the headers and only if that isn't possible, use some default behavior.

## Current Behavior
When sending emails in UTF-8 format the decode_qprint() function on imap.php uses the utf8_encode() function. That function expects a ISO-8859-1 encode. So the card created have problems with special characters.

## Screenshots (if appropriate):
![restyaboard_encode](https://user-images.githubusercontent.com/2033838/28321721-533f6072-6baa-11e7-9247-0ac299e14b6f.jpg)

## Possible Solution
Maybe you could try reading the encode from the subject (examples below): 

ISO-8859-1 subject: `Subject: =?ISO-8859-1?Q?ASS=DAN=C7O?=`
UTF-8 subject: `Subject: =?utf-8?Q?Central_de_Manuten=C3=A7=C3=A3o_-_OS_1532?=`

and the headers from message body (examples below):

An ISO-8859-1 body:
```
Content-Type: text/plain; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: 8bit

message
```

An UTF-8 body:
```
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 8bit

message
```

After detecting you can try using the correct function for that encode format. If not, use a default one.

## Steps to Reproduce (for bugs)
1. Send an email with UTF-8 format.
2. Execute the imap.sh script to read that email from an inbox and create a card automatically.
3. The card created have weird texts.

## Your Environment
* Version used: 0.5.1

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/3dffbdf812a1c929bbbe7034d93829cb9787ce74
