### ISSUE TITLE
Bug: reading only first address on imap.php

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1257]
## Expected Behavior
If I send an email with two or more address separated by comma pointing to different boards, after executing imap.sh script the cards with same content should be created on different boards.

## Current Behavior
It is only creating a card on the first board of the email address list.
For example: if I send an email to restya+1+hash@localhost.com,restya+2+hash@localhost.com the current code is reading only the board 1.

## Possible Solution
Do not fix on the code the array position 0 on line:
`$mail = explode('+', $header->to[0]->mailbox);`

## Steps to Reproduce (for bugs)
1. Send one email to two boards just separating the address by comma.
2. Execute imap.sh script.
3. The card will be created only on the first board specified by email

## Your Environment
* Version used: 0.5.1

**Comment by lmarikannan** [comment]
Fixed on this commit 7af93e2
