### ISSUE TITLE
Suggestion: translation constants on PHP shell scripts

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1261]
## Expected Behavior
The PHP scripts on /server/php/shell/ should use translation constants so, for example, emails sent by card_due_notification.php should be on the selected language on Restyaboard application.

## Current Behavior
There are hardcoded strings on some of these php scripts.

## Your Environment
* Version used: 0.5.1

**Comment by sridhar391** [comment]
We have added this enhancement in the Restyaboard latest version 0.6.6 and for more details, please refer https://restya.com/board/changelog
