### ISSUE TITLE
Bug: after adding a due date, card is shrinking

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1262]
## Expected Behavior
After clicking the button to save the due date, the card should stay as it is.

## Current Behavior
After clicking the button, the card is becoming almost invisible on the cards list. I have to reload the page to view the card again.

## Screenshots (if appropriate):
![duedate_bug](https://user-images.githubusercontent.com/2033838/28778585-57aa5bd6-75d6-11e7-938a-5148af84c02e.jpg)

## Steps to Reproduce (for bugs)
1. Create a simple card on a board and save it
2. Open it again and add a due date
3. After clicking the button to save the due date, the card shrinks on card list

## Your Environment
* Version used: 0.5.1
* Browser: Firefox 43.0.1

**Comment by flashfs** [comment]
Oddly enough, after doing a Control+F5 this 'bug' didn't happen anymore. So, I think it could be archived.

**Comment by flashfs** [comment]
Really weird. Now it is happening again. Can someone try it?

**Comment by lmarikannan** [comment]
@flashfs We got this type of issue on our local, and we fixed already. So we'll push this changes on our future release version.
