### ISSUE TITLE
Suggestion: site name tooltip should span more

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1263]
## Expected Behavior
After hovering over the restyaboard logo at the bottom, a tooltip with the site's name appears, and it should have enough room to be more readable.

## Current Behavior
The tooltip have very little horizontal space.

## Screenshots (if appropriate):
![tooltip](https://user-images.githubusercontent.com/2033838/28779301-f77bd6ba-75d8-11e7-89ac-f8877de5fdbc.jpg)

## Your Environment
* Version used: 0.5.1
* Browser: Firefox 43

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/e66fd9347468cd7d32888251226ba8f7982d6666
