### ISSUE TITLE
Bug: profile picture path wrong on shell scripts

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1264]
## Expected Behavior
When automatics emails are sent through instant_email_notification.php and periodic_email_notification.php, we should see the profile picture of the user that triggered the activity.

## Current Behavior
When reading the received email, we just see the 'alt' from img tag.

## Possible Solution
Correct the path under $profile_picture_path, since there isn't a $_server_domain_url . '/img/. Maybe it is $_server_domain_url . '/client/img/

## Your Environment
* Version used: 0.5.1
* Using Gmail to read the emails.

**Comment by lmarikannan** [comment]
@flashfs Currently img folder is in client directory only. But in profile_picture_path, we use `/img`. And we  route the `/img` to `/client/img` using with restyaboard.conf file on line https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf#L46. Could you please check your `/client/img` and `media` folder permission level?

**Comment by flashfs** [comment]
I'm using Apache, so using the .htaccess here: https://github.com/RestyaPlatform/board/blob/master/.htaccess

**Comment by lmarikannan** [comment]
@flashfs Can you please confirm, currently images are not showing on email only or in your restyaboard site also?

**Comment by flashfs** [comment]
Only email.

The url of the avatar in email is: http://localhost:8080/img/small_thumb/User/1.cee46acef87d2f83da4b6584b6578796.png
The url of the avatar in site is: /restyaboard/img/small_thumb/User/1.cee46acef87d2f83da4b6584b6578796.png

My index URL is http://localhost:8080/restyaboard/. My .htaccess is inside the /restyaboard folder.

Writing this I think I found the problem. The $_server_domain_url was 'http://localhost:8080' when it should be 'http://localhost:8080/restyaboard'. Who populates this file? Should it be changed manually?

**Comment by lmarikannan** [comment]
@flashfs Yes, $_server_domain_url is wrong. You can edit that manually by updating `site_url_for_shell.php` file which is located in  `tmp/cache` on your restyaboard server. And please update `$_server_domain_url = 'http://localhost:8080';` to `$_server_domain_url = 'http://localhost:8080/restyaboard';`

**Comment by flashfs** [comment]
Ok, I dit that and it worked.

So, just to clarify: the creation of this file will be fixed or the expected behavior of this kind of URL is to change the file manually?

**Comment by lmarikannan** [comment]
@flashfs Yes, currently we need to change it manually for Subpath domains 

Ex.: localhost/restyaboard
