### ISSUE TITLE
Suggestion: admin configuration to change default subscription on cards

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1265]
## Expected Behavior
It would be nice to have a configuration on administration where we could change the default behavior of user subscription on boards. The user can subscribe/unsubscribe to board activities, but the admin should have the possibility to change the default behavior for new users.

## Current Behavior
A user can subscribe/unsubscribe to board activities, but there isn't an option to admins change the default behavior for new users (they are always subscribed).

## Your Environment
* Version used: 0.5.1

**Comment by lmarikannan** [comment]
@flashfs Already we are integrated this on our local, and we'll push this changes on our future release version
