### ISSUE TITLE
Bug: cards comments not showing line break

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1266]
## Expected Behavior
When writing a comment with a new line (Enter), the visualization of comments should show it.

## Current Behavior
The new line is not visible after saving the comment.

## Screenshots (if appropriate):
![newline](https://user-images.githubusercontent.com/2033838/28786147-b6d69526-75ee-11e7-92ce-3fb2bd77aae8.jpg)

## Your Environment
* Version used: 0.5.1
* Browser: Firefox 43.0.1

**Comment by lmarikannan** [comment]
@flashfs As per Markdown format, single enter doesn't go to the new line, double enter only will go to the new line. Anyway we'll check and update with you

**Comment by lmarikannan** [comment]
Fixed
