### ISSUE TITLE
Suggestion: use strftime() and not date() when outputting words

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1267]
## Expected Behavior
When outputting dates with month or day names, they should appear in the selected language in the application.

## Current Behavior
Month names are showing only in english.

## Possible Solution
Try to use strftime() instead of date() where month or day names are necessary. strftime() will respect setlocale(). For example, at my environment, using
`setlocale(LC_TIME, array("pt_BR.UTF8", "pt_BR", "pt"));
echo strftime("%A %e %B %Y");`
will output the names in brazilian portuguese.

## Steps to Reproduce (for bugs)
You can see this behavior on file instant_email_notification.php. It uses `date("h:i A (F j, Y)", strtotime($timezone));`.

## Your Environment
* Version used: 0.5.1
* Environment name and version (e.g. OS, PHP, PostgreSQL): PHP 5.4
* Operating System and version (desktop or mobile): Docker from CentOS 7

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/fb34103f48102a85b14eb22b7a772da6569df3da
