### ISSUE TITLE
Bug: when adding members to cards, users are appearing duplicate

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1268]
## Expected Behavior
When clicking the plus button next to 'Members' on the card windows, a popup appears with some users names.

## Current Behavior
Every time I hit the button the names are duplicated. The same is valid if adding through the gear icon > Members.

## Screenshots (if appropriate):
![member_add](https://user-images.githubusercontent.com/2033838/28881871-f137340e-777f-11e7-9b18-5f7e3b528717.jpg)

## Steps to Reproduce (for bugs)
1. Create a card and open it
2. Click the plus sign to add a member, then close the little popup
3. Click the plus sign again and it will show duplicates

## Your Environment
* Version used: 0.5.1
* Browser: Firefox 43

**Comment by lmarikannan** [comment]
Fixed in this commit - https://github.com/RestyaPlatform/board/commit/26d44f8ae8c84bf9329545e2fc62c251ecb68571#diff-31adb146eea72c3a34093c3e483fa839R3059
