### ISSUE TITLE
Suggestion: improve due date email notifications

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1269]
## Expected Behavior
The email notifications sent by card_due_notification.php should consider all the future time and if a user already received that email (like the flags on instant_email_notification). For example, if the system was down between 10:00 AM and 11:00 AM and goes up, all the users should receive notifications of due date from 11:00 AM and forward, and not only 1 day in the future with 5min window. With this kind of control, the cronjobs can stop and recover and the notifications will be sent, just like the periodic email notifications.

## Current Behavior
Using `BETWEEN ((now() + '1 day'::INTERVAL) - '300 seconds'::INTERVAL) AND (now() + '1 day'::INTERVAL)` can cause weird behaviors. For instance, I wasn't receiving any notifications because my job was executing let's say 14:25:01 and the due date was 14:20:00 of tomorrow, so more than 300s (just by 1s).

## Your Environment
* Version used: 0.5.1

**Comment by lmarikannan** [comment]
@flashfs 

Can you please check below work flow and we need your suggestion?

Work flow:
1. We will create a new field in cards table as is_due_date_notification_sent.
2. If is_due_date_notification_sent = 0 & due_date > 24 hours, then we will send due date notification

Need your suggestion:
1. In the above work flow, if the user set due_date to past date, then we should send notification immediately or we have to update is_due_date_notification_sent = 1 if the user enters past date.

**Comment by flashfs** [comment]
Thanks for the hard work on Restyaboard.

I think you could warn the user that he is entering a past date (maybe he clicked wrong) and not let him do that. But if you still want do allow this behavior, I think you should send the email and just after that mark the flag, so the flag status will reflect the truth.

About the workflow, on step 2, what if I create a card with due date 3 months in the future? I will receive just 1 notification 3 months before due date and never anymore? And what if the cron stops working and recovers at 24h or less to due date? The email will never be sent. Maybe the correct comparison would be <=24.

And there's another thing: if the user changes the due date, I think you should reset the flag, because maybe his intention is to receive a new notification.

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/08fba970016e3e47c1ea8f242eb4a4c96526b923
