### ISSUE TITLE
Suggestion: change input type of Local Timezone

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1270]
## Expected Behavior
As many other sites, the default timezone should be selected based on a select box with city name and the timezone, like "Brasilia (GMT+3)".

## Current Behavior
On the administrator system settings panel I have to manually input the timezone in a textbox, like "+0300".

## Your Environment
* Version used: 0.5.1

**Comment by lmarikannan** [comment]
Fixed in v0.5.2 and commited on https://github.com/RestyaPlatform/board/commit/0aa440562b648e673cb658f31d3a47ed1e28230d#diff-35df25b9af27bbb19c1176a9cdf9695d, https://github.com/RestyaPlatform/board/commit/0aa440562b648e673cb658f31d3a47ed1e28230d#diff-0cc9662c3caf14bf344a5854ae79a106
