### ISSUE TITLE
Cards cannot be deleted intuitively

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1272]
(From Daimler)

## Expected Behavior

Intuitive way to manage cards, especially delete

## Current Behavior

Cards cannot be deleted

**Comment by lmarikannan** [comment]
Fixed in these commits https://github.com/RestyaPlatform/board/commit/5ac065990605860cb20a688bea8fb98e54ce2240 and https://github.com/RestyaPlatform/board/commit/dabb45e94bf5d0d822c327f17611ee7bc9914d40
