### ISSUE TITLE
Install script is not clear about final install URL

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1277]
## Expected Behavior

After installing, install script should mention what URL has to be opened in browser for Restyaboard instance

## Current Behavior

Currently it is not clear for many people, what URL should be opened after installing.

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/60ed269e818d30edabc9400f82967513eb5334fc
