### ISSUE TITLE
Suggestion: get user profile timezone from global settings

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1278]
## Expected Behavior
When first editting a user profile, the timezone input should get, by default, the info from the administrator panel settings. And the input type should be a select box, and not a text box (like issue #1270 ).

## Current Behavior
When editting the user profile for the first time, timezone input comes blank and it is a mandatory field, so the user can't save the form.

## Your Environment
* Version used: 0.5.1

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/cc1da0958c89a3876c6b96b3f2e119051ccee67d
