### ISSUE TITLE
In mobile version, scrolling is not smooth

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1279]
## Expected Behavior

For example, trello app allow it move a card only with 'press and hold'. You have to hold your finger for few seconds, before the card will be movable

## Current Behavior

 the scrolling in the app is unreasonable. If you touch a card, you can never stop the moving

**Comment by lmarikannan** [comment]
Fixed in this commit - https://github.com/RestyaPlatform/board/commit/ede7f6058724f4842c86516edf440da79d15ea45
