### ISSUE TITLE
Not able to install in Ubuntu 14.04

### ISSUE THREAD

**Issue by nagendratest** [RestyaPlatform/board#128]
[logfile.pdf](https://github.com/RestyaPlatform/board/files/95390/logfile.pdf)

Hi Team,

   I have tried to install Restyaboard application in ubuntu platform.But i could not able to complete it.
   Please find the attached log file and provide me the assistance to complete installation process.

Regards,
Nagendra.

**Comment by ssivachidambaram** [comment]
We have added few more logging to the log file https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh

Can you please try this? Please review the log file content before uploading (it will contain passwords, if you host it in external IP, you have to censor it).

Also can you please send the putty username used to run the script?

**Comment by rrjanbiah** [comment]
@nagendratest To give you more detail.. we think that you're not having root access to the system.

**Comment by tmikaeld** [comment]
I noticed this as well, since the install script require root access the script should check for that.

**Comment by rrjanbiah** [comment]
@tmikaeld Thanks for your note

@ssivachidambaram Can we add root check in script?

**Comment by ssivachidambaram** [comment]
@rrjanbiah Added root check in install script https://github.com/RestyaPlatform/board/commit/eceb11b96b4ccc23b5c08e108893bdeceeb42c4e

**Comment by rrjanbiah** [comment]
@ssivachidambaram Thank you

@nagendratest Can you please check now?

**Comment by nagendratest** [comment]
I will check now.. Thanks for your help

**Comment by rrjanbiah** [comment]
@nagendratest Sure. Please let us know how it goes

**Comment by rrjanbiah** [comment]
@nagendratest Closing this for now. If you get any issues, please feel free to reopen.
