### ISSUE TITLE
Bug: thumbnails bundled with zip are causing weird behaviors

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1280]
## Expected Behavior
When adding some images to cards the correct thumbnail will show up after the upload and always.

## Current Behavior
When adding some images to cards, I do see the correct thumbnail just after uploading the image. But when I reboot the system I see some images like Yahoo, 'Test', some screenshots. I realized that these images are bundled with the .zip release, in folders like /client/img/large_thumb/CardAttachment/. Since I'm using the default SECURITYSALT for test purpose, so the hash (SECURITYSALT . $model . $id . $ext . $size) of my image is the same from the bundled ones.

## Possible Solution
Remove the bundled images from thumbnails directories.

## Your Environment
* Version used: 0.5.1
I'm using restyaboard with Docker

**Comment by lmarikannan** [comment]
@flashfs Sorry for the inconvenience. We're wrongly bundled the test files in img folder. And we're removed those files which are unnecessary, and will update in our future release. For now, please remove those files from `client/img/large_thumb/CardAttachment/` and check again.

**Comment by flashfs** [comment]
Yeah, deletting the images works.
