### ISSUE TITLE
Suggestion: remove thumbnail and original file when deleting attachments

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1281]
## Expected Behavior
When I delete an attachment, I would expect that the original file and their thumbnail (if it's an image) to be removed too.

## Current Behavior
When deleting attachments, the original file and thumbnail remains on disk. This could generate many orphaned files and consume disk space.

## Your Environment
* Version used: 0.5.1

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/b8c6188e643635909ec068061f0fa53dbb67f66c
