### ISSUE TITLE
Create board template

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#1284]
## Expected Behavior
Add possibility for user to create his own template

**Comment by lmarikannan** [comment]
@morphos88 You can create template and paste in this folder `client/js/workflow_templates`. For reference, you can check other files already available in that folder.

**Comment by morphos88** [comment]
Ok but for users it's not possible to connect directly to the server to create template.

**Comment by bcgoodmate** [comment]
I tried add new json file in this folder /opt/restyaboard/client/js/workflow_templates but it's not reflecting to the admin dashboard.

**Comment by lmarikannan** [comment]
@bcgoodmate Can you please check by add new json file in this folder `/usr/share/nginx/html/restyaboard/client/js/workflow_templates`?

**Comment by bcgoodmate** [comment]
I found it now. Thank you.

**Comment by lmarikannan** [comment]
@rrjanbiah Now we're having card template plugin for user level template creation. For Board template, we're using workflow templates json only. Need to create new interface to add workflow templates for users?

**Comment by morphos88** [comment]
No it's ok

**Comment by rrjanbiah** [comment]
Yep, I think, we can close it for now. In case, if anyone asks for, we can reopen
