### ISSUE TITLE
Removing member from card throws error 

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1289]
(From Daimler)

## Expected Behavior

Removing member from a card should work without any issue

## Current Behavior

When I try to remove a member from a card in the Restyaboard, the board closes with the following error message in the background: "Board not found. This board may be private"

## Screenshots:

![rb-boardnotfound](https://user-images.githubusercontent.com/4907427/29271452-23deab4c-8119-11e7-8626-adefa777b759.jpg)

**Comment by lmarikannan** [comment]
This issue is related to https://github.com/RestyaPlatform/board/issues/338 and it was fixed in this commit https://github.com/RestyaPlatform/board/commit/63aae4f5f302e62e076abf17d00a0eb63afedef3
