### ISSUE TITLE
automatic setup script on qnap TS-469L

### ISSUE THREAD

**Issue by kaefert** [RestyaPlatform/board#1293]
the automatic setup script tries to use "yum" on my NAS, although the only package manager available is "ipkg"

maybe you should print a warning if none of the supported linux distributions is found.

[restyaboard_install.log.txt](https://github.com/RestyaPlatform/board/files/1231781/restyaboard_install.log.txt)

**Comment by lmarikannan** [comment]
@kaefert We're checked your install log, and there is a problem with lsb-release detection. So please install lsb-release (e.g., apt-get install lsb-release) on your server, and please try again with restyaboard installation script.

**Comment by rrjanbiah** [comment]
@lmarikannan OP is saying that `yum` or `apt-get` is not available in his distribution. Meaning, our install script doesn't do proper detection of distribution.

**Comment by kaefert** [comment]
@rrjanbiah exactly what I meant, yes.

**Comment by lmarikannan** [comment]
@kaefert Fixed on this commit https://github.com/RestyaPlatform/board/commit/e747225108fdc3ab5f45e67ca19d6ba04bcef9df. Can you please update on this line https://github.com/RestyaPlatform/board/commit/e747225108fdc3ab5f45e67ca19d6ba04bcef9df#diff-e2930341cebfe21b6b1fd322a42667e2R19 and try again?

**Comment by rrjanbiah** [comment]
@lmarikannan Hmm.. no.. As he mentioned, only package manager available in his system is `ipkg` and the script doesn't handle that yet

**Comment by rrjanbiah** [comment]
@lmarikannan Here https://github.com/strk/gnash/blob/master/packaging/install-gnash.sh they may be using better logic to detect distribution and package manager.
