### ISSUE TITLE
Windows install documentation is inadequate

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1297]
## Expected Behavior

http://restya.com/board/docs/windows should have been created based on https://github.com/RestyaPlatform/board/issues/224#issuecomment-184282834 and https://github.com/RestyaPlatform/board/issues/224#issuecomment-182229772 But, it is missing information from https://github.com/RestyaPlatform/board/issues/224#issuecomment-182229772 especially on `fastcgi_pass` related changes.

## Current Behavior

http://restya.com/board/docs/windows is missing necessary information on `fastcgi_pass`

**Comment by lmarikannan** [comment]
Fixed on local and committed on dev site.
