### ISSUE TITLE
Better checking of $data['assets'] on r.php

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1298]
## Expected Behavior
A plugin without assets key defined on client/apps/pluginname/app.json should work normally, since it should not be mandatory a plugin have a js or css.

## Current Behavior
A plugin without both assets defined is throwing an error:
```
PHP Notice:  Undefined index: css in /var/www/html/restyaboard/server/php/R/r.php on line 1580
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/restyaboard/server/php/R/r.php on line 1580
```
I found that trying to use LdapPlugin. It has 'js' but not 'css' defined on app.json.

## Possible Solution
You should just check on r.php, since it shouldn't be mandatory to define theses assets with blank values.

## Your Environment
* Version used: 0.5.1

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/21e61ff1e977121ab50e1c70e5a604cfcd477dfe
