### ISSUE TITLE
Head icons on wrong position

### ISSUE THREAD

**Issue by fswmlu** [RestyaPlatform/board#1300]
columns of the table titel are on wrong position (see attached file)

![8b27649b409f816a44ec9a04afea050c](https://user-images.githubusercontent.com/31476853/29874953-a42cf7be-8d98-11e7-9a48-2bd82b121c41.jpg)
)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/1a06dfd2ab0b6cd1bdd43ba4a815b0766cb27e94
