### ISSUE TITLE
Comment thread display order is currently reversed

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1302]
## Expected Behavior

Comments display in proper threaded order

## Current Behavior

Thread is currently reversed

**Comment by lmarikannan** [comment]
Fixed on these commits https://github.com/RestyaPlatform/board/commit/06db60a3011741800e34dd76c026e2bf198781c6#diff-9812550cecc4e99d42faa21f771c0b8cL1158 and https://github.com/RestyaPlatform/board/commit/b342b493d64504d7fd582b303a85b3bc4b9eca87#diff-c60e449103faf0245fd84ac4277313fdL1384
