### ISSUE TITLE
Attachments for 'Add Instant Card'

### ISSUE THREAD

**Issue by Erik-eMP** [RestyaPlatform/board#1303]
## Expected Behavior

Being able to add an attachment on 'Instant Add Card' just like it is now possible to assign people and add labels. 

## Current Behavior

Currently you can add description, member, due date and label. Not attacment
## Screenshots (if appropriate):
![attachment](https://user-images.githubusercontent.com/31650102/30054748-62629e8a-922d-11e7-8078-01604e7b870a.png)

## Context
Most tasks includes screenshots or small files, so for Instant Add Card to be fully functional for the intended purpose, this would be necessary.

## Your Environment
* Link to your project: project.emailplatform.com

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/a911ddd4aae39f39346ef0c959ad03c1dae45734#diff-9812550cecc4e99d42faa21f771c0b8cL3489
