### ISSUE TITLE
Suggestion: don't delete all messages when using imap.php

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1305]
## Expected Behavior
When running imap.php I'd like to see all mails non related with restyaboard on the same place.

## Current Behavior
imap.php is using imap_delete() on all messages and If I'm using a mailbox with different kind of messages, all of them will be marked to be deleted.

## Possible Solution
Delete only messages identified after the "Check email hash with generated hash", so only messages that are trully related with this restyaboard functionality will be deleted.

## Your Environment
* Version used: 0.5.1

**Comment by rrjanbiah** [comment]
@lmarikannan Instead of using delete flag, can we use read flag?

**Comment by rrjanbiah** [comment]
@lmarikannan When you remove milestone, give reason. Also, at least move to next milestone

**Comment by lmarikannan** [comment]
@rrjanbiah Ok sure
