### ISSUE TITLE
ISSUE: BUG: Custom role not working

### ISSUE THREAD

**Issue by iwdselmo** [RestyaPlatform/board#1306]
After i created a custom role and assigned it to a user, after logging in and refreshing the page, restya stopped working and just loads white page. 

See print screen below to see console error:

https://www.screencast.com/t/G1xqBDIM4Ha

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/e8282c0037b49de92a5bdcb525100e589c82c63b, https://github.com/RestyaPlatform/board/commit/2bc5f4753d66bdb7285db89431d4b5f0a7b89bfe
