### ISSUE TITLE
Language switch is not updating UI

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1307]
(From Daimler)

## Expected Behavior

Language switch updates UI

## Current Behavior

The language just changes when there is some other action taken afterwards. When you try to set the language the UI does not set a check mark next to the language

**Comment by lmarikannan** [comment]
Fixed on this commit - https://github.com/RestyaPlatform/board/commit/0aa440562b648e673cb658f31d3a47ed1e28230d#diff-c60e449103faf0245fd84ac4277313fdR276
