### ISSUE TITLE
Chat UI needs improvement

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1308]
## Current Behavior

Currently chat UI is confusing as it displays only the status message in initial tab.

## Expected Behavior

* Better to combine both tab and remove tabs.
* If tab needs to be displayed, it can be "Rooms/Boards" -- instead of just "Boards"

**Comment by sridhar391** [comment]
The chat app UI has been changed and the changes are Tabs merged and label changed to "Chatrooms for Boards".
