### ISSUE TITLE
Add new card template is not working

### ISSUE THREAD

**Issue by bcgoodmate** [RestyaPlatform/board#1309]
I added a new card template "project-management.json" under this folder "/opt/restyaboard/client/js/workflow_templates" but it's not reflecting to the dropdown option.

**Comment by lmarikannan** [comment]
@bcgoodmate You need to add new template json on this folder `/usr/share/nginx/html/restyaboard/client/js/workflow_templates`. Can you please add json file in mentioned folder and check again?

**Comment by bcgoodmate** [comment]
Found it. Thanks.
