### ISSUE TITLE
Not all files and folders are showing in /opt/restyaboard compared to restya github https://github.com/RestyaPlatform/board

### ISSUE THREAD

**Issue by bcgoodmate** [RestyaPlatform/board#1310]

**Comment by lmarikannan** [comment]
@bcgoodmate In github, https://github.com/RestyaPlatform/board is having source files. which are can't run without build task. In release (https://github.com/RestyaPlatform/board/releases) zip, we are converted all files to minified and make easy to run. So there are some folders and files are removed.

**Comment by bcgoodmate** [comment]
Thanks for clarifying it.
