### ISSUE TITLE
version 0.5.2 loggin not working

### ISSUE THREAD

**Issue by iwdselmo** [RestyaPlatform/board#1316]
The login for this site is not working http://prolancerr.com

And also how to update the database with the new one. Thanks

**Comment by morphos88** [comment]
i have the same problem. after update to 0.5.2 we can not loggin.

i roll back to 0.5.1. in log i have 

> ++

 php /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php
PHP Warning:  pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update settings set value = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 26

Warning: pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update settings set value = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 26
PHP Warning:  pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41

Warning: pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41
PHP Warning:  pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41

Warning: pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41
PHP Warning:  pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41

Warning: pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41
PHP Warning:  pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41

Warning: pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41
PHP Warning:  pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41

Warning: pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41
PHP Warning:  pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41

Warning: pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41
PHP Warning:  pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41

Warning: pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41
PHP Warning:  pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41

Warning: pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41
PHP Warning:  pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41

Warning: pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41
PHP Warning:  pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41

Warning: pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41
PHP Warning:  pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41

Warning: pg_query_params(): Query failed: ERREUR:  la relation « timezones » n'existe pas
LINE 1: update users set timezone = (select code from timezones wher...
                                                      ^ in /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php on line 41
++ exit<

**Comment by lmarikannan** [comment]
@morphos88 There was an issue with v0.5.2 release zip, that having v0.5.2 upgrade sql filename was wrong. Now we've renamed sql file name from `upgrade-0.5.1-0.5.2.sql` to `v0.5.2.sql` and uploaded here. So you please update version `0.5.2` to `0.5.1` on this file `/opt/restyaboard/release`. And please upgrade using https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh. After that upgrade, logout and login again.
