### ISSUE TITLE
##SITE_URL## in e-mail templates point to https and not http

### ISSUE THREAD

**Issue by tmikaeld** [RestyaPlatform/board#132]
Maybe add additional tag for HTTPS and use HTTP by default?

Though i'd love it if https where the default
Might even be a good idea to integrate Let's Encrypt client to the script to auto-install SSL cert.

**Comment by tmikaeld** [comment]
See this: https://webnugget.de/setting-up-gitlab-with-free-ssl-certs-from-lets-encrypt-on-ubuntu-14-04/

For an elegant solution to auto-installing a cert.

**Comment by rrjanbiah** [comment]
@tmikaeld Thanks, we'll see what we can do here.

**Comment by rrjanbiah** [comment]
Closing this as this is already part of #1711
