### ISSUE TITLE
Description disappears when Adding attachment

### ISSUE THREAD

**Issue by Erik-eMP** [RestyaPlatform/board#1321]
## Expected Behavior
1. Write description
2. Upload attachment
3. Description is still there

## Current Behavior
1. Write description
2. Upload attachment
3. Description is lost

## Screenshots (if appropriate):
![restya_2](https://user-images.githubusercontent.com/31650102/30416837-f49df752-992d-11e7-86e6-3f896c954e98.png)
![restya_1](https://user-images.githubusercontent.com/31650102/30416838-f49f6786-992d-11e7-97a7-3fc2313dc4bb.png)

## Possible Solution
Remember the description.

## Steps to Reproduce (for bugs)
1. Write description
2. Upload attachment
3. Description is lost

## Context
It makes it frustrating because when you want to
1. Write description
2. Upload attachment
3. Save

Then you loose your entire description..

## Your Environment

* Link to your project: project.emailplatform.com

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/18ede4e0bf7865eeef207d3d3db802e041201e07
