### ISSUE TITLE
Getting wrong syncing offline message for 401 response

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1322]
## Expected Behavior

Should get offline message only when there is no internet connection

## Current Behavior

Now, getting wrong syncing offline message even for 401 responses

## Screenshots

![rb-sync-offline](https://user-images.githubusercontent.com/4907427/30430710-b0d80d4a-9979-11e7-8895-bd0d64a95941.png)

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/5f250b904d06e05d5aca8d4836dfdd80e78905dd

**Comment by rrjanbiah** [comment]
Looks like it got reopened in v0.6.4
