### ISSUE TITLE
iCal file can't get variable: $_server_domain_url

### ISSUE THREAD

**Issue by fswmlu** [RestyaPlatform/board#1326]
The iCal file bigins with the error message:

<br />
<b>Notice</b>:  Undefined variable: _server_domain_url in <b>/usr/share/nginx/html/restyaboard/server/php/ical.php</b> on line <b>28</b><br />
<br />
<b>Notice</b>:  Undefined variable: _server_domain_url in <b>/usr/share/nginx/html/restyaboard/server/php/ical.php</b> on line <b>40</b><br />
<br />
<b>Notice</b>:  Undefined variable: _server_domain_url in <b>/usr/share/nginx/html/restyaboard/server/php/ical.php</b> on line <b>40</b><br />
BEGIN:VCALENDAR
VERSION:2.0
(...)

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/8c8d444abea86c804679a25abc9a0c01a51b3b34
