### ISSUE TITLE
New card disappears when added to list if member filter active

### ISSUE THREAD

**Issue by ccrabtree10** [RestyaPlatform/board#1327]
## Expected Behavior
If you filter a board by a member, and add a new card assigned to that member, the card should appear in the list without having to refresh the page in the browser.

## Current Behavior
If you filter a board by a member, and then add a new card to which the member is assigned, the new card is not shown in the list. The page must be refreshed to show the card.

## Steps to Reproduce (for bugs)
1. Go to a board.
2. Filter cards by a member.
3. Click "Add a card" in a list.
4. Fill in card description.
5. Add the member used in the filter to the card.
6. Click "Add" to add the card.
Card disappears and is not shown in list.

## Context
Our board is very busy, so I always filter by cards assigned to myself.

## Your Environment
* Restyaboard 0.5.1
* Running on Oracle Linux 6

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/6b4a2f85fce981e2d295b2fde1a7c058e86f5d1b
