### ISSUE TITLE
Escape HTML/XML in comment

### ISSUE THREAD

**Issue by ccrabtree10** [RestyaPlatform/board#1329]
## Expected Behavior
When writing a comment on a card, any HTML/XML that appears in the text should be escaped, and displayed unchanged in the resulting comment.

## Current Behavior
HTML/XML appears to be interpreted by the browser, for example, adding the comment:

`Jeff, you need to add this to the root: <sometag>test</sometag>.`

results in a comment being displayed like this:

`Jeff, you need to add this to the root: test.`

## Steps to Reproduce (for bugs)
1. Open a card.
2. Type this comment: `Jeff, you need to add this to the root: <sometag>test</sometag>.`
3. Click "Comment" button.
4. Comment appears in list as `Jeff, you need to add this to the root: test.`

## Your Environment
* Restyaboard 0.5.1 on Oracle Linux 6

**Comment by lmarikannan** [comment]
Fixed on v0.5.2 and committed on https://github.com/RestyaPlatform/board/commit/0aa440562b648e673cb658f31d3a47ed1e28230d. Please refer https://github.com/RestyaPlatform/board/commit/0aa440562b648e673cb658f31d3a47ed1e28230d#diff-4f91f1e45c7c7a45fe11275fe4564ceeR81, https://github.com/RestyaPlatform/board/commit/0aa440562b648e673cb658f31d3a47ed1e28230d#diff-24a7194ed4306674650f3d47610ec0ecR43
