### ISSUE TITLE
restyaboard.sh script - handle exit code

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#133]
Check for exit code for each install commands.. .. probably use some bitwise error code to track error line.. when install script fails,

      echo "Install failed with error code $error_code. Open a ticket in https://github.com/RestyaPlatform/board/issues/new?title=Installation%20failed%20(error%20code%20$error_code) and attach restyaboard_install.log file found in current directory."

**Handling exit codes and using exit codes:**

 *  http://bencane.com/2014/09/02/understanding-exit-codes-and-how-to-use-them-in-bash-scripts/
 *  http://stackoverflow.com/questions/8447011/how-to-ensure-yum-install-was-successful-in-a-shell-script

**Comment by ssivachidambaram** [comment]
Done.
