### ISSUE TITLE
$_server_domain_url empty in export to google calendar option

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1331]
From Softbyte:

## Current Behavior

i had trouble with the export function from restyaboard calendar to google calendar ...

to fix it i had to put this in icalc.php: `$_server_domain_url='restya.example.com';`
where `restya.example.com` is the fqdn of our site
otherwise google calendar was not able to import the data ... that variable should be already present in `config.inc.php`, but looks like it's empty

**Comment by lmarikannan** [comment]
Duplicate #1326

**Comment by lmarikannan** [comment]
Fixed on this commit 8c8d444
