### ISSUE TITLE
export to google calendar doesn't publish all events

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1332]
From Softbyte:

## Current Behavior

my colleague told me now that the export to google calendar does not expose all the events ...  sometime all the event on the same list are published but not the other events  from other list, sometime instead it doesn't publish all the events on the same list ...

**Comment by rrjanbiah** [comment]
Referring @softb1te for him to track...

**Comment by lmarikannan** [comment]
@softb1te ical publish the due date's events only. And also it's working fine on our live server. Could you please share your ical url for test purpose? 

For reference please see the attachments. In that attachments, i use ical url from firefox board (http://board.demo.restya.com/#/board/7) and in our google calendar events it's published all the events of all the lists and cards.

Attachment 1 - firefox board: 

![google-calendar-sample1](https://user-images.githubusercontent.com/17758064/30742648-acf77f82-9fb7-11e7-939a-75814729d69d.png)

Attachment 2 - google calendar: 

![google-calendar-sample2](https://user-images.githubusercontent.com/17758064/30742667-c0609e3c-9fb7-11e7-8092-e05b2db41e1c.png)

**Comment by softb1te** [comment]
Maybe there was a misunderstanding, with "all events" we mean all the due dates of the events and not all the details of a single event.
Check the attached screenshots
![restya_dues](https://user-images.githubusercontent.com/32159214/30746453-238f4020-9faa-11e7-9aed-b79e5f482f00.png)
![gcal_restya1_dues](https://user-images.githubusercontent.com/32159214/30746454-238fd044-9faa-11e7-9d8f-84c108d44ef1.png)
![gcal_restya2_dues](https://user-images.githubusercontent.com/32159214/30746455-2394aeca-9faa-11e7-9ccb-bb4d68d5a0dc.png)

**Comment by rrjanbiah** [comment]
@softb1te Thanks for sharing the details

**Comment by lmarikannan** [comment]
@softb1te  Could you please share your ical file which is available on `/usr/share/nginx/html/restyaboard/server/php/` directory for test purpose?

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/8dbc94d9ed852c2420f6861c91c0df1152078a02#diff-037979dd76c0424e090df1752de7c91d, could you please update this changes on ical file and check again?

**Comment by rrjanbiah** [comment]
*Internal note*

@softb1te shared ical file privately and it appeared that the UID is not really unique. It was only an unique number before and the team now made it something like `id@host.tld`
