### ISSUE TITLE
Card problem due to mail addresses in comment

### ISSUE THREAD

**Issue by softb1te** [RestyaPlatform/board#1333]
Whenever create a comment in a card that include a mail address, the comment shows messed up.
If you edit the comment and save it again (no need to type anything), the mail address show correctly.
When you read the card from another account the problem appears again, and again if you edit and save you get the address correct.
## Expected Behavior

The mail address should show correctly without need to edit the comment.
## Current Behavior

The address is not shown, instead some random characters are displayed.
## Screenshots (if appropriate):
![emailbug_restyaboard](https://user-images.githubusercontent.com/32159214/30686020-3c240876-9eb7-11e7-8c8a-3b3ee92f6b7d.png)

## Steps to Reproduce (for bugs)

1. Create a new list
2. Create a new card
3. Open the card
4. Add a comment with an email address (the comment show the email address messed up)
5. Just edit the comment and save (the comment show the email correctly)

## Your Environment

* Version used: v 0.5.2 (2017-09-11)
* Environment name and version (e.g. OS, PHP, PostgreSQL): debian 8.9, php 7.0.23-1~dotdeb+8.1, postgresql 9.6.5-1.pgdg80+1
* Operating System and version (desktop or mobile):debian 8.9
* Link to your project:

**Comment by lmarikannan** [comment]
Fixed on this commit : https://github.com/RestyaPlatform/board/commit/6821521b8479cff864fbf23c4779ee39ba3d88a2
