### ISSUE TITLE
Text attachments are getting truncated

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1335]
From Softbyte @softb1te

## Current Behavior

another issue we found is on the attachment ... we attached a file from the desktop and it got truncated ... does it have any sort of limitation (the file was few kb)

> What was the format?

txt without any extension ... it's an ansible inventory

i've stripped the sensible data from the file and tried to upload it again .. the file once downloaded is trucated ...btw the file is truncated in different places if compared with the one that still has the sensible data ... the size are different, so it looks like it is not something to do with it

**Comment by softb1te** [comment]
See the attach file for example of the problem.
original:
[restyaboard_test.txt](https://github.com/RestyaPlatform/board/files/1321390/restyaboard_test.txt)

Downloaded:
[restyaboard_test_downloaded_error.txt](https://github.com/RestyaPlatform/board/files/1321393/restyaboard_test_downloaded_error.txt)

This happens if the files don't have any extension.
If i upload it with a txt extension (didn't try with other extensions) and download it i got it correct, as you can see:
[restyaboard_test_downloaded.txt](https://github.com/RestyaPlatform/board/files/1321397/restyaboard_test_downloaded.txt)

**Comment by lmarikannan** [comment]
@softb1te We're tried to reproduce this issue on our local server, but we couldn't reproduce this, can you please double check this?

In our local demo server, 

Without extension
http://boarddev.demo.restya.com/download/61/2e5dfcbb6f263a3be129d8caf7570c05

With extension
http://boarddev.demo.restya.com/download/60/3df1e9736969a2f4cee04f9116a91825

**Comment by rrjanbiah** [comment]
@softb1te What web server do you use (nginx or Apache)? Do you have `mod_security` enabled?

**Comment by softb1te** [comment]
We use nginx without mod_security, do we need to install it ?

**Comment by rrjanbiah** [comment]
@softb1te Not really. As it works for us, I'm trying to understand if you have any other extensions installed that's causing this issue.

If possible, please share your nginx conf file (Over the top of my head, it may be due to some configuration that's parsing files without extension)

**Comment by softb1te** [comment]
This is our nginx configuration:
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        return 301 https://$host$request_uri;
}

server {

        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        include snippets/ssl-example.com.conf; #ssl key
        include snippets/ssl-params.conf;  #ssl parameters


        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }


        location ~ /.well-known {
                allow all;
        }
}

**Comment by rrjanbiah** [comment]
@softb1te Are you still experiencing this issue? If so, please share it through Skype

**Comment by softb1te** [comment]
I just performed a test, looks like it's fixed at least using a text file without any extensions, didn't do more test.

**Comment by rrjanbiah** [comment]
@softb1te Thanks for your confirmation. So, closing this for now. If you reproduce it again, please reopen.
