### ISSUE TITLE
It should be possible to consult archived card

### ISSUE THREAD

**Issue by softb1te** [RestyaPlatform/board#1336]
It is not possible to consult (check comment, download attachment files, etc) a card  even if a it is archived to be able to access to the data.

## Expected Behavior

Consult the card as if not archived

## Current Behavior

It is not possible to consult an archived card.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by rrjanbiah** [comment]
*Internal note*

From @softb1te 

i will post a suggestion too, regarding the archived item, it should be to see them without moving them back to a list

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/33a16b676391a038cb432a753c69305fdf8a7b41
