### ISSUE TITLE
Very limited view for card details in the view "profile -> cards"

### ISSUE THREAD

**Issue by fswmlu** [RestyaPlatform/board#1337]
If you open a card throw list view profile -> card (/#/user/x/cards), you don't see any details. If you open the same card through board link /#/board/6/card/161, you can see all details and edit the card. Is ist possible to adapt the view to the user permission?
I'm owner of the card and I'm only able to see the title, set the colour and add atachment (see screenshot).
![2017-09-22_140233](https://user-images.githubusercontent.com/31476853/30744285-a7f150fa-9fa1-11e7-996f-9016c330a6ff.png)

**Comment by lmarikannan** [comment]
Fixed on this commit - https://github.com/RestyaPlatform/board/commit/1940ad0758be3f1be55aca916be925e54fd2a190#diff-430cd250037288f88b63de19c93426ea
