### ISSUE TITLE
Time on the comments in a card are wrong 

### ISSUE THREAD

**Issue by softb1te** [RestyaPlatform/board#1339]
The time displayed on the comments is wrong, in our case it is back of 2 hours.
## Expected Behavior

The time should be the local one.

## Current Behavior

the time is off of -2 hours

## Steps to Reproduce (for bugs)

1. Open a card
2. Write a comment and save it
3. The time on the just posted comment (but also on the others) is wrong.

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by rrjanbiah** [comment]
@lmarikannan Any progress on this?

**Comment by baskar383** [comment]
Fixed in new version 0.6
