### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1341]
From @softb1te 

for the installation problem we solved using this command:
`apt install -t jessie-backports  openjdk-8-jre-headless ca-certificates-java`

where the flag `-t` is used to use a specific repository, in this case `jessie-backports`

this is a repo that is not normally installed, you have to add it to you apt source on debian

**Comment by ssivachidambaram** [comment]
@rrjanbiah If we used the above command, its showing below error.

```
apt install -t jessie-backports openjdk-8-jre-headless ca-certificates-java
Reading package lists... Done
E: The value 'jessie-backports' is invalid for APT::Default-Release as such a release is not available in the sources
```

**Comment by sridhar391** [comment]
We have fixed this issue in the Restyaboard latest version 0.6.6
