### ISSUE TITLE
When LDAP is enabled, allow users to register using email as well

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1342]
Provide some option to allow user registration when LDAP is enabled

**Comment by sridhar391** [comment]
we have fixed this issue in the older version

![ldap_enable](https://user-images.githubusercontent.com/17172525/37447167-d41c3f0e-2846-11e8-8c20-2898ffab79f6.png)

![register](https://user-images.githubusercontent.com/17172525/37447184-e31be07c-2846-11e8-9432-2d6bade6ce1c.png)

**Comment by rrjanbiah** [comment]
@sridhar391 Where is the "option" to control this behavior? Also, kindly update the milestone in which this was closed

**Comment by rrjanbiah** [comment]
@sridhar391 

> For control this behaviour

Thank you

> and we can't able to find the milestone

Why? Can't we pull from Git and changelog?
