### ISSUE TITLE
Allow users to invite others using email address to a board

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1343]
Allow invite using email address. 

**Important:** This has to be handled carefully especially when using in intranet using LDAP.. as there should be clear distinction between internal and external users.

**Comment by rrjanbiah** [comment]
*Internal note*

Being Restyaboard a self-hosted application, this Trello like implementation causes lot of side effects. Users will invite anyone that are not within their organization and may cause security/privacy issues.

**Comment by morphos88** [comment]
The idea has been abandoned ? or note is just for information ?

**Comment by itzmeank** [comment]
@rrjanbiah is it possible to keep this in the restyaboard admin settings, so the organizations admin can decide if they want to allow ability to invite external users or not ?

**Comment by morphos88** [comment]
Seems that just admin user can invite external people ? Or admin permit users can invite external people ?

**Comment by rrjanbiah** [comment]
We need to consider multiple use cases. Our current approach (which is similar to GitLab) seems to be most suitable for most organizations. Other cases need to be handled through roles.

**Comment by itzmeank** [comment]
@rrjanbiah I also agree that it might be the best way to handle it...

**Comment by baskar383** [comment]
Documentation updated for `inviting external users` with clear steps,  kindly go through  https://restya.com/board/docs/restyaboard-user-invite/#0
