### ISSUE TITLE
Can't open attachment in iOS mobile version

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1344]
From Luszka

## Current Behavior

There is not possible to open an attachment. If you click on the file, you see only an white screen 

## Screenshots

![img_0041](https://user-images.githubusercontent.com/4907427/30813520-501774cc-a22b-11e7-8fc1-35669e871776.PNG)

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/b09174e7f3472a64b301e1f56d19f0b0912c3e8a
