### ISSUE TITLE
Can't upload attachment in iOS mobile version

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1345]
From Luszka

## Current Behavior

There is not possible to upload an attachment. You can select the files from media store on iOS device but you can’t start the upload. On pressing the invisible button “go” at the top-right corner you will redirect to the main screen.

## Screenshots

![img_0042](https://user-images.githubusercontent.com/4907427/30813636-973d7ec8-a22b-11e7-9df8-a334e1c863ec.PNG)

**Comment by rrjanbiah** [comment]
We can't reproduce this issue

* It is prompting with permission request (access to photo gallery)
* And then, able to choose photo or video

So, closing this now. Will reopen if we get more feedback

**Comment by fswmlu** [comment]
How did you choose photo or video? I don't see the button "select" or "ok". (see screenshot above). I testet this option on two mobile phones (iOS 10 and iOS 11) and I got the same result.
You can press the "invisible" button at the top-right corner you will redirect to the main screen, but the file don't be loaded and you will switched to the main screen.

**Comment by rrjanbiah** [comment]
@fswmlu Issues we've noted are:

1. Invisible button in top-right corner and top-left corner
2. On clicking invisible button in top-right corner, it uploads, but takes to boards listing page

But definitely upload happens here. 

(Reopening for further discussion)

**Comment by fswmlu** [comment]
on my mobile phone doesn't work. I tested with 'choose photo' and 'take a photo'. Nothing. It will not be uploaded.

**Comment by rrjanbiah** [comment]
@fswmlu Can you please share your mobile model and OS version? Also, approximately, what will be the size of the file?

**Comment by fswmlu** [comment]
@rrjanbiah We tested with iPhone SE, iPhone 5s and iPhone 6s under iOS 10.3.3 and 11.0.2. The images were ca. 20kB - 300kB.

**Comment by rrjanbiah** [comment]
@fswmlu Thanks for your information. Over the top of my head, I think, you may have clicked the hidden cancel button (not the hidden OK button). Anyhow, we're also trying to check the issue related to the hidden button from our end.

**Comment by fswmlu** [comment]
@rrjanbiah Sorry, but I don't think so. If I click the hidden button cancel, left corner, I switch to previous menu (back function). If I click the button at the top-right corner I'll redirect to the main screen.

**Comment by rrjanbiah** [comment]
@fswmlu Checking here. Trying to fix the hidden buttons first.

**Comment by fswmlu** [comment]
@rrjanbiah ok, fine! thanks!

**Comment by lmarikannan** [comment]
@fswmlu Uploading attachment in iOS issue fixed.
