### ISSUE TITLE
Default boards samples have to be redone for better practices

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1348]
Current sample records show that we can use kanban board for any use cases (for example, Y Combinator, Yahoo!, Apple, Mozilla, etc). When users start adopting similar approaches, they can't be able to properly track their todos with in progress and done status properly. 

So, sample records have to be recreated using todo, crm & scrum templates

**Comment by rrjanbiah** [comment]
@lmarikannan @ssivachidambaram This should be given priority. Currently, doesn't even have samples for color feature.

**Comment by lmarikannan** [comment]
@rrjanbiah Now the color feature has done for sample data

**Comment by sridhar391** [comment]
The Default board samples with todo templates are given below

Board Waymo

Todo:
1. Need a ride from Phoenix
2. Speed maintenance over city streets with pedestrians, cyclists, road work and more 
3. Safety regulations
4. Integration of self-driving technology into Fiat Chrysler
5. Expansion of testing grounds to the Asian country

Doing:
1. Custom sensors, computers, steering and braking with energy efficiency
2. Testing against different traffic regulations around the country

Done:
1. Test drive over ten uninterrupted 100-mile routes
2. Obstacle detection, 360-degree view
3. Test drive over freeways and subways
4. The accuracy of navigation to the destination

Board Google Home

Todo:
1. Self-adjustment to the particular language by device location
2. Permission to access wi-fi if available at a distance of 300m
3. Suggest the playlist and songs based on the user survey from the regional places
4. Make the video call to a person when connected to wi-fi and cam
5. Control the devices which are connected to intranet also

Doing:
1. Voice recognization improvement
2. Changing volume of the devices by swipe, Swipe circle clockwise to turn up the volume, and counterclockwise to turn down the volume
3. Quick charging capacity
4. Showing the status of the process by showing color on LED light on top of Google Home

Done:
1. Showing the status of Google Home is searching for an answer by showing LED light on top of Google Home continuously spinning clockwise (multi-colored)
2. Protecting user privacy by Pressing the mute button on the back of Google Home to keep from triggering your Google Assistant, even if you say “Ok Google”.
3. Showing the response of Google Home by showing LED light on top of Google Home continuously pulse (multi-colored)
4. Showing the error status

Board Pokemon GO

Todo:
1. Optimize for tablets
2. Compatibility with Android devices with 1GB RAM
3. Play the game via connecting with wi-fi
4. Updation of interface and introducing more new levels
5. GPS Location accuracy

Doing:
1. Compatibility with iPhone 4S or earlier iPhone devices
2. Compatibility with Android devices, which are having Android 4.4 installed
3. VIP membership purchase
4. Replay game without an internet connection
5. 2G network connection optimization

Done:
1. The pokemon indicator prioritizes Pokemon that are not registered to the user Pokedex and are at PokeStops near you
2. Added new Pokemon characters at different places
3. Added the extra reward points for catching particular Pokemon characters

**Comment by sridhar391** [comment]
Can you please give us the confirmation for board samples

**Comment by sridhar391** [comment]
Can you please give us the confirmation for the above board samples

**Comment by sridhar391** [comment]
We have created in our local and will update in our upcoming release.

**Comment by sridhar391** [comment]
We have created in our local and will update in our upcoming release.
