### ISSUE TITLE
Blank Page after a new install Restya on CentOS 7

### ISSUE THREAD

**Issue by filPhil** [RestyaPlatform/board#1349]
Hi,

After installation with install script restyaboard.sh , restya just showing blank page.
I have got these errors in nginx logs : 

2017/09/27 16:12:41 [error] 1611#0: *4 open() "/usr/share/nginx/html/restyaboard/client/api/v1/oauth.json" failed (2: No such file or directory), client: 192.168.1.21, server: _, request: "GET /restyaboard/client/api/v1/oauth.json?_=1506521559238 HTTP/1.1", host: "192.168.1.180", referrer: "http://192.168.1.180/restyaboard/client/"

I send also the log of the install.

Thank in advance,

Phil
[restyaboard_install.log](https://github.com/RestyaPlatform/board/files/1337577/restyaboard_install.log)

**Comment by lmarikannan** [comment]
@filPhil While checking your error log, you have accessed Restyaboard with wrong URL. Access Restyaboard like this `http://192.168.1.180/restyaboard/`.

**Comment by filPhil** [comment]
@lmarikannan If I use http://192.168.1.180/restyaboard/, I've got "403 Forbidden nginx/1.10.2"
Here is my restyaboard directory
![image](https://user-images.githubusercontent.com/32333935/30955122-db98530a-a432-11e7-8174-009747e1b62b.png)

I send also the conf of restyboard

[restyaboard.conf.log](https://github.com/RestyaPlatform/board/files/1340011/restyaboard.conf.log)

**Comment by lmarikannan** [comment]
@filPhil It looks lot of things changed from original `restyaboard.conf` file. Please refer https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf. Can you please revert it like and access `http://192.168.1.180/restyaboard/`? If you got any error, then please send nginx `/val/log/nginx/error.log`

**Comment by filPhil** [comment]
@lmarikannan Ok with the new restyaboard.conf and for http://192.168.1.180 I've got this error 👍 2017/09/28 11:48:02 [error] 3402#0: *1 "/usr/share/nginx/html/client/restyaboard/index.html" is not found (2: No such file or directory)

**Comment by lmarikannan** [comment]
@filPhil Can you please replace the attached configuration and access like this URL `http://192.168.1.180/`?

[restyaboard.conf.log](https://github.com/RestyaPlatform/board/files/1340419/restyaboard.conf.log)

**Comment by filPhil** [comment]
@lmarikannan If I do that, the url http://192.168.1.180 becomes http://192.168.1.180/#/users/login and I've got a blank page like before.

I have also this nginx log error : 
2017/09/28 12:24:07 [crit] 5256#0: *3 connect() to unix:/run/php/php7.0-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.1.21, server: _, request: "GET /api/v1/oauth.json?_=1506594246301 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "192.168.1.180", referrer: "http://192.168.1.180/"

**Comment by lmarikannan** [comment]
@filPhil Let me know your PHP version. Also can you please check whether this file `/run/php/php7.0-fpm.sock` is available?

**Comment by filPhil** [comment]
I had a version 5.4.16 that I just uninstall in favor of a 7.1.9.

[root@localhost ~]# php -v
PHP 7.1.9 (cli) (built: Sep 14 2017 19:40:34) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

but I dont have a /run/php directory so the `/run/php/php7.0-fpm.sock` doesn't exist !

**Comment by lmarikannan** [comment]
@filPhil Can you please try with changing like this?

`fastcgi_pass 127.0.0.1:9000;`

**Comment by filPhil** [comment]
With this parameter the error is : 

`2017/09/28 14:15:10 [error] 2748#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.21, server: _, request: "GET /api/v1/oauth.json?_=1506600905275 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.180", referrer: "http://192.168.1.180/"`

**Comment by lmarikannan** [comment]
@filPhil We have analyzed in your installation log, it looks like sock mentioned as this `/var/run/php5-fpm.sock` in this file `/etc/php-fpm.d/www.conf`. But we have given wrongly `/run/php/php7.0-fpm.sock`

So please use the below code in restyaboard.conf file,

`fastcgi_pass /var/run/php5-fpm.sock`

**Comment by filPhil** [comment]
Ok I suppose you mean 

`fastcgi_pass unix:/var/run/php5-fpm.sock;` but both give the same error 

`2017/09/28 15:51:29 [crit] 7695#0: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory)`

I don't find any file with *.sock on HD

**Comment by rrjanbiah** [comment]
@filPhil Please check if below links are helpful:

* https://stackoverflow.com/questions/17570658/how-to-find-my-php-fpm-sock
* https://stackoverflow.com/questions/35367676/php-fpm-doesnt-create-sock-file
* https://www.digitalocean.com/community/tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-on-centos-6

**Comment by filPhil** [comment]
Ok Ihave create .sock file with the command : 

`python -c "import socket as s; sock = s.socket(s.AF_UNIX); sock.bind('/var/run/php5-fpm.sock')"`

I have this line in restyaboard.conf

`		fastcgi_pass unix:/var/run/php5-fpm.sock;`

I have modified the /etc/php-fpm.d/www.conf lihe this

`listen.owner = nginx
listen.group = nginx
listen.mode = 0666`

but now I have this error : (it's a shame)

`2017/09/28 17:17:07 [crit] 3551#0: *1 connect() to unix:/var/run/php5-fpm.sock failed (13: Permission denied) while connecting to upstream`

**Comment by rrjanbiah** [comment]
@filPhil You may better contact us for free install support (Our IT team will install it if you provide remote access; either SSH or TeamViewer) http://restya.com/contact?category=free-installation

Please note that we're on festival holidays and team will be able to check on Oct 3rd, Tuesday.

**Comment by rrjanbiah** [comment]
@filPhil 

As per IT team:

* Path to socket file was wrong and had to use appropriate path
* Some ports were not open and they had to open them (During that they also disabled SELinux)
* Finally they also enabled SELinux
