### ISSUE TITLE
Trello Import Issue: URL attachments don't import properly

### ISSUE THREAD

**Issue by lmarikannan** [RestyaPlatform/board#1351]
From https://groups.google.com/forum/#!topic/restya/v_kVf7YJOFA,

Recently installed Restyaboard on an EC2 instance in order to test things out before I go installing it on our NAS.
My wife runs her company on Trello but wants something self-hosted. Obviously one of the requirements is that it can import Trello content perfectly.
So far, so good, except for one major problem: URL attachments in Trello don't seem to be importing well to Restyaboard.

When importing a card with URL attachments Restyaboard creates an attachment called <SeeminglyrandomString>.htmlcharsetutf-8
For example, a YouTube URL was imported as DMf6RStaTk.htmlcharsetutf-8
The original URL on Trello was https://youtu.be/DM_f6RStaTk

Looking in the JSON exported from Trello all appears well. The original URL appears as it should, and "DMf6RStaTk" doesn't appear anywhere in the file.

Looking at the file that gets downloaded when you click on the .htmlcharsetutf-8 file in Restyaboard it appears that it's the entire code for the page that was linked to.

It also appears that links are being properly attached when added directly in Restyaboard.

Hope you guys can look into this.

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/bde03c1bed0b02954286124acc96858b71025511

**Comment by rrjanbiah** [comment]
@lmarikannan Can you explain the fix?

Please check with Trello. I think, we shouldn't download youtube URLs and I can't find that in above fix

**Comment by lmarikannan** [comment]
@rrjanbiah In above fix, we're checked every attachments with this condition `if($attachment['isUpload']) {`. With this `isUpload` boolean, we can filter the url and images. So now the youtube URLs will be shown as link.

**Comment by rrjanbiah** [comment]
@lmarikannan Cool
