### ISSUE TITLE
In email notifications, formatting is slightly off

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1356]
## Expected Behavior

Markdown formats are correctly coming in email notifications

## Current Behavior

Some formats are not coming properly. Looks like there's an issue in markdown & diff handling

**Comment by sridhar391** [comment]
The markdown formats are correctly coming in email notifications

![markdown_formatting_email](https://user-images.githubusercontent.com/17172525/36259286-bcd1dd28-1283-11e8-80a2-5d8e57f92d6c.png)
