### ISSUE TITLE
Search and sorting of members for a card

### ISSUE THREAD

**Issue by lmarikannan** [RestyaPlatform/board#1357]
From Nick Crowdy,

When the   button is used to add a member to a card the search only seems to search for matches in the last name of the available list of members. This can be awkward in large organisation when a user wouldn't necessarily know the last name of all staff. It would be preferable if the search was looser, i.e. searched over more fields e.g. last name, first name, user id etc.

In addition, it would make navigation easier if the list was ordered alphabetically, it doesn't appear to use a natural order. Ideally, a profile setting would allow a user to change their preference for the ordering of the list.

**Comment by sridhar391** [comment]
The users only have full name and the users name fields, the search will match for the given value with user name and full name
