### ISSUE TITLE
Filtering cards is hard with a large number of labels and members

### ISSUE THREAD

**Issue by lmarikannan** [RestyaPlatform/board#1358]
The Filter Cards starts to get unmanageable when the number of labels and or the number of members is large.

There are a couple of things that would improve usability.
1. Provide Filter my cards button or menu item which provides a shortcut to filtering all cards where the current user is a member.
 2. Separate the Filter by Labels and Filter by Members into 2 separate menu items. A tick, Unicode Check Mark U 2713, could be used to indicate that a filter of that type has been applied.

**Comment by sridhar391** [comment]
Duplicate #1510
