### ISSUE TITLE
Syntax Highlighting ignored

### ISSUE THREAD

**Issue by sfkleach** [RestyaPlatform/board#1359]
## Expected Behavior

Git-flavoured markdown supports syntax-highlighting for a variety of languages by inserting the name of a programming language after three backticks. Here is an example taken from https://guides.github.com/features/mastering-markdown/ - a document I was referred to when I enquired about this by info@restya.com.

    ```javascript
    function fancyAlert(arg) {
      if(arg) {
        $.facebox({div:'#foo'})
      }
    }
    ```
The above should be rendered as
```javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```

## Current Behavior

In both my local deployment of Restyaboard _and_ the demo version at http://board.demo.restya.com/, the language directive is ignored. The result is that the code is treated as preformatted text i.e. no highlighting/colouring. In other words it looks like the block shown below.

```
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```

## Possible Solution

Perhaps a required module (such as CodeRay) has not been installed?

## Steps to Reproduce (for bugs)

1. Create a new card.
2. In the description field add the following text.

    ```javascript
    function fancyAlert(arg) {
      if(arg) {
        $.facebox({div:'#foo'})
      }
    }
    ```

3. Save the description.
4. The contents of the description are rendered without syntax highlighting/colouring and do not match the example shown in the Syntax Highlighting section of Mastering Markdown.

## Context

* The ability to reference snippets of code with improved readability.

## Your Environment

* http://restya.com/board/demo, 30th Sept 2017. (I don't know how to get the version number sorry.)
* Local installation based on restyaboard.sh inside Docker container. v0.5.2, Ubuntu 16.04.

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/a7300a71c8d8cd65986dbfd6107a5aeee5ebb034
