### ISSUE TITLE
login IP is not getting updated in users listing

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#136]
Seems to happen only in v0.1.6

**Comment by ssivachidambaram** [comment]
Fixed. https://github.com/RestyaPlatform/board/commit/5ae52493d87e19a40e207c13f7dcfa461fc91145

**Comment by rrjanbiah** [comment]
Also mentioned in #183

@ssivachidambaram Have we handled register IP cases too? (reopening for this)

**Comment by ssivachidambaram** [comment]
@rrjanbiah Yes. Handled in both cases.
