### ISSUE TITLE
Window does not scroll when dragging card

### ISSUE THREAD

**Issue by ccrabtree10** [RestyaPlatform/board#1361]
## Expected Behavior
When dragging a card, if the card touches the edge of the window, the window should scroll in that direction.

## Current Behavior
The window does not scroll when you drag a card to its edge.

## Steps to Reproduce (for bugs)
1. Create a board with several lists so that all do not fit in one window.
2. Create a card in the leftmost list.
3. Drag the card to the right of the window.

## Context
We currently have 8 lists on a board and all do not fit easily on one screen. We often need to move cards from the leftmost list to the rightmost list.

## Your Environment
Server: Restyaboard 0.5.2 on Oracle Linux 6
Client: Firefox 56.0 on Windows 10

**Comment by lmarikannan** [comment]
@ccrabtree10 Can you please mention your window resolution?

**Comment by ccrabtree10** [comment]
My screen is 1920 x 1080 and I have my browser window maximised.

**Comment by lmarikannan** [comment]
@ccrabtree10 We have tried to reproduce the issue but we cannot able to do it. If possible can you please reproduce and send as video?

**Comment by ccrabtree10** [comment]
Yep no problem, here you go:
[window not scrolling.zip](https://github.com/RestyaPlatform/board/files/1430968/window.not.scrolling.zip)

**Comment by lmarikannan** [comment]
@ccrabtree10 Thank you. We will check again and update you.
