### ISSUE TITLE
BUG past image

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#1362]
## Expected Behavior

When i paste image from clipboard in card it works but it also change my photo profil

## Steps to Reproduce (for bugs)
1. Take screenshot
2. open card
3. past image

## Your Environment
v0.5.2

**Comment by lmarikannan** [comment]
@morphos88 We have tried to reproduce this issue, but its working fine for us. Let me know any other test cases is there?

**Comment by morphos88** [comment]
i try to make video :
![2017-10-05_08h53_43](https://user-images.githubusercontent.com/25505555/31214602-36ae7458-a9ac-11e7-816c-b25a55d01aa4.gif)
