### ISSUE TITLE
Path to fpm socket file is hardcoded in install script

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1363]
As per Prem, path to fpm socket file is hardcoded and so they had to modify in some instances to get it working properly

(Related #1349)

**Comment by lgg** [comment]
@rrjanbiah is it fixed now?

**Comment by sridhar391** [comment]
@lgg we are checking on that

**Comment by lmarikannan** [comment]
@lgg @rrjanbiah Now the issue is fixed on this commit https://github.com/RestyaPlatform/board/pull/1661/commits/a16161545a3a707387fff7e2149c6a7559ff3b82
