### ISSUE TITLE
Transifex translation Portuguese (Brazil) broken

### ISSUE THREAD

**Issue by flashfs** [RestyaPlatform/board#1365]
## Expected Behavior
I remember I did many translations 4 months ago on Transifex website, so I expect to see them on restyaboard now.

## Current Behavior
I don't see where are my translations. I see many weird translations, like from Google Translate. When I go to Transifex website I really don't see my translations.

## Your Environment
* Version used: 0.5.2

**Comment by rrjanbiah** [comment]
@lmarikannan Please give high priority

**Comment by lmarikannan** [comment]
@flashfs Now we're changing and reverted translations on Transifex website, could you please check those changes on transifex website?

**Comment by flashfs** [comment]
I think it's all good now on transifex website.

**Comment by lmarikannan** [comment]
@flashfs Thank you for your confirmation. We're closing this.
