### ISSUE TITLE
Getting empty border after moving all cards from a list

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1366]
## Current Behavior

When I move all cards from a list, I'm getting some empty borders. Please check screenshot

## Screenshots

![restyaboard-empty](https://user-images.githubusercontent.com/4907427/31376223-cf565a5e-adc1-11e7-93b4-95164f684161.png)

**Comment by lmarikannan** [comment]
@rrjanbiah We cannot able to reproduce it.
