### ISSUE TITLE
Restyaboard White Page No Errors (?)

### ISSUE THREAD

**Issue by orangelynx** [RestyaPlatform/board#1367]
I'm setting up my custom docker based version of restyaboard. Please note that this is only remotely based on the "official" docker image, which I don't want to use because it doesn't follow certain docker philosophies. However I think that the problem is (if at all) only inherently docker related.

## Expected Behavior
Login Page when going to board.mydomain.com

## Current Behavior
White Page, nginx and php show loads these messages

`php_1       | - -  10/Oct/2017:13:35:43 +0000 "GET /server/php/R/r.php" 200
nginx_1     | 172.18.0.3 - - [10/Oct/2017:13:35:43 +0000] "GET /api/v1/oauth.json?_=1507642544159 HTTP/1.1" 200 226 "https://board.mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0" "155.69.160.32"
php_1       | - -  10/Oct/2017:13:35:44 +0000 "GET /server/php/R/r.php" 200
nginx_1     | 172.18.0.3 - - [10/Oct/2017:13:35:44 +0000] "GET /api/v1/oauth.json?_=1507642544570 HTTP/1.1" 200 226 "https://board.mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0" "155.69.160.32"
`

## Your Environment
* Version used: latest release zip
* Nginx, Postgres 9.6.5, php7-fpm
* debian latest / docker

No installation log available, because of manual installation. Database connection credentials have been tested and seem to work. info.php works as expected as well.

**Comment by rrjanbiah** [comment]
@orangelynx Please note that docker is from third party. However based on your error message, can you please share the response of API calls. Most likely it could be database credentials issue.

**Comment by orangelynx** [comment]
Hi,

the response always looks something like this:

`<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function pg_connect() in /usr/share/nginx/html/server/php/config.inc.php:60
Stack trace:
#0 /usr/share/nginx/html/server/php/R/r.php(23): require_once()
#1 {main}
  thrown in <b>/usr/share/nginx/html/server/php/config.inc.php</b> on line <b>60</b><br />`

My current suspicion is that I forgot to install the pgsql module for php, I will double check that.
