### ISSUE TITLE
Restyaboard turns white after some time / Cannot modify header information / cookies

### ISSUE THREAD

**Issue by orangelynx** [RestyaPlatform/board#1369]
I'm running Restyaboard in a custom docker setup. Everything seems to be working  more or less fine, however after a certain time, I can only see a white screen and when I check the HTTP traffic, I see

`{"username":"admin","expires":"2017-10-11 09:36:51","scope":"read write","client_id":"7742632501382313","error":{"type":"OAuth"}}<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /usr/share/nginx/html/server/php/bootstrap.php:66) in <b>/usr/share/nginx/html/server/php/bootstrap.php</b> on line <b>67</b><br />
`

Deleting all site related cookies brings me  back to the login page and the site functions for another few minutes / hours

I'm running the latest restyaboard release on debian / docker with postgres 9.6.5 and Firefox. Also, this restyaboard setup is running behind a reverse proxy.

**Comment by lmarikannan** [comment]
@orangelynx Can you please change debug mode to false in this line https://github.com/RestyaPlatform/board/blob/master/server/php/config.inc.php#L15

**Comment by orangelynx** [comment]
I did and reloaded php-fpm. I now see a "proper" json response, which shows an OAuth error. The js log still shows an error `18:55:48.859 TypeError: a is undefined 1 default.cache.c75390c7.js:28:12269`. I will now delete my cookies again and see if the bug persists.

**Comment by lmarikannan** [comment]
@orangelynx Could you please tell us, which language you are using in restyaboard?

**Comment by orangelynx** [comment]
The problem has occurred again. I'm using Restyaboard in English (UK) if I recall correctly, even though my browser has German signatures. Time zone is Zurich (I noticed there is Zurich two times, that drop down menu should be revised). I also may not have correctly set the time zone for php.

**Comment by orangelynx** [comment]
I still was not able to fix it. even with setting the correct time zone (Etc/UTC)

**Comment by lmarikannan** [comment]
> Time zone is Zurich (I noticed there is Zurich two times, that drop down menu should be revised).

For this issue, can you please refer this link https://github.com/RestyaPlatform/board/issues/1328

**Comment by orangelynx** [comment]
My current guess is that something goes wrong when a user tries to access the site with an outdated OAuth token. What should happen is that the user is taken back to the login page, but instead the process just stops.

**Comment by lmarikannan** [comment]
@orangelynx @rrjanbiah We have checked the same case but its working fine for us.

For some of the clients, we are getting error like this `Missing chunk number 0 for toast value 25432 in pg_toast_2619`. While analyze this, we got this link https://wiki.postgresql.org/wiki/Corruption. While checking this it may be due to RAM, CPU or some hardware problem.
