### ISSUE TITLE
Option to disable registration

### ISSUE THREAD

**Issue by tmikaeld** [RestyaPlatform/board#137]
Would be usable for private boards where only the admin manages users and accounts.

**Comment by ssivachidambaram** [comment]
You can disable the registration using roles page http://board.demo.restya.com/#/roles. In this page, uncheck the Register for Guest role.

**Comment by tmikaeld** [comment]
Aha, thanks! It's a bit of an odd place to put that setting though, but it guess it works.

**Comment by rrjanbiah** [comment]
> Aha, thanks! It's a bit of an odd place to put that setting though, but it guess it works.

@tmikaeld If you have any suggestion, please feel free to share
