### ISSUE TITLE
Edit and delete actions for admin should be placed "not that obviously" in comments listing

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1370]
## Current Behavior

From admin login, Edit and Delete actions are placed too closely next to Reply action. 

It should not be that too obvious and because of that accidental delete and edit are possible. Better to move it to right with some different colors or so.

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/294df1920d8ff75c5d1fb7145a7fe12550f317e9
