### ISSUE TITLE
Outdated oAuth token blanks out page instead of redirecting to login page

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1372]
From #1369 by @orangelynx 

My current guess is that something goes wrong when a user tries to access the site with an outdated OAuth token. What should happen is that the user is taken back to the login page, but instead the process just stops.

**Comment by lmarikannan** [comment]
@orangelynx @rrjanbiah We have checked the same case but its working fine for us.

For some of the clients, we are getting error like this `Missing chunk number 0 for toast value 25432 in pg_toast_2619`. While analyze this, we got this link https://wiki.postgresql.org/wiki/Corruption. While checking this it may be due to RAM, CPU or some hardware problem.

**Comment by orangelynx** [comment]
It is indeed possible that my DB got corrupted, I will check that. Where did you see that error, how can I analyse the system for myself?

**Comment by lmarikannan** [comment]
@orangelynx Download adminer (https://github.com/vrana/adminer/releases/download/v4.3.1/adminer-4.3.1-en.php) or phppgadmin (http://phppgadmin.sourceforge.net/doku.php?id=download) and connect to your database and click `oauth_access_token` or `oauth_refresh_token` table then if your database is corrupted then you can able to saw that message.

**Comment by orangelynx** [comment]
Thanks, I checked and I don't see any error. Is there any documentation that can help me debug the problem further? can I "step debug" what is happening when i go to the site?

**Comment by lmarikannan** [comment]
@orangelynx We need SSH or teamviewer access to understand more about your issue. Can you please contact through email info@restya.com?

**Comment by orangelynx** [comment]
I will do that.

**Comment by lmarikannan** [comment]
Fixed on this commit - https://github.com/RestyaPlatform/board/commit/1010c8e8883a6a5db565ad018e7826e6cc17f099

Header 401 was moved before json response.
