### ISSUE TITLE
Import from Trello and Wekan not working, nothing happens

### ISSUE THREAD

**Issue by darko190** [RestyaPlatform/board#1373]
Hi all

I have been trying to import some boards to Restya, but it doesn't work. Nothing happens, not even an error message.
Tried installing on a few servers and systems and it doesn't work either way.
I have found the troublesome lines:

2544
$utf8_encoded_content = utf8_encode($get_files);
2562
$utf8_encoded_content = utf8_encode($get_files);

I am using Croatian letters ččćžđš in my Trello boards.
The server is installed from restya by request and is newest version.

I have attached my error log 
[Error log](https://github.com/RestyaPlatform/board/files/1404127/Error.log)

When I import on the Restyaboard demo site, everything works and imports well.

**Comment by lmarikannan** [comment]
@darko190 While check your log file you got error as `Uncaught Error: Call to undefined function utf8_encode()`. So please install the `php7.0-xml` extension in your server. Please refer, https://stackoverflow.com/questions/35701730/utf8-endecode-removed-from-php7

**Comment by erl4nc** [comment]
@lmarikannan I had the same issue and installing php7.0-xml fixed it.  Thanks.
