### ISSUE TITLE
Assign Member - Instant Add Card

### ISSUE THREAD

**Issue by Erik-eMP** [RestyaPlatform/board#1375]
## Expected Behavior
To be allowed to assign people to boards where I have the permissions.
To not be allowed to assign people to boards where I have the permissions.
For every member only to be printed once in the dropdown table of members

## Current Behavior
If you want to add members via Instant Add Card, and you have different 'add member' permissions on various boards. The function is buggy
## Screenshots (if appropriate):
![assign](https://user-images.githubusercontent.com/31650102/31883052-ef85b618-b7e8-11e7-8d1a-1a5eb8e9d24b.png)

## Possible Solution
Do not load list of members if the user adding the card to not have permission to Add Members for this board.
## Steps to Reproduce (for bugs)

1. Don't have permission to add members
2. Try to add members via instant add card
3. See the list of members to add

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile): desktop, mac, chrome
* Link to your project: project.emailplatform.com

**Comment by lmarikannan** [comment]
Fixed on our local
