### ISSUE TITLE
User that own organization can't create boards

### ISSUE THREAD

**Issue by skonvols2k** [RestyaPlatform/board#138]
Hi,
on 0.1.6 if the admin create an organization and add a user making him owner of the organization, this user cannot create boards, the only way i can allow him to create boards is to change his role in admin.
Demo portal doesn't have this issue.
Thanks

**Comment by rrjanbiah** [comment]
@ssivachidambaram Possibly due to the DB import issue he's having? #122

**Comment by ssivachidambaram** [comment]
You can enable "Add board" option for user using roles page http://board.demo.restya.com/#/roles. Please refer the screenshot.
![roles](https://cloud.githubusercontent.com/assets/91407/12446487/508a8e50-bf90-11e5-8e84-93b7ed04f815.png)

**Comment by skonvols2k** [comment]
Thanks

**Comment by lehnen** [comment]
Thx, now all working
