### ISSUE TITLE
Comments disappear on cards with many checklists

### ISSUE THREAD

**Issue by Yasharah** [RestyaPlatform/board#1381]
i have a problem with cards that have many checklists/checklist-options. The comments on that cards just disappear. they are there after your wrote them, but they are not there anymore after you close the card and open it again. you still see the speech bubble on the card but there are no comments...

**Comment by sridhar391** [comment]
Related #1408 Initially we are fetching 20 activities only and using load more link we can load more activities. So in your case, load more link is not displayed to load more comments/activities. Now we fixed the load more link issue.
