### ISSUE TITLE
Only nginx welcome screen after installscript

### ISSUE THREAD

**Issue by goddib** [RestyaPlatform/board#1383]
I am trying to install Restyaboard within an LXC container using the installscript. The template is fresh so no other software is installed but in the end I only get an nginx welcome screen when accessing my IP address.

## Expected Behavior
After running the installscript I expect to be able to access Restyaboard by opening my server IP address in a browser.

## Current Behavior
When accessing the IP address I get a nginx welcome screen.

## Possible suggestions
I'm not sure but it seems PHP is not installing correctly?

## Your Environment
Proxmox based LXC container.
Ubuntu 16.04 template as operating system.
No further software installed.

[restyaboard_install.log](https://github.com/RestyaPlatform/board/files/1443990/restyaboard_install.log)

**Comment by lmarikannan** [comment]
@goddib While checking your install log file, php-imagick is not installed.

Can you please change the below line in `restyaboard.sh` file and try again?

`apt-get install -y php7.0-imagick`

=>

`apt-get install -y php-imagick`

**Comment by goddib** [comment]
@lmarikannan Thanks, that actually fixed it. The script completed this time and restyaboard seems to work.
