### ISSUE TITLE
Activity window doesnt work anymore after newest update

### ISSUE THREAD

**Issue by Yasharah** [RestyaPlatform/board#1388]
Hello,
i updated to the newest version with the script and now the activity window doenst work anymore. If i open it it just loads and loads and loads and nothing happens and sometimes its even not over the whole site and just at the bottom. I have to press the load more activities button and so i just see older activities or i press the all button...then it works. The in this board options just shows nothing.

**Comment by lmarikannan** [comment]
@Yasharah Sorry for this issue. We will fix it and update in release file immediately.

**Comment by lmarikannan** [comment]
@Yasharah Can you please rename attached file `default.cache.f1443ef3.js.txt` to `default.cache.f1443ef3.js` and overwrite in this path `/usr/share/nginx/html/restyaboard/client/js/`?

[default.cache.f1443ef3.js.txt](https://github.com/RestyaPlatform/board/files/1457568/default.cache.f1443ef3.js.txt)

**Comment by Yasharah** [comment]
i did that and rebootet the whole vm and it changed nothing sorry :/

**Comment by lmarikannan** [comment]
Can you please clear your browser cache and retry ?

Command in console to clear cache `localStorage.clear()`

**Comment by Yasharah** [comment]
i thought i did that, but obviously not..because its working now. thank you so much :)

**Comment by lmarikannan** [comment]
@Yasharah Welcome :)
