### ISSUE TITLE
IMAP doesn't work 

### ISSUE THREAD

**Issue by Yasharah** [RestyaPlatform/board#1393]
Hello, 
I tried to use the IMAP feature to create cards per Mail but I can't get it to work. I filled in all the infos and activated plus adressing and the mails arrive at the mail account but if I try to start the imap.sh myself I always get the error "PHP notice: undefined property: stdclass::parts..."

**Comment by Yasharah** [comment]
okay now 3000 tries later "it is working"...the name of the card is fine, but the message text that should land in the description filed is just the first letter of my message text. The same happens if i use the replay via mail button in the emails...just the first letter lands in the comment field.

i think its a layer 8 error and my fault..is there some docu somewhere, where it is explained how i use this feature?

**Comment by bseclier** [comment]
Same problem here. It works if you send a mail in html format but it doesn't if you send a mail in text format. It would be great to patch it for the next release.
