### ISSUE TITLE
Preview in comment & description

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#1402]
## Expected Behavior
1. Add comment or description with markdown content on Card
2. Click preview tab for the live preview of markdown content in converted format On card

## Screenshots (if appropriate):
![comment_and_description_preview](https://user-images.githubusercontent.com/17172525/33512933-0b3a8dbc-d75f-11e7-935f-817f5f317b3d.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
Comment and description markdown content can be previewed in live on Card.

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by rrjanbiah** [comment]
Reopening for lack of proper description

**Comment by baskar383** [comment]
Description changed
