### ISSUE TITLE
Linking to NixOS in download options

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1405]
## Context

NixOS has now first class integration for Restyaboard now! https://github.com/NixOS/nixpkgs/commit/67ce1357fac761342cdb72c0b5e14fb0bb4ca24c

Have to link it in Restyaboad download options

**Comment by ts468** [comment]
Hi!

Thanks for your amazing work on Restyaboard! I liked it so much that I decided to integrate it into NixOS.

For an even smoother deployment it would be good to enhance the user management options of Restyaboard in NixOS. For example, I'm wondering if you have any plans to add an OpenID Connect authentication option and whether you could maybe imagine to provide the LDAP plugin for free? With these two options available one could add Restyaboard seamlessly to, e.g., an existing Single-Sign-On setup. I know it is asking for a lot to make your LDAP plugin available for free, but in return I could offer to add proper support in NixOS to extend Restyaboard with commercial plugins as well.

As a general note, NixOS provides a lot of interesting tooling to e.g. generate container images with pre-installed software. So in case you're thinking about offering e.g. Docker container images for Restyaboard, then maybe it would be worth looking at what NixOS provides.

**Comment by rrjanbiah** [comment]
@ts468 Thanks for your kind words. We need to internally discuss to take it forward. In the mean time, please share your Skype handle through our email: info at our domain

Thank you

**Comment by rrjanbiah** [comment]
@itzmeank Looks like we missed this one

**Comment by sridhar391** [comment]
NixOS download link has been added to the download option and will be available after the release
