### ISSUE TITLE
"Free Installation" not trusty

### ISSUE THREAD

**Issue by CodeBrauer** [RestyaPlatform/board#1406]
I've just tried to install it on myself, didn't work well. So now I tried you "Free Installation"-service.

So they connected via skype and asked for a user to install restya.
Of cause I setup some shell rules so the external_username can't access commands like su/passwd etc.

Just checked the command history and this is definitely not a trusty support member that want to lock me out: https://gist.github.com/CodeBrauer/7cb1b1614f3b4b70eab4a079bee84e48

**Comment by rrjanbiah** [comment]
@CodeBrauer I'm checking with the team and will update

**Comment by rrjanbiah** [comment]
@CodeBrauer 

Please find https://www.dropbox.com/s/5wce9uaq8vcefo6/rb-history-reasons.txt?dl=0 for reasons from IT team. If anything is wrong or not convincing, please feel free to reply. I'll try my best to provide better answers. As you have my Skype handle, you can also connect me via Skype; I'll try to arrange a conference call with IT team in case if you want more explanation.

**Comment by rrjanbiah** [comment]
@CodeBrauer 

Moreover the idea of "Free Installation" is help people who cannot use our install script for any reason. Some people earlier had difficulties as the script was not working across all Linux distros. So, instead of wasting more time by themselves and just opening a ticket, we thought that we could help them to get it installed quickly.

I'm sorry, it didn't work as expected for you. In case, if you have any suggestion for us, please feel free to share.

**Comment by CodeBrauer** [comment]
So I rechecked the logs. Seems that someone else somehow got into the system. Your IP address was from India as I checked, but the sshd logs show another IP from China which actually connected before your team connected. So this suspicious user could have executed commands 1-18...

We shared the credentials directly from my terminal session to the newest version of Skype. No idea how the attacker could get the credentials  😕

**Comment by rrjanbiah** [comment]
@CodeBrauer Thanks for your detailed review. Please check if you have any malwares in your system; we'll also do the same from our end. In future, we'll ask our users to restrict the SSH access to our IPs and will see the possibility to share credentials through PGP. In case if you have any more suggestions, please feel free to share. Thanks again for your time.

**Comment by CodeBrauer** [comment]
Yes, basically it isn't a big deal for us, because the account was restricted anyway + the system itself is just a docker container so there is no big problem on the server side.

**Comment by rrjanbiah** [comment]
@CodeBrauer Thank you. Glad to hear that
