### ISSUE TITLE
Stretched Attachments/Pictures

### ISSUE THREAD

**Issue by ssivachidambaram** [RestyaPlatform/board#1416]
From Google Groups,

https://groups.google.com/forum/#!topic/restya/RFedCbBpfd0

I've installed a fresh restyaboard on a newly installed Ubuntu 16.04 LTS with the help of the install script (restyaboard.sh). During the installation process, all went fine. 
After all, the restyaboard works fine. I only have one little problem and can't find any usefull advice, so I will ask here: when I try to Upload pictures as attachments, these pictures are stretched to full size. This problem is repeatable on different clients and browsers, so one "defective" browser can be excluded.Do you have any ideas, what is going wrong during the upload of this picture?

## Screenshots (if appropriate):

![restya_problem_original](https://user-images.githubusercontent.com/91407/33932886-2fc5d6b4-e01a-11e7-85a4-35bace812c56.jpg)

![restya_problem](https://user-images.githubusercontent.com/91407/33932880-2a2c51ce-e01a-11e7-8cc7-d63ae23e4225.png)

![restya_problem_2](https://user-images.githubusercontent.com/91407/33932882-2cfa4c6c-e01a-11e7-91e1-b024321a827e.png)

**Comment by ssivachidambaram** [comment]
From Google Groups,

https://groups.google.com/forum/#!topic/restya/RFedCbBpfd0

Same problem:
It is not a cropping but a wrong rescaling of the thumbnail.
The proportions (length / width) in the thumbnail are distorted.
A flat rectangle is distorted to a square-like image.
I suspected some ImageMagick-options, but I can not get any further.

**Comment by khklein** [comment]
Found similar bug in your official demo 
if you add an image, the preview will be streched ( in our system the regular board view too)

Restya Demo:

![preview-bug](https://user-images.githubusercontent.com/37366403/37395037-897e4018-2775-11e8-9dbb-dc61a1a81d52.jpg)
![board-view-ok](https://user-images.githubusercontent.com/37366403/37395114-b9344f3c-2775-11e8-98e0-4501fefecec0.jpg)

Local Installation:
![board-view-bug](https://user-images.githubusercontent.com/37366403/37395263-1ea7d4ce-2776-11e8-8012-26328e9c8a9b.jpg)

**Comment by rrjanbiah** [comment]
From Markus through forum:

in my opinion, the streteched-images problem isn't fixed. I've updated my test system to 0.6.4 and uploaded some new pics - they are still stretched :/

https://groups.google.com/forum/#!topic/restya/RFedCbBpfd0
https://github.com/RestyaPlatform/board/issues/1416

**Comment by sridhar391** [comment]
The images are not stretched while uploading in modal card page, while we try to upload them in the live demo site: http://board.demo.restya.com and we have attached the screenshot of uploaded attachments in modal card page with different sizes

**Comment by sridhar391** [comment]
We are unable to reproduce the issue on our demo server while uploading different sizes of images

**Comment by maickel** [comment]
I just tried to attached an image on a fresh installation 
(last version + Ubuntu 16.04.4), but still stretched.
But I also tried on your demo board, and it seems to work fine there.

![stretch_restya](https://user-images.githubusercontent.com/2687492/41569457-cec10c7c-739d-11e8-88b0-0c603cf237b7.jpg)

What's the difference ?

**Comment by maickel** [comment]
In 
_board/server/php/config.inc.php_
I found an hardcoded ratio : 
```php
'CardAttachment' => array(
        'small_thumb' => '108x78',
        'medium_thumb' => '153x153',
        'large_thumb' => '202x151'
    )
```
Seems to be the exact same size I have in my boards

**Comment by ssivachidambaram** [comment]
@maickel We have fixed the issue and updated the code. Please refer https://github.com/RestyaPlatform/board/commit/9f66b8678ef294effdf1d2a6e78210e75baf12f1.
