### ISSUE TITLE
Checklist changes don't reflect without page refresh

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1428]
From Łukasz

## Current Behavior

Wwhen somebody change an item in checklist, It doesn't refresh in the other person and person doesn't see changes.

**Comment by ssivachidambaram** [comment]
Related #1391

**Comment by sridhar391** [comment]
@rrjanbiah Now when somebody changes an item in the checklist or remove an item from the checklist, It will be live updated in another person without refresh.
This has been solved in the #1420
