### ISSUE TITLE
What's up with the card view layers not overlapping?

### ISSUE THREAD

**Issue by mauzao9** [RestyaPlatform/board#143]
As on this image from the demo: http://i.imgur.com/1jVsRs3.png

The side bar, says under, any menu i try to click will not open correctly if the size is not big enough, what sometimes even on the expanded view isn't and the buttons stay.

**Comment by rrjanbiah** [comment]
@mauzao9 Our UX/UI team intentionally did it to be responsive. Reasons are:

* In normal view, if we put everything one by one, the comment box will go bottom (will need to scroll)
* In expanded view, you can adjust the divider by dragging

Please let us know if you have any other thoughts here

**Comment by rrjanbiah** [comment]
@mauzao9 Sorry, accidentally closed. Would like to hear your feedback.

**Comment by mauzao9** [comment]
When i poked surrounding this, it really feels like a bug mostly because part of the functionality is broken on the default layout, and some on the extended, when the popup, etc...  When it doesn't fit.

So it ends up all merged into that default normal space and cuts everything horizontally over that X.

**Comment by rrjanbiah** [comment]
@mauzao9 Since this is an intentional thing, I'm not sure if our UX/UI team will have any solution for that. If you have any suggestion, please feel free to share.

**Comment by ssivachidambaram** [comment]
Fixed.
