### ISSUE TITLE
Refused to get unsafe header "x-response-url" error from app.js of apps

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1433]
## Current Behavior

Getting "Refused to get unsafe header "x-response-url"" error from all apps.

## Your Environment
* Browser: Chromium Version 63.0.3239.84 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (32-bit)

**Comment by baskar383** [comment]
Fixed in local commit
