### ISSUE TITLE
When translations are updated?

### ISSUE THREAD

**Issue by xchopin** [RestyaPlatform/board#1434]
Hi,

I contributed to your transifex project but I was wondering who should send a pull request (everyone or a Restya employee) ? if it's the second case when translations are updated on the repository (on request, each new release, etc...) ?

Thanks

**Comment by ssivachidambaram** [comment]
@xchopin We will pull and update in repository on each release.

**Comment by xchopin** [comment]
Thank you

**Comment by xchopin** [comment]
By the way do you give credits to the translators ?

**Comment by rrjanbiah** [comment]
@xchopin Yes http://restya.com/board/credits
