### ISSUE TITLE
The client credentials are invalid

### ISSUE THREAD

**Issue by andreadotta** [RestyaPlatform/board#144]
hi,
 after new self-hosted installation with restyaboard.sh at any first login I got this message:

"error":"invalid_client","error_description":"The client credentials are invalid","user"

thanks in advance
A

**Comment by rrjanbiah** [comment]
@andreadotta Perhaps you've updated ``OAUTH_CLIENT_SECRET`` in https://github.com/RestyaPlatform/board/blob/master/server/php/R/config.inc.php#L25 ?

If so, you have to also update that in ``oauth_clients`` DB table.

Please confirm

**Comment by andreadotta** [comment]
|OAUTH_CLIENT_SECRET| is unchanged both in config and DB
A
Il 25/01/2016 17:14, R. Rajesh Jeba Anbiah ha scritto:
>
> @andreadotta <https://github.com/andreadotta> Perhaps you've updated 
> |OAUTH_CLIENT_SECRET| in 
> https://github.com/RestyaPlatform/board/blob/master/server/php/R/config.inc.php#L25 
> ?
>
> If so, you have to also update that in |oauth_clients| DB table.
>
> Please confirm
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/RestyaPlatform/board/issues/144#issuecomment-174558315>.
>


-- 
-------------------------------------------------
Andrea Dotta
mobile: +39 338 1335897
skype: bauhausk
linkedin: http://www.linkedin.com/in/andreadotta
www.xkoll.com

-------------------------------------------------

La presente comunicazione, che potrebbe contenere informazioni riservate e/o protette da segreto
professionale, è indirizzata esclusivamente ai destinatari della medesima qui indicati.
Le opinioni, le conclusioni e le altre informazioni qui contenute, che non siano relative alla nostra
attività caratteristica, devono essere considerate come non inviate né avvalorate da noi.
Tutti i pareri e le informazioni qui contenuti sono soggetti ai termini ed alle condizioni previsti
dagli accordi che regolano il nostro rapporto con il cliente.
Nel caso in cui abbiate ricevuto per errore la presente comunicazione, vogliate cortesemente darcene
immediata notizia, rispondendo a questo stesso indirizzo di e-mail, e poi procedere alla cancellazione
di questo messaggio dal Vostro sistema. E’ strettamente proibito e potrebbe essere fonte di violazione
di legge qualsiasi uso, comunicazione, copia o diffusione dei contenuti di questa comunicazione da parte
di chi la abbia ricevuta per errore o in violazione degli scopi della presente.

This communication, that may contain confidential and/or legally privileged information, is intended solely
for the use of the intended addressees. Opinions, conclusions and other information contained in this message,
that do not relate to the official business of this firm, shall be considered as not given or endorsed by it.
Every opinion or advice contained in this communication is subject to the terms and conditions provided by
the agreement governing the engagement with such a client. If you have received this communication in error,
please notify us immediately by responding to this email and then delete it from your system. Any use, disclosure,
copying or distribution of the contents of this communication by a not-intended recipient or in violation of the
purposes of this communication is strictly prohibited and may be unlawful.
        
Please consider the environment before printing this email

**Comment by rrjanbiah** [comment]
@andreadotta

> at any first login I got this message:

Does it work after that? If not can you see if you can attach the install log file. Please review content for any sensitive data before uploading.

**Comment by ssivachidambaram** [comment]
Could not reproduce this issue.
