### ISSUE TITLE
Displaying organization info when listing boards

### ISSUE THREAD

**Issue by ssivachidambaram** [RestyaPlatform/board#1454]
From Google Groups,

https://groups.google.com/forum/#!topic/restya/VIc1QhDNmGo

We are already started to test Restya for the management of our business processes. We are using organization structure to organize boards. Bu did not work well. Because there may be some boards with same name and  it can be confusing in board listings.

So may be add here a kind of update request. Would you please include organization name before the board name when listing boads. Such as; Organization 1 > My Board 1 etc..

**Comment by rrjanbiah** [comment]
Internal note: Retest if organization icon is not working

**Comment by lmarikannan** [comment]
@ssivachidambaram Now the organization name and icon is displaying on the board header. So we can track that board with organization name and icon.
