### ISSUE TITLE
There is too much space between Add Comment form and comment button

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#1457]
## Expected Behavior
1. Go to card page
2. Open modal card and for commenting on particular issue place enter the comments in Add comment 
   Form input.
3. There should be enough space between input and comment button
 
## Current Behavior
1. Go to card page
2. Open modal card and for commenting on particular issue place enter the comments in Add comment 
   Form input.
3. There is too much space between input and comment button

## Screenshots (if appropriate):
![sapce_comment](https://user-images.githubusercontent.com/17172525/34551899-ccfa1712-f143-11e7-8fa3-11261f6660f4.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by baskar383** [comment]
Fixed on this commit 500d7972223b0d23e9033b5307f2d43cf67ef585
