### ISSUE TITLE
In users page in the roles for admin the roles are aligned improperly

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#1460]
## Expected Behavior
1. Go to users page.
2. For admin the role is set to Admin.
3. In the dropdown menu of role, roles are aligned properly.

## Current Behavior
1. Go to users page.
2. For admin the role is set to Admin.
3. In the dropdown menu of role, roles are not aligned properly.

## Screenshots (if appropriate):
![admin_role](https://user-images.githubusercontent.com/17172525/34553400-4cf97f58-f14d-11e7-93e4-2ba4289d6d84.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by baskar383** [comment]
Fixed on this commit 500d7972223b0d23e9033b5307f2d43cf67ef585
