### ISSUE TITLE
Show the number of cards

### ISSUE THREAD

**Issue by YutoKaneko** [RestyaPlatform/board#1474]
## Expected Behavior

On each of lists, display the number of cards.
It's like "CardCounter for Trello". https://chrome.google.com/webstore/detail/cardcounter-for-trello/miejdnaildjcmahbhmfngfdoficmkdhi

**Comment by BlackDark** [comment]
Currently I am trying to include a counter for the displayed view for the board/lists.
So far I see different inconsistencies in both model & rendering of the components.

In `list_view.js` is the `renderCardsCollection` method where I started with adding a rendering method for updating the counter for the cards.
So far so good. This only works in some scenarios.
For example when adding a new card the model is not updated in time (that means when the render method is called the model does not contain the new data). => Inconsistent
Another point is the `model.cards` and `board.lists.model.cards` they seem to be also not linked and in sync.
A far more annoying one is the filtering. When I started to implement the issue I thought that you kinda render the view according to the model and the model does always stay in sync. But your filtering algorithm does remove the view objects depending on the filtering arguments in the URI. I think you could save up quite a bunch of code and complexity if you would try to manage the rendering through the model. That means for the example with filtering:
1. Process the filter parameters
2. Modify the view model accordingly
3. Trigger rendering of the modified UI components (like react)

This are only some thoughts that I got so far scanning through the code and trying to include the card numbers In a clever and comfortable way. Maybe you/we could try to optimize the code base to improve the code quality.

My question to solve the issue. Are there some methods or ways where I can get the necessary up-to-date information for the drawing of the card numbers (in `list_view.js`). For example view callback or anything?

Thanks in advance.

My progress so far:
<img width="558" alt="t" src="https://user-images.githubusercontent.com/9947112/38173278-db0f146c-35bb-11e8-84a7-9115f3891e24.png">

**Comment by sridhar391** [comment]
Please note that the conversation about this issue is going in https://github.com/RestyaPlatform/board/pull/1732/files#diff-91b484199d580d0aae8eff571442cd96
