### ISSUE TITLE
Presumably debugging code in repo

### ISSUE THREAD

**Issue by maxhq** [RestyaPlatform/board#1476]
I think the hard coded client id is debugging code:
https://github.com/RestyaPlatform/board/blob/981104f5c01fdb7e6d79f3809ed7a9e0c57c8a44/server/php/shell/periodic_email_notification.php#L364
(Added in b98781b3eb7e878a630f3718fa028377f415122d)

**Comment by ssivachidambaram** [comment]
@maxhq Yes. Previously it will delete the expired tokens of all OAuth clients. But for Zapier we need long live access tokens. So for temporary purposes we have added this. And also need to handle expires dynamically based on OAuth clients.

**Comment by maxhq** [comment]
@ssivachidambaram I see, thank you very much for the explanation.
