### ISSUE TITLE
Few action links are hidden and had to scroll to view them

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#148]
From anrc.class through https://groups.google.com/forum/#!topic/restya/08mIc5PyDGo

I've noticed on a few card input options that options are sometimes hidden and you have to scroll to see them. For example clicking Add Attachment produces the "From Computer" and "From DropBox" links down below the visible left pane.  This is also evident in the Delete functions as well.  I've tested in multiple browsers (Chrome, Safari, and Firefox) and on the demo site.  Screenshot below showing the issue:

**Comment by ssivachidambaram** [comment]
Fixed.
