### ISSUE TITLE
Copying board shows comment icon but no comments

### ISSUE THREAD

**Issue by maxhq** [RestyaPlatform/board#1482]
If a board is copied incl. cards and the cards had comments, in the new board the card comment indicator is still shown but the card details do not show any comments.

## Expected Behavior
Maybe have a choice to also copy card comments, I guess usually it is not desired as general information should be in the card description.
If card comments are not copied, do not show comment icon on cards (board view).

## Current Behavior
See above, I dont know if the comments are not copied or just not shown.

## Your Environment
- Version used: v0.6
- Environment: Debian Stretch (Docker), PHP 7.0.19-1, PostgreSQL 9.6

**Comment by sridhar391** [comment]
@maxhq Now when a board is copied including cards and the cards had comments, in the new board the card comment count will not be shown and in the card details comments will not be shown.
