### ISSUE TITLE
Login IOS App 

### ISSUE THREAD

**Issue by gitotp** [RestyaPlatform/board#1507]
I am new user and installed latest Version 0.6.  which is nice Tool and it works via the browser on the PC and IPhone.

Unfortunately the IOS APP won't work. You enter the URL and Login data, then you are asked if you want to let the Mobile App appliaction use to your Account (Allow) and then either you get a Request failed or nothing happens but a loading sign.

Using Apache Webserver and the corresponding .htaccess rewrites.

HTTP and HTTPS both won't work.

![image](https://user-images.githubusercontent.com/35888083/35480666-a0327d18-0413-11e8-8420-ec718b2e26a3.png)

Last Apache Message is:
dns name removed:80 IP removed - - [28/Jan/2018:08:51:23 +0100] "POST /oauth/authorize?response_type=code&client_id=6664115227792148&state=1456750015553&redirect_uri=restyaboard://http://dns name removed/&scope=read%20write HTTP/1.1" 200 1314 "http://dns name removed/oauth/authorize?response_type=code&client_id=6664115227792148&state=1456750015553&redirect_uri=restyaboard://http://dns name removed/&scope=read%20write" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_2 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C202"

dns name removed:80 IP removed - - [28/Jan/2018:08:51:26 +0100] "POST /oauth/authorize?response_type=code&client_id=6664115227792148&state=1456750015553&redirect_uri=restyaboard://http://dns name removed/&scope=read%20write HTTP/1.1" 302 1194 "http://dns name removed/oauth/authorize?response_type=code&client_id=6664115227792148&state=1456750015553&redirect_uri=restyaboard://http://dns name removed/&scope=read%20write" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_2 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C202"
OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C202"

**Comment by sridhar391** [comment]
@gitotp can you please provide us your domain link

**Comment by gitotp** [comment]
@sridhar391 Thanks for your request. I don’t like the idea of posting the domain link public for security reasons. But I am happy to troubleshoot or provide logs/information as they are available in the system.

**Comment by lgg** [comment]
I faced the same error. No errors in nginx logs. What logs i need to check?

**Comment by sridhar391** [comment]
@gitotp, @lgg can you please provide us your domain link at info@restya.com

**Comment by lgg** [comment]
Done, please check Email

>

**Comment by lgg** [comment]
@sridhar391 Done, please check Email

**Comment by sridhar391** [comment]
@lgg we got your mail with  domain link, we are checking on our local app

**Comment by lgg** [comment]
@sridhar391 i replied you on email.

**Comment by lgg** [comment]
@gitotp any updates on this?

**Comment by lgg** [comment]
@gitotp check https://github.com/RestyaPlatform/board/pull/1550/

**Comment by sridhar391** [comment]
@lgg Fixed this issue in pull request #1550

**Comment by sridhar391** [comment]
@gitotp we are waiting for your domain link

**Comment by lgg** [comment]
@sridhar391 i tried: `psql -U restya -d restya -a -f update.sql` where `update.sql` was https://github.com/RestyaPlatform/board/blob/adca0907116c4784c960a02acf6fe8b4ee3897f0/sql/upgrade-0.6.1-0.6.2.sql

but got error:
```
postgres@taskmanager:~$ psql -U restya -d restya -a -f update.sql | grep ERROR
psql:update.sql:1: ERROR:  relation "custom_fields" does not exist
psql:update.sql:3: ERROR:  view "custom_fields_listing" does not exist
psql:update.sql:28: ERROR:  relation "custom_fields" does not exist
LINE 25:     FROM custom_fields custom_field;
                  ^
psql:update.sql:30: ERROR:  view "cards_elasticsearch_listing" does not exist
psql:update.sql:96: ERROR:  relation "cards_custom_fields" does not exist
LINE 59:                            FROM (cards_custom_fields cards_c...
                                          ^

```

**Comment by sridhar391** [comment]
@lgg we have updated your server and SQL will be removed and will put in the separate file

**Comment by lgg** [comment]
@sridhar391 great thank you for help! If you can, please answer to email.

**Comment by gitotp** [comment]
Great job restyaboard team! I upgraded to v0.61 first(since it was released meanwhile) and then applied and the sql Patch and the App is able to login to the board now.
Thank you!

**Comment by sridhar391** [comment]
@gitotp @lgg Thank you for your support
