### ISSUE TITLE
Card ownership not changed when copying board from another user 

### ISSUE THREAD

**Issue by maxhq** [RestyaPlatform/board#1508]
If a board is copied from another user, the new boards' cards still have the `user_id` of the original boards' creator.

## Expected Behavior
- *user A* creates a board *board A*, adds lists and cards
- *user B* copies the board into *board B*
- cards of *board B* should be owned by *User B*

## Current Behavior
- cards of *board B* are owned by *user A* (as seen in the servers' JSON response)

## Your Environment
- Version used: v0.6
- Environment: Debian Stretch (Docker), PHP 7.0.19-1, PostgreSQL 9.6

**Comment by sridhar391** [comment]
@maxhq We have checked with Trello and they are having same ownership of original board to the copied board, can you please explain more about this card ownership

**Comment by sridhar391** [comment]
@maxhq we are closing this issue currently. if the issue still exists please reopen this issue

**Comment by maxhq** [comment]
Example:
**Alice** has *user_id = 1*
**Bob** has *user_id = 2*
IMHO if **Bob** copies a board from **Alice**, then **Bob**s new board is owned by him (which Restyboard does as expected: the board's *user_id = 2*).
But now all the copied cards in **Bob**s new board are still owned by **Alice** (they have *user_id = 1*), which seems quite inconsistent to me. Bob might modify them and they still belong to Alice, who does not know anything about them.

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/e546ed2973b020269a899e1423efebe5f16e311f

**Comment by lmarikannan** [comment]
@maxhq Now we've an option to keep users on copy board form, if we select keep users checkbox means, it'll copy all users and them roles from that particular board to copied board, otherwise the copied user will be the board owner of the copied board. And these changes will be updated on our future release
![copy_boards](https://user-images.githubusercontent.com/17758064/36464312-30cda12e-16f5-11e8-9915-2c3067fe679b.png)

**Comment by maxhq** [comment]
@lmarikannan @ssivachidambaram Thank you very much for implementing!
