### ISSUE TITLE
Flickr background images do not respect protocol

### ISSUE THREAD

**Issue by shortjared** [RestyaPlatform/board#151]
The flickr images, when used for the background and displayed via the api in the selector, are hard coded to the http protocol.

Browsers then complain about loading assets over non-secure connections and will no longer display the security indicators.

Fixes needed:
https://github.com/RestyaPlatform/board/blob/77bd1d87bec8e4d55d933d7acf0e7df05bf50c3d/client/js/templates/flickr.jst.ejs#L3

https://github.com/RestyaPlatform/board/blob/fde9693b1019f71f14382f41ba459a2fcf27ba92/client/js/views/modal_flickr_photo_view.js#L190
https://github.com/RestyaPlatform/board/blob/fde9693b1019f71f14382f41ba459a2fcf27ba92/client/js/views/modal_flickr_photo_view.js#L199
https://github.com/RestyaPlatform/board/blob/fde9693b1019f71f14382f41ba459a2fcf27ba92/client/js/views/modal_flickr_photo_view.js#L222

**Comment by rrjanbiah** [comment]
@shortjared Many thanks for reporting this issue. We'll fix it in upcoming release.

**Comment by rrjanbiah** [comment]
Fixed https://github.com/RestyaPlatform/board/commit/d9b0a82670606a9398a83cb51948e7c3efc4efc2
