### ISSUE TITLE
Nginx configuration for restyaboard

### ISSUE THREAD

**Issue by IssueFindings** [RestyaPlatform/board#1525]
Hello,

I have just finalised the installation of Ratsyaboard on my Raspberry (Stretch version). I use Nginx to provide access to my self-hosted version of Restyaboard (the last version 0.6.1). The automatic installation works well. To enforce security of my https connexion (based on feed back of https://securityheaders.io/ and https://www.ssllabs.com/ssltest/), I modify the nginx configuration as below.

`server {
    listen 80;
    server_tokens off;
    server_name mywebsite;

    location '/' {
        return 301 https://mywebsite$request_uri;
        }
    }

    server {
        listen 443;
        ssl on;

        ssl_protocols TLSv1.2;

        ssl_certificate      /certificate/mywebsite/fullchain.pem;
        ssl_certificate_key  /certificate/mywebsite/privkey.pem;

        ssl_session_cache none;
        ssl_session_tickets off;

        ssl_stapling on;
        resolver 80.67.169.12 valid=30s;
        resolver_timeout 5s;
        ssl_stapling_verify on;
        ssl_trusted_certificate /certificate/mywebsite/chain.pem;

        ssl_dhparam /etc/nginx/dhparam.pem;

        ssl_prefer_server_ciphers on;
        ssl_ciphers '!kEECDH+ECDSA+AES128 kEECDH+ECDSA+AES256 !kEECDH+AES128 kEECDH+AES256 !kEDH+AES128 kEDH+AES256 +SHA !aNULL !eNULL !LOW !kECDH !DSS !MD5 !RC4 !EXP !PSK !SRP !CAMELLIA !SEED';

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
        add_header Content-Security-Policy "default-src https://mywebsite:443"; 
        add_header X-Frame-Options "DENY"; 
        add_header X-Xss-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";
        add_header 'Referrer-Policy' 'no-referrer';

        server_name mywebsite;
        server_tokens off;
        root /usr/share/nginx/html/restyaboard;
        index  index.html index.php;
        client_max_body_size 300M;

        rewrite ^/oauth/authorize$ /server/php/authorize.php last;
        rewrite ^/oauth_callback/([a-zA-Z0-9_\.]*)/([a-zA-Z0-9_\.]*)$ /server/php/oauth_callback.php?plugin=$1&code=$2 last;
        rewrite ^/download/([0-9]*)/([a-zA-Z0-9_\.]*)$ /server/php/download.php?id=$1&hash=$2 last;
        rewrite ^/ical/([0-9]*)/([0-9]*)/([a-z0-9]*).ics$ /server/php/ical.php?board_id=$1&user_id=$2&hash=$3 last;
        rewrite ^/api/(.*)$ /server/php/R/r.php?_url=$1&$args last;
        rewrite ^/api_explorer/api-docs/$ /client/api_explorer/api-docs/index.php last;

        location / {
                root /usr/share/nginx/html/restyaboard/client;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"; #Activation de HSTS
        add_header Content-Security-Policy "default-src https://mywebsite:443"; 
        add_header X-Frame-Options "DENY"; 
        add_header X-Xss-Protection "1; mode=block"; 
        add_header X-Content-Type-Options "nosniff"; 
        add_header 'Referrer-Policy' 'no-referrer'; 
        }

        location ~ \.php$ {
                try_files $uri =404;
                include fastcgi_params;
                fastcgi_pass    unix:/run/php/php7.0-fpm.sock;
                fastcgi_index   index.php;
                fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PHP_VALUE "upload_max_filesize=9G \n post_max_size=9G \n max_execution_time=200 \n max_input_time=200 \n memory_limit=256M";
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"; 
        add_header Content-Security-Policy "default-src https://mywebsite:443"; 
        add_header X-Frame-Options "DENY"; 
        add_header X-Xss-Protection "1; mode=block"; 
        add_header X-Content-Type-Options "nosniff"; 
        add_header 'Referrer-Policy' 'no-referrer'; 
        }

        location ~* \.(css|js|less|html|ttf|woff|jpg|jpeg|gif|png|bmp|ico) {
                root /usr/share/nginx/html/restyaboard/client;
                if (-f $request_filename) {
                        break;
                }
                rewrite ^/img/([a-zA-Z_]*)/([a-zA-Z_]*)/([a-zA-Z0-9_\.]*)$ /server/php/image.php?size=$1&model=$2&filename=$3 last;
                add_header        Cache-Control public;
                add_header        Cache-Control must-revalidate;
                expires           7d;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"; 
        add_header Content-Security-Policy "default-src https://mywebsite:443"; 
        add_header X-Frame-Options "DENY"; 
        add_header X-Xss-Protection "1; mode=block"; 
        add_header X-Content-Type-Options "nosniff"; 
        add_header 'Referrer-Policy' 'no-referrer'; 
        }
}`

Based on that, I have two questions:

1. Why I need to repeate the 6 lines dédicated to add_header in each section "location" ? Usually I just need to insert these lines in the generic part of section "server". If I do it, It appears that this configuration is not apply. Some ideas ?
2. When I want to connect to my self-hosted version of restyaboard, I get an empty page with Firefox Quantum 58.0.1 (without any error message, only a white page) and the login page when I use Safari 11.0.3. Why ?

Have a nice day.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sridhar391** [comment]
@IssueFindings we followed this type of configuration 

[restyaboard-ssl.conf.zip](https://github.com/RestyaPlatform/board/files/1710516/restyaboard-ssl.conf.zip)

replace your website name in the places of yourdomain text

**Comment by IssueFindings** [comment]
Many thnaks for your answer. Just a question, I don't find anymore the part below:

**Comment by sridhar391** [comment]
@IssueFindings sure,but if it leads to some issues let us know about that

**Comment by IssueFindings** [comment]
Hello, after several tests it appears that the part "add_header" locks off the access to restyaboard only with Firefox/Safari (I only have an empty page). Only IE run. What I can do ?
Have a nice day

**Comment by ssivachidambaram** [comment]
@IssueFindings Can you please provide screenshot of Network tab in Chrome browser and also provide request/response headers.

**Comment by sridhar391** [comment]
Closing the issue due to inactivity, if the information is confidential, please send us the file at  info@restya.com

**Comment by IssueFindings** [comment]
After many tests, please find below the error message by web browser. Sorry for this long delay...

`Refused to load the stylesheet 'https://fonts.googleapis.com/css?family=Open+Sans' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-eval'". Note that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-HfavkP3xDl2cB4eFGebkoNm+iojnSO57V7pktavpNE8='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-/YaaZ69fuiEIuKIgrA7KM0ZZdmYJ/jF5qEzFgloZM5w='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-Yn+q5w1JiNTKLw3d6+JJV88HbHgD+aKJGmNfIQzJsyQ='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

Uncaught ReferenceError: api_url is not defined at default.cache.b41fdf50.js:48

default.cache.b41fdf50.js:37
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

p @ default.cache.b41fdf50.js:37
E @ default.cache.b41fdf50.js:37
l @ default.cache.b41fdf50.js:2
fireWith @ default.cache.b41fdf50.js:2
ready @ default.cache.b41fdf50.js:2
ma @ default.cache.b41fdf50.js:2

default.cache.b41fdf50.js:37
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-tFH5KRmizb/+eruMkSeYor+UVhiMbPUtVTRTEMsQopc='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.`
