### ISSUE TITLE
Search for cards moved between boards

### ISSUE THREAD

**Issue by Erik-eMP** [RestyaPlatform/board#1535]
## Expected Behavior
The search function should work no matter if the Cards are moved to another Board.

## Current Behavior
If you create a card and move it between boards, you can't use the search function to find it.

## Possible Solution
Search across all boards

## Steps to Reproduce (for bugs)

1. Create card
2. Move it to another board
3. Search for the card.

## Context
This is our biggest irritation with Restya-board. We have Cards moving between boards and the search function is unuseable :/ 

## Your Environment

* Link to your project: project.emailplatform.com

**Comment by sridhar391** [comment]
@Erik-eMP Can you please check your crontab that elastic_search crons are exist. and if it exist, please wait for five minutes for elastic_search crons to run, or you can do it manually by running your_site_url/server/php/plugins/ElasticSearch/shell/indexing_to_elasticsearch.php file

**Comment by sridhar391** [comment]
@Erik-eMP To see ElasticSearch changes on the search page, we need to wait 5 mins. Because cron will be executed every 5 mins. After that cron execution, we can see the changes on search page
