### ISSUE TITLE
Non-Logged user can't see public boards

### ISSUE THREAD

**Issue by ikarus--** [RestyaPlatform/board#1536]
## Expected Behavior
A non-authenticated user should be able to see a board set as public through the direct link like http://www.yourdomain.com/restyaboard/#/board/number_of_the_board (according to its own description "This board is public. It's visible to anyone with the link and will show up in search engines like Google. Only people added to the board can edit."

## Current Behavior

A non-authenticated user can't see a board set as public and gets the "Board not found. This board may be private. You may be able to view it by logging in." message.
This happened on versions v0.6.1 and v0.6. It does not happen on version v0.5.2.

## Possible Solution

There is something wrong in the file 'r.php', lines 937 and 938. I removed the variable $authUser['id'] from both lines and it worked. I have zero clue about what I just did. (:

## Steps to Reproduce (for bugs)

1. Create a board and set as public.
2. Copy the link (ttp://www.yourdomain.com/restyaboard/#/board/number_of_the_board)
3. Open a new browser with cleared navigation data
4. Paste previous link
5. "Board not found. This board may be private. You may be able to view it by logging in." shows.

## Context

We want our (future) boards to be acessible by everyone as read-only.

## Your Environment

* Version used: v0.6.1

**Comment by sridhar391** [comment]
@ikarus-- Now the non-logged user can see public boards
