### ISSUE TITLE
When are you going to update translations

### ISSUE THREAD

**Issue by xchopin** [RestyaPlatform/board#1537]
Hi,

it's been more than one month I asked how the translations are updated; you answered me by saying "every release", there are news releases but the .json didn't change and it's still google translator quality which is bloody wrong.

Why ?

Regards,

**Comment by lmarikannan** [comment]
@xchopin Really sorry for that. We have used this Transifex command `tx pull -s -a` to pull changes from Transifex. But this command will only download the changes which are reviewed translations. Unfortunately in your translation, there are no reviewed translations done, so only your changes were not reflecting on our release. Anyway, now we're committed your changes by downloading that translation file manually. You can replace this file `https://raw.githubusercontent.com/RestyaPlatform/board/dev/client/locales/fr_FR/translation.json` on this path `{{your_server_path}}/client/locales/fr_FR/`, after this replacing your changes will be apply.

**Comment by xchopin** [comment]
Thanks !
