### ISSUE TITLE
We need cli for managing users at least

### ISSUE THREAD

**Issue by lgg** [RestyaPlatform/board#1541]
We need cli tool for RestyaBoard at least for managing user list.
Are there some plans for it?

**Comment by sridhar391** [comment]
@lgg we already have web interface for managing user list
1. Login as admin and click admin
![admin](https://user-images.githubusercontent.com/17172525/36017175-99596b86-0d9c-11e8-8dd0-1e1cdcc1436d.png)
2. Click users for users page
![users](https://user-images.githubusercontent.com/17172525/36017179-9c7b0176-0d9c-11e8-9cda-5d8cab02a508.png)
3. we will manage users here
![users_listing](https://user-images.githubusercontent.com/17172525/36017181-9ebc5836-0d9c-11e8-9d6f-2374a6f34c56.png)

Are you suggesting to use  command line interface tools for managing users

**Comment by rrjanbiah** [comment]
@lgg

Probably you may look at the `curl` command available in Swagger UI / API explorer?

**Comment by lgg** [comment]
@sridhar391 yes, im suggesting to use command line interface tools for managing user. Something like:

```
restya-cli user create bob email pass
restya-cli user delete bob
restya-cli user update bob email pass
```
and etc

**Comment by lgg** [comment]
@rrjanbiah sorry, but i did not understand you.

**Comment by rrjanbiah** [comment]
@lgg

Look at the auto generated `curl` command here in the API explorer http://board.demo.restya.com/api_explorer/#!/users/get_v1_users_search_json

`curl -X GET --header 'Accept: application/json' 'http://board.demo.restya.com/api/v1/users/search.json?token=Fix%20me'`

This for users search. 

Basically, everything is accessible through API. You may just wrap it through `curl` CLI

**Comment by rrjanbiah** [comment]
@lgg 

As shown above, you should be able to handle operations via 'curl` 

We may wrap it through some bash scripting, based on demand. So, for now, closing this.
