### ISSUE TITLE
 Case sensitive email address at login

### ISSUE THREAD

**Issue by ffuentes** [RestyaPlatform/board#1544]
Email login not case sensitive, as github and other apps, allow login with emails like **eMaiL@emAil.CoM**.

**Comment by ffuentes** [comment]
Hi, sorry for closing and opening this issue again.
Has this been addressed in any version after 0.6?

Thanks.

**Comment by sridhar391** [comment]
@ffuentes No, usage of case sensitive email address at login has not been addressed after `v0.6`

**Comment by ffuentes** [comment]
Thanks @sridhar391, I've made a pull request with a fix. Please review it and let me know if there is anything to change.

**Comment by sridhar391** [comment]
@ffuentes The case-sensitive usernames are not handled by this method.so, we have to change this code

**Comment by sridhar391** [comment]
The clients have asked the option for handling email in case sensitive. so, that only we have added the changes  and we are now adding the feature for handling email in case in-sensitive
