### ISSUE TITLE
While giving link for attachments in cards, the attachment is saved

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#1555]
## Expected Behavior
1. Goto modal card page.
2. Add attachment through link, by giving attachment URL in add attachment form
3. The attachment should represent the link and it won't be downloaded in server

## Current Behavior
1. Goto modal card page.
2. Add attachment through link, by giving attachment URL in add attachment form
3. The attachment is downloaded in the media folder, and inside the media folder, the attachment was 
    saved in the folder which has the card id

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by rrjanbiah** [comment]
Reopening. I think, we have to handle it differently; probably through some admin settings to enforce it. Especially customers like Tom don't want to download as they feel that we're duplicating storage.

**Comment by rrjanbiah** [comment]
Closing as wrongly reopened
