### ISSUE TITLE
brute-force attacks

### ISSUE THREAD

**Issue by gitotp** [RestyaPlatform/board#1558]
Not sure if it exists yet or I am just not finding it, but currently I am looking for a possibility to protect against brute force attacks on logins. 

Running on version 0.6.1 with apache webserver.

I can only see the pop-up on the website in case you entered the password wrong but it doesn't seem to limit requests.

![password_error](https://user-images.githubusercontent.com/35888083/36172420-1e64642c-1106-11e8-9c6e-e1df438ef6dc.PNG)

Maybe I just overlooked it in the documentation, but otherwise my suggestion would be the possibility to have failed logins logged to the webserver log or a file. That might be an easy thing to setup for the restyaboard team like:

\"Login failed for \<username\> from \<IP address\>\"

From there other programs/scripts like fail2ban etc. can take action and monitor/block IP address or user accounts  for security reasons.

Any information is appreciated.

**Comment by sridhar391** [comment]
@gitotp Thanks for your suggestion, we will check on that

**Comment by gitotp** [comment]
Any breakthrough on this part?

**Comment by sridhar391** [comment]
We have added [Two-factor authentication (2FA) using Google Authenticator](https://github.com/RestyaPlatform/board/issues/1646) which protect against brute force attacks on logins. can you  please tell us if you still want us to  store failed logins logged to the webserver log or a file

**Comment by gitotp** [comment]
Thank you for this update. I will have a look when the 2FA is released, since I am currently missing the details on this how it works, also in conjunction with the App.
 I would say the option of generating logs would be still nice to have, to be aware something is going on, but I don’t know how much work that is.

**Comment by sridhar391** [comment]
We'll internally discuss about this and will update
