### ISSUE TITLE
Apps description for certain apps are not clear

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1577]
## Expected Behavior

When you click an app from Restyaboard, description are self explanatory. For certain apps like "Amazon Echo App", "Support Desk", "Hide Card ID", and "Auto Archive Expired Cards" description are somehow self explanatory. 

## Current Behavior

For other apps, description are one liner and there is no clear explanation on what it does.

**Comment by sridhar391** [comment]
Other apps descriptions are now describing about their functionalities and their uses and it will be available after the release
