### ISSUE TITLE
Helper app for Kanban Printer

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1587]
Need helper app for the Kanban Printer http://restya.com/board/printer

Features required

1. CSS print style sheet for list names and card titles
2. Responsive font handling https://codepen.io/CrocoDillon/pen/fBJxu so that card title will fill the entire sticky sheet
3. `@page` handling for paper size
4. `page-break` for papers (list names & cards) https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-after

**Comment by sridhar391** [comment]
Helper app for kanban printer have been done in `local commit` and it can be viewd in http://restya.com/board/apps/r_kanban_printer

**Comment by rrjanbiah** [comment]
@sridhar391 Documentation is still not adequate. It is not clear clear what it does, how it will look like and how to use it, etc

**Comment by rrjanbiah** [comment]
@sridhar391 Still it is not clear. May add screenshots, etc. Also, please have someone review the documentation and see if he/she can understand it.

**Comment by sridhar391** [comment]
Documentations of helper app is changed and screenshots have been added

**Comment by rrjanbiah** [comment]
@sridhar391 Screenshots are still not useful. Please have someone else review documentation. Also, properly crop screenshots

**Comment by sridhar391** [comment]
Documentation of helper app and screenshots have been updated

**Comment by sridhar391** [comment]
The screenshots for helper app have been changed

![3](https://user-images.githubusercontent.com/17172525/40308529-31dd8992-5d24-11e8-80b9-0153677c4148.png)

**Comment by rrjanbiah** [comment]
1. Still finding old screenshot http://restya.com/images/restyaboard/apps/r_kanban_printer/1.png
2. Screenshots still don't give a clear idea on how a board will be printed (how a list, card will be getting printed
3. As per screenshot the texts are skewed to top (better to vertically center, if possible)

**Comment by sridhar391** [comment]
The screenshots for helper app have been changed and explained about the printing of card name and list name of the board page

![restyacom_kanban_printer_helper_app_page](https://user-images.githubusercontent.com/17172525/40407396-e8446e90-5e81-11e8-9c18-5908b258ba8d.png)

**Comment by rrjanbiah** [comment]
Documentation looks good to go now.

But, as per screenshot the texts are skewed to top (better to vertically center, if possible)

**Comment by sridhar391** [comment]
Thanks for the suggestion, we will check and update

**Comment by sridhar391** [comment]
We tried to vertically center the list name and card name. but, we are not able to vertically center  the list name and card name

**Comment by rrjanbiah** [comment]
@sridhar391 What are the approaches you have tried and their results?

**Comment by sridhar391** [comment]
we have tried https://codepen.io/sokrati-engineering/pen/jmQjpN , http://bfred.it/public/13/print-verically-centered/ and we have hided some elements in order to show only list names and card names and applied page-break-before some elements to show list name and card name each in single page, and for multi parent mult child elements we are unable to vertically center the list name and card name.
