### ISSUE TITLE
For Launching IOS app from the site, the normal users cannot able to see the QR code    

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#1588]
## Expected Behavior
1. Login as user.
2. If you want to launch the Myrestyaboards app from your iPhone or iPad Safari scan the QR code and the app will be launched.

## Current Behavior
1. For admin only QR code is available.

## Screenshots (if appropriate):
![ios-app](https://user-images.githubusercontent.com/17172525/36714504-892625c2-1bb8-11e8-9646-103dacc4c8f2.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by rrjanbiah** [comment]
Related #1285
