### ISSUE TITLE
Cards will come back to their initial position

### ISSUE THREAD

**Issue by mtohidi** [RestyaPlatform/board#1599]
I have installed the restyaboard and it works good. 
But the issue is that no changes will be save except creating new card or list.
Even if you change a card's position or its color or anything else, when you exit the board and then came back, all changes have been canceled and you see the board in its initial view. 
The error shown in console windows is like below:

PUT http://ex1.ir/api/v1/boards/5/lists/214/cards/22.json?token=6401ee29727cc5572d9ba42994a5f1493c871f70 net::ERR_CONNECTION_RESET

**Comment by sridhar391** [comment]
@mtohidi can you please attach the nginx error.log file

**Comment by mtohidi** [comment]
I have finally solve this problem. It had been caused by some restriction rule in direct admin.

**Comment by ssivachidambaram** [comment]
@mtohidi Thank you for the confirmation. We are closing this issue. Please reopen if you need any assistance from us.
