### ISSUE TITLE
Install procedure for Windows Server / IIS (non nginx install)

### ISSUE THREAD

**Issue by t0mgerman** [RestyaPlatform/board#1600]
Hi guys, first off - I love the software, I think you've done an amazing job here! Out of all of the boards I've tried, including some of the competitors, this is possibly the most versatile and portable. Some other products _require_ *nix due to dependencies on extensions and libraries like PHP's pcntl, gunicorn for python etc. whereas the requirements for this are broadly achievable on every platform.

I note that the repo currently points to [Windows instructions on the official site](http://restya.com/board/docs/windows)

Those instructions use WPN-XM -- one of many stacks that people might use on Windows. I recently wanted to install restyaboard on a test server where I work, and given the server has a bunch of other applications on it currently - all running under IIS - I wanted to have restyaboard running in a similar environment. I've written up the install procedure below as a gist as I wasn't sure how else to contribute it. It may help someone, it may not! I hope it does!

[Windows Server / IIS Install Guide](https://gist.github.com/t0mgerman/0f77ac95fdba863ca478b0583aa2b925)

These instructions were tested on this environment:

- Windows Server 2008 R2
- IIS 7.5
- PHP 5.6
- PostgreSQL 10

Updated the gist 2 March 2018: the web.config file rewrite rules benefited from a tweak to allow for a leading slash

**Comment by sridhar391** [comment]
@t0mgerman hi, we have added your Installation procedure for Windows Server / IIS (non nginx install) in http://restya.com/board/docs/windows-iis and we have added your link to credits

**Comment by rrjanbiah** [comment]
@t0mgerman Thank you so much for your wonderful contribution
