### ISSUE TITLE
Intro video will be repeated infinite times

### ISSUE THREAD

**Issue by BlackDark** [RestyaPlatform/board#1601]
The intro video will be repeated always (upon first login of course). For example in the dashboard view /boards when you click away the intro and hit F5 -> repeated.

## Expected Behavior

Intro only displayed once.

## Current Behavior

Intro displayed infinity times until user logs out and in again.
In https://github.com/RestyaPlatform/board/blob/b9cc567ffd6e48edbb14d8427e418d3ff20f7594/client/js/views/intro_video_view.js#L32
the `is_intro_video_skipped` is "f" until relogging even if the value in db is true.

## Your Environment
v0.6.2 via docker (https://github.com/BlackDark/docker-restyaboard)

**Comment by sridhar391** [comment]
@BlackDark hi, we tried to reproduce the issue on our live server and we unable to reproduce the issue. So please refer the video which is attached below. If you face the issues again, Please take the video and update us.
[intro_video.zip](https://github.com/RestyaPlatform/board/files/1779792/intro_video.zip)

**Comment by rrjanbiah** [comment]
@sridhar391 Can you try with fresh install?
