### ISSUE TITLE
Issue with multiple Users working on same board

### ISSUE THREAD

**Issue by Mattes1000** [RestyaPlatform/board#1605]
When user A create a new card on a board while User B moves or edits another card on the same board the board refreshs and the card of user A dissapears.

**Comment by sridhar391** [comment]
@Mattes1000  hi, we tried to reproduce the issue on our live server and we can't reproduce the issue. So, please refer the video which is attached below. If you face the issue again, please take the video and update us.
[multi_users.zip](https://github.com/RestyaPlatform/board/files/1780609/multi_users.zip)

**Comment by sridhar391** [comment]
Closing the issue due to inactivity
