### ISSUE TITLE
RestyaBoard Install Failed | Error Code 17

### ISSUE THREAD

**Issue by Threat-Hunter** [RestyaPlatform/board#1609]
## Steps to Reproduce (for bugs)

1. sudo ./restyaboard.sh
2.
3.
4.

## Your Environment

* Version used: Current
* Environment name and version (e.g. OS, PHP, PostgreSQL): 
* Operating System and version (desktop or mobile): Linux Mint 18.1 Serena
* Link to your project:

**Comment by sridhar391** [comment]
@Threat-Hunter can you please attach the nginx error.log file from the `/var/log/nginx/error.log` path

**Comment by ssivachidambaram** [comment]
@Threat-Hunter 

```
vi /etc/yum.repos.d/atrpms.repo
vi /etc/yum.conf
```
In the above two files replace `http://dl.atrpms.net/` to `https://www.mirrorservice.org/sites/dl.atrpms.net/` and try again.

**Comment by rrjanbiah** [comment]
@ssivachidambaram As noted in #693 we should have already fixed touching repo sources issue.. that is, adding repo sources without prompting user (?)
