### ISSUE TITLE
Gantt button does not show

### ISSUE THREAD

**Issue by leonardomaccari** [RestyaPlatform/board#161]
Hi,
I have installed from docker, and updated to 1.6. I can login and create boards, i see the grid, list and calendar buttons top right, and they are alright. I see no Gantt button, as instead i can see in the online demo. Where should i start debugging?

**Comment by rrjanbiah** [comment]
@leonardomaccari Is there anyway you can migrate to our new install script? (Supporting docker seems like a time consuming task for us at this moment).

Perhaps when you upgrade, all files are not replaced?

**Comment by leonardomaccari** [comment]
Thanks,
these are bad news, i heavily rely on docker. Will try to run the install script in docker.

**Comment by rrjanbiah** [comment]
@leonardomaccari We'll definitely try to support after our current list of items. Also, theoretically it should work fine as both are using same code base. I still doubt that all files may not have copied

**Comment by ssivachidambaram** [comment]
Could not reproduce this issue.
