### ISSUE TITLE
Card does not always open by tapping if mouse+touch desktop device is used.

### ISSUE THREAD

**Issue by ik9999** [RestyaPlatform/board#1610]
## Expected Behavior
It should open the card instead of dragging it by 2px and back.

## Current Behavior
When im dragging the card by ~1-3px it drags it by 1-3px and back. Same with all buttons on draggable elements and lists.

## Screenshots (if appropriate):
I can record a video if needed.

## Possible Solution
There should be a threshold for dragging, if i drag card by <3 px on my PC and stop dragging(mousup/touchend event), it should just open the card instead.

http://hammerjs.github.io/recognizer-tap/
This library allows it with either pan or tap event.

## Steps to Reproduce (for bugs)
I think its possible with VirtualBox by setting a tablet pointer instead of mouse, but im not sure.

## Your Environment
* Version used: 0.6.2
* Environment name and version (e.g. OS, PHP, PostgreSQL): Debian/Chromium. Firefox has the same issue.
* Operating System and version (desktop or mobile): desktop

**Comment by sridhar391** [comment]
@ik9999 can you please attach us a screenshot or video

**Comment by rrjanbiah** [comment]
@sridhar391 Can you check this in tablet first?

**Comment by ik9999** [comment]
https://streamable.com/6waho
@sridhar391 Here is the video.
On the video im trying to click on the card to open it but the card is moving instead.

**Comment by lmarikannan** [comment]
@ik9999 We're checked your video. We understood, In your video, you trying to tap the card, but you're tapping with drag, so card doesn't open. In restyaboard, if we start to drag the card and drop it without tapping, it doesn't open default. Trello also has the same feature, here it's the video.

[card_open.webm.zip](https://github.com/RestyaPlatform/board/files/1803015/card_open.webm.zip)

> http://hammerjs.github.io/recognizer-tap/
This library allows it with either pan or tap event.

And also we're checked the library which is you mentioned. In that library having the feature that we can delay the timing (100ms), but we can't delay the pixel range.

**Comment by rrjanbiah** [comment]
@lmarikannan 

I can also reproduce @ik9999 comment and it is somewhat behaves odd. 

It looks like there is some event loop making touch action freeze and definitely needs improvement on touch behavior. Probably hammer or fast click may help

**Comment by ik9999** [comment]
@lmarikannan I think delay by timing would be ok too.

**Comment by ik9999** [comment]
@rrjanbiah Thank you for including this issue to the milestone!

**Comment by sridhar391** [comment]
@ik9999 We tried to delay the drag time of the cards using the library which is you mentioned. But, it doesn't allow the drag on the first time while exceeding the given condition and on the second time of drag, the library is not worked and allowed the dragging of cards by default.

So we have searched an alternative option and we came to know that the sortable function for the cards has the distance option http://api.jqueryui.com/sortable/#option-distance, which enables the user to specify the minimum distance for the drag and we would like to enable this option in mobile view only. Can you please provide your suggestion?

**Comment by ik9999** [comment]
@sridhar391 I think it can be done with distance treshold. I.e. 10px.
User drags the card by 5px and doesnt trigger mouseup/touchend -> do nothing. If user triggers mouseup/touchend - trigger click event.
User drags the card by 10px -> start the dragging.
