### ISSUE TITLE
After installation the website does open but loads forever

### ISSUE THREAD

**Issue by Richigeht** [RestyaPlatform/board#1611]
## Expected Behavior

Well, I would expect the website does load and I can enter my login data but this is not happening.
## Current Behavior
The website is loading and loading forever.

## Screenshots (if appropriate):

![2018-03-04_16-20-55](https://user-images.githubusercontent.com/21252095/36947109-034fbf4e-1fc8-11e8-8b63-d3c786899d50.png)

## Steps to Reproduce (for bugs)

1. Start nginx
2. Start website
3.
4.

## Your Environment

* Version used: latest from installation script
* Environment name and version (e.g. OS, PHP, PostgreSQL): debian jessie, php7.0, postgres 9.4
* Operating System and version (desktop or mobile): desktop, Win 10, using latest chrome 64 bit and tried IE
* Link to your project: 

EDIT: Nevermind, fixed it! My postgresql server port is different, that was the issue.

**Comment by sridhar391** [comment]
@Richigeht can you please attach the nginx error.log file from the `/var/log/nginx/error.log` path and also can you please enable debug mode in `root folder/server/php/config.inc.php#L15` and post HTTP response header and response (In Firebug or Chrome's Developer tool)

**Comment by Richigeht** [comment]
Hi,
Thanks but figured it out using that log already :)
Thought I already closed the issue, too. 
Thanks for the quick reply. 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by sridhar391** [comment]
@Richigeht Thanks for your confirmation.
