### ISSUE TITLE
For MyRestyaboards app QR code link, pass username along with instance URL

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1622]
## Current Behavior

From "View in iOS App" QR code from Restyaboard instance, it passes instance URL alone to MyRestyboards iOS App. Users have to still type in username and password

## Enhancements 

Pass username too in the URL so that users have to type only the password.

## Context

#1285

**Comment by lmarikannan** [comment]
This changes was done and committed on this issue https://github.com/RestyaPlatform/board/issues/1650
