### ISSUE TITLE
forget admin password, 

### ISSUE THREAD

**Issue by zhhwdev** [RestyaPlatform/board#1623]
i forget admin password, how can i do?

**Comment by lmarikannan** [comment]
@zhhwdev You can update admin password by running this psql command on your postgresql server  **` update users set password ='$2y$12$QiJW6TjPKzDZPAuoWEex9OjPHQF33YzfkdC09FhasgPO.MjZ5btKe' where username = 'admin';`**, after executing this psql query your admin password will be **restya**.

To execute this query, please follow these steps:

Goto terminal and type below commands

`sudo -u postgres psql`

`\connect restyaboard`

`update users set password ='$2y$12$QiJW6TjPKzDZPAuoWEex9OjPHQF33YzfkdC09FhasgPO.MjZ5btKe' where username = 'admin';`

**Comment by ssivachidambaram** [comment]
Related #1624
