### ISSUE TITLE
It is impossible to change user password in v0.6.2

### ISSUE THREAD

**Issue by arbv** [RestyaPlatform/board#1624]
I have successfully installed Restyaboard v0.6.2 - it looks and works great so far, but there is one annoying issue: It is impossible to change the user password after the user was created. It is impossible to do even in the admin panel. I cannot change the default admin account password too. Seems like a **critical bug** for me.

## Steps to reproduce
1. Create a new user;
2. Select "Change password" in the user menu. Restyaboard will report that password was changed, but in fact, it is not.
3. Alternatively one could try to change the password for the user in "Admin Panel" but it does not work either.

I found the following information in the nginx log, which is, I believe, related to the issue (I replaced my real domain name with *example.com*):

```
Mar 07 11:31:07 raspi nginx[293]: 2018/03/07 11:31:07 [error] 314#314: *2111 FastCGI sent in stderr: "PHP message: PHP Warning:  pg_query_params(): Query failed: ERROR:  source for a multiple-column UPDATE item must be a sub-SELECT or ROW() expression
Mar 07 11:31:07 raspi nginx[293]: LINE 1: UPDATE users SET (password) = ($1) WHERE id = $2
Mar 07 11:31:07 raspi nginx[293]:                                        ^ in /srv/http/www/restyaboard/server/php/R/r.php on line 2319" while reading response header from upstream, client: 127.0.0.1, server: http_server, request: "POST /restyaboard/api/v1/users/4/changepassword.json?token=13c49cc8f6daa32acea9c32130cd3c88a72e7a00 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "example.com", referrer: "https://example.com/restyaboard/"
```

I hope you will investigate the issue.

**Comment by lmarikannan** [comment]
@arbv Really sorry for that. Due to postgresql version, this issue was caused. Now the issue is fixed, so you can replace this https://raw.githubusercontent.com/RestyaPlatform/board/dev/server/php/R/r.php file on this path `{YOUR_SERVER}/server/php/R/`. After replacing the `r.php` file, you can update password.

**Comment by arbv** [comment]
Thanks for the very quick fix!

I have checked - it does work.
