### ISSUE TITLE
SMTP not working ?

### ISSUE THREAD

**Issue by dadarko** [RestyaPlatform/board#1627]
I have the newest build of Restyaboard.
Been trying to fix the SMTP for a few days but no success, no e-mails are sent from Restya at all.
The log file:

``
Feb 26 08:39:17 restyaboard postfix[1510]: Postfix is running with backwards-compatible default settings
Feb 26 08:39:17 restyaboard postfix[1510]: See http://www.postfix.org/COMPATIBILITY_README.html for details
Feb 26 08:39:17 restyaboard postfix[1510]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
Feb 26 08:39:17 restyaboard postfix/master[1547]: daemon started -- version 3.1.0, configuration /etc/postfix
Feb 27 14:12:18 restyaboard postfix/pickup[10386]: 1EDEA42E67: uid=33 from=<www-data>
Feb 27 14:12:18 restyaboard postfix/cleanup[11285]: 1EDEA42E67: message-id=<20180227131218.1EDEA42E67@restyaboard.adria.loc>
Feb 27 14:12:18 restyaboard postfix/qmgr[1550]: 1EDEA42E67: from=<www-data@MYIP>, size=3110, nrcpt=1 (queue active)
Feb 27 14:12:18 restyaboard postfix/smtp[11287]: 1EDEA42E67: to=<informatika@adriadiesel.hr>, relay=mx.optinet.hr[85.114.35.5]:25, delay=0.21, delays=0.08/0.02/0.09/0.01, dsn=5.0.0, status=bounced (host mx.optinet.hr[85.114.35.5] said: 554 sender verification failed [MYIP:41014:73519] (in reply to MAIL FROM command))
Feb 27 14:12:18 restyaboard postfix/cleanup[11285]: 45D5242E68: message-id=<20180227131218.45D5242E68@restyaboard.adria.loc>
Feb 27 14:12:18 restyaboard postfix/qmgr[1550]: 45D5242E68: from=<>, size=5144, nrcpt=1 (queue active)
Feb 27 14:12:18 restyaboard postfix/bounce[11288]: 1EDEA42E67: sender non-delivery notification: 45D5242E68
Feb 27 14:12:18 restyaboard postfix/qmgr[1550]: 1EDEA42E67: removed
Feb 27 14:12:18 restyaboard postfix/error[11289]: 45D5242E68: to=<www-data@MYIP>, relay=none, delay=0.02, delays=0.01/0.01/0/0, dsn=5.1.3, status=bounced (bad address syntax)
Feb 27 14:12:18 restyaboard postfix/qmgr[1550]: 45D5242E68: removed
Feb 27 14:46:33 restyaboard postfix[1407]: Postfix is running with backwards-compatible default settings
Feb 27 14:46:33 restyaboard postfix[1407]: See http://www.postfix.org/COMPATIBILITY_README.html for details
Feb 27 14:46:33 restyaboard postfix[1407]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
Feb 27 14:46:33 restyaboard postfix/master[1444]: daemon started -- version 3.1.0, configuration /etc/postfix
Feb 27 15:08:07 restyaboard postfix/pickup[1446]: 1A1DE42E67: uid=33 from=<www-data>
Feb 27 15:08:07 restyaboard postfix/cleanup[1689]: 1A1DE42E67: message-id=<20180227140807.1A1DE42E67@restyaboard.adria.loc>
Feb 27 15:08:07 restyaboard postfix/qmgr[1447]: 1A1DE42E67: from=<www-data@MYIP>, size=3110, nrcpt=1 (queue active)
Feb 27 15:08:07 restyaboard postfix/smtp[1691]: 1A1DE42E67: to=<informatika@adriadiesel.hr>, relay=mx.optinet.hr[85.114.35.5]:25, delay=0.18, delays=0.09/0.01/0.08/0, dsn=5.0.0, status=bounced (host mx.optinet.hr[85.114.35.5] said: 554 sender verification failed [MYIP:49728:952309] (in reply to MAIL FROM command))
Feb 27 15:08:07 restyaboard postfix/cleanup[1689]: 3D07742E68: message-id=<20180227140807.3D07742E68@restyaboard.adria.loc>
Feb 27 15:08:07 restyaboard postfix/qmgr[1447]: 3D07742E68: from=<>, size=5146, nrcpt=1 (queue active)
Feb 27 15:08:07 restyaboard postfix/bounce[1692]: 1A1DE42E67: sender non-delivery notification: 3D07742E68
Feb 27 15:08:07 restyaboard postfix/qmgr[1447]: 1A1DE42E67: removed
Feb 27 15:08:07 restyaboard postfix/error[1693]: 3D07742E68: to=<www-data@MYIP>, relay=none, delay=0.01, delays=0/0.01/0/0, dsn=5.1.3, status=bounced (bad address syntax)
Feb 27 15:08:07 restyaboard postfix/qmgr[1447]: 3D07742E68: removed
Mar  8 09:38:28 restyaboard postfix[11599]: Postfix is running with backwards-compatible default settings
Mar  8 09:38:28 restyaboard postfix[11599]: See http://www.postfix.org/COMPATIBILITY_README.html for details
Mar  8 09:38:28 restyaboard postfix[11599]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
Mar  8 09:38:28 restyaboard postfix/master[1444]: reload -- version 3.1.0, configuration /etc/postfix
Mar  8 09:38:29 restyaboard postfix[11803]: Postfix is running with backwards-compatible default settings
Mar  8 09:38:29 restyaboard postfix[11803]: See http://www.postfix.org/COMPATIBILITY_README.html for details
Mar  8 09:38:29 restyaboard postfix[11803]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
Mar  8 09:38:29 restyaboard postfix/master[1444]: reload -- version 3.1.0, configuration /etc/postfix

**Comment by ssivachidambaram** [comment]
@dadarko Can you please provide Teamviewer or SSH access to understand about your issue via email info@restya.com?

**Comment by dadarko** [comment]
I have identified the problem. Postfix sends from wrong adress (www-data@something) instead of sending from the designated adress

**Comment by ssivachidambaram** [comment]
@dadarko Can you please post your fixes here?

**Comment by dadarko** [comment]
I have solved it by changing:
/etc/mailname (add domain name)

/etc/postfix create new file called generic (www-data@mydomain.com boards@mydomain.com)

in /etc/postfix/main.cf change following:
myhostname= myhostname.com
mydestination= boards@mydomain.com
Add line:
smtp_generic_maps = hash:/etc/postfix/generic

run postmap /etc/postfix/generic

**Comment by ssivachidambaram** [comment]
@dadarko Thank you. We are closing this issue.
