### ISSUE TITLE
Comment disappearing on cards with long checklists

### ISSUE THREAD

**Issue by Yasharah** [RestyaPlatform/board#1628]
Hello,
before the update from 0.6 to 0.6.2 we had the problem that longer comments disappeared on cards with long checklists. After the update that doesn't happen anymore... at least not in the same way as before. Now i only see some of the comments and at the end of the comments section is a red button with the text "Load next 20 of 54", that i have to use 3 times so see all the other comments...but there are only 4 comments in total. Why does this happen? Why 20 of 54, when there are only 4 and why are they not shown directly? The sorting of the comments is wrong, too.

I'm happy that i'm able to see the comments now, because before there was the speech bubble number with the correct comment counter on the card itself and the comments were invisible completely.

## Screenshots (if appropriate):
just 2 comments and the button:
![1](https://user-images.githubusercontent.com/30473222/37156493-882187a4-22e6-11e8-850f-10575c96596b.png)

after is used the button 3 times to see the other 2 comments in the wrong order:
![2](https://user-images.githubusercontent.com/30473222/37156492-880a1632-22e6-11e8-8014-efdb922ab623.png)

**Comment by Yasharah** [comment]
we cant even edit the comments, just delete them. this is a serious bug

**Comment by lmarikannan** [comment]
@Yasharah Really sorry for this. Actually, activities listing will display 20 records per page, in that 20 records having activities and comments also. "activities" and "comments" button will fetch details from those 20 records only, so the records are displaying like what you're mentioned.

**To filter activities:**

![image-1](https://user-images.githubusercontent.com/17758064/37241841-e43ef274-2485-11e8-9670-7dc0e9ddc3b5.png)

**To filter comments:**

![image-2](https://user-images.githubusercontent.com/17758064/37241845-eadcb3be-2485-11e8-8833-97ffc8bfce54.png)

> we cant even edit the comments, just delete them. this is a serious bug

 we're trying to reproduce this issue, but we couldn't reproduce this is on our local server. Could you please explain briefly, or share any screenshots.

**Comment by Yasharah** [comment]
Hey,
We only display the comments and not the activities on the cards.. Should the button with 29 from 59 still be there, if there are only 4 comments ? It makes no sense for me, that I have to press the button 3 times to see all 4 comments..

I shared the Screenshots already. We have 14 checklist items with longer texts and 4 comments with more than 1 line and some have formatting like lists

If I open the card sometimes I can edit 1 or 2 of the 4 comments and sometimes I can't edit any of them. Just nothing happens if I use the edit button or the edit button just disappears

**Comment by lmarikannan** [comment]
> We only display the comments and not the activities on the cards.. Should the button with 29 from 59 still be there, if there are only 4 comments ? It makes no sense for me, that I have to press the button 3 times to see all 4 comments..

As per our code for functionality,

in your 54 records of activities having only 4 comments. If the first 20 records having 2 comments and 18 activities means, it'll show only 2 comments on comments tab. Then 2nd page having 20 records and all the 20 records are activities means, it won't show comments, so it'll display empty page on comments tab. Then final page having 20 records activities means, it'll show remaining 2 comments on comments tab.

Because that two filter button (activities, comments), will hide the activities if we click the comments button, and hide the comments if we click the activities button. They do not get records from server for every click. 

So we understand your issue, we need to change the filters with get the records from server for every click. Once the issue is fix, we'll update.

**Comment by Yasharah** [comment]
okay, thanks for the explanation. The main problem still is the bug that we sometimes cant edit the comments at all. sometimes some work, sometimes nothing happens after we press the edit button...just the line with edit, delete disappears :/

**Comment by lmarikannan** [comment]
@Yasharah We're working on this. Once the issue is fix, we'll update.

**Comment by rrjanbiah** [comment]
FWIW, @lmarikannan I can also reproduce odd load more behavior in one of my boards.

![rb-loadmore-bug](https://user-images.githubusercontent.com/4907427/37352636-b8c45758-2703-11e8-9c7d-df8c30cc4717.png)
