### ISSUE TITLE
"View user activities" permission side effect

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1635]
From Markus Ehrlicher in https://groups.google.com/forum/#!topic/restya/tE57X4eVvQI

today, I tracked a strange behavior with the permission "View user activities". When I disable this permission for normal users and log in with a user in this group, the profile page for this user is empty. Also, when you are in a board and wait for the automatic refresh, the message "Board not found / This board may be private." appears. I think, there is a little bug in the permission-management or something else.

When I give back the permission, all problems went away and the behavior is reproducable all times (with v0.6.2).

**Comment by lmarikannan** [comment]
Yes, this issue reproduced on our local server also. Are you trying to hide this user's profile page activities by disable this "view user activities" role? Or any other activities you want to hide? please refer the attachment

![download](https://user-images.githubusercontent.com/17758064/37239269-80f47224-245e-11e8-99ff-09882f85df34.png)
