### ISSUE TITLE
Microsoft Edge does not auto-collapse long lists on page load

### ISSUE THREAD

**Issue by erl4nc** [RestyaPlatform/board#1636]
In Microsoft Edge, lists with lots of items show all the cards on page load.  See screenshot:
![before](https://user-images.githubusercontent.com/33263752/37222290-5f00d12c-2381-11e8-9818-e102caf05b82.png)

As soon as the long list gets focus from an input device such as mouse hover or keyboard tabbing, it collapses the cards and auto-shrinks to fit page height.  See screenshot:
![after](https://user-images.githubusercontent.com/33263752/37222343-883c8eaa-2381-11e8-9fcb-aa3d6f5b0b7b.png)

This happens every time the page loads and results in poor user experience.  Other browsers (IE 11, Chrome, Firefox) do not exhibit this behaviour.

## Expected Behavior
Long lists are collapsed on page load.

## Current Behavior
Long lists show all cards on page load until lists get focus from an input device and then shrinks.

## Screenshots (if appropriate):  
See above.

## Steps to Reproduce (for bugs)
1. Populate a list on a board with many cards
2. Open board in Microsoft Edge

## Context
This is poor user experience as the list sometimes resizes while the user is working with it.  A list only shrinks when it gets focus meaning that a board could have both collapsed and un-collapsed lists causing page scrolling issues.

## Your Environment
* Version used: 0.6.2
* Environment name and version (e.g. OS, PHP, PostgreSQL): Windows 10 with Microsoft Edge 41.16299.15.0 & 41.16299.248.0
* Operating System and version (desktop or mobile): desktop

**Comment by lmarikannan** [comment]
@erl4nc We're trying to reproduce this issue on our Microsoft edge browser, we're also getting page like this, but after 1 to 3 seconds its restoring to normal UI. 

Here is the sample video 
[Microsoft-Edge-scroll-issue.mp4.zip](https://github.com/RestyaPlatform/board/files/1811554/Microsoft-Edge-scroll-issue.mp4.zip)

Could you please tell us, are you getting this auto collapse issue on page load time only or always? Or Did you get any console errors on your browser console tab?. If you get any errors on your browser console means, please share with us here.

**Comment by erl4nc** [comment]
> Could you please tell us, are you getting this auto collapse issue on page load time only or always? Or Did you get any console errors on your browser console tab?

Always and no.

[edge.mp4.zip](https://github.com/RestyaPlatform/board/files/1812428/edge.mp4.zip)

**Comment by sridhar391** [comment]
The previous video was captured in Microsoft edge 38.14393 and in the Microsoft edge (41.16299.280.0) it took ten seconds and we are working on that issue

[Microsoft_Edge_latest.zip](https://github.com/RestyaPlatform/board/files/1844196/Microsoft_Edge_latest.zip)

**Comment by erl4nc** [comment]
Did this fix make it into 0.6.3?  My 0.6.3 deployment did not see a difference in Edge.

[edge0.6.3.mp4.zip](https://github.com/RestyaPlatform/board/files/1877791/edge0.6.3.mp4.zip)

**Comment by ssivachidambaram** [comment]
@erl4nc Is it possible to arrange a Teamviewer session or SSH access? Please contact us through mail info@restya.com. So we can check & fix the Edge & ElasticSearch app issue.

**Comment by erl4nc** [comment]
After a lot of debugging, it looks like `max-height:100%;` on `.list` does not always work in Edge.  I say does not _always_ work meaning it sometimes works, which would explain the difference between your experience and mine. 

I fixed the issue by adding to common.js window resize: `if($(".js-board-list")){$(".js-board-list").css("height",(boardH+'px'));`.  The `if` may be unnecessary but I didn't want to look through all the code.

HTH.

**Comment by erl4nc** [comment]
The fix has the downsize of making all lists the height of the window including empty lists but I prefer this experience over the original.

**Comment by rrjanbiah** [comment]
@erl4nc Many thanks for your efforts

**Comment by rrjanbiah** [comment]
@sridhar391 Let's defer this until we get better fix/solution

**Comment by erl4nc** [comment]
In my opinion, my fix is only acceptable if an onClick is added to .js-board-list so that a new card could be added to a list by clicking anywhere in the list's gray area (asides from title of course).  

Edge is the mandated browser for some of my users and this bug is a deal breaker for them.

**Comment by rrjanbiah** [comment]
@erl4nc Noted, thanks. We'll revisit this in next milestone to check closely
