### ISSUE TITLE
User profile pictures strange transparency

### ISSUE THREAD

**Issue by BlackDark** [RestyaPlatform/board#1648]
The transparency of some user profile is kinda strange. The uploaded image has no transparency but as soon as it is set as profile pic it gets sometimes a strange transparency.

Maybe some problems with the alpha layer?

## Expected Behavior

Uploaded pictures is shown as it is and not transformed.

## Current Behavior

Some profile pictures get some strange transparencies

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/9947112/37292350-0fb81e62-2611-11e8-9e6e-fa868a9a2177.png)

## Your Environment

* Version used: 0.6.2
* Environment name and version (e.g. OS, PHP, PostgreSQL): docker version

**Comment by lmarikannan** [comment]
@BlackDark Really sorry for this, Already this issue is noted and fixed.  Related https://github.com/RestyaPlatform/board/issues/1607
