### ISSUE TITLE
While scanning QR code, we are passing username to app for login

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#1650]
## Expected Behavior
1. After login to restyaboard
2. Scan the QR code
3. It will open the app for login with username already prefill in it

## Current Behavior
1. After login to restyaboard
2. Scan the QR code 
3.  It will only open the app

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by lmarikannan** [comment]
Duplicate of https://github.com/RestyaPlatform/board/issues/1622
