### ISSUE TITLE
LDAP login doesn't work first time

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1664]
From Todor

The login works only on the second login attempt. On the first, the following error occurs:
`
<br />
<b>Notice</b>: Undefined index: first_name in <b>/var/www/restyaboard/server/php/plugins/LdapLogin/functions.php</b> on line <b>84</b><br />
<br />
<b>Notice</b>: Undefined index: first_name in <b>/var/www/restyaboard/server/php/plugins/LdapLogin/functions.php</b> on line <b>89</b><br />
`

After that the user can login every time.

**Comment by lmarikannan** [comment]
@rrjanbiah Now the issue is fixed on our LDAP plugin folder functions.php file and committed.

**Comment by erl4nc** [comment]
@rrjanbiah How could my existing plugin deployments receive bug fixes such as this?

**Comment by rrjanbiah** [comment]
@erl4nc Our plugin release process is similar to our core product release approach. Only difference is that for paid plugins, we'll release through different channel.
