### ISSUE TITLE
Improvement: Autofocus on input field in login view

### ISSUE THREAD

**Issue by BlackDark** [RestyaPlatform/board#1669]
## Expected Behavior

It would be nice if the login page would autofocus on the input fields.
My colleagues for example use keepass to autofill the login data. But they always have to click manually on the input field to apply the focus.

## Current Behavior

No focus on input field.

## Possible Solution

Apply autofocus on the first input field (email)

## Your Environment
* Version used: 0.6.2 Docker

**Comment by rrjanbiah** [comment]
Internal note:

`autofocus` attribute https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
