### ISSUE TITLE
Issues with restyaboard.sh and CentOS7

### ISSUE THREAD

**Issue by giantjunkbox** [RestyaPlatform/board#167]
I am attempting to use the restyaboard.sh script on a clean / bare CentOS7 system. When all is done I end up and I attempt to access RestyaBoard I get a blank white screen. While the page is loading I see a red bar at the top of the page. If I view source I see HTML and a script.

I have tried the latest script, 018d9bb

I noticed an error in the installation where it looked like php-fpm was not being installed. After rolling back the snapshot and retrying the errors cleared, however the problems did not. I think this is package is a missing dependency

The only errors I see in the nginx log file is this one:
2016/02/02 00:38:09 [error] 1373#0: *2 open() "/usr/share/nginx/html/api/v1/oauth.json" failed (2: No such file or directory), client: 10.143.96.20, server: _, request: "GET /api/v1/oauth.json?_=1454402289070 HTTP/1.1", host: "restyaboard", referrer: "http://restyaboard/client/"

Nothing looks particularly interesting in the php-fpm log.

I see some errors in the installation log related to Postgresql: "ERROR:  must be member of role "postgres"". Looking at the restya database I do see that the referenced objects exist. I think this message is related to the script attempting to set the owner to postgres as the owner of the object is restya.

Not sure where to go look. This is on a VM and I can easily re-test the installation from scratch. I'm willing to spend some time on working through whatever I can to help.

One more thing, some of the questions in the installation script could be rephrased so that they are less ambiguous.

"Already installed Restyaboard y/n?" >> "Is Restyaboard already installed y/n?"

"To copy downloaded script, enter your document root path (e.g., /usr/share/nginx/html):" >> I'm not sure what this is really asking? I just put /usr/share/nginx/html.

Oh, and it probably obvious to most, but the installation instructions at http://restya.com/board/install.html#Installscript should have you chmod +x the script.

Thanks for your assistance and this project looks really, really nice. I'm hoping it works out for us. Nicely done so far.
[restyaboard_install.zip](https://github.com/RestyaPlatform/board/files/113628/restyaboard_install.zip)

**Comment by rrjanbiah** [comment]
@giantjunkbox Thanks for your kind words. We're looking into it now. Will keep you posted.

**Comment by rrjanbiah** [comment]
@giantjunkbox We're sorry, we couldn't get much idea, as everything looks OK.

> 2016/02/02 00:38:09 [error] 1373#0: *2 open() "/usr/share/nginx/html/api/v1/oauth.json" failed (2: No such file or directory), client: 10.143.96.20, server: , request: "GET /api/v1/oauth.json?=1454402289070 HTTP/1.1", host: "restyaboard", referrer: "http://restyaboard/client/"

Above line suggests that the nginx rewrite rule https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf#L23 is not taken into account (Not 100% sure though). Have you changed path? If possible, please check /conf.d/restyaboard.conf

> "ERROR: must be member of role "postgres"".

This is hopefully handled in dev version. 

> I'm not sure what this is really asking? I just put /usr/share/nginx/html.

It is the folder where you have to keep the software. 

> Oh, and it probably obvious to most, but the installation instructions at http://restya.com/board/install.html#Installscript should have you chmod +x the script.

Thanks. Fixed it now.

**Comment by giantjunkbox** [comment]
Thanks for the hint, the nginx rewrite rule looks like one might expect. Playing with this for a bit the problem appears to revolve around the FQDN of the box.

In the restyaboard.conf file I have the full FQDN of my box set in the server_name field. If I attempt to access Restyaboard using just the hostname the re-write rules don't appear to match. If I access the box using the FQDN... I get farther... I now see this showing up in the www-error.log:

[02-Feb-2016 17:12:22 Europe/Berlin] PHP Warning:  pg_connect(): Unable to connect to PostgreSQL server: could not
        Is the server running on host &quot;localhost&quot; (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Permission denied
        Is the server running on host &quot;localhost&quot; (127.0.0.1) and accepting
        TCP/IP connections on port 5432? in /usr/share/nginx/html/server/php/R/config.inc.php on line 44

I can connect to Postgresql via psql and everything looks good. I completely disabled selinux, rebooted, and that appears to have resolved this and I now get a login page.

I'll muck with the restyaboard.conf later and see if I can suggest some improvements. As far as the selinux - I don't know if I can be of any assistance with that beast...

Thanks

**Comment by rrjanbiah** [comment]
@giantjunkbox Many thanks for your note. This is really helpful. Please keep sharing your findings if any.

**Comment by giantjunkbox** [comment]
Had a chance to look at this more. The problem is that the server name in the /etc/nginx/conf.d/restyaboard.conf must match what the client used to connect. If you enter myserver.mydomain.com in the install script then attempt to goto myserver it fails. If you enter myserver in the install script then attempt to goto myserver.mydomain.com it fails.

You can enter multiple server_names, so you could use both myserver and myserver.mydomain.com and it would work...

I don't know much about nginx, but it seems like there is a better way... If you use the following in the /etc/nginx/conf.d/restyaboard.conf file:
        listen 80 default_server;
        server_name _;

Then comment out or remove the equivalent or the entire server block from /etc/nginx/nginx.conf it answers to everything, and you don't need to prompt for a server name in the installation script - which is exactly what you would want to do if this wasn't be shared with a bunch of other servers or exactly the opposite if it was... 

I guess the right thing largely depends on what this script is intended to be used for. Perhaps if it installs nginx it would be safe to assume it should be the default server.

**Comment by rrjanbiah** [comment]
@giantjunkbox Many thanks for your great insights. We'll see what we can do here. Thanks again

**Comment by rrjanbiah** [comment]
Leaving ``server_name _;`` as it is without replacing with server name prompted during installation step may work in this case. But, we think it is the right approach to replace it with exact server name, especially when we have multiple vhosts. 

Please feel free to reopen in case if this wouldn't still work.
