### ISSUE TITLE
New translations available

### ISSUE THREAD

**Issue by xchopin** [RestyaPlatform/board#1672]
Hi,

the french translation got updated; therefore you will have to manually add it since there aren't reviewers (#1537)

Regards,

**Comment by lmarikannan** [comment]
@xchopin Thanks for your contribution. Could you please give reviewers request? Because if you give reviewer request, we'll accept your request, and then you can review your own translation.

**Comment by xchopin** [comment]
@lmarikannan unfortunately I'm not allowed to click on the reviewed button "only reviewers can perform this action"

**Comment by lmarikannan** [comment]
@xchopin Now your all translations are reviewed by us, hereafter, your translations will be merge automatically from transifex. And your translations are committed on https://github.com/RestyaPlatform/board/commit/15b3ef79db40ff5770eb9a4291ff5ddb1431951e
