### ISSUE TITLE
Import from Trello not working on big files

### ISSUE THREAD

**Issue by dadarko** [RestyaPlatform/board#1676]
Again, 
having huge problems uploading json's from Trello.
When importing a smaller board everything is okay.
When importing 2mb json, the activities imported stop at 5 months ago (after 10.2017 to today's date, no data is imported)

When importing 6mb json, it wont import comments at all

I tried on the official demo server and everything is fine.

Can you show me how the import works so i can try to debug?

Thanks!

**Comment by lmarikannan** [comment]
@dadarko Really, sorry for that. If your json is not importing on your server,  you can debug import code on this function https://github.com/RestyaPlatform/board/blob/dev/server/php/libs/core.php#L995. Or your json is not importing on our demo server then, you can email to us with your json to info@restya.com, we'll check the json, and let you know.
