### ISSUE TITLE
Trello Import not getting comments

### ISSUE THREAD

**Issue by lmarikannan** [RestyaPlatform/board#1678]
## Expected Behavior

Trello Import should getting comments

## Current Behavior

Trello Import not getting comments while import trello json

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by dadarko** [comment]
I have the same issue. With smaller files it works very well. And on your demo server it works perfect even with big files. With huge files (6mb) id doesnt import comments at all.

**Comment by ssivachidambaram** [comment]
@dadarko We have modified the issue title. Actually here the case is some of the comments are provided by members but those members are removed later from that board. So those members are not coming in boardMembers object, but its coming in comments object. So now we modified the code to insert member if its not available in boardMembers.

**Comment by dadarko** [comment]
But i didn't remove them. I imported one json (2mb)(40% of comments didnt upload , added emails to user accounts in restya, then uploaded another 6mb board  and no comments were showed on that board.
