### ISSUE TITLE
user name limitation

### ISSUE THREAD

**Issue by yetzt** [RestyaPlatform/board#168]
i installed restya board and wanted to create an account for myself. as you can see, my username is `yetzt`. unfortunately my username was not allowed due to an unnessecary and pointless requirement of 6 characters, despite there being a user called `admin`, which has, as you may count, 5 characters. please remove this limitation.

**Comment by rrjanbiah** [comment]
Resolved by @AlecPapierniak https://github.com/RestyaPlatform/board/pull/166
