### ISSUE TITLE
Activities producing lots of PHP warnings

### ISSUE THREAD

**Issue by erl4nc** [RestyaPlatform/board#1685]
Log files are littered with the following, which is produced every 10 seconds:

PHP message: PHP Warning:  substr() expects parameter 1 to be string, array given in server/php/libs/core.php on line 394
PHP message: PHP Warning:  substr() expects parameter 1 to be string, array given in server/php/libs/core.php on line 394
PHP message: PHP Warning:  substr() expects parameter 1 to be string, array given in server/php/libs/core.php on line 394
PHP message: PHP Warning:  substr() expects parameter 1 to be string, array given in server/php/libs/core.php on line 394
PHP message: PHP Warning:  substr() expects parameter 1 to be string, array given in server/php/libs/core.php on line 394
PHP message: PHP Warning:  substr() expects parameter 1 to be string, array given in server/php/libs/core.php on line 394
PHP message: PHP Warning:  substr() expects parameter 1 to be string, array given in server/php/libs/core.php on line 394
PHP message: PHP Warning:  substr() expects parameter 1 to be string, array given in server/php/libs/core.php on line 394" while reading response header from upstream, client: IP, server: domain, request: "GET /api/v1/users/14/activities.json?type=all&last_activity_id=...&token=...&_=... HTTP/1.1", ...

## Context
Log file sizes are unnecessarily large and the warnings are hiding real errors.

## Your Environment

* Version used: 0.6.2
* Environment name and version (e.g. OS, PHP, PostgreSQL): ubuntu 16.04, PHP 7.2
* Operating System and version (desktop or mobile): desktop

**Comment by erl4nc** [comment]
This issue is not totally fixed.  The patched core.php now produces:

PHP message: PHP Warning:  strlen() expects parameter 1 to be string, array given in server/php/libs/vendors/finediff.php on line 436
PHP message: PHP Warning:  strcspn() expects parameter 1 to be string, array given in server/php/libs/vendors/finediff.php on line 651
PHP message: PHP Warning:  strspn() expects parameter 1 to be string, array given in server/php/libs/vendors/finediff.php on line 652
PHP message: PHP Warning:  strlen() expects parameter 1 to be string, array given in server/php/libs/vendors/finediff.php on line 436
PHP message: PHP Warning:  strcspn() expects parameter 1 to be string, array given in server/php/libs/vendors/finediff.php on line 651
PHP message: PHP Warning:  strspn() expects parameter 1 to be string, array given in server/php/libs/vendors/finediff.php on line 652
PHP message: PHP Warning:  strlen() expects parameter 1 to be string, array given in server/php/libs/vendors/finediff.php on line 436
PHP message: PHP Warning:  strcspn() expects parameter 1 to be string, array given in server/php/libs/vendors/finediff.php on line 651
PHP message: PHP Warning:  strspn() expects parameter 1 to be string, array given in server/php/libs/vendors/finediff.php on line 652
PHP message: PHP Warning:  strlen() expects parameter 1 to be string, object given in server/php/libs/vendors/finediff.php on line 436
PHP message: PHP Warning:  strcspn() expects parameter 1 to be string, object given in server/php/libs/vendors/finediff.php on line 651
PHP message: PHP Warning:  strspn() expects parameter 1 to be string, object given in server/php/libs/vendors/finediff.php on line 652

**Comment by ssivachidambaram** [comment]
@erl4nc As technically we have put `return false` if anyone of the from and to text are array/object. Please refer https://github.com/RestyaPlatform/board/commit/d8927cea06a0b5f23a5172956789209a0733831c. So only string will go to FineDiff library. But your errors are showing as array given. So we cannot able to reproduce this issue.

**Comment by erl4nc** [comment]
@ssivachidambaram you are right, I missed the diff on the return lines.  This should fix the issue.  My apologies.

**Comment by ssivachidambaram** [comment]
@erl4nc Thank you for the confirmation.
