### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by drpepper** [RestyaPlatform/board#17]
I'm looking to see if I can integrate Restya into an open source web project. My main requirement is to be able to automatically create users and shared boards, and to log those users in to access their boards. 

I see some code under the `api_explorer` directory but would like to know what is possible and if there is any documentation on the API.

Thanks!

**Comment by rrjanbiah** [comment]
@drpepper Basically all actions should be possible through API. The API server is oAuth2 compliant.

Simple documentation and API explorer/sandbox can be viewed in browser at http://yourdomain/api_explorer/ For example, http://board.demo.restya.com/api_explorer/

Just now, we have noticed that file upload endpoints are not included in above explorer; we'll add them in upcoming version.

For your case, the possible flow will be:

1. `GET /v1/oauth.json` - to get guest `access_token` for all other API calls (All API calls are oAuth protected)
2. `POST /v1/users/login.json` - to login to admin user. This will return higher level `access_token` that you can pass it for high level API calls
3. `POST /v1/boards.json` - create new board

Please let us know how it goes!

**Comment by drpepper** [comment]
Great, I'll try that out!

**Comment by drpepper** [comment]
After going through the API explorer, which is great by the way, I have a few further questions, please:

1. We are planning on integrating the Restyaboard interface via an iFrame, and using our existing server to create users and boards for our existing users and groups, and logging these users automatically within the iframe. Would this be possible?  I don't see anything about embedding in the docs...

2. How are the notifications sent from the server to the client? Are they accessible via the API as well?

3. What do you use to format the API explorer, please?

**Comment by rrjanbiah** [comment]
> We are planning on integrating the Restyaboard interface via an iFrame, and using our existing server to create users and boards for our existing users and groups, and logging these users automatically within the iframe. Would this be possible? I don't see anything about embedding in the docs...

Untested, but might work. After login, please try storing `access_token` in `auth` key in `sessionStorage` 

Refer https://github.com/RestyaPlatform/board/blob/master/client/js/views/login_view.js#L54

> How are the notifications sent from the server to the client? Are they accessible via the API as well?

Yes, through `activities.json` endpoint

> What do you use to format the API explorer, please?

We use Swagger UI https://github.com/swagger-api/swagger-ui

It is mentioned in credits section of "About" page http://board.demo.restya.com/#/about This page is accessible by clicking Restyaboard icon found in left corner of the footer.

**Comment by rrjanbiah** [comment]
@drpepper Are things working as expected?

**Comment by drpepper** [comment]
@rrjanbiah Haven't done it yet but will keep you posted!

**Comment by rrjanbiah** [comment]
@drpepper OK, sure!

**Comment by jaiBITS** [comment]
Hi, 

I am trying to access rest API through postman using auth. But request to api only returns access token. But not able to do it.

**Comment by rrjanbiah** [comment]
@jaiBITS As I mentioned above https://github.com/RestyaPlatform/board/issues/17#issuecomment-131810549, all API endpoints, except `/v1/oauth.json` are oAuth2 protected. You'll need `access_token` to access all other APIs.

We're not familiar with postman. So, if you're able to figure it out, please share your findings.

**Comment by rrjanbiah** [comment]
@jaiBITS Were you able to figure it out? Do you need any help from us?

**Comment by rrjanbiah** [comment]
Closing this for now. If you get any issues, please feel free to reopen.

**Comment by rrjanbiah** [comment]
Reopening this as we're getting similar such requests. Have to properly document the workflow somewhere.

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/commit/ae6b1c0446cee21e6c81f92fedc3bf89f4bada8f.

**Comment by rrjanbiah** [comment]
@lmarikannan  Reopening this as above fix is not really helpful in understanding the API workflow. Need proper documentation.

**Comment by rrjanbiah** [comment]
This isn't look like a correct fix/solution. Reopening.

**Comment by lmarikannan** [comment]
Updated on restya.com API documentation - http://restya.com/board/docs/api

**Comment by SheheryarGhaznavi** [comment]
https://github.com/RestyaPlatform/board/issues/17#issuecomment-132238141

i am trying to login into restyaboard through api 
i first get the outh token (success)
then login though login.json (sucess)
then i redirect to domain.com/#/boards it redirect me to login page
