### ISSUE TITLE
Work in progress (WIP) limit

### ISSUE THREAD

**Issue by arnoldligtvoet** [RestyaPlatform/board#1700]
New to Restyaboard and surprised that I could not set a WIP limit (essential part of Kanban way of working) on swimlanes? I would like to request this as a feature enhancement for upcoming releases.

**Comment by rrjanbiah** [comment]
@arnoldligtvoet

Thanks for suggesting this feature. When you get a chance, can you please share more details about this requirement like how it should work?

**Comment by arnoldligtvoet** [comment]
WIP limits are an effective tool in Kanban to make sure that work gets finished before new work is started (stop starting and start finishing). Most common is to place a WIP limit on each lane, where the WIP limit is a maximum number of cards that can be in that lane. Imagine a Kanban board with the lanes ToDo, Doing, Testing, Done and there is a WIP limit of 5 on Testing. As soon as there are 5 cards in that lane no additional cards can be moved to testing, so the team first have to finish cards that are in testing and move them to done. Some systems also have the ability to have a WIP limit on team members, so a certain team member can only handle X amount of cards at a time. 

Nice explanation here : http://engineering.usertesting.com/2016/07/the-magic-of-wip-limits-in-kanban/

**Comment by rrjanbiah** [comment]
@arnoldligtvoet Thanks for sharing additional information. We'll internally discuss this and take it forward. Thanks again

**Comment by rrjanbiah** [comment]
*Internal note*

Based on further discussion with @itzmeank need to add card limit in list setting so that users can't add more cards than one specified in limit

**Comment by itzmeank** [comment]
@rrjanbiah is it possible to give that ability to the owner of the board ?

**Comment by arnoldligtvoet** [comment]
The WIP should be a property of a list. Each list can have a different WIP limit. I would suggest adding it under the gear icon on the list

**Comment by itzmeank** [comment]
@arnoldligtvoet and that ability should only be available to the owner of the board, is that correct ? please confirm...

**Comment by estevaocma** [comment]
@itzmeank Correct, that should be available only to the owner of the board. We should also have the ability to create swimmlanes.

**Comment by itzmeank** [comment]
@rrjanbiah do we have plans to implement this feature ?

**Comment by sridhar391** [comment]
Added the Work in progress limit plugin and it will be available on the upcoming version
