### ISSUE TITLE
List moved date - shown only temporarily

### ISSUE THREAD

**Issue by Mattes1000** [RestyaPlatform/board#1717]
When I move a card on the board page the moved date is shown.
When I refresh the board, the moved date is not showing.

I got the app "Hide Creation Date" enabled and I don´t want the "moved date" to be shown.
Since https://github.com/RestyaPlatform/board/issues/1616 is fixed, the Moved Date is shown.

Maybe there is an need of an new App "Hide Move Date"?

**Comment by sridhar391** [comment]
Really sorry for that, now we have updated the styles for toggling list moved date in hide card created date app and you can download the app latest version from https://github.com/RestyaPlatform/board-apps/releases/download/v1/r_hide_card_created_date-v0.1.1.zip

**Comment by Mattes1000** [comment]
Perfect! Thank you!

**Comment by sridhar391** [comment]
If you face any issues in future, please re-open this issue
