### ISSUE TITLE
Add an option to open card in maximized view

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#173]
From https://groups.google.com/forum/#!topic/restya/lVBaFPBQpGU by Antti Hurme:

>> Add an option or make it default so that when a card is opened, it would open in the center rather than in the bottom right corner. Perpahs add an option to 

> This is possible. But, would love to know the reason. Wouldn't it be killing "open many cards at same time" feature?

In my opinion it wouldn't, as long as you only have one card open. Would it be possible to check if there's a card open, and if there is then open it to the bottom right. Perhaps a user option to open single cards (when no other cards are open)as maximized/centerd could be a solution? Having multiple open at the same time is good, but it's quite crammed (hard to read) when it's opened in the cards bar and is limited in size. One idea could be to havea a different style when it's opened in the smalller form. Perhaps utilize Accordion or Tabs when it's small (or when maximized as well)?

**Comment by rrjanbiah** [comment]
@ssivachidambaram What about double click or ctrl+click for maximized view?

**Comment by ssivachidambaram** [comment]
@rrjanbiah Maximized view implemented on ctrl+click.
