### ISSUE TITLE
Move all cards of list not working correctly?

### ISSUE THREAD

**Issue by BlackDark** [RestyaPlatform/board#1749]
## Expected Behavior

When moving all cards to another list all cards should be moved to the other list.

## Current Behavior

Somehow not all cards are moved or only some cards are moved?

## Screenshots (if appropriate):
https://streamable.com/vvylw

## Your Environment

* Version used: 0.6.3 Docker
* Operating System and version (desktop or mobile): Win 7, Chrome 65

**Comment by sridhar391** [comment]
Duplicate #1744  and we have fixed this issue in https://github.com/RestyaPlatform/board/commit/8bf65fb53a5f5164eec9c62fbd3b1fba61b0693c
