### ISSUE TITLE
E-mail notification not working (when mentioning member on card)

### ISSUE THREAD

**Issue by dadarko** [RestyaPlatform/board#1751]
When mentioning a member on a board (etc @ssivachidambaram ) the member doesn't receive any e-mail notification. All other notifications are working.

The mail log is clear

**Comment by sridhar391** [comment]
we are unable to reproduce the issue, can you please give your teamviewer details at info@restya.com

**Comment by sridhar391** [comment]
@dadarko Cron was not set in server and also email is missing in users table. Email notification will works once you updated the mentioned details. Please reopen if you are having problem in future.

**Comment by dadarko** [comment]
@sridhar391 could you help me out with setting up Cron?
All other e-mails work...
Thanks!

**Comment by sridhar391** [comment]
Please refer https://github.com/RestyaPlatform/board/issues/1919 for setting up cron
