### ISSUE TITLE
Editing a comment break's the comment 

### ISSUE THREAD

**Issue by dadarko** [RestyaPlatform/board#1754]
When editing a comment, in the activity is shown:

##USER_NAME## updated comment to this card ##CARD_LINK##

12:00-
12:00-14:00=02:00
razmontiranje kučišta, micanje Dominikove elektronike, spajanje nove elektronike koja je došla,

spajanje nove elektronike jedan izlaz na bateriju, jedan na mobitel i spajanje jos dva mobitela na bateirju

**Comment by sridhar391** [comment]
Duplicate #1398 and fixed in this commit https://github.com/RestyaPlatform/board/commit/bca482c79c2f158442cc4f62a30c98c6f2d67c7f
