### ISSUE TITLE
No login page after new install using shell script

### ISSUE THREAD

**Issue by Twizty1** [RestyaPlatform/board#1756]
Fresh install using shell script from website.  Installed on centos 7.  Just get blank page with forever cycling orange bar.

Checking through various logs for potential cause and find this in /var/log/php-fpm/www-error.log

```
[19-Apr-2018 19:50:56 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function pg_connect() in /usr/share/nginx/html/restyaboard/server/php/config.inc.php:55
Stack trace:
#0 /usr/share/nginx/html/restyaboard/server/php/R/r.php(26): require_once()
#1 {main}
  thrown in /usr/share/nginx/html/restyaboard/server/php/config.inc.php on line 55
```

This repeats over and over in the log.  Have confirmed that php-pgsql is installed.

```
[root@ nginx]# yum install -y php70w-pgsql
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.rackspace.com
 * epel: mirror.beyondhosting.net
 * extras: mirror.atlanticmetro.net
 * updates: mirrors.rit.edu
 * webtatic: us-east.repo.webtatic.com
Package php70w-pgsql-7.0.27-1.w7.x86_64 already installed and latest version
Nothing to do

```

Complete loss for cause.

**Comment by rrjanbiah** [comment]
> Call to undefined function pg_connect()

This may be due to pgsql extension is not enabled in `php.ini` file. Please enable by removing `;` in front of:
`;extension=php_pgsql.so`

Note that ';` is a comment symbol for `ini` files

**Comment by Twizty1** [comment]
Just found the problem.  php-fpm wasn't starting for some reason.  Not sure why.  Tried starting it and it failed.

Rebooted machine, stopped nginx, stopped php-fpm.  Then restarted php-fpm followed by nginx and all is well.

**Comment by rrjanbiah** [comment]
@Twizty1 Glad to know that. Thanks for updating
