### ISSUE TITLE
Doug-nut chart in boards listing misses a list

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#176]
From https://groups.google.com/forum/#!topic/restya/lVBaFPBQpGU by Antti Hurme:

>> The circles that show how many cards are in each board group are inconsistent, sometimes a group of cards is missing from the circle

> If a list has 0 cards, it won't be displayed, as it is a pie chart flavor. Is that you're talking about?
 
For example we have a board with 4 lists, each have a few cards in it. One of the lists with cards don't show up in the  in the circle.

**Comment by ssivachidambaram** [comment]
Fixed https://github.com/RestyaPlatform/board/commit/5ae52493d87e19a40e207c13f7dcfa461fc91145.

**Comment by rrjanbiah** [comment]
@ssivachidambaram Please mention what was actually fixed. Are we able to reproduce above issue?

**Comment by ssivachidambaram** [comment]
@rrjanbiah While move cards to empty lists in board view its not updated in doughnut chart.
