### ISSUE TITLE
Add a filter in calendar view to show cards by creation date

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#177]
From https://groups.google.com/forum/#!topic/restya/lVBaFPBQpGU by Antti Hurme:

>> Calendar only shows cards with a due date. Perhaps add a filter to show 
>> cards by their creation date as well? Would make it possible to track which 
>> cards were created on what day

> Good suggestion. But, would love to know the usecases.

We were thingking the calendar could be used to see what has been done during a week. Having the calendar show up more tasks with or without fitlers would allow tracking tasks easier.

**Comment by julienmoinard** [comment]
I agree, for a long task, maybe it is a good idea to have only 1 event for each day.

**Comment by rrjanbiah** [comment]
@julienmoinard 

> I agree, for a long task, maybe it is a good idea to have only 1 event for each day.

Can you please consider rephrasing? It looks like, you're talking about something else (?)

**Comment by julienmoinard** [comment]
Sorry, I think too, I talk about something else.  In fact, when I create a card, restya takes the date of the day and use a due time. (I can't change the starttime). And in the calendar I have only 1 event at the end .
I think it is better to able to change the startdate not only the date of the day and use an event for the duration.  I am not sure it is the good issue you are right.

**Comment by rrjanbiah** [comment]
@julienmoinard Thanks for clarifying.

**Comment by julienmoinard** [comment]
Thanks to you for your good application !

**Comment by rrjanbiah** [comment]
@julienmoinard Thanks for your kind words. If you have any more feedback, please feel free to open tickets.

**Comment by lmarikannan** [comment]
@julienmoinard Closing this for now. If you get any issues, please feel free to reopen.
