### ISSUE TITLE
Can't send email from Azure hosting

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1771]
There is a known issue in Azure that emails can't be sent from Azure VM. So, have to:

1. Update document
2. Update install script

**Related links**

1. https://blogs.msdn.microsoft.com/azuresecurity/2016/08/16/pro-tip-on-sending-email-from-azure-virtual-machines-to-external-domains/
2. https://blogs.msdn.microsoft.com/mast/2017/11/15/enhanced-azure-security-for-sending-emails-november-2017-update/
3. https://blog.himorpheus.com/2016/03/06/linux-vm-on-azure-a-mail-server/

**Comment by crazimoskito** [comment]
@rrjanbiah is there a simple way to configure restyaboard to use an external SMTP server (e.g. a gmail account) to send out the notification/registration emails etc. for a restyaboard running inside an Azure VM?
If yes, can you please describe the steps?
Thank you!

**Comment by rrjanbiah** [comment]
@crazimoskito If it is Windows VM, you can mention the external SMTP details in `php.ini` and that will be sufficient. (Refer https://github.com/RestyaPlatform/board/issues/450#issuecomment-196814831)

For Linux VM, you can add external SMTP configuration through `postfix`. For that you may try this Sendgrid guide https://sendgrid.com/docs/Integrate/Mail_Servers/postfix.html and let us know how that's working?
