### ISSUE TITLE
Gantt layout needs to account start date

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#178]
From https://groups.google.com/forum/#!topic/restya/lVBaFPBQpGU by Antti Hurme

Gantt chart is pretty useless as tasks show as one day long as it only takes into account the due date. Add a start date (which would by default use the creation date) to to create tasks that take several days to complete.

**Comment by ssivachidambaram** [comment]
Gantt chart is working like described in issue.
