### ISSUE TITLE
Install script stops with 'FATAL: Peer authentication failed for user "postgres"' with error code 32

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1783]
For some users, install script terminates with FATAL: Peer authentication failed for user "postgres"

**Comment by sridhar391** [comment]
The authentication has been failed due to the updation of the Restyaboard by user without full installation and also we have added support to handle PostgreSQL peer authetication in install script https://github.com/RestyaPlatform/board/blob/dev/restyaboard.sh#L515.
