### ISSUE TITLE
Installation issue: nginx not started due to apache running in port 80

### ISSUE THREAD

**Issue by ssivachidambaram** [RestyaPlatform/board#1800]
Using the standard Ubuntu 17 VM on Azure and running the Restyaboard install script fresh out of the box, nginx failed to start after the installation. After some investigation, it seems Apache was listening on port 80 already, so nginx couldn't start and I first had to stop the Apache service manually and then start nginx. Maybe a check for this could be added to the Restyaboard installer, to check if Apache or anything else is running and listening on ports 80 and 443, and if yes, to throw an error, ask whether to shut them down, or similar.

Following this, nginx wasn't automatically set to the Restyaboard directory after the install script finished. I don't know if that is related to issues with a), but I had to change this in the configuration manually.

## Expected Behavior
Install script should check and stop whether apache running in port 80.

## Current Behavior
nginx not started due to apache running in port 80

**Comment by pinkunicorn** [comment]
Another option could be to see the presence of a running apache server at install time as a desire from the user to use apache as the web server.

**Comment by BlackDark** [comment]
I guess nginx is not the only possible app which could block the http ports.

My suggestion is in focusing in docker #1741 instead of install scripts
