### ISSUE TITLE
How to Change Intro Video?

### ISSUE THREAD

**Issue by crazimoskito** [RestyaPlatform/board#1808]
**IMMEDIATE ISSUE:**
I need to change the intro video (that appears for first-time users) for my users to a short introduction I have made for my users in their language, custom for our organisation, as they didn't very well understand the standard introduction video which uses the English Restyaboard GUI.

I have found the responding youtube iframe in this file in /restyaboard/client/js
`default.cache.cf26302f.js`

Unfortunately, I think this is compiled Javascript (from EJS) and this file is practially impossible to edit. I've tried it anyway using Notepad++ and in the process destroyed the login screen for Restyaboard which is now no longer loading (thankfully, I made a copy before).

**Can you advise me how I can easily replace the iframe of the YouTube Video.**

**FEATURE REQUEST:**

- In a future version I would like to request that the admin can set the iframe to the intro video in the admin panel.

- There should also be a way for the admin to "push" a welcome video or welcome message even to existing users upon their next login, so he can inform them about changes, downtime, new features etc. 

- In the popup for the users should be a checkbox saying "I have read this message - don't display this message again", if they don't click this checkbox, the message or video should appear every time. This should be resettable by the admin if he publishes a new message or video, so it is again seen by everyone upon login.

**Comment by sridhar391** [comment]
Thanks for your request, we will consider this in the future version

Temporary solution for changing the Intro video:
For changing the intro video links in
`/client/js/default.cache.cf26302f.js` you can find the youtube link
`https://www.youtube.com/embed/GD8Nmi1600U?autoplay=1` and you can
change it with your video link and you have to clear all caches and
reload to see the changes.

If you want to show the intro video for existing users and new users,
please execute the following SQL command in your Restyaboard database:
`UPDATE users SET is_intro_video_skipped = 'f';`

For particular user, you can set the Intro video by the username:
`UPDATE users SET is_intro_video_skipped = 'f' WHERE "username" = 'username';`
