### ISSUE TITLE
Notification needed for card overdue

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#181]
From https://groups.google.com/forum/#!topic/restya/l3FsaCSrYCI by Domenico Mele

notifications about cards in overdue date

**Comment by rrjanbiah** [comment]
Also from https://groups.google.com/d/msg/restya/lVBaFPBQpGU/fG83mKnaAAAJ by Antti Hurme

- eMail reminder when a cards due date is close, perhapse one day/24h before due-date?

**Comment by ssivachidambaram** [comment]
Done.
