### ISSUE TITLE
Feature: Display organisation in Card move/copy and my boards

### ISSUE THREAD

**Issue by deadeye636** [RestyaPlatform/board#1810]
We have the problem that boards have the same name in different organisations. 
if we now try to copy/move a card to another board we dont now which is the right one. 
it would be nice to have the organisation name in the selection spinner. 
like
ToDo (ACME)
ToDo (Test organisation)

the same problem is on the my board page.

**Comment by sridhar391** [comment]
In the latest released version v0.6.4, the boards have been organised with the organization name
