### ISSUE TITLE
Problem with activity displayed when comment is updated

### ISSUE THREAD

**Issue by bseclier** [RestyaPlatform/board#1813]
Hi,
When we edit a comment in a card, we have a new "activity" telling us that we updated our comment (see screenshot, restya 0.6.3). We have a bug here because username and card_link are not correct, but I just don't want this information here, I just want to see the comments of my cards, is it possible to disable this new activity notification ?
Thanks a lot.
![capture du 2018-05-15 11-13-33](https://user-images.githubusercontent.com/3954149/40048012-68afa04c-5831-11e8-9a61-74af2d197bed.png)

**Comment by sridhar391** [comment]
Duplicate #1754 and fixed in this commit bca482c

**Comment by bseclier** [comment]
Thank you !
