### ISSUE TITLE
Need provision to copy checklist items in same list

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#182]
From https://groups.google.com/forum/#!topic/restya/l3FsaCSrYCI by Domenico Mele

possibility to share checklist'item in the same list; for example if I create a checklist for a card and for another one I need to set the same checklist, I'd be appreciated if I can't rewrite it again but I select the first one. Obviously, all item'll be unchecked.

**Comment by ssivachidambaram** [comment]
Fixed
