### ISSUE TITLE
Failure of RESTYA to load Login page after script install

### ISSUE THREAD

**Issue by rgmmach** [RestyaPlatform/board#1824]
Installed using the restyaboard.sh onto a CENTOS 7 distribution
## Expected Behavior

I expected to see the login page after opening ports in the firewall
found errors in install log (see attached)

## Current Behavior

Page "displays" blank (no errors)
## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/23518416/40300329-8fa4c67a-5d1b-11e8-90f8-32bbe053607a.png)

## Possible Solution

Unknown? Tried it again - same result. Tried a reboot of the virtual machine. same result. Tried stopping and starting nginx - same result

## Steps to Reproduce (for bugs)

1. Start up Centos VM.
2. yum install wget
3. follow steps on restya website for self hosted Linux
4. run the script restyaboard.sh
5. open ports 80 band 25 and restart network and reload firewalld
6. Check ports open
7. check nginx running (ps -ef | grep nginx)
8. go to browser restya01.rmtp.rmt.com.au
9. blank page

## Context

Cannot use the product

## Your Environment

* Version used: v0.6.3
[restyaboard_install_log.zip](https://github.com/RestyaPlatform/board/files/2021985/restyaboard_install_log.zip)

* Environment name and version (e.g. OS, PHP, PostgreSQL): Centos 7, rest as installed by script
* Operating System and version (desktop or mobile): Client is Windows 10, Google Chrome
* Link to your project:

**Comment by sridhar391** [comment]
Can you please check `SELINUX` value in `/etc/selinux/config` and update it to `disabled`. Then reboot the system by using `reboot` command.

**Comment by rgmmach** [comment]
A look at the nginx error file (/var/log/nginx/error.log) shows:
2018/05/22 08:34:45 [error] 2513#2513: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.15.81, server: restya01.rmtp.rmt.com.au, request: "GET /api/v1/oauth.json?_=1526949268987 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "restya01.rmtp.rmt.com.au", referrer: "http://restya01.rmtp.rmt.com.au/index.html"

**Comment by rgmmach** [comment]
Found the issue(s)

Based on the log entry 
2018/05/22 14:21:22 [crit] 22515#22515: *1 connect() to unix:/var/run/php-fpm/php7.0-fpm.sock failed (13: Permission denied) while connecting to upstream, client: 192.168.15.81, server: restya01.rmtp.rmt.com.au, request: "GET /api/v1/oauth.json?_=1526970065821 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php7.0-fpm.sock:", host: "restya01.rmtp.rmt.com.au", referrer: "http://restya01.rmtp.rmt.com.au/"

I did the following
1. the path to the sock file was updated to **/run/php-fpm/php7.0-fpm.sock** as the existing path was incorrect in these files
    -  /etc/nginx/conf.d/restyaboard.conf
    -  /usr/share/nginx/html/restyaboard/restyaboard.conf
    -  /opt/restyaboard/restyaboard.conf
2. the **php7.0-fpm.sock** needed to be created/updated by running the command (the file is created every time php-fpm is started)
    -  /usr/sbin/php-fpm
3. I also changed **/etc/php-fpm.d/www.conf** to include the lines  below (_but may not have been necessary_)
   - listen.owner = nginx
   - listen.group = nginx
   - listen.mode  = 0660 
4. I checked the **php7.0-fpm.sock** belonged to nginx (which it did) 
   - ls -l /var/run/php-fpm/php7.0-fpm.sock
   - chown nginx /var/run/php-fpm/php7.0-fpm.sock
   - chgrp nginx /var/run/php-fpm/php7.0-fpm.sock
5. I set the php-fpm to start at boot 
   - systemctl enable php-fpm

**Comment by sridhar391** [comment]
@rgmmach Thanks for your detailed explation
