### ISSUE TITLE
LDAP issues

### ISSUE THREAD

**Issue by giantjunkbox** [RestyaPlatform/board#183]
**User names with a '-' can not login**
It appears that we cannot login using LDAP users with a '-' in their name. Looking at a traffic capture I can see that we successfully retrieve the users details from the LDAP directory and are able to bind to the directory as the user. The message we receive from the UI is: "Sorry, login failed. Either your username or password are incorrect or admin deactivated your account."

I don't see any error messages in any logs. I haven't looked at the code, but it seems like there might be some logic that prevents '-'s.

**Users details are not imported from LDAP**
When logging in as a LDAP user the users details are not imported from LDAP. For example I see the following:
Full Name: <blank>
Initials: <The first letter of my username>

**LDAP fields are named inconsistently in the LDAP configuration**
The fields are named are very different from what is normally used. I would suggest the following changes.
Root dn >> User Search Base
Organization >> I have no idea what this field is for...
Uid field >> User ID Attribute
Bind dn >> Username DN
Bind password >> Password

There should also be an option of specifying an LDAP filter (perhaps that what organization is?)

**LDAP Bind password is displayed in clear text in the UI**
The password would not be visible and should not be transmitted to the client. The user should only be able to set or clear the password.

Thanks for the great product, keep up the nice work

**Comment by rrjanbiah** [comment]
@giantjunkbox Many thanks for your valuable input and report. We'll look into it and fix it.

**Comment by rrjanbiah** [comment]
Related #79

**Comment by rrjanbiah** [comment]
Few more related issues from https://groups.google.com/forum/#!topic/restya/lVBaFPBQpGU by Antti Hurme

- LDAP Login if the user doens't have the email field specified, returns same error message as when user enters wrong password or has been disabled. A check to see if the user has email field correctly enterd in LDAP and returning appropriate error message would help a lot when debuggnign LDAP issues
- LDAP configuration Bind Password is stored as cleartext. Please don't do this :)
- Admin > Users table doesn't show if a user is a LDAP user or not. Would like to see a column that displays a user as a LDAP (checkbox) using the "is_ldap" field from db.
- LDAP users First Name and Last Name don't populate the full_name entry in users table.
- LDAP users shouldn't see the change password option, or should they? Didn't go trough the code to see if LDAP users would really be able to change their LDAP password using restya.
- Login IP and Registered IP don't populate correctly in the Admin > Users view ( http://imgur.com/8ZqeMyG )
- php mail() function doesn't like /r/n in headers when using centos as the OS. Perhaps use PHP_EOL for line breaks?

**Comment by giantjunkbox** [comment]
Shoot, sorry - didn't see that other issue.

After reading the above I suspect the problem with the accounts with a '-' in them have more to do with the missing email address then the '-'.

Thanks

**Comment by giantjunkbox** [comment]
Confirming that setting an email address in LDAP corrects this; however it also illuminates a new problem.

If i have two LDAP accounts with the same email address Restyaboard seems to think they are the same account.

To reproduce create two LDAP accounts with a different sAMAccountNames and the same email address. Login with the first one then logout. Then login with the second one.

It looks like it is using the email address as the account name somehow.

**Comment by rrjanbiah** [comment]
@giantjunkbox Many thanks for sharing more related details.

Yes, in Restyaboard, users can login either by username or email. So, that feature seems to bring up above issues. We'll fix it soon.

**Comment by ssivachidambaram** [comment]
Changed labels and given help tip for LDAP settings to configure easily. Also fixed reported issues related to LDAP.
