### ISSUE TITLE
File name in upgrade instructions doesn't match file name in downloaded zip file

### ISSUE THREAD

**Issue by pinkunicorn** [RestyaPlatform/board#1836]
The page https://github.com/RestyaPlatform/board has a section "Upgrade" that tells me to apply the script "/sql/upgrade-0.6.3-0.6.4.sql" in order to upgrade from 0.6.3 to 0.6.4. If I look at the files in the project via the same GitHub page, the file names match. If, on the other hand, I download all the code via https://github.com/RestyaPlatform/board/releases/download/v0.6.4/board-v0.6.4.zip I get a zip file containing "/sql/v0.6.4.sql" instead of "/sql/upgrade-0.6.3-0.6.4.sql". This is confusing for no good reason.

## Expected Behavior
File name in documentation and code should match, regardless of where the code is obtained.

## Current Behavior
File name in documentation and code matches the files on GitHub but not the files in the zip file downloadable from GitHub.

**Comment by sridhar391** [comment]
We will download the zip while installing and updating Restyaboard via shell script file and we have provided link for the sql files that have been shown in the `Upgrade` section of `README.md` file

**Comment by pinkunicorn** [comment]
This (while useful) does not address that the file name in the zip file is different, as far as I can see. I'll admit that it's not difficult to figure out the name change if one is upgrading from the zip file but on the other hand I don't see the point of renaming the file before making the zip file.

**Comment by sridhar391** [comment]
Thanks for your suggestion. Actually v0.6.4.sql is used in install script. For manual upgrade, we have committed SQL in GitHub repository. Now we have provided link for those upgrade SQL to avoid confusion.
