### ISSUE TITLE
Uncaught (in promise) DOMException in setItem of localforage issue on some browsers

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#1838]
## Expected Behavior
1. Usage of localforage by restyaboard in browsers could not throw any issue on browsers
## Current Behavior
1. Usage of localforage by restyaboard in browsers throw issue on some browsers

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by rrjanbiah** [comment]
Reopening as this is still an issue in few client browsers

**Comment by rrjanbiah** [comment]
Linking to localForage issue https://github.com/localForage/localForage/issues/816

**Comment by rrjanbiah** [comment]
*Internal note*

Perhaps, will this comment fix the issue https://github.com/localForage/localForage/issues/816#issuecomment-388345070 ?
