### ISSUE TITLE
Wrong creation date and creator for cards after import from Trello

### ISSUE THREAD

**Issue by pinkunicorn** [RestyaPlatform/board#1848]
## Expected Behavior
Cards on boards imported from Trello should have the same creator and creation date as they had on Trello.

## Current Behavior
Cards on boards imported from Trello appear as created by the person doing the import and appear to be created at the time the import was run.

## Your Environment
* Version used: 0.6.4
* Environment name and version (e.g. OS, PHP, PostgreSQL): CentOS 7, PoastgreSQL 9.6

**Comment by sridhar391** [comment]
The JSON for the single card in the board is added below and the card created user and created date of the card is not given. so, the card created user is the person doing the import 
 `{
            "id": "569f2b8178a06711e157bf16",
            "checkItemStates": null,
            "closed": false,
            "dateLastActivity": "2016-01-20T06:38:57.371Z",
            "desc": "",
            "descData": null,
            "idBoard": "569f2b8178a06711e157bf05",
            "idList": "569f2b8178a06711e157bf06",
            "idMembersVoted": [],
            "idShort": 5,
            "idAttachmentCover": "569f2b8178a06711e157bf0b",
            "limits": {
                "attachments": {
                    "perCard": {
                        "status": "ok",
                        "disableAt": 950,
                        "warnAt": 900
                    }
                },
                "checklists": {
                    "perCard": {
                        "status": "ok",
                        "disableAt": 475,
                        "warnAt": 450
                    }
                },
                "stickers": {
                    "perCard": {
                        "status": "ok",
                        "disableAt": 67,
                        "warnAt": 63
                    }
                }
            },
            "idLabels": [],
            "manualCoverAttachment": false,
            "name": "You can also see board activity, change the background and more. ",
            "pos": 327679,
            "shortLink": "zLiWROvN",
            "badges": {
                "votes": 0,
                "attachmentsByType": {
                    "trello": {
                        "board": 0,
                        "card": 0
                    }
                },
                "viewingMemberVoted": false,
                "subscribed": false,
                "fogbugz": "",
                "checkItems": 0,
                "checkItemsChecked": 0,
                "comments": 0,
                "attachments": 0,
                "description": false,
                "due": null,
                "dueComplete": false
            },
            "dueComplete": false,
            "due": null,
            "email": "user+2lkf7xpdms2webdymf6+2lkf7xx5xk4yinnjk0m+1eq21n9zmc@boards.trello.com",
            "idChecklists": [],
            "idMembers": [],
            "labels": [],
            "shortUrl": "https://trello.com/c/zLiWROvN",
            "subscribed": false,
            "url": "https://trello.com/c/zLiWROvN/5-you-can-also-see-board-activity-change-the-background-and-more",
            "attachments": [],
            "pluginData": [],
            "customFieldItems": []
        }`
