### ISSUE TITLE
Need option to remove (unused) label from board

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#185]
From https://groups.google.com/forum/#!topic/restya/GgCN02Ea15g by Vicente Gonzalez

Is it possible to remove a label of a board? 

I want to remove a label which is not associated to any card.

**Comment by ssivachidambaram** [comment]
Done.

**Comment by rrjanbiah** [comment]
From Vicente Gonzalez in https://groups.google.com/forum/#!topic/restya/GgCN02Ea15g

> We have update to v 0.2.1 (2016-03-16) but we can't delete the labels. The process begins and returns OK but the labels still remains in our board.

So, reopening it now.

**Comment by lmarikannan** [comment]
We have tried to reproduce this issue in http://boardalpha.demo.restya.com, but we cannot able to reproduce it. Closing this for now.
