### ISSUE TITLE
Documentation for email to board (IMAP) feature

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1853]
Need documentation on how to setup plus addressing for different mail servers and how to configure IMAP feature.

Many people also don't know the use case for IMAP and so need documentation with screenshots

**Comment by sridhar391** [comment]
Documentation about IMAP has been added and the link for the documentation is http://restya.com/board/docs/imap/

**Comment by sridhar391** [comment]
Screenshots for Card Email settings, Board Email settings added and the link for the documentation is http://restya.com/board/docs/imap/ and IMAP uses shown in the first page
