### ISSUE TITLE
Version codenames

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1859]
Starting from v0.6.6, all upcoming versions will be codenamed after legendary music bands, as a token of respect and appreciation.

### What does it mean?

- Versions will be codenamed as in "v0.6.6 (Modern Talking)"
- Default board background will be changed to respective band's wallpaper
- A new "codename" app will be created and that will provide information on respective bands
- Anyone can propose their favorite band for upcoming milestones https://github.com/RestyaPlatform/board/milestones

**Comment by rrjanbiah** [comment]
I'm not sure how this changeset https://github.com/RestyaPlatform/board/commit/0ed6cf2641807147cbe17136f60d638dde1a0dc3 will close this issue.

**Comment by sridhar391** [comment]
We have created an app regarding Version codenames

**Comment by rrjanbiah** [comment]
@sridhar391 Please open appropriate issues and refer changeset when closing. Wrong references will be difficult to refer back and maintain

**Comment by sridhar391** [comment]
Sure, we will open appropriate issue and refer changes when closing
