### ISSUE TITLE
Salt change

### ISSUE THREAD

**Issue by comzeradd** [RestyaPlatform/board#1876]
Hi,

For some reason the `SECURITYSALT` changed on a Restya installation. I know that this is used to generate the password hashes, so it's expected result that users can't login. But shouldn't the "forgot password" generate a new password with the new salt?

**Comment by sridhar391** [comment]
we don't use `SECURITYSALT` for password changes and we have used https://github.com/RestyaPlatform/board/blob/dev/server/php/libs/core.php#L105 and the forgot password option is working
