### ISSUE TITLE
Installation / document issue

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1879]
Note from Michael Schechter: FYI, even with support's help, it was a pain to install restyaboard. Here are my notes, in the hopes that it lets you adjust the script for the better:

**HOWTO install restyaboard**

 - from [http://restya.com/board/install](http://restya.com/board/install)

  

 - MUST USE UBUNTU XENIAL!!!! Debian 9 doesn't work, even though they don't say it won't.
 - always say 'n' to 'is restyaboard already installed'
 - can change name in /etc/nginx/conf.d/restyaboard.conf -- line 2
 - make LCX container called **restyaboard.whatever.dom**
 - adduser **yourlogin**
 - ssh in from somewhere you can paste to/from
 - su
 - apt update (NOTE: use apt, not apt-get or aptitude, when doing \*anything\* here. Using apt-get as in the script doesn't seem to allow many of the apps to install)
 - apt upgrade
 - apt install nginx php php7.2-fpm php7.2-curl php7.2-pgsql php7.2-mbstring php7.2-ldap php-imagick php7.2-imap (then 'y', and 'y' again) **NOTE: you MUST do these, otherwise the script** **fails on each**
 - wget [https://github.com/RestyaPlatform/board/raw/master/restyaboard.sh](https://github.com/RestyaPlatform/board/raw/master/restyaboard.sh) --no-check-certificate

Then

*   In restyaboard.sh, [update PostgreSQL configurations](https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh#L11) as you wanted. For intranet or medium security setup, you may leave it as it is. If you edit, you must remember the details.
*   Execute chmod +x restyaboard.sh
*   Execute restyaboard.sh
    

 - postgresql u/p: **UniquePostgreSQLPassword**
 - is restyaboard already installed? 'n'
 - then 'y', enter
 - add PPA's question -- enter to allow
 - install postgresql? 'y'
 - enter url, like ****restyaboard.whatever.dom****
 - document root: /usr/share/nginx/html/restyaboard
 - smtp? 'Y' -- NOTE: using PHPMailer() relies on the system having some sort of smtp access. This is difficult when most ISPs prevent you from delivery directly, and it's \*not\* easy to setup smtp+auth. Therefore, right now, our restyaboard installation does NOT have email capability, and therefore CANNOT send new user confirmations, password resets, notifications, etc.
 - restyaboard apps? 'Y'
 - setup ssl, and it should be a public instance? 'Y'
 - mkdir /etc/nginx/ssl
 - copy bundle.crt  and STAR_**whatever**_**dom**_privkey.txt from another machine to /etc/nginx/ssl
 - nano -w /etc/nginx/conf.d/restyaboard.conf ...and change the following:

```apacheconf
#ssl_certificate      /etc/letsencrypt/live/******restyaboard.whatever.dom******/fullchain.pem;
#ssl_certificate_key  /etc/letsencrypt/live/******restyaboard.whatever.dom******/privkey.pem;
```

```apacheconf
ssl on;
ssl_certificate /etc/nginx/ssl/bundle.crt;
ssl_certificate_key /etc/nginx/ssl/STAR_****whatever**_**dom****_privkey.txt;
```

 - service nginx restart
 - u/p: admin/restya

**Comment by rrjanbiah** [comment]
*Internal note*

Note on PHPMailer() is wrong and may need to revise

**Comment by sridhar391** [comment]
Added fix in this commit https://github.com/RestyaPlatform/board/commit/b788391bc36ad5be1abdd031068fa211f33e6d57
