### ISSUE TITLE
Hard coded messages on server-side (i18n)

### ISSUE THREAD

**Issue by ikarus--** [RestyaPlatform/board#1880]
Unfortunately, translating the JSON file found in ./client/locales/SELECTED_LANGUAGE/translation.json don't accomplish the user full-experience in their native language because a lot of server-side messages are hard coded, mainly contemplating browser notifications and emails.

## Expected Behavior

Selecting a language through your user configuration (found in the left of the 'bell' button) should fully translate the app.

## Current Behavior

Selecting a language through your user configuration (found in the left of the 'bell' button) don't fully translate the app.

## Screenshots (if appropriate):
![i18n](https://user-images.githubusercontent.com/7583743/41245771-5f134440-6d7f-11e8-9e18-916569779be0.jpg)

## Possible Solution

Create a JSON parse, similar to what is done on client-side, on the files below:
./server/php/libs/core.php
./server/php/shell/card_due_notification.php
./server/php/shell/imap.php
./server/php/shell/instant_email_notification.php
./server/php/shell/periodic_email_notification.php
./server/php/shell/authorize.php

EDIT: ./server/php/R/r.php

This is an example where I made a hard-coded translation for my native language (portuguese). Affected lines can be found searching for 'TRANSLATION' (no quotes).
[server-php-libs-core.zip](https://github.com/RestyaPlatform/board/files/2090992/server-php-libs-core.zip)

## Your Environment

* Version used: v0.6.5

**Comment by rrjanbiah** [comment]
@ikarus-- Thanks a lot for your contribution. We will look into it ASAP

**Comment by ssivachidambaram** [comment]
Duplicate #1261

**Comment by rrjanbiah** [comment]
*Internal note*

Should be very high priority
