### ISSUE TITLE
Hide Card Additional Informations don't hide cards ID

### ISSUE THREAD

**Issue by bseclier** [RestyaPlatform/board#1893]
Hello,
I'm currently running restyaboard 0.6.5 with the last version of the Hide Card Additional Informations plugin, even if I set "Hide card ID" to true in the preferences, I can still see them.
Am I the only one ?

Cheers,

![capture du 2018-06-19 09-34-47](https://user-images.githubusercontent.com/3954149/41583293-3fcb634e-73a4-11e8-951e-8e8c8679f44e.png)

**Comment by sridhar391** [comment]
We didn't face this issue in our demo server and can you please logout and login again to see the changes or please clear the cache and check again?

**Comment by bseclier** [comment]
You're right, I had to "deeply" remove caches, Alt+F5 was not enough.
Thanks for the tip !
