### ISSUE TITLE
_server_domain_url written and read from different places

### ISSUE THREAD

**Issue by boun** [RestyaPlatform/board#1916]
Hi,

in config.inc.php the _server_domain_url is written to 

https://github.com/RestyaPlatform/board/blob/d1c466c81280607c7b2fe2520d631d1bd5b0cc99/server/php/config.inc.php#L28

and read from 
https://github.com/RestyaPlatform/board/blob/d1c466c81280607c7b2fe2520d631d1bd5b0cc99/server/php/shell/card_due_notification.php#L19

obviously these never match, as both APP_PATH != sys_get_temp_dir AND restya_site_url_for_shell.php != site_url_for_shell.php 

This is  why links do not work and pictures are not displayed.

**Comment by rrjanbiah** [comment]
Looks like a regression from #1740

**Comment by sridhar391** [comment]
Duplicate https://github.com/RestyaPlatform/board/issues/1933 and we have fixed this in https://github.com/RestyaPlatform/board/commit/994bda8db49e00d187e35c26834d4407e6f7b10f
