### ISSUE TITLE
E-mail when someone mentiones another member

### ISSUE THREAD

**Issue by dadarko** [RestyaPlatform/board#1919]
I tried fixing Cron jobs, but when someone mentions another member, no e-mail notifications are sent to the member,,,

**Comment by dadarko** [comment]
root@boards:/# ./usr/share/nginx/html/restyaboard/server/php/shell/instant_email_notification.sh
2018-07-10 12:01:01 #################################################
successfully acquired lock: /usr/share/nginx/html/restyaboard/server/php/shell/instant_email_notification_sh.lock
root@boards:/# pgrep cron
1010

root@boards:/# ./usr/share/nginx/html/restyaboard/server/php/shell/instant_email_notification.sh
2018-07-10 12:07:41 #################################################
successfully acquired lock: /usr/share/nginx/html/restyaboard/server/php/shell/instant_email_notification_sh.lock

When running Cron manually, the e-mail comes...

**Comment by dadarko** [comment]
When running cron job manually, it sends and receives the email. The Cron is running as a process:
(pgrep cron returns 1010) but it wont start automatically

**Comment by rrjanbiah** [comment]
@dadarko Please try piping the cron command to a log file and see if there's any path error or permission error

**Comment by rrjanbiah** [comment]
@dadarko 

In case, if it helps, something like:

`*/1 * * * * /path/blah_blah.sh >> /path/blah_blah.log 2>&1`
