### ISSUE TITLE
E-mails spamming - Add option for unsubsrcibe members from board

### ISSUE THREAD

**Issue by dadarko** [RestyaPlatform/board#1965]
After creating members and importing board, the default subscription option doesn't work -  there is no way to unsubscribe people from boards from admin panel

**Comment by dadarko** [comment]
edit: also if i Unsubscribe from a board, I am still getting emails for every comment that happens

**Comment by sridhar391** [comment]
There will be setting for auto subscription to the board and you can disable it. So user will not auto subscribe on board while adding in board.

If you want to remove old members from subscription then you have to do it manually in database.
