### ISSUE TITLE
When editing a comment, Edit, save and delete buttons disappear

### ISSUE THREAD

**Issue by dadarko** [RestyaPlatform/board#1966]
Sometimes, when editing a comment, Edit, save and delete buttons disappear.

**Comment by sridhar391** [comment]
Can you please tell us the version of Restyaboard you are using, you can find the Restyaboard version by clicking the `About Restyaboard` option in the `user icon dropdown menu` in the `footer`

**Comment by dadarko** [comment]
0.6.5
