### ISSUE TITLE
When deleting an attachment, it takes a very long time

### ISSUE THREAD

**Issue by dadarko** [RestyaPlatform/board#1967]
Sometimes, when deleting an attachment, it takes a very long time

**Comment by sridhar391** [comment]
We are not able to reproduce the issue on our local and live server, Can you please provide us more information by screenshot or video

**Comment by sridhar391** [comment]
Can you please provide us the steps for reproducing the issue by video or screenshots

**Comment by sridhar391** [comment]
The fix is available on the dev branch and it will be available on the upcoming release version
