### ISSUE TITLE
LDAP setting password encryption is breaking when updating other values

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1994]
## Current Behavior

After entering LDAP password, it is showing in encrypted form. Now, updating other values, breaking the LDAP login. Also, error message is not correct.

## Possible Solution

Don't display password once it is set; but give a hint that it is already set. Since the error message is completely confusing, perhaps add a test button for testing LDAP configuration

**Comment by sridhar391** [comment]
Duplicate https://github.com/RestyaPlatform/board/issues/1927 and we have fixed in this commit https://github.com/RestyaPlatform/board/commit/1d5703af4cd0b6e9ed17efceca9ea01e2ca0b955
