### ISSUE TITLE
Issues list from IBM

### ISSUE THREAD

**Issue by satheeshm70** [RestyaPlatform/board#2]
Some of us tried Restya baord here and liked it. Some issues and questions

1. When we enable LDAP only username is getting displayed. Like trello, it should display name
2. How to add music to card as in your demo?
3. How can we import a single board from trello?
4. Why is that some options have archive and others have delete? It seems to be similar to trello. But, is there any specific reason for that?
5. Closing board sometimes freezes browser
6. Moving a card to another board resets number of comments indicator
7. When will you release chat?
8. How can we export cards?
9. How can we use both LDAP and normal register option?

**Comment by rrjanbiah** [comment]
Thanks for you bug report.

Regarding your questions:

> How to add music to card as in your demo?

In the board page, under cog icon, you can find "Change Background" and then "Productivity Beats". You'll have to use abc notation.

> How can we import a single board from trello?

This is mentioned here http://restya.com/board/install.html#import-trello Please let us know if that is not clear

> Why is that some options have archive and others have delete? It seems to be similar to trello. But, is there any specific reason for that?

We'll see what we can do here. Thanks for your points. 

> When will you release chat?

Approx mid of August.

> How can we export cards?

Currently we don't have this feature. If you can tell us usecase that will help us to plan.

> How can we use both LDAP and normal register option?

Currently, enabling LDAP will disable register option. In next release, we'll add one more additional setting for that.

**Comment by satheeshm70** [comment]
thank you!

**Comment by satheeshm70** [comment]
Any news about chat?

**Comment by rrjanbiah** [comment]
@satheeshm70 Sorry we had to postpone it to another 15 days due to current progress in apps and other minor enhancements.

**Comment by rrjanbiah** [comment]
> When we enable LDAP only username is getting displayed. Like trello, it should display name

Fixed. Now it displays name in all places.

> Moving a card to another board resets number of comments indicator

Fixed. Now the correct comment count will display.

> Closing board sometimes freezes browser

Fixed.

**Comment by lmarikannan** [comment]
Closing this for now. If you get any issues, please feel free to reopen.
