### ISSUE TITLE
Error installing 

### ISSUE THREAD

**Issue by ammo8600** [RestyaPlatform/board#2020]
estyaboard.sh: line 146: `upgrade-0.3-0.4': not a valid identifier

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sridhar391** [comment]
Can you please tell us if you are trying to update Restyaboard or install Restyaboard

If you are trying to install Restyaboard, 
please type 'n'  for 'Is Restyaboard already installed and configured/working y/n?'

Please download the latest version of shell script file from https://github.com/RestyaPlatform/board/blob/dev/restyaboard.sh

**Comment by ammo8600** [comment]
this is a fresh install

**Comment by ammo8600** [comment]
Still the same.

[root@kanban ~]# sh restyaboard.sh
+ whoami
root
++ cat /etc/issue
+ echo '\S' Kernel '\r' on an '\m'
\S Kernel \r on an \m
++ lsb_release -i -s
+ OS_REQUIREMENT=CentOS
+ '[' CentOS = '' ']'
++ cut -f1 -d.
++ lsb_release -rs
+ OS_VERSION=7
+ '[' CentOS = Ubuntu ']'
+ '[' CentOS = Debian ']'
+ '[' CentOS = Raspbian ']'
+ yum install -y curl unzip
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.ges.net.pk
 * extras: mirrors.ges.net.pk
 * updates: mirrors.ges.net.pk
Package curl-7.29.0-46.el7.x86_64 already installed and latest version
Package unzip-6.0-19.el7.x86_64 already installed and latest version
Nothing to do
++ curl --silent https://api.github.com/repos/RestyaPlatform/board/releases
++ grep tag_name -m 1
++ awk '{print $2}'
++ sed -e 's/[^v0-9.]//g'
+ RESTYABOARD_VERSION=v0.6.5
+ POSTGRES_DBHOST=localhost
+ POSTGRES_DBNAME=restyaboard
+ POSTGRES_DBUSER=restya
+ POSTGRES_DBPASS='hjVl2!rGd'
+ POSTGRES_DBPORT=5432
+ DOWNLOAD_DIR=/opt/restyaboard
restyaboard.sh: line 146: `upgrade-0.3-0.4': not a valid identifier

**Comment by sridhar391** [comment]
We need a screen share session to analyze this problem. Can you please send mail to info@restya.com and we will provide zoom meeting URL

**Comment by sridhar391** [comment]
Closing the issue due to inactivity
