### ISSUE TITLE
When opening our restyaboard server strange things are going on

### ISSUE THREAD

**Issue by nickbe** [RestyaPlatform/board#2022]
The following sites seem to be access via restyaboard:

![grafik](https://user-images.githubusercontent.com/10890765/44311494-de2c8580-a3e8-11e8-8958-256365a00e46.png)

The Server is exclusive - the browser sandboxed and fresh. Access to russian sites? I beg your pardon?
Would someone be so kind and explain what's going on here?

**Comment by rrjanbiah** [comment]
@nickbe Can you please share more details? If possible, please connect to Skype handle `live:info_713225`

Trying to understand where did you find these links (in source code or UI)

**Comment by rrjanbiah** [comment]
@nickbe Also, what is your OS, Browser and respective versions? How did you install Restyaboard?

**Comment by nickbe** [comment]
Restyaboard was installed manually on a fresh Unbuntu 16.04
Restyaboard Version is v0.6.5.(2018-05-28)

Browsers are Firefox (latest) and Chrome (latest).
On Chrome "ScriptSafe" reports this:

![image](https://user-images.githubusercontent.com/10890765/44354886-5491bc00-a4ab-11e8-9117-a9d3154adc44.png)

**Comment by nickbe** [comment]
Ok I think we solved the problem. Seems to be a browser extension, but the messages were very strange because they looked like it was coming from the board domain.
