### ISSUE TITLE
What does the card member feature even do?

### ISSUE THREAD

**Issue by nickbe** [RestyaPlatform/board#2023]
I add a user to a card, but when he logs in he sees the whole board.
That doesn't make any sense at all.

Actually he should see only cards he was assigned to. (At least if he's only a worker)

**Comment by sridhar391** [comment]
@nickbe Thank your for the suggestion. Currently we have implemented like Trello. We need to internally discuss to take it forward.

**Comment by rrjanbiah** [comment]
Currently getting handled in #2760 and so closing this now.
