### ISSUE TITLE
Need a role option to see not assigned cards

### ISSUE THREAD

**Issue by nickbe** [RestyaPlatform/board#2024]
In my opinion the worker should be able to change the position of a card and modify certain data within a card, but he should not be able to move/edit a column or create a new one.

**Comment by sridhar391** [comment]
@nickbe You can handle it using Roles from admin side. Can you please refer the screenshot?

![roles_list](https://user-images.githubusercontent.com/17172525/44380015-75e3be00-a526-11e8-9b88-227208abca8e.png)

**Comment by sridhar391** [comment]
@nickbe Yes. We can handle it using roles.

**Comment by nickbe** [comment]
Is there already an option for this in the roles?

**Comment by nickbe** [comment]
I just took a quick glance at the sourcecode. I think this should be fairly simple to implement.

**Comment by nickbe** [comment]
Would you be so kind and consider to add this option to the roles?

**Comment by ssivachidambaram** [comment]
Duplicate #2023
