### ISSUE TITLE
How to change the main color?

### ISSUE THREAD

**Issue by zhonghanwen** [RestyaPlatform/board#2036]
How to change the main color?

**Comment by sridhar391** [comment]
You can change the main color by changing the color codes in the default.cache.css 
or 
you can change it in the source file by downloading main source and change the color changing the color codes in the less files and build the source by using command from the below link
https://github.com/RestyaPlatform/board#build

**Comment by nickbe** [comment]
Is the complete build process necessary or can we just convert the css file and replace them single file?

**Comment by rrjanbiah** [comment]
> Is the complete build process necessary or can we just convert the css file and replace them single file?

If you build from `LESS` files, it will be relatively easy to change primary, secondary colors, etc. You can also replace in built / single file.
