### ISSUE TITLE
SMTP Settings simply do not work, and no instructions on how to use 2FA

### ISSUE THREAD

**Issue by rwatts3** [RestyaPlatform/board#2056]
Greetings, 

I followed the instructions on setting up docker. 
I have not been successful in registering a new account,
and the default account admin/restya always asks for a 6 digit code, with no idea of where to get that 6 digit code. 

What am I missing here ?

**Comment by rwatts3** [comment]
What is the 6 digit code. 
I keep getting this on a brand new install and there is nothing in the UI that remotely tells me how to gain access to it ?

**Comment by rwatts3** [comment]
Ok I was able to solve this finally. 

A huge step missing in the docker instructions. 
With the current built images, you have to run the sql upgrade script at the latest version.

https://github.com/RestyaPlatform/board/blob/dev/sql/upgrade-0.6.5-0.6.6.sql

Basically the database setup in docker is out of sync with what's expected in the code.

**Comment by ssivachidambaram** [comment]
@rwatts3 Thank for the information and we've updated in docker description.

Regarding SMTP issue, let us know the proper error you are getting?

**Comment by nickian** [comment]
"Run the SQL upgrade script"? How do you do this? There are no instructions for this.

**Comment by m-paniez9292** [comment]
Hi,
Thanks to rwatts3 for this issue because I have the same and I do the same process (sql upgrade) and it works.
Like him, I don't know at this moment if email sending works (it will be great in admin part, to have a SMTP tab to configure that). 
Thanks

**Comment by m-paniez9292** [comment]
> "Run the SQL upgrade script"? How do you do this? There are no instructions for this.

Hi,
You go to your postgres container and copy-paste sql instructions.

**Comment by nickian** [comment]
That's not so straightforward. So...

`docker exec -it postgres_1 bash`

Then what? Is there a shared volume from which I can import the SQL file? I'm used to MySQL, so Postgres is quite confusing.

Just saying, I think you'd have much more market adoption if this were easier to install or the instructions were clearer.

**Comment by ssivachidambaram** [comment]
@nickian 

Sorry for the confusion. We're working on to provide easier installation steps.

Can you please run the below command to download the SQL?

`wget https://raw.githubusercontent.com/RestyaPlatform/board/dev/sql/upgrade-0.6.5-0.6.6.sql`

To import SQL please run the below command,

`psql -h postgres -d restyaboard -U admin -W < "upgrade-0.6.5-0.6.6.sql"`

Password is `admin`.

Let us know your feedback.

**Comment by nickian** [comment]
@ssivachidambaram that worked. Thank you!

**Comment by ssivachidambaram** [comment]
@nickian Thank you very much for confirmation. We'll add these command in docker description.
