### ISSUE TITLE
In board page, display only assigned cards using roles to the logged in member

### ISSUE THREAD

**Issue by ssivachidambaram** [RestyaPlatform/board#2057]
From Client,

We are interested in Restyaboard. Is it possible to share certain cards and their status (= on which list they currently are) with a customer? So someone who is not in our team? We do not want to give access to our whole board for our customers, but only to the cards which are about them. So that they can see the status of their card.

**Comment by sridhar391** [comment]
The assigned cards for the users can be viewed by goto the profile page and click on the cards tab and the assigned cards for the user and the cards created by the user will be shown and it will be available in the upcoming version
