### ISSUE TITLE
User update error in nginx

### ISSUE THREAD

**Issue by Zimeon-** [RestyaPlatform/board#206]
When a user tries to update his profile or an admin then nginx shows the following error.

2016/02/08 12:26:11 [error] 10582#0: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  array_push() expects parameter 1 to be array, string given in /usr/share/nginx/html/server/php/R/r.php on line 1227
PHP message: PHP Notice:  Undefined variable: sfields in /usr/share/nginx/html/server/php/R/r.php on line 1231
PHP message: PHP Warning:  array_push() expects parameter 1 to be array, string given in /usr/share/nginx/html/server/php/R/r.php on line 1227
PHP message: PHP Warning:  array_push() expects parameter 1 to be array, string given in /usr/share/nginx/html/server/php/R/r.php on line 1227
PHP message: PHP Warning:  array_push() expects parameter 1 to be array, string given in /usr/share/nginx/html/server/php/R/r.php on line 1227" while reading response header from upstream, client: 192.168.120.55, server: infra.dc.local, request: "POST /api/v1/users/3.json?token=123456789c44dfda369deef78751d2e99abd92bc HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/restyaboard.socket:", host: "nn.yy", referrer: "http://nn.yy/"

**Comment by rrjanbiah** [comment]
@Zimeon- Thanks for your report. We'll fix it soon.

**Comment by ssivachidambaram** [comment]
Fixed.
