### ISSUE TITLE
Howto change Organisation for a board

### ISSUE THREAD

**Issue by nickbe** [RestyaPlatform/board#2061]
Just that.
How can I move a board into another organisation?

**Comment by sridhar391** [comment]
For moving the board to the organization, please click the Change visibilty option in the Board Header next to the members list and select the organization option in the Changer visibility dropdown menu and you can select the organiztion and click save for moving the board to the organization. 

Please refer the below image for moving the board to the organization,


![orga](https://user-images.githubusercontent.com/17172525/45665151-21cff780-bb2d-11e8-8223-a8071d627c7b.png)

**Comment by nickbe** [comment]
Thanks a lot. I've been looking for this for ages now.
