### ISSUE TITLE
Show tab labels in cards

### ISSUE THREAD

**Issue by nickbe** [RestyaPlatform/board#2064]
It would be nice to (at least optionally) show the tag labels together instead of the little icons in the table view. Is there an option for this?

**Comment by sridhar391** [comment]
Please install Label Style Plugin from https://github.com/ik9999/r_labelstyle and install in your Restyaboard to see the tag Labels together in the table view

**Comment by nickbe** [comment]
Very nice. Thanks a lot. I defintetly overlooked this one :)
