### ISSUE TITLE
Wiki plugin

### ISSUE THREAD

**Issue by ssivachidambaram** [RestyaPlatform/board#2135]
Need a simple wiki feature to create some content pages.

The Pages are visible to every logged in user. In case its easy to integrate it into the restya permission system (admin settings) then do that too. Otherwise just visible for all logged in users.

Need the possibility to create content pages with html content using a wysiwyg editor, give
them a title and select a parent wiki page for them.

A tree view should be available on the left (not inside the menu, as additional column) which
shows the wiki pages in their hierarchical order.

![1](https://user-images.githubusercontent.com/91407/46662342-ce574380-cbd8-11e8-9354-2c5a472f2bd0.png)

Here an example of what I’m looking for.

The tree view has not to be expand and collapsible. It can just be static.

**Comment by sridhar391** [comment]
Created the wiki plugin, the admin can able to add the wiki in the app setting page and the users can view the added wiki on the wiki page
