### ISSUE TITLE
Markdown rendering not consistent in sub levels

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#2137]
From @itzmeank 

 it does not properly render like 2nd or 3rd level of lists and also it does not render tables

**Comment by sridhar391** [comment]
The sublist rendering can be achieved by giving the four space before the list content
<pre> 
- foo
   - bar
        - baz
            - qux
</pre>

**Comment by baskar383** [comment]
this issue explained by @sridhar391 in the above comment . Hence closing the issue
