### ISSUE TITLE
restyaboard installation issue

### ISSUE THREAD

**Issue by mdmle** [RestyaPlatform/board#2146]
Having installed restyboard on debian with the install script, i've had to solve 2 small issues in restyaboard.sh :

1) Version check for postgresql fails when postgresql > 10 is used
line 969: if [[ $PSQL_VERSION < 9.3 ]]
returns true for PSQL_VERSION 10.5

Should use -lt instead

2) PostgreSQL version detemination

in my case, 
`psql  --version `
returns 
`psql (PostgreSQL) 10.5 (Debian 10.5-1)`

Thus, on line 528 (and 3 other places), 
`PSQL_VERSION=$(psql --version | egrep -o '[0-9]{1,}\.[0-9]{1,}')`
returns : 
```
10.5
10.5
```

I've piped with `| head -1` as a quick workaround, but that could be corrected. 

Anyway, the script is really useful and well done. Thanks for the work !

**Comment by ssivachidambaram** [comment]
@mdmle Thanks for your kind words and contribution. We've also fixed this in our development branch https://github.com/RestyaPlatform/board/blob/dev/restyaboard.sh#L523.
