### ISSUE TITLE
Need notification highlight for username mentions

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#218]
From https://groups.google.com/d/msg/restya/lVBaFPBQpGU/fG83mKnaAAAJ by Antti Hurme

- Notification highlight when users username is mentioned in card. For example when user is added as a meber to a card, it could be highlighted in the notification bar and email sent?

- While on notification highlighting. Perhaps add a divider between new notifications and old ones or highlight unread notifications somehow? Would make it easier to see new changes.

**Comment by ssivachidambaram** [comment]
Fixed.
