### ISSUE TITLE
Add new role to board with same permissions against owner, but add and edit labels not working

### ISSUE THREAD

**Issue by jacky9003** [RestyaPlatform/board#2184]
I add a new role to the board in Role page, and I tick all permissions, however the user with this role can't add and edit labels in cards. Once I add or edit labels then hit "Save" button, the board went blank and nothing happen.

**Comment by sridhar391** [comment]
Please execute the following sql command in your Restyaboard database for showing the roles for Add labels in the card and Edit labels .
```
UPDATE "acl_board_links" SET "is_hide" = '0' WHERE "slug" = 'add_labels';
UPDATE "acl_board_links" SET "is_hide" = '0' WHERE "slug" = 'edit_labels';
```
After executing the above sql commands, in the Board Role page, you can see the option for add and edit labels and tick the option for the new role and the user will be able to add and edit label.

**Comment by sridhar391** [comment]
Thanks for your confirmation, we are closing the issue.
