### ISSUE TITLE
How to back up all data? (including boards, users, groups, etc.) And restore?

### ISSUE THREAD

**Issue by jacky9003** [RestyaPlatform/board#2192]
I search on google this question but there are a few answers there, one is: ["milosz/restyaboard-backup"](https://github.com/milosz/restyaboard-backup) on github. The other is: ["How to backup and restore Restyaboard boards"](https://blog.sleeplessbeastie.eu/2018/04/02/how-to-backup-and-restore-restyaboard-boards/)

Apart from those, I couldn't find any thing useful. 

Is there an offical way of backing up and restoring data? If yes, could you guys plz show me the right direction of it?

Thank you!

**Comment by sridhar391** [comment]
Please refer https://github.com/RestyaPlatform/board/wiki/Backup-and-Restore for how to backup and restore all data.

**Comment by jacky9003** [comment]
Thanks! @sridhar391

**Comment by sridhar391** [comment]
Added the steps for backing up restoring the particular tables in the Restyaboard database and the document will be updated in the upcoming release
