### ISSUE TITLE
Mobile view no way to go back to boards

### ISSUE THREAD

**Issue by ongkhua** [RestyaPlatform/board#2193]
If you open restyaboard using mobile device, and "use add to home screen", the next time you open via that icon your session may still be active and not required to login again.

Problem is if your last view is inside a board, there is no way to go back to view all boards, as pressing the back button will take you back to Android home screen instead.

Suggestion:
Add a button to go to home screen, like the board icon in desktop view in lower left corner.  This button can be added in the "hamburger" icon in the upper left corner to save space.

Environment:
Android 8.1
Chrome 70

**Comment by sridhar391** [comment]
We have shown the Restyaboard icon at the bottom of the board page for going to the boards page
![board](https://user-images.githubusercontent.com/17172525/51423322-64413800-1be4-11e9-9f8b-7acc68a60a4f.png)
