### ISSUE TITLE
Size of the list scroll bar is too thin and have to increase the size of the scroll bar

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#2202]
## Expected Behavior
Size of the list scroll bar should be comfortable to be used

## Current Behavior
Size of the list scroll bar is too thin and have to increase the size of the scroll bar

## Screenshots:
![11](https://user-images.githubusercontent.com/17172525/48117398-16788d00-e28f-11e8-8bbd-99bbd4b91ffb.png)

**Comment by rrjanbiah** [comment]
Changes made UI unappealing. So, have to revert and close
