### ISSUE TITLE
Misalignment in the email notification for due date

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#2203]
## Expected Behavior
There should not be any Misalignment in the email notification for due date

## Current Behavior
Misalignment in the email notification for due date

**Comment by baskar383** [comment]
Card Due Date email notification alignment style are corrected. Kindly Refer below screenshot
![due_date_fix](https://user-images.githubusercontent.com/17172610/51686082-aec41980-2015-11e9-8da4-f8617f10c9e2.png)
