### ISSUE TITLE
After update to 0.6.6 can't login

### ISSUE THREAD

**Issue by dadarko** [RestyaPlatform/board#2211]
After updating the system via script, i can not log in at all. The system is asking me for 2FA which I am  not using.

**Comment by sridhar391** [comment]
It seems that while upgrading the Restyaboard, the SQL file `upgrade-0.6.5-0.6.6.sql` didn't execute and have to be manually run by executing the following command:
`psql -h localhost -d restyaboard -U restya -W < "/usr/share/nginx/html/restyaboard/sql/upgrade-0.6.5-0.6.6.sql"`

**Comment by dadarko** [comment]
Yes, solved it that way allready. Thanks anyways!
