### ISSUE TITLE
Opening PDF and mp4 inside browser

### ISSUE THREAD

**Issue by dadarko** [RestyaPlatform/board#2213]
After the update to 0.6.6., the embeded file preview is now working. However, I can not open PDF or mp4. The browser only says Nginx bla bla not found. THe only way I can see theese attachments is by downloading them to the PC like before.

**Comment by sridhar391** [comment]
You have to add the extensions pdf, mp4 in the `line 41` of the `restyaboard.conf` file in the `/etc/nginx/conf.d` path like https://github.com/RestyaPlatform/board/blob/dev/restyaboard.conf#L41

**Comment by dadarko** [comment]
yes, this solved it. Thanks!
