### ISSUE TITLE
No Response on Free Apps Request after Marketing for you. 

### ISSUE THREAD

**Issue by rwatts3** [RestyaPlatform/board#2214]
I requested several months ago for permission to use the apps and per the docs it says you will be contacted nothing 48 hours. 

I made posts ti my social media , sent links out, as well as made posts on Twitter and my personal website to promote restyaboard. 

I have also contributed an issue that solved a major head scratcher for new users.  

Can you please let me know the status of my request to receieve free apps paid apps.  

Thanks 

Ryan.

**Comment by rrjanbiah** [comment]
@rwatts3 We're internally checking this and will update you in a day or two.

**Comment by rwatts3** [comment]
Thank you

**Comment by rwatts3** [comment]
Hmm, I see that you closed this , but I still have not received an email or a code for the apps?
