### ISSUE TITLE
Unable to install restyaboard on Linux Mint?

### ISSUE THREAD

**Issue by Carrot-C** [RestyaPlatform/board#2215]
Okay I'm not experienced here or with the material at large, so I hope I only did something stupid and someone can help me along. :)

I tried to run the self-hosted version for Linux, but get stuck at 'Execute restyaboard.sh'.  install.log only returns "This script must be run as root". But I can't seem to run it as root, because I still get this when running it as root. 
I followed instructions from https://restya.com/board/install#Installscript

It seems such a cool application so I hope someone can help me soon and I can go on being amazed. :)

**Comment by sridhar391** [comment]
We need screen share meeting to understand the problem, please send us the mail at info@restya.com about your available time for arranging the meeting.

**Comment by baskar383** [comment]
Above issue are fixed and changes are committed(https://github.com/RestyaPlatform/board/commit/ffa772e1875b5e8205b25dc1e223ea05f85f1b16) in the related issue #1800
