### ISSUE TITLE
Need a button to delete all archived items

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#222]
From https://groups.google.com/d/msg/restya/lVBaFPBQpGU/fG83mKnaAAAJ by Antti Hurme

- Add a button to delete All archived items.

http://imgur.com/1HcYYqg

For example at the top of the archived items list and/or bottom. Preferbly with a confirmation diablog to prevent misclicks. 

(Self note: Admin only feature??)

**Comment by ssivachidambaram** [comment]
Done.
