### ISSUE TITLE
Problems with installation with psql 11.1

### ISSUE THREAD

**Issue by al3xst** [RestyaPlatform/board#2224]
The first condition is true for me, with psql 11.1
see: https://github.com/RestyaPlatform/board/blob/dev/restyaboard.sh#L530

Bash doesn't support simple floating point comparison.
(Have a look at https://stackoverflow.com/questions/4023830/how-to-compare-two-strings-in-dot-separated-version-format-in-bash)

And for psql 11.1 my directory is simply `11`  and not `11.1`
see: https://github.com/RestyaPlatform/board/blob/dev/restyaboard.sh#L560
and https://github.com/RestyaPlatform/board/blob/dev/restyaboard.sh#L561

**Comment by sridhar391** [comment]
@al3xst Thanks for your suggestions, we will check it and update you soon
