### ISSUE TITLE
Username validation is now case sensitive (it shouldn't be)

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#2226]
High priority issue that username is now case sensitive and it shouldn't be

**Comment by sridhar391** [comment]
we have only handled the email in the case sensitive and the
username is handled in case-insensitive only and we have tried in our
local server with LDAP username as 'Testldap' and the user can able to
log in without creating another user.

**Comment by itzmeank** [comment]
But why would email be case sensitive it should be case-insensitive too....

**Comment by sridhar391** [comment]
Some clients have faced issues while handling email in case-insensitive method and please refer the issue https://github.com/RestyaPlatform/board/issues/1544 for more details

**Comment by itzmeank** [comment]
I think there is a misunderstanding of the issue explained in https://github.com/RestyaPlatform/board/issues/1544 it clearly says that email id can be case-insensitive, that is if I try to login as foo@bar.com and or Foo@Bar.com and or foo@BAR.com either case should work which means it should be case-insensitive please fix it...

**Comment by itzmeank** [comment]
Except for password nothing else should be case sensitive

**Comment by rrjanbiah** [comment]
Also, case sensitivity should NOT be handled by `strtolower` or so. It has to be handled in database.

In MySQL, all fields except `binary` type are case **insensitive**.

In PostgreSQL, all fields except `citext` are case **sensitive** (note the difference)

**Comment by sridhar391** [comment]
The clients have asked the option for handling email in case sensitive. so, that only we have added the changes  and we are now adding the feature for handling email in case in-sensitive

**Comment by rrjanbiah** [comment]
Looks like there's an logical issue with this approach. May work when client used lower case email address during signup. May have to test it for other case and or have to address it in V2
