### ISSUE TITLE
Installation issue (Manual setup)

### ISSUE THREAD

**Issue by stanleyliu1006** [RestyaPlatform/board#224]
Hi,

we are trying to install the Restya on the windows platform, but it shows me a blank page of login page. The Nginx error log shows error below: and the /client/js/templates/templates.js and /client/css/bootstrap.css cannot be found either. Could you please advise what the solution to solve this or did I misss some steps.

 *6 CreateFile() "C:\Nginx/html/api/v1/oauth.json" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /api/v1/oauth.json?_=1455062056457 HTTP/1.1", host: "localhost:8084", referrer: "http://localhost:8084/restyboard/client/index.html"

Thanks
Stanley

**Comment by stanleyliu1006** [comment]
Hi ssivachidambaram 

I also investigate the issue further, when I fake up the oauth.json and settins.json and users/login.json, the login form is showing up, but cannot log-in. Is this because I am using the windows platform, which will not auto generate the api/v1/json files compare with Linux. FYI, i am using the source code version, and run the grunt to build the css and js.

So could you please advise where can i get the  oauth.json and settins.json etc?

Regards
Stanley

**Comment by ssivachidambaram** [comment]
> So could you please advise where can i get the oauth.json and settins.json etc?

These are all API calls and you can find the PHP code in server/php/R/r.php file.

settings.json - https://github.com/RestyaPlatform/board/blob/master/server/php/R/r.php#L319
oauth.json - https://github.com/RestyaPlatform/board/blob/master/server/php/R/r.php#L3879

**Comment by stanleyliu1006** [comment]
Thanks ssivachidambaram, so is there any way I can install them on the windows? so if the Restya can install on the windows or linux only?

**Comment by ssivachidambaram** [comment]
You can install it in windows also.

For Apache:
https://github.com/RestyaPlatform/board/blob/master/.htaccess#L7
Change `RewriteBase` /` to `RewriteBase /your_local_folder/`

For nginx:
https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf - Change `root` directory in nginx configuration
Also,
https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf#L21 - Add your local folder name in rewrite rules

**Comment by stanleyliu1006** [comment]
Hi ssivachidambaram

Thanks so much. Follow your instruction, the login page still cannot show up. Can you please help me to confirm the question below, so I can understand more about mine issue:

1. the config file restyaboard.conf is located at the root folder rather than the board/restyaboard.conf, is that ok?

2. The code below is our restyaboard config file, we are using php5.6, do we still need to install php-fpm in windows?

3. We are using Nginx, root folder is C:\Nginx\html and project folder is C:\Nginx\html\restyboard, can you please kindly let me know if there's any wrong with config file, the Nginx is runing on the port 8084

4. Is just download the V0.16 source code, and push it to the Nginx\html folder, and run the grunt to build the files, and I also configure the postgredatabase. Is there any steps i am missing or I am using the wrong source code etc? 


server {
	listen 8084 default_server;
	server_name _;

	root C:\Nginx\html;
	index  index.html index.php;

	gzip on;
	gzip_disable "msie6";

	gzip_comp_level 6;
	# gzip_comp_level 9;
	gzip_min_length  1100;
	gzip_buffers 16 8k;
	gzip_proxied any;
	# gzip_http_version 1.1;
	gzip_types       text/plain application/xml text/css text/js text/xml application/x-javascript text/javascript application/json application/xml+rss;

	client_max_body_size 300M;

	rewrite ^/download/([0-9]*)/([a-zA-Z0-9_\.]*)$ /server/php/R/download.php?id=$1&hash=$2 last;
	rewrite ^/ical/([0-9]*)/([a-z0-9]*).ics$ /server/php/R/ical.php?id=$1&hash=$2 last;
	rewrite ^/api/(.*)$ /server/php/R/r.php?_url=$1&$args last;
		
	location / {
		root C:\Nginx\html\restyboard;
	}

	location ~ \.php$ {
		try_files $uri =404;
		include fastcgi_params;
		fastcgi_pass	unix:/var/run/php5-fpm.sock;
		fastcgi_index   index.php;
		fastcgi_param	SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PHP_VALUE "upload_max_filesize = 300M \n post_max_size=301M";
	}

	location ~* \.(css|js|less|html|ttf|woff|jpg|jpeg|gif|png|bmp|ico) {
		root /usr/share/nginx/html/client;
		if (-f $request_filename) {
			break;
		}
		rewrite ^/img/([a-zA-Z_]*)/([a-zA-Z_]*)/([a-zA-Z0-9_\.]*)$ /server/php/R/image.php?size=$1&model=$2&filename=$3 last;
		add_header        Cache-Control public;
		add_header        Cache-Control must-revalidate;
		expires           7d;
	}
}

**Comment by rrjanbiah** [comment]
@stanleyliu1006 Just a quick thing...

From http://nginx.org/en/docs/windows.html

> nginx/Windows uses the directory where it has been run as the prefix for relative paths in the configuration. In the example above, the prefix is C:\nginx-1.9.11\. Paths in a configuration file must be specified in UNIX-style using forward slashes:
> 
> > access_log   logs/site.log;
> > root         C:/web/html;

**Comment by ssivachidambaram** [comment]
> the config file restyaboard.conf is located at the root folder rather than the board/restyaboard.conf, is that ok?

Yes. Its correct.

> The code below is our restyaboard config file, we are using php5.6, do we still need to install php-fpm in windows?
> We are using Nginx, root folder is C:\Nginx\html and project folder is C:\Nginx\html\restyboard, can you please kindly let me know if there's any wrong with config file, the Nginx is runing on the port 8084

Can you please try the below configuration,

`server {
	listen 8084 default_server;
	server_name _;

	root C:/Nginx/html/restyboard;
	index  index.html index.php;

	gzip on;
	gzip_disable "msie6";

	gzip_comp_level 6;
	# gzip_comp_level 9;
	gzip_min_length  1100;
	gzip_buffers 16 8k;
	gzip_proxied any;
	# gzip_http_version 1.1;
	gzip_types       text/plain application/xml text/css text/js text/xml application/x-javascript text/javascript application/json application/xml+rss;

	client_max_body_size 300M;

	rewrite ^/download/([0-9]*)/([a-zA-Z0-9_\.]*)$ /server/php/R/download.php?id=$1&hash=$2 last;
	rewrite ^/ical/([0-9]*)/([a-z0-9]*).ics$ /server/php/R/ical.php?id=$1&hash=$2 last;
	rewrite ^/api/(.*)$ /server/php/R/r.php?_url=$1&$args last;

	location / {
	    root C:/Nginx/html/restyboard/client;
	}

	location ~ \.php$ {
	    try_files $uri =404;
	    include fastcgi_params;
	    fastcgi_pass    127.0.0.1:9000;
	    fastcgi_index   index.php;
	    fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
	    fastcgi_param PHP_VALUE "upload_max_filesize = 300M \n post_max_size=301M";
	}

	location ~* \.(css|js|less|html|ttf|woff|jpg|jpeg|gif|png|bmp|ico) {
	    root C:/Nginx/html/restyboard/client;
	    if (-f $request_filename) {
		break;
	    }
	    rewrite ^/img/([a-zA-Z_]*)/([a-zA-Z_]*)/([a-zA-Z0-9_\.]*)$ /server/php/R/image.php?size=$1&model=$2&filename=$3 last;
	    add_header        Cache-Control public;
	    add_header        Cache-Control must-revalidate;
	    expires           7d;
	}
}`

**Comment by rrjanbiah** [comment]
@stanleyliu1006 Were you able to get it installed?

**Comment by stanleyliu1006** [comment]
Thanks your guys reply, I will test it this morning and see how it going

**Comment by stanleyliu1006** [comment]
Hi Guys

It still shows the error message as below after using the config file as above, even if I cleared up the restyboard.config file, it still shows the error below. So i am doubting if there's something wrong with my installation process.

2016/02/11 09:23:39 [error] 7868#6944: *3 CreateFile() "C:\Nginx/html/api/v1/oauth.json" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /api/v1/oauth.json?_=1455143019052 HTTP/1.1", host: "localhost:8084", referrer: "http://localhost:8084/restyboard/client/index.html"


The steps I am doing are:

1. Copy the source file in the html folder
2. Run the npm install (it shows the error npm-cli.js install error, if you are behind a proxy, please make sure that the proxy config is set properly, not sure if  this is the issue)
3. Run the grunt less and grunt js (done without errors)
4. Access to http://localhost:8084/restyboard/client/index.html#/users/login
5. Blank page with the error above.

Any advise would be appreciate.

Thanks
Stanley

**Comment by stanleyliu1006** [comment]
The full error mesage of npm install is as below:

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "express-generator"
npm ERR! node v4.3
npm ERR! npm v2.14.12
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=getaddrinfo ENOTFOUND port port:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly. See: 'npm help config'

**Comment by stanleyliu1006** [comment]
The error above is fixed now, after install a different version of node.js. But the error 

 " CreateFile() "C:\Nginx/html/api/v1/oauth.json" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /api/v1/oauth.json?_=1455143019052 HTTP/1.1", host: "localhost:8084" 

still shows up in the Nginx log file when accessing the login page.

**Comment by stanleyliu1006** [comment]
I am wondering how can we configure Nginx with restyaboard.conf?

**Comment by stanleyliu1006** [comment]
For further reference

1. Nginx html folder  
![image](https://cloud.githubusercontent.com/assets/6980917/12970552/4d76a0a4-d0e4-11e5-94bc-987c432ed188.png)

2. Restyaboard.conf
![image](https://cloud.githubusercontent.com/assets/6980917/12970564/6d6040aa-d0e4-11e5-91c2-ec0a3f031198.png)

3. Blank page
![image](https://cloud.githubusercontent.com/assets/6980917/12970574/877c7b02-d0e4-11e5-96c6-d5114f8f64af.png)

4. Nginx error log
![image](https://cloud.githubusercontent.com/assets/6980917/12970582/9c49530c-d0e4-11e5-813f-92562cf2e627.png)

Please let me know if miss something, I am really keen to install the RestyaBoard, which is a really a good app.

**Comment by rrjanbiah** [comment]
@stanleyliu1006 Please give us few mins.. We're looking into it

**Comment by rrjanbiah** [comment]
@stanleyliu1006 From the errors, it is clear that nginx rewrite rules are not triggering. Probably, you have not placed `restyaboard.conf` file in the right directory.

Usually, there will be a folder inside nginx to keep all conf files. Something like `C:/nginx/conf/conf.d` or `C:/nginx/conf/sites-enabled` or so. You have to place `restyaboard.conf` file there.

Then in `nginx.conf` (may mostly be in `C:/nginx` or `C:/nginx/conf`, a directive to include all conf files (might already be there by default) (refer the right folder path) :

    include C:/nginx/conf/sites-enabled/*.conf;

Then you need to restart nginx. Access Restyaboad by http://localhost/restyaboard/ or so.

Please let us know how it goes. It may be useful for other Windows users.

**Comment by stanleyliu1006** [comment]
Hi Rajesh


Thanks your reply, I will try it tomorrow. But I don't think the Nginx windows version has either conf.d or sites-enabled folder, probably I will include the absolute directory.


Kind regards

Stanley


________________________________

**Comment by rrjanbiah** [comment]
@stanleyliu1006 OK sure

**Comment by stanleyliu1006** [comment]
Hi rrjanbiah

After testing, its still showing the same error. Let me specify what I have done:

1. Unfortunately, there's no sites-enabled or conf.d folder in the windows Nginx version, such as the diagram below:
![image](https://cloud.githubusercontent.com/assets/6980917/12997522/34f85d6a-d18e-11e5-9f6e-5df70f06338e.png)

2. Then I include the restyaboard.conf in the nginx.conf 
![image](https://cloud.githubusercontent.com/assets/6980917/12997538/6919ea5a-d18e-11e5-9076-b3665733bdcf.png)
 
3. I tried to use (with quote or not) in nginx.conf: 
include "C:/Nginx/html/restyaboard/*.conf"; 
include C:/Nginx/html/restyaboard/*.conf; 
but none of them is working

4. Finally I make up the site-enabled folder and put the restyaboard.conf in, and reflects the nginx.conf, but still not working.

I am pretty sure the Nginx rewirte rules are not triggering, can you please let me know if there's still something I am missing?

Stanley

**Comment by rrjanbiah** [comment]
@stanleyliu1006 

> I tried to use (with quote or not) in nginx.conf: 
> include "C:/Nginx/html/restyaboard/.conf"; 
> include C:/Nginx/html/restyaboard/.conf; 
> but none of them is working

In the screenshot we can find `*.conf`; but here above, you're missing `*`

So, we're not sure if you're doing things correct.

Please try this:

1. Create `C:/nginx/conf/sites-enabled` directory
2. Copy `restyaboard.conf` and place it inside `C:/nginx/conf/sites-enabled`
3. In `nginx.conf`, mention path: `include C:/nginx/conf/sites-enabled/*.conf;`

Restart nginx. Please double check if it is really restarting. If not, restart your system to get it restarted. If you're still getting same error, enable `error_log` and `access_log` by removing `#`. Attache screenshots and attach error log and access log files.

**Comment by stanleyliu1006** [comment]
Hi rrjanbiah

The error still happens after following the steps you suggested.

1. The location of restyaboard.conf
![image](https://cloud.githubusercontent.com/assets/6980917/13036815/17516862-d3c6-11e5-991b-abefd775eb46.png)

2. Nginx.conf, error_log and access_log (download zip files)
[error_log.zip](https://github.com/RestyaPlatform/board/files/129944/error_log.zip)

3. Nginx is already starting
![image](https://cloud.githubusercontent.com/assets/6980917/13036849/e2a84d8c-d3c6-11e5-971d-9baabd215d4b.png)

4. The restyaboard is still showing blank page
![image](https://cloud.githubusercontent.com/assets/6980917/13036854/0105b7ec-d3c7-11e5-84da-03b4ac9c838c.png)

5. Restyaboard.conf file is as below:
server {
	listen 8084 default_server;
	server_name _;

	root C:/Nginx/html/restyaboard;
index  index.html index.php;

gzip on;
gzip_disable "msie6";

gzip_comp_level 6;
# gzip_comp_level 9;
gzip_min_length  1100;
gzip_buffers 16 8k;
gzip_proxied any;
# gzip_http_version 1.1;
gzip_types       text/plain application/xml text/css text/js text/xml application/x-javascript text/javascript application/json application/xml+rss;

client_max_body_size 300M;

rewrite ^/download/([0-9]*)/([a-zA-Z0-9_\.]*)$ /server/php/R/download.php?id=$1&hash=$2 last;
rewrite ^/ical/([0-9]*)/([a-z0-9]*).ics$ /server/php/R/ical.php?id=$1&hash=$2 last;
rewrite ^/api/(.*)$ /server/php/R/r.php?_url=$1&$args last;

location / {
    root C:/Nginx/html/restyaboard/client;
}

location ~ \.php$ {
    try_files $uri =404;
    include fastcgi_params;
    fastcgi_pass    127.0.0.1:9000;
    fastcgi_index   index.php;
    fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PHP_VALUE "upload_max_filesize = 300M \n post_max_size=301M";
}

location ~* \.(css|js|less|html|ttf|woff|jpg|jpeg|gif|png|bmp|ico) {
    root C:/Nginx/html/restyaboard/client;
    if (-f $request_filename) {
    break;
    }
    rewrite ^/img/([a-zA-Z_]*)/([a-zA-Z_]*)/([a-zA-Z0-9_\.]*)$ /server/php/R/image.php?size=$1&model=$2&filename=$3 last;
    add_header        Cache-Control public;
    add_header        Cache-Control must-revalidate;
    expires           7d;
}
}

Please let me know if there's any possibilities make it stop working.

Stanley

**Comment by rrjanbiah** [comment]
@stanleyliu1006 We're trying to set it up in Windows like you and trying to reproduce the error. Please give us few hours to reply.

**Comment by stanleyliu1006** [comment]
Thanks so much rrjanbiah. You are legend

**Comment by rrjanbiah** [comment]
@stanleyliu1006 Please find the steps that I have followed in Windows XP:

1. Install nginx, postgresql, adminer, Pickle, Fake Sendmail, WPN-XM - Service Control Panel, WPN-XM Webinterface using https://github.com/WPN-XM/WPN-XM at `D:\server`

2. Download latest built file from https://github.com/RestyaPlatform/board/releases (board-v0.1.6.zip) and place it in `D:\server\www\restyaboard`

3. Place attached
[restyaboard.conf](https://github.com/RestyaPlatform/board/files/131073/restyaboard.conf.txt) in `D:\server\bin\nginx\conf\domains-enabled`. Notice the changes in `fastcgi_pass`

4. Prepare postgresql with below (this could have been done better):

       `D:\server\bin\pgsql\bin>createuser -s -d -r postgres`
       `D:\server\bin\pgsql\bin>createdb -h localhost -U postgres restyaboard`
       `D:\server\bin\pgsql\bin>psql -h localhost -U postgres`

```
CREATE USER restya WITH PASSWORD 'hjVl2!rGd';
ALTER DATABASE restyaboard OWNER TO restya;
GRANT ALL PRIVILEGES ON DATABASE restyaboard TO restya;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO restya;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO restya;
```

`D:\server\bin\pgsql\bin>psql -h localhost -d restyaboard -U restya -W < d:\server\www\restyaboard\sql\restyaboard_with_empty_data.sql
`
5. Visit http://localhost/tools/webinterface/index.php?page=config#php-ext to enable curl, gd2, ldap, mobstring, pdo_pgsql, pgsql extensions.
6. Start nginx, php, postgresql through WPN-XM Service Control Panel. If they're already running, restart them.
7. Restyaboard is up and running at http://localhost:8084/


@stanleyliu1006 Please let us know if you need any more help.

**Comment by stanleyliu1006** [comment]
Hi rrjanbiah

Thanks so much for your suggestions. Finally I got the login page showing up following your instruction, unfortunately the login function seems not working, when i using username: admin, password: restya

The login page stucks and not really login to the restyaboard after test the links below

http://localhost:8084/index.html#/boards (not working, and redirect back to login page)

![image](https://cloud.githubusercontent.com/assets/6980917/13065051/9c445ebc-d4ac-11e5-8dff-4be59af993a6.png)

php configuration items:

![image](https://cloud.githubusercontent.com/assets/6980917/13065117/52fbb2fe-d4ad-11e5-8868-f5f69df8e695.png)

Postgre database should be correctly configured.

And php_error has the warning message below:

[16-Feb-2016 12:50:32 Australia/Melbourne] PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
[16-Feb-2016 12:50:32 Australia/Melbourne] PHP Warning:  Cannot modify header information - headers already sent in Unknown on line 0
[16-Feb-2016 12:50:32 Australia/Melbourne] PHP Warning:  Cannot modify header information - headers already sent in C:\WPN-XM\server\www\restyaboard\server\php\R\r.php on line 21
[16-Feb-2016 12:50:32 Australia/Melbourne] PHP Warning:  Cannot modify header information - headers already sent in C:\WPN-XM\server\www\restyaboard\server\php\R\r.php on line 22
[16-Feb-2016 12:50:32 Australia/Melbourne] PHP Warning:  Cannot modify header information - headers already sent in C:\WPN-XM\server\www\restyaboard\server\php\R\r.php on line 3841


Nginx access log shows:

127.0.0.1 - - [16/Feb/2016:12:58:31 +1100] "GET /index.html HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
127.0.0.1 - - [16/Feb/2016:12:58:31 +1100] "GET /css/default.cache.2455c212.css HTTP/1.1" 304 0 "http://localhost:8084/index.html" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
127.0.0.1 - - [16/Feb/2016:12:58:31 +1100] "GET /js/default.cache.4eef4336.js HTTP/1.1" 304 0 "http://localhost:8084/index.html" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
127.0.0.1 - - [16/Feb/2016:12:58:31 +1100] "GET /favicon.ico HTTP/1.1" 304 0 "http://localhost:8084/index.html" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
127.0.0.1 - - [16/Feb/2016:12:58:32 +1100] "GET /api/v1/oauth.json?_=1455587911933 HTTP/1.1" 200 689 "http://localhost:8084/index.html" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
127.0.0.1 - - [16/Feb/2016:12:58:32 +1100] "GET /api/v1/settings.json?token=3cfe1d44e1fd91ee08b5abb00f7cabbd16c94e1a&_=1455587912169 HTTP/1.1" 200 168 "http://localhost:8084/index.html" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
127.0.0.1 - - [16/Feb/2016:12:58:36 +1100] "POST /api/v1/users/login.json?token=3cfe1d44e1fd91ee08b5abb00f7cabbd16c94e1a HTTP/1.1" 200 1580 "http://localhost:8084/index.html" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"


No error in the Nginx error_log

The r.php file is like the link below:
[r.zip](https://github.com/RestyaPlatform/board/files/131762/r.zip)

Any advise would be really appreciated.

Regards
Stanley

**Comment by rrjanbiah** [comment]
@stanleyliu1006 

> And php_error has the warning message below:
> 
> [16-Feb-2016 12:50:32 Australia/Melbourne] PHP Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
> [16-Feb-2016 12:50:32 Australia/Melbourne] PHP Warning: Cannot modify header information - headers already sent in Unknown on line 0

As we don't have anything such in Restyaboard, this could be coming from extensions or you might have changed php.ini. Please check:
1. If you have any extensions that are loaded twice
2. Disable extensions one by one to trap culprit
3. Disable error reporting in `php.ini`. It is the easy step, but it is better that you find out the real cause.

**Comment by rrjanbiah** [comment]
@stanleyliu1006 Were you able to resolve it?

**Comment by stanleyliu1006** [comment]
Hi rrjanbiah

It has been fixed now, after I set 'always_populate_raw_post_data' to '-1'. 

Thank you so much for your help.

The issue can be closed now.

Stanley

**Comment by rrjanbiah** [comment]
@stanleyliu1006 Thanks for letting us know.

**Comment by trangluong2006** [comment]
Please help me solve it. I tried to do all your steps but when connect localhost:8084 then blank screen
![image](https://cloud.githubusercontent.com/assets/20334882/16647514/cd99b77e-4459-11e6-9c13-df3f1f0bd53c.png)

**Comment by trangluong2006** [comment]
Hi ssivachidambaram,
Im using Restyaboard v1.0.3.
I encountered a problem as follows: I can add comment, edit and reply comment for card but when i choose delete comment then it does not work. Please help me solve it. 
Thank you so much!
 Regards,
Trang
