### ISSUE TITLE
Database errors in logs

### ISSUE THREAD

**Issue by erl4nc** [RestyaPlatform/board#2247]
There are database errors in logs.  I do not know if the web server log errors correspond to the postgres error log entries but timestamps indicate they may be related.

postgres error log shows multiple entries of:
`
2018-12-06 09:12:29.175 PST [1929] STATEMENT:  INSERT INTO checklist_items (created, modified, "card_id", "checklist_id", "name", "checklist_items", "activities", "user_id", "position") VALUES (now(), now(), $1, $2, $3, $4, $5, $6, $7) RETURNING *`
`2018-12-06 09:12:29.221 PST [1930] ERROR:  column "checklist_items" of relation "checklist_items" does not exist at character 84
`

Web server error log shows multiple entries of the following:
`
2018/12/06 09:12:29 [error] 1173#1173: *244 FastCGI sent in stderr: "PHP message: PHP Notice:  Array to string conversion in server/php/libs/core.php on line 882
PHP message: PHP Notice:  Array to string conversion in server/php/libs/core.php on line 882
PHP message: PHP Warning:  pg_query_params(): Query failed: ERROR:  column &quot;checklist_items&quot; of relation &quot;checklist_items&quot; does not exist
LINE 1: ...ted, modified, &quot;card_id&quot;, &quot;checklist_id&quot;, &quot;name&quot;, &quot;checklist...
                                                             ^ in server/php/libs/core.php on line 882
PHP message: PHP Warning:  pg_fetch_assoc() expects parameter 1 to be resource, boolean given in server/php/R/r.php on line 4433" while reading response header from upstream, client: 172.16.0.100, server: taskmanager.delta.bc.ca, request: "POST /api/v1/boards/30/lists/343/cards/1809/checklists/321/items.json?token=token HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:",  referrer: "/"`
`2018/12/06 09:12:29 [error] 1173#1173: *244 FastCGI sent in stderr: "PHP message: PHP Notice:  Array to string conversion in server/php/libs/core.php on line 882
PHP message: PHP Notice:  Array to string conversion in server/php/libs/core.php on line 882
PHP message: PHP Warning:  pg_query_params(): Query failed: ERROR:  column &quot;checklist_items&quot; of relation &quot;checklist_items&quot; does not exist
LINE 1: ...ted, modified, &quot;card_id&quot;, &quot;checklist_id&quot;, &quot;name&quot;, &quot;checklist...
                                                             ^ in server/php/libs/core.php on line 882
PHP message: PHP Warning:  pg_fetch_assoc() expects parameter 1 to be resource, boolean given in server/php/R/r.php on line 4433" while reading response header from upstream, client: 172.16.0.100, server: taskmanager.delta.bc.ca, request: "POST /api/v1/boards/30/lists/343/cards/1809/checklists/321/items.json?token=token HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:",  referrer: "/"
`

## Expected Behavior
No errors in logs

## Current Behavior
Lots of errors.

## Steps to Reproduce (for bugs)
Unfortunately, I do not know what the users are doing to generate these errors.  I did not reproduce it by testing checklists.

## Context
I'm very concerned about losing data since the errors are insert statements.
 
## Your Environment
* Version used: 0.6.5, installed using board-v0.6.5.zip on [releases](https://github.com/RestyaPlatform/board/releases) page
* Environment name and version (e.g. OS, PHP, PostgreSQL): ubuntu 16.04, php 7, postgres 9.6
* Operating System and version (desktop or mobile): desktop

**Comment by sridhar391** [comment]
@erl4nc Can you please update your Restyaboard to the latest version 0.6.6 and please tell us if you are facing the same problem after updating your Restyaboard.

Please see the friendly changelog at https://restya.com/board/changelog
