### ISSUE TITLE
Blank Page After Installation on WAMP

### ISSUE THREAD

**Issue by itsme888** [RestyaPlatform/board#2254]
Hello,

I tried to install restyaboard v0.6.6 according to the official manual and youtube manual:

https://restya.com/board/docs/windows/#0
https://www.youtube.com/watch?v=AB2IJYuMxTQ

I'm using Bitnami WAMP Stack 7.0.27.

After installation I just get a blank page:

![grafik](https://user-images.githubusercontent.com/45767164/49819653-47f4e480-fd76-11e8-91de-a21f2d885657.png)

There is no new entry in the apache-log where I could find any hint.

In other related issues they mentioned the restyaboard_install.log.txt.

Where can I find this log-file within the folder structure?

![grafik](https://user-images.githubusercontent.com/45767164/49819449-bc7b5380-fd75-11e8-9249-7561f163b6c4.png)

Do you have any idea to solve this problem?

Thank you in advance.

**Comment by sridhar391** [comment]
@itsme888 Can you please tell us that you have rewritten the base name as /restyaboard in the `/www/html/restyaboard/.htaccess` file like  https://github.com/RestyaPlatform/board/blob/master/.htaccess#L7

Please set R_DEBUG as true on the config.inc.php file in line 15 on `/www/html/restyaboard/server/php` path like https://github.com/RestyaPlatform/board/blob/dev/server/php/config.inc.php#L15 and copy the response of http://restyaboard_url/api/v1/oauth.json on the Network tab of Browser developer tools and paste it here.

The `restyaboard_install.log` file will be only available while installing the Restyaboard using the shell script file `restyaboard.sh`

**Comment by sridhar391** [comment]
@itsme888 please create a file named `info.php` with the below content:
`<?php
phpinfo();
?>`
and save and put in your server root and access http://localhost/info.php and
please search for PDO section and under that section, there will be pdo_pgsql section for postgresql database and if you don't see the above-mentioned drivers, please find the path of php.in file by 
searching for `Configuration File (php.ini) Path` in http://localhost/info.php and
you should edit `php.ini` file and add `extension=pdo_pgsql.dll`
and restart your server and try again in info.php and if the PDO and pdo_pgsql section is in the http://localhost/info.php, please run the Restyaboard URL in the browser and if you are seeign the blank page again please follow the below instruction

Please set `R_DEBUG` as true on the `config.inc.php` file in line 15 on `/www/html/restyaboard/server/php` path like https://github.com/RestyaPlatform/board/blob/dev/server/php/config.inc.php#L15 and copy the response of http://restyaboard_url/api/v1/oauth.json on the Network tab of Browser developer tools and paste it here.

**Comment by itsme888** [comment]
Thank you so much for your support! After I included extension=pdo_pgsql.dll in php.ini and checked the pdo section again in info.php Restyaboard is loading the login page now and I was already able to login myself.

**Comment by sridhar391** [comment]
@itsme888 Thanks for your confirmation on the fix of PDOException issue
