### ISSUE TITLE
Error Message after installation

### ISSUE THREAD

**Issue by itsme888** [RestyaPlatform/board#2258]
Hello,

I tried to install restyaboard v.0.6.6 on another Server with WAMP-Stack for Windows (PHP 7.0.29).

I followed the following instructions 

https://restya.com/board/docs/windows/#0
https://www.youtube.com/watch?v=AB2IJYuMxTQ

I setup the database, 
- imported the SQL-Script, 
- changed the database credentials in server/php/config.inc.php
- used the .htacces according to https://github.com/RestyaPlatform/board/blob/master/.htaccess
- Rewrote the base name in .htaccess according to https://github.com/RestyaPlatform/board/blob/master/.htaccess#L7 as /restyaboard

After that I got a blank page when trying to run restyaboard.

Then I turned on the debugging mode in 
\server\php\config.inc.php  (line 15)

define('R_DEBUG', true);

When I try to run 

http://restyaboard_url/api/v1/oauth.json

I get the following error message:

Fatal error: Uncaught Error: Call to undefined function pg_connect() in C:\xampp\apache2\htdocs\restyaboard\server\php\config.inc.php:52 Stack trace: #0 C:\xampp\apache2\htdocs\restyaboard\server\php\R\r.php(26): require_once() #1 {main} thrown in C:\xampp\apache2\htdocs\restyaboard\server\php\config.inc.php on line 52

Do you know how to solve this problem?

**Comment by itsme888** [comment]
Ok, I found the error.
I had to install **extension=php_pgsql.dll** in the php.ini file of the WAMP-Stack.

**Comment by sridhar391** [comment]
@itsme888 Thanks for your confirmation on the fixed issue of Restyaboard installation.
