### ISSUE TITLE
Cannot login after LDAP plugins upgrade

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#2266]
Hi,

i have an issue after update ldap plugins.

## Context
Install ioncube_loader_lin_7.0.so
Edit php.ini file with 'zend_extension = /usr/lib/php/20151012/ioncube_loader_lin_7.0.so'
Restart php7.0-fpm and nginx
Execute sql script /usr/share/nginx/html/restyaboard/client/apps/r_ldap_login_bak/sql/r_ldap_login.sql
Execute sql script upgrade-0.6.5-0.6.6.sql

When i try to login with my LDAP credential i have message in chrome developper tab console :
default.cache.b41fdf50.js:68 Uncaught TypeError: Cannot read property 'is_two_factor_authentication_enabled' of undefined
    at success (default.cache.b41fdf50.js:68)
    at d.success (default.cache.b41fdf50.js:11)
    at default.cache.b41fdf50.js:85
    at Object.d.success (default.cache.b41fdf50.js:13)
    at l (default.cache.b41fdf50.js:2)
    at Object.fireWith [as resolveWith] (default.cache.b41fdf50.js:2)
    at d (default.cache.b41fdf50.js:4)
    at XMLHttpRequest.d (default.cache.b41fdf50.js:4)

## Your Environment
RestyaBoard 0.6.6

**Comment by sridhar391** [comment]
@morphos88 Can you please set R_DEBUG as true on the `config.inc.php` file in `line 15` on `/usr/share/nginx/html/restyaboard/server/php` path like https://github.com/RestyaPlatform/board/blob/dev/server/php/config.inc.php#L15 and copy the response of Login call on the Network tab of Browser developer tools and paste it here or copy the contents from your server error log and paste it here

**Comment by morphos88** [comment]
@sridhar391 

<br />
<b>Notice</b>:  Use of undefined constant R_LDAP_DISPLAY_NAME_ATTRIBUTE - assumed 'R_LDAP_DISPLAY_NAME_ATTRIBUTE' in <b>/usr/share/nginx/html/restyaboard/server/php/plugins/LdapLogin/functions.php</b> on line <b>0</b><br />
<br />
<b>Notice</b>:  Use of undefined constant R_LDAP_DISPLAY_NAME_ATTRIBUTE - assumed 'R_LDAP_DISPLAY_NAME_ATTRIBUTE' in <b>/usr/share/nginx/html/restyaboard/server/php/plugins/LdapLogin/functions.php</b> on line <b>0</b><br />
<br />
<b>Notice</b>:  Use of undefined constant R_LDAP_EMAIL_ATTRIBUTE - assumed 'R_LDAP_EMAIL_ATTRIBUTE' in <b>/usr/share/nginx/html/restyaboard/server/php/plugins/LdapLogin/functions.php</b> on line <b>0</b><br />
<br />
<b>Notice</b>:  Use of undefined constant R_LDAP_EMAIL_ATTRIBUTE - assumed 'R_LDAP_EMAIL_ATTRIBUTE' in <b>/usr/share/nginx/html/restyaboard/server/php/plugins/LdapLogin/functions.php</b> on line <b>0</b><br />
<br />
<b>Notice</b>:  Use of undefined constant R_LDAP_IMAGE_ATTRIBUTE - assumed 'R_LDAP_IMAGE_ATTRIBUTE' in <b>/usr/share/nginx/html/restyaboard/server/php/plugins/LdapLogin/functions.php</b> on line <b>0</b><br />
<br />
<b>Notice</b>:  Use of undefined constant R_LDAP_IMAGE_ATTRIBUTE - assumed 'R_LDAP_IMAGE_ATTRIBUTE' in <b>/usr/share/nginx/html/restyaboard/server/php/plugins/LdapLogin/functions.php</b> on line <b>0</b><br />
<br />
<b>Notice</b>:  Use of undefined constant R_LDAP_LOGIN_HANDLE - assumed 'R_LDAP_LOGIN_HANDLE' in <b>/usr/share/nginx/html/restyaboard/server/php/plugins/LdapLogin/functions.php</b> on line <b>0</b><br />
<br />
<b>Notice</b>:  Use of undefined constant R_LDAP_LOGIN_HANDLE - assumed 'R_LDAP_LOGIN_HANDLE' in <b>/usr/share/nginx/html/restyaboard/server/php/plugins/LdapLogin/functions.php</b> on line <b>0</b><br />
{"code":"LDAP","error":"ERROR_LDAP_EMAIL_NOT_ASSOCIATED"}

**Comment by sridhar391** [comment]
@morphos88 we need screen share meeting to solve the issue, please mail us at info@restya.com

**Comment by sridhar391** [comment]
The issue has been solved by running the LDAP Login update SQL file in the Restyaboard Database.
