### ISSUE TITLE
Allow different ports for postgres in docker

### ISSUE THREAD

**Issue by DracoMilesX** [RestyaPlatform/board#2269]
Hello I tried to install restya with docker but it looks like since postgres databases run on different ports it doesn't seem to connect.

By the looks of things this is because port "5432" is hard coded 

https://github.com/RestyaPlatform/board/blob/dev/docker-scripts/docker-entrypoint.sh

Could this be replaced with a variable as well so that we can use custom ports too?

**Comment by sridhar391** [comment]
@DracoMilesX sorry, we aren't familiar with docker, @BlackDark can you able to apply the changes for replacing the Postgresql Port value with a variable.

**Comment by BlackDark** [comment]
Created PR
