### ISSUE TITLE
cannot see file attachment

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#2272]
When i click on file attachment on card i have a 404 error.

Restyaboard v0.6.6

**Comment by morphos88** [comment]
In nginx error log :
[error] 6452#6452: *60343 open() "/usr/share/nginx/html/restyaboard/client/img/original/CardAttachment/2817.14563cf92c1d7a131b5119ce07c42e89.pdf" failed (2: No such file or directory), client: , server: , request: "GET /img/original/CardAttachment/2817.14563cf92c1d7a131b5119ce07c42e89.pdf HTTP/1.0", host: , referrer:

**Comment by sridhar391** [comment]
@morphos88 Please add the pdf extension in the `restyaboard.conf` file `line 41` like https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf#L41

**Comment by morphos88** [comment]
he was already there :
![image](https://user-images.githubusercontent.com/25505555/50557865-73ba1900-0ce9-11e9-9050-42280755d7cc.png)

**Comment by morphos88** [comment]
in directory usr/share/nginx/html/restyaboard/client/img/original/CardAttachment/ i have almost nothing :

![image](https://user-images.githubusercontent.com/25505555/50557963-4752cc80-0cea-11e9-8e7b-3f3253494c75.png)

**Comment by sridhar391** [comment]
@morphos88 We haven't seen this type of issue, Shall we have a screen share meeting to solve the problem, please send us the mail at info@restya.com and we will send the meeting URL with the password.

**Comment by morphos88** [comment]
it was on line 67 not 41
