### ISSUE TITLE
Docker fixes

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#2282]
@LittleFox94 has kindly provided fixes at https://github.com/LittleFox94/board/commits/docker-fixes (From https://groups.google.com/d/msg/restya/xh8JB_3toLE/sicbGcnuDwAJ )

(As we're not very much familiar with Docker) Current docker code was kindly provided by @BlackDark So, @BlackDark can you please share your feedback so that we can merge? Thanks

**Comment by LittleFox94** [comment]
I'll look into it

**Comment by rrjanbiah** [comment]
Thank you both of you @BlackDark @LittleFox94

**Comment by BlackDark** [comment]
@rrjanbiah assign me. Will fix this.

**Comment by LittleFox94** [comment]
I'm very sorry I didn't look into this again ._.
