### ISSUE TITLE
IMAP Mails with Umlauts wont get importet as card

### ISSUE THREAD

**Issue by niklaskarg** [RestyaPlatform/board#2285]
## Current Behavior
Title is pretty self explaining, as soon as i have an umlaut in text body the mail is marked read but never imported as card.

## Steps to Reproduce (for bugs)
send mail with Umlaut

## Your Environment
* Version used:
Restyaboard v0.6.6
Debian 9.2
nginx/1.10.3
Postfix 3.1.6
dovecot 2.2.27

**Comment by niklaskarg** [comment]
i worked around the issue in imap.php with adding iconv for our specific encoding, perhaps someone can code a more generic fix for it.
line 91:
            $val_arr = array(
                                $board_id,
                                $list_id,
                               iconv("Windows-1252", "UTF-8//TRANSLIT",$title),
                                iconv("Windows-1252", "UTF-8//TRANSLIT",$body),
                                $position,
                                $board['user_id']
                            );

**Comment by sridhar391** [comment]
@niklaskarg Thanks for your fix and we will check about the issue

**Comment by sridhar391** [comment]
@niklaskarg we have fixed the issue in the commit https://github.com/RestyaPlatform/board/commit/7f517950a959cd84cbd4f245cfdeee68bbc25888 , please copy the file and paste in in the `/usr/share/nginx/html/restyaboard/server/php/shell` folder path
