### ISSUE TITLE
Problem with new LDAP account

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#2288]
With the new LDAP v 0.1.3 application users are imported with special characters instead of accented characters.

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/25505555/51175692-4d84a380-18bb-11e9-9657-04da1c2db04c.png)

## Your Environment
RestyaBoard v 0.6.6
LDAP v 0.1.3

**Comment by rrjanbiah** [comment]
@morphos88 We can't seem to reproduce it here.

Can you please kindly share the original text and mangled text? That will help us to see if it is anything to do with encoding. Thanks

**Comment by morphos88** [comment]
Original text is "RANAIVOSON Frédéric"

**Comment by rrjanbiah** [comment]
@morphos88 Thank you

**Comment by sridhar391** [comment]
@morphos88 we have fixed the issue and sent the fixed files to your mail
