### ISSUE TITLE
Gant chart doesn't update

### ISSUE THREAD

**Issue by Zimeon-** [RestyaPlatform/board#229]
Gant chart doesn't update if you make changes in a board card, for example add a due date to a card. Once the due date has been added, clicking on gant chard doesn't list the new card with due date. For the gant chart to reload, user needs to re-open/reload the board and then move to gant chart.
edit: fixed typos

**Comment by rrjanbiah** [comment]
@Zimeon- Thanks for your report. We'll fix it soon.

**Comment by ssivachidambaram** [comment]
Fixed.
