### ISSUE TITLE
In modal card page, in the custom field, while pasting the contents from the excel sheet, it adds the attachment to the card

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#2293]
## Expected Behavior
In modal card page, in the custom field, while pasting the contents from the excel sheet, it should be pasted as the value

## Current Behavior
In modal card page, in the custom field, while pasting the contents from the excel sheet, it adds the attachment to the card

## Steps to Reproduce (for bugs)

1. Login and go to boards page
2. Go to any particular board page by clicking the board name
3. Open the modal card by clicking any card
4. Open any custom field by clicking and paste any content copied from the excel sheet

**Comment by baskar383** [comment]
closing the issue, Due to inactivity.
