### ISSUE TITLE
Card history filtering

### ISSUE THREAD

**Issue by Zimeon-** [RestyaPlatform/board#230]
Option to filter out card actions from the card activity history. This would allow the user to only see comments on a card and not actions like when the card was moved. Comments are easily pushed down on a card and thus hard to find. This option could be a toggle button within the card itself.

**Comment by rrjanbiah** [comment]
@Zimeon- Thanks for your report. Looks like this is same as #179 ?

**Comment by Zimeon-** [comment]
Similar, notifications are the feed on the side (bell icon) while this would be within the card itself to filter out other actions except comments. Filtering none the less.

**Comment by rrjanbiah** [comment]
@Zimeon- Thanks for clarifying.

**Comment by ssivachidambaram** [comment]
Done.
