### ISSUE TITLE
 trying to login into restyaboard through api

### ISSUE THREAD

**Issue by SheheryarGhaznavi** [RestyaPlatform/board#2337]
i am trying to login into restyaboard through api
i first get the outh token (success)
then login though login.json (sucess)
then i redirect to domain.com/#/boards it redirect me to login page

code  :

`<?php 
// print_r($_POST);
// echo "good";
$ch = curl_init("http://ip/api/v1/oauth.json");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, 'Content-Type: application/json');
$result = curl_exec($ch);
curl_close($ch);
$result = json_decode(preg_replace('/[\x00-\x1F\x80-\xFF]/', '', $result), true);
$token = $result['access_token'];
// print_r($token);

$params=['email'=>'sheheryar@technolectuals.com', 'password'=>'abc123'];
$params = json_encode($params);
$ch = curl_init("http://ip/api/v1/users/login.json?token=".$token);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, 'Content-Type: application/json');
curl_setopt($ch, CURLOPT_POSTFIELDS, $params);
$result = curl_exec($ch);
curl_close($ch);
$result = json_decode(preg_replace('/[\x00-\x1F\x80-\xFF]/', '', $result), true);
// print_r($result);

header('Location: http://ip/#/boards');

?>`

**Comment by rrjanbiah** [comment]
@SheheryarGhaznavi It is not clear... what do you want to achieve here?

Are you trying to login to our demo instance or your local instance? In both cases, why do you want to login using API?

**Comment by rrjanbiah** [comment]
@SheheryarGhaznavi But, you're still redirecting to Restyaboard instance, right?

```php
header('Location: http://ip/#/boards');
```

Or, are you just trying to consume boards from other application?

**Comment by rrjanbiah** [comment]
@SheheryarGhaznavi In other words, if you're trying to access boards through API, why are you trying to access it in UI after login?

**Comment by SheheryarGhaznavi** [comment]
yes because after all i am doing all this to access that board page

**Comment by SheheryarGhaznavi** [comment]
actually i am connecting restyaboard to my site and i want to redirect my user to this board page to use, but i dont want my user to go through the registration and login process , these thing i want to handle through api in backend

**Comment by rrjanbiah** [comment]
@SheheryarGhaznavi Understood.

You need to set `auth` cookie. Please refer here https://github.com/RestyaPlatform/board/blob/dev/client/js/views/authenticate_view.js#L127

**Comment by SheheryarGhaznavi** [comment]
what do i have to set in auth cookie

**Comment by rrjanbiah** [comment]
@SheheryarGhaznavi Please refer to the code and you'll get idea https://github.com/RestyaPlatform/board/blob/dev/client/js/views/authenticate_view.js#L127

**Comment by rrjanbiah** [comment]
Closing this now. In case, if you face any issues, please feel free to reopen
