### ISSUE TITLE
Coloring difference needed for archive and overdue

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#234]
From https://groups.google.com/d/msg/restya/l3FsaCSrYCI/2smvr2Z4AQAJ by Domenico Mele

in calendar view, card archived coloured in other way (now all is orange, for example archive cards in  light gray)
in overdue date card, change color of calendar date from little gray to red.

**Comment by Zimeon-** [comment]
Sounds like a good idea.

**Comment by rrjanbiah** [comment]
@Zimeon- Thanks for your input too

**Comment by ssivachidambaram** [comment]
Fixed
