### ISSUE TITLE
Boards Visibility

### ISSUE THREAD

**Issue by itsme888** [RestyaPlatform/board#2363]
Hello,

I have a question:

I created new boards with an admin user and set the visibility for each board on “private” and I didn’t add any member to the boards.

 
![board](https://user-images.githubusercontent.com/45767164/52557229-138dbb00-2def-11e9-8e72-477b7e5c1fa7.png)

But when I log in with another admin user I can see all the boards although they have private visibility.

Do all admins have access to other admins’ boards although they are private or how can I set these boards invisible for other admin users?

Thank you in advance for your help.

**Comment by sridhar391** [comment]
@itsme888 By the flow, the admin users can see all the boards in the Restyaboard

**Comment by baskar383** [comment]
Duplicate issue Reference #2243. kindly closing the issue.
