### ISSUE TITLE
function __1 not found in imap.php

### ISSUE THREAD

**Issue by niklaskarg** [RestyaPlatform/board#2367]
in imap php on line 112 is called a function "__1"

` // Inserting activities for the inserted card` 
`                             $val_arr = array(` 
`                                 $card_id,` 
`                                 $board['user_id'],` 
`                                 $list_id,` 
 `                                $board_id,` 
   `                              'add_card',` 
`                                 __l('##USER_NAME## added card ##CARD_LINK## to list ##LIST_NAME##.')` 

 i cant find it in the php file and it generates an error:
`Uncaught Error: Call to undefined function __l() `
if i replace this with some string the error is gone and i get the string as comment on my card.
I guess the function should fill the correct user, which is not happneing for me.
What am i missing, where should the function be found?

**Comment by sridhar391** [comment]
@niklaskarg please add the line `require_once $app_path . '/libs/core.php';` after `line 16` of the `/usr/share/nginx/html/restyaboard/server/php/shell/imap.php` file like https://github.com/RestyaPlatform/board/blob/master/server/php/shell/imap.php#L16 and the the function __l is defined in the `server/php/libs/core.php` file like https://github.com/RestyaPlatform/board/blob/master/server/php/libs/core.php#L2970
