### ISSUE TITLE
There is no smoothness, while moving the lists and cards.

### ISSUE THREAD

**Issue by Rosalie1992** [RestyaPlatform/board#24]
There is no smoothness, while moving the lists and cards.

**Comment by rrjanbiah** [comment]
Does it happen all the times?

**Comment by Rosalie1992** [comment]
We have around 15 list. moving first list to outside of the viewport gets slow, when we move it to right end.

**Comment by rrjanbiah** [comment]
Thanks for clarifying.

**Comment by rrjanbiah** [comment]
@ssivachidambaram For your attention

**Comment by ssivachidambaram** [comment]
Fixed
