### ISSUE TITLE
Issue with restyaboard.sh

### ISSUE THREAD

**Issue by genie-nlu-shared** [RestyaPlatform/board#240]
Hi, this is similar to issue 167, but his solution didn't address mine.

I've installed via the script, and when I run the app from the FQDN, I get the blank page, I can see the red progress indicator, I get redirected to the login URL, and when I look at the logs, I see oauth request getting a 502 Bad Gateway error.

I'll keep poking around to see if I can discover anything, but I'm kind of at a loss.

Cheers,
Arlo

**Comment by rrjanbiah** [comment]
Linking #167 for future reference.

@genie-nlu-shared It looks like php-fpm may not be running. Can you check if it is started? and let us know?

**Comment by genie-nlu-shared** [comment]
Well... you're right, it wasn't running. It's running now but I still get the blank white page, now without the error in the log.

**Comment by genie-nlu-shared** [comment]
Okay, that stopped the 502 error, but now I'm still getting the blank white page.

After clearing out my nginx error.log file, I'm not showing any errors (and I have logging turned on).

**Comment by rrjanbiah** [comment]
@genie-nlu-shared Can you check HTTP request and post HTTP status and response?

**Comment by genie-nlu-shared** [comment]
For Oauth? Looks like it happens via GET, not POST.

Here's the URL, I can edit it out later: http://aol.a45.co

**Comment by genie-nlu-shared** [comment]
Oh, looking at the Oauth content it's a Postgres password error. - I had fixed that... so now I'm not entirely sure what to do since the passwords are all the same and line up (I've only ever used MySQL and MongoDB, so I'm a little green with Postgres setup, sorry).

**Comment by genie-nlu-shared** [comment]
I think I have the PW issues fixed, but now I see the install never created the actual DB. I'm trying a reinstall, but I don't see how to do a clean and am not getting anywhere. Sorry for being a pest. :-/

The script just exits with:

./restyaboard.sh: 86: ./restyaboard.sh: [[: not found
+ echo No new version available
No new version available

**Comment by genie-nlu-shared** [comment]
Okay, looks like a chain of things failed in the install. I've been redoing them by hand, and I think I'm up and running now. WHEW!

**Comment by rrjanbiah** [comment]
@genie-nlu-shared Sorry for the trouble you had. Glad to hear that you got it resolved. 

In case if you found any issues in the script, please share. That may be useful for other people.

**Comment by genie-nlu-shared** [comment]
@rrjanbiah Looking at the script, my feeling is that it needs to be more robust about error reporting, solving the errors in the script, and being more thorough about partial installs when re-run.

In my case, whatever happened the first time caused it to not let me know php-fpm was missing. It should have checked, then on seeing it wasn't there do an install of it.

I don't know why the DB piece failed, but again, if it did a sanity check, maybe saw the permissions weren't right, or the password didn't work, it could then walk the user through getting that set up right.

**Comment by rrjanbiah** [comment]
@genie-nlu-shared Thanks a lot for your kind suggestions. Yes, handling exit code is pending #133

We'll definitely improve
