### ISSUE TITLE
How to enable ElasticSearch ?

### ISSUE THREAD

**Issue by PolarisPT** [RestyaPlatform/board#246]
Hi,
I've just installed restya in ubuntu 14.04 and seach doesn't seem to be running, do i need to do any configuration in restya ?

Thx
Pol

**Comment by rrjanbiah** [comment]
@PolarisPT Yes it needs ElasticSearch. How did you install Restyaboard? Have you used our install script?

**Comment by PolarisPT** [comment]
Yes i did, and i have it running :  

elastic+  1196     1  0 Feb11 ?        00:02:30 /usr/lib/jvm/java-6-openjdk-amd64/bin/java -Xms256m -Xmx1g -Xss256k -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Delasticsearch -Des.pidfile=/var/run/elasticsearch.pid -Des.path.home=/usr/share/elasticsearch -cp :/usr/share/elasticsearch/lib/elasticsearch-0.90.7.jar:/usr/share/elasticsearch/lib/*:/usr/share/elasticsearch/lib/sigar/* -Des.default.config=/etc/elasticsearch/elasticsearch.yml -Des.default.path.home=/usr/share/elasticsearch -Des.default.path.logs=/var/log/elasticsearch -Des.default.path.data=/var/lib/elasticsearch -Des.default.path.work=/tmp/elasticsearch -Des.default.path.conf=/etc/elasticsearch org.elasticsearch.bootstrap.ElasticSearch

But do i need to setup anything else in /?#/settings/1 ?

**Comment by rrjanbiah** [comment]
@PolarisPT Yes, you have to enter the server details (IP, port)

Also, you need to setup cron too.. for the ElasticSearch indexing

**Comment by dfragac** [comment]
Exactly why is ElasticSearch neccesary in Restyaboard. All simple features are disponible without it...

**Comment by rrjanbiah** [comment]
@dfragac ElasticSearch is for providing better search feature. Our approach is to use right tool for the right feature without affecting performance.

**Comment by dfragac** [comment]
Perfect! Regards for the info!

**Comment by rrjanbiah** [comment]
@dfragac You're welcome

**Comment by rrjanbiah** [comment]
@PolarisPT Were you able to figure it out?

**Comment by PolarisPT** [comment]
Not yet :(
confgured "http://localhost:9200" in URL field, but still i'm not able to find any card ...

Also took a look at cron and cron.sh is returning an error pls look below : 

"
root@tcboard:~# crontab -l
*/5 * * * * /usr/share/nginx/html/restyaboard/server/php/R/shell/cron.sh
*/5 * * * * /usr/share/nginx/html/restyaboard/server/php/R/shell/instant_email_notification.sh
0 * * * * /usr/share/nginx/html/restyaboard/server/php/R/shell/periodic_email_notification.sh
root@tcboard:~# /usr/share/nginx/html/restyaboard/server/php/R/shell/cron.sh
2016-02-12 18:16:57 #################################################
successfully acquired lock: /usr/share/nginx/html/restyaboard/server/php/R/shell/cron_sh.lock
/usr/share/nginx/html/restyaboard/server/php/R/shell/cron.sh: line 16: php: command not found
"

**Comment by rrjanbiah** [comment]
@PolarisPT

> php/R/shell/cron.sh: line 16: php: command not found

Yes, thi

**Comment by rrjanbiah** [comment]
@PolarisPT

> php/R/shell/cron.sh: line 16: php: command not found

Yes, this looks like the culprit.

Can you see:

1. If php is installed
2. If so try setting path environment or mention complete path in `cron.sh`

**Comment by PolarisPT** [comment]
@rrjanbiah 
php-cli wasn't installed , should be included in restyaboard.sh

Now another error ...
"
root@tcboard:/usr/local# /usr/share/nginx/html/restyaboard/server/php/R/shell/cron.sh
2016-02-12 18:44:55 #################################################
successfully acquired lock: /usr/share/nginx/html/restyaboard/server/php/R/shell/cron_sh.lock
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
Not Found.
"

**Comment by PolarisPT** [comment]
@dfragac 
Are you able to do searches inside restya ?
searches for cards, boards, organizations for instance ?

**Comment by rrjanbiah** [comment]
@PolarisPT


Error suggests either ElasticSearch is not available or not correctly configured in Restyaboard.

1. Check ElasticSearch at http://localhost:9200/

2. Check our demo for how to enter ElasticSearch configuration

**Comment by PolarisPT** [comment]
@rrjanbiah 

I'm able to run curl -X GET 'http://localhost:9200' sucessfully , so elasticsearch is up and running.
I've also configured ElasticSearch has in Demo site but search still doesn't work.

Any logs where i could try to find an error ?

**Comment by rrjanbiah** [comment]
@PolarisPT

Error is thrown due to unexpected HTTP code coming from ElasticSearch in https://github.com/RestyaPlatform/board/blob/master/server/php/R/shell/cron.php

We'll need some time to add more descriptive error handling.

**Comment by dfragac** [comment]
Sorry for not answering before. I'm using Docker image to run Restyaboard and Elasticsearch. I don't configure it yet but, as soon as I try, I'll post here.

**Comment by rrjanbiah** [comment]
@PolarisPT We need your help to identify the issue. 

1. Please execute `UPDATE settings SET value = 0 WHERE name = 'elasticsearch.last_processed_activtiy_id';`
2. Overwrite https://github.com/RestyaPlatform/board/blob/master/server/php/R/shell/cron.php with attached [cron.php](https://github.com/RestyaPlatform/board/files/132042/cron.php.txt)

And let us know the error reported now.

**Comment by PolarisPT** [comment]
@rrjanbiah 
Regarding 1 what do i need to do ?
Where shoud i put "UPDATE settings SET value = 0 WHERE name = 'elasticsearch.last_processed_activtiy_id';"

**Comment by PolarisPT** [comment]
@rrjanbiah 
Ok figured it out executed UPDATE on postgres DB : 

"
root@tcboard:/usr/share/nginx/html/restyaboard/server/php/R# psql -d restyaboard -U restya
psql (9.4.6)
Type "help" for help.

restyaboard=> UPDATE settings SET value = 0 WHERE name = 'elasticsearch.last_processed_activtiy_id';
UPDATE 1
"

Executed cron.sh manually and here is the output : 

"
root@tcboard:/usr/share/nginx/html/restyaboard/server/php/R# /usr/share/nginx/html/restyaboard/server/php/R/shell/cron.sh
2016-02-16 10:32:54 #################################################
successfully acquired lock: /usr/share/nginx/html/restyaboard/server/php/R/shell/cron_sh.lock
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
Saved Successfully.
root@tcboard:/usr/share/nginx/html/restyaboard/server/php/R#
"

**Comment by PolarisPT** [comment]
@rrjanbiah 
Search is working now !
it seems new cron.php version fixed the problem, thanks !

**Comment by rrjanbiah** [comment]
@PolarisPT Awesome news! But, strange that I have only added few debug codes. Not fixed anything.

Anyway closing this for now. In case, if you get any more issues, please feel free to reopen.

**Comment by vgonzal** [comment]
Hello.

I've got the same problem. I've installed using the script in a Ubuntu 14.04. 

Elasticsearch is listening at 9200. 
{
  "ok" : true,
  "status" : 200,
  "name" : "Death",
  "version" : {
    "number" : "0.90.7",
    "build_hash" : "36897d07dadcb70886db7f149e645ed3d44eb5f2",
    "build_timestamp" : "2013-11-13T12:06:54Z",
    "build_snapshot" : false,
    "lucene_version" : "4.5.1"
  },
  "tagline" : "You Know, for Search"
}

I've updated the DB and execute the cron.sh


root@restya:/var/log# /usr/share/nginx/html/restyaboard/server/php/R/shell/cron.sh
2016-02-16 12:10:21 #################################################
successfully acquired lock: /usr/share/nginx/html/restyaboard/server/php/R/shell/cron_sh.lock
root@restya:/var/log#


Maybe, Can I missed anything?

Best regards

**Comment by rrjanbiah** [comment]
@vgonzal Strange. What exact error you get? Can you please attach install log?

**Comment by vgonzal** [comment]
I  have not error. Simply no have response from the field with the magnifying glass

**Comment by vgonzal** [comment]
[restyaboard_install.txt](https://github.com/RestyaPlatform/board/files/132349/restyaboard_install.txt)

**Comment by rrjanbiah** [comment]
@vgonzal There are few issues in DB import, but that shouldn't be a blocker. Few notes:

1. Do you have enough cards/data?
2. Please enable debug mode in https://github.com/RestyaPlatform/board/blob/master/server/php/R/config.inc.php#L15 and post HTTP response header and response (In Firebug or Chrome's Developer tool)

**Comment by PolarisPT** [comment]
@vgonzal

Ensure you have configured restya properly, pic attached (login with admin)

![image](https://cloud.githubusercontent.com/assets/17142000/13075739/67d9063e-d4a5-11e5-87d7-970ba6c0408f.png)

**Comment by vgonzal** [comment]
We have URL: http://restya.ono.es:9200/
Index: restya

**Comment by vgonzal** [comment]
Hi rrjanbiah.

After set the configuration of the elasticsearch I obtain the info for the new cards.

It's possible to force a new scan of all the cards?

Thx in advance.

**Comment by rrjanbiah** [comment]
@vgonzal Please execute `UPDATE settings SET value = 0 WHERE name = 'elasticsearch.last_processed_activtiy_id';`

**Comment by vgonzal** [comment]
Now works.

8-)

**Comment by rrjanbiah** [comment]
@vgonzal Nice to know that. Closing this for now. If you face any more issues, please feel free to reopen. Thanks
