### ISSUE TITLE
Make language selection more accessible

### ISSUE THREAD

**Issue by samtuke** [RestyaPlatform/board#2467]
First time user. Login to the demo at http://board.demo.restya.com. The interface language is the same as the country I'm currently in, which unfortunately I don't speak. Looking around the interface it's not clear how to change the language, including on this page: http://board.demo.restya.com/#/user/1/settings

Make the language setting easily accessible, as without this being correct, the rest of the UI is unintelligible.

Great that translations are already supported, by the way ;)

**Comment by rrjanbiah** [comment]
@samtuke Thanks a lot for your suggestion. We'll try to implement browser based language preference.

**Comment by rrjanbiah** [comment]
*Internal note*

Perhaps use below first time and store it in cookie?

`var lang = navigator.language || navigator.userLanguage;`
