### ISSUE TITLE
File not

### ISSUE THREAD

**Issue by baztedz16** [RestyaPlatform/board#2477]
## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
WIndows10
![a](https://user-images.githubusercontent.com/31683365/54167520-112d8800-44a5-11e9-97af-22e7e0b9b942.png)

* Link to your project:

**Comment by sridhar391** [comment]
@baztedz16 pleas set `R_DEBUG` as `true` on the `config.inc.php` file in `line 15` on `/www/html/restyaboard/server/php` path like https://github.com/RestyaPlatform/board/blob/dev/server/php/config.inc.php#L15 and copy the response of http://localhost/restyaboard/api/v1/oauth.json on the Network tab of Browser developer tools and paste it here.

**Comment by baskar383** [comment]
closing the issue, Due to inactivity.
