### ISSUE TITLE
New feature: Estimated time

### ISSUE THREAD

**Issue by dfragac** [RestyaPlatform/board#248]
In my team, we're interesting in use Restyaboard for our daily tasks. Our workflow requires to have easily located something like "estimated time to complete" on some tasks (That's how we can determine, at first, which ones we can prioritize, delegate, split, assign other team... etc). That's something like in GTD method "important", "urgent", "5 minutes"... to Get Things Done.

This is a screenshot of the suggestion:

![feature](https://cloud.githubusercontent.com/assets/13408072/13013163/91a055d4-d1ae-11e5-85bc-179fc855f525.jpg)

¿Is possible to add something like that or other approach you consider?

**Comment by rrjanbiah** [comment]
@dfragac Thanks for your wonderful suggestions. We'll see what we can do here

**Comment by ssivachidambaram** [comment]
Done.
