### ISSUE TITLE
Switching between card and list loses list title changes.

### ISSUE THREAD

**Issue by genie-nlu-shared** [RestyaPlatform/board#250]
Steps to reproduce:
1) Create a new board, choose ToDo template.
2) Change "Todo" title to "New This week" & Save
3) Change "Doing" title to "Ongoing" & Save
4) Click list view icon.
5) Click card view icon.

Result:
"New This week" has reverted back to "Todo" and "Ongoing" has reverted back to "Doing".

Expected:
Titles should have saved.

**Comment by arlorose** [comment]
Just noticed I was signed in via a work test account. Adding myself to the thread.

**Comment by rrjanbiah** [comment]
@genie-nlu-shared @arlorose Thanks a lot for your report. We'll fix it soon.

**Comment by rrjanbiah** [comment]
@srileka Need QA report for this issue

**Comment by ssivachidambaram** [comment]
Fixed.
