### ISSUE TITLE
List View Doesn't Show Anything

### ISSUE THREAD

**Issue by genie-nlu-shared** [RestyaPlatform/board#251]
Steps to Reproduce:
1) Create a new board, choose the ToDo template.
2) Add 2 cards each to the "Todo" and "Doing" list.
3) Switch to List view.

Result:
An empty list that says "No cards available."

Expected:
A list that contained headers and items for the lists and cards on my board.

**Comment by arlorose** [comment]
Just noticed I was signed in via a work test account. Adding myself to the thread.

**Comment by rrjanbiah** [comment]
@genie-nlu-shared @arlorose Thanks a lot for your report. We'll fix it soon.

**Comment by rrjanbiah** [comment]
@srileka Need QA report for this issue

**Comment by ssivachidambaram** [comment]
Fixed.
