### ISSUE TITLE
Blank page for the login page

### ISSUE THREAD

**Issue by IssueFindings** [RestyaPlatform/board#2522]
Hello,

I try to configure my local Restyaboard and I can't. I only have a blank page when I try to connect to the login page Restyaboard. I don't see any error message and I check logfile to understand why. I lose my patience with this issue. So I beg your help !!!

I don't know if my nginx code can help you. If yes, please find it below.
```
`server {
    listen 80;
    server_tokens off;
    server_name MyServer.com;

    location '/.well-known/acme-challenge' { 
        default_type "text/plain";
        root /var/www/restyaboard;
        }
    location '/' {
        return 301 https://MyServer.com$request_uri;
        }
    }

    server {
        listen 443;
        ssl on;

        ssl_protocols TLSv1.2;

        ssl_certificate      /fullchain.pem;
        ssl_certificate_key  /privkey.pem;

        ssl_session_cache none;
        ssl_session_tickets off;

        ssl_stapling on;
        resolver 80.67.169.12 valid=30s; 
        resolver_timeout 5s;
        ssl_stapling_verify on;
        ssl_trusted_certificate /chain.pem;  

        ssl_dhparam /dhparam4096.pem;

        ssl_prefer_server_ciphers on;
        ssl_ciphers '!kEECDH+ECDSA+AES128 kEECDH+ECDSA+AES256 !kEECDH+AES128 kEECDH+AES256 !kEDH+AES128 kEDH+AES256 +SHA !aNULL !eNULL !LOW !kECDH !DSS !MD5 !RC4 !EXP !PSK !SRP !CAMELLIA !SEED';

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"; 
        add_header Content-Security-Policy "default-src 'self' 'unsafe-eval'"; 
        add_header X-Frame-Options "DENY"; 
        add_header X-Xss-Protection "1; mode=block"; 
        add_header X-Content-Type-Options "nosniff"; 
        add_header 'Referrer-Policy' 'no-referrer'; 

        gzip on;
        gzip_disable "msie6";
        gzip_comp_level 6;
        # gzip_comp_level 9;
        gzip_min_length  1100;
        gzip_buffers 16 8k;
        gzip_proxied any;
        # gzip_http_version 1.1;
        gzip_types text/plain application/xml text/css text/js text/xml application/x-javascript text/javascript application/json application/xml+rss;

        server_name MyServer.com;
        server_tokens off;
        root /LocalRestyaboardDirectory;
        index index.html index.php;
        client_max_body_size 300M;

        rewrite ^/oauth/authorize$ /server/php/authorize.php last;
        rewrite ^/oauth_callback/([a-zA-Z0-9_\.]*)/([a-zA-Z0-9_\.]*)$ /server/php/oauth_callback.php?plugin=$1&code=$2 last;
        rewrite ^/download/([0-9]*)/([a-zA-Z0-9_\.]*)$ /server/php/download.php?id=$1&hash=$2 last;
        rewrite ^/ical/([0-9]*)/([0-9]*)/([a-z0-9]*).ics$ /server/php/ical.php?board_id=$1&user_id=$2&hash=$3 last;
        rewrite ^/api/(.*)$ /server/php/R/r.php?_url=$1&$args last;
        rewrite ^/api_explorer/api-docs/$ /client/api_explorer/api-docs/index.php last;

        location / {
                root /LocalRestyaboardDirectory/client;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"; 
        add_header Content-Security-Policy "default-src 'self' 'unsafe-eval'"; 
        add_header X-Frame-Options "DENY"; 
        add_header X-Xss-Protection "1; mode=block"; 
        add_header X-Content-Type-Options "nosniff"; 
        add_header 'Referrer-Policy' 'no-referrer'; 
        }

        location ~ \.php$ {
                try_files $uri =404;
                include fastcgi_params;
                fastcgi_pass    unix:/var/run/php/php7.0-fpm.sock;
                fastcgi_index   index.php;
                fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PHP_VALUE "upload_max_filesize=9G \n post_max_size=9G \n max_execution_time=200 \n max_input_time=200 \n memory_limit=256M ";
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"; 
        add_header Content-Security-Policy "default-src 'self' 'unsafe-eval'"; 
        add_header X-Frame-Options "DENY"; 
        add_header X-Xss-Protection "1; mode=block"; 
        add_header X-Content-Type-Options "nosniff";
        add_header 'Referrer-Policy' 'no-referrer'; 
        }

        location ~* \.(css|js|less|html|ttf|woff|jpg|jpeg|gif|png|bmp|ico|pdf|doc|docx|xls|xlx|txt|ppt|pptx|mp4|webm|mkv|wmv|avi|mp3) {
                root /LocalRestyaboardDirectory/client;
                if (-f $request_filename) {
                        break;
                }
                rewrite ^/img/([a-zA-Z_]*)/([a-zA-Z_]*)/([a-zA-Z0-9_\.]*)$ /server/php/image.php?size=$1&model=$2&filename=$3 last;
                add_header        Cache-Control public;
                add_header        Cache-Control must-revalidate;
                expires           7d;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"; 
        add_header Content-Security-Policy "default-src 'self' 'unsafe-eval'"; 
        add_header X-Frame-Options "DENY"; 
        add_header X-Xss-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";
        add_header 'Referrer-Policy' 'no-referrer'; 
        }
}
```

**Comment by sridhar391** [comment]
@IssueFindings we have checked your Restyaboard URL https://restyaboard.nolla.eu/ and it seems that the scripts are not loaded due to the below error 

`Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-/YaaZ69fuiEIuKIgrA7KM0ZZdmYJ/jF5qEzFgloZM5w='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.`

**Comment by IssueFindings** [comment]
Hello,

I change 4 times `add_header Content-Security-Policy "default-src 'self' 'unsafe-eval'";` to `add_header Content-Security-Policy "default-src 'self'";` but the login page is still blank. I understand that the issue is located around the add_header but I don't find where exactely. Especially regarding the CSP, I suppose that Restyaboard needs ressources outside my server. But which one ?

@sridhar391 : could you explain me where in the web console you find the error message because I try to find it but there is too many informations.
@sridhar391 : could you anonymise the URL above. Many thanks

**Comment by sridhar391** [comment]
@IssueFindings we have added the image with the error highlighted in the below image

![console_errors](https://user-images.githubusercontent.com/17172525/55888113-71ab0480-5bcc-11e9-8f64-4a152eb2945e.png)

**Comment by IssueFindings** [comment]
Hello,
Based on your answer, I find the solution. To work with a CSP header, it's necessary to use this code : add_header Content-Security-Policy "default-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com";

@sridhar391 why it's necessary to use eval ? It's not very secure, is it ? In a next version, that could disapear ?

Many thanks.

**Comment by IssueFindings** [comment]
Hello,
With the v0.6.7 I understand that some improvements arrived regarding dependencies. So for the CSP header, what I can simplify (you still need googleapis or fonts.gstatic ?)
Have a nice day.

**Comment by rrjanbiah** [comment]
@IssueFindings Can you please let us know from where did you copy your initial nginx conf and what was the intention behind?

**Comment by IssueFindings** [comment]
Hello, I created it myself based on my own experience. The target is to get a grade level A+ on this website securityheaders.com/ At the moment, I get only a grade level A with my nginx conf but I continue to improve it when I have time.
Have a nice day.

**Comment by sridhar391** [comment]
@IssueFindings Can you please attach us your Restyaboard configuration file

**Comment by sridhar391** [comment]
Closing the issue, due to inactivity.
