### ISSUE TITLE
Problems with Organization

### ISSUE THREAD

**Issue by ricardomartinez28** [RestyaPlatform/board#2523]
Hi, I installed RestyaBoard on a Ubuntu server and everything its fine except the organization part because i can create one organization but i cant edit anything about it including the members adding and removing. I saw in the features part of the website and the thing is that these buttons don't appear either in the top right part when you are in a table,  I cant see the organization control buttons. When i go to the organization tab and i  click in an organization name,  it opens another page but its empty.
I tried to change from owner to editor but it doesn't work

**Comment by dernicc** [comment]
Same here

**Comment by dernicc** [comment]
For me it worked to run the following commandes in the postgres container:
```
wget https://raw.githubusercontent.com/RestyaPlatform/board/dev/sql/upgrade-0.6.5-0.6.6.sql
psql -h postgres -d restyaboard -U admin -W < "upgrade-0.6.5-0.6.6.sql"
```

And then the same for the update from 0.6.6 to 0.6.7.

Not sure if the last one is necessary.

**Comment by ricardomartinez28** [comment]
Thank you very much for your patience , it worked!
