### ISSUE TITLE
Logfile to check error login

### ISSUE THREAD

**Issue by IssueFindings** [RestyaPlatform/board#2524]
Hello,

In which restyaboard logfile I can see the error message when someone try to login with an error regarding password or Id ? Especially, what is the structure of this error message with the IP address ?

Have a nice day.

**Comment by sridhar391** [comment]
@IssueFindings sorry, there is no log file for Restyaboard login attempt but we have added the users login page in the admin panel, which will show the login attempts by the users with success or failure Login status in the upcoming Restyaboard Boney M (v0.6.7) version

**Comment by IssueFindings** [comment]
Hello, I successfully install the v0.6.7. Many thanks for this upgrade !!! Now where I can find the logfile in my system ?
Have a nice day.

**Comment by sridhar391** [comment]
@IssueFindings We have added the Users Logins page in the admin panel, which will show the login attempts by the users with success or failure Login status and the IP address from which they tried to log in the Restyaboard like the below image

![Restyaboard   Users Logins](https://user-images.githubusercontent.com/17172525/57057368-c02c5a00-6cc5-11e9-9207-77a3ea417ccf.png)

**Comment by IssueFindings** [comment]
Hello, many thanks for this new function. Could you specify me the log file access (in the system) to use it with fail2ban.
Have a nice day.
