### ISSUE TITLE
Change language to Vietnamese Can't view and edit my card.

### ISSUE THREAD

**Issue by thangnguyenn** [RestyaPlatform/board#2528]
Hello
I have a problem when I switch to Vietnamese language. My card cannot view and edit. 
![1](https://user-images.githubusercontent.com/26301164/56254903-dabeda80-60ec-11e9-91fa-b046dfdab505.PNG)

**Comment by sridhar391** [comment]
We have fixed this issue in the dev server in the commit https://github.com/RestyaPlatform/board/commit/2bb6fdb9a786516d4536acec465a5a0aa59b92a0 and it will be available in the upcoming Restyaboard Boney M(v0.6.7) version
