### ISSUE TITLE
Unable to selecting board in "Instant add card"

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2542]
## Expected Behavior

Select board option, should be working fine in instant add card

## Current Behavior

Unable to selecting board in "Instant add card"

## Screenshots (if appropriate):

![Instant add card_ board](https://user-images.githubusercontent.com/14290356/56203995-0d70c080-6064-11e9-9ad5-2fed42d363b0.png)

## Steps to Reproduce (for bugs)

1. Login as aisha/agriya
2. Go to board.
3. Go to instant add card.
4. Unable to selecting board in "Instant add card"

**Comment by baskar383** [comment]
Above issue fixed in the local app
