### ISSUE TITLE
Comment - Deleted cards displayed in add card

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2548]
## Expected Behavior
Comment - Deleted cards should not be displayed in add card

## Current Behavior

Comment - Deleted cards displayed in add card

## Screenshots (if appropriate):

![Deleted card](https://user-images.githubusercontent.com/14290356/56287216-62cad180-6139-11e9-862b-948bb704304f.png)

## Steps to Reproduce (for bugs)

1. Login as aisha/agriya.
2. Go to board.
3. Open the card and go to comment.
4. Comment - add card - deleted cards are displayed.

**Comment by baskar383** [comment]
Above issue fixed in the local app.
