### ISSUE TITLE
Cannot able to import users from Trello

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#2564]
## Expected Behavior
Import trello board members into Restyaboard using the JSON file 

## Current Behavior
Cannnot able to import board members into Restyaboard

## Context
Cannot able to import users from Trello

## Your Environment
* Version used:
* Operating System and version (desktop or mobile): Ubuntu
* Link to your project:

**Comment by rrjanbiah** [comment]
*Internal note*

Regression due to #2226 because of `UNIQUE index` on email

For a quick fix, we may create dummy email using `trello-username@mailinator.com`

Probably, in future, we may prompt with a data grid for admins to enter email address

**Comment by rrjanbiah** [comment]
Reopening so that related documentations in modal dialog and install page won't be missed
