### ISSUE TITLE
Productivity beat for v0.6.8 (Roxette)

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#2575]
"Roxette - Listen To Your Heart" ABC notation [Roxette-Listen_To_Your_Heart.abc.txt](https://github.com/RestyaPlatform/board/files/3128210/Roxette-Listen_To_Your_Heart.abc.txt)

*Internal note*

**Creating ABC notation from MuseScore MusicXML**

1. Downloading MuseScore MusicXML will download a file with `.mxl`. Had to rename it to `.zip`. Extracting it will have `.xml` file
2. Pasted XML content in https://www.mandolintab.net/abcconverter.php to convert it to ABC notation.

Note: Another MusicXML to ABC notation converter is https://wim.vree.org/js/xml2abc-js.html

**Comment by sridhar391** [comment]
@rrjanbiah We have added the changes for the adding productivity beats for v0.6.8 (Roxette) in the local commit
