### ISSUE TITLE
Cannot login after migrating and updating restyaboard

### ISSUE THREAD

**Issue by Richigeht** [RestyaPlatform/board#2577]
## Expected Behavior
Hi,
I expect to enter my password and then be able to log into the application however it just loads - no errors in the logs. 

## Current Behavior
Site is just loading (you see it in the top, that it tries to do something) and in the logs you see that some activity is happening. However nothing in the error log file.
I checked that the postgres User has permissions and like a change of a password is working without issues.
I made a new user however could not find him in the user table? Maybe because the initial logging doesn't work? 

`xx.xx.xxx.xx - - [02/May/2019:00:23:45 +0200] "GET /api/v1/settings.json?token=892e06c3644e7dd8bbc62c32903a665a8cace091&_=1556749425648 HTTP/1.1" 200 256 "http://URL.COM:808/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
xx.xx.xxx.xx - - [02/May/2019:00:23:45 +0200] "PUT /api/v1/users/21/activation.json?token=892e06c3644e7dd8bbc62c32903a665a8cace091 HTTP/1.1" 200 102 "http://URL.COM:808/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
xx.xx.xxx.xx - - [02/May/2019:00:23:49 +0200] "POST /api/v1/users/login.json?token=892e06c3644e7dd8bbc62c32903a665a8cace091 HTTP/1.1" 200 1022 "http://URL.COM:808/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
`

I also thought first it's an issue of my PHP7.2 FPM configuration but putting a phpinfo.php in the main folder of the restyaboard does work fine and the site is loading all details from php. 

I also used the diagnostics.php to check if the folder permissons are ok etc. and all is green; besides IMAP and ImageMagick is orange with value "ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org"

Anybody an idea what I could have forgotten? I also have a new URL (until I migrate) however in the site_url_for_shell.php everything is OK. 

Also since the password reset worked, the DB connection must be fine - because I don't get a login error anymore. 

I have originally copied over the config.inc.php but even using a new one and just adjusting DB settings and making sure the salt values are similar, it does not work... 

Also if I directly restore the database, the first thing I notice: my Passowrd is not accepted and I need to reset it! Could be related?!

Really would be great if somebody has a saving idea! Thanks. 

## Your Environment

* Version used: 0.6.7
* Environment name and version (e.g. OS, PHP, PostgreSQL): postgreSQL 11.2, Ubuntu 18.4, PHP FPM 7.2, Nginx latest version
* Operating System and version (desktop or mobile): Windows 10 Desktop with Chrome Stable 73int (just doing an update and try again indeed)
* Link to your project:

**Comment by sridhar391** [comment]
@Richigeht can you please send us the mail at info@restya.com and we will arrange the zoom screen share meeting in your convenient time to understand and solve the problem?

**Comment by Richigeht** [comment]
Thanks, I have send you a mail.

**Comment by sridhar391** [comment]
@Richigeht The issue has been fixed and it seems to be the database has been overwritten more than once and we have fixed the problem.

**Comment by Richigeht** [comment]
Support helped me here - solved now. Thank you.
