### ISSUE TITLE
Title & heading not changing based on the view of board page and Gantt page not loaded properly while clicking browser back navigation.

### ISSUE THREAD

**Issue by baskar383** [RestyaPlatform/board#2578]
- [X] Title and heading remain the same while moving from grid view to any other view in the board view page.
- [X] In Gantt and Insight board view page, while viewing the page as tab view,  URL  and title of the page not changing based on the Tab.
- [X] While going back with the browser navigation, Gantt and Insights page not loaded properly,

**Comment by rrjanbiah** [comment]
Please explain/rephrase the issue clearly
