### ISSUE TITLE
Invalid barcode token for two factor auth

### ISSUE THREAD

**Issue by Richigeht** [RestyaPlatform/board#2597]
Hi,
I try to add two factor auth however then I scan the barcode in Google Auth I get an error.

## Expected Behavior

I expect to be able to scan the barcode and enable two factor auth. 
## Current Behavior

I get an error, that the barcode would be invalid for the authentication in Googe.
## Screenshots (if appropriate):
It says
"otpauth://totp/User Name(username@mail.com)?secret=XXXXXX is not valid. 
## Possible Solution

This was working in 0.6.6.
## Steps to Reproduce (for bugs)

1. Go to Profile.
2. Click on enable two factor auth.
3. Scan barcode with smartphone.
4.

## Your Environment

* Version used: 0.6.7
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile): iOS Google Auth
* Link to your project:

**Comment by sridhar391** [comment]
@Richigeht Can you please tell us your Phone model name and Phone OS name and version

**Comment by Richigeht** [comment]
Hi
Using iPhone XS Max, iOS 12.3. 

However another colleague had issues with I believe Android as well. He has it setup already but if he enters the code it states that the code would be wrong. 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by rrjanbiah** [comment]
*Internal note*

Check if we broke any timezone or time related things... as Google Authenticator seems to be time based

**Comment by sridhar391** [comment]
@Richigeht Please download the file from the commit https://github.com/RestyaPlatform/board/commit/80cb708c639458f7d113d94060421d25f750d159 and paste it in the `/usr/share/nginx/html/restyaboard/server/php/libs/vendors` folder and please tell us if the issue is fixed

**Comment by Richigeht** [comment]
Hi,
well it allows to register the application however if I then try to login with one of those codes it does not work and it states the code would be wrong.

**Comment by sridhar391** [comment]
@Richigeht Can you please tell us the user time zone in the Restyaboard and your current timezone

**Comment by Richigeht** [comment]
Hi
Both should be CEST. So GTM+2 I believe. Based in Germany. 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by sridhar391** [comment]
@Richigeht Can you please tell us the Site Timezone you have configured in the Restyaboard site and the Timezone you have configured for the user in the Restyaboard user profile settings page

**Comment by Richigeht** [comment]
Hi, The website has GTM+2 and the server is running in the same time zone. 

Also I could add the Two Factor Auth successfully, just the reevaluation does not seem to work for some reason.

**Comment by sridhar391** [comment]
@Richigeht We are not able to reproduce this issue and shall we have a zoom screen share meeting to understand and solve the problem?

**Comment by rrjanbiah** [comment]
@Richigeht Or, can you please let us know:

1. Are you really sure that it was working in previous version? (with same username, etc)
2. Can you please explain, what do you mean by "reevaluation"?

**Comment by Richigeht** [comment]
Hi,
One person was using it before with success.

Well, I can sign up for two factor auth with my phone and my PC but then I login in another browser session, the barcode is not accepted anymore.

If you wish we could have a Zoom session.

**Comment by sridhar391** [comment]
@Richigeht can you please mail us at info@restya.com with your convenient time for the zoom meeting.

**Comment by Richigeht** [comment]
Hi,
will do so, thank you.

**Comment by sridhar391** [comment]
@Richigeht The issue has been fixed.
