### ISSUE TITLE
Update from v0.6.6 to v0.6.7: Missing files

### ISSUE THREAD

**Issue by CodexAnima** [RestyaPlatform/board#2607]
Trying to update v0.6.6 to v0.6.7 (overwrite app data and run upgrade-sql), the files "...restyaboard/client/css/bootstrap.css" and "...restyaboard/client/js/templates/template.js" are missing. They were not present in v0.6.6 and even not in the v0.6.7 files.

## Expected Behavior
Restyaboard is up and running on v0.6.7, yay!

## Current Behavior
Page shows blank with Restyaboard link on top left. Favicon is showing right, settings.json just contains a warning about array_merge(). client/css/bootstrap.css and client/js/templates/template.js missing.

## Possible Solution
Add the two missing files to the v0.6.7 data.

## Steps to Reproduce (for bugs)
1. Install v0.6.6 (is up and running fine)
2. Download v0.6.7 from latest release
3. Copy files from v0.6.7 over v0.6.6
4. Apply /sql/upgrade-0.6.6-0.6.7.sql to PostgreSQL (updating DB runs fine)

## Your Environment
* Version used: initial v0.6.6 (installed with installation batch file)
* Environment (Ubuntu 18.04 LTS, PHP 7.3 FPM, PostgreSQL):

**Comment by ssivachidambaram** [comment]
@CodexAnima It looks you have updated the source files from GitHub. Can you please download the deployable files and update? Please refer https://github.com/RestyaPlatform/board/releases & https://github.com/RestyaPlatform/board/releases/download/v0.6.7/board-v0.6.7.zip.

**Comment by CodexAnima** [comment]
> @CodexAnima It looks you have updated the source files from GitHub. Can you please download the deployable files and update? Please refer https://github.com/RestyaPlatform/board/releases & https://github.com/RestyaPlatform/board/releases/download/v0.6.7/board-v0.6.7.zip.

Hey there :)
I did download and extract the file, but inside the folder structure are no "board-v0.6.7/client/css/bootstrap.css" and "board-v0.6.7/client/js/templates/template.js".

So if I overwrite my v0.6.6 with this and run the "../sql/upgrade-0.6.6-0.6.7.sql", this two files are still missing.

Even in v0.6.6 they are not present, so I think they are new in v0.6.7 ?

**Comment by ssivachidambaram** [comment]
@CodexAnima Actually those source files are not needed for server. In deploy files, all source files are merged into `board-v0.6.7/client/js/default.cache.8d3b5ded.js` and `board-v0.6.7/client/css/default.cache.223ad2be.css`. Can you please compare `board-v0.6.7/client/index.html` file with your server file?

**Comment by CodexAnima** [comment]
Yes that was my mistake using the source files instead of the deployed ones.
Thanks a lot :)

**Comment by ssivachidambaram** [comment]
@CodexAnima Thanks for your confirmation.
