### ISSUE TITLE
Uploading PDF Files in v.0.6.7 showing after board refresh

### ISSUE THREAD

**Issue by CodexAnima** [RestyaPlatform/board#2609]
Hey there Restya team,

if I attach a pdf-file, the loading indicator starts whiggling but nothing more happens. No visible "upload complete" state like attaching an image.

After a few seconds I need to refresh the browser tab and then the attached pdf-file is visible in the board.

## Expected Behavior
Attaching a pdf-file works exactly like attaching an image.

## Current Behavior
Attaching a pdf-file gives no visible feedback but a console error. After refreshing the browser tab the file is visible attached to the board

## Screenshots (if appropriate):
![pdf_upload_chrome_console](https://user-images.githubusercontent.com/32327232/57763990-d6dda280-7702-11e9-9191-8ae913a457ec.png)

## Possible Solution
Don't know here...

## Steps to Reproduce (for bugs)
1. Attach pdf-file (4 MB of size here) to board.
2. See upload indicator in boards top right whiggling.
3. Waiting... Nothing more happens. 
4. Wait a few seconds more, then refresh browser tab and attached pdf-file is displayed.

## Context
My users are trying to attach pdf-files to the board.
They may think the attachment process did crash.
When they just wait, they wait for a loooong time.

## Your Environment
* Version used: v0.6.7 (Boney M)
* Environment name and version: Ubuntu 18.04 LTS, PHP 7.3 FPM, PostgreSQL

**Comment by ssivachidambaram** [comment]
@CodexAnima Can you please copy & paste the error log from `/var/log/nginx/error.log`?

**Comment by baskar383** [comment]
@CodexAnima  We have tried to reproduce this issue in our local and demo, but its not reproduced. Kindly copy & paste the error log from `/var/log/nginx/error.log`. Its help us to sort out the issue.

**Comment by CodexAnima** [comment]
Hey there, sorry for the delay.
error.log point out this:

> [error] 1906#1906: *22505 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught ImagickException: not authorized `/var/www/html/restyaboard/media/Card/234/testfile.pdf` @ error/constitute.c/ReadImage/412 in /var/www/html/restyaboard/server/php/R/r.php:4815
>
> Stack trace:
> 0 /var/www/html/restyaboard/server/php/R/r.php(4815): Imagick->__construct('/var/www/html/r...')
> 1 /var/www/html/restyaboard/server/php/bootstrap.php(132): r_post('/boards/?/lists...', Array, Array, Array)
> 2 /var/www/html/restyaboard/server/php/R/r.php(7276): main()
> 3 {main}
>
> thrown in /var/www/html/restyaboard/server/php/R/r.php on line 4815" while reading response header from upstream, client: ..., server: ..., request: "POST /api/v1/boards/14/lists/260/cards/234/attachments.json?token=... HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "...", referrer: "https://..."

**Comment by baskar383** [comment]
@CodexAnima  no problem, Need to give read permission for the ImageMagick in the file of /etc/ImageMagick-6/policy.xml.
In /etc/ImageMagick-6/policy.xml (or /etc/ImageMagick/policy.xml) find the following line

```<policy domain="coder" rights="none" pattern="PDF" />```

and change it like below

```<policy domain="coder" rights="read" pattern="PDF" />```

then, restart the php7.2-fpm in the terminal using this cmd ```sudo service php7.2-fpm restart```. then check it. Kindly refer the below URL for your reference 
https://alexvanderbist.com/posts/2018/fixing-imagick-error-unauthorized

**Comment by CodexAnima** [comment]
@baskar383 You did right, dear Sir!

After changing it from "none" to "read", the PDF files are processed as expected.
Thank you very much.

**Comment by erl4nc** [comment]
Please consider adding this to installation or configuration instructions since more than 1 people are arriving at this issue.

**Comment by baskar383** [comment]
@erl4nc 
While Restyaboard installation using the install script file, we will change the permission to read the PDF file of ImageMagick.
