### ISSUE TITLE
Card checklist action needs better responsiveness

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#2618]
## Expected Behavior

Checklist actions are butter smooth

## Current Behavior

Slightly slow responsiveness (random behavior)

**Comment by sridhar391** [comment]
@rrjanbiah The issue has been fixed in the commit https://github.com/RestyaPlatform/board/pull/2625/commits/c9908c5310b5c1fe610cebd14fa60f50b67fa6fe
