### ISSUE TITLE
First install PHP warning "relation settings does not exist"

### ISSUE THREAD

**Issue by romain-malet** [RestyaPlatform/board#262]
I install with restyaboard.sh and run it on apache server, I've got a blank page. 
the error log content:

PHP Warning:  pg_query_params(): Query failed: ERROR:  relation &quot;settings&quot; does not exist
LINE 1: SELECT name, value FROM settings WHERE setting_category_id i... in /var/www/html/restyaboard/server/php/R/config.inc.php on line 45
PHP Warning:  pg_fetch_assoc() expects parameter 1 to be resource, boolean given in /var/www/html/restyaboard/server/php/R/config.inc.php on line 46
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42P01]: **Undefined table**: 7 ERROR:  relation "oauth_clients" does not exist
LINE 1: SELECT * from oauth_clients where client_id = $1 in /var/www/html/restyaboard/server/php/R/libs/vendors/OAuth2/Storage/Pdo.php:96
Stack trace:
#0 /var/www/html/restyaboard/server/php/R/libs/vendors/OAuth2/Storage/Pdo.php(96): PDOStatement->execute(Array)
#1 /var/www/html/restyaboard/server/php/R/libs/vendors/OAuth2/Storage/Pdo.php(115): OAuth2\\Storage\\Pdo->getClientDetails('774263250138231...')
#2 /var/www/html/restyaboard/server/php/R/libs/vendors/OAuth2/Controller/TokenController.php(142): OAuth2\\Storage\\Pdo->checkRestrictedGrantType('774263250138231...', 'client_credenti...')
#3 /var/www/html/restyaboard/server/php/R/libs/vendors/OAuth2/Controller/TokenController.php(49): OAuth2\\Controller\\TokenController->grantAccessToken(Object(OAuth2\\Request), Object(OAuth2\\Response))
#4 /var/www/html/restyaboard/server/php/R/libs/vendors/OAuth2/Server.php(2 in /var/www/html/restyaboard/server/php/R/libs/vendors/OAuth2/Storage/Pdo.php on line 9

I try to delete the database and re-run manually the empty script sql but same error.

EDIT
When I run restyaboard.sh: 
++ psql -U postgres -c '\q'
psql: FATAL:  Peer authentication failed for user "postgres"
++ sleep 1
++ echo 'Creating PostgreSQL user and database...'
Creating PostgreSQL user and database...
++ psql -U postgres -c 'CREATE USER user WITH ENCRYPTED PASSWORD '\''password'\'''
psql: FATAL:  Peer authentication failed for user "postgres"
++ psql -U postgres -c 'CREATE DATABASE database OWNER user ENCODING '\''UTF8'\'' TEMPLATE template0'
psql: FATAL:  Peer authentication failed for user "postgres"

**Comment by rrjanbiah** [comment]
@romain-malet Thanks for reporting this issue.

Looks like your postgresql setup is differently configured already (?)

Please attach install log file that will help us to understand the issue much better.

**Comment by romain-malet** [comment]
My postgres installation is very basic one, I just edit the listening port.
I see in the log some problem with php-fpm: 
++ sed -i -e 's/date.timezone/;date.timezone/g' /etc/php5/fpm/php.ini
sed: can't read /etc/php5/fpm/php.ini: No such file or directory
++ echo 'date.timezone = Europe/Paris'
./restyaboard.sh: line 194: /etc/php5/fpm/php.ini: No such file or directory

and in the end
++ service php5-fpm restart
Failed to restart php5-fpm.service: Unit php5-fpm.service failed to load: No such file or directory.

[restya-install.txt](https://github.com/RestyaPlatform/board/files/131124/restya-install.txt)

**Comment by rrjanbiah** [comment]
@romain-malet Thanks for attaching log file. We'll look into it and revert soon.

**Comment by ssivachidambaram** [comment]
@romain-malet 

Can you please check the database user has privileges for the restyaboard database?

To grant privileges to database,
`GRANT ALL PRIVILEGES ON DATABASE restyaboard TO restya;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO restya;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO restya;`

**Comment by romain-malet** [comment]
Thanks, 
I just try it but nothing has changed.

**Comment by rrjanbiah** [comment]
@romain-malet In our understanding it is more of a privilege issue as mentioned in http://dba.stackexchange.com/questions/101570/error-42p01-relation-does-not-exist

Probably, you may:
1. Recreate DB
2. Browse through postgresql GUI tools to understand permission

**Comment by rrjanbiah** [comment]
@romain-malet Were you able to figure it out?

**Comment by romain-malet** [comment]
Ok, I delete postgresql and re-run restyaboard.sh.
It's working now! 
Thanks

**Comment by rrjanbiah** [comment]
@romain-malet Thanks for your update. That's nice to know.

Closing this now. If you get any more issues, please feel free to reopen.
