### ISSUE TITLE
Cannot read property 'statusText' of null

### ISSUE THREAD

**Issue by Mattes1000** [RestyaPlatform/board#2628]
Hi,

when I click on an organisation I got the following URL:
[restya]/#/organization/3

I got the following error:
`default.cache.8d3b5ded.js:formatted:82509 Uncaught TypeError: Cannot read property 'statusText' of null
    at hasOfflineStatusCode (default.cache.8d3b5ded.js:formatted:82509)
    at default.cache.8d3b5ded.js:formatted:82524
    at Object.d.success (default.cache.8d3b5ded.js:formatted:14852)
    at l (default.cache.8d3b5ded.js:formatted:1104)
    at Object.fireWith [as resolveWith] (default.cache.8d3b5ded.js:formatted:1159)
    at d (default.cache.8d3b5ded.js:formatted:3927)
    at XMLHttpRequest.d (default.cache.8d3b5ded.js:formatted:4186)`

The compressed code is:
return b = Backbone.DualStorage.offlineStatusCodes,
    _.isFunction(b) && (b = b(a)),
    "abort" === a.statusText ? !1 : _.isUndefined(a) || 0 === a.status || (c = a.status,
    d.call(b, c) >= 0)

Version is:  0.6.7

**Comment by sridhar391** [comment]
@Mattes1000 can you please mail your convenient time to schedule a meeting at info@restya.com to understand and solve the problem.

**Comment by sridhar391** [comment]
@Mattes1000 The Upgrade SQL file [upgrade-0.6.6-0.6.7.sql](https://raw.githubusercontent.com/RestyaPlatform/board/dev/sql/upgrade-0.6.6-0.6.7.sql) hasn't been executed during the update to the latest version v0.6.7 (Boney M)

**Comment by virtualcharlotte** [comment]
I'm also having this issue, running the upgrade sql file just completely destroys my install though

**Comment by sridhar391** [comment]
@virtualcharlotte Can you please attach the `restyaboard_install.log` file for solving the issue

**Comment by baskar383** [comment]
@virtualcharlotte Can you please attach the restyaboard_install.log file for solving the issue, the above issue is not reproduced our side.

**Comment by baskar383** [comment]
Due to inactivity, we are closing this issue
