### ISSUE TITLE
Cannot able to logout in MyRestyaboard iOS app

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#2650]
## Expected Behavior
After pressing the `logout` button in the Restyaboard, the user should be logged out

## Current Behavior
After pressing the `logout` button in the Restyaboard, the user is not logged out

## Steps to Reproduce (for bugs)
1. Login in Restyaboard 
2. Click `Logout`

## Your Environment
* Version used: MyRestyaboard iOS app v1.7

**Comment by baskar383** [comment]
Logout in MyRestyaboard iOS app issue fixed. Fixed changes are Available on the store. Kindly re-install and check it
