### ISSUE TITLE
While move or copy card to another board, the custom fields are not copied along with card

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#2651]
## Context
While move or copy card to another board, the custom fields are not copied along with card

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by srileka** [comment]
Issue not fixed

**Comment by sridhar391** [comment]
@srileka We are closing this issue as we are not able to reproduce the issue and feel free to reopen the issue if it occured again
