### ISSUE TITLE
How to see "list" in mail notification

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#2690]
Is it possible to see list of card int mail notification.

Actually we see the card and board but can we add list ?

Regards

Alban

**Comment by sridhar391** [comment]
@morphos88 Can you please tell us if you want to see the list of cards with activity in the one email notification

**Comment by morphos88** [comment]
When i comment card users receive mail with the comment, the name of card and the board but we don't see list who card is member.
![image](https://user-images.githubusercontent.com/25505555/60441577-8faa6300-9c17-11e9-927e-9f1155475d2e.png)

**Comment by sridhar391** [comment]
@morphos88 We have the same email notifications context as trello and can you please tell us how to show the list name in which format?

**Comment by morphos88** [comment]
Like this : 

![image](https://user-images.githubusercontent.com/25505555/60499689-44489100-9cb9-11e9-92aa-ef61529abc71.png)

**Comment by sridhar391** [comment]
@morphos88 We will discuss it in the team and update you as soon as possible
