### ISSUE TITLE
Failed to create index when upgrading to 0.6.7

### ISSUE THREAD

**Issue by pinkunicorn** [RestyaPlatform/board#2694]
## Expected Behavior
Clean upgrade.

## Current Behavior
Error message when upgrading the database.

I just performed an upgrade to 0.6.7 of my restyaboard server. When running the database update scripts (I was on 0.6.4 when I started, so two of them), I got an error message when running the last one:

> # /usr/bin/psql -d restyaboard -U restya -f /srv/html/sql/upgrade-0.6.6-0.6.7.sql 
[...]
> psql:/srv/html/sql/upgrade-0.6.6-0.6.7.sql:52: ERROR:  could not create unique index "users_unique_lower_email_idx"
> DETAIL:  Key (lower(email::text))=() is duplicated.

I assume that it's not really a big deal for me to be missing an index (at least as my database is small, as I expect it to be), but it seems to me that me getting this error to begin with indicates that there is some problem with the logic that has allowed me to get into this situation to begin with.

(If it is vital for me to have this index, let me know how to create it now, after the upgrade process.)

## Your Environment
* Version used: Upgrade from 0.6.4 to 0.6.7
* Environment name and version (e.g. OS, PHP, PostgreSQL): CentOS 7, postgresql 9.6.14

**Comment by sridhar391** [comment]
@pinkunicorn There are two users with the same email address in your Restyaboard and that's why it's throwing the error, please change the email of one user and execute the SQL command and please tell us if the issue is fixed after following the above steps

**Comment by pinkunicorn** [comment]
Do you mean to rerun the entire upgrade script for 0.6.7, or just some part of it?

**Comment by sridhar391** [comment]
@pinkunicorn Please rerun the upgrade SQL command from the line https://github.com/RestyaPlatform/board/blob/dev/sql/upgrade-0.6.6-0.6.7.sql#L52

**Comment by pinkunicorn** [comment]
The only instances I can see of users that have the same email address is for users that have no email address at all, after being created by imports from Trello. Do I need to manually go through all those and invent mail addresses for them (some are real users but some are previous employees that don't have a useful email address with us). If there needs to be a unique email address for all users going forward, how does that play along with the Trello import that doesn't seem to add one?

**Comment by sridhar391** [comment]
@pinkunicorn you have to add the email address to the users with no email and for trello import, we have added the fix in the commit https://github.com/RestyaPlatform/board/commit/83243a8cba4c9a76aa547351f61edf84962741f2

**Comment by pinkunicorn** [comment]
For the record, my immediate problem with this bug is solved by adding email addresses to all users (but #2709 is still relevant). 

Ideally, the upgrade script should verify that the database to be upgraded does not contain duplicate email addresses before trying to initiate an upgrade and otherwise provide an instructive error message and refuse to start the upgrade.

**Comment by baskar383** [comment]
@pinkunicorn 
While upgrading to version 0.6.7, We have added an instructive error message.
