### ISSUE TITLE
Missing an avatar picture

### ISSUE THREAD

**Issue by mzch** [RestyaPlatform/board#2714]
## Expected Behavior

When uploading an avatar picture, it will be immediately shown.
## Current Behavior

Browken.

## Possible Solution

Uploading an avatar file to media/User directory successfully, so I think it's good to move or convert it into client/img/micro_thumb/User.

## Steps to Reproduce (for bugs)

1. select or drag & drop an avatar image onto pict area in setting.
2.
3.
4.

## Your Environment

* Version used: v0.6.7
* Environment name and version (e.g. OS, PHP, PostgreSQL):Debian 10 (buster), php 7.3, PostgreSQL 11
* Operating System and version (desktop or mobile):macOS 10.14 Mojave, Google Chrome 75
* Link to your project: https://detailedtask.com/

**Comment by sridhar391** [comment]
@mzch Can you please tell us if you have given the read permission to the `/usr/share/nginx/html/restyaboard/media` folder and `/usr/share/nginx/html/restyaboard/client/img` folder

**Comment by mzch** [comment]
Yes, www-data user, who runs php, has both folders and read/write permissions. 

#### media/
```
合計 84
drwxr-xr-x  7 www-data www-data  4096  7月 11 06:03 .
drwxr-xr-x 26 root     root      4096  7月 11 08:30 ..
-rw-r--r--  1 www-data www-data  1295  7月 11 04:40 .htaccess
drwx------  8 www-data www-data  4096  5月 10 13:40 client
-rw-rw-r--  1 www-data www-data 17357  4月 24 20:06 diagnose.php
-rw-rw-r--  1 www-data www-data 22561  4月 24 20:06 ejabberd.yml
drwx------  3 www-data www-data  4096  5月 10 13:40 media
-rw-rw-r--  1 www-data www-data   674  4月 24 20:06 restyaboard-ssl.conf
-rw-r--r--  1 www-data www-data  1846  1月 22 11:21 restyaboard.conf
drwx------  3 www-data www-data  4096  5月 10 13:40 server
drwx------  2 www-data www-data  4096  5月 10 13:40 sql
drwx------  3 www-data www-data  4096  5月 10 13:40 tmp
```

#### client/img
```
drwx------  8 www-data www-data  4096  5月 10 13:40 .
drwxr-xr-x  7 www-data www-data  4096  7月 11 06:03 ..
drwx------  7 www-data www-data  4096  5月 10 13:40 api_explorer
-rw-rw-r--  1 www-data www-data  2555  4月 24 20:06 apple-touch-icon-114x114.png
-rw-rw-r--  1 www-data www-data  1734  4月 24 20:06 apple-touch-icon-72x72.png
-rw-rw-r--  1 www-data www-data  1226  4月 24 20:06 apple-touch-icon.png
drwx------  2 www-data www-data  4096  5月 10 13:40 css
-rw-rw-r--  1 www-data www-data  1149  4月 24 20:06 default.appcache
-rw-rw-r--  1 www-data www-data 32988  4月 24 20:06 favicon.ico
drwx------  2 www-data www-data  4096  5月 10 13:40 font
drwx------  4 www-data www-data  4096  7月 11 06:03 img
-rw-rw-r--  1 www-data www-data  2362  4月 24 20:06 index.html
drwx------  3 www-data www-data  4096  5月 10 13:40 js
drwx------ 37 www-data www-data  4096  5月 10 13:40 locales
-rw-rw-r--  1 www-data www-data   369  4月 24 20:06 manifest.json
```

**Comment by sridhar391** [comment]
@mzch Can you please set `R_DEBUG` as `true` on the `config.inc.php` file in `line 15` on `/usr/share/nginx/html/restyaboard/server/php` path like https://github.com/RestyaPlatform/board/blob/dev/server/php/config.inc.php#L15 and copy the response of https://detailedtask.com/api/v1/users/<user_id>.json on the Network tab of Browser developer tools while uploading the user profile picture and paste the response here or copy the contents from your server error log and paste it here.

**Comment by mzch** [comment]
<img width="1551" alt="ScreenShot 2019-07-11 15 01 06" src="https://user-images.githubusercontent.com/621178/61025862-f0425880-a3ec-11e9-9e9a-60b4bf2774ae.png">

mm...GET https://detailedtask.com/api/v1/users/1.json returns status 401...

**Comment by sridhar391** [comment]
@mzch Please mail us your available time to info@restya.com for zoom screen share meeting to understand and solve the problem

**Comment by mzch** [comment]
OK. I'll mail you.

**Comment by sridhar391** [comment]
Fixed the issue in the zoom screen share meeting.
