### ISSUE TITLE
Failed upgarde

### ISSUE THREAD

**Issue by ludovic-durand** [RestyaPlatform/board#2715]
## Current Behavior

After doing the upgrade, there is no more HTML pages loaded:

https://projets.djaseo.com/

## Steps to Reproduce (for bugs)

wget https://github.com/RestyaPlatform/board/raw/master/restyaboard.sh --no-check-certificate
sudo chmod +x restyaboard.sh
sudo restyaboard.sh

## Your Environment
v 0.6.6 (2018-11-01)

* Version used:
Description:    Debian GNU/Linux 9.5 (stretch)
PHP 7.0.33-0+deb9u3
[restyaboard_install.log](https://github.com/RestyaPlatform/board/files/3383337/restyaboard_install.log)

* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:
https://projets.djaseo.com/

**Comment by sridhar391** [comment]
@ludovic-durand you have attached the `restyaboard_install.log` file for updated Restyaboard from v0.6.4 to v0.6.5 and you Restyaboard URL  https://projets.djaseo.com/ seems to be loading correctly

**Comment by ludovic-durand** [comment]
Hi,

Yes, this is because I rolled back to 0.6.6.
It was an update from 0.6.6 to 0.6.7.

Ludovic Durand

Le ven. 12 juil. 2019 à 07:07, sridhar391 <notifications@github.com> a
écrit :

**Comment by sridhar391** [comment]
@ludovic-durand The attached `restyaboard_install.log` file contains the log for updating the Restyaboard from v0.6.4 to v0.6.5, please attach the `restyaboard_install.log` file for updating the Restyaboard from v0.6.6 to v0.6.7

**Comment by ludovic-durand** [comment]
Hi,

It works now.
You can close this case.

Bien cordialement.
Ludovic DURAND

E: ludovic.durand@djaseo.com
M: +33 6 87 70 69 97
<https://telephonie-djaseo.innze.cloud/webclient/#/call?phone=+33687706997>
[image:
DJASE'O] <https://www.djaseo.com/>
https://www.djaseo.com
<https://www.djaseo.com/>


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mar. 16 juil. 2019 à 09:55, sridhar391 <notifications@github.com> a
écrit :

**Comment by sridhar391** [comment]
@ludovic-durand Thanks for the confirmation of the issue fix
