### ISSUE TITLE
SMTP Configuration

### ISSUE THREAD

**Issue by dfanaei** [RestyaPlatform/board#2734]
Hi,
I have been trying to find a solution for this however I could not find any. 
I just installed restyaboard and everything is working fine except:
I cannot get the smtp working. 
I tried to apply in php.ini, however, I am using Mailjet to send the emails. and in php.ini there is no option to add username and password. 
this is what it currently has so far:

[mail function]
; For Win32 only.
; http://php.net/smtp
SMTP = in-v3.mailjet.com
; http://php.net/smtp-port
smtp_port = 587

; For Win32 only.
; http://php.net/sendmail-from
;sendmail_from = email@example.com

; For Unix only.  You may supply arguments as well (default: "sendmail -t -i").
; http://php.net/sendmail-path
;sendmail_path =

; Force the addition of the specified parameters to be passed as extra parameters
; to the sendmail binary. These parameters will always replace the value of
; the 5th parameter to mail().
;mail.force_extra_parameters =

Can you help me set this up please?
Thanks,

**Comment by rrjanbiah** [comment]
@dfanaei 

The `php.ini` trick will work only in Windows. You may check https://github.com/RestyaPlatform/board/issues/450#issuecomment-196814831 for additional info

*Internal note*

Bump on #1772

**Comment by sridhar391** [comment]
@dfanaei Due to inactivity, we are closing this issue, if the issue occurred again, please feel free to reopen the issue
