### ISSUE TITLE
Remove/disable Card number

### ISSUE THREAD

**Issue by dfanaei** [RestyaPlatform/board#2735]
Is there a way we could remove/disable the card number? 
I find it a bit confusing specially when trying to organize cards in the list from top to bottom. 
Please let me know, 
Thanks,
![restyaboard card number](https://user-images.githubusercontent.com/29267557/61758232-cd169200-ad78-11e9-851a-c16cee41045c.jpg)

**Comment by rrjanbiah** [comment]
@dfanaei You can very well hide the card ID. Kindly refer here https://restya.com/board/docs/hide-card-additional-informations-plugin-installation/

**Comment by dfanaei** [comment]
yes, perfect. it was actually installed on mine already. Thanks
