### ISSUE TITLE
Start Date Not Showing up (Date Range)

### ISSUE THREAD

**Issue by dfanaei** [RestyaPlatform/board#2736]
Hi, 
I see in the demo and some of the screenshots that there is a field for start date in the card detail page, However, Mine doesn't have that. 
Is it disabled? How would I be able to add it? 
Also, does the calendar have the ability to show date range?

**Comment by sridhar391** [comment]
@dfanaei The start date and the Gantt view features are provided by `Gantt View` app and it is a paid app and you can refer the link https://restya.com/board/apps/r_gantt_view for more details

**Comment by dfanaei** [comment]
Gantt View is a good feature to have but I don't really think it's a necessity as much as a date range display in the calendar. any type of calendar out there has a date range feature where it shows an event or task must happen between two different dates along with stretching the event card within the days that it is happening.. I checked the demo, and even when you have the gantt view, the start date and the date range yet don't show in the calendar. I think this would be a really good and necessary feature to add soon. honestly, everything in restyaboard is amazing and I thought I could continue implementing it for my project and task managements but without this feature I don't really think I can get it to work for me. Thanks

**Comment by sridhar391** [comment]
@dfanaei The start date field is shown only when the Gantt View app is installed and in the Gantt View, we will show the card with start date and due date as task and we will consider the suggestion for showing an event or task must happen between two different dates along with stretching the event card between the start date and due date
