### ISSUE TITLE
Send to board not working

### ISSUE THREAD

**Issue by erl4nc** [RestyaPlatform/board#2739]
"Send to board" link not working in modal card view of an archived card

## Expected Behavior
Archived card is restored back to board

## Current Behavior
User being kicked out of board to home page and the archived card is not restored

## Screenshots (if appropriate):
[send-to-board-fail.zip](https://github.com/RestyaPlatform/board/files/3444440/send-to-board-fail.zip)

## Possible Solution
Use the "Send to board" arrow from board archived items list

## Steps to Reproduce (for bugs)
1. Archive a card
2. Open the archived card modal view
3. From the modal view window, select "Send to board"

## Context
The 2 "Send to board" links should behave the same way

## Your Environment
* Version used: 0.6.7

**Comment by erl4nc** [comment]
I tested (d22b694) and it does not work.  The commit does not restore the archived card.  Did any of your testing restore the archived card to board?

**Comment by sridhar391** [comment]
@erl4nc We have uploaded the codes in our dev server https://boarddev.demo.restya.com/, please login with below credentials and please try to reproduce the issue and tell us if the issue is reproduced?

Username:  user
Password:  restya
Username:  admin
Password:  restya

**Comment by erl4nc** [comment]
Works on dev
