### ISSUE TITLE
Restoring archived cards do not restore labels until refresh

### ISSUE THREAD

**Issue by erl4nc** [RestyaPlatform/board#2740]
Users report that all of their archived cards have lost all the labels leading them not to want to archive any more.  After investigation, the labels are not lost, just not restored to view when the card is restored. The labels appear after a page refresh.

## Expected Behavior
Restoring any card restores its labels to view

## Current Behavior
Older cards restore without labels (simulated in video by closing and reopening browser). Recently archived cards restore with labels. 

## Screenshots (if appropriate):
[archived-labels-missing.zip](https://github.com/RestyaPlatform/board/files/3444559/archived-labels-missing.zip)

## Steps to Reproduce (for bugs)
See video

## Context
The bug caused panic when users thought they had lost all the labels on archived items

## Your Environment
* Version used: 0.6.7

**Comment by erl4nc** [comment]
I don't see (9c1b674) fixing the issue.  Even though I see the code block adding labels to card, no label is rendered in archived card modal view:
![labels still missing](https://user-images.githubusercontent.com/33263752/62155400-9f23d700-b2bd-11e9-83f6-a6b985962fbd.png)

Clicking on + next to labels would show them:
![card-has-labels](https://user-images.githubusercontent.com/33263752/62156225-6dac0b00-b2bf-11e9-9478-54eac02261a0.png)

Restoring the card back to board also still shows no label:
![restored-archive-no-labels](https://user-images.githubusercontent.com/33263752/62155490-ddb99180-b2bd-11e9-8a62-9ba95edd6c50.png)

Did any of your testing show different results?  Please be reminded that if you archive the card and immediately restore it, the labels will appear. Only after clearing cache can you adequately test this bug.

**Comment by sridhar391** [comment]
@erl4nc We have uploaded the codes in our dev server https://boarddev.demo.restya.com/, please login with below credentials and please try to reproduce the issue and tell us if the issue is reproduced?

Username:  user
Password:  restya
Username:  admin
Password:  restya

**Comment by erl4nc** [comment]
Dev produces inconsistent results.  Sometimes this works. Sometimes it gives very strange restore behaviour:
[strange-restore.zip](https://github.com/RestyaPlatform/board/files/3457830/strange-restore.zip)

1. archive card with 2 labels
2. clear everything from browser
3. for good measures, close and reopen browser
4. restore card from "archived items"
5. card restored to board without any label
6. just when I was going to stop recording, card jumps back to archived item without any user interaction
7. the next card in list that wasn't archived also jumps to archived item
