### ISSUE TITLE
Board  List and Grid view configuration related enhancement with additional features

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#2779]
## Context
- [X] Option for folding the lists in the board Grid view page for the better view.
- [X] Weekly and Daily Mail notification option added for the Users to see the Restyaboard activities. 
- [X] Start date and Due date is shown in the date-time format in front of the card in Board Grid View, Board List View, and Elastic Search. 
- [X] When a user creates a card, card description was shown in edit view by default on modal card page, it would be better to enter the description without fail.
- [X] Add the sort by ID option in the additional settings of default sort for cards on the board page.
- [X] Activity content changes in the footer notification for adding a new comment for the card.
- [X] Option for adding custom color to the cards, labels, and lists in the Boards.
- [X] `Copy Board` option is enhanced, provided an option for choosing fields in a board to be copied and also provided the option for copying the comments.  
- [X] Provided the option to export the card comments and custom fields using the Export CSV app.
- [X] `Grid View Configuration` new app is added to change the default look of cards, flexibility to define which columns/fields need to be displayed in the front of the card in the Board Grid View page it would be better, for the user could define how the card must be displayed in Grid.
- [X] `List View Configuration` new app is added to define which columns/fields need to be displayed in the Board list page and also possible to modify the order of the columns it would be better, for the user could define how the list must be displayed.

**Comment by olympica** [comment]
is Number 3 going to show in calendar view?

**Comment by rrjanbiah** [comment]
@olympica For calendar view issue, please refer #2783
