### ISSUE TITLE
Nothing displayed 

### ISSUE THREAD

**Issue by Herlderlord** [RestyaPlatform/board#278]
Hi 
I've no problem during installing Restya but i don't see anything on the web client. 
Here you can see my restya : 
http://center.mathiasquillot.com/#/users/login 

I don't understand why it doesn't work. 
Info : I use Ubuntu 15.10 on OVH VPS.

**Comment by Herlderlord** [comment]
Sorry, problem with postgresql. 
Basicly, it's not possible to user some commands of the sh file installer. 
Just see logs : 
`
++ psql -U postgres -c '\q'
psql: FATAL:  Peer authentication failed for user "postgres"
++ sleep 1
++ echo 'Creating PostgreSQL user and database...'
Creating PostgreSQL user and database...
++ psql -U postgres -c 'CREATE USER idolon WITH ENCRYPTED PASSWORD '\''Star34Shard'\'''
psql: FATAL:  Peer authentication failed for user "postgres"
++ psql -U postgres -c 'CREATE DATABASE restya OWNER idolon ENCODING '\''UTF8'\'' TEMPLATE template0'
psql: FATAL:  Peer authentication failed for user "postgres"
`

**Comment by rrjanbiah** [comment]
@Herlderlord Does it mean that you already fixed it? or still looking for solution?

**Comment by Herlderlord** [comment]
I've fixed it by installing the database by myself but there's a problem in the installing script.

**Comment by rrjanbiah** [comment]
@Herlderlord Thanks for letting us know the issue. Looks like you already had postgres installed in your machine (?). I'm just assuming this as your "postgres" user seems to be with different password than expected. 

If possible, please share your install log. That will give us better picture about it. (Please review the content of the file and remove any sensitive data like password, etc before posting here).

**Comment by Herlderlord** [comment]
@rrjanbiah yes, i had already postgresql and user postgres was block. (impossible to connect with directly) I don't know if it was possible to configure the sh file in order to able script to connect to pgsql bdd with other ids. 

One other things, with the tutorial, i had not understood that we don't have to create a user in pgsql. So, my user that i've writen on the sh script was already created. 
I hope you understand what i mean. 

Here you can read my logs:
[restyaboard_install.log](https://github.com/RestyaPlatform/board/files/136138/restyaboard_install.txt)

**Comment by rrjanbiah** [comment]
@Herlderlord Many thanks for sharing helpful information. This is really helpful.

**Comment by lmarikannan** [comment]
Error handling added if psql connection was not performed with default `postgres` user. Please refer, https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh#L1173
