### ISSUE TITLE
Show a board with all tasks that match a list name

### ISSUE THREAD

**Issue by CrashLaker** [RestyaPlatform/board#2780]
Hi all.

Thank you for the project. Just started using it and I'm finding it very useful.

One thing I'd like to know is if you could have a consolidated view of Lists from other boards that match a certain criteria.

For example:
I wanna see all tasks assigned to me that's in the "Doing" List from all boards i'm in.

Is it possible?

**Comment by rrjanbiah** [comment]
@CrashLaker Thanks for your kind words

Did you try `user:me`? https://restya.com/board/docs/search/

**Comment by CrashLaker** [comment]
Hi @rrjanbiah 

thank you for your reply.

How can I search? I can only see the boards page.

I'm using v 0.6.7 (2019-04-24).

**Comment by rrjanbiah** [comment]
@CrashLaker 

If you have Elasticsearch plugin https://restya.com/board/apps/r_elasticsearch it should work.

**Comment by rrjanbiah** [comment]
Closing this for now. If you face any issues, please feel free to reopen
