### ISSUE TITLE
Start date not updating in Gantt view, While adding start date in the modal card page.

### ISSUE THREAD

**Issue by baskar383** [RestyaPlatform/board#2786]
## Expected Behavior
After adding the start date in the modal card page, it needs to be shown in Gantt view Board page

## Current Behavior
Start date not updating in Gantt view, While adding start date in the modal card page.

## Steps to Reproduce (for bugs)
1. Login with user credentials 
2. Add start date to the card in the modal card page.
3. Without refreshing page, Go to Board Gantt view page, the Start date will not be shown 

## Your Environment
* Version used: v0.6.7
* Environment name and version (e.g. OS, PHP, PostgreSQL): Ubuntu, PHP 7.1
* Operating System and version (desktop or mobile): desktop

**Comment by baskar383** [comment]
Above issue fixed in Gantt View App, Changes will available on  upcoming release v0.6.8 (Roxette)

**Comment by sridhar391** [comment]
Duplicate https://github.com/RestyaPlatform/board/issues/2830, hence issue closed
