### ISSUE TITLE
Check the icons alignment in grid view

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2795]
## Expected Behavior

Icon should be displayed proper alignment in grid view

## Current Behavior

Check the icons alignment in grid view

## Screenshots (if appropriate):

![align](https://user-images.githubusercontent.com/14290356/63208962-8f4b2600-c0f8-11e9-80e7-b99824391765.png)

![align1](https://user-images.githubusercontent.com/14290356/63208964-91ad8000-c0f8-11e9-8787-a3adffdf6eb0.png)

## Steps to Reproduce (for bugs)

1. https://boarddev.demo.restya.com/#/board/282
2. Login as ramya / agriya
3. Check the icons alignment in grid view

**Comment by jawahar336** [comment]
Above issue fixed in Agile WIP App, App Changes will available on upcoming release v0.6.8 (Roxette)
