### ISSUE TITLE
If we update only time in custom field, "undefined" word is displayed in date

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2796]
## Expected Behavior
If we update only time in custom field, correct date and time should be display in date field

## Current Behavior
If we update only time in custom field, "undefined" word is displayed in date

## Screenshots (if appropriate):

![undefined](https://user-images.githubusercontent.com/14290356/63209055-c79f3400-c0f9-11e9-8f55-2c1ac34d21bd.png)

## Steps to Reproduce (for bugs)

1. https://boarddev.demo.restya.com/#/board/282
2. Login as ramya / agriya
3. Go to board and open the card.
4. If we update only time in custom field, "undefined" word is displayed in date

**Comment by baskar383** [comment]
Above issue fixed in Custom Field App Local Commit, App Changes will available on upcoming release v0.6.8 (Roxette)

**Comment by sridhar391** [comment]
Duplicate https://github.com/RestyaPlatform/board/issues/3149, hence issue closed
