### ISSUE TITLE
One user created the custom field. After created, custom field is not updated immediately in other user browser

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2797]
## Expected Behavior
One user created the custom field. After created, custom field should be update immediately in other user browser

## Current Behavior
One user created the custom field. After created, custom field is not updated immediately in other user browser

## Screenshots (if appropriate):

![custom field](https://user-images.githubusercontent.com/14290356/63209129-a4c14f80-c0fa-11e9-91b7-d9c4b7d91319.png)

## Steps to Reproduce (for bugs)

1. https://boarddev.demo.restya.com/#/board/282
2. Login as ramya / agriya
3. Go to board and open the card.
4. One user created the custom field. After created, custom field is not updated immediately in other user browser

**Comment by sridhar391** [comment]
If one user created the custom field and added the custom field values in the card, it will be updated in the other user browser

**Comment by srileka** [comment]
Issue not fixed.

Steps: Already other user browser, has been opened the model card. 
At the time current user trying to add the custom field. That custom field did not updated in other user browser model card page
