### ISSUE TITLE
In calendar and gantt view content gets broken when hovering the mouse one the card

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2799]
## Expected Behavior

In calendar and gantt view content should not broken when hovering the mouse one the card

## Current Behavior

In calendar and gantt view content gets broken when hovering the mouse one the card

## Screenshots (if appropriate):

![broken_1](https://user-images.githubusercontent.com/14290356/63209803-56647e80-c103-11e9-9338-b7a2fdc8df32.png)

![broken_2](https://user-images.githubusercontent.com/14290356/63209805-58c6d880-c103-11e9-9857-4359fa2dd97f.png)

![broken_3](https://user-images.githubusercontent.com/14290356/63209808-5a909c00-c103-11e9-9084-975a7c015ebb.png)

## Steps to Reproduce (for bugs)

1. https://boarddev.demo.restya.com/#/board/282/calendar
2. Login as ramya / agriya
3. In calendar and gantt view content gets broken when hovering the mouse one the card

**Comment by baskar383** [comment]
Gantt View Content issue fixed in the Gantt APP.  App changes will available on Upcoming release of Restyboard v0.6.8 (Roxette)
