### ISSUE TITLE
Couldn't Deploy this on Debian 8 (Jessie

### ISSUE THREAD

**Issue by mroe1234** [RestyaPlatform/board#28]
We spent a few days trying to deploy this on Debian Jessie.  We have been unable to get this project functional.  Digging into the code a bit and it looks like your error handling is a bit confusing.  Your database connection prepends the '@' which disables error handling then you separately do your own error handling?  You are emitting '404 Page not found' in many places which really should only ever be handed out by the webserver, not by the application.  Further, error codes should provide a bit more information about where the problem is.  

I'm going to keep an eye on this project, but it seems a bit unpolished to use at the moment.  Keep up the good work.

**Comment by rrjanbiah** [comment]
@mroe1234 Thanks for your bug report. However it is not very clear, what exact issues are you facing.

This is high performance SPA (single page application) consuming REST JSON API. So suppressing default database errors and throwing HTTP statuses are necessary.

If you're looking to find default error messages, you may enable debug mode at https://github.com/RestyaPlatform/board/blob/master/server/php/R/config.inc.php#L15

Also, to understand the issue better, please attach  relevant screenshots.

**Comment by rrjanbiah** [comment]
@mroe1234 Restyaboard is made available on docker by @namikingsoft https://github.com/namikingsoft/docker-restyaboard You may use it for installation too.

Or, provide more details on this issue. Closing this issue now. Feel free to reopen with more details.
