### ISSUE TITLE
Change the grid view configuration and add the instant add card, check the board url

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2805]
## Expected Behavior

Change the grid view configuration and add the instant add card, check the board url

## Current Behavior

Change the grid view configuration and add the instant add card, check the board url

## Screenshots (if appropriate):

![board url](https://user-images.githubusercontent.com/14290356/63211846-5f147f00-c11a-11e9-80f1-2bf0af568e8a.png)

## Steps to Reproduce (for bugs)

1. Dev instance
2. Login as ramya / agriya
3. Go to board
4. Change the grid view configuration and add the instant add card, check the board url

**Comment by baskar383** [comment]
Above issue fixed in Instant Add card in the local commit, Fixes changes will available in upcoming release of v0.6.8 (Roxette)
