### ISSUE TITLE
After adding the card in the list, empty white space are shown after refresh the page its get removed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2806]
## Expected Behavior
After adding the card in the list, added card should be display

## Current Behavior

After adding the card in the list, empty white space are shown after refresh the page its get removed (Chrome Version 76.0.3809.100)

## Screenshots (if appropriate):

![card removed](https://user-images.githubusercontent.com/14290356/63211944-cc74df80-c11b-11e9-86f3-fff257a8c86c.png)

## Steps to Reproduce (for bugs)

1. https://boarddev.demo.restya.com/#/board/283
2. Login as ramya / agriya.
3. Go to board.
4. After adding the card in the list, empty white space are shown after refresh the page its get removed (Chrome Version 76.0.3809.100)

**Comment by baskar383** [comment]
Duplicate issue of #2791. Hence we Closing this issue.
