### ISSUE TITLE
You can add yourself repeatedly to a task using the keyboard space shortcut

### ISSUE THREAD

**Issue by Rekemot** [RestyaPlatform/board#2821]
When you're in card view and use the spacebar to add yourself to the card, then you press spacebar again to remove yourself - you add yourself again. This way you can add yourself repeatedly to the same card.

## Expected Behavior
Pressing the space bar should add and remove us from this card alternately.

## Current Behavior
Pressing the space bar adds us back to the card indefinitely.

## Screenshots (if appropriate):
![Screenshot 2019-08-22 at 10 22 46](https://user-images.githubusercontent.com/6618081/63499225-bbcfbb00-c4c7-11e9-83af-6b04a8139572.png)

## Steps to Reproduce (for bugs)
1. Click on the selected tab to view its settings
2. Press spacebar to add yourself to the card
3. Press the space bar again, you will be added to the card again.
4. Pressing the space bar again adds up again.

## Context
In my workflow, using shortcuts is very important for speeding up the workflow, so these types of errors disqualify Restya platform from using it.

## Your Environment
* Version used: v 0.6.7 (2019-04-24)
* Environment: PHP 7.3.0, PostgreSQL 9.3
* Operating System and version: Ubuntu 16.04.6 LTS (on hosting)

**Comment by dfanaei** [comment]
@sridhar391  Do you know when this version will be released? I thought the deadline was set for 10 days ago in the milestone.
