### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attributes' of undefined error thrown while adding the card with labels using instant add card

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2841]
## Expected Behavior

Need to fixed the console error "Uncaught TypeError: Cannot read property 'attributes' of undefined error thrown while adding the card with labels using instant add card"

## Current Behavior

Uncaught TypeError: Cannot read property 'attributes' of undefined error thrown while adding the card with labels using instant add card

## Screenshots (if appropriate):

![card with label](https://user-images.githubusercontent.com/14290356/63687762-1435ee00-c823-11e9-8443-e3e3ad597d98.png)

**Comment by sridhar391** [comment]
@srileka Not able to reproduce and we are closing this issue, if the issue is reproduced, please provide us the steps to reproduce and feel to reopen the issue
