### ISSUE TITLE
While adding and removing the same member multiple time, check the console error and board has been removed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2842]
## Expected Behavior

While adding and removing the same member multiple time, board should not be removed

## Current Behavior

While adding and removing the same member multiple time, check the console error and board has been removed

## Screenshots (if appropriate):

![member_multiple](https://user-images.githubusercontent.com/14290356/63687870-595a2000-c823-11e9-8035-8a87783cc7ef.png)

**Comment by srileka** [comment]
Issue not fixed.

 when we simultaneously add and remove member in modal card

**Comment by srileka** [comment]
Issue not fixed.

**Comment by baskar383** [comment]
cc @srileka 

It's not an error,  once a user token has expired, an error will be thrown as authentication error, to handle the refresh token
