### ISSUE TITLE
prompt.js:1 Uncaught SyntaxError: Identifier 'originalPrompt' has already been declared error thrown all the time

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2845]
## Expected Behavior

Need to fix the console error "prompt.js:1 Uncaught SyntaxError: Identifier 'originalPrompt' has already been declared" 

## Current Behavior

"prompt.js:1 Uncaught SyntaxError: Identifier 'originalPrompt' has already been declared" error thrown all the time

## Screenshots (if appropriate):

![all the time](https://user-images.githubusercontent.com/14290356/63688282-88bd5c80-c824-11e9-8a00-412c1157856c.png)

**Comment by sridhar391** [comment]
@srileka Seems to be an chrome extension error
