### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attributes' of undefined error thrown, other user (user not a member of the board) open the card in public board

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2857]
## Expected Behavior

Uncaught TypeError: Cannot read property 'attributes' of undefined error thrown, other user (user not a member of the board) open the card in public board

## Current Behavior

Uncaught TypeError: Cannot read property 'attributes' of undefined error thrown, other user (user not a member of the board) open the card in public board

## Screenshots (if appropriate):

![public board](https://user-images.githubusercontent.com/14290356/63748040-2cab1480-c8c6-11e9-8b78-77d8b9a0e067.png)

**Comment by sridhar391** [comment]
@srileka The above issue is fixed in the Card Template App Local commit and it will be avialable on the upcoming release v0.6.8 (Roxette)
