### ISSUE TITLE
When we trying to copy the list or card (card should having the comment), at the time notification update for own user for his activities

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2858]
##  Expected Behavior

When we trying to copy the list or card (card should having the comment), at the time notification should not update for own user for his activities

## Current Behavior

When we trying to copy the list or card (card should having the comment), at the time notification update for own user for his activities

## Screenshots (if appropriate):

![activities](https://user-images.githubusercontent.com/14290356/63750322-e310f880-c8ca-11e9-9dd3-fbb235d10d8a.png)

**Comment by srileka** [comment]
Issue not Fixed

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the commit https://github.com/RestyaPlatform/board/commit/cc56a5f0dfa1f544349e3cd189a3be8cf95e9cc9 and it will be available in the upcoming release v0.6.8 (Roxette)
