### ISSUE TITLE
Copy the list and then changing the list position continuously, scroll bar is moving automatically at the end of the page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2860]
## Expected Behavior

Copy the list and then changing the list position continuously, scroll bar should be work properly

## Current Behavior

Copy the list and then changing the list position continuously, scroll bar is moving automatically at the end of the page

## Screenshots (if appropriate):

![scroll bar](https://user-images.githubusercontent.com/14290356/63752692-56b50480-c8cf-11e9-8f4c-dabee58e1b20.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the dev branch and it will be available in the upcoming release v0.6.8 (Roxette)
