### ISSUE TITLE
Card due date is not updated properly in calendar view. After refreshing the page only it's updated

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2864]
## Expected Behavior

Card due date should be update properly in calendar view. 

## Current Behavior

Card due date is not updated properly in calendar view. After refreshing the page only it's updated

## Screenshots (if appropriate):

![due date_update](https://user-images.githubusercontent.com/14290356/63763901-46a72000-c8e3-11e9-961b-5e9f713f1a4a.png)

**Comment by sridhar391** [comment]
@srileka Fixed in the dev branch and it will be available on the upcoming release v0.6.8 (Roxette)
