### ISSUE TITLE
Other user (user not a member of the board), If we giving the value in "task move on due date, auto archive days and agile wip" those field,  console error came

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2868]
## Expected Behavior

Other user (user not a member of the board), If we giving the value in "task move on due date, auto archive days and agile wip" those field,  console error came

## Current Behavior

Other user (user not a member of the board), If we giving the value in "task move on due date, auto archive days and agile wip" those field,  console error came

## Screenshots (if appropriate):

![console_not a mem](https://user-images.githubusercontent.com/14290356/63764698-0648a180-c8e5-11e9-9dae-6c3ab91e4745.png)

**Comment by sridhar391** [comment]
Fixed in the Local commit of Auto archive Expired cards app, Agile WIP, Task Move on due date app and it will be available on the upcoming release v0.6.8 (Roxette)
