### ISSUE TITLE
In card after clicking the "convert to card", card is not updated properly in current user and other user browser

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2871]
## Expected Behavior

In card after clicking the "convert to card", card is not updated properly in current user and other user browser

## Current Behavior

In card after clicking the "convert to card", card is not updated properly in current user and other user browser

## Two cases are there

Case 1: Current user browser give the "convert to card", converted card is not updated in other user browser

Case 2: Other user browser give the "convert to card", converted card is not updated in both user 

## Screenshots (if appropriate):

![conver to card](https://user-images.githubusercontent.com/14290356/63768416-c639ec80-c8ed-11e9-85f2-bf7cd7e40cf8.png)

**Comment by sridhar391** [comment]
Fixed in the dev branch and it will be available on the upcoming release v0.6.8 (Roxette)

**Comment by sridhar391** [comment]
Issue not fixed
