### ISSUE TITLE
After deleted the label, deleted label did not updated in other user browser

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2882]
## Expected Behavior

After deleted the label, deleted label should be update in other user browser

## Current Behavior

After deleted the label, deleted label did not updated in other user browser

## Screenshots (if appropriate):

![delete_label](https://user-images.githubusercontent.com/14290356/63775865-de196c80-c8fd-11e9-97db-549e6af9b156.png)

**Comment by sridhar391** [comment]
Now, all the cards in other user browsers jerking while updated about the delete label

**Comment by sridhar391** [comment]
Now, all the cards whose not having the deleted label in other user browsers will not trigger

**Comment by srileka** [comment]
Issue Not Fixed.

After deleted the label, deleted label did not updated in current and other user browser "labels settings"

![labels_deleted](https://user-images.githubusercontent.com/14290356/69608649-e775ba80-104d-11ea-8fe6-822e798d83b7.png)

**Comment by sridhar391** [comment]
Issue Not Fixed.
After delete the label, go to the list view and then come to grid view.
At the time, previously deleted label did not removed.
