### ISSUE TITLE
Sometimes activity did not displayed in notification

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2884]
## Expected Behavior

Sometimes activity did not displayed in notification

## Current Behavior

Sometimes activity did not displayed in notification

## Screenshots (if appropriate):

![notification_activirty](https://user-images.githubusercontent.com/14290356/63776313-c7274a00-c8fe-11e9-8439-8c9d79e3ed02.png)

**Comment by sridhar391** [comment]
@srileka we have fixed the above issue in the commit https://github.com/RestyaPlatform/board/commit/02e840a3392c9769d16d825c76845dd21eff5fda and it will be available on the upcoming release v0.6.8 (Roxette)
