### ISSUE TITLE
Uncaught TypeError: $dom.getAttribute is not a function error thrown when we trying to move the card in listview

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2900]
## Expected Behavior

Uncaught TypeError: $dom.getAttribute is not a function error thrown when we trying to move the card in listview

## Current Behavior

Uncaught TypeError: $dom.getAttribute is not a function error thrown when we trying to move the card in listview

## Screenshots (if appropriate):

![list view_console](https://user-images.githubusercontent.com/14290356/63852352-b4238100-c9b5-11e9-9843-d9977afe3c7c.png)

**Comment by sridhar391** [comment]
@srileka It seems to be an chrome extension error, please check and re-open this issue if the issue is reproduced after disabling the chrome extension
