### ISSUE TITLE
Exported csv file , field name should be displayed proper name and proper order

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2901]
## Expected Behavior

Exported csv file , field name should be displayed proper name and proper order

## Current Behavior

Exported csv file , field name should be displayed proper name and proper order

## Screenshots (if appropriate):

![csv file](https://user-images.githubusercontent.com/14290356/63852788-b508e280-c9b6-11e9-9410-15bd50dd6136.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the Export CSV app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
