### ISSUE TITLE
When we set the true in Hide Card Additional Information settings, hided options are should be disable in boards page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2906]
## Expected Behavior

When we set the true in Hide Card Additional Information settings, hided options are should be disable in boards page

## Current Behavior

When we set the true in Hide Card Additional Informations settings, hided options are should be disable in boards page

## Screenshots (if appropriate):

![information](https://user-images.githubusercontent.com/14290356/63858557-4ed68c80-c9c3-11e9-9095-d7cc643de186.png)

**Comment by sridhar391** [comment]
@srileka When we set the true in Hide Card Additional Information settings, the option will not be shown in the Grid View Configure and List View Configure apps options
