### ISSUE TITLE
Open the card in list view and then click back navigation, board has been removed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2907]
## Expected Behavior

Open the card in list view and then click back navigation, board has been removed

## Current Behavior

Open the card in list view and then click back navigation, board has been removed

## Screenshots (if appropriate):

![board removed](https://user-images.githubusercontent.com/14290356/63861036-c1e20200-c9c7-11e9-8266-bb53e722bdc3.png)

**Comment by sridhar391** [comment]
The page is directed to the calendar view while clicking the back navigation, but the modal card is not closed
