### ISSUE TITLE
Auto-archive cards on some list

### ISSUE THREAD

**Issue by dfragac** [RestyaPlatform/board#291]
Here is what I think could be an interesting feature:

- Possibility to configure lists like "Finished cards"
- When I put a card there, it's considered "done"
- When a card is "done" in this list for more than "xx" days/hours/months... autoarchive it.

¿What do you think?

**Comment by rrjanbiah** [comment]
@dfragac Thanks for your suggestions. We'll see what we can do about this.

**Comment by ssivachidambaram** [comment]
Done as a separate app.
