### ISSUE TITLE
Change the card id position. After created the card, card id should be display the left side or right side corner

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2911]
## Expected Behavior

Change the card id position. After created the card, card id should be display the left side or right side corner

## Current Behavior

Change the card id position. After created the card, card id should be display the left side or right side corner

## Screenshots (if appropriate):

![card id_position](https://user-images.githubusercontent.com/14290356/63916050-3020d600-ca55-11e9-8d8b-2934747277cd.png)

**Comment by sridhar391** [comment]
@srileka Fixed in our Github Restyaboard apps repository on the commit https://github.com/RestyaPlatform/board-apps/pull/145/commits/d4f2f5edcac4ce0e550a354edbdde1e16546c8c2
