### ISSUE TITLE
In Grid view, current user archived the card and then send to board. At the time, other user browser in list view, that archived card position wrong.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2912]
## Expected Behavior

In Grid view, current user archived the card and then send to board. At the time, other user browser in list view, that archived card should be in display in old position.

## Current Behavior

In Grid view, current user archived the card and then send to board. At the time, other user browser in list view, that archived card position wrong.

## Screenshots (if appropriate):

![archive_list view_removed](https://user-images.githubusercontent.com/14290356/63916190-855ce780-ca55-11e9-80dc-2f7026d1bb37.png)

**Comment by sridhar391** [comment]
@srileka Fixed in the dev branch and it will be available on the upcoming release v0.6.8 (Roxette)
