### ISSUE TITLE
In list view, card subscription count is not updated

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2918]
## Expected Behavior

In list view, card subscription count should be update

## Current Behavior

In list view, card subscription count is not updated

## Screenshots (if appropriate):

![card_subscription_list view](https://user-images.githubusercontent.com/14290356/63921357-46805f00-ca60-11e9-997b-5b412badba64.png)

**Comment by jawahar336** [comment]
@srileka If the user is subscribed to the card, the subscribe icon will be shown in the subscribe column of the card in the board List View

**Comment by sridhar391** [comment]
If the same user logged in on the two different browsers, the card subscription is not updated in the list view
