### ISSUE TITLE
Workflow for cards

### ISSUE THREAD

**Issue by dfragac** [RestyaPlatform/board#292]
Another interesting thing to do with cards (to put view on Gantt) is:
 - We could configure a list for "pending" or "on queue" or "drafts" and, when a card pops out of that list to another, its "start time".
 - We could configure a list for "done", when I put a card on that list, it's considered "done".
 - If I move a card to "drafts" or other list with that kind of configure, it's considedred "stopped"
 - If i move a card out to "done" ist sonsidered "start again".

It's to simulate something like a timeline for cards. Sorry if my explanation is not so clear.

Regards

**Comment by rrjanbiah** [comment]
@dfragac Many thanks for your suggestions. We hope that we understand your points. If there's anything that is not clear, we'll let you. Thanks

**Comment by ssivachidambaram** [comment]
Done in `dev` branch.
