### ISSUE TITLE
When we add the card in grid view, other user browser card position wrong in list view

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2926]
## Expected Behavior

When we add the card in grid view, other user browser card position should be correct in list view

## Current Behavior

When we add the card in grid view, other user browser card position wrong in list view

## Screenshots (if appropriate):

![list view_card position](https://user-images.githubusercontent.com/14290356/63929954-fd380b80-ca6f-11e9-90c1-30f8089eeebb.png)

**Comment by sridhar391** [comment]
@srileka Fixed in the commit https://github.com/RestyaPlatform/board/pull/2958/commits/c47e82e74d340c0f8e04363e5eb1ed8647e28927 and it will be available on the upcoming release v0.6.8 (Roxette)
