### ISSUE TITLE
When we editing the custom field, we unable to change the field type

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2927]
## Expected Behavior

When we editing the custom field, we unable to change the field type

## Current Behavior

When we editing the custom field, we unable to change the field type

## Screenshots (if appropriate):

![custom_edit_type](https://user-images.githubusercontent.com/14290356/63930053-36707b80-ca70-11e9-999d-4cb4221b6d89.png)

**Comment by sridhar391** [comment]
@srileka It is not possible to edit the custom field type in the edit form
