### ISSUE TITLE
In add custom field (drop down field), options should be displayed as mandatory

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2930]
## Expected Behavior

In add custom field (drop down field), options should be displayed as mandatory

## Current Behavior

In add custom field (drop down field), options should be displayed as mandatory

## Screenshots (if appropriate):

![drop_options](https://user-images.githubusercontent.com/14290356/63932462-d92af900-ca74-11e9-8d95-7f2040eee759.png)

**Comment by sridhar391** [comment]
@srileka As like trello, we have followed the required fields and it is not required to give options values as mandatory
