### ISSUE TITLE
In add custom field (drop down field), if we give the space in between the options, options order wrong

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2931]
## Expected Behavior

In add custom field (drop down field), if we give the space in between the options, options order wrong

## Current Behavior

In add custom field (drop down field), if we give the space in between the options, options order wrong

## Screenshots (if appropriate):

![options_order](https://user-images.githubusercontent.com/14290356/63932532-fb247b80-ca74-11e9-8f1d-d11cf46a6290.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the Custom Fields app local commit and it will be released on the upcoming release v0.6.8 (Roxette)

**Comment by srileka** [comment]
Issue not fixed. In add custom field (drop down field), if we give the space in between the options, options order wrong

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the local commit and it will be available in the upcoming release v0.6.8 (Roxette)

**Comment by sridhar391** [comment]
Issue not fixed

**Comment by sridhar391** [comment]
Fixed the above issue in the Custom Fields app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)
