### ISSUE TITLE
In custom field, when we editing the custom field name before giving the value, "undefined" displayed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2932]
## Expected Behavior

In custom field, when we editing the custom field name before giving the value, "undefined" displayed

## Current Behavior

In custom field, when we editing the custom field name before giving the value, "undefined" displayed

## Screenshots (if appropriate):

![undefined](https://user-images.githubusercontent.com/14290356/63932588-18594a00-ca75-11e9-9177-6ff867af52cb.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the Custom Fields app local commit and it will be released on the upcoming release v0.6.8 (Roxette)
