### ISSUE TITLE
When we go the calendar view through the list view, this console error thrown Uncaught TypeError: Cannot read property 'set' of undefined

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2934]
## Expected Behavior

When we go the calendar view through the list view, this console error thrown Uncaught TypeError: Cannot read property 'set' of undefined

## Current Behavior

When we go the calendar view through the list view, this console error thrown Uncaught TypeError: Cannot read property 'set' of undefined

## Screenshots (if appropriate):

![calendar view_console](https://user-images.githubusercontent.com/14290356/63934264-8d7a4e80-ca78-11e9-9e5b-6dcf8736a897.png)

**Comment by sridhar391** [comment]
Fixed in the dev branch and it will be available on the upcoming release v0.6.8 (Roxette)
