### ISSUE TITLE
When the drop down options are not there in custom field, this console error came "Uncaught TypeError: a.option.split is not a function"

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2935]
## Expected Behavior

When the drop down options are not there in custom field, this console error came "Uncaught TypeError: a.option.split is not a function"

## Current Behavior

When the drop down options are not there in custom field, this console error came "Uncaught TypeError: a.option.split is not a function"

## Screenshots (if appropriate):

![drop_option_console](https://user-images.githubusercontent.com/14290356/63936094-a258e100-ca7c-11e9-8023-2cba99d6adaf.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in Custom Fields app local commit and it will be released on the upcoming release v0.6.8 (Roxette)
