### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined error thrown when removing the parent or  child card, it's not updated properly in parent and child card. 

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2937]
## Expected Behavior

Uncaught TypeError: Cannot read property 'indexOf' of undefined error thrown when removing the parent or  child card, it's not updated properly in parent and child card. 

## Current Behavior

Uncaught TypeError: Cannot read property 'indexOf' of undefined error thrown when removing the parent or  child card, it's not updated properly in parent and child card. 

## Screenshots (if appropriate):

![parent_dependency](https://user-images.githubusercontent.com/14290356/63940901-12209900-ca88-11e9-8826-7ecc46adca74.png)

## Steps to Reproduce (for bugs)

1. Open the card
2. The add the parent or child card.
3. Then remove the parent or child card.
4. After removed, open the particular parent or child card. That time, removed card is displayed.
5. Now click to remove the card, console error came

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)

**Comment by srileka** [comment]
Issue Not Fixed.

Card dependency -> If we add the more than one card from the same list. Then remove the single card, all the card from the list has been removed.

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)
