### ISSUE TITLE
Check the children alignment in card

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2939]
## Expected Behavior

Check the children alignment in card

## Current Behavior

Check the children alignment in card

## Screenshots (if appropriate):

![children_align](https://user-images.githubusercontent.com/14290356/63945117-6e87b680-ca90-11e9-8546-36fbc6893362.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the Gantt View app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
