### ISSUE TITLE
If we add the multiple child card at the time, start date and due date is wrong

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2942]
## Expected Behavior

If we add the multiple child card at the time, start date and due date is wrong

## Current Behavior

If we add the multiple child card at the time, start date and due date is wrong

## Screenshots (if appropriate):

![child card_date](https://user-images.githubusercontent.com/14290356/63945852-b955fe00-ca91-11e9-923c-e90fb392d258.png)

**Comment by sridhar391** [comment]
@srileka If we add the child cards, the child cards start date will be one day after the parent card due date.
