### ISSUE TITLE
When we update all the custom fields at the same time, custom field color did  not updated in grid view page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2946]
## Expected Behavior

When we update all the custom fields at the same time, custom field color should be update in grid view page

## Current Behavior

When we update all the custom fields at the same time, custom field color did  not updated in grid view page

## Screenshots (if appropriate):

![custom_color](https://user-images.githubusercontent.com/14290356/64006216-819d9380-cb2f-11e9-89e3-12d217514510.png)

**Comment by sridhar391** [comment]
@srileka Fixed in the Custom Fields app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
