### ISSUE TITLE
When we move the card from one board to another board, other user browser moved card position is wrong

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2948]
## Expected Behavior

When we move the card from one board to another board, other user browser moved card position should be correct

## Current Behavior

When we move the card from one board to another board, other user browser moved card position is wrong

## Screenshots (if appropriate):

![card_move_other_position](https://user-images.githubusercontent.com/14290356/64006490-11dbd880-cb30-11e9-964f-9ae0b0ec4b09.png)

**Comment by srileka** [comment]
Issue not fixed

**Comment by srileka** [comment]
Issue not Fixed

Additional settings - card position set as a ascending.

**Comment by sridhar391** [comment]
The Moved list cards are not added in the other user browser list view of other board

**Comment by srileka** [comment]
Issue not Fixed.

Case : First time we move the card from one board to another board, card position updated correctly.

Second time we move the card from one board to another board, that time card position is wrong in other user browser.

**Comment by srileka** [comment]
Issue not Fixed.

First we move list from one board to another board.

And then we move the card from "current list to previously moved list".

Move the more than one card, at the time card position is wrong.

Default sort for card : position (ASC)

![2019-11-07_11-00-31](https://user-images.githubusercontent.com/14290356/68362242-8e9cbb80-014c-11ea-9c09-e26786376bd7.png)
