### ISSUE TITLE
we able to add "one card" as parent card or child card in multiple card. That time start date and due date is wrong

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2951]
## Expected Behavior

we able to add "one card" as parent card or child card in multiple card. That time start date and due date is wrong

## Current Behavior

we able to add "one card" as parent card or child card in multiple card. That time start date and due date is wrong

## Screenshots (if appropriate):

![card_mutiple_child](https://user-images.githubusercontent.com/14290356/64006749-8adb3000-cb30-11e9-95a0-33c8eec27e68.png)

**Comment by sridhar391** [comment]
@srileka We have fixed the above issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)
