### ISSUE TITLE
First time we add the parent card or child card, at the time current user date dose not updated automatically

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2952]
## Expected Behavior

First time we add the parent card or child card, at the time current user date dose not updated automatically

## Current Behavior

First time we add the parent card or child card, at the time current user date dose not updated automatically

## Screenshots (if appropriate):

![First time_parent_child](https://user-images.githubusercontent.com/14290356/64006810-aa725880-cb30-11e9-84ed-8d6fd6f93469.png)

**Comment by sridhar391** [comment]
@srileka We have fixed the above issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)
