### ISSUE TITLE
Open the board and click the "list, calendar, grid and gantt view" multiple time and then clicking back navigation continuously,  console error came

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2953]
## Expected Behavior

Open the board and click the "list, calendar, grid and gantt view" multiple time and then clicking back navigation continuously,  console error came

## Current Behavior

Open the board and click the "list, calendar, grid and gantt view" multiple time and then clicking back navigation continuously,  console error came

## Screenshots (if appropriate):

![view_console](https://user-images.githubusercontent.com/14290356/64006880-cbd34480-cb30-11e9-9983-d99b3593ab0c.png)

**Comment by baskar383** [comment]
@srileka 
Fixed the above issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)
