### ISSUE TITLE
After copy the card, other user browser open the card and then click the grid view, list view and calendar view, console error came

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2954]
## Expected Behavior

After copy the card, other user browser open the card and then click the grid view, list view and calendar view, console error came

## Current Behavior

After copy the card, other user browser open the card and then click the grid view, list view and calendar view, console error came

## Screenshots (if appropriate):

![card copy_calendar_open](https://user-images.githubusercontent.com/14290356/64006948-ec030380-cb30-11e9-9b3b-21c0b4fba4d9.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the dev branch, it will be available in the upcoming release v0.6.8 (Rxette)
