### ISSUE TITLE
After move the card, other user browser open the card console error came

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2957]
## Expected Behavior

After move the card, other user browser open the card console error came

## Current Behavior

After move the card, other user browser open the card console error came

## Screenshots (if appropriate):

![move_other](https://user-images.githubusercontent.com/14290356/64007076-210f5600-cb31-11e9-9858-b260749921b0.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the dev branch and it will be available in the upcoming release v0.6.8 (Roxette)

**Comment by sridhar391** [comment]
Issue not fixed

**Comment by sridhar391** [comment]
Fixed the above issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.8(Roxette)
