### ISSUE TITLE
Add custom field, custom color option did not displayed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2962]
## Expected Behavior

Add custom field, custom color option did not displayed

## Current Behavior

Add custom field, custom color option did not displayed

## Screenshots (if appropriate):

![custom color_add fiel](https://user-images.githubusercontent.com/14290356/64018308-b9b1d000-cb49-11e9-876e-9d8139ba9535.png)

**Comment by sridhar391** [comment]
@srileka Added the enhancement in the Custom Fields app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
