### ISSUE TITLE
After added the custom field, all the boards custom fields are displayed. Current board custom field only should be display

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2963]
## Expected Behavior

After added the custom field, all the boards custom fields are displayed. Current board custom field only should be display

## Current Behavior

After added the custom field, all the boards custom fields are displayed. Current board custom field only should be display

## Screenshots (if appropriate):

![add field_all board field](https://user-images.githubusercontent.com/14290356/64018421-fed60200-cb49-11e9-9fb7-d3a834fe8003.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the Custom Fields app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
