### ISSUE TITLE
Custom field added activity "null" value displayed and check the activity message

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2964]
## Expected Behavior

Custom field added activity "null" value displayed and check the activity message

## Current Behavior

Custom field added activity "null" value displayed and check the activity message

## Screenshots (if appropriate):

![custom field_null](https://user-images.githubusercontent.com/14290356/64018627-90de0a80-cb4a-11e9-8b5b-c0746386dfdc.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the Local custom field app commit and it will be available on the upcoming release v0.6.8 (Roxette)

**Comment by sridhar391** [comment]
Custom field added activity shown in the footer notification, but the board name shown as below text
`Admin added custom field Test Field on ##BOARD_LINK## board`

**Comment by sridhar391** [comment]
Fixed the above issue in the Custom Fields app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)
