### ISSUE TITLE
First copy the one list. when trying to move the card from another list to "copied list", console error came

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2965]
## Expected Behavior

First copy the one list. when trying to move the card from another list to "copied list", console error came

## Current Behavior

First copy the one list. when trying to move the card from another list to "copied list", console error came

## Screenshots (if appropriate):

![coplist_move card](https://user-images.githubusercontent.com/14290356/64018696-c2ef6c80-cb4a-11e9-989e-b5f9c45ddbf6.png)

**Comment by sridhar391** [comment]
@srileka Fixed in the dev branch and it will be available on the upcoming release v0.6.8 (Roxette)
