### ISSUE TITLE
In Show attachments, after deleted the attachment "No attachments available."  should be display

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2967]
## Expected Behavior

In Show attachments, after deleted the attachment "No attachments available."  should be display

## Current Behavior

In Show attachments, after deleted the attachment "No attachments available."  should be display

## Screenshots (if appropriate):

![no attchments](https://user-images.githubusercontent.com/14290356/64018790-01852700-cb4b-11e9-8297-0166671d519d.png)

**Comment by sridhar391** [comment]
@srileka We are closing this issue as we are not able to reproduce the issue and please feel free to re-open the issue if the issue reoccured
