### ISSUE TITLE
When we copying the checklist items, this console error is thrown Uncaught TypeError: Cannot read property 'innerText' of undefined

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2970]
## Expected Behavior

When we copying the checklist items, this console error is thrown Uncaught TypeError: Cannot read property 'innerText' of undefined

## Current Behavior

When we copying the checklist items, this console error is thrown Uncaught TypeError: Cannot read property 'innerText' of undefined

## Screenshots (if appropriate):

![copy_checklist_console](https://user-images.githubusercontent.com/14290356/64026298-1cac6280-cb5c-11e9-9716-c9ff0c5d0db4.png)

**Comment by sridhar391** [comment]
@srileka It seems to be an chrome extension error, please check and re-open this issue if the issue is reproduced after disabling the chrome extension
