### ISSUE TITLE
Checklist pending count ascending and descending order is not working

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2971]
## Expected Behavior

Checklist pending count ascending and descending order is not working

## Current Behavior

Checklist pending count ascending and descending order is not working

## Screenshots (if appropriate):

![pending_1](https://user-images.githubusercontent.com/14290356/64026350-3483e680-cb5c-11e9-8b61-533eca0f0c5e.png)

![pending_2](https://user-images.githubusercontent.com/14290356/64026357-38b00400-cb5c-11e9-83a6-b29bd5a8308f.png)

**Comment by sridhar391** [comment]
@srileka Fixed in the dev branch and it will be available on the upcoming release v0.6.8 (Roxette)
