### ISSUE TITLE
Add the card and the sorting the list moved date, all the cards has been removed in the list

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2973]
## Expected Behavior

Add the card and the sorting the list moved date, all the cards has been removed in the list

## Current Behavior

Add the card and the sorting the list moved date, all the cards has been removed in the list

## Screenshots (if appropriate):

![add card_moved list](https://user-images.githubusercontent.com/14290356/64026519-8c225200-cb5c-11e9-9949-86027ea262f4.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the commit https://github.com/RestyaPlatform/board/commit/2eab2254ac0b3a9aaf1c0d24f46a3f5adabf97db
