### ISSUE TITLE
While try to move the card to other board with different sort by option using the move card option in the modal card page , the position field is not shown

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#2975]
## Expected Behavior
While try to move the card to other board with different sort by option using the move card option in the modal card page , the position field should show

## Current Behavior
While try to move the card to other board with different sort by option using the move card option in the modal card page , the position field is not shown

**Comment by srileka** [comment]
Issue not fixed

**Comment by sridhar391** [comment]
Issue not fixed
