### ISSUE TITLE
Add the card and then sorting based on the "start date", all the cards are removed (start date not there in added card)

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2976]
## Expected Behavior

Add the card and then sorting based on the "start date", all the cards are removed (start date not there in added card)

## Current Behavior

Add the card and then sorting based on the "start date", all the cards are removed (start date not there in added card)

## Screenshots (if appropriate):

![add card_start date](https://user-images.githubusercontent.com/14290356/64061328-04d5ec80-cbf7-11e9-8f72-2f38c5d92adc.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the commit https://github.com/RestyaPlatform/board/commit/2eab2254ac0b3a9aaf1c0d24f46a3f5adabf97db and it will be available on the upcoming release v0.6.8 (Roxette)
