### ISSUE TITLE
In filter by cards, "due date in next month and next week" is not working properly

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2978]
## Expected Behavior

In filter by cards, "due date in next month and next week" is not working properly

## Current Behavior

In filter by cards, "due date in next month and next week" is not working properly

## Screenshots (if appropriate):

![due date_1](https://user-images.githubusercontent.com/14290356/64061340-1cad7080-cbf7-11e9-92c3-9c8e8864388a.png)

![due date_2](https://user-images.githubusercontent.com/14290356/64061344-1f0fca80-cbf7-11e9-9d61-a7ecf7edfedd.png)

**Comment by jawahar336** [comment]
@srileka As like Trello, The "due in the next week"  will show you the cards which are having the due date from the current date to next 7 days & The "due in the next month"  will show you the cards which are having the due date from the current date to next 30 days.
