### ISSUE TITLE
"Match any labels and any member" and "Match all labels and all member", same result displayed in filter cards

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#2982]
## Expected Behavior

"Match any labels and any member" and "Match all labels and all member", same result displayed in filter cards

## Current Behavior

"Match any labels and any member" and "Match all labels and all member", same result displayed in filter cards

## Screenshots (if appropriate):

![same result](https://user-images.githubusercontent.com/14290356/64061409-06ec7b00-cbf8-11e9-8588-81a689b5a772.png)

**Comment by sridhar391** [comment]
@srileka As like trello we are filtering the cards in the boards
