### ISSUE TITLE
Without giving the template name in create template,  when we clicking the save button, create template dropdown should not be closed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3004]
## Expected Behavior

Without giving the template name in create template,  when we clicking the save button, create template box should not be closed

## Current Behavior

Without giving the template name in create template,  when we clicking the save button, create template box should not be closed

## Screenshots (if appropriate):

![create template_box](https://user-images.githubusercontent.com/14290356/64160391-7e6d1500-ce59-11e9-8027-1b6c3184edc4.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the Card Template app local commit and it will be available on the upcoming release v0.6.8 (Roxette)

**Comment by sridhar391** [comment]
without giving template name, the `Space is not allowed` message shown and the HTML validation should be added to the card template name field

**Comment by sridhar391** [comment]
Fixed the above issue in the Card Template app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)
