### ISSUE TITLE
After created card templates, sometimes created templates not updated in current and other user browser. After refreshing the page only, it's updated

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3005]
## Expected Behavior

After created card templates, sometimes created templates not updated in current and other user browser. After refreshing the page only, it's updated

## Current Behavior

After created card templates, sometimes created templates not updated in current and other user browser. After refreshing the page only, it's updated

## Screenshots (if appropriate):

![create template](https://user-images.githubusercontent.com/14290356/64160460-9775c600-ce59-11e9-8102-2ddfcaa55db7.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Card Template app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
