### ISSUE TITLE
In cards, same user has been displayed twice in votes

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3010]
## Expected Behavior

In cards, same user has been displayed twice in votes

## Current Behavior

In cards, same user has been displayed twice in votes

## Screenshots (if appropriate):

![votes_same user](https://user-images.githubusercontent.com/14290356/64161276-043d9000-ce5b-11e9-81ae-807c254d1441.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the commit https://github.com/RestyaPlatform/board/commit/07232aa02b89b35963fb7b4aa58851f5c68eba92 and it will be available in the upcoming release v0.6.8 (Roxette)
