### ISSUE TITLE
Sorting not working properly in checklist pending and completed count

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3011]
## Expected Behavior

Sorting not working properly in checklist pending and completed count

## Current Behavior

Sorting not working properly in checklist pending and completed count

## Screenshots (if appropriate):

![sorting](https://user-images.githubusercontent.com/14290356/64161343-1f100480-ce5b-11e9-8c8b-9269f19b0b4f.png)

**Comment by sridhar391** [comment]
Duplicate #3109 and hence the issue has been close

**Comment by srileka** [comment]
Issue not Fixed.

When we copy the card with checklist items, at the time "checklist pending count" sorting did not work properly

**Comment by sridhar391** [comment]
Issue Not Fixed

Case 1:  When we copy the card with checklist items, at the time "checklist pending count" sorting did not work properly
