### ISSUE TITLE
If we add the "webp" format file in add an attachment, added file image did not displayed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3017]
## Expected Behavior

If we add the "webp" format file in add an attachment, added file image did not displayed

## Current Behavior

If we add the "webp" format file in add an attachment, added file image did not displayed

## Screenshots (if appropriate):

![webp file](https://user-images.githubusercontent.com/14290356/64167004-f04b5b80-ce65-11e9-8ffe-97e66e25d97b.png)

**Comment by sridhar391** [comment]
@srileka The webp format file is not supported by browser. so, we are closing this issue
