### ISSUE TITLE
Cannot manually approve users

### ISSUE THREAD

**Issue by raphaelcasimir** [RestyaPlatform/board#302]
Hello,
I am in a very restricted workspace so I can't send e-mails from my servers. The admin has to manually approve the users, but the only thing he can do in restyaboard is unblock them. So they are able to login but can't be part of organisations since the member search doesn't find them.
Is there a mean to make them appear like confirmed users ?

Thanks by advance for your help.

**Comment by rrjanbiah** [comment]
@raphaelcasimir Sorry, this feature is currently not available. We didn't come across such use case as many people need LDAP only. Anyway thanks for reporting this. Based on demand, we'll prioritize this issue.

**Comment by raphaelcasimir** [comment]
Thanks

**Comment by raphaelcasimir** [comment]
Just a last try to make it work, I will be allowed to send e-mails froms the servers, but I cannot see where are the smtp mail settings are ! I searched everywere, and could only see some oauth settings... I don't know this protocol, is it used here to send mails ?

Thank you for your patience and kindness

**Comment by rrjanbiah** [comment]
@raphaelcasimir Restyaboard uses PHP's inbuilt `mail` function to send emails. That will use default mail server in the system. If you want to configure SMTP on your own, you have to check `php.ini`

Please feel free to post any issues that you face during setup process. We'll try to address that as early as possible.

**Comment by raphaelcasimir** [comment]
@rrjanbiah Thanks a lot, I configured mail and ssmtp and it works pretty well !

**Comment by rrjanbiah** [comment]
@raphaelcasimir Thanks for your update. Nice to know that.

**Comment by raphaelcasimir** [comment]
Another suggestion is about when you want to organize your board by organisations AND let everyone see what's inside, it is impossible.

**Comment by rrjanbiah** [comment]
@raphaelcasimir 

> Another suggestion is about when you want to organize your board by organisations AND let everyone see what's inside, it is impossible.

Thanks for your suggestion.

Are you talking about #129 ? We have fixed it in our `dev` branch. If that's not the case, can you please provide little more information?

**Comment by raphaelcasimir** [comment]
Yes exactly ! Do I need to switch to the dev branch and upgrade my version or is it unsafe ?

**Comment by rrjanbiah** [comment]
@raphaelcasimir We're in the final stage of this release. If possible, please wait for few more days.

**Comment by raphaelcasimir** [comment]
Ok

**Comment by Menomenta** [comment]
@rrjanbiah has it become possible to manually add / approve users by now?

**Comment by sridhar391** [comment]
Sure, we can add users in the users page by clicking Add user

![add_user](https://user-images.githubusercontent.com/17172525/36017823-58132a60-0d9f-11e8-9ae5-11597183f321.png)

then give the user credential for creating user

![user_add](https://user-images.githubusercontent.com/17172525/36017856-70dbf5f4-0d9f-11e8-9da1-4141878e1415.png)

also we can approve the users by selecting the user

![click_users](https://user-images.githubusercontent.com/17172525/36301337-75d5a07e-132a-11e8-8ff6-0b6e2110238b.png)

and In More Actions click Confirm Email for approval of that user

![confirm_mail](https://user-images.githubusercontent.com/17172525/36301615-798e83f6-132b-11e8-8ee9-7c5adbfe1094.png)

**Comment by chrisshixing** [comment]
who can tell me how to set imap in restsyboard? thank you so much!
