### ISSUE TITLE
In boards page, when we click the "today, doing or done", page did not redirecting to correct page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3025]
## Expected Behavior

In boards page, when we click the "today, doing or done", page did not redirecting to correct page

## Current Behavior

In boards page, when we click the "today, doing or done", page did not redirecting to correct page

## Screenshots (if appropriate):

![Boards_today](https://user-images.githubusercontent.com/14290356/64176839-df0d4980-ce7b-11e9-9dc6-f126d22ed953.png)

**Comment by sridhar391** [comment]
@srileka As it seems to be an elasticsearch server error, we have restarted the server and it's redirecting to the correct page
