### ISSUE TITLE
When we trying to open the board in without login, this console error thrown "Uncaught TypeError: Cannot read property 'id' of undefined"

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3031]
## Expected Behavior

When we trying to open the board in without login, this console error thrown "Uncaught TypeError: Cannot read property 'id' of undefined"

## Current Behavior

When we trying to open the board in without login, this console error thrown "Uncaught TypeError: Cannot read property 'id' of undefined"

## Screenshots (if appropriate):

![without login_board](https://user-images.githubusercontent.com/14290356/64240072-ed607180-cf1e-11e9-8e2c-17dabdb28261.png)

**Comment by sridhar391** [comment]
@srileka Fixed in the commit https://github.com/RestyaPlatform/board/commit/631e20958e40f4a638f04e0bf3a9fb0711b2e45e and it will be available on the upcoming release v0.6.8 (Roxette)
