### ISSUE TITLE
Other user (user not a member of the board), If we giving the value in "description" field, console error came and board not found

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3035]
## Expected Behavior

Other user (user not a member of the board), If we giving the value in "description" field, console error came and board not found

## Current Behavior

Other user (user not a member of the board), If we giving the value in "description" field, console error came and board not found

## Screenshots (if appropriate):

![other_desc](https://user-images.githubusercontent.com/14290356/64240435-7d9eb680-cf1f-11e9-9102-122cdfc88dfd.png)

**Comment by sridhar391** [comment]
Issue not fixed

**Comment by sridhar391** [comment]
Fixed in the `dev` branch and the fix will be available in the upcoming release v0.6.8 (Roxette)
