### ISSUE TITLE
When we click the download all attachments in card, page is redirecting to wrong page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3036]
## Expected Behavior

When we click the download all attachments in card, page is redirecting to wrong page

## Current Behavior

When we click the download all attachments in card, page is redirecting to wrong page

## Screenshots (if appropriate):

![download_1](https://user-images.githubusercontent.com/14290356/64240483-914a1d00-cf1f-11e9-99a7-578ea1c59958.png)

![download_2](https://user-images.githubusercontent.com/14290356/64240489-93ac7700-cf1f-11e9-9c3d-da11945a6eda.png)

**Comment by sridhar391** [comment]
@srileka Seems to be an configuration error and it has been fixed
