### ISSUE TITLE
In copy card, unable to select the "attachment" field at very first time. It has been displayed as not clickable

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3038]
## Expected Behavior

In copy card, unable to select the "attachment" field at very first time. It has been displayed as not clickable

## Current Behavior

In copy card, unable to select the "attachment" field at very first time. It has been displayed as not clickable

## Screenshots (if appropriate):

![copy_clickable](https://user-images.githubusercontent.com/14290356/64240612-cce4e700-cf1f-11e9-922d-dfacfe8e75e9.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the commit https://github.com/RestyaPlatform/board/commit/7f9aece926380b067e600fb754aedce6225eec51 and it will be available on the upcoming release v0.6.8 (Roxette)

**Comment by srileka** [comment]
Now also, In copy card, unable to select the "attachment" field at the very first time
