### ISSUE TITLE
Viewer role, add label option is disabled in admin side. So remove the add label button

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3040]
## Expected Behavior

Viewer role, add label option is disabled in admin side. So remove the add label button

## Current Behavior

Viewer role, add label option is disabled in admin side. So remove the add label button

## Screenshots (if appropriate):

![label](https://user-images.githubusercontent.com/14290356/64240720-061d5700-cf20-11e9-9565-61f28567c5c2.png)

**Comment by sridhar391** [comment]
Issue not fixed

**Comment by sridhar391** [comment]
Fixed the issue in the `dev` branch and the fix will be available in the upcoming release v0.6.8 (Roxette)
