### ISSUE TITLE
Viewer role, "add member" option option is disabled is admin side. Now also we try to add the member through the view member, console error thrown

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3041]
## Expected Behavior

Viewer role, "add member" option option is disabled is admin side. Now also we try to add the member through the view member, console error thrown

## Current Behavior

Viewer role, "add member" option option is disabled is admin side. Now also we try to add the member through the view member, console error thrown

## Screenshots (if appropriate):

![add member_viewer](https://user-images.githubusercontent.com/14290356/64240784-1f260800-cf20-11e9-8bec-ca97f259b6e7.png)

**Comment by sridhar391** [comment]
Issue not fixed

**Comment by sridhar391** [comment]
Fixed in the `dev` branch and the fix will be available in the upcoming release v0.6.8 (Roxette)
