### ISSUE TITLE
Viewer role user, when we trying to edit the start date, 401 authentication failed console error thrown

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3043]
## Expected Behavior

Viewer role user, when we trying to edit the start date, 401 authentication failed console error thrown

## Current Behavior

Viewer role user, when we trying to edit the start date, 401 authentication failed console error thrown

## Screenshots (if appropriate):

![start date_viewer](https://user-images.githubusercontent.com/14290356/64240919-69a78480-cf20-11e9-9503-6a90f94dd3fb.png)

**Comment by sridhar391** [comment]
@srileka Fixed in the Gantt View app local commit and it will be available in the upcoming release v0.6.8 (Roxette)

**Comment by sridhar391** [comment]
Issue not fixed

**Comment by sridhar391** [comment]
Fixed the issue in the `dev` branch and the fix will be available in the upcoming release v0.6.8 (Roxette)
