### ISSUE TITLE
In Filtering by cards and then refresh the page. Again when we click the filter cards, filtered values did not removed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3047]
# Expected Behavior

In Filtering by cards and then refresh the page. Again when we click the filter cards, filtered values did not removed

## Current Behavior

In Filtering by cards and then refresh the page. Again when we click the filter cards, filtered values did not removed

## Screenshots (if appropriate):

![filter cards_refresh](https://user-images.githubusercontent.com/14290356/64241135-c1de8680-cf20-11e9-86b4-298bfd345763.png)

**Comment by sridhar391** [comment]
Issue not fixed
