### ISSUE TITLE
Viewer role, add card option is disabled in admin side. But we able to add the card through instant add card

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3048]
## Expected Behavior

Viewer role, add card option is disabled in admin side. But we able to add the card through instant add card

## Current Behavior

Viewer role, add card option is disabled in admin side. But we able to add the card through instant add card

## Screenshots (if appropriate):

![add card_viewer](https://user-images.githubusercontent.com/14290356/64250552-0a536f80-cf34-11e9-9b9c-37ceebf34935.png)

**Comment by sridhar391** [comment]
Fixed the above issue in the Instant add card app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette) and now, if the user selects the board and haven't had the permission, then all options will be disabled
