### ISSUE TITLE
After added the list, added list did not displayed in instant add card. After refreshing the page, list updated

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3050]
## Expected Behavior

After added the list, added list did not displayed in instant add card. After refreshing the page, list updated

## Current Behavior

After added the list, added list did not displayed in instant add card. After refreshing the page, list updated

## Screenshots (if appropriate):

![list_instant add card](https://user-images.githubusercontent.com/14290356/64250611-35d65a00-cf34-11e9-9f2e-4c81a3f953cd.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the Instant Add Card app local commit and it will be available in the upcoming release v0.6.8 (Roxette)
