### ISSUE TITLE
In Instant add card, add the image and remove the image. Again when we add the image, added image did not displayed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3051]
## Expected Behavior

In Instant add card, add the image and remove the image. Again when we add the image, added image did not displayed

## Current Behavior

In Instant add card, add the image and remove the image. Again when we add the image, added image did not displayed

## Screenshots (if appropriate):

![add image_instant](https://user-images.githubusercontent.com/14290356/64250650-4edf0b00-cf34-11e9-8050-f5211c03cfcb.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Instant Add card app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
