### ISSUE TITLE
When we add the card using template through the instant add card, label design gets broken

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3052]
## Expected Behavior

When we add the card using template through the instant add card, label design gets broken

## Current Behavior

When we add the card using template through the instant add card, label design gets broken

## Screenshots (if appropriate):

![label_design](https://user-images.githubusercontent.com/14290356/64250681-661df880-cf34-11e9-968b-f9734325f5bc.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Instant add card app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
