### ISSUE TITLE
When we add the card using template through the instant add card, "labels and custom field values" are did not added

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3053]
## Expected Behavior

When we add the card using template through the instant add card, "labels and custom field values" are did not added

## Current Behavior

When we add the card using template through the instant add card, "labels and custom field values" are did not added

## Screenshots (if appropriate):

![instant_custom](https://user-images.githubusercontent.com/14290356/64250728-7df57c80-cf34-11e9-8482-97da77793149.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Instant add card app local commit and it will be available on the upcoming release v0.6.8 (Roxette)

**Comment by srileka** [comment]
When we add the card using template through the instant add card, "labels" are did not added

![labels_instant](https://user-images.githubusercontent.com/14290356/64951560-cd746a80-d89b-11e9-8572-0b831c6ddfbd.png)

**Comment by sridhar391** [comment]
@srileka We are closing this issue as we are not able to reproduce the issue, please feel free to reopen the issue if the issue occured again
