### ISSUE TITLE
After added the list, when we add the card through the instant add card, extra space has been displayed before the card

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3054]
## Expected Behavior

After added the list, when we add the card through the instant add card, extra space has been displayed before the card

## Current Behavior

After added the list, when we add the card through the instant add card, extra space has been displayed before the card

## Screenshots (if appropriate):

![extra space](https://user-images.githubusercontent.com/14290356/64250771-95cd0080-cf34-11e9-8925-b8a316573e30.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Instant Add Card app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
