### ISSUE TITLE
After added the card, card position wrong in current user

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3055]
## Expected Behavior

After added the card, card position wrong in current user. First add the list. Then add the card using instant add card and again add the card using "Add a card"

## Current Behavior

After added the card, card position wrong in current user

First add the list. Then add the card using instant add card and again add the card using "Add a card"

## Screenshots (if appropriate):

![card position](https://user-images.githubusercontent.com/14290356/64250817-b09f7500-cf34-11e9-81f5-609370f006f9.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Instant Add Card app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
