### ISSUE TITLE
When we add the due date through the instant add card, due date is wrong

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3056]
## Expected Behavior

When we add the due date through the instant add card, due date is wrong

## Current Behavior

When we add the due date through the instant add card, due date is wrong

## Screenshots (if appropriate):

![due date_instant](https://user-images.githubusercontent.com/14290356/64250846-c4e37200-cf34-11e9-95ad-9f7cba61a963.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Instant add card app local commit and the fix will be available in the upcoming release v0.6.8(Roxette)
