### ISSUE TITLE
When we add the due date through the instant add card, date format is wrong

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3057]
## Expected Behavior

When we add the due date through the instant add card, date format is wrong

## Current Behavior

When we add the due date through the instant add card, date format is wrong

## Screenshots (if appropriate):

![due date_format](https://user-images.githubusercontent.com/14290356/64250869-d6c51500-cf34-11e9-9f36-285848be7d5b.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Instant add card app local commit and it will be available on the upcoming release v0.6.8 (Roxette)

**Comment by srileka** [comment]
When we add the due date through the instant add card, the date format and time is wrong

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Instant add card app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)

**Comment by srileka** [comment]
Issue not Fixed
