### ISSUE TITLE
Admin users page, sorting not working properly

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3061]
## Expected Behavior

Admin users page, sorting not working properly

## Current Behavior

Admin users page, sorting not working properly

## Screenshots (if appropriate):

![sorting_users_admin](https://user-images.githubusercontent.com/14290356/64260590-c4ed6d00-cf48-11e9-9e80-1047eedb3fab.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the commit https://github.com/RestyaPlatform/board/commit/ec1a1f51516a2a868513ab12b005341c52d63fff and it will be available in the upcoming release v0.6.8 (Roxette)

**Comment by srileka** [comment]
Issue not fixed.
