### ISSUE TITLE
In organization member activity, load more activities button color is not there

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3062]
## Expected Behavior

In organization member activity, load more activities button color is not there

## Current Behavior

In organization member activity, load more activities button color is not there

## Screenshots (if appropriate):

![loan more activity](https://user-images.githubusercontent.com/14290356/64260635-dd5d8780-cf48-11e9-91ba-d8391464a474.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the commit https://github.com/RestyaPlatform/board/commit/ae27e87b01b0195c1b6a608531a54276a0389106 and it will be available on the upcoming release v0.6.8 (Roxette)
