### ISSUE TITLE
Organization and boards, owner and members count is not updated correctly

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3063]
## Expected Behavior

Organization and boards, owner and members count is not updated correctly

## Current Behavior

Organization and boards, owner and members count is not updated correctly

## Screenshots (if appropriate):

![org_count](https://user-images.githubusercontent.com/14290356/64260669-ee0dfd80-cf48-11e9-935d-18fd81a30322.png)

**Comment by sridhar391** [comment]
@srileka The users have the correct organisation count and board count
