### ISSUE TITLE
In boards page, organization sorting did not working properly

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3066]
## Expected Behavior

In boards page, organization sorting did not working properly

## Current Behavior

In boards page, organization sorting did not working properly

## Screenshots (if appropriate):

![org_sorting](https://user-images.githubusercontent.com/14290356/64260975-6379ce00-cf49-11e9-952f-85477b782e25.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the commit https://github.com/RestyaPlatform/board/pull/3230/commits/86b02e1e199a66997053b714d66cd9f258386eb8 and it will be available on the upcoming release v0.6.8 (Roxette)
