### ISSUE TITLE
Search did not working in boards page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3067]
## Expected Behavior

Search did not working in boards page

## Current Behavior

Search did not working in boards page

## Screenshots (if appropriate):

![boards_search](https://user-images.githubusercontent.com/14290356/64261014-77253480-cf49-11e9-88ec-0044704b7e74.png)

**Comment by sridhar391** [comment]
@srileka The Board name search is case sensitive and you have to search it with exact words like the board name
