### ISSUE TITLE
Open the one card and then minimize the card. At the time when we trying to add the label in another card, add label option did not displayed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3068]
## Expected Behavior

Open the one card and then minimize the card. At the time when we trying to add the label in another card, add label option did not displayed

## Current Behavior

Open the one card and then minimize the card. At the time when we trying to add the label in another card, add label option did not displayed

## Screenshots (if appropriate):

![add label](https://user-images.githubusercontent.com/14290356/64261100-9b811100-cf49-11e9-999f-879c9d725cac.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the dev branch and the fixes will be available on the upcoming release v0.6.8 (Roxette)
