### ISSUE TITLE
After added the card, card count did not update in open card

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3069]
## Expected Behavior

After added the card, card count did not update in open card

## Current Behavior

After added the card, card count did not update in open card

## Screenshots (if appropriate):

![open card_count](https://user-images.githubusercontent.com/14290356/64261152-ae93e100-cf49-11e9-8227-7c781a3ddc98.png)

**Comment by sridhar391** [comment]
@srileka We have fixed this issue in the v0.6.7 (Boney M) in the commit https://github.com/RestyaPlatform/board/commit/7594d944b7c89d99d37d3c5f2d5f496519b736ac
