### ISSUE TITLE
Deleted card count also has been displayed in open card

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3070]
## Expected Behavior

Deleted card count also has been displayed in open card

## Current Behavior

Deleted card count also has been displayed in open card

## Screenshots (if appropriate):

![delete card_open](https://user-images.githubusercontent.com/14290356/64261201-c79c9200-cf49-11e9-89ed-bdd34aa06199.png)

**Comment by srileka** [comment]
After deleting all the cards in archived items, card count is reduced in the open card. Card count should be reduced in archived card count

**Comment by srileka** [comment]
Issue not fixed.

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the dev branch and it will be available on the upcoming release v0.6.8 (Roxette)
