### ISSUE TITLE
If we enable the card counter app in admin side, "card counter" app did not displayed in apps

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3080]
## Expected Behavior

If we enable the card counter app in admin side, "card counter" app did not displayed in apps

## Current Behavior

If we enable the card counter app in admin side, "card counter" app did not displayed in apps

## Screenshots (if appropriate):

![card counter](https://user-images.githubusercontent.com/14290356/64318229-37a52980-cfd7-11e9-8bbb-d406c7d2a733.png)

**Comment by sridhar391** [comment]
@srileka Fixed in the board-apps repository in the commit https://github.com/RestyaPlatform/board-apps/pull/147/commits/2e1e3043c3eff3b6eb05d2de558b285c6552d1f8 and it will be available on the upcoming release v0.6.8 (Roxette)
