### ISSUE TITLE
Calendar view card color is did not working properly in admin settings

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3081]
## Expected Behavior

Calendar view card color is did not working properly in admin settings

## Current Behavior

Calendar view card color is did not working properly in admin settings

## Screenshots (if appropriate):

![calendar_settings](https://user-images.githubusercontent.com/14290356/64318286-57d4e880-cfd7-11e9-9586-0def0be8e338.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the dev branch and the fixes will be available on the upcoming relase v0.6.8 (Roxette)
