### ISSUE TITLE
When the user enable the two factor authentication, verification is not completed 

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3082]
## Expected Behavior

When the user enable the two factor authentication, verification is not completed 

## Current Behavior

When the user enable the two factor authentication, verification is not completed 

## Screenshots (if appropriate):

![two factor_verification](https://user-images.githubusercontent.com/14290356/64319839-e8f98e80-cfda-11e9-9144-8b0e40b5efe5.png)

**Comment by sridhar391** [comment]
@srileka Have to manually add the text to the [Google Authenticator app](https://support.google.com/accounts/answer/1066447?hl=en")  and enter the generated code in the Input field
