### ISSUE TITLE
After added the wiki, added wiki did not displayed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3083]
## Expected Behavior

After added the wiki, added wiki did not displayed

## Current Behavior

After added the wiki, added wiki did not displayed

## Screenshots (if appropriate):

![wiki](https://user-images.githubusercontent.com/14290356/64320138-7dfc8780-cfdb-11e9-95a6-057dd3397268.png)

**Comment by sridhar391** [comment]
@srileka It seems to be an SQL execution issue and we have fixed the issue
