### ISSUE TITLE
After imported QA checklist template, flash message did not closed automatically

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3084]
## Expected Behavior

After imported QA checklist template, flash message did not closed automatically

## Current Behavior

After imported QA checklist template, flash message did not closed automatically

## Screenshots (if appropriate):

![QA template_close](https://user-images.githubusercontent.com/14290356/64323971-22ce9300-cfe3-11e9-8674-80b37ce1b259.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Website QA Checklist app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
