### ISSUE TITLE
If we enable the board's bar, scrollbar hidden in board's page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3101]
## Expected Behavior

If we enable the board's bar, scrollbar hidden in board's page

## Current Behavior

If we enable the board's bar, scrollbar hidden in board's page

## Screenshots (if appropriate):

![scoll bar](https://user-images.githubusercontent.com/14290356/64472464-804a1780-d17c-11e9-8a27-43fc345d81dc.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Elasticsearch app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
