### ISSUE TITLE
In elastic search, "board:name" searching is did not working properly

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3104]
## Expected Behavior

In elastic search, "board:name" searching is did not working properly

## Current Behavior

In elastic search, "board:name" searching is did not working properly

## Screenshots (if appropriate):

![board name](https://user-images.githubusercontent.com/14290356/64589466-cee8f300-d3c2-11e9-8607-eb654263eca4.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Elastic search app local commit and it will be available in the upcoming release v0.6.8 (Roxette)
