### ISSUE TITLE
If we enable the board's bar in the admin side, the elastic search box has been hidden in the search result page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3106]
## Expected Behavior

If we enable the board's bar in the admin side, the elastic search box has been hidden in the search result page

## Current Behavior

If we enable the board's bar in the admin side, the elastic search box has been hidden in the search result page

## Screenshots (if appropriate):

![elastic_hidded](https://user-images.githubusercontent.com/14290356/64592132-edea8380-d3c8-11e9-803f-20f7c4e47f4f.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Elastic search app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
