### ISSUE TITLE
Dropbox app key is empty. Now also, dropbox option has been displayed in instant add card

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3110]
## Expected Behavior

Dropbox app key is empty. Now also, dropbox option has been displayed in instant add card

## Current Behavior

Dropbox app key is empty. Now also, dropbox option has been displayed in instant add card

## Screenshots (if appropriate):

![drop box_instant add card](https://user-images.githubusercontent.com/14290356/64617158-9a455d80-d3fb-11e9-818e-7e36345c368c.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Instant add card app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
