### ISSUE TITLE
Load more button did not display in archived cards

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3125]
## Expected Behavior

Load more button should be displayed in archived cards

## Current Behavior

Load more button did not display in archived cards

## Screenshots (if appropriate):

![load more_archive card](https://user-images.githubusercontent.com/14290356/64937825-6c3b9f80-d879-11e9-91ed-94b40a2fd7c2.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the commit cb9f90a and it will be available in the upcoming release v0.6.8 (Roxette)
