### ISSUE TITLE
An archived list, load more button did not work properly

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3126]
## Expected Behavior

An archived list, load more button did not work properly

## Current Behavior

An archived list, load more button did not work properly

## Screenshots (if appropriate):

![load more](https://user-images.githubusercontent.com/14290356/64937942-cccadc80-d879-11e9-9fb4-a2953431c8e6.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the commit https://github.com/RestyaPlatform/board/pull/3227/commits/cb9f90ab60e0b0d28de8eb8c7e26fb2d072203e8 and it will be available in the upcoming release v0.6.8 (Roxette)

**Comment by sridhar391** [comment]
Duplicate https://github.com/RestyaPlatform/board/issues/3092, hence issue closed
