### ISSUE TITLE
In add wiki, should disable the add wiki button after a single click

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3127]
## Expected Behavior

In add wiki, should disable the add wiki button after a single click

## Current Behavior

In add wiki, should disable the add wiki button after a single click

## Screenshots (if appropriate):

![add wiki](https://user-images.githubusercontent.com/14290356/64938015-11ef0e80-d87a-11e9-90d9-2e50edb1b242.png)

**Comment by sridhar391** [comment]
@srileka The above issue is fixed in the Wiki app local commit and it will be available on the upcoming version v0.6.8 (Roxette)

**Comment by srileka** [comment]
Issue not fixed.

**Comment by sridhar391** [comment]
@srileka The above issue is fixed in the Wiki app local commit and it will be available on the upcoming version v0.6.8 (Roxette)

**Comment by srileka** [comment]
Issue not Fixed.

**Comment by sridhar391** [comment]
@srileka The above issue is fixed in the Wiki app local commit and it will be available on the upcoming version v0.6.8 (Roxette)
