### ISSUE TITLE
After added the card, card count is did not updated in open card count. After doing some activities, card count updated

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3129]
## Expected Behavior

After added the card, card count is did not updated in open card count. After doing some activities, card count updated

## Current Behavior

After added the card, card count is did not updated in open card count. After doing some activities, card count updated

## Screenshots (if appropriate):

![card count_activirty](https://user-images.githubusercontent.com/14290356/64943092-71ecb180-d888-11e9-9003-4523e56069ba.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the 7594d944b7c89d99d37d3c5f2d5f496519b736ac and it is already fixed in the v0.6.7 release
