### ISSUE TITLE
In the admin users page, user sorting did not work properly

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3133]
## Expected Behavior

In the admin users page, user sorting did not work properly

## Current Behavior

In the admin users page, user sorting did not work properly

## Screenshots (if appropriate):

![admin user_sorting](https://user-images.githubusercontent.com/14290356/64954005-fc8dda80-d8a1-11e9-8739-6cbc5473ef81.png)

**Comment by srileka** [comment]
Issue not fixed.

Sorting not working properly in "organization, boards, login and registered"

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the commit https://github.com/RestyaPlatform/board/commit/c4fde80d826564455c81a8a6d1d60ad0f1fe8779 and it will be available on the upcoming release v0.6.8 (Roxette)
