### ISSUE TITLE
Open the one card and then minimize the card. At the time when we trying to add the label in another card, board labels are did not displayed in add labels

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3134]
## Expected Behavior

Open the one card and then minimize the card. At the time when we trying to add the label in another card, board labels are did not displayed in add labels

## Current Behavior

Open the one card and then minimize the card. At the time when we trying to add the label in another card, board labels are did not displayed in add labels

## Screenshots (if appropriate):

![add label_minimize](https://user-images.githubusercontent.com/14290356/64954498-63f85a00-d8a3-11e9-8624-706f9aca9f67.png)

**Comment by sridhar391** [comment]
Related https://github.com/RestyaPlatform/board/issues/3200

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the commit https://github.com/RestyaPlatform/board/commit/6aed2a93ed9ac89f5f35bdfb47efc770eeb42652 and it will be available in the upcoming release v0.6.8 (Roxette)
