### ISSUE TITLE
Comment replied activity content, has been displayed same as the comment added activity content. So need some difference in comment replied activity content

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3138]
## Expected Behavior

Comment replied activity content, has been displayed same as the comment added activity content. So need some difference in comment replied activity content

## Current Behavior

Comment replied activity content, has been displayed the same as the comment added activity content. So need some difference in comment replied activity content

## Screenshots (if appropriate):

![coment reply](https://user-images.githubusercontent.com/14290356/65013197-c3a04500-d937-11e9-9096-3ea38ab206c7.png)

**Comment by sridhar391** [comment]
@srileka As we are not mentioning the comment for which we are adding the reply, there will be no need for the activity to represent the reply for the particular comment
