### ISSUE TITLE
Change password doesn't work in 0.6.7

### ISSUE THREAD

**Issue by juniorUniv** [RestyaPlatform/board#3142]
Docker 18.09.0-0505
Restya 0.6.7 + PG 11.3.-1
Browser for Front End:
Chrome Version 77.0.3865.75

Change password feature doesn't work in 0.6.7. Event description:
1. change password function
2. screen is showed correctly (old, new, confirm new)
3. processed Change password
4. message from Restya = "Your old password is incorrect, please try again."

triple checked, changed browser (Chrome to IE Edge), same situation.

tested, if something had happened (in background), the existing psw is still valid.

**Comment by BlackDark** [comment]
Tested with #4013
Works locally for me.
Tested PG9 and PG11

@rrjanbiah assign me
