### ISSUE TITLE
In boards page notification, label deleted activity has been displayed wrong

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3145]
## Expected Behavior

In boards page notification, label deleted activity has been displayed wrong

## Current Behavior

In boards page notification, label deleted activity has been displayed wrong

## Screenshots (if appropriate):

![label delete_board activity](https://user-images.githubusercontent.com/14290356/65042198-fc5f0f00-d975-11e9-88d9-26e211ca9b81.png)

**Comment by sridhar391** [comment]
@srileka As likje trello we have added the activity for the deleted label in the board
