### ISSUE TITLE
In edit labels, if we edited the label name only. But label color also changed automatically

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3146]
## Expected Behavior

In edit labels, if we edited the label name only. But label color also changed automatically

## Current Behavior

In edit labels, if we edited the label name only. But label color also changed automatically

## Screenshots (if appropriate):

![label_edit](https://user-images.githubusercontent.com/14290356/65044303-4944e480-d97a-11e9-8161-d420697d0acb.png)

**Comment by sridhar391** [comment]
@srileka While adding the labels to the card, the label color shown based on the label name and if you haven't set any color to the label and if you rename the label, then the label color will change based on the label name
