### ISSUE TITLE
If we changing the custom field color, color did not update in card front page. After refreshing the page, color updated in card front page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3148]
## Expected Behavior

If we changing the custom field color, color did not update in card front page. After refreshing the page, color updated in card front page

## Current Behavior

If we changing the custom field color, color did not update in card front page. After refreshing the page, color updated in card front page

## Screenshots (if appropriate):

![custom field_color](https://user-images.githubusercontent.com/14290356/65120619-8b6a3680-da0b-11e9-963c-327fea4721f8.png)

**Comment by jawahar336** [comment]
@srileka  Fixed the above issue in the Custom field app local commit and it will be available on the upcoming release v0.6.8 (Roxette)

**Comment by srileka** [comment]
Issue not fixed.

If we changing the custom field color, color has been update in particular card only. After refreshing the page, color has been update in remaining cards in the board

**Comment by sridhar391** [comment]
@srileka We have fixed the above issue and if the custom fields color has been edited or custom field visibility has been edited, it will be reflected on all the cards.
