### ISSUE TITLE
When we giving the date and time value in the custom field, "undefined" has been displayed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3149]
## Expected Behavior

When we giving the date and time value in the custom field, "undefined" has been displayed

## Current Behavior

When we giving the date and time value in the custom field, "undefined" has been displayed

## Screenshots (if appropriate):

![date and time_undefined](https://user-images.githubusercontent.com/14290356/65120720-b3599a00-da0b-11e9-8307-8b4dcd41fb01.png)

**Comment by sridhar391** [comment]
@srileka We have fixed the above issue in the Custom Fields app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
