### ISSUE TITLE
In the custom field, give the value and click submit button. After clicking the submit button, custom field box should be closed automatically

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3150]
## Expected Behavior

In the custom field, give the value and click submit button. After clicking the submit button, custom field box should be closed automatically

## Current Behavior

In the custom field, give the value and click submit button. After clicking the submit button, custom field box should be closed automatically

## Screenshots (if appropriate):

![custom_submit](https://user-images.githubusercontent.com/14290356/65120801-d5ebb300-da0b-11e9-91f1-d4465df0b8f0.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Custom Fields app local commit and the fixes will be available on the upcoming release v0.6.8 (Roxette)
