### ISSUE TITLE
While unsubscribing the list, this console error is thrown"Uncaught ReferenceError: subscribe is not defined"

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3154]
## Expected Behavior

While unsubscribing the list, this console error is thrown"Uncaught ReferenceError: subscribe is not defined"

## Current Behavior

While unsubscribing the list, this console error is thrown"Uncaught ReferenceError: subscribe is not defined"

## Screenshots (if appropriate):

![unsubscribe](https://user-images.githubusercontent.com/14290356/65129620-4e0ca580-da19-11e9-82ac-42b200a4f5ad.png)

**Comment by sridhar391** [comment]
@srileka Fixed in the dev branch and it will be available on the upcoming release v0.6.8 (Roxette)
