### ISSUE TITLE
When we open the card in Gantt view, console error is thrown Uncaught TypeError: Cannot read property 'set' of undefined

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3161]
## Expected Behavior

When we open the card in Gantt view, console error is thrown Uncaught TypeError: Cannot read property 'set' of undefined

## Current Behavior

When we open the card in Gantt view, console error is thrown Uncaught TypeError: Cannot read property 'set' of undefined

## Screenshots (if appropriate):

![gantt_console](https://user-images.githubusercontent.com/14290356/65148946-ce91cd00-da3e-11e9-9813-4b9beb44ddd5.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)
