### ISSUE TITLE
When we click the search cards text box,  all the cards in the current board should be display

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3163]
## Expected Behavior

When we click the search cards text box,  all the cards in the current board should be display

## Current Behavior

When we click the search cards text box,  all the cards in the current board should be display

## Screenshots (if appropriate):

![search cards](https://user-images.githubusercontent.com/14290356/65150366-9a6bdb80-da41-11e9-8ba2-8c2ffbdd1bc4.png)

**Comment by jawahar336** [comment]
@srileka  Added the above enhancement in the Gantt View app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
