### ISSUE TITLE
When we add the card through "instant add card and convert to card in checklist item", Default sort for cards did not work properly

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3167]
## Expected Behavior

When we add the card through "instant add card and convert to card in checklist item", Default sort for cards did not work properly

## Current Behavior

When we add the card through "instant add card and convert to card in checklist item", Default sort for cards did not work properly

## Screenshots (if appropriate):

![default sort_add card](https://user-images.githubusercontent.com/14290356/65234164-b2029d00-daf1-11e9-8112-d75786c732b1.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Instant Add card app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
