### ISSUE TITLE
Grid view and list view column value did not update properly in other user browser

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3169]
## Expected Behavior

Grid view and list view column value did not update properly in other user browser

## Current Behavior

Grid view and list view column value did not update properly in other user browser

## Screenshots (if appropriate):

![grid view_value_other](https://user-images.githubusercontent.com/14290356/65234288-e8d8b300-daf1-11e9-8efc-82ff6825d966.png)

**Comment by sridhar391** [comment]
@srileka As like trello, we are updating the fields in the board.

**Comment by sridhar391** [comment]
Duplicate https://github.com/RestyaPlatform/board/issues/2885, hence issue closed

**Comment by srileka** [comment]
Issue Not Fixed.

**Comment by sridhar391** [comment]
@srileka In the edit form of Grid view and List View configure in the board header settings, the changes will not be applied due to the current user changes in the edit form will be lost.
