### ISSUE TITLE
When we add the label in the numeric letter, label did not update proper order in current user and other user browsers

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3170]
## Expected Behavior

When we add the label in the numeric letter, label did not update proper order in current user and other user browsers

## Current Behavior

When we add the label in the numeric letter, label did not update proper order in current user and other user browsers

## Screenshots (if appropriate):

![label_numeric](https://user-images.githubusercontent.com/14290356/65234327-fdb54680-daf1-11e9-93de-4964210b75ab.png)

**Comment by sridhar391** [comment]
@srileka If the labels added with only numerical number, it will be ordered in this manner only

**Comment by sridhar391** [comment]
The labels should be ordered by the created time like Trello
