### ISSUE TITLE
Other user (user not a member of the board) When we trying to minimize or maximize the list, it's not working

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3171]
## Expected Behavior

Other user (user not a member of the board) When we trying to minimize or maximize the list, it's not working

## Current Behavior

Other user (user not a member of the board) When we trying to minimize or maximize the list, it's not working

## Screenshots (if appropriate):

![mini_other](https://user-images.githubusercontent.com/14290356/65234411-23dae680-daf2-11e9-8780-adb66845d25d.png)

**Comment by sridhar391** [comment]
If the owner member minimizes the list, the expand icon shown to another member without permission
