### ISSUE TITLE
Other user (user not a member of the board) When we trying to  open the board, "all" activities did not displayed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3172]
## Expected Behavior

Other user (user not a member of the board) When we trying to  open the board, "all" activities did not displayed

## Current Behavior

Other user (user not a member of the board) When we trying to  open the board, "all" activities did not displayed

## Screenshots (if appropriate):

![all](https://user-images.githubusercontent.com/14290356/65234471-45d46900-daf2-11e9-9a65-9fb94e0ec945.png)

**Comment by sridhar391** [comment]
Sometimes, for current user, "all" activities did not displayed

**Comment by sridhar391** [comment]
We are closing this issue as we are not able to reproduce the issue
