### ISSUE TITLE
In calendar view, if we "add, edit or remove" the start date and due date in the model card, the date did not update properly

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3173]
## Expected Behavior

In calendar view, if we "add, edit or remove" the start date and due date in the model card, the date did not update properly

## Current Behavior

In calendar view, if we "add, edit or remove" the start date and due date in the model card, the date did not update properly

## Screenshots (if appropriate):

![date_calne](https://user-images.githubusercontent.com/14290356/65234572-76b49e00-daf2-11e9-9105-feaadf291d5e.png)

**Comment by sridhar391** [comment]
Related #3174
