### ISSUE TITLE
After added the board, when we trying to add the card through instant add card "created board" did not displayed. After refreshing the page only, board has been displayed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3183]
## Expected Behavior

After added the board, when we trying to add the card through instant add card "created board" did not displayed. After refreshing the page only, board has been displayed

## Current Behavior

After added the board, when we trying to add the card through instant add card "created board" did not displayed. After refreshing the page only, board has been displayed

## Screenshots (if appropriate):

![board_instant add card](https://user-images.githubusercontent.com/14290356/65328647-65dc5900-dbd4-11e9-8b4c-bc8b6535f543.png)

**Comment by jawahar336** [comment]
@srileka Fixed the above issue in the Instant Add card app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
