### ISSUE TITLE
When we linked to the one card to another card, at the time we unable to see the existing labels in the board

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3193]
## Expected Behavior

When we linked to the one card to another card, at the time we unable to see the existing labels in the board

## Current Behavior

When we linked to the one card to another card, at the time we unable to see the existing labels in the board

## Screenshots (if appropriate):

![existing_1](https://user-images.githubusercontent.com/14290356/65482708-91529280-deb7-11e9-83d4-ed2af5b51bce.png)

![existing_2](https://user-images.githubusercontent.com/14290356/65482715-94e61980-deb7-11e9-9617-d9b165f302e3.png)

**Comment by sridhar391** [comment]
Realted https://github.com/RestyaPlatform/board/issues/3200

**Comment by sridhar391** [comment]
Fixed the above issue in the commit https://github.com/RestyaPlatform/board/commit/6aed2a93ed9ac89f5f35bdfb47efc770eeb42652
