### ISSUE TITLE
If we open the linked card in the comment and close the linked card, check the label design in model card page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3194]
## Expected Behavior

If we open the linked card in the comment and close the linked card, the label dropdown should not be opened

## Current Behavior

If we open the linked card in the comment and close the linked card, check the label design in model card page

## Screenshots (if appropriate):

![label design](https://user-images.githubusercontent.com/14290356/65482764-b34c1500-deb7-11e9-801e-2a27a05baa8c.png)

**Comment by sridhar391** [comment]
Realted #3200

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the commit https://github.com/RestyaPlatform/board/commit/6aed2a93ed9ac89f5f35bdfb47efc770eeb42652 and it will be available in the upcoming release v0.6.8 (Roxette)
