### ISSUE TITLE
In model card page, if we click the dropdown list and close the model card, check the label design

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3195]
## Expected Behavior

In model card page, if we click the dropdown list and close the model card, check the label design

## Current Behavior

In model card page, if we click the dropdown list and close the model card, check the label design

## Screenshots (if appropriate):

![dropdown_design](https://user-images.githubusercontent.com/14290356/65482804-da0a4b80-deb7-11e9-9858-5d86550e71e2.png)

![dropdown_design1](https://user-images.githubusercontent.com/14290356/65482808-dd053c00-deb7-11e9-8531-b7676c72f8d5.png)

**Comment by jawahar336** [comment]
@srileka Fixed the above issue on the Custom Fields app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
