### ISSUE TITLE
Other user (user not a member of the board), custom field and label options are did not displayed in model card page. But custom field value has been displayed card front page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3196]
## Expected Behavior

Other user (user not a member of the board), custom field and label options are did not displayed in model card page. But custom field value has been displayed card front page

## Current Behavior

Other user (user not a member of the board), custom field and label options are did not displayed in model card page. But custom field value has been displayed card front page

## Screenshots (if appropriate):

![other_custom and label](https://user-images.githubusercontent.com/14290356/65482847-f4dcc000-deb7-11e9-9830-8e0ce5a15db9.png)

**Comment by sridhar391** [comment]
@srileka As like trello, in the Public board, if the card has the labels and custom fields values in it , then it will be shown in front of the card
