### ISSUE TITLE
In model card page, first member name hidden 

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3198]
## Expected Behavior

In model card page, first member name hidden 

## Current Behavior

In model card page, first member name hidden 

## Screenshots (if appropriate):

![member name_hidden](https://user-images.githubusercontent.com/14290356/65482913-26558b80-deb8-11e9-9593-f2ff87e69bca.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the commit https://github.com/RestyaPlatform/board/commit/d8eea7a31d336c4d794b88a609189b900361e755 and it will be available in the upcoming release v0.6.8 (Roxette)
