### ISSUE TITLE
In model card, we unable to see the existing labels in current board

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3200]
## Expected Behavior

In model card, we unable to see the existing labels in current board

## Current Behavior

In model card, we unable to see the existing labels in current board

Case 1: First open  the one model card and then open the another card. At the time, unable to see the label in current card

Case 2: If we open the instant add card, at the time unable to see the label in current card

## Screenshots (if appropriate):

![label_unable to see](https://user-images.githubusercontent.com/14290356/65482971-4c7b2b80-deb8-11e9-917b-1d34a2f9dbbf.png)

**Comment by sridhar391** [comment]
Duplicate https://github.com/RestyaPlatform/board/issues/3134, hence issue closed
