### ISSUE TITLE
Other user(user not a member of the board) tries to access the public board, board labels are did not displayed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3222]
## Expected Behavior

Other user(user not a member of the board) tries to access the public board, board labels are did not displayed

## Current Behavior

Other user(user not a member of the board) tries to access the public board, board labels are did not displayed

## Screenshots (if appropriate):

![board labels](https://user-images.githubusercontent.com/14290356/65671523-0ca57700-e065-11e9-865d-d15d700754f4.png)

**Comment by sridhar391** [comment]
@srileka For viewing the card labels in the board, you should have to be a board member and you should have the permission for `View card labels` for your board roles
