### ISSUE TITLE
If we click the date field in custom field and then scroll, check the date picker alignment

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3223]
## Expected Behavior

If we click the date field in custom field and then scroll, check the date picker alignment

## Current Behavior

If we click the date field in custom field and then scroll, check the date picker alignment

## Screenshots (if appropriate):

![scroll](https://user-images.githubusercontent.com/14290356/65671636-35c60780-e065-11e9-8898-ffc753aed58a.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Custom Fields app local commit and it will be available on the upcoming release v0.6.8 (Roxette)
