### ISSUE TITLE
email notification not working

### ISSUE THREAD

**Issue by mabulhija** [RestyaPlatform/board#3231]
## Expected Behavior

receive emails after configure smtp settings in admin console

## Current Behavior

currently no emails are being sent for any action
## Possible Solution

in the installation script no email configuration was done, after system is up and running, i updated the smtp in the settings menu, but nothing happened.

i have followed couple of comments on github, google forms and internet but no luck
i have configured postfix on my environment, php.ini file as well.
i noticed that links mentioned in crontab below do not exists
```
*/5 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/instant_email_notification.sh > /dev/null 2> /dev/null
0 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/periodic_email_notification.sh > /dev/null 2> /dev/null
*/30 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/imap.sh > /dev/null 2> /dev/null
*/5 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/webhook.sh > /dev/null 2> /dev/null
*/5 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/card_due_notification.sh > /dev/null 2> /dev/null 
```

## Context

the issue makes it difficult for the team to be informed about any changes, with so many changes its hard to check each board/card for changes.

im trying to enable email notifications for all actions related to boards/cards so the team can be informed of any change 

## Your Environment

* Version used: 0.6.7
* Environment name and version (e.g. OS, PHP, PostgreSQL): ubuntu 18.04, php 7.2.22, postgresSQL 10.10, nginx 1.14.0, apache2 2.4.29
* Operating System and version (desktop or mobile): desktop
* Link to your project: none (local)

**Comment by sridhar391** [comment]
@mabulhija In installation script file, we have added the code for setting up the crontab at  the line https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh#L753 and you should have to add the below code in your crontab for email notifications
`*/5 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/main.sh > /dev/null 2> /dev/null`

**Comment by mabulhija** [comment]
@sridhar391 thanks for the reply. i have added the entry you mentioned in the crontab, however i'm still missing something, since the notifications are not being sent.

this is what i did so far
1. configure IMAP Settings in admin page with external SMTP details
2. modified the crontab to add the entry you mentioned
3. configured postfix (used same details for SMTP i used in admin page)

modify cards, boards to generate change - no email notifications
send mail through postfix and mailutils - email received normally
run main.sh, script run fine no error on terminal - no email
run main.php, script run fine no error on terminal - no email
run instant_email_notification.php, script run fine no error on terminal - no email

entries in crontab
```
*/5 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/main.sh > /dev/null 2> /dev/null
*/5 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/instant_email_notification.sh > /dev/null 2> /dev/null
0 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/periodic_email_notification.sh > /dev/null 2> /dev/null
*/30 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/imap.sh > /dev/null 2> /dev/null
*/5 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/webhook.sh > /dev/null 2> /dev/null
*/5 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/card_due_notification.sh > /dev/null 2> /dev/null
```
postfix is owned by root
`drwxr-xr-x  5 root root     4096 Oct  1 07:51 postfix`

the system is owned by administrator (no other user on the system)
```
-rw-r--r-- 1 administrator administrator  3879 Sep  9 19:03 card_due_notification.php
-rw-r--r-- 1 administrator administrator  2028 Sep  9 19:03 cron_mail.php
-rw-r--r-- 1 administrator administrator 22149 Sep  9 19:03 imap.php
-rw-r--r-- 1 administrator administrator 33615 Sep  9 19:03 instant_email_notification.php
-rw-r--r-- 1 administrator administrator   901 Sep  9 19:03 main.php
-rwxr-xr-x 1 administrator administrator   867 Sep  9 19:03 main.sh
-rw-r--r-- 1 administrator administrator 35886 Sep  9 19:03 periodic_email_notification.php
-rw-r--r-- 1 administrator administrator  4479 Sep  9 19:03 webhook.php
```
thanks for the support

**Comment by sridhar391** [comment]
@mabulhija Can you please remove the below crontab commands from the crontab and can you please apply executable permission to the `main.sh` file by executing the command `chmod +x /usr/share/nginx/html/restyaboard/server/php/shell/main.sh` and manually execute the shell script file by executing the command `sudo ./main.sh` and please tell us if there is any issues shown while executing the shell script file and also, can you please tell us if there is any error logged in the `var/log/mail.log` file.

```
*/5 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/instant_email_notification.sh > /dev/null 2> /dev/null
0 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/periodic_email_notification.sh > /dev/null 2> /dev/null
*/30 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/imap.sh > /dev/null 2> /dev/null
*/5 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/webhook.sh > /dev/null 2> /dev/null
*/5 * * * * /usr/share/nginx/html/restyaboard/server/php/shell/card_due_notification.sh > /dev/null 2> /dev/null
```

**Comment by mabulhija** [comment]
@sridhar391 i have removed the mentioned entries and changed the file to executable, i saw some errors in the log file although a moment back i received 3 emails (there should be more emails), however my teammate didn't receive anything.

log is attached, i modified email addresses for anonymity.
 
[log.txt](https://github.com/RestyaPlatform/board/files/3674462/log.txt)

**Comment by sridhar391** [comment]
@mabulhija We have analyzed the log file and it seems that you are using the `IMAP` server for sending mail notification and you have to use the SMTP to send mail notifications and please refer the below link 

https://www.linode.com/docs/email/postfix/postfix-smtp-debian7/

**Comment by mabulhija** [comment]
@sridhar391 apologies for the late reply. i have applied the settings as you mentioned but im traveling currently i will check the server once im back, thank you very much i will update this once im back.

**Comment by mabulhija** [comment]
@sridhar391, thank you very much, issue is now resolved.

**Comment by sridhar391** [comment]
@sridhar391 Thanks for the confirmation of the issue fix.
