### ISSUE TITLE
Emails are not working in DigitalOcean droplet

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#3249]
Some customers are reporting that emails are not working in DigitalOcean droplet

**Comment by sridhar391** [comment]
@rrjanbiah We have checked the email notifications with IP address as Restyaboard URL in the Digital Ocean and we are receiving the mail notifications in the SPAM folder and some users are receiving the email notification and some users are  using the mail from their domain and they should have to check the firewall for allowing the email notification.

**Comment by rrjanbiah** [comment]
Closing this in favor of #3264
