### ISSUE TITLE
SQL error: column "is_expirable_token" does not exist

### ISSUE THREAD

**Issue by macno** [RestyaPlatform/board#3263]
## Expected Behavior
No sql error in logs

## Current Behavior
In logs I see:

```
2019/10/12 18:24:44 [error] 66#66: *145 FastCGI sent in stderr: "PHP message: PHP Warning:  pg_query_params(): Query failed: ERROR:  column &quot;is_expirable_token&quot; does not exist
LINE 1: SELECT is_expirable_token FROM oauth_clients WHERE client_id...
                ^ in /usr/share/nginx/html/server/php/libs/core.php on line 568
PHP message: PHP Warning:  pg_num_rows() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/server/php/libs/core.php on line 569" while reading response header from upstream, client: 172.18.0.2, server: localhost, request: "GET /api/v1/users/1/activities.json?type=all&last_activity_id=4&direction=ASC&token=c3c804e3033f34258b1f494eed151e74324f3dec&_=1570904684406 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "restyaboard.authkeys.io", referrer: "https://restyaboard.authkeys.io/"
```

## Possible Solution
Fix upgrade script adding the missing column

## Steps to Reproduce (for bugs)

1. start a new instance with docker: `restyaplatform/restyaboard:dev` 
2. add a new user
3.
4.

## Context
New installation

## Your Environment

* Version used: `restyaplatform/restyaboard:dev`
* Environment name and version (e.g. OS, PHP, PostgreSQL):
docker-compose:
```
version: '3'

networks:
  http_network:
    external: true
  db_network:
    external: false
services:
  restyaboard:
    image: restyaplatform/restyaboard:dev
    environment:
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - SMTP_DOMAIN
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_SERVER
      - SMTP_PORT
      - TZ
    volumes:
    - ./data/media:/usr/share/nginx/html/media
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${FQDN}
      - traefik.docker.network=http_network
    networks:
      - http_network
      - db_network
  postgres:
    image: postgres:9-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    volumes:
    - ./data/db:/var/lib/postgresql/data
    networks:
      - db_network
```

**Comment by macno** [comment]
I discovered there are 2 more scripts to run: 0.6.6-0.6.7 and 0.6.7-0.6.8

https://hub.docker.com/r/restyaplatform/restyaboard overview must be updated to include them

**Comment by sridhar391** [comment]
@macno In each Restyaboard version release, we will update the required fields in the installation script and we will update the script in the upcoming release v0.6.8 (Roxette)

**Comment by BlackDark** [comment]
Updated README and added reference that all new SQL scripts have to be applied in order to migrate DB. See https://hub.docker.com/r/restyaplatform/restyaboard

@sridhar391 assign me and close issue.

![image](https://user-images.githubusercontent.com/9947112/77835283-8ff67100-714b-11ea-86a8-8a18f3bb7fbf.png)
