### ISSUE TITLE
Documentation on SPF and DKIM to handle emails (avoid spam flags)

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#3264]
Need to document on how to setup SPF and DKIM (or at least give link to other documents)

* https://www.digitalocean.com/community/tutorials/how-to-create-a-spf-record-for-your-domain-with-google-apps
* https://www.digitalocean.com/community/questions/how-do-i-setup-spf-on-my-droplet
* https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-dkim-with-postfix-on-debian-wheezy
* https://www.digitalocean.com/community/questions/dkim-on-dns-panel-digitalocean

**Comment by sridhar391** [comment]
Added the document about how to add SPF and DKIM to handle emails and the documentation link is https://restya.com/board/docs/mailserver-configuration/#3
