### ISSUE TITLE
New Items (eg boards) are flagged "2 hours ago"

### ISSUE THREAD

**Issue by heitmanr** [RestyaPlatform/board#3274]
All activities shown with wrong time/delta-time.

## Expected Behavior
i add something and the correct time is shown for this activity.

## Current Behavior
i add something and the delta-time is shown from my timezone to UTC.

## Screenshots (if appropriate):
these activities have been completed a second ago, not 2 hours:
![restya-2-hours-ago](https://user-images.githubusercontent.com/26636908/66873643-3ccba000-efa9-11e9-9d43-5843dab05d50.png)

## Steps to Reproduce (for bugs)
* set timezone to GMT+2
Linux: sudo timedatectl set-timezone Europe/Copenhagen
* set user-timezone to GMT+2 in the Restyaboard-GUI
the common shown "site-timezone"-setting has gone in the current release
there is a "timezone"-setting in the user-settings - set to GMT+2, too

## Your Environment
Linux Server 18.04

**Comment by sridhar391** [comment]
@ron4all Can you please tell us if the user has set the timezone to GMT+2 Europe/Copenhagen in his profile settings page like the attached below image.

![user_timezone](https://user-images.githubusercontent.com/17172525/66888236-5dbce100-effb-11e9-8c34-9be483e5d974.png)

**Comment by ron4all** [comment]
@sridhar391 yes - the `system.settings.timezone` has been set to _GMT+2_ and the `user.settings.timezone` of _all users_ have been already set to _GMT+2_, too.

**Comment by sridhar391** [comment]
@ron4all Related https://github.com/RestyaPlatform/board/issues/3046 and the fix will be available in the upcoming release v0.6.8 (Roxette)

**Comment by ron4all** [comment]
@sridhar391 (just as a note:) I've been deleting the whole VM, setting it up completely new and the timestamps are working fine.

* what's the difference between both installations
=> at the new setup i did "`sudo timedatectl set-timezone Europe/Berlin`" before installing restya using the install-shell-script

at the first setup, i've been
a) setting up restya first
b) changing restya-timezone to GMT+2/Berlin
c) adding users with timezone GMT+2/Berlin
d) noticed the +2 time-difference displayed for all activities
e) configured "sudo timedatectl..."
f) it was too late ,-) +2h time-difference still in place for all activities

**Comment by sridhar391** [comment]
@ron4all In the database, we store the activity with server timezone dates and when you change the server timezone, the activities will be shown with different time variation and in this version, we have handled the activity with the Restyaboard user timezone and the Restyaboard timezone

**Comment by sridhar391** [comment]
@heitmanr Due to inactivity, we are closing this issue, if the issue occurred again, please feel free to reopen the issue
