### ISSUE TITLE
Outgoing eMail fails

### ISSUE THREAD

**Issue by heitmanr** [RestyaPlatform/board#3275]
the receiving mail-server blocks all mails to user-accounts since my IP is a customer-internet-access and the whole ISP-Address-Range has been blacklisted, on purpuse to block spam.

## Expected Behavior
restyaboard might use a common email-client for outgoing mails, with encrypted mail

## Current Behavior
restyaboard uses a local mail-server, unauthenticated and clear-text protocol settings for outgoing mails.

## 212.227.15.9 is the german "gmx"-Mailserver
```
user@restya:~$ sudo tcpdump tcp -n -vv host 212.227.15.9
...
21:21:20.278377 IP (tos 0x0, ttl 53, id 25158, offset 0, flags [DF], proto TCP (6), length 257)
    212.227.15.9.25 > 192.168.0.23.57030: Flags [P.], cksum 0x94e9 (correct), seq 1:206, ack 1, win 57, options [nop,nop,TS val 2554449015 ecr 3855461716], length 205: SMTP, length: 205
        554-gmx.net (mxgmx016) Nemesis ESMTP Service not available
        554-No SMTP service
        554-IP address is black listed.
        554 For explanation visit http://postmaster.gmx.com/en/error-messages?ip=31.16.73.188&c=bl

```
## Possible Solution
Make the outgoing-mail-function configurable, 
[x] use standard mail-client
[x] use encrypted smtp
[x] use authenticated smtp

## Steps to Reproduce (for bugs)
default-install
at site with residential-IP-Address
add user
start tcpdump at the shell
the email containing the "activation"-link will get blocked

## Context
blocks effectively adding new users since there is no manual activation-feature.

## Your Environment
ubuntu server 18.04, fresh-install, restya-setup using the "shell-script"

**Comment by sridhar391** [comment]
@ron4all Please setup the SMTP mail server with your domain instead of IP address and please add DKIM & SPF setup

**Comment by ron4all** [comment]
@sridhar391 which mail-server do you mean?
a) the mail-server installed by restyaboard - i assume this, but i don't find any configuration dialog within restyaboard. 
- btw. this is a residential site: no domain, just a public IP at the NAT-Router
or
b) the mail-server containing the receivers mail-box (in the example @gmx.de) which is public and out of reach.

**Comment by sridhar391** [comment]
@ron4all Postfix mail server is installed while installing the Restyaboard and please refer the below link for how to configure the mail server
https://www.linode.com/docs/email/postfix/postfix-smtp-debian7/

**Comment by ron4all** [comment]
@sridhar391 since this is a residential site, i don't have a domain-name so the guide fails since it's impossible to met the prerequisites afaik!?

...
PrerequisitesPermalink
---
Before starting this tutorial, you should have:
    Your fully qualified domain name (FQDN)
---

my local dns uses the domain "lab.local", i shouldn't waste time to try this for the postfix-setup ;-)

the restya-email-address is something like
* restyaboard@gmx.de
the receiving user is something like
* user1name@gmx.de

I don't own the domain "gmx.de" - this is a public email-provider.

I'd prefer restyaboard to use an email-client-functionality with an outgoing-email-account configured containing email-username and email-password and in 2019 with fully encrypted SMTP (SMPTS/587).

**Comment by sridhar391** [comment]
@ron4all Currently there is no settings in the Restyaboard for email-client-functionality with an outgoing-email-account configured containing email-username and email-password and the postfix is  installed while installing Restyaboard and you just have to configure SMTP server

**Comment by rrjanbiah** [comment]
@ron4all 

If I understand right, sending email from non-gmx.de but using gmx.de email is causing the issue... especially when it doesn't have any domain. 

* Can you try using any other from email address?
* Or, try using third party SMTP like sendgrid? (You have to enter sendgrid SMTP details in postfix)

**Comment by ron4all** [comment]
btw. i found it easier to fix the original-problem (using a mail-server to send mails which seems to be a mail-client function):
* using PHPMailer

Prepare:
```
cd ~
wget https://github.com/PHPMailer/PHPMailer/archive/v5.2.23.zip
unzip *.zip

cd /usr/share/nginx/html/restyaboard/server/php/libs
cp ~/PHPMailer-5.2.23/class.phpmailer.php ./
sudo cp ~/PHPMailer-5.2.23/class.phpmailer.php ./
sudo cp ~/PHPMailer-5.2.23/class.smtp.php ./

```
user@restya:/usr/share/nginx/html/restyaboard/server/php/libs$ ls *.php -l
-rw-r--r-- 1 root root   8935 Oct 20 21:49 ActivityHandler.php
-rw-r--r-- 1 root root 146762 Oct 29 14:01 class.phpmailer.php
-rw-r--r-- 1 root root  42430 Oct 29 14:02 class.smtp.php
-rw-r--r-- 1 root root 146883 Oct 29 15:29 core.php

Edit "core.php"

1.  Add the "require"-statements:
```
<?php
require_once('class.phpmailer.php');
require_once('class.smtp.php');
```

2.  Replace the PHP-Mail-Routine:

```
function sendMail($template, $replace_content, $to, $reply_to_mail = '')
{
    global $r_debug, $db_lnk, $_server_domain_url;
    if (file_exists(SITE_URL_FOR_SHELL)) {
        include_once SITE_URL_FOR_SHELL;
    }
    $default_content = array(
        '##SITE_NAME##' => SITE_NAME,
        '##SITE_URL##' => $_server_domain_url,
        '##FROM_EMAIL##' => DEFAULT_FROM_EMAIL_ADDRESS,
        '##CONTACT_EMAIL##' => DEFAULT_CONTACT_EMAIL_ADDRESS
    );
    $qry_val_arr = array(
        $template
    );
    $emailFindReplace = array_merge($default_content, $replace_content);
    $templates = executeQuery('SELECT * FROM email_templates WHERE name = $1', $qry_val_arr);
    if ($templates) {
        $message = strtr($templates['email_text_content'], $emailFindReplace);
        $message.= '<div itemscope itemtype="http://schema.org/EmailMessage"><div itemprop="potentialAction" itemscope itemtype="http://schema.org/ViewAction"><link itemprop="target" href="' . $_server_domain_url .
        $subject = strtr($templates['subject'], $emailFindReplace);
        $from_email = strtr($templates['from_email'], $emailFindReplace);

        //new
        $mail = new PHPMailer;

        $mail->isSMTP();                                      // Set mailer to use SMTP
        $mail->Host = '<hardcoded-mail-server-of-my-provider>';  // Specify main and backup SMTP servers
        $mail->SMTPAuth = true;                               // Enable SMTP authentication
        $mail->Username = '<hardcoded-mail-account>';                 // SMTP username
        $mail->Password = '<hardcoded-mail-password';                           // SMTP password
        $mail->SMTPSecure = 'tls';                            // Enable encryption, 'ssl' also accepted

        $bracketpos1 = strpos($from_email, '<');
        $bracketpos2 = strpos($from_email, '>');

        $mail->From = substr($from_email, $bracketpos1+1, ($bracketpos2-$bracketpos1-1) );
        //"<Sitename> Restyaboard"
        $mail->FromName = substr($from_email, 0, $bracketpos1-1);

        $mail->addAddress($to);     // Add a recipient

        //this should get completed...
        /*if (!empty($reply_to_mail)) {
            $mail->addReplyTo($reply_to_mail);
        }*/

        $mail->isHTML(true);                                  // Set email format to HTML

        $mail->Subject = $subject;
        $mail->Body    = $message;
        $result = $mail->send();

        if (R_DEBUG) {
            if (!$result) {
                $compose_string = 'F, ' . $mail->From . ', (' . $mail->FromName . '), ' . $to . ', ' . $subject . PHP_EOL;
            } else {
                $compose_string = 'S, ' . $mail->From . ', (' . $mail->FromName . '), ' . $to . ', ' . $subject . PHP_EOL;
            }
            error_log($compose_string, 3, CACHE_PATH . DS . 'mail.log');
        }
    }
}

```

**Comment by ron4all** [comment]
the Parameters:
* mail-server-IP(s)
* mail-account-user
* mail-account-pass
* mail-server-securitymethod 
need to be configurable by the user/GUI of course.

I skipped the "reply-to-mail"-Feature since i didn't need it right now.

**Comment by rrjanbiah** [comment]
@ron4all 

Thanks a lot for your suggestion to use PHPMailer (similar to #1397)

Currently, we use Postfix approach (as noted in https://github.com/RestyaPlatform/board/issues/450#issuecomment-196814831) Technically, both should work. But, I'm not sure why gmx.de is working in PHPMailer but not through Postfix. If you have any information related to that, kindly share.

**Comment by rrjanbiah** [comment]
*Internal note*

Not sure what to do here, except that it points to #1397. So, updating label & milestones accordingly

**Comment by ron4all** [comment]
might it be worth considering this as an option for an enhancement? people might want to simply install and use restya board without having to learn how to set up an authenticated mail server, which seems to be absolutely unneccecery overhead without any advantage provided.

how many bug Tickets here are Email related? 10% of all issues!? all could be avoided by implementing a simple email-client functionality as shown in ny tiny code snippet. just my 2cts...

**Comment by rrjanbiah** [comment]
@ron4all Thanks for your note.

Yes, we understood that #1397 has to be given priority. But, we're not sure why PHPMailer based SMTP works but not Postfix based approach. For that we need help.

**Comment by sridhar391** [comment]
For outgoing mails, now you can use the [Spark Post app](https://restya.com/board/apps/r_sparkpost) to send mails without using the SMTP library
