### ISSUE TITLE
Not able to add board while removing the permission of "Load workflow templates" for user roles 

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3289]
## Expected Behavior
Should be able to add board while removing the permission of Load workflow templates for user roles 

## Current Behavior
Not able to add board while removing the permission of Load workflow templates for user roles 

## Steps to Reproduce (for bugs)
1. Uncheck the permission for particular user role for Load workflow templates in the roles page 
2. Log in as the user with that role 
3. Try to add board

**Comment by srileka** [comment]
Issue not Fixed.

Not able to add board while removing the permission of "Load workflow templates" for user roles

![2019-11-13_11-38-45](https://user-images.githubusercontent.com/14290356/68737249-e3d34400-0608-11ea-89aa-0bdc9cefbc5e.png)

**Comment by sridhar391** [comment]
Issue not fixed

**Comment by sridhar391** [comment]
Fixed in the `dev` branch and the fix will be available in the upcoming release v0.6.8 (Roxette)
