### ISSUE TITLE
Other use browser in list view, "archive list" did not update properly

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3291]
## Expected Behavior

Other use browser in list view, "archive list" did not update properly

## Current Behavior

Other use browser in list view, "archive list" did not update properly

## Screenshots (if appropriate):

![1_other_list_archive](https://user-images.githubusercontent.com/14290356/67201450-f7352a00-f423-11e9-874c-a1ab0bf8546f.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the commit https://github.com/RestyaPlatform/board/commit/6f6131962a7c861737e40041f115d07ab3c57920 and it will be available in the upcoming release v0.6.8 (Roxette)

**Comment by sridhar391** [comment]
While sending the archived list to board, the list is not updated in another user browser list view

**Comment by srileka** [comment]
Issue not fixed.

Other user browser in list view, archived card did not updated properly.

**Comment by srileka** [comment]
Issue not Fixed.

First archive all the cards in the list. Then archived items, after click the "load more" button click the send to board, it dose not working properly.

![archive_1](https://user-images.githubusercontent.com/14290356/68302872-d4b03b80-00c8-11ea-86b4-9db5659983d2.png)

![archive_2](https://user-images.githubusercontent.com/14290356/68302882-d7ab2c00-00c8-11ea-983d-64afc85fea60.png)
