### ISSUE TITLE
Other user browser(list view) deleted the list in archive item. Current user browser(grid view) open the archive items in settings, console error came

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3292]
## Expected Behavior

Other user browser(list view) deleted the list in archive item. Current user browser(grid view) open the archive items in settings, console error came

## Current Behavior

Other user browser(list view) deleted the list in archive item. Current user browser(grid view) open the archive items in settings, console error came

## Screenshots (if appropriate):

![2_current_archive_grid](https://user-images.githubusercontent.com/14290356/67201536-2481d800-f424-11e9-8120-0a1e05d7b784.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the commit https://github.com/RestyaPlatform/board/commit/6f6131962a7c861737e40041f115d07ab3c57920 and it will be available in the upcoming release v0.6.8 (Roxette)
