### ISSUE TITLE
Current user browser (grid view) move the list from one board to another board, moved list did not updated in other user browser (list view)

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3293]
## Expected Behavior

Current user browser (grid view) move the list from one board to another board, moved list did not updated in other user browser (list view)

## Current Behavior

Current user browser (grid view) move the list from one board to another board, moved list did not updated in other user browser (list view)

## Screenshots (if appropriate):

![3_other_archive_list](https://user-images.githubusercontent.com/14290356/67206245-e807a980-f42e-11e9-8527-2fe8cc5545a4.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the commit https://github.com/RestyaPlatform/board/commit/544f4b89a90267d6d727a0b9506801e508dae3ae and it will be available in the upcoming release v0.6.8 (Roxette)

**Comment by sridhar391** [comment]
Issue not fixed

**Comment by sridhar391** [comment]
Fixed in the `dev` branch and the fix will be available in the upcoming release v0.6.8 (Roxette)

**Comment by sridhar391** [comment]
Issue not fixed
