### ISSUE TITLE
After adding the new board, if we try to add the board member console error thrown for current user

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3307]
## Expected Behavior
After adding the new board, if we try to add the board member, the member should be added

## Current Behavior
After adding the new board, if we try to add the board member console error thrown for current user

> Uncaught TypeError: a.showImage is not a function

## Steps to Reproduce (for bugs)
1. Add a board
2. Add the board member

**Comment by srileka** [comment]
After adding the new board, if we try to add the board member (that board member having the profile image) console error thrown for current user.

![2019-11-13_12-19-59](https://user-images.githubusercontent.com/14290356/68739628-47607000-060f-11ea-8fb1-af4558d5e7e3.png)
