### ISSUE TITLE
Cannot install with PostgreSQL 12

### ISSUE THREAD

**Issue by FanyangMengDev** [RestyaPlatform/board#3314]
Cannot install with PostgreSQL 12

Ubuntu 18.04 LTS
Php 7.3
PostgreSQL has already been installed and the file it displays in the following is all properly there. Why happen this?

Using one click script.
It display like this:
+ sed -e s/peer/trust/g -e s/ident/trust/g
./restyaboard.sh: line 609: /etc/postgresql/12.0/main/pg_hba.conf: No such file or directory
+ cd /etc/postgresql/12.0/main
./restyaboard.sh: line 610: cd: /etc/postgresql/12.0/main: No such file or directory
+ exit

[restyaboard_install.log](https://github.com/RestyaPlatform/board/files/3797409/restyaboard_install.log)

**Comment by sridhar391** [comment]
@FanyangMengDev can you please download the attached file and rename it as restyaboard.sh 
and try to install the Restyaboard by executing the below commands and please tell us if Restyaboard is successfully installed

Execute below commands:
`chmod +x restyaboard.sh` 
`./restyaboard.sh`

[restyaboard.txt](https://github.com/RestyaPlatform/board/files/3797614/restyaboard.txt)

**Comment by FanyangMengDev** [comment]
Ah, actually I have already uninstall version 12 and use the default version which is 10.
Please have a look on the other of my issue, that one is the most important

**Comment by sridhar391** [comment]
@FanyangMengDev Fixed the Not able to install Restyaboard with PostgreSQL 12 issue in the commit https://github.com/RestyaPlatform/board/pull/3374/commits/8ecc9b580b2129a6012510e874e2c1fe57d2add8
