### ISSUE TITLE
Got a blank page after install it

### ISSUE THREAD

**Issue by FanyangMengDev** [RestyaPlatform/board#3315]
Got a blank page after install it

## Current Behavior
After I installed it, It just display a blank page.

## Possible Solution
I think it is the nginx configuration which has probelms.

Here is the error log:
[error.log](https://github.com/RestyaPlatform/board/files/3797886/error.log)

[current nginx.txt](https://github.com/RestyaPlatform/board/files/3797688/current.nginx.txt)
![oauth](https://user-images.githubusercontent.com/53750381/68021958-d7341f00-fcdd-11e9-999c-e46cddf7128a.PNG)

## Steps to Reproduce (for bugs)
see the http://restya.fanyangmeng.com

## Your Environment
* Version used: 0.6.7
* Environment name and version (e.g. OS, PHP, PostgreSQL): Ubuntu 18.04 LTS PHP 7.3 and 7.2(which installed by the one click script) PostgreSQL 10
* Operating System and version (desktop or mobile): Both
* Link to your project: http://restya.fanyangmeng.com

**Comment by sridhar391** [comment]
@FanyangMengDev Please attach the Nginx error log file named `error.log` file in the path `/var/log/nginx`

**Comment by FanyangMengDev** [comment]
@sridhar391 Hi my friend, done. Please have a check. Thanks

**Comment by sridhar391** [comment]
@FanyangMengDev Please provide your domain name at the `restyaboard.conf` file at `line 2` like https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf#L3 in the Nginx configuration folder path `/etc/nginx/conf.d`

**Comment by FanyangMengDev** [comment]
Sorry mate. I think I give you the wrong error log. Please allow me to upload the right one. This one you saw is not the right one.

**Comment by FanyangMengDev** [comment]
Sorry mate, I really do not understand. You can see that the current nginx configuration is just set as the same as I send you, and I have already put my domain name in the right place. 
I have to admit that I forgot to delete the "_" which cause a litlle problem. But after I deleted the "_" and make the restyaboard.conf just like the nginx configuration, it still display a blank page.
Would you please have a check this time?
You can have a look of the error log.

> 2019/11/01 20:22:38 [notice] 9897#0: signal process started
2019/11/01 20:25:58 [warn] 9970#0: conflicting server name "_" on 0.0.0.0:80, ignored
2019/11/01 20:25:58 [notice] 9970#0: signal process started
2019/11/01 21:05:48 [notice] 10967#0: signal process started

After I delete "_" it still display blank

**Comment by FanyangMengDev** [comment]
I will paste the configuration of this website in the following:

> server {
	listen 80;
	server_name restya.fanyangmeng.com;

	root /hdd2/www/websites/restya.fanyangmeng.coml;
	index  index.html index.php;

	gzip on;
	gzip_disable "msie6";

	gzip_comp_level 6;
	# gzip_comp_level 9;
	gzip_min_length  1100;
	gzip_buffers 16 8k;
	gzip_proxied any;
	# gzip_http_version 1.1;
	gzip_types       text/plain application/xml text/css text/js text/xml application/x-javascript text/javascript application/json application/xml+rss;

	client_max_body_size 300M;

	rewrite ^/oauth/authorize$ /server/php/authorize.php last;
	rewrite ^/oauth_callback/([a-zA-Z0-9_\.]*)/([a-zA-Z0-9_\.]*)$ /server/php/oauth_callback.php?plugin=$1&code=$2 last;
	rewrite ^/download/([0-9]*)/([a-zA-Z0-9_\.]*)$ /server/php/download.php?id=$1&hash=$2 last;
	rewrite ^/ical/([0-9]*)/([0-9]*)/([a-z0-9]*).ics$ /server/php/ical.php?board_id=$1&user_id=$2&hash=$3 last;
	rewrite ^/api/(.*)$ /server/php/R/r.php?_url=$1&$args last;
	rewrite ^/api_explorer/api-docs/$ /client/api_explorer/api-docs/index.php last;
		
	location / {
		root /hdd2/www/websites/restya.fanyangmeng.com/client;
	}

	location ~ \.php$ {
		try_files $uri =404;
		include fastcgi_params;
		fastcgi_pass	unix:/run/php/php7.2-fpm.sock;
		fastcgi_index   index.php;
		fastcgi_param	SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PHP_VALUE "upload_max_filesize=9G \n post_max_size=9G \n max_execution_time=200 \n max_input_time=200 \n memory_limit=256M";
	}

	location ~* \.(css|js|less|html|ttf|woff|jpg|jpeg|gif|png|bmp|ico|pdf|doc|docx|xls|xlx|txt|ppt|pptx|mp4|webm|mkv|wmv|avi|mp3) {
		root /hdd2/www/websites/restya.fanyangmeng.com/client;
		if (-f $request_filename) {
			break;
		}
		rewrite ^/img/([a-zA-Z_]*)/([a-zA-Z_]*)/([a-zA-Z0-9_\.]*)$ /server/php/image.php?size=$1&model=$2&filename=$3 last;
		add_header        Cache-Control public;
		add_header        Cache-Control must-revalidate;
		expires           7d;
	}
}

**Comment by FanyangMengDev** [comment]
Hi mate, I am still waiting, I really hope that I can use it as soon as possible. Please help. I am so appreciate it.

**Comment by rrjanbiah** [comment]
@FanyangMengDev 

For me it looks like php fpm is not up. Also, can you please attach only the latest error log (after emptying it, please retry and attach)

Also, you may avail our free install support https://calendly.com/restya/it-support

**Comment by FanyangMengDev** [comment]
it just keep display like this in the error log,  no more other logs:
2019/11/01 23:16:38 [notice] 13700#0: signal process started
2019/11/01 23:16:59 [notice] 13718#0: signal process started

**Comment by FanyangMengDev** [comment]
You can go to my website and refresh it, it just stuck here.
The error log I sent to you is just the latest, with the same message display

**Comment by FanyangMengDev** [comment]
I found the right version of this error log, please have a look
[restya.fanyangmeng.com.error.log](https://github.com/RestyaPlatform/board/files/3798495/restya.fanyangmeng.com.error.log)

**Comment by FanyangMengDev** [comment]
I think this is the right version of the wensite. I really wanna use restya board as soon as possible.
Thank you for your support and hardworking. Please help me through this.

**Comment by FanyangMengDev** [comment]
it says that line 71 in the config.inc.php has wrong.
I checked this and I found that it is for php 5? I am using php 7.3

**Comment by rrjanbiah** [comment]
@FanyangMengDev 

> "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function pg_connect()

So, it looks like you didn't have PostgreSQL PHP extension.

**Comment by FanyangMengDev** [comment]
I know, let me have a look where to install

**Comment by FanyangMengDev** [comment]
OMG, Finally it is because the extension!

**Comment by rrjanbiah** [comment]
Yes. Found it ? :-)

**Comment by FanyangMengDev** [comment]
Yes! OMG it is because I did not install the extension, after I install it, all become normal.......
Thank you so much my friend. I will add ssl to it now. Please allow me a few minutes until I add ssl to it.
I am afraid there will be more problems.

**Comment by rrjanbiah** [comment]
Sure :-)

**Comment by rrjanbiah** [comment]
@FanyangMengDev 

Thanks for your kind words. Cheers!
