### ISSUE TITLE
If we add the card through instant add card using the label, card has been added twice

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3316]
## Expected Behavior

If we add the card through instant add card using the label, card has been added twice

## Current Behavior

If we add the card through instant add card using the label, card has been added twice

## Screenshots (if appropriate):

![card_twice](https://user-images.githubusercontent.com/14290356/68066551-a98fba00-fd5f-11e9-9957-498e3009df68.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Instant Add Card app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)
