### ISSUE TITLE
After added the card through instant add card, when we click the select list option, previously selected board lists has been displayed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3317]
## Expected Behavior

After added the card through instant add card, when we click the select list option, previously selected board lists has been displayed

It should not be displayed. After selected the board only, list has been displayed

## Current Behavior

After added the card through instant add card, when we click the select list option, previously selected board lists has been displayed

It should not be displayed. After selected the board only, list has been displayed

## Screenshots (if appropriate):

![board list_instant](https://user-images.githubusercontent.com/14290356/68066564-c7f5b580-fd5f-11e9-9b47-e1956076814a.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Instant Add Card app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)
