### ISSUE TITLE
Create template are not aligned correctly in the modal card page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3320]
## Expected Behavior

Create template are not aligned correctly in the modal card page

## Current Behavior

Create template are not aligned correctly in the modal card page

## Screenshots (if appropriate):

![create template_align](https://user-images.githubusercontent.com/14290356/68066618-f031e400-fd60-11e9-8e85-9f5b10453353.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the Card Template app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)
