### ISSUE TITLE
After added the card dependency, change the start date and due date in child card, date is wrong in child card

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3322]
## Expected Behavior

After added the card dependency, change the start date and due date in child card, date is wrong in child card

## Current Behavior

After added the card dependency, change the start date and due date in child card, date is wrong in child card

## Screenshots (if appropriate):

![child_date chnage](https://user-images.githubusercontent.com/14290356/68066752-ec9f5c80-fd62-11e9-8768-8ba77995d194.png)

**Comment by sridhar391** [comment]
Fixed the above issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.8(Roxette)
