### ISSUE TITLE
After login sometimes cookie policy message displayed twice

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3323]
## Expected Behavior

After login sometimes cookie policy message displayed twice

## Current Behavior

After login sometimes cookie policy message displayed twice

## Screenshots (if appropriate):

![cookie_msg](https://user-images.githubusercontent.com/14290356/68066788-86ffa000-fd63-11e9-8a55-5b9d17013fde.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the commit https://github.com/RestyaPlatform/board-apps/pull/149/commits/b2159d4872370d7343e71ef32d5cb19c67cd35de and the fix will be available in the upcoming release v0.6.8 (Roxette)
