### ISSUE TITLE
while filtering the cards and switch between different views, filter clears but clear filter button shown 

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3351]
## Expected Behavior
while filtering the cards and switch between different views, filter clears and clear filter button should be hidden

## Current Behavior
while filtering the cards and switch between different views, filter clears but clear filter button shown 

## Steps to Reproduce (for bugs)
1. Goto any board
2. Filter cards in the grid view
3. Change the board view

**Comment by srileka** [comment]
Issue Not Fixed.

In Grid view filter the cards and then go to the gantt view, calender view and list view.

At the time filters applied in all the views.

![2019-11-11_13-59-03](https://user-images.githubusercontent.com/14290356/68572004-5669e580-048a-11ea-841d-3797a41c66f9.png)

**Comment by sridhar391** [comment]
while refreshing the view, the filter cleared

**Comment by srileka** [comment]
Issue Not Fixed.

While filtering the card in grid view, then go to the gantt view "clear filter" button shown.

![2019-11-15_10-59-34](https://user-images.githubusercontent.com/14290356/68918885-09418880-0796-11ea-9beb-44bf51e3f15b.png)

**Comment by sridhar391** [comment]
@srileka We filter the cards in the Gantt view if we move to the Gantt View from the filtered Grid View
