### ISSUE TITLE
After create the card, when we move the card from one list to another list this console error thrown "Uncaught TypeError: Cannot read property 'set' of undefined"

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3375]
## Expected Behavior

After create the card, when we move the card from one list to another list this console error thrown "Uncaught TypeError: Cannot read property 'set' of undefined"

## Current Behavior

After create the card, when we move the card from one list to another list this console error thrown "Uncaught TypeError: Cannot read property 'set' of undefined"

## Screenshots (if appropriate):

![card move_list](https://user-images.githubusercontent.com/14290356/68457311-fd017c80-0225-11ea-9824-5bc101cc04a2.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the commit https://github.com/RestyaPlatform/board/pull/3377/commits/8cf83211681188a977fa0608cce1fd14db673873 and the fix will be available in the upcoming release v0.6.8 (Roxette)

**Comment by srileka** [comment]
Issue not Fixed.

Create the card and then move the card from one list to another list, this console error thrown "Uncaught TypeError: Cannot read property 'set' of undefined"  in other user browser.

![2019-11-11_13-10-17](https://user-images.githubusercontent.com/14290356/68571782-cfb50880-0489-11ea-965f-d3c184c2c7a1.png)
