### ISSUE TITLE
After create the card, when we move the card from one board to another board this console error thrown "Uncaught TypeError: Cannot read property 'attributes' of undefined"

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3376]
## Expected Behavior

After create the card, when we move the card from one board to another board this console error thrown "Uncaught TypeError: Cannot read property 'attributes' of undefined"

## Current Behavior

After create the card, when we move the card from one board to another board this console error thrown "Uncaught TypeError: Cannot read property 'attributes' of undefined"

## Screenshots (if appropriate):

![card move_board](https://user-images.githubusercontent.com/14290356/68457418-4225ae80-0226-11ea-983e-0a55670c55c6.png)

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the commit https://github.com/RestyaPlatform/board/pull/3377/commits/8cf83211681188a977fa0608cce1fd14db673873 and the fix will be available in the upcoming release v0.6.8 (Roxette)
