### ISSUE TITLE
If we edit the comment, edited comment has been updated in comment created activity also

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3386]
## Expected Behavior

If we edit the comment, edited comment has been updated in comment created activity also

When we delete the comment, comment created activity has been removed

## Current Behavior

1. If we edit the comment, edited comment has been updated in comment created activity also

2. When we delete the comment, comment created activity has been removed

## Screenshots (if appropriate):

![comment_edit](https://user-images.githubusercontent.com/14290356/68579257-af8d4580-0499-11ea-826c-3e8d583183b5.png)

![comment_delete](https://user-images.githubusercontent.com/14290356/68579265-b1ef9f80-0499-11ea-979b-41fb149f0fcc.png)

**Comment by sridhar391** [comment]
@srileka As like trello, we have shown the activity for add comment and edit comment

**Comment by sridhar391** [comment]
Issues Not Fixed.

Case 1: After edit the comment, refresh the comment. Edited comment did not updated.

Case 2: If we edit or delete the comment, comment edited and deleted activity did not updated in other user browser.

Case 3: Comment created activity is did not displayed in both current and other user browser

**Comment by sridhar391** [comment]
Fixed the issue in the dev branch and the fix will be available in the upcoming release v0.6.9 (Stereopony)
