### ISSUE TITLE
Image link attachment not appearing in card on board view

### ISSUE THREAD

**Issue by trinity-db-42** [RestyaPlatform/board#3393]
My apologies for posting this here as I recognise this may well not be a bug, but I am getting no replies from any other contacts so here is my last resort. 

I am a teacher in the UK and am looking to use RestyaBoard as a front end for teachers to access information about students in their classes. I am hoping to use Excel VBA to access the Restyaboard API to create classes as boards with students as cards. Key to this visually is to have student photos appear on the cards in board view. Using the user interface I am able to upload image files to appear in the cards but when I try to add a link to an image file ie web-based then it appears as a placeholder and I have to click the link to see the image.

I am assuming that if my system is to work I would need to be able to attach images using links somehow (I am able to do this in Trello), so I guess I'm asking if I'm missing something or if this is possible using the API and moreso how the API attachment concept works ie if you add an attachment using the API is it link based or does it allow uploading of local files? My Restyaboard installation is on DigitalOcean.

**Comment by srileka** [comment]
@trinity-db-42 In Trello, first, they showed the attachment link like Restyaboard and now only they showed the attachment and we will consider this option and will discuss within the team and we will update you

**Comment by rrjanbiah** [comment]
@trinity-db-42 

> My apologies for posting this here as I recognise this may well not be a bug, but I am getting no replies from any other contacts so here is my last resort.

Sorry to hear this. Whom did you contact before? You may escalate your experience to `info at our domain`. We'll try to improve our customer experience. Sorry again.

**Comment by trinity-db-42** [comment]
My original experience was with Restya.com, so nothing to do with github, they were initially helpful but then I asked 2 different contacts there the questions I had, or to be directed to someone who might be able to help and got no reply after a few attempts.

I have had a reply from you guys already which is great regarding the image link attachment so thank you for that. Is there anyone I can contact regarding how the API works for attachments? I have looked at the API explorer but my question is more basic working like does it attach through links (from web) or does it allow upload of local files?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rrjanbiah** [comment]
@trinity-db-42 

Sorry about that. We'll internally look into it.

Regarding API, whatever features currently possible in Restyaboard are possible through API as the API is exactly same. For support, you may also use our forum https://groups.google.com/d/forum/restya

**Comment by trinity-db-42** [comment]
Great, thanks for your help, I really appreciate it. I will now use the forum

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
