### ISSUE TITLE
MyRestyaboards iOS app does not work with - in URL 

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#3405]
From customer:

When your board has an - in URL you can‘t use this App

**Comment by sridhar391** [comment]
Tried accessing the URL containing `-` and the page is accessible in the MyRestyaboards iOS app, please refer the attached video


https://user-images.githubusercontent.com/17172525/112984925-24d7e400-917d-11eb-896b-e8298b660988.mp4
