### ISSUE TITLE
MyRestyaboard iOS app - boards not loaded even after connecting instance

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#3407]
From customer:

I was able to connect to my instance but no board loaded.

**Comment by srileka** [comment]
After login, log out in boards page. Again logged in boards page, go to the home page and then come to the boards page. That time boards are not loaded

**Comment by rrjanbiah** [comment]
@srileka This looks like a different issue and needs to be logged in separate ticket. 

But, for customer, he seems to be able to login/connect his instance, but his boards are not getting loaded. Have to reproduce this issue

**Comment by srileka** [comment]
After login go to the boards page, boards not loaded.

Steps:
1. Give the url 
2. Give the username and password.
3. Then go to the boards, boards are not loaded.

**Comment by rrjanbiah** [comment]
*Internal note*

It happens for the first time.
