### ISSUE TITLE
Questions: change label colors, add boards to organization

### ISSUE THREAD

**Issue by akhasis** [RestyaPlatform/board#341]
Hello,

in the firm I work for we have implemented Restyaboard (v 0.1.6) as a test, and so far, so good. We only have a couple of questions:

- Is there any way to change the color of the labels?
- How can I create a board inside an organization, or move an existing one?

I guess that once we get answered it will seem obvious, but we can't manage to find the way, nor any manual that addresses these processes.

Also, is there any way to translate the application? It would be really useful, since most of our colleagues don't speak a word of English, so they navigate around the board learning "where" things are.

Thank you for your attention and keep up the great work.

**Comment by rrjanbiah** [comment]
@akhasis 

> Is there any way to change the color of the labels?

Currently the coloring is made automatic (to avoid the need to set colors manually). So, you may change that algorithm or implement that feature.

> How can I create a board inside an organization, or move an existing one?

You'll have to change the "visibility" of the board to "Organization". You can do that from boards listing page (say, /#/boards) ![change-visibility-board-listing](https://cloud.githubusercontent.com/assets/4907427/13247698/da3b1488-da40-11e5-89fe-9b2496421aac.png)

 or board page (say, /#/board/5) ![change-visibility-board-view](https://cloud.githubusercontent.com/assets/4907427/13247697/d9a5eeda-da40-11e5-8f60-419b35ebacab.png)

Regarding manual, we'll definitely work on that. 

> Also, is there any way to translate the application? It would be really useful, since most of our colleagues don't speak a word of English, so they navigate around the board learning "where" things are

Our upcoming release is having multi language support. For translation, please find our note here in the forum https://groups.google.com/forum/#!topic/restya/uhc7rJp_KLU

**Comment by akhasis** [comment]
Thank you!

**Comment by rrjanbiah** [comment]
Closing this for now
