### ISSUE TITLE
While login in the safari browser with browser language as english and if the Resyaboard user has no language set to him, the cards are not displayed in board page

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3415]
## Expected Behavior
While login in the safari browser with browser language as English and if the Resyaboard user has no language set to him, the cards should be shown in board page

## Current Behavior
While login in the safari browser with browser language as English and if the Resyaboard user has no language set to him, the cards are not displayed in board page

**Comment by srileka** [comment]
Issue not Fixed.

If we open the board in safari browser, cards are did not displayed
