### ISSUE TITLE
In IOS App after login, log out in boards page. Again logged in boards page, go to the home page and then come to the boards page. That time boards are not loaded

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3417]
## Expected Behavior

In IOS App after login, log out in boards page. Again logged in boards page, go to the home page and then come to the boards page. That time boards are not loaded

## Current Behavior

In IOS App after login, log out in boards page. Again logged in boards page, go to the home page and then come to the boards page. That time boards are not loaded

## Screenshots (if appropriate):

![boards_empty](https://user-images.githubusercontent.com/14290356/68769994-5238f600-064b-11ea-8e47-3699002f10dc.PNG)

**Comment by sridhar391** [comment]
we have fixed this issue in the commit https://github.com/RestyaPlatform/board/commit/0461b00e4470c77ef908f2c0abebc6e360c306e2
