### ISSUE TITLE
In Safari browser and ios app, boards list has been displayed as empty

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3418]
## Expected Behavior

In Safari browser and ios app, cards are should be display in boards page
## Current Behavior

In Safari browser and ios app, boards list has been displayed as empty

**Comment by sridhar391** [comment]
@srileka Fixed the above issue in the commit https://github.com/RestyaPlatform/board/commit/b3de9553a308a67bbd5fac843d33ad889a1d9443 and the fix will be available in the upcoming release v0.6.8 (Roxette)
