### ISSUE TITLE
Restyaboard instance is laggy

### ISSUE THREAD

**Issue by tamasberesoebb** [RestyaPlatform/board#3421]
Restyaboar instance is laggy. 

<img width="547" alt="Screenshot 2019-11-13 at 16 14 10" src="https://user-images.githubusercontent.com/41002963/68776611-ad112400-0630-11ea-8fbb-0804c1a996e0.png">

<img width="541" alt="Screenshot 2019-11-13 at 16 21 16" src="https://user-images.githubusercontent.com/41002963/68777262-adf68580-0631-11ea-8969-de7b4a6bdae1.png">

It's waiting for something, and I don't know what is causing this issue.

This is a fresh install, with barely any data or users in it. It's running on our own VM. There are no extra plugins installed. GDPR plugin is OFF.

## Expected Behavior
It should not delay for 10-20 seconds when loading the webpage.

## Current Behavior
Opening the page the first time, or force reloading the page causes a 10-20 second delay. Settings and oauth are delayed.

## Steps to Reproduce (for bugs)
1. install restyaboard
2. force reload webpage
3. wait 20 seconds for it to load

## Your Environment
This is a self hosted instance, running on a very beefy server.
Server software is WmVare ESXI 6.7.0
VM is running Ubuntu server 6 cores, 16Gb ram.
Restyaboard is running in Docker. Version is the latest non dev, which is currently v0.6.7.
Client is in the same LAN as server.

**Comment by rrjanbiah** [comment]
@tamasberesoebb 

Are you sure is this a fresh install? Over the top of my head, mostly it could be something to do with corrupt database. Can you please check your postgres instance?

**Comment by tamasberesoebb** [comment]
@rrjanbiah yes, it's a very fresh install. Database looks fine.
We have wasted a whole day trying to debug this, but we give up. If you have any other useful hints, please let me know, meanwhile we are switching to wekan. :(

**Comment by BlackDark** [comment]
@tamasberesoebb still an issue? 
You could try the image from #4013 
Otherwise issue can be closed.
