### ISSUE TITLE
While setting the Calendar View Card Color as first label color and if we change the color of the label, the card is not updated in the calendar view

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3432]
## Expected Behavior
While setting the Calendar View Card Color as first label color and if we change the color of the label, the card should be updated with the calendar view

## Current Behavior
While setting the Calendar View Card Color as first label color and if we change the color of the label, the card is not updated in the calendar view

## Screenshots (if appropriate):
![label_card_update](https://user-images.githubusercontent.com/17172525/68994553-37b08800-08aa-11ea-9cf4-06f93f024ff4.png)

**Comment by srileka** [comment]
Issue not Fixed.

If we change the label color in calendar view, card color is not updated

![card color_reopen](https://user-images.githubusercontent.com/14290356/69779672-d4d6bf00-11ce-11ea-8ce2-8d3146b85dba.png)

**Comment by sridhar391** [comment]
Duplicate https://github.com/RestyaPlatform/board/issues/3547 and issue is closed

**Comment by sridhar391** [comment]
Issue not fixed.
Case : If we change the label color in calendar view, card color is not updated
