### ISSUE TITLE
The board import form in mobile view is broken

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3446]
## Expected Behavior
The board import form in mobile view should not be broken

## Current Behavior
The board import form in mobile view is broken

## Screenshots (if appropriate):
![import_board_mobile_view](https://user-images.githubusercontent.com/17172525/69142129-23f46400-0aec-11ea-931d-fc6b7c5efe0e.png)

**Comment by sridhar391** [comment]
Issue not fixed

**Comment by srileka** [comment]
Issue not Fixed

**Comment by sridhar391** [comment]
Fixed the issue in the commit https://github.com/RestyaPlatform/board/commit/0c782f23f94cb7843e32affe7965d25d5ed01124 and the fix will be available in the upcoming release v0.6.8 (Roxette)
