### ISSUE TITLE
On user login 404 

### ISSUE THREAD

**Issue by romain-malet** [RestyaPlatform/board#349]
There is no organization and one board with 2 members: one admin and a user.
As admin no problem.
When I log on as user -> 404 Page not found but if I click on shared boards (icon top right) I get the correct page. After this action, I can access to the board by clicking "My boards".

When I login as admin:
POST login.json?...
GET board.json?type=simple...
GET organization.json?...
GET board.json?token=...
GET board.json?type=simple...

But as user:
POST login.json?...
GET board.json?type=simple...
GET organization.json?...

Do I need to create an organization ?

**Comment by rrjanbiah** [comment]
@romain-malet Sorry for the issue you're facing. We quickly tried to reproduce this behavior, but couldn't.

Can you please share your Restyboard version? Also, if you don't have any sensitive data, can you please also share your SQL dump?

**Comment by romain-malet** [comment]
Ok I fixed the problem by checking "View Organization" for user's roles.

**Comment by rrjanbiah** [comment]
@romain-malet Thanks for letting us know. Is this fix a convincing one? If not, please keep this open for us to fix.

**Comment by romain-malet** [comment]
Ok,
I unchecked all Organization roles for user.
It seems that uncheck "View organization" and "View organizations listing" for user role in Organization is the problem.
With this two roles checked, no 404.

**Comment by rrjanbiah** [comment]
@romain-malet Thanks for letting us know. We'll check our default SQL dump for this.

**Comment by ssivachidambaram** [comment]
@rrjanbiah We have checked in default SQL dump and all are enabled by default.
