### ISSUE TITLE
Linking from calendar to card

### ISSUE THREAD

**Issue by Chundri** [RestyaPlatform/board#3498]
Currently the calendar just displays the cards on their dates. It would be nice if they would actually link to the cards themselves.

**Comment by sridhar391** [comment]
@Chundri We have added the option to open the card while clicking the item in the calendar view and you can edit the card details in the modal card and this feature will be available in the upcoming release v0.6.8 (Roxette). For more details, please refer https://github.com/RestyaPlatform/board/issues/2407
