### ISSUE TITLE
Email notifications don't work

### ISSUE THREAD

**Issue by Chundri** [RestyaPlatform/board#3499]
Ciao,

for us to properly use Restyaboard it would be nice to actually have email notifications. Currently they don't work (I've tried selecting every five minutes, every hour, requesting an update for every single topic...) nothing seems to work.

However, receiving an email notification every 5 minutes or every hour on everything is not what we would want. Basically just a notification in case somebody is mentioned in a comment (when you write @person.name or when a card is assigned to a certain person to also receive a notification. Saves me sending out emails whenever I assign a card to someone.

Thanks.

Chundri

**Comment by sridhar391** [comment]
> Ciao,
> 
> for us to properly use Restyaboard it would be nice to actually have email notifications. Currently they don't work (I've tried selecting every five minutes, every hour, requesting an update for every single topic...) nothing seems to work.

Can you please check your spam folder for any emails regarding the Restyaboard notifications

> However, receiving an email notification every 5 minutes or every hour on everything is not what we would want. Basically just a notification in case somebody is mentioned in a comment (when you write @person.name or when a card is assigned to a certain person to also receive a notification. Saves me sending out emails whenever I assign a card to someone.

Please set the user email notification as Instant email notifications and unsubscribe from the card and try to mention the user in the comment of the card and the user will get the email notification about mentioning him in the card comment

**Comment by Chundri** [comment]
Hi,

There’s nothing in the spam folder.

I tried activating all notifications for two different users and put to instant email notifications without any luck.

How to proceed?

Thanks,

Chundri

**Comment by sridhar391** [comment]
> Hi, There’s nothing in the spam folder. I tried activating all notifications for two different users and put to instant email notifications without any luck. How to proceed? 

Please refer the attached document to setup the SMTP server for receiving the mail notifications.

[Documentation on SMTP server setup.pdf](https://github.com/RestyaPlatform/board/files/3891188/Documentation.on.SMTP.server.setup.pdf)

**Comment by Chundri** [comment]
Ciao,

we already have a SMTP server running to send email notifications from other web based applications. For Restyaboard in the admin control panel we cannot find where to link the SMTP server. There's only something there related to IMAP for incoming mails, but nothing related to SMTP.

Can you tell us where we can tell Restyaboard to which SMTP server it needs to refer?

Thanks,

Chundri

**Comment by sridhar391** [comment]
@Chundri You have to configure the SMTP server  in the Postfix and not the Restyaboard admin panel

**Comment by Chundri** [comment]
Hi sridhar,

But where should Restyaboard be looking for this SMTP server?
Just like we can set an incoming mailserver we should have to be able to set an outgoing mailserver?

Is it looking for the SMTP mailserver on the same location, what if we have the SMTP server running on a different machine?

Thank you for your help.

Best regards,

Chundri

**Comment by rrjanbiah** [comment]
@Chundri 

We're working on a documentation for emails related issues. Here's a draft. Please check and let us know if that's helpful. 


[Troubleshoot_email.pdf](https://github.com/RestyaPlatform/board/files/3955132/Troubleshoot_email.pdf)

**Comment by sridhar391** [comment]
@Chundri Please refer to our documentation link https://restya.com/board/docs/mailserver-configuration/
