### ISSUE TITLE
Flickr images are not loading.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#35]
Flickr images are not loading.

refer the attachment.
![unable to chooce flicker image](https://cloud.githubusercontent.com/assets/14290356/9873936/b9b0da1c-5bc0-11e5-93d4-2789a5cebe99.png)

**Comment by rrjanbiah** [comment]
Fixed.

**Comment by nickbe** [comment]
Seems like we have the same problem again with the latest version.

**Comment by sridhar391** [comment]
@nickbe Can you please get Flickr API key here https://www.flickr.com/services/ and update in admin side settings page http://board.demo.restya.com/#/settings/6?

**Comment by nickbe** [comment]
Where is the facepalm smiley if you need it 🤦‍♂️ 
I'm sorry. I didn't realize we had to do this first.
