### ISSUE TITLE
Check the settings icon and card number alignment in model card page while opening child card or parent card dependency

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3535]
## Expected Behavior
Check the settings icon and card number alignment in model card page while opening child card or parent card dependency

## Current Behavior
Check the settings icon and card number alignment in model card page while opening child card or parent card dependency

## Screenshots (if appropriate):
![211 5e2b0925bc867ae6430e426c078771f0](https://user-images.githubusercontent.com/17172525/69729035-9fd55880-114b-11ea-9ede-11964a1a73a8.png)

**Comment by baskar383** [comment]
Fixed the above issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)
