### ISSUE TITLE
While opening the card in parent or child card dependency, board url is wrong

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3536]
## Expected Behavior
While opening the card in parent or child card dependency, board url is wrong

## Current Behavior
While opening the card in parent or child card dependency, board url is wrong

## Screenshots (if appropriate):
![213 5e0672cfadabe62f70549934a6988cf7](https://user-images.githubusercontent.com/17172525/69729179-e6c34e00-114b-11ea-94ec-a8eac6cc1f42.png)

**Comment by baskar383** [comment]
Fixed the above issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)
