### ISSUE TITLE
If we set the due date in card, start time is wrong in gantt view

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3549]
## Expected Behavior
If we set the due date in card, start time is wrong in gantt view

## Current Behavior
If we set the due date in card, start time is wrong in gantt view

## Screenshots (if appropriate):
![24_starttime_gantt](https://user-images.githubusercontent.com/17172525/69730671-7f5acd80-114e-11ea-802d-9e615b658181.png)

**Comment by sridhar391** [comment]
Fixed the above issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)

**Comment by sridhar391** [comment]
Issues Not Fixed.
Case 1: If we give the due date only in the card, "created start time" is wrong in card

**Comment by sridhar391** [comment]
Fixed the issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)

**Comment by srileka** [comment]
Issue not Fixed

If we set the due date only, card created time is automatically take as a start date. Now card created time is wrong

![reopen_3549](https://user-images.githubusercontent.com/14290356/73818027-5f145280-4812-11ea-8988-04ff2853b9ea.png)

**Comment by sridhar391** [comment]
Fixed the issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
