### ISSUE TITLE
In instant add card, first time we click the label, text field is small in fraction of second

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3550]
## Expected Behavior
In instant add card, first time we click the label, text field is small in fraction of second

## Current Behavior
In instant add card, first time we click the label, text field is small in fraction of second

## Screenshots (if appropriate):
![25_label_instant_small](https://user-images.githubusercontent.com/17172525/69730745-a1545000-114e-11ea-8d3a-1b512b419ec8.png)

**Comment by baskar383** [comment]
Fixed the above issue in the Instant Add Card app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)
