### ISSUE TITLE
When the mouse hover on the card at very first time, custom field values are did not displayed in calendar and gantt view

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3552]
## Expected Behavior
When the mouse hover on the card at very first time, custom field values are did not displayed in calendar and gantt view

## Current Behavior
When the mouse hover on the card at very first time, custom field values are did not displayed in calendar and gantt view

## Screenshots (if appropriate):
![27_first_time_custom_calendar_gantt](https://user-images.githubusercontent.com/17172525/69730910-f09a8080-114e-11ea-9aa9-99b47f5906f1.png)

**Comment by baskar383** [comment]
@sridhar391 
In calendar view,  Instead of the tooltip, We shown details of the card by clicking the card in the calendar slots
