### ISSUE TITLE
One member having multiple cards at the same dates in member view, cards are hidden

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3568]
## Expected Behavior
One member having multiple cards at the same dates in member view, cards are hidden

## Current Behavior
One member having multiple cards at the same dates in member view, cards are hidden

## Screenshots (if appropriate):
![33_cards_hidden_same_date](https://user-images.githubusercontent.com/17172525/69844099-a6b9b380-1290-11ea-8118-d9f355968e42.png)

**Comment by baskar383** [comment]
Fixed the above issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.8 (Roxette)
