### ISSUE TITLE
While user performing action, console error thrown

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3676]
## Expected Behavior
While user performing action, console error thrown

## Current Behavior
While user performing action, console error thrown

```
TypeError: Failed to execute 'linearRampToValueAtTime' on 'AudioParam': 2 arguments required, but only 1 present.
  at a._truncateSound(/js/default.cache.4f4f6c3f.js:42:15588)

```

**Comment by srileka** [comment]
@sridhar391 

Steps: Create the board and then wait 2 minutes, this console error thrown "Uncaught TypeError: Failed to execute 'linearRampToValueAtTime' on 'AudioParam': 2 arguments required, but only 1 present."

![board_console_reproduce](https://user-images.githubusercontent.com/14290356/70438217-583bbe80-1ab3-11ea-8e14-4d3ce0de9e5f.png)

**Comment by srileka** [comment]
Issue not Fixed.

After open the board, wait for 3 minutes. Console error thrown

![2020-02-04_13-12-20](https://user-images.githubusercontent.com/14290356/73723437-0af46a00-474f-11ea-8156-a5176e865728.png)

**Comment by srileka** [comment]
Issue Not Fixed.

![reopen_3676](https://user-images.githubusercontent.com/14290356/73821864-e1087980-481a-11ea-9c46-7bd8265e4379.png)

**Comment by sridhar391** [comment]
@srileka We are closing this issue as we are not able to re-produce the issue, please feel to reopen if the issue occurred again and add the reproduce steps
