### ISSUE TITLE
RangeErrorp(default.cache) error Maximum call stack size exceeded console error thrown

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3683]
## Expected Behavior
RangeErrorp(default.cache) error Maximum call stack size exceeded console error thrown

## Current Behavior
RangeErrorp(default.cache) error Maximum call stack size exceeded console error thrown

**Comment by srileka** [comment]
@sridhar391 

Steps: Board show attachments - view and close the attachment, this console error is thrown "Uncaught RangeError: Maximum call stack size exceeded"

![attachment_console_reproduce](https://user-images.githubusercontent.com/14290356/70438473-ec0d8a80-1ab3-11ea-931e-075bfa7bb39f.png)
