### ISSUE TITLE
[sprintf] unexpected placeholder console error thrown

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3693]
## Expected Behavior
[sprintf] unexpected placeholder console error thrown

## Current Behavior
[sprintf] unexpected placeholder console error thrown

**Comment by sridhar391** [comment]
We are closing this issue as we are not able to re-produce the issue, please feel to reopen if the issue occurred again and add the reproduce steps

**Comment by milosz** [comment]
Hello,

It is likely problem with local translation.

When I open board on the https://board.demo.restya.com/ using:
- English language in browser: everything is fine
- Polish language: error
