### ISSUE TITLE
If we give the space in edit label, space accepted. But we unable to give the space in create label

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3710]
## Expected Behavior
If we give the space in edit label, space accepted. But we unable to give the space in create label

## Current Behavior
If we give the space in edit label, space accepted. But we unable to give the space in create label

## Screenshots (if appropriate):
![6_label_space](https://user-images.githubusercontent.com/17172525/70218850-cb6acb00-1769-11ea-9c56-785249307a30.png)

**Comment by sridhar391** [comment]
Issue not Fixed.
Case: Labels having space, the label name is separated by a comma in label related activity

**Comment by srileka** [comment]
Issue Not Fixed.

We unable to give the space in create label.

![reopen_3710](https://user-images.githubusercontent.com/14290356/73824154-aead4b00-481f-11ea-9cb8-c6bc8f54d775.png)

**Comment by sridhar391** [comment]
@srileka While creating the label, the spacebar key and the enter key is used to enter new label
