### ISSUE TITLE
If we giving the special character in labels, console error thrown

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3714]
## Expected Behavior
If we giving the special character in labels, console error thrown

## Current Behavior
If we giving the special character in labels, console error thrown

## Screenshots (if appropriate):
![10_special_console](https://user-images.githubusercontent.com/17172525/70219320-9d39bb00-176a-11ea-9a9c-b7d0be68f4de.png)

**Comment by srileka** [comment]
Issue not Fixed.

![2020-02-04_12-54-59](https://user-images.githubusercontent.com/14290356/73722754-47bf6180-474d-11ea-9a2c-61f2673b2ff9.png)
