### ISSUE TITLE
bug user can't login after invitation. fixed

### ISSUE THREAD

**Issue by DAigory** [RestyaPlatform/board#3751]
I think you made mistake here: 
board/server/php/R/r.php
``
  } else {
            if ($user['is_invite_from_board'] == 't' && $user['is_active'] == 0 && $user['is_email_confirmed'] == 0) {
                $r_post['password'] = getCryptHash($r_post['password']);
                $qry_val_arr = array(
                    'true',
                    'true',
                    $r_post['username'],
                    getCryptHash($r_post['password']) ,
                    $user['id']
                );
``

you crypted pass twice
1.  $r_post['password'] = getCryptHash($r_post['password']);
2.   getCryptHash($r_post['password']) ,

correct:
``
} else {
            if ($user['is_invite_from_board'] == 't' && $user['is_active'] == 0 && $user['is_email_confirmed'] == 0) {
                $r_post['password'] = getCryptHash($r_post['password']);
                $qry_val_arr = array(
                    'true',
                    'true',
                    $r_post['username'],
                    $r_post['password'] ,
                    $user['id']
                );
``

**Comment by sridhar391** [comment]
@DAigory The `Invite from Board` option is removed in the upcoming release v0.6.8 (Roxette) and we have provided the alternative way to add the existing Restyaboard member in board in the documentation link https://restya.com/board/docs/restyaboard-user-invite/#0

Also, please refer https://github.com/RestyaPlatform/board/issues/1343
