### ISSUE TITLE
Question - Can this be installed on..?

### ISSUE THREAD

**Issue by Rustymage** [RestyaPlatform/board#3760]
Can this be installed on a Raspberry Pi 3B+ or 4 (4GB)?

I've tried but it didn't seem to work. No errors were thrown up and I didn't dig through the logs as I ran out of time. I'd like to try again but I would like confirmation that it should work first.

Could anyone let me know if it's intended to work please?

Thanks

**Comment by sridhar391** [comment]
@Rustymage Please try to install Restyaboard with the Restyaboard installation script file from the dev branch [restyaboard.sh](https://raw.githubusercontent.com/RestyaPlatform/board/dev/restyaboard.sh)
