### ISSUE TITLE
Labels button don't work.

### ISSUE THREAD

**Issue by DAigory** [RestyaPlatform/board#3777]
I was able to add lables and for some reasons labels button stop to work for several boards
It stop to work fully in approximate in 5 of 15 boards.
In new created board it works fine
In admin user all labels in all board works
This problem same for all not admin users

**Comment by srileka** [comment]
@DAigory Please contact our technical team at info@restya.com

**Comment by sridhar391** [comment]
Closing the issue, due to inactivity.
