### ISSUE TITLE
Wrong image URL

### ISSUE THREAD

**Issue by mzch** [RestyaPlatform/board#3780]
## Expected Behavior

Avatar is shown correctly.
## Current Behavior

Broken image mark is shown.

## Screenshots (if appropriate):
<img width="552" alt="ScreenShot 2019-12-14 5 59 18" src="https://user-images.githubusercontent.com/621178/70832179-c8da3680-1e37-11ea-9d13-34c5e7be194a.png">

## Possible Solution

I don't know.
## Steps to Reproduce (for bugs)

1. Fresh install RestyaBoard on Debian 10.
2. Login and try to change an avatar. At this time, it gets successful.
3. Close browser tab and reopen blank tab.
4. Enter URL with restyaboard, then login.

## Context

visually undesirable
## Your Environment

* Version used: 0.6.7
* Environment name and version (e.g. OS, PHP, PostgreSQL): Debian 10, PHP 7.3.11, PostgreSQL 12
* Operating System and version (desktop or mobile): macOS 10.15.2, Chrome 79.0.3945.79
* Link to your project:

**Comment by mzch** [comment]
I found Google Chrome caused this issue. Thanks.

**Comment by mzch** [comment]
Hi,
It occurred again. It hasn't been fixed though resetting Chrome...

**Comment by rrjanbiah** [comment]
@mzch Sorry to hear that you had to reinstall Restyaboard. Anyway glad to know that it fixed the issue

**Comment by mzch** [comment]
Oh, this recurred...

**Comment by mzch** [comment]
Please sign up and look into https://taskmoe.com/

**Comment by sridhar391** [comment]
@mzch We have registed and tried to change the profile image and there is no issue and the link for the image is https://taskmoe.com/img/micro_thumb/User/3.ffbf92f45cc4c79424df70db528e8d31.png?uid=3068 

Can you please explain us in detail about the correct issue

**Comment by mzch** [comment]
Oh, that means my browser is broken....
I tried another browser from my old Mac, then everything is OK.
Thanks.
