### ISSUE TITLE
User log file

### ISSUE THREAD

**Issue by IssueFindings** [RestyaPlatform/board#3786]
Hello,
I install the last version V0.6.8 and I check the log file. I found it and I test it. I was very surprise by the results especially by the IP address displayed (please see below) :

2019-12-18 20:14:12|5|XXXXXXXXXXX|User agent 2019-12-18 20:15:36|5|XXXXXXXXXX|User agent 2019-12-18 20:19:27|13|XXXXXXXXXXXX|Mobile User agent

I did something wrong ?
Have a nice day.

**Comment by sridhar391** [comment]
@IssueFindings Sorry, i am not able to understand and can you please explain in detail about the issue with screenshot or video

**Comment by IssueFindings** [comment]
Hello,
When I use the command `nano /XXXX/restyaboard/tmp/cache/user_logins_failed.log`, I open the log file dedicated to authentification failure. Right (it's something new with v0.6.8).

When I read informations in this file user_logins_failed.log, I normally see this structure:
`Date | IP | User | User agent`

In my case, IP value is only one number (in my case the number 5 or 13) instead of something like XXX.XXX.XXX.XXX (for IPV4). So could you check in the code where comes from the value IP, because I don't understand the result.

I hope is more clear now. Have a nice day.

**Comment by sridhar391** [comment]
@IssueFindings 
 
 We are only saving the primary ID of IP address of ips table on the `user_logins_failed.log` file and you can get the full details of the IP address data like state, country details etc..  in the Restyaboard database ips table.

**Comment by IssueFindings** [comment]
Hello,
The patch works very well. Many thanks for your help.
Merry Christmas !!!!
