### ISSUE TITLE
Empty boards with iOS application 

### ISSUE THREAD

**Issue by IssueFindings** [RestyaPlatform/board#3787]
Hello,
I updated to 0.6.8. I can access as usually to my restyaboard with a web page. But when I try to connect, as previously, through my iOS application I get an empty page for my boards (but I see the last activities and notifications in Home). What I did wrong ?
Have a nice day.

**Comment by IssueFindings** [comment]
Hello, to illustrate the issue, please see below the empty screen. The 2 others tabs (Homes and Activities) are as usual.
![IMG_0010](https://user-images.githubusercontent.com/26858396/71294899-46db9780-237a-11ea-9680-c9668555acf6.PNG)
Have a nice day.

**Comment by IssueFindings** [comment]
It looks like the same than this issue https://github.com/RestyaPlatform/board/issues/3417

**Comment by sridhar391** [comment]
@IssueFindings We will check and update you about the issue

**Comment by IssueFindings** [comment]
@sridhar391 Did you find something ? It's really disabling this situation. Especially with a so special period. So could you give me some news about this bug.
Have a nice day.

**Comment by sridhar391** [comment]
@IssueFindings we have fixed this issue in the commit https://github.com/RestyaPlatform/board/commit/0461b00e4470c77ef908f2c0abebc6e360c306e2 and the fix will be available in the upcoming release v0.6.9 (Stereopony)

**Comment by IssueFindings** [comment]
Great !!! Do you know when this release will be available ?
Have a nice day.

**Comment by sridhar391** [comment]
@IssueFindings Please find approximate plan here https://github.com/RestyaPlatform/board/milestones

**Comment by IssueFindings** [comment]
Hello,
Thanks to the new version 0.6.9, I can access to my boards with iOS application. Many thanks for that.
Nevertheless, it's not very user friendly to navigate through differents boards inside iOS application. For instance, if I consult one board and I want to back to my boards list, I need to click to Restyaboard icon in the middle back then Boards menu and finaly Boards item (3 clicks for one action !) Is not really optimize for use on iOS...

Have a nice day.

**Comment by sridhar391** [comment]
@IssueFindings Thanks for your suggestion and we will discuss within the team
