### ISSUE TITLE
Activity time incorrect for some users

### ISSUE THREAD

**Issue by erl4nc** [RestyaPlatform/board#3791]
Some users get incorrect time in activity feed. Might be same bug as #3274 but I'm on version 0.6.8.

## Expected Behavior
Time shown should be identical on the same computer for users in the same time zone.

## Current Behavior
Time is incorrect for some users.

## Screenshots (if appropriate):
On the same computer, logging in as 2 different users. Left shows the owner of the board who is not an admin and who is not an LDAP user. Right shows an admin LDAP user that is not a member of the board. The correct time is on the right.
![time-difference](https://user-images.githubusercontent.com/33263752/71371969-e1e59480-2567-11ea-8d9a-cb83930d2a7d.png)

These 2 users have the same timezone set:
![same-timezone](https://user-images.githubusercontent.com/33263752/71372118-4d2f6680-2568-11ea-9453-87753851f70a.png)

Just to make sure browsers are not the cause, swapped the users in the 2 browsers, still incorrect result:
![swap-browser](https://user-images.githubusercontent.com/33263752/71372209-9e3f5a80-2568-11ea-82fb-d18042412924.png)

The JSON responses returned by api/v1/boards/39/activities.json are identical for the 2 accounts but somehow time is converted differently when displayed:
![image](https://user-images.githubusercontent.com/33263752/71372621-c24f6b80-2569-11ea-8d22-246305bb6d3d.png)

![image](https://user-images.githubusercontent.com/33263752/71372681-de530d00-2569-11ea-9d13-3cade1676fb8.png)

## Steps to Reproduce (for bugs)
1. Open activities on any board. Time is wrong on all boards for this user. Using a different computer in the same time zone produces the same incorrect result.

## Your Environment
* Version used: 0.6.8

**Comment by sridhar391** [comment]
@erl4nc Can you please logout for admin LDAP user and login again and please tell us if the activity time displayed correctly

**Comment by erl4nc** [comment]
@sridhar391, already did, that's what happened between screenshots 1 & 3.  Besides, if you look at the screenshots, admin user **HAS** the right time so I don't think you want to see different results. Like the bug mentioned, it does not matter if I switch browser or computer, the owner of the board **ALWAYS** sees wrong time.

**Comment by sridhar391** [comment]
@erl4nc Can you please tell us if you have set the Restyaboard server timezone in the Restyaboard admin panel site timezone

**Comment by erl4nc** [comment]
> @erl4nc Can you please tell us if you have set the Restyaboard server timezone in the Restyaboard admin panel site timezone

yes, same timezone as users.

**Comment by sridhar391** [comment]
@erl4nc Please mail your available time to us at info@restya.com for arranging the Zoom screen share meeting to understand and solve the issue

**Comment by erl4nc** [comment]
@sridhar391 I cannot comply with that request due to private data. I can provide screenshots and sanitized data however if you are looking for something specific.

**Comment by sridhar391** [comment]
@erl4nc Please give us the sample data in your Restyaboard database to understand and solve the issue.

**Comment by erl4nc** [comment]
Data is off limits as I specified.

**Comment by sridhar391** [comment]
@erl4nc Please give us the sanitized data as we are not able to reproduce the issue and you can mail us your sanitized data to info@restya.com if you don't want to share your data in public.

**Comment by erl4nc** [comment]
I don't have the will or the time to sanitize a database.  Sanitizing portions of response data from REST calls is already time consuming enough. Please narrow down your request.

**Comment by rrjanbiah** [comment]
@erl4nc 

Few items to check:

1. Server's timezone (system timezone)
2. From admin panel, Restyaboard instance's timezone (`Settings->User` in `/#/settings/16`)
3. Logged in user's timezone (`Profile->Settings` in `/#/user/999/settings`)
4. Also, any of these timezone have DST?

**Comment by erl4nc** [comment]
> @erl4nc
> 
> Few items to check:
> 
> 1. Server's timezone (system timezone) 

$ timedatectl
       Time zone: America/Vancouver (PST, -0800)
> 2. From admin panel, Restyaboard instance's timezone (`Settings->User` in `/#/settings/16`)

See above
> 3. Logged in user's timezone (`Profile->Settings` in `/#/user/999/settings`)

See above
> 4. Also, any of these timezone have DST?

yes, all

**Comment by rrjanbiah** [comment]
@sridhar391 @srileka Can we please try to setup an instance with above timezone details and check?

**Comment by erl4nc** [comment]
After a lot of debugging, I determined where the error came from. Despite the Demo Acct user profile showing a timezone, parse_date() in common.js logged that logged_user.user.timezone is null. I confirm in the database that this user does not have a timezone in the database.

This leads to:
1. Why does the user profile show a timezone when none is set? Does the user profile timezone show site timezone by default? This is misleading if true and hides problems. I'd recommend showing nothing.
2. I'd recommend the following change:
![image](https://user-images.githubusercontent.com/33263752/72116402-0333d800-32ff-11ea-9913-68f6dd1684d9.png)

**Comment by rrjanbiah** [comment]
@erl4nc Thank you so much for your fixes and suggestions. We'll take care shortly
