### ISSUE TITLE
Email Notification setting not respected

### ISSUE THREAD

**Issue by erl4nc** [RestyaPlatform/board#3792]
For some users, it's undesirable to receive any notification email. Despite setting system wide Default Email Notification to 'Never' and personal profile Email Notification to 'Never', users still received email such as 'newprojectuser'. Disabling server/php/shell/main.sh in crontab did not fix the issue.

v0.6.8

**Comment by sridhar391** [comment]
@erl4nc The user email notification settings will not be applied here and if you don't want to send the mail ntification, please comment the `Line 2490` of `r.php` file in the Restyaboard folder path `/usr/share/nginx/html/restyaboard/server/php/R` like https://github.com/RestyaPlatform/board/blob/dev/server/php/R/r.php#L2490

**Comment by erl4nc** [comment]
Instead of commenting out random lines of code which I'd need to remember every time I deploy a new version, please consider respecting the setting.

**Comment by sridhar391** [comment]
@erl4nc We wil fix this issue in the upcoming version v0.6.9 (Stereopony)

**Comment by sridhar391** [comment]
@erl4nc While adding the user in the board, the user have to be notified  for added in the board to be notified for the new project and we followed trello mail notification preferences and can you please tell us your use case?

**Comment by erl4nc** [comment]
I am not familiar with Trello's workflow and am not concerned with it. In my organization, some users specifically do not want card_due_notification.php email.

**Comment by sridhar391** [comment]
@erl4nc We will discuss internally discuss this issue within the team and will update you as soon as possible

**Comment by rrjanbiah** [comment]
*Internal note*

1. 'newprojectuser' notification is sent when preference is Never - Issue
2. 'card due' notification is sent when preference is Never - As in Trello - issue?

**Comment by sridhar391** [comment]
@erl4nc 

Email notification preferences are only checked while sending the mail notification for the user activities and

For below other activities, the email notification is not checked

1. Welcome Email
2. Forgot password
3. Change password
4. New Board User
5. LDAP Welcome
6. Broadcast message
7. Due Date Notification
8. Board Import User Notification
9. Email Notification For Card Support User
10. New Card Support User

**Comment by sridhar391** [comment]
@erl4nc the below email notifications are user level email notifications and if you want to change the email notifictaions, you may not be able to login in the Restyaboard

1. Welcome Email
2. Forgot password
3. Change password
4. New Board User
5. LDAP Welcome
6. Broadcast message
7. Due Date Notification
8. Board Import User Notification
9. Email Notification For Card Support User
10. New Card Support User
