### ISSUE TITLE
In organizations, members count is not updated properly.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#38]
In organizations, members count is not updated properly.
By default it displayed 1 member.

refer the attachment.
![members not updated in organizations](https://cloud.githubusercontent.com/assets/14290356/9874355/380a7a2e-5bc3-11e5-8b67-2f644b94ac98.png)

**Comment by rrjanbiah** [comment]
We have checked in all environment and its working fine. If the issue still exists, can you please post steps to reproduce this issue.
