### ISSUE TITLE
In modal card and footer notification, Filter by comments and Filter by activities options are not working properly

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3807]
## Expected Behavior
In modal card and footer notification, Filter by comments and Filter by activities options should work properly

## Current Behavior
In modal card and footer notification, Filter by comments and Filter by activities options are not working properly

## Steps to Reproduce (for bugs)
1. Open the modal card
2. Click  Filter by comments or Filter by activities three times

**Comment by sridhar391** [comment]
If the user clicks the comment or activity icon in the modal card activity section, first, the selected filter will be applied and the comments will be only shown and if the user clicks the comment section all the activity will be displayed.

**Comment by srileka** [comment]
Issue Not Fixed.

If we filtering the activity and comments, it's working fine. But icon visualization is wrong

![reopen_3807](https://user-images.githubusercontent.com/14290356/73847830-0c0bc100-484d-11ea-9664-cab29ebf0423.png)
