### ISSUE TITLE
If we add the card through the instant add card and then move the card, console error is thrown "Uncaught TypeError: Cannot read property 'attributes' of undefined"

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3832]
## Expected Behavior

If we add the card through the instant add card and then move the card, card should be move properly

## Current Behavior

If we add the card through the instant add card and then move the card, console error is thrown "Uncaught TypeError: Cannot read property 'attributes' of undefined"

## Screenshots (if appropriate):

![card_instant_move](https://user-images.githubusercontent.com/14290356/73717636-63703b00-4740-11ea-8c44-b9933159852a.png)

**Comment by sridhar391** [comment]
Fixed the above issue in the Instant add card app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
