### ISSUE TITLE
When we trying to open the card after adding the card, unable to open

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3833]
## Expected Behavior

When we trying to open the card after adding the card, card should be open

## Current Behavior

When we trying to open the card after adding the card, unable to open

## Screenshots (if appropriate):

![card_open](https://user-images.githubusercontent.com/14290356/73717721-96b2ca00-4740-11ea-8ffa-12c0f72b164f.png)

**Comment by sridhar391** [comment]
Duplicate https://github.com/RestyaPlatform/board/issues/3804
