### ISSUE TITLE
If we add the card through the instant add card and then move the card, scroll bar is not working properly

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3834]
## Expected Behavior

If we add the card through the instant add card and then move the card, scroll bar is not working properly

## Current Behavior

If we add the card through the instant add card and then move the card, scroll bar is not working properly

## Screenshots (if appropriate):

![scrool](https://user-images.githubusercontent.com/14290356/73717817-d7124800-4740-11ea-94ef-4db5d3094545.png)

**Comment by sridhar391** [comment]
Fixed the above issue in the Instant add card app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
