### ISSUE TITLE
If we add the card through the instant add card, card count is did not updated in list

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3835]
## Expected Behavior

If we add the card through the instant add card, card count should be update in the list

## Current Behavior

If we add the card through the instant add card, card count is did not updated in list

## Screenshots (if appropriate):

![card_count_instant](https://user-images.githubusercontent.com/14290356/73717910-150f6c00-4741-11ea-9793-9db4bc10acdf.png)

**Comment by sridhar391** [comment]
Fixed the above issue in the Instant add card app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
