### ISSUE TITLE
If we refreshing the page in gantt view and then come to calendar view, console error is thrown "Uncaught TypeError: l.getFullYear is not a function"

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3836]
## Expected Behavior

If we refreshing the page in gantt view and then come to calendar view, console error is thrown "Uncaught TypeError: l.getFullYear is not a function"

## Current Behavior

If we refreshing the page in gantt view and then come to calendar view, console error is thrown "Uncaught TypeError: l.getFullYear is not a function"

## Screenshots (if appropriate):

![calendar_console](https://user-images.githubusercontent.com/14290356/73723842-08464480-4750-11ea-92bc-c8edfcb99051.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the `dev` branch and the fix will be available in the upcoming release v0.6.9 (Stereopony)
