### ISSUE TITLE
If we refreshing the page, board not found content is displayed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3837]
## Expected Behavior

If we refreshing the page, board not found content is displayed

## Current Behavior

If we refreshing the page, board not found content is displayed

If we add or remove the member, board not found content displayed in other user browser

## Screenshots (if appropriate):

![board_not_found](https://user-images.githubusercontent.com/14290356/73723995-5e1aec80-4750-11ea-98af-905e5ac80c35.png)

**Comment by sridhar391** [comment]
We are closing this issue as we are not able to re-produce the issue, please feel to reopen if the issue occurred again and add the reproduce steps

**Comment by srileka** [comment]
Issue Not Fixed.

Doing any activity, then refresh the page "board not found" content displayed in current and other user browser

![board_not_found](https://user-images.githubusercontent.com/14290356/74133806-64f1a580-4c0f-11ea-8285-aa594a9583e2.png)

**Comment by sridhar391** [comment]
@srileka We are closing this issue as we are not able to re-produce the issue, please feel to reopen if the issue occurred again and add the reproduce steps
