### ISSUE TITLE
Apache2 Debian Default Page instead of the page

### ISSUE THREAD

**Issue by Luke-101** [RestyaPlatform/board#3839]
Hello, yesterday I installed restya with the Linux Script and all when right but today when I tried to connect to it i saw the Apache2 Debian Default Page.
I also tried to with different Browser but i get the same result.

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/53636779/73737382-cf53a300-4742-11ea-9ec7-822f83b188e2.png)

## Your Environment
* Version used: 0.6.8 (latest)
* Environment: raspberry pi with raspbian

**Comment by sridhar391** [comment]
@Luke-101 please attach the restyaboard_install.log file

**Comment by Luke-101** [comment]
[restyaboard_install.log](https://github.com/RestyaPlatform/board/files/4152790/restyaboard_install.log)

**Comment by sridhar391** [comment]
@Luke-101 Can you please execute the below two commands in the terminal and paste the response here

`service apache2 status`
`service nginx status`

**Comment by Luke-101** [comment]
![image](https://user-images.githubusercontent.com/53636779/73740271-2e67e680-4748-11ea-96d3-925472a559cd.png)
But when I tried to start nginx:
![image](https://user-images.githubusercontent.com/53636779/73740387-6838ed00-4748-11ea-827b-7943ba8c1c02.png)

**Comment by sridhar391** [comment]
@Luke-101 Please execute the command `service apache2 stop` to stop the Apache server and execute the command `service nginx restart` to restart the Nginx server and load the Restyaboard URL and please tell if the Restyaboard login page loading?

**Comment by Luke-101** [comment]
Ok now it work but I have to do this every time i reboot the system ?

**Comment by sridhar391** [comment]
@Luke-101 No, you don't have to execute the commands after every reboot of the system

**Comment by Luke-101** [comment]
but I have just rebooted and I've got the same error as before

**Comment by sridhar391** [comment]
@Luke-101 You can uninstall the Apache server to avoid this issue

**Comment by Luke-101** [comment]
ok thanks
