### ISSUE TITLE
Restyaboard without nginx

### ISSUE THREAD

**Issue by irby42** [RestyaPlatform/board#3840]
I've completed the installation through the Ubuntu script you provide but I've kept my Apache settings and didn't install nginx at all. I am currently getting a reloading page without forwarding me to the login page. 

Is nginx needed in order to run RB?

I basically get a 404 on http://xxx/board/client/api/v1/oauth.json?_=158xxxxx4345

**Comment by sridhar391** [comment]
@irby42 You don't need Nginx to run Restyabard, Restyaboard can be also configured in different servers and in the install script also, if the Apache server is running, the user will be asked to choose whether to configure Restyaboard on Apache or Nginx.

Can you please attach us the `restyaboard_install.log` file to understand and solve the issue?

**Comment by irby42** [comment]
Sure thing, here you go. Thank you.
[restyaboard_install.log](https://github.com/RestyaPlatform/board/files/4158986/restyaboard_install.log)

**Comment by sridhar391** [comment]
@irby42 Please attach the Apache server error log

**Comment by irby42** [comment]
The error log is empty :/

**Comment by irby42** [comment]
Fixed it. I had some errors on my htaccess file and then had to install php7.3-pgsql (thought it was already installed)
