### ISSUE TITLE
Problem with image laoding

### ISSUE THREAD

**Issue by Luke-101** [RestyaPlatform/board#3842]
Hello, today when i logged in I found that every image (profile or attachment on card) cannot be found by the client
## Screenshots:
![image](https://user-images.githubusercontent.com/53636779/73826645-747f8180-47fe-11ea-90dc-04c4607f3c72.png)
![image](https://user-images.githubusercontent.com/53636779/73826853-c6280c00-47fe-11ea-82f8-eb3fb4b743ab.png)
![image](https://user-images.githubusercontent.com/53636779/73826948-fa033180-47fe-11ea-86ef-26b3262cfed0.png)

## Your Environment
* Version used: 0.6.8 (latest)
* Environment: raspberry pi with raspbian

**Comment by sridhar391** [comment]
@Luke-101 Can you please set R_DEBUG as true on the config.inc.php file in line 15 on 'C:\xampp\htdocs\board\server\php' path like https://github.com/RestyaPlatform/board/blob/dev/server/php/config.inc.php#L15 and please open the image in new tab and copy the contents and paste it here.

**Comment by Luke-101** [comment]
URL:http://192.168.1.42/img/micro_thumb/User/1.2693f85e04a5ee2e71e12b22a2698db9.png?uid=2809

Response:
Warning: call_user_func() expects parameter 1 to be a valid callback, function 'imagecreatefrompng' not found or invalid function name in /usr/share/nginx/html/restyaboard/server/php/image.php on line 131

Fatal error: Uncaught Error: Call to undefined function imagecreate() in /usr/share/nginx/html/restyaboard/server/php/image.php:168 Stack trace: #0 {main} thrown in /usr/share/nginx/html/restyaboard/server/php/image.php on line 168

**Comment by sridhar391** [comment]
@Luke-101 You have to enable the PHP GD extension by opening  the `php.ini` file in the `C:\xampp\php` folder path and remove the `;` from the code like `extension=php_gd2.dll` and restart the server and restart the Xampp server and please tell us if the images are loading?

**Comment by Luke-101** [comment]
So I tried to find this php.ini file in the file structure of the raspberry and I found 3 of it but no one contains the ";extension=php_gd2.dll" line so I tried to add it and restart the nginx service but with no luck

**Comment by sridhar391** [comment]
@Luke-101 Sorry, we have given the instructions for Windows Apache server, can you please attach the `restyaboard_install.log` file

**Comment by Luke-101** [comment]
https://github.com/RestyaPlatform/board/files/4152790/restyaboard_install.log
(This is from the post I made yesterday)

**Comment by sridhar391** [comment]
@Luke-101 Please execute the command `sudo apt-get install php-imagick` to install the PHP imagemagick extension and after installing restart the PHP and Nginx server by executing below commands

 `service php7.2-fpm restart`
`service nginx restart`

**Comment by Luke-101** [comment]
Just done it without any problems.
But nothing has changed

**Comment by sridhar391** [comment]
@Luke-101 Please execute the command `sudo apt-get install php7.2-gd` to install the PHP GD extension and after installing restart the PHP and Nginx server by executing below commands

 `service php7.2-fpm restart`
`service nginx restart`

**Comment by Luke-101** [comment]
Ok thanks. now it works
