### ISSUE TITLE
After added the user in admin gantt page, tick symbol need to display in username

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3843]
## Expected Behavior

After added the user in admin gantt page, tick symbol need to display in username

## Current Behavior

After added the user in admin gantt page, tick symbol not displayed in username

## Screenshots (if appropriate):

![gann_user_tick](https://user-images.githubusercontent.com/14290356/73834988-ae6a7b00-4832-11ea-8832-9a422ee4623d.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
