### ISSUE TITLE
While adding or removing the member in gantt page, member did not updated properly

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3844]
## Expected Behavior

While adding or removing the member in gantt page, member did not updated properly

## Current Behavior

While adding or removing the member in gantt page, member did not updated properly

## Screenshots (if appropriate):

![member_add1](https://user-images.githubusercontent.com/14290356/73835761-f938c280-4833-11ea-911a-54ef4ea2f742.png)

![member_add](https://user-images.githubusercontent.com/14290356/73835765-fb9b1c80-4833-11ea-8b8b-c01a4584bd94.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
