### ISSUE TITLE
List with WIP limit and not exceeding the card count are not showing in Instant add card

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3845]
## Expected Behavior

List with WIP limit and not exceeding the card count are not showing in Instant add card

## Current Behavior

List with WIP limit and not exceeding the card count are not showing in Instant add card

## Screenshots (if appropriate):

![list_missing](https://user-images.githubusercontent.com/14290356/73837566-bd076100-4837-11ea-92bb-1ae18f5925ce.png)

**Comment by sridhar391** [comment]
Fixed the issue in the Instant add card app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
