### ISSUE TITLE
If we giving the member and emoji in comment, check the comments 

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3849]
## Expected Behavior

If we giving the member and emoji in comment, check the comments 

## Current Behavior

If we giving the member and emoji in comment, check the comments 

## Screenshots (if appropriate):

![comment](https://user-images.githubusercontent.com/14290356/73848670-8e48b500-484e-11ea-8023-3991813310d4.png)

**Comment by sridhar391** [comment]
@srileka Like trello, we have shown the preview for the mention member and emoji and there should be space between text and member mention
