### ISSUE TITLE
Blank login page

### ISSUE THREAD

**Issue by qupo** [RestyaPlatform/board#385]
Hi,
I have a problem with blank login page. I've tried all recommendations from other "blank login issues" but it not help. 
OS: Ubuntu 14.04
DB: Postgresql 9.3
Web: Apache2
Apache and Postgres was installed before Restyaboard. Restya was installed by restyaboard.sh and then I copy .htaccess from git to restyaboard folder. In restyaboards_install.log was some errors:
`Errors were encountered while processing:
 /var/cache/apt/archives/libjpeg8_8d-1+deb7u1_amd64.deb
 /var/cache/apt/archives/libjpeg-progs_8d-1+deb7u1_amd64.deb
 /var/cache/apt/archives/mysql-client-5.5_5.5.47-0+deb7u1_amd64.deb`

In apache logs I see only one error: 
`[Mon Feb 29 14:54:07.045594 2016] [core:info] [pid 5666] [client ::1:60074] AH00128: File does not exist: /var/www/api/v1/oauth.json, referer: http://localhost/restyaboard/client/`
I think that problem with my /api/ rule in .htaccess, but I've checked other rules and they works fine (change link to fav icon).

Thanks.

**Comment by rrjanbiah** [comment]
@qupo 

> [Mon Feb 29 14:54:07.045594 2016] [core:info] [pid 5666] [client ::1:60074] AH00128: File does not exist: /var/www/api/v1/oauth.json, referer: http://localhost/restyaboard/client/

Above error suggests that Apache mod_rewrite rules are not working. Can you please check in that aspect?

**Comment by qupo** [comment]
Seems it working:
`[Mon Feb 29 18:05:21.240128 2016] [rewrite:trace3] [pid 10271] mod_rewrite.c(468): [client ::1:33900] ::1 - - [localhost/sid#7f3ce7890560][rid#7f3ce77d50a0/initial] [perdir /var/www/restyaboard/] applying pattern '^api/(.*)$' to uri 'client/' `

**Comment by rrjanbiah** [comment]
@qupo Can you please check document root and paths? It definitely looks like `r.php` is not getting called.

**Comment by rrjanbiah** [comment]
@qupo Were you able to resolve it? If not, can you please attach install log? Before attaching please mask any sensitive information in it.

**Comment by qupo** [comment]
Sorry, was far away from internet. Yes, it was partially solved. At least, I see login page.
As you said, problem was in document root link. I have 2 services in 1 virtual host and they both located in /var/www and document root was /var/www/. Then I changed it to /var/www/restyaboard and was able to see login page, but ofc other service don't work now. I'll close the bug, thank you for help.

**Comment by rrjanbiah** [comment]
@qupo You're most welcome. If you are still looking for any help, please feel free to update.
