### ISSUE TITLE
While trying to add dependency in the board page gantt view, console error thrown

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3856]
## Expected Behavior
While trying to add dependency in the board page gantt view, console error should not be thrown 

## Current Behavior
While trying to add dependency in the board page gantt view, console error thrown

## Steps to Reproduce (for bugs)
1. Open the board
2. Add start date and due date to the cards
3. Goto the Gantt View and try to add dependency

**Comment by sridhar391** [comment]
Fixed the issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)

**Comment by srileka** [comment]
Issue Not Fixed.

Card dependency not update in gannt page.

**Comment by sridhar391** [comment]
Fixed the issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
