### ISSUE TITLE
If we giving the due date only , start date did not displayed in member view

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3859]
## Expected Behavior

If we giving the due date only , start date did not displayed in member view

## Current Behavior

If we giving the due date only , start date did not displayed in member view

## Screenshots (if appropriate):

![duedate_gannt](https://user-images.githubusercontent.com/14290356/74082261-309aaf80-4a7e-11ea-920c-8a6b231d6e02.png)

**Comment by sridhar391** [comment]
Fixed the issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
