### ISSUE TITLE
Unable to add a member to an organization via API

### ISSUE THREAD

**Issue by nicolas-r** [RestyaPlatform/board#386]
Hi

I'm playing with the API but can't add a member to an organization, I get :

2016/02/29 17:48:41 [error] 82#0: *4026 FastCGI sent in stderr: "PHP message: PHP Warning:  pg_query_params(): Query failed: ERROR:  null value in column &quot;organization_id&quot; violates not-null constraint
DETAIL:  Failing row contains (86, 2016-02-29 17:48:41.121281, 2016-02-29 17:48:41.121281, null, null, null). in /usr/share/nginx/html/server/php/R/libs/core.php on line 821" while reading response header from upstream, client: 192.168.0.21, server: _, request: "POST /api/v1/organizations/35/users/6.json?token=7a87dd6df77a73ff8e5778698e3064652f520469 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "centos-docker:1234"

Here is what my program currently does :
* Get the access token
* Login with default admin user
* Retrieve some infos about the existing users (id, email)
* Create an organization
* Try to add the existing users to this organization
And that fails

* Example of debug output:

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): centos-docker
send: 'POST /api/v1/organizations/37/users/3.json?token=081d8974fd15c619d519a7b6e9ef980dd377f7f8 HTTP/1.1\r\nHost: centos-docker:1234\r\nContent-Length: 0\r\nUser-Agent: python-requests/2.9.1\r\nConnection: keep-alive\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx/1.2.1
header: Date: Mon, 29 Feb 2016 17:54:13 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: X-Powered-By: PHP/5.4.45-0+deb7u2
header: Access-Control-Allow-Origin: http://centos-docker:1234
header: Access-Control-Allow-Methods: *
header: Content-Encoding: gzip
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/v1/organizations/37/users/3.json?token=081d8974fd15c619d519a7b6e9ef980dd377f7f8 HTTP/1.1" 200 None
 done.

* Same if I try to pass the email as a parameter

INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): centos-docker
send: 'POST /api/v1/organizations/29/users/3.json?token=2e0d762684eae6fb5692b637e1535634d912446d HTTP/1.1\r\nHost: centos-docker:1234\r\nContent-Length: 26\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nUser-Agent: python-requests/2.9.1\r\nConnection: keep-alive\r\nContent-Type: application/json\r\n\r\n{"email": "user1@test.com"}'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx/1.2.1
header: Date: Mon, 29 Feb 2016 17:32:18 GMT
header: Content-Type: application/json
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: X-Powered-By: PHP/5.4.45-0+deb7u2
header: Access-Control-Allow-Origin: http://centos-docker:1234
header: Access-Control-Allow-Methods: *
header: Content-Encoding: gzip
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/v1/organizations/29/users/3.json?token=2e0d762684eae6fb5692b637e1535634d912446d HTTP/1.1" 200 None
 done.

I'm using the 0.1.6 version running inside a docker. Docker file comes from https://github.com/namikingsoft/docker-restyaboard

**Comment by nicolas-r** [comment]
I have the same problem to add a member to a board.

**Comment by ssivachidambaram** [comment]
We have fixed in our dev version. Please refer the pull request #394.

**Comment by nicolas-r** [comment]
Hi

thank your for the fix. Can I apply your fix on the 0.1.6 code ? Because I can't build the dev version

**Comment by ssivachidambaram** [comment]
Yes. You can apply the changes in 0.1.6 version.
