### ISSUE TITLE
After creating the card, while we set the due date immediately, "start time" wrong in gantt view

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3863]
## Expected Behavior

After creating the card, while we set the due date immediately, "start time" wrong in gantt view

## Current Behavior

After creating the card, while we set the due date immediately, "start time" wrong in gantt view

## Screenshots (if appropriate):

![starttime_gantt](https://user-images.githubusercontent.com/14290356/74141592-38448a80-4c1d-11ea-9154-737aa77cb9b8.png)

**Comment by sridhar391** [comment]
Fixed the issue in the Gantt View app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
