### ISSUE TITLE
Unable to import trello json file in to the Restyaboard

### ISSUE THREAD

**Issue by stanleyliu1006** [RestyaPlatform/board#387]
Hi 

Can you please advise the reasons that import trello file failed, the sample file I am using is as below:

[trello_email.zip](https://github.com/RestyaPlatform/board/files/152017/trello_email.zip)

When I upload to the restyaboard, it shows unable to import, please try it again.

Is there any permission configuration I may miss?

Kind regards
Stanley

**Comment by rrjanbiah** [comment]
@stanleyliu1006 This is because PHP's `json_decode` function is throwing error for above file. We're looking into it.

**Comment by ssivachidambaram** [comment]
Fixed in our dev version. Please refer pull request #395.

**Comment by rrjanbiah** [comment]
@stanleyliu1006 @ssivachidambaram For the sake of record, exact issue with above file was:

`Malformed UTF-8 characters, possibly incorrectly encoded`
