### ISSUE TITLE
Inquiry on the extra functions

### ISSUE THREAD

**Issue by stanleyliu1006** [RestyaPlatform/board#388]
Hi 

We are using the restyaboard for our email analysis tool, just wondering for the card details, can we add free textbox to capture some input data, or if no there's any alternative solutions to achieve this, and we can easily to generate some reports based on these textfields?

Kind regards
Stanley

**Comment by rrjanbiah** [comment]
@stanleyliu1006 Currently this requirement needs customization.

We have planned to add similar feature sometime later. But, we don't have set any timeline for that.

**Comment by ssivachidambaram** [comment]
Done in `dev` branch. Custom fields can able through app architecture.
