### ISSUE TITLE
In MyRestyaboards iOS app, In add user, after giving the mail id click the first name, page design gets broken

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3887]
## Expected Behavior

In MyRestyaboards iOS app, In add user, after giving the mail id click the first name, page design gets broken

## Current Behavior

In MyRestyaboards iOS app, In add user, after giving the mail id click the first name, page design gets broken

## Screenshots (if appropriate):

![4_user_design](https://user-images.githubusercontent.com/14290356/74154810-5e782380-4c39-11ea-8022-71fbc4bfe703.png)

**Comment by sridhar391** [comment]
@srileka While the phone keyboard opens only, the footer is showing in the top of phone keyboard
