### ISSUE TITLE
In MyRestyaboards iOS app, If we clicking the pagination in footer, page should be redirecting to top

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3888]
## Expected Behavior

In MyRestyaboards iOS app, If we clicking the pagination in footer, page should be redirecting to top

## Current Behavior

If we clicking the pagination in footer, page should be redirecting to top

Note: Check all the admin pages

## Screenshots (if appropriate):

![5_pagination_top](https://user-images.githubusercontent.com/14290356/74154898-8c5d6800-4c39-11ea-9cff-0542924ba386.png)

**Comment by sridhar391** [comment]
@srileka We have tried to reproduce the issue in MyRestyaboards iOS app and the page and shows the top contents when clicking the pagination.
