### ISSUE TITLE
In MyRestyaboards iOS app, Images are displayed as blur in app

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3889]
## Expected Behavior

Images are displayed as blur in app

## Current Behavior

Images are displayed as blur in app

## Screenshots (if appropriate):

![6_image_blurr](https://user-images.githubusercontent.com/14290356/74154977-b57df880-4c39-11ea-9a93-c97db93d6495.png)

**Comment by sridhar391** [comment]
Fixed the issue in the dev branch and the fix will be available in the upcoming release v0.6.9 (Stereopony)
