### ISSUE TITLE
In MyRestyaboards iOS app, Admin roles page, selected options need to display like users page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3893]
## Expected Behavior

In MyRestyaboards iOS app, Admin roles page, selected options need to display like users page

## Current Behavior

In MyRestyaboards iOS app, Admin roles page, selected options need to display like users page

## Screenshots (if appropriate):

![10_select_option](https://user-images.githubusercontent.com/14290356/74155272-4a80f180-4c3a-11ea-804e-b9bbe12e7f5b.png)

**Comment by sridhar391** [comment]
@srileka In the users page, there are list of known filters and in the roles page, there are only three filters for checking the permission level and this design is only suitable for the roles page
