### ISSUE TITLE
In MyRestyaboards iOS app, In Users page, after clicking the ok in alert box, more actions option should not be display 

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3895]
## Expected Behavior

In MyRestyaboards iOS app, In Users page, after clicing the ok in alert box, more actions option should not be display 

## Current Behavior

In MyRestyaboards iOS app, In Users page, after clicing the ok in alert box, more actions option should not be display 

Note: Check all the admin pages

## Screenshots (if appropriate):

![1](https://user-images.githubusercontent.com/17172525/101138839-b6ec3780-3636-11eb-9725-a8c52919c3e8.png)
![2](https://user-images.githubusercontent.com/17172525/101138846-b8b5fb00-3636-11eb-9ed3-42317af38c9f.png)

**Comment by sridhar391** [comment]
@srileka Please clikc the `Done` option after performing the actions on the user
