### ISSUE TITLE
In MyRestyaboards iOS app, Scroll option some difficult in app

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3896]
## Expected Behavior

In MyRestyaboards iOS app, Scroll option some difficult in app

## Current Behavior

In MyRestyaboards iOS app, Scroll option some difficult in app

## Screenshots (if appropriate):

![13_scroll](https://user-images.githubusercontent.com/14290356/74155419-90d65080-4c3a-11ea-9a68-0837dc640f19.png)

**Comment by sridhar391** [comment]
@srileka We are able to smoothly scroll through MyRestyaboards iOS app
