### ISSUE TITLE
In MyRestyaboards iOS app, Broadcast Messages Settings page, check the table border alignment

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3899]
## Expected Behavior

In MyRestyaboards iOS app, Broadcast Messages Settings page, check the table border alignment

## Current Behavior

In MyRestyaboards iOS app, Broadcast Messages Settings page, check the table border alignment

## Screenshots (if appropriate):

![16_table_align](https://user-images.githubusercontent.com/14290356/74155615-e6126200-4c3a-11ea-8651-02a2b2559a4b.png)

**Comment by sridhar391** [comment]
Fixed the issue in the Broadcasts app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
