### ISSUE TITLE
In MyRestyaboards iOS app, Broadcast Messages Settings page, Check the delete button, content and close icon alignment

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3900]
## Expected Behavior

In MyRestyaboards iOS app, Broadcast Messages Settings page, Check the delete button, content and close icon alignment

## Current Behavior

In MyRestyaboards iOS app, Broadcast Messages Settings page, Check the delete button, content and close icon alignment

## Screenshots (if appropriate):

![17_delete_align](https://user-images.githubusercontent.com/14290356/74155669-fb878c00-4c3a-11ea-9e74-fc603152249b.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the Broadcasts app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
