### ISSUE TITLE
In MyRestyaboards iOS app, In Broadcast Messages Settings page, end date field value always displayed empty

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3901]
## Expected Behavior

In MyRestyaboards iOS app, In Broadcast Messages Settings page, end date field value always displayed empty

## Current Behavior

In MyRestyaboards iOS app, In Broadcast Messages Settings page, end date field value always displayed empty

## Screenshots (if appropriate):

![18_enddae_broad](https://user-images.githubusercontent.com/14290356/74155729-14903d00-4c3b-11ea-81d8-2dbc7bede26b.png)

**Comment by sridhar391** [comment]
@srileka The email type broadcast  is an one time broadcast and it will be sent in mail to all the Restyaboard users once created. so, there is no need for showing End date
