### ISSUE TITLE
In MyRestyaboards iOS app, Email type broadcast messages, edit and delete option is not there

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3902]
## Expected Behavior

In MyRestyaboards iOS app, Email type broadcast messages, edit and delete option is not there

## Current Behavior

In MyRestyaboards iOS app, Email type broadcast messages, edit and delete option is not there

## Screenshots (if appropriate):

![19_edit_delete](https://user-images.githubusercontent.com/14290356/74155803-296cd080-4c3b-11ea-818d-55cea379b4cd.png)

**Comment by sridhar391** [comment]
@srileka The email type broadcast  is an one time broadcast and it will be sent in mail to all the Restyaboard users once created. so, there is no need for Edit and Delete action to the broadcast
