### ISSUE TITLE
In custom field settings page, need single space between the edit and icon

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3910]
## Expected Behavior

In custom field settings page, need single space between the edit and icon

## Current Behavior

In custom field settings page, need single space between the edit and icon

## Screenshots (if appropriate):

![21_edit_custom_settings](https://user-images.githubusercontent.com/14290356/74304136-19abd400-4d82-11ea-9c40-858128bb5570.png)

**Comment by sridhar391** [comment]
Fixed the issue in the Custom Fields app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
