### ISSUE TITLE
In MyRestyaboards iOS app, without giving the value, we able to add the custom field in manage page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3911]
## Expected Behavior

In MyRestyaboards iOS app, without giving the value, we able to add the custom field in manage page

## Current Behavior

In MyRestyaboards iOS app, without giving the value, we able to add the custom field in manage page

## Screenshots (if appropriate):

![22_custom_field_novalue](https://user-images.githubusercontent.com/14290356/74304226-58da2500-4d82-11ea-96ce-7d561ba0ab11.png)

**Comment by sridhar391** [comment]
Fixed the issue in the Custom Fields app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
