### ISSUE TITLE
In MyRestyaboards iOS app, check the selected color bar and remove button alignment in manage page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3912]
## Expected Behavior

In MyRestyaboards iOS app, check the selected color bar and remove button alignment in manage page

## Current Behavior

In MyRestyaboards iOS app, check the selected color bar and remove button alignment in manage page

## Screenshots (if appropriate):

![23_color_bar](https://user-images.githubusercontent.com/14290356/74304300-8e7f0e00-4d82-11ea-95d0-0bdff3c3e578.png)

**Comment by sridhar391** [comment]
Fixed the issue in the Custom Fields app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
