### ISSUE TITLE
In MyRestyaboards iOS app, edit field button gets brokened in manage page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3913]
## Expected Behavior

In MyRestyaboards iOS app, edit field button gets brokened in manage page

## Current Behavior

In MyRestyaboards iOS app, edit field button gets brokened in manage page

## Screenshots (if appropriate):

![24_edit_broken](https://user-images.githubusercontent.com/14290356/74304860-334e1b00-4d84-11ea-843d-1b9fbc3c9c7e.png)

**Comment by sridhar391** [comment]
Fixed the issue in the Custm Fields app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
