### ISSUE TITLE
In MyRestyaboards iOS app, check the delete field content alignment in manage page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3914]
## Expected Behavior

In MyRestyaboards iOS app, check the delete field content alignment in manage page

## Current Behavior

In MyRestyaboards iOS app, check the delete field content alignment in manage page

## Screenshots (if appropriate):

![25_delete_content_align](https://user-images.githubusercontent.com/14290356/74305160-19f99e80-4d85-11ea-98ff-25436b6b658e.png)

**Comment by sridhar391** [comment]
@srileka Fixed the issue in the Custom Fields app local commit and the fix will be available in the upcoming release v0.6.9 (Stereopony)
