### ISSUE TITLE
Sorting option did not working in custom field manage page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3915]
## Expected Behavior

Sorting option did not working in custom field manage page

## Current Behavior

Sorting option did not working in custom field manage page

## Screenshots (if appropriate):

![26_sort_cutom](https://user-images.githubusercontent.com/14290356/74305188-3695d680-4d85-11ea-83e1-99ef501cd435.png)

**Comment by sridhar391** [comment]
@srileka if the "Sort By" option value is "name", then in the admin panel custom fields apps page, the custom fields  will be ordered according to their names
