### ISSUE TITLE
In MyRestyaboards iOS app, we unable to edit the value in dashboard charts settings page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3917]
## Expected Behavior

In MyRestyaboards iOS app, we unable to edit the value in dashboard charts settings page

## Current Behavior

In MyRestyaboards iOS app, we unable to edit the value in dashboard charts settings page

## Screenshots (if appropriate):

![28_dashboard_value](https://user-images.githubusercontent.com/14290356/74305290-896f8e00-4d85-11ea-847c-b63cad31a056.png)

**Comment by sridhar391** [comment]
Duplicate #3909
