### ISSUE TITLE
In MyRestyaboards iOS app, We unable to edit the text field and dropdwon field in admin apps page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3922]
## Expected Behavior

In MyRestyaboards iOS app, We unable to edit the text field and dropdwon field in admin apps page

elastic search settings page, hide card additional settings, import from github, label style, slack and Support Desk - Settings

## Current Behavior
In MyRestyaboards iOS app, We unable to edit the text field and dropdwon field in admin apps page

elastic search settings page, hide card additional settings, import from github, label style, slack and Support Desk - Settings

## Screenshots (if appropriate):

![33_select](https://user-images.githubusercontent.com/14290356/74306002-54fcd180-4d87-11ea-8371-941292310a5d.png)

**Comment by sridhar391** [comment]
Duplicate https://github.com/RestyaPlatform/board/issues/3909
