### ISSUE TITLE
We unable to add the wiki in admin apps page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3923]
## Expected Behavior

We unable to add the wiki in admin apps page

## Current Behavior

We unable to add the wiki in admin apps page

## Screenshots (if appropriate):

![34_wiki](https://user-images.githubusercontent.com/14290356/74306046-6e058280-4d87-11ea-8e9f-e4714801206d.png)

**Comment by sridhar391** [comment]
It seems there is an issue in the database and the issue has been fixed
