### ISSUE TITLE
In MyRestyaboards iOS app, "settings and email templates" pages selected options need to display like users page

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#3924]
## Expected Behavior

In MyRestyaboards iOS app, "settings and email templates" pages selected options need to display like users page

## Current Behavior

In MyRestyaboards iOS app, "settings and email templates" pages selected options need to display like users page

## Screenshots (if appropriate):

![35_select_option](https://user-images.githubusercontent.com/14290356/74306097-8ecdd800-4d87-11ea-98f7-c6e251f4c6b2.png)

**Comment by sridhar391** [comment]
@srileka We are having list of email templates and it will be not suitable to change it like users page
