### ISSUE TITLE
script to support Apache

### ISSUE THREAD

**Issue by witzker** [RestyaPlatform/board#3932]
> @adnanmitf09
> 
> > in 1915 you wrote
> > 
> > We have a plan to update the install script to support Apache. Hopefully for the time being you can use this.

Is the installation script ready in the meantime?
I try to install on Ionos (1und1) web space but really don't know how
I copied files But I do not know how to go on

**Comment by sridhar391** [comment]
`Required software`: nginx or apache, php-fpm (with mbstring, ImageMagick and IMAP), PostgreSQL, GeoIP and jq

Download [latest "ready deployable" version](https://github.com/RestyaPlatform/board/releases/download/v0.6.8/board-v0.6.8.zip). You can directly unzip and upload to your server—without needing to build with grunt.

- `sql/restyaboard_with_empty_data.sql` - Database generation script
- `server/php/config.inc.php` - Database and other configurations
- `media, tmp/cache, server/php/shell/*.sh` & `client/img` - Need write permission for php; can be `chmod 655` or `755` or `777` depending upon server configuration
- Setup cron for sending email notification to user, HTTP POST payload to the webhook's configured URL, due date notification email to user and to read configured IMAP email for add card or update card comment `*/5 * * * * /path/to/server/php/shell/main.sh`

**Comment by witzker** [comment]
THX
But I really don't know how to execute the commands on hosted server at Ionos hosted sever
pls help

I also found this:
https://restya.com/board/docs/apache/#0

I created a  .htaccess in the root directory where the files are but the serve says:
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.
Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by sridhar391** [comment]
@witzker Please schedule your convenient time to configure the Restyaboard in your server in the link https://calendly.com/restya/it-support?email=max.witzker@gmail.com&name=MaxWitzker

**Comment by witzker** [comment]
Great THX
what should I prepare

**Comment by sridhar391** [comment]
@witzker Please schedule your time to meeting and please install the [zoom](https://support.zoom.us/hc/en-us/articles/204206269-Linux-Installation) software in your server we will install the Restyabard in your server

**Comment by witzker** [comment]
I don't know how to install zoom on server
I have a Windows PC with TeamViewer, is this possible

**Comment by witzker** [comment]
Zoom installed and opened waiting for your call at 14:00
THX

**Comment by witzker** [comment]
THX for your support with zoom

I asked Ionos support but:

gern beantworte ich ihre Frage zur Einrichtung im eines anderen Datenbankservers  postgresql.

Im  Sharehosting ist dies nicht möglich. ( NOT Possible)

Ich freue mich, wenn ich Ihnen damit weitergeholfen habe.

Freundliche Grüße

Hans-Jürgen Meißner
IONOS Kundenservice

Facebook: https://www.facebook.com/ionos.deutschland
Twitter: https://twitter.com/IONOS_hilft

Can You PLS be so kind and recommend me another tool similar to Restya which can be installed with sql database or without a Database

I know it will be hard because of quality form Restya

**Comment by rrjanbiah** [comment]
@witzker Are there any hard reasons for not trying our cloud option https://restya.com/board/cloud ?

**Comment by witzker** [comment]
Yes they insist on having it self hosted DSGVO

**Comment by rrjanbiah** [comment]
FYI, DO cloud is also compliant https://www.digitalocean.com/legal/gdpr/

**Comment by witzker** [comment]
They want it it self hosted

**Comment by rrjanbiah** [comment]
@witzker Apologies for the delay. 

It is not clear what do you mean by 'self hosted'. Both DO and IONOS are almost same kind of cloud providers. So, hope you didn't mean it for 'intranet' setup.

Also, IONOS seems to offer PostgreSQL in other plans https://twitter.com/ionos_hilft/status/1230783126110162944

So, closing this for now. In case, if you still face any issue, please feel free to reopen.

**Comment by witzker** [comment]
I Now have an Ubuntu server on a ThinkPad setup @home
as I'm totally new with this I also installed Virtualmin to make administering server easier for a beginner.
Can you pls be so kind and help me step by step to create a VPS in Virtualmin and install and run Restya there finally?
