### ISSUE TITLE
Not enough mail

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#3933]
Hello,

we do not have any notifications yet since 10 days.

I have nothing in logs and i don't know where to search. Can you help me ? 

Regards

**Comment by sridhar391** [comment]
@morphos88 can you please check if the `main.sh` file in the Restyaboad folder path `/usr/share/nginx/html/restyaboard/server/php/shell` has an executable permission

**Comment by morphos88** [comment]
@sridhar391 Thanks for your response, no there is no executable permission on main.sh :

![image](https://user-images.githubusercontent.com/25505555/74716766-7c441a80-522f-11ea-9bc5-97fe79833dfa.png)

**Comment by sridhar391** [comment]
@morphos88 Please execute  the command `chmod +x main.sh` to apply executable permission and try to manually run the `main.sh` file by executing the command `/usr/share/nginx/html/restyaboard/server/php/shell/main.sh` and please tell us if there is any error

**Comment by morphos88** [comment]
When i try to run manually : 

> PHP Warning:  file_get_contents(/usr/share/nginx/html/restyaboard/client/apps/r_chat/app.json): failed to open stream: No such file or directory in /usr/share/nginx/html/restyaboard/server/php/plugins/Chat/shell/chat_activities.php on line 20

Warning: file_get_contents(/usr/share/nginx/html/restyaboard/client/apps/r_chat/app.json): failed to open stream: No such file or directory in /usr/share/nginx/html/restyaboard/server/php/plugins/Chat/shell/chat_activities.php on line 20
PHP Warning:  file_get_contents(/usr/share/nginx/html/restyaboard/client/apps/r_elasticsearch/app.json): failed to open stream: No such file or directory in /usr/share/nginx/html/restyaboard/server/php/plugins/ElasticSearch/shell/indexing_to_elasticsearch.php on line 28

Warning: file_get_contents(/usr/share/nginx/html/restyaboard/client/apps/r_elasticsearch/app.json): failed to open stream: No such file or directory in /usr/share/nginx/html/restyaboard/server/php/plugins/ElasticSearch/shell/indexing_to_elasticsearch.php on line 28
Please configure the ElasticSearch on <a href="https://restyaboard.myclauger.com#/apps/r_elasticsearch">settings</a> pageElastic Search downPHP Warning:  pg_query_params(): Query failed: ERREUR:  la relation « card_support_users » n'existe pas
LINE 1: SELECT * FROM card_support_users
                      ^ in /usr/share/nginx/html/restyaboard/server/php/plugins/SupportApp/shell/send_activity_mail.php on line 39

Warning: pg_query_params(): Query failed: ERREUR:  la relation « card_support_users » n'existe pas
LINE 1: SELECT * FROM card_support_users
                      ^ in /usr/share/nginx/html/restyaboard/server/php/plugins/SupportApp/shell/send_activity_mail.php on line 39

**Comment by sridhar391** [comment]
@morphos88 Can you please contact our technical team regarding your issue at info@restya.com

**Comment by morphos88** [comment]
@sridhar391 Sure, thanks !

**Comment by sridhar391** [comment]
@morphos88 The issue has been fixed in the meeting and we are closing the issue.
