### ISSUE TITLE
In Modal card page, while clicking the print options in the settings share and more options, the design brakes in print page

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#3934]
## Expected Behavior
In Modal card page, while clicking the print options in the settings share and more options, the design should be perfect in print page

## Current Behavior
In Modal card page, while clicking the print options in the settings share and more options, the design brakes in print page

## Steps to Reproduce (for bugs)
1. Go to particular board
2. Click and open the modal card
3. Click settings button and click the share and more option in dropdwon menu
4. Click the print option

**Comment by erl4nc** [comment]
One of my users reports this occurs intermittently. She showed me 2 print outs of same card from same board same browser same computer. One of them looks fine and the other has broken layout.

**Comment by sridhar391** [comment]
@erl4nc The issue has been occurred in our local servers also and we are working on the issue.

[Restyaboard-print-modalcard.webm.zip](https://github.com/RestyaPlatform/board/files/4671296/Restyaboard-print-modalcard.webm.zip)

**Comment by sridhar391** [comment]
We are closing this issue as we are not able to re-produce the issue, please feel to reopen if the issue occurred again and add the reproduce steps with the form of image or video
