### ISSUE TITLE
Is there a unbuntu version of install script

### ISSUE THREAD

**Issue by fmerrow** [RestyaPlatform/board#396]
Well, I could post the whole log, but my swag is everything was going well until you tried to use "yum" . . . so while your site says it is a "linux" script, sound more like it is a Red Hat Script.

Do you have a Ubuntu version?

Frank

**Comment by fmerrow** [comment]
Never mind . . . I figured out that the install script could do both, but didn't seem to work on my system.  I am not sure what you expected in /etc/issues, but in my case it contains some IT information, clearly not what you expected.

**Comment by rrjanbiah** [comment]
@fmerrow In case if you have any more information about this, please feel free to share. We'll definitely try to fix it.

**Comment by fmerrow** [comment]
After a couple of false starts, I ordered up a fresh VM and decide to try again:
1. I am not sure I addressed LDAP 100% correct and have not addressed nsswtich.conf issue yet, but otherwise install seemed to go okay
2. EXCEPT at prompt for HTML root . . . I thought I would just take the default (or at least I thought the path shown was a default), but that did not put any files at the location . . .
3. Restarted script, it didn't want to run because was already installed, nosed around in code and deleted /opt/restyaboard and tried again
4. This time when asked for root I copied the default provided except for a minor typo and so got: /usr/share/nginx/html/restyabaord

So then I tried to run it:

http://fmerrow-vcac brings up a nginx default page . . . which seems promising

So then tried:

http://fmerrow-vcac/restyabaord/client/index.html

which immediately turns into

http://fmerrow-vcac/restyabaord/client/index.html#/users/login

However, this displays a completely blank page . . . shows NOTHING . . . except the cursor turns into a "hand" and it I try to type anything the browser exits

Suggestions?

Frank

**Comment by rrjanbiah** [comment]
@fmerrow Can you please attach your install log? That will give us better picture about your environment/setup. Please mask any sensitive information before you upload here.

**Comment by fmerrow** [comment]
Here is the install log per your request.  As I mentioned before, my /ect/issues file clearly doesn't match your expectations . . . so I hard coded OS_REQUIREMENT to "Ubuntu" before I ran the script.

[restyaboard_install.log.txt](https://github.com/RestyaPlatform/board/files/158965/restyaboard_install.log.txt)

**Comment by rrjanbiah** [comment]
@fmerrow It looks like the script doesn't have `root` access (?) and so couldn't update DB credentials in the `config.inc.php`

If the script could update nginx conf file and `config.inc.php`, you should be able to view Restyaboard in root URL itself.

Can you please open your browser console and see if there's any errors?

Also, please try to enable debug mode https://github.com/RestyaPlatform/board/blob/master/server/php/R/config.inc.php#L15 and look up HTTP header. Post HTTP header response if you get any error.

Hopefully it might be the DB credentials issue.

**Comment by rrjanbiah** [comment]
@fmerrow Were you able to resolve it?

**Comment by ssivachidambaram** [comment]
Fixed.
