### ISSUE TITLE
Restyaboard API explorer issue (add a new card)

### ISSUE THREAD

**Issue by stanleyliu1006** [RestyaPlatform/board#397]
Hi 

We are trying to test Restyaboard API, like post a card etc. But it constantly shows error 405 Invalid input as shown in the diagram below:

![image](https://cloud.githubusercontent.com/assets/6980917/13452108/16230e3e-e099-11e5-997a-c7dd4d15c35e.png)

The board_id and list_id are existing in the database
![image](https://cloud.githubusercontent.com/assets/6980917/13452120/2d36728c-e099-11e5-9b74-3da75c7ae48d.png)

The access token is right, which I can get the card info.

Please advise if there's any bug with API code, or if there's something wrong with my input variable.

Kind regards
Stanley

**Comment by ssivachidambaram** [comment]
Please check attached images in the mentioned order to create access token for an admin. Should be self explanatory. Using that access token you can able to create new card from api explorer.

![api-step1](https://cloud.githubusercontent.com/assets/91407/13492592/f3d9f61e-e15e-11e5-8dbc-7a3de4a5d18e.png)

![api-step2](https://cloud.githubusercontent.com/assets/91407/13492593/f3db4b4a-e15e-11e5-959b-923da17e540b.png)

**Comment by stanleyliu1006** [comment]
Thanks ssivachidambaram, that's work perfect.

**Comment by rrjanbiah** [comment]
@stanleyliu1006 That's nice to know. Thanks for confirming.
