### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by FanyangMengDev** [RestyaPlatform/board#4005]
Hi there, I just build from the newest dev branch and install it manually, but after all done and visit my website, I just got a blank page. When I click f12 to debug, it just alert me this.

Would you please help me have a look on it?

My website is https://kanban.fanyangmeng.com

Thanks a lot.

php_pgsql extension has already been installed

## Screenshots (if appropriate):

![图片](https://user-images.githubusercontent.com/53750381/76197713-a2a21800-6227-11ea-913b-f683784d543f.png)

## Your Environment

* Version used: Newest dev branch
* Environment name and version (e.g. OS, PHP, PostgreSQL): Ubuntu 18.04 Postgresql 12
* Operating System and version (desktop or mobile): Both
* Link to your project: https://kanban.fanyangmeng.com

**Comment by FanyangMengDev** [comment]
error] 14169#0: *1083639 open() "/www/wwwroot/kanban.fanyangmeng.com/client/api/v1/oauth.json" failed (2: No such file or directory), client: 161.117.39.40, server: kanban.fanyangmeng.com, request: "GET /api/v1/oauth.json?_=1583744614861 HTTP/2.0", host: "kanban.fanyangmeng.com", referrer: "https://kanban.fanyangmeng.com/"

**Comment by sridhar391** [comment]
@FanyangMengDev You have scheduled the zoom meeting with us, we will check about the above issue in the meeting.

**Comment by FanyangMengDev** [comment]
@sridhar391 Sorry, but can we solve it now? I really wanna solve this problem now so it will save a lot of time, please

**Comment by FanyangMengDev** [comment]
Please help me have a look on it.... I can give you all the information you need right now. It will be so so so much appreciate. Thanks in advance

**Comment by FanyangMengDev** [comment]
I can assure you that I have already installed php-pgsql and pdo-pgsql extension. I just do not understand why this happened. My English speaking is not that good so I think maybe contact you by typing will be more efficient. Thanks

**Comment by FanyangMengDev** [comment]
Here is the nginx configuration of my server:
```nginx
server
{
    listen 80;
	listen 443 ssl http2;
    server_name kanban.fanyangmeng.com;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/kanban.fanyangmeng.com/client;
    

	rewrite ^/oauth/authorize$ /server/php/authorize.php last;
	rewrite ^/oauth_callback/([a-zA-Z0-9_\.]*)/([a-zA-Z0-9_\.]*)$ /server/php/oauth_callback.php?plugin=$1&code=$2 last;
	rewrite ^/download/([0-9]*)/([a-zA-Z0-9_\.]*)$ /server/php/download.php?id=$1&hash=$2 last;
	rewrite ^/ical/([0-9]*)/([0-9]*)/([a-z0-9]*).ics$ /server/php/ical.php?board_id=$1&user_id=$2&hash=$3 last;
	rewrite ^/api/(.*)$ /server/php/R/r.php?_url=$1&$args last;
	rewrite ^/api_explorer/api-docs/$ /client/api_explorer/api-docs/index.php last;

    
    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #HTTP_TO_HTTPS_START
    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }
    #HTTP_TO_HTTPS_END
    ssl_certificate    /www/server/panel/vhost/cert/kanban.fanyangmeng.com/fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/kanban.fanyangmeng.com/privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    error_page 497  https://$host$request_uri;

    #SSL-END
    
    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    #ERROR-PAGE-END
    
    #PHP-INFO-START  PHP引用配置，可以注释或修改
    include enable-php-73.conf;
    #PHP-INFO-END
    
    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/kanban.fanyangmeng.com.conf;
    #REWRITE-END
    
    
    
    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }
    
   
    access_log  /www/wwwlogs/kanban.fanyangmeng.com.log;
    error_log  /www/wwwlogs/kanban.fanyangmeng.com.error.log;
}
```

**Comment by FanyangMengDev** [comment]
I did not add this line
```nginx
fastcgi_pass	unix:/run/php/php7.2-fpm.sock;
```
Cause I did not find where is it although I have already install php 7.3

**Comment by sridhar391** [comment]
@FanyangMengDev Please change the Restyaboard root folder path to "/www/wwwroot/kanban.fanyangmeng.com" like https://github.com/RestyaPlatform/board/blob/dev/restyaboard.conf#L5 and please add the cofiguration for PHP and image access like https://github.com/RestyaPlatform/board/blob/dev/restyaboard.conf#L32 and https://github.com/RestyaPlatform/board/blob/dev/restyaboard.conf#L41

After following the above instructions please restart the Nginx server by executing the command `systemctl restart nginx` and please tell us if the Restyaboard login page loading correctly or not?

**Comment by FanyangMengDev** [comment]
```nginx
server
{
    listen 80;
	listen 443 ssl http2;
    server_name kanban.fanyangmeng.com;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/kanban.fanyangmeng.com;
    
   
    gzip on;
	gzip_disable "msie6";

	gzip_comp_level 6;
	# gzip_comp_level 9;
	gzip_min_length  1100;
	gzip_buffers 16 8k;
	gzip_proxied any;
	# gzip_http_version 1.1;
	gzip_types       text/plain application/xml text/css text/js text/xml application/x-javascript text/javascript application/json application/xml+rss;

	client_max_body_size 300M;
    

	rewrite ^/oauth/authorize$ /server/php/authorize.php last;
	rewrite ^/oauth_callback/([a-zA-Z0-9_\.]*)/([a-zA-Z0-9_\.]*)$ /server/php/oauth_callback.php?plugin=$1&code=$2 last;
	rewrite ^/download/([0-9]*)/([a-zA-Z0-9_\.]*)$ /server/php/download.php?id=$1&hash=$2 last;
	rewrite ^/ical/([0-9]*)/([0-9]*)/([a-z0-9]*).ics$ /server/php/ical.php?board_id=$1&user_id=$2&hash=$3 last;
	rewrite ^/api/(.*)$ /server/php/R/r.php?_url=$1&$args last;
	rewrite ^/api_explorer/api-docs/$ /client/api_explorer/api-docs/index.php last;
	
	 location / {
		root /usr/share/nginx/html/client;
	}
	
	location ~ \.php$ {
		try_files $uri =404;
		include fastcgi_params;
		fastcgi_index   index.php;
		fastcgi_param	SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PHP_VALUE "upload_max_filesize=9G \n post_max_size=9G \n max_execution_time=200 \n max_input_time=200 \n memory_limit=256M";
	}

	location ~* \.(css|js|less|html|ttf|woff|jpg|jpeg|gif|png|bmp|ico|pdf|doc|docx|xls|xlx|txt|ppt|pptx|mp4|webm|mkv|wmv|avi|mp3) {
		root /www/wwwroot/kanban.fanyangmeng.com/client;
		if (-f $request_filename) {
			break;
		}
		rewrite ^/img/([a-zA-Z_]*)/([a-zA-Z_]*)/([a-zA-Z0-9_\.]*)$ /server/php/image.php?size=$1&model=$2&filename=$3 last;
		add_header        Cache-Control public;
		add_header        Cache-Control must-revalidate;
		expires           7d;
	}

    
    
    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #HTTP_TO_HTTPS_START
    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }
    #HTTP_TO_HTTPS_END
    ssl_certificate    /www/server/panel/vhost/cert/kanban.fanyangmeng.com/fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/kanban.fanyangmeng.com/privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    error_page 497  https://$host$request_uri;

    #SSL-END
    
    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    #ERROR-PAGE-END
    
    #PHP-INFO-START  PHP引用配置，可以注释或修改
    include enable-php-73.conf;
    #PHP-INFO-END
    
    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/kanban.fanyangmeng.com.conf;
    #REWRITE-END
    
    
    
    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }
    
   
    access_log  /www/wwwlogs/kanban.fanyangmeng.com.log;
    error_log  /www/wwwlogs/kanban.fanyangmeng.com.error.log;
}
```

I just changed it like this . And now the homepage becomes 404 now.
Like I said I did not add this ` fastcgi_pass	unix:/run/php/php7.2-fpm.sock;` cause I really cannot find out where is this file. But I install php-7.3 correctly.

**Comment by sridhar391** [comment]
@FanyangMengDev  Can you please execute the command `cd /run/php` and execute the command `ls -l` and please copy the response in the command and paste here

**Comment by FanyangMengDev** [comment]
I just change nginx config like this :
```nginx
server
{
    listen 80;
	listen 443 ssl http2;
    server_name kanban.fanyangmeng.com;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/kanban.fanyangmeng.com;
    
   
    gzip on;
	gzip_disable "msie6";

	gzip_comp_level 6;
	# gzip_comp_level 9;
	gzip_min_length  1100;
	gzip_buffers 16 8k;
	gzip_proxied any;
	# gzip_http_version 1.1;
	gzip_types       text/plain application/xml text/css text/js text/xml application/x-javascript text/javascript application/json application/xml+rss;

	client_max_body_size 300M;
    

	rewrite ^/oauth/authorize$ /server/php/authorize.php last;
	rewrite ^/oauth_callback/([a-zA-Z0-9_\.]*)/([a-zA-Z0-9_\.]*)$ /server/php/oauth_callback.php?plugin=$1&code=$2 last;
	rewrite ^/download/([0-9]*)/([a-zA-Z0-9_\.]*)$ /server/php/download.php?id=$1&hash=$2 last;
	rewrite ^/ical/([0-9]*)/([0-9]*)/([a-z0-9]*).ics$ /server/php/ical.php?board_id=$1&user_id=$2&hash=$3 last;
	rewrite ^/api/(.*)$ /server/php/R/r.php?_url=$1&$args last;
	rewrite ^/api_explorer/api-docs/$ /client/api_explorer/api-docs/index.php last;
	
	 location / {
		root /www/wwwroot/kanban.fanyangmeng.com/client;
	}
	


location ~ \.php$ {
		try_files $uri =404;
		include fastcgi_params;
		fastcgi_pass	unix:/tmp/php-cgi-73.sock;
		fastcgi_index   index.php;
		fastcgi_param	SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PHP_VALUE "upload_max_filesize=9G \n post_max_size=9G \n max_execution_time=200 \n max_input_time=200 \n memory_limit=256M";
	}

	location ~* \.(css|js|less|html|ttf|woff|jpg|jpeg|gif|png|bmp|ico|pdf|doc|docx|xls|xlx|txt|ppt|pptx|mp4|webm|mkv|wmv|avi|mp3) {
		root /www/wwwroot/kanban.fanyangmeng.com/client;
		if (-f $request_filename) {
			break;
		}
		rewrite ^/img/([a-zA-Z_]*)/([a-zA-Z_]*)/([a-zA-Z0-9_\.]*)$ /server/php/image.php?size=$1&model=$2&filename=$3 last;
		add_header        Cache-Control public;
		add_header        Cache-Control must-revalidate;
		expires           7d;
	}
    
    
    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #HTTP_TO_HTTPS_START
    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }
    #HTTP_TO_HTTPS_END
    ssl_certificate    /www/server/panel/vhost/cert/kanban.fanyangmeng.com/fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/kanban.fanyangmeng.com/privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    error_page 497  https://$host$request_uri;

    #SSL-END
    
    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    #ERROR-PAGE-END
    
    #PHP-INFO-START  PHP引用配置，可以注释或修改
    include enable-php-73.conf;
    #PHP-INFO-END
    
    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/kanban.fanyangmeng.com.conf;
    #REWRITE-END
    
    
    
    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }
    
   
    access_log  /www/wwwlogs/kanban.fanyangmeng.com.log;
    error_log  /www/wwwlogs/kanban.fanyangmeng.com.error.log;
}
```

And it keeps the same problem.

And I installed php via a panel called BaoTa Panel, you can found them in bt.cn.

And it installed php into /www/server/php/73 so I did not have /run/php dir

**Comment by FanyangMengDev** [comment]
I do not know why but when I change it to this `fastcgi_pass	unix:/tmp/php-cgi-73.sock;`
the error changed.
When I input php-fpm -v it display 7.3.15 but I cannot find where is php-fpm7.3.sock

**Comment by FanyangMengDev** [comment]
Just tried your script and it still the same problem.....

**Comment by FanyangMengDev** [comment]
Finally I just fixed it by myself.........
Closed.

**Comment by rrjanbiah** [comment]
@FanyangMengDev Awesome! What was the issue?

**Comment by FanyangMengDev** [comment]
As I said, I change this line : `fastcgi_pass	unix:/tmp/php-cgi-73.sock;`

And finally all worked.

But now it comes a new problem. Why I used script install the RestyaBoard but it cannot display Apps? Although I have already pasted all the apps to my website root/client/apps/ and chmod them to 777. would you please help me with this?

**Comment by FanyangMengDev** [comment]
Oh, I just found that I have to activate them. Now works. Thanks.

**Comment by FanyangMengDev** [comment]
But now I am keeping receiving this email:

> Please check the permission for the shell folder of main.sh in your server https://kanban.fanyangmeng.com

I have already set the sh file to 777, why I keep receiving this alert now?

Could you please do some help?
Thanks!

**Comment by sridhar391** [comment]
@FanyangMengDev You have apply the executable permission to the shell file by executing the command `chmod +x /www/wwwroot/kanban.fanyangmeng.com/server/php/shell/main.sh`

**Comment by FanyangMengDev** [comment]
That's not correct cause when I chmod +x main.sh, I still can receive the alert email. That really confused me. Maybe 655 is correct?

**Comment by sridhar391** [comment]
@FanyangMengDev Can you please confirm that the Restyaboard tmp folder path `/www/wwwroot/kanban.fanyangmeng.com/tmp` and Restyaboard cache folder path `/www/wwwroot/kanban.fanyangmeng.com/tmp/cache` and Restyaboard shell folder path `/www/wwwroot/kanban.fanyangmeng.com/server/php/shell` have readable permission.

Can you please tell us which cronjobs are running on the Restyaboard server by executing the command `crontab -l` and copy the response and paste it here.

**Comment by FanyangMengDev** [comment]
I just set all the path you said as 777.

And I set a cronjob that is 
```
/www/wwwroot/kanban.fanyangmeng.com/server/php/shell/main.sh
```
And I set it runs every three minutes

**Comment by rrjanbiah** [comment]
@FanyangMengDev FWIW, do you get any error when executing manually?
`./main.sh`

**Comment by FanyangMengDev** [comment]
I will have a try right now

**Comment by FanyangMengDev** [comment]
![图片](https://user-images.githubusercontent.com/53750381/76217994-60d89800-624e-11ea-9255-7545d6ad04d7.png)
@rrjanbiah

**Comment by FanyangMengDev** [comment]
![图片](https://user-images.githubusercontent.com/53750381/76218151-abf2ab00-624e-11ea-88d5-6e99cf5a3218.png)
I just found this.

The first and second one are added by your script I think?

And the third one added by me manually. I think maybe I should delete the first and second one .

I will have a try now.

**Comment by FanyangMengDev** [comment]
Done. Delete them works.
