### ISSUE TITLE
[Feature Request] flickr alternatives like unsplash

### ISSUE THREAD

**Issue by fnetX** [RestyaPlatform/board#4009]
Hey there, 

when using Restyaboards, I am often looking for a nice background for a new board without much caring about which exactly. 
Therefore, I am looking for something like the topic on unsplash.com and choose an awesome image as board background. 

Since RestyaBoard already offers flickr support, I recommend adding more image source alternatives (without the need for an API key which I did not setup), I propose unsplash.com but there are probably others e.g. pixabay.com ... 

That'd be a nice feature for the next Restyaboard release!

Thank you very much
Otto

**Comment by sridhar391** [comment]
@fnetX  Thanks for your kind words. Internally we'll discuss and implement this feature
