### ISSUE TITLE
Deleted attachments remain on the server

### ISSUE THREAD

**Issue by FuXXz** [RestyaPlatform/board#4019]
Hello,

i have a fresh restyaboard installation on Debian 10-
i just noticed that deleted attachments remain on the server in the media folder.
I think after some time a lot of trash could accumulate.
Is this a feature or a bug?
Greetings

**Comment by rrjanbiah** [comment]
*Internal note*

In the code, I can find `unlink`, so not sure if it is due to any permission issues.

Also, noticed other issues:

1. When this issue is reproduced, thumbnails are displaying
2. While other thumbnails display the old/deleted images, `original` thumbnail, displays a random image. So, not sure if thumbnail creation code has some logical issues.

**Comment by FuXXz** [comment]
I have only one user, admin. So why this should be due to any permission issue.
But without deleting the file from server, you cant use restya.
you cant manage files manually, this would be a waste of time :(

**Comment by rrjanbiah** [comment]
@FuXXz I actually meant Linux file permissions. Permission for PHP to `unlink`

**Comment by FuXXz** [comment]
ah ok!
Can I change or test something to solve it?

**Comment by rrjanbiah** [comment]
@FuXXz Yes, try to give writable permission for the folders `media` and `img` under `client`

**Comment by FuXXz** [comment]
There is no folder media under client. 
Look at the tree, but the folders have writable permission
![2](https://user-images.githubusercontent.com/9010594/78384595-bc423f80-75da-11ea-8281-055b03245cbb.png)
![1](https://user-images.githubusercontent.com/9010594/78384596-bcdad600-75da-11ea-8584-3a148a0f6324.png)

**Comment by rrjanbiah** [comment]
Yes, `img` under `client` and `media` in base

**Comment by FuXXz** [comment]
it seems to be okay

/clients/img
![img_clients](https://user-images.githubusercontent.com/9010594/78404176-228c8980-75fe-11ea-9387-a71d05611024.png)

/media
![1](https://user-images.githubusercontent.com/9010594/78404223-346e2c80-75fe-11ea-99e9-eba6c09328a6.png)

/restyaboard
![restya root](https://user-images.githubusercontent.com/9010594/78404234-3d5efe00-75fe-11ea-95e5-68eb2073b28a.png)

**Comment by FuXXz** [comment]
With Cards the same. If i create a new Card, there is a new folder with the Cardnumber in /restyaboard/media/Card.
If i delete the Card, the folder is not deleted

**Comment by rrjanbiah** [comment]
@FuXXz 

Deleting the card will not remove attachments. It is by design.

But, deleting the attachment should remove files. Looks like it is not the case when file permissions are not set right. So, we'll need to work on that.

**Comment by FuXXz** [comment]
@rrjanbiah Deleting the card will not remove attachments. It is by design.

If I delete a card (not put in the archive), I would also like to delete it.
Just deleting them from the UI and leaving them in the system cannot be by design.
Depending on the number of users, tons of useless data accumulate
Are you sure that this is intended?

**Comment by rrjanbiah** [comment]
@FuXXz Yes, in a team based environments, attachments are not just associated with cards. They're also accessed through 'Show Attachments' menu option.

**Comment by FuXXz** [comment]
Sure i understand team based enviroment. But if you want to delete Content, in this case the image or a card, why should the image stay on server. 
And why should a deleted image be accessed through "show Atttachments" ?
I dont understand the workflow behind. Delete = Delete, Fini, empty, not needed any more, dont show it. 

Maybe i need an example of workflow that shows the advantages to showing deleted content to the user.
