### ISSUE TITLE
Not able to install in Apache Windows with XAMPP

### ISSUE THREAD

**Issue by rkhapre** [RestyaPlatform/board#4021]
Hi

I am getting this error after following all documentation.Not able to install the product at all.
Not able to launch it in browser
Please suggest how should i debug

![image](https://user-images.githubusercontent.com/13833102/78506922-b1360d80-779a-11ea-9b1d-d25ae44f4467.png)

**Comment by sridhar391** [comment]
@rkhapre Can you please tell us if you have followed all the installation instruction in the link https://restya.com/board/docs/windows

**Comment by rkhapre** [comment]
Yes, i have followed all the 8 steps from here https://restya.com/board/docs/windows/#3

The #9 Step has not gone through with me. I am not sure how to run that. Is that the problem because of it. Can you tell me how to execute the Step#9 in Windows Server

Including add the below extension in php.ini
extension=php_pdo_pgsql.dll
extension=php_pgsql.dll

**Comment by rkhapre** [comment]
@sridhar391  any comments on my above steps. I am really interested to use this product.

**Comment by sridhar391** [comment]
@rkhapre Please check if you have downloaded the `.htaccess` file as all type file format and not as the text type file format

**Comment by rkhapre** [comment]
yes that was the problem, .htaccess file made it as all type format
