### ISSUE TITLE
Installed fine, but can't access application

### ISSUE THREAD

**Issue by obizbu** [RestyaPlatform/board#4038]
I Installed Restyaboard using the shell script on Ubuntu 16.04 LTS and it ran fine, but when I go to access it from the browser, it doesn't load. I checked the developer tools and looks like the server keeps trying to request oauth.json, but the server keeps returning a 500 error

**Comment by rrjanbiah** [comment]
@obizbu 

Most likely it is a database issue. Please double check the database credentials. If you still face issue, please enable debug mode (https://github.com/RestyaPlatform/board/blob/dev/server/php/config.inc.php#L15 ) and check for errors the API call.

**Comment by tommyvange** [comment]
I have the exact same issue, did you solve it @obizbu?

> @obizbu
> 
> Most likely it is a database issue. Please double check the database credentials. If you still face issue, please enable debug mode (https://github.com/RestyaPlatform/board/blob/dev/server/php/config.inc.php#L15 ) and check for errors the API call.

How do I check if it has the right DB credentials? I just used to installer script.

**Comment by rrjanbiah** [comment]
@tommyvange Can you please enable debug mode and share the output you see in the network panel for the API call?

**Comment by tommyvange** [comment]
I managed to solve my issue, I didn't have the `pgsql` PHP package installed.

**For anyone wondering how to do it:**
- Debian/Ubuntu : `sudo apt-get install php-pgsql`
- Windows Add this line (`extension=php_pgsql.dll`) to the active php.ini

**Comment by rrjanbiah** [comment]
Closing this. If you face any more issues, please feel free to reopen.
