### ISSUE TITLE
Disabling card cover image doesn't work for PDF preview

### ISSUE THREAD

**Issue by erl4nc** [RestyaPlatform/board#4041]
Users report that card attachment preview clutters lists in a board. Is there an option to turn these off?
![image](https://user-images.githubusercontent.com/33263752/80824311-0810e600-8b93-11ea-8e0c-3ac9c1bbe794.png)

**Comment by rrjanbiah** [comment]
@erl4nc 

Please turn off card cover feature under board settings in `Additional Settings->Card Cover Images Enabled` (Refer the screenshot below)

![rb-card-cover](https://user-images.githubusercontent.com/4907427/80829511-ebad9180-8c04-11ea-9d52-e54547eba195.png)

**Comment by erl4nc** [comment]
Thank you. I did not realize that option is there.  However, the option turned off the image attachment preview but not the pdf preview:
![image](https://user-images.githubusercontent.com/33263752/80842981-e37b3500-8bb7-11ea-8b9d-884b362db82e.png)

Could the pdf preview also be disabled?
