### ISSUE TITLE
Restyaboard frozen after backup and restore Database

### ISSUE THREAD

**Issue by IssueFindings** [RestyaPlatform/board#4049]
Hello,
I made a fresh install of the last version of Restyabord on Raspberry Pi4 Buster. Install works fine and I manually created users.

After that, I followed the different steps backup/restore (https://restya.com/board/docs/backup-and-restore/#0). During the restore process, I got errors regarding duplicated keys that broken unique constraint « cities_pkey », « countries_pkey », « email_templates_id », « ips_pkey », « labels_id », « login_types_id », « oauth_access_tokens_access_token », « oauth_clients_client_id », « oauth_refresh_tokens_refresh_token », « organization_user_roles_id », « roles_id », « setting_categories_id », « settings_id », « states_pkey », « user_logins_id » and « users_id », etc.

Now, when I try to connect to my restyaboard website, I can't. I receive mail to reset password but when I use it, I'm locked in the welcome page without any error message...

I become crazy and tired. What can I do ?

Have a nice day.

**Comment by sridhar391** [comment]
@IssueFindings Can you please tell us if you are trying to restore the database on the existing database of Restyaboard?

**Comment by IssueFindings** [comment]
@sridhar391 
Hello,
I just made a complete fresh install, created user's profiles and imported the database from old Restyaboard to fresh install restyaboard. I made something wrong ? If yes, how I can do ?
Have a nice day.

**Comment by IssueFindings** [comment]
Hello,
I understood my mistake. I need to use the right database password. So I fixed it and I imported the database.

I also do the same with documents and images uploaded. I checked access rights of folders and files. It's the same than source but the fresh Restyaboard installation can't display it. It can only downloaded locally. Why ? How I can fix that ?

Have a nice day.

**Comment by IssueFindings** [comment]
The initial issue is solved. Regarding the issue with users' attachments see the new dedicated ticket.

https://github.com/RestyaPlatform/board/issues/4071
