### ISSUE TITLE
Uninstall Restyaboard

### ISSUE THREAD

**Issue by IssueFindings** [RestyaPlatform/board#4067]
Hello,
What is the process to uninstall properly the currently last version of Restyaboard. Indeed, I would like to perform a new fresh install because of bugs.

I run Restyaboard on Rpi 4 Buster.

Have a nice day.

**Comment by rrjanbiah** [comment]
@IssueFindings Please use the uninstall script https://github.com/RestyaPlatform/board/blob/dev/restyaboard_uninstall.sh

**Comment by IssueFindings** [comment]
@rrjanbiah
Hello,
Many thanks for the link. That works perfectly !
Have a nice day.

**Comment by rrjanbiah** [comment]
@IssueFindings Some users are asking if Restyaboard works in Rpi. What are the problems are you facing in Rpi?
