### ISSUE TITLE
Increase webpage loading time

### ISSUE THREAD

**Issue by IssueFindings** [RestyaPlatform/board#4081]
Hello,
How to increase login webpage (and others webpages) loading time ?
I test it with https://developers.google.com/speed/pagespeed/insights/ and a nginx service.
Results are especially :
- activate text compression ;
- delete unused JavaScript resources.

I activate gzip with this code :
>gzip on;
gzip_vary on;
gzip_proxied any;
gzip_comp_level 6;
gzip_buffers 16 8k;
gzip_http_version 1.1;
gzip_types text/plain text/css text/js application/json application/javascript application/x-javascript text/xml application/xml    application/xml+rss text/javascript image/svg+xml;

What I can add ?

Have a nice day.

**Comment by rrjanbiah** [comment]
@IssueFindings 

The default setup is already optimized for speed. For nginx, you can see gzip is already enabled https://github.com/RestyaPlatform/board/blob/dev/restyaboard.conf#L8

PageSpeed metrics may be slightly misleading for single page application like Restyaboard. Restyaboard app initial loading will be slightly slow as it loads all assets, but after that it caches.

**Comment by IssueFindings** [comment]
Hello,

Many thanks for your answer. It's a great application. Continue to improve it (speed too).

Have a nice day.
