### ISSUE TITLE
Filtered views arent updated

### ISSUE THREAD

**Issue by morbificagent** [RestyaPlatform/board#4082]
Hi together,

im not sure if its a bug or if it isnt possible at the moment:

If User 1 has enabled a filter to his user to only see the cards assigned to him he sees only the cards assigned to him... works...

Now User 2 assigns him a new card... so i would expect it pops up in User 1 filtered view... but it doesnt.... if User 1 disables the filter he can see the new card. He than can reenable the filter but this cant be a solution of course.

Sometimes i saw that in the same situation the User 1 filter gets disabled after User 2 added a card...

Very strange

**Comment by sridhar391** [comment]
Need to test the below cases also

1. Add user
2. Remove user
3. Add label
4. Remove label
5. Add card due date
6. Remove card due date
7. Matches any label and any member
8. Matches all labels and all members
