### ISSUE TITLE
Image Upload: "File extension not supported. It supports only jpg, png, bmp and gif."

### ISSUE THREAD

**Issue by fnetX** [RestyaPlatform/board#4095]
## Expected Behavior
Uploading a something.JPG file as board background works without issues.

## Current Behavior
Uploading such an image file does not result in any visual error displayed to the user in the interface. After the upload finishes, nothing is changed after all.

The HTTP POST call is answered with a `200 OK` response which seems like an issue of its own. I think that errors should be indicated with an appropriate response code. 

The server responds with an error wrapped in JSON:
```
{"error":"File extension not supported. It supports only jpg, png, bmp and gif."}
```

## Possible Solution
- allow for different spelling of file extensions (e. g. .jpeg, .JPG, .Jpg, .PNG, etc)
- display error messages to the user if it's not a valid file extension
- consider not responding every API call with status 200 if there was an error.

## Steps to Reproduce (for bugs)
Upload a .JPG file as board background.

## Your Environment
* Version used: v 0.6.8 (2019-12-16)
* Environment name and version: Apache on Debian Stretch LXC behind lighttpd reverse proxy

**Comment by sridhar391** [comment]
@fnetX We have fixed the issue, please apply the changes in the `/usr/share/nginx/html/restyaboard/server/php/R/r.php` file from the commit https://github.com/RestyaPlatform/board/commit/55e1422f0bda9a5aaf6860594f26f060bc33a1ab
