### ISSUE TITLE
Newly created card jumps to another column

### ISSUE THREAD

**Issue by morbificagent** [RestyaPlatform/board#4101]
Hi again,

actually i sometimes have the problem that my newly created card jumps away after i click on the "Add"-Button

Like you can see on the attached screenshot i created a card on the left side under "Prio 1", than i click on "Add" an BÄM its gone... searching for it shows that it is somewhere in the right column "Abgeschlossen"...!?

90% of the time creating cards works good but the shown scenario happens sometimes.
![Unbenannt](https://user-images.githubusercontent.com/50199132/85272786-eb9b7680-b47c-11ea-8411-552e2ff859ae.png)

**Comment by morbificagent** [comment]
Possible this is part of #4103 

So im not sure if #4103 was happening before this

**Comment by morbificagent** [comment]
Tested on your Demo-System: Same Problem here (see attached screenrecording):

[CardInWrongColumn.zip](https://github.com/RestyaPlatform/board/files/4869635/CardInWrongColumn.zip)

**Comment by sridhar391** [comment]
@morbificagent Thanks for informing us about the issue, we will fix this issue along with other issues according to the priority

**Comment by sridhar391** [comment]
@sridhar391 We have fixed the above issue in the `dev` branch and the fixes will be available in the upcoming release v0.6.9 (Stereopony)
