### ISSUE TITLE
Endless Scrolling Bug

### ISSUE THREAD

**Issue by morbificagent** [RestyaPlatform/board#4103]
Hi again,

New game new bug ;-)
This time i want to report a bug that causes a endless scrolling in columns.

It happens several times a day here eventually because the board is bigger than the display. But im not sure about that.
If i try to move a card to a column which is outside of the monitor it auto-scrolls when i move my mouse to the right end of my screen.
Then i can put the card in the column and it snaps in and seams to be ok.
but my collegues does see the card at its old place...

At this point i can see that one column is "endless scrolling" to the bottom of it.

First i thought my mouse is broken and sends wrong information but now this happens several collegues too.

Refreshing the page solves the "endless scrolling" but as i can see now the card wasnt moved to the new column. 
So i can try this again.

Sometimes i dont notice the problem first and after an hour i see "oh no there is the endless scrolling bug".
So i have to reload the page and remember which cards i wanted to move to which place.

Annoying

**Comment by morbificagent** [comment]
OK, it isnt a problem of the board-size. I have rearranged all so they fit into my screensize so i dont have to scroll horizontally.
But it happens again.
Here a screenrecord about that. And remember, i dont press any keys or really scrolling at the mouse for sure.
And this isnt only at my client the case as we are trying to use restya in our company and others have this too.


[scrolling.zip](https://github.com/RestyaPlatform/board/files/4868016/scrolling.zip)

**Comment by sridhar391** [comment]
@morbificagent Thanks for informing us about the issue, we have tried it in our local server but not able to reproduce the issue, can you please tell us if you can able to reproduce the issue in our demo server and please refer the link https://restya.com/board/demo for our demo server credentials

**Comment by morbificagent** [comment]
@sridhar391 I have tried it and the problem is there too but with the difference it doesnt scrolls endless in my test.

If i create a column with 30-40 cards in it and want to move an other card in there it begins to scroll to the bottom(see attached video).
But after that i can manually scroll back to the top. On my system it wasnt possible and i had to reload.

Eventually because i have Pictures or checklists or or or in it which i dont had on your demosystem.

Anyway, i think it shouldnt begin to scroll at all because ther is no reason for this.

Screenrecord on your Demo-System:

[ScrollingDemosystem.zip](https://github.com/RestyaPlatform/board/files/4869626/ScrollingDemosystem.zip)

**Comment by sridhar391** [comment]
@morbificagent Thanks for informing us about the issue, we will fix this issue along with other issues according to the priority
