### ISSUE TITLE
Install script for Linux Error

### ISSUE THREAD

**Issue by tatatafuku** [RestyaPlatform/board#4106]
## Expected Behavior
In script, wget "geolite" Error

## Current Behavior
503 Service Unavailable, and aninstall GeoIp.dat.gz

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/67665623/86189478-aa8e1b00-bb7c-11ea-8b5d-cbcd89e0e5a7.png)

## Possible Solution
version change geolite to geolite2,and it reflect install script

## Steps to Reproduce (for bugs)

1.do install script

## Your Environment

Linux 18.04 LTS

**Comment by sridhar391** [comment]
@tatatafuku We have fixed this issue in the coomit https://github.com/RestyaPlatform/board/commit/0d2e941b84253c70a0379b79e9e06ff9442f82d7 and you can use the dev branch `restyaboard.sh` file from the link https://raw.githubusercontent.com/RestyaPlatform/board/dev/restyaboard.sh
