### ISSUE TITLE
Setting "subscribe a member when added to card" broken

### ISSUE THREAD

**Issue by morbificagent** [RestyaPlatform/board#4108]
When i select "subscribe a member when added to card" in the additional settings the card cover images get disabled...

![image](https://user-images.githubusercontent.com/50199132/86357102-a1c94200-bc6d-11ea-8bd5-f5434d00cfc4.png)

So the wrong action is executed here.

**Comment by sridhar391** [comment]
@morbificagent Thanks for informing us about the issue, we will fix this issue along with other issues according to the priority.

**Comment by morbificagent** [comment]
@sridhar391 Great, thank you. I can imagine that this project consumes many time and i am happy that you rockin this ;-)
