### ISSUE TITLE
Setting "Add Cards via Email" doesnt save settings

### ISSUE THREAD

**Issue by morbificagent** [RestyaPlatform/board#4109]
If i change the Setting "Position" to "Bottom" it wont be saved.
If i reopen the settings its back at "Top"

![image](https://user-images.githubusercontent.com/50199132/86357524-392e9500-bc6e-11ea-9522-1fc4cab1a310.png)

**Comment by sridhar391** [comment]
@morbificagent Thanks for informing us about the issue, we will fix this issue along with other issues according to the priority
