### ISSUE TITLE
Restyaboard not starting after installation on Centos 7 linux server 

### ISSUE THREAD

**Issue by sagarpdesai** [RestyaPlatform/board#4114]
[restyaboard_install.log](https://github.com/RestyaPlatform/board/files/4914643/restyaboard_install.log)

Restyaboard installed on AWS Lightsail server running Centos 7. Installation is done using Linux Script provided on Restyaboard site (https://restya.com/board/install#Installscript). After installation, when we try to access the site we are getting a blank white page. There are infinite calls being made to the following URL : mydomain.com/api/v1/oauth.json?_=1594668640759

## Expected Behavior

mydomain.com/#/users/login should load after installation

## Current Behavior

Blank white page appears with multiple calls being made to oauth.json in the background.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sridhar391** [comment]
@sagarpdesai Can you please try to install the Restyaboard with the `latest` install shell script by downloading the shell script file using the command `wget https://github.com/RestyaPlatform/board/raw/dev/restyaboard.sh --no-check-certificate` and apply the executable permission to the file by executing the command `chmod +x restyaboard.sh` and execute the installation script file by the command `sudo ./restyaboard.sh`

**Comment by sagarpdesai** [comment]
Thanks @sridhar391 for the reply.

Tried the above steps. I am still getting a blank white page. This time the only difference is the call to https://mydomain.com/api/v1/oauth.json?_=1594715711539 is giving error 502.

[restyaboard_install.log](https://github.com/RestyaPlatform/board/files/4917617/restyaboard_install.log)

**Comment by sridhar391** [comment]
@sagarpdesai We have checked the installation log file and can you please tell us that if you have registered the domain name "task.fmgizmo.com" and if you have not registered the domain name please remove the below lines in the 
" /etc/nginx/conf.d/restyaboard.conf" file

listen 443 ssl;
ssl_certificate /etc/letsencrypt/live/restya.com/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/restya.com/privkey.pem;
ssl_session_cache shared:SSL:1m;
ssl_session_timeout 15m;
# Set system wide SSL settings
ssl_prefer_server_ciphers on;
ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
#Forward Secrecy
ssl_ciphers "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384
EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4
EECDH EDH+aRSA RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS";
if ($scheme = 'http') {
rewrite ^/(.*)$ https://restya.com/$1 permanent;
}

After following the above instructions, please restart the Nginx server and PHP by executing below commands and please tell us if the Restyaboard page is loading or not?

service apache2 stop
systemctl restart nginx
systemctl restart php-fpm

**Comment by revresx** [comment]
@sagarpdesai - I'm having the same issue. Showing blank page with infinite calls. 

I tried the script "dev" .sh script. After fixing certbot it's now showing just a blank page. [restya.pslschweiz.ch](restya.pslschweiz.ch)

Changed the nginx ssl settings to the one you've posted. Didn't change anything for me.

**Comment by sridhar391** [comment]
@revresx Can you please attach the Nginx error log file named `error.log` file from `/var/log/nginx/` folder path to understand the issue

**Comment by sagarpdesai** [comment]
Got hold of the issue. The following line in restyaboard.conf file had to be changed:

`                fastcgi_pass    unix:/run/php/php7.2-fpm.sock;`
changed to
`                fastcgi_pass   127.0.0.1:9000;`

The default setting for php-fpm is to run on TCP port 9000 rather than running on a socket.

**Comment by sridhar391** [comment]
@sagarpdesai Thanks for informing us the fix for your issue

**Comment by revresx** [comment]
@sagarpdesai Thank you! Fixed it for me as well.
@sridhar391 Issue solved.
