### ISSUE TITLE
Docker build problems

### ISSUE THREAD

**Issue by daryl-o** [RestyaPlatform/board#4119]
I cloned the current master and ran into a couple problems while trying to build for docker. I am currently running CentOS 7.8 in AWS. The compile failed in two locations.

1.  In Dockerfile, I had to comment the following line because the file didn't exist in the image:
           `RUN chmod 600 /etc/postfix/sasl_passwords`

2. sql/restyaboard_with_empty_data.sql has features from postgres 11 and 12 but docker-compose.yml had:
        `image: postgres:9-alpine`
    which caused numerous syntax errors. I changed it to:
        `image: postgres:12-alpine`
    and everything compiled OK

**Comment by sridhar391** [comment]
@daryl-o We have fixed this issue in the `dev` branch and  the fix will be available in the upcoming release v0.6.9 (Stereopony) and thanks for your fixes

**Comment by manakill** [comment]
I've also have build issues today on a Raspberry Pi 3b+, Raspian Buster. The container is stuck in some sort of restart loop.
Definitely looking forward to getting this up and running. Thanks to all contributors!

**Comment by sridhar391** [comment]
@manakill We have fixed the issue in the commit https://github.com/RestyaPlatform/board/commit/636fac5adc47b56183d341c7904c697aa7590060 https://github.com/RestyaPlatform/board/commit/c82876aa355b8a5c092e6c58183c56382605c203 and merged the changes in the `dev` branch with pull requests https://github.com/RestyaPlatform/board/pull/4105 https://github.com/RestyaPlatform/board/issues/4116
