### ISSUE TITLE
NGINX 403 | Permission Problems

### ISSUE THREAD

**Issue by Cartmanan** [RestyaPlatform/board#4121]
Hi, I don't have that much experience with servers yet, so it would be great if you could explain it as simple as possible.

![3333](https://user-images.githubusercontent.com/21957515/87851661-29b07c80-c8fb-11ea-941b-23015ef404ec.PNG)

If you look in the diagnosis.php, I always get told that the directory tmp does not have the appropriate rights, but no matter what rights I assign to the directory, the error does not disappear and I always get the same error (403).

**Comment by sridhar391** [comment]
@Cartmanan Can you please send us the `restyaboard_install.log` file if you have installed Restyaboard using the Restyaboard installation script file `restyaboard.sh` or if you have manually installed the Restyaboard, can you please send us the steps you have followed to install Restyaboard

**Comment by sridhar391** [comment]
@Cartmanan Can you please send us the `restyaboard_install.log` file if you have installed Restyaboard using the Restyaboard installation script file `restyaboard.sh` or if you have manually installed the Restyaboard, can you please send us the steps you have followed to install Restyaboard

**Comment by manakill** [comment]
I have a similar issue but different directories:

/usr/share/nginx/html/restyaboard/media | Not Writable
/usr/share/nginx/html/restyaboard/client/img | Not Writable

however they are indeed writable.. I did notice they are owned by 'root' and not 'www-data'  so I don't know if that is related.

[restyaboard_install.log](https://github.com/RestyaPlatform/board/files/4973332/restyaboard_install.log)

**Comment by manakill** [comment]
I have changed the owners of my 2 directories that were not working, and that fixed it! This has also solved my other issue (https://github.com/RestyaPlatform/board/issues/4124) 

![fix-image-permissions-1](https://user-images.githubusercontent.com/9597295/88465521-ae6a4000-ce91-11ea-8dbf-18687f1de840.jpg)

![fix-image-permissions-2](https://user-images.githubusercontent.com/9597295/88465523-b1653080-ce91-11ea-95e9-5a65699f40bf.jpg)

![fix-image-permissions-3](https://user-images.githubusercontent.com/9597295/88465525-b3c78a80-ce91-11ea-80c4-977fa97b6e83.jpg)

**Comment by sridhar391** [comment]
@manakill Thanks for your fix, @Cartmanan can you please try the above fix and please tell us if the issue is fixed

**Comment by sridhar391** [comment]
@manakill Thanks for your fix, @Cartmanan can you please try the above fix and please tell us if the issue is fixed

**Comment by sridhar391** [comment]
> I have changed the owners of my 2 directories that were not working, and that fixed it! This has also solved my other issue (#4124)
> 
> ![fix-image-permissions-1](https://user-images.githubusercontent.com/9597295/88465521-ae6a4000-ce91-11ea-8dbf-18687f1de840.jpg)
> 
> ![fix-image-permissions-2](https://user-images.githubusercontent.com/9597295/88465523-b1653080-ce91-11ea-95e9-5a65699f40bf.jpg)
> 
> ![fix-image-permissions-3](https://user-images.githubusercontent.com/9597295/88465525-b3c78a80-ce91-11ea-80c4-977fa97b6e83.jpg)
> 
> Maybe the ownership wasn't set properly during install?
> Seems like something that should be built in to do automatically. Most users can't troubleshoot like us ;)

@manakill Thanks for your fix, @Cartmanan can you please try the above fix and please tell us if the issue is fixed

**Comment by sridhar391** [comment]
> I have changed the owners of my 2 directories that were not working, and that fixed it! This has also solved my other issue (#4124)
> 
> ![fix-image-permissions-1](https://user-images.githubusercontent.com/9597295/88465521-ae6a4000-ce91-11ea-8dbf-18687f1de840.jpg)
> 
> ![fix-image-permissions-2](https://user-images.githubusercontent.com/9597295/88465523-b1653080-ce91-11ea-95e9-5a65699f40bf.jpg)
> 
> ![fix-image-permissions-3](https://user-images.githubusercontent.com/9597295/88465525-b3c78a80-ce91-11ea-80c4-977fa97b6e83.jpg)
> 
> Maybe the ownership wasn't set properly during install?
> Seems like something that should be built in to do automatically. Most users can't troubleshoot like us ;)

@manakill Thanks for your fix, @Cartmanan can you please try the above fix and please tell us if the issue is fixed

**Comment by sridhar391** [comment]
@manakill We are closing the issue due to inactivity, if the issue occured again, please feel free to reopen the issue
