### ISSUE TITLE
Installed Plugins not showing up

### ISSUE THREAD

**Issue by Goepfie** [RestyaPlatform/board#4122]
## Description
Admin->Plugins: List is empty, even though all basic apps are downloaded into the correct folder. Triple checked, for testing the path was even reachable by url, json readable. Restarted Nginx serveral times. Restarted php7-fpm. Logged out/Logged in. Refreshed with cleared Browser cache.

## Expected Behavior
The plugins to show up and be ready to be activated.

## Current Behavior
The plugin overview page is completely empty. No error, No log, nothing. Did check the webconsole there where a few cache.js errors.

## Screenshots (if appropriate):
Diagnosis.php is completely fine, I can attach if you want. IMAP is not configured though.
Error log is empty.

## Possible Solution
I have no idea.

## Steps to Reproduce (for bugs)
Selfhosted board with sensitive information. I might be able to setup a new one with remote access.

## Context
Just wanted to the basic plugins, most notably the "hide additional information" one.

## Your Environment
* Version used: 0.6.8
* Environment name and version (e.g. OS, PHP, PostgreSQL):
- PHP7.4 (Latest stable)
- PostgreSQL (Latest Stable)
- Remote Proxy throug NGINX (latest stable)
* Operating System and version (desktop or mobile): 
- Raspberry Pi 4B with 8G
- Alpine Linux 3.12 (Latest stable) -> Running from ram, (/media) Card data is on a local NFS Share
- Accessed through Firefox Desktop (latest stable)
* Link to your project: --

**Comment by sridhar391** [comment]
@Goepfie For some server the readable permission is 755 or 777, please choose the correct permission and apply to the files, E.g., `chmod -R 755 /usr/share/nginx/html/restyaboard/client/apps/`

**Comment by Goepfie** [comment]
@sridhar391 Thank your for the reply. Like I said permissions are set up correctly. In my test-case it is 777. I am going to gather some log files and screenshots later today.

Currently the folder is symlinked to a persistent storage, but I had the issue with file folder as well.

**Comment by sridhar391** [comment]
@Goepfie Okay, please attach your log files and screenshots.

**Comment by Goepfie** [comment]
Please find attached [logs.zip](https://github.com/RestyaPlatform/board/files/4953903/logs.zip) for this issue as well as issue #4123 

Included:
- access.log -> file & folder permissions
- error.log -> nginx error reports
- php_errors -> php-fpm7 error reports
- process.log -> running processes with users
- apps.png -> screenshot of apps issue
- locale.png -> screenshot of language settings issue
- diagnose.png -> diagnose.php output

The access error log of nginx was empty so I guess there where no access violations.
I am utlizing the "default" nginx non-ssl variant of the reverse proxy setup provided in the repo.

Let me know, if I missed to attach something.

**Comment by sridhar391** [comment]
@Goepfie We have fixed the issue in the commit https://github.com/RestyaPlatform/board/commit/66762732363481b97d7563d61a3f88b61956b4a2 and the fix will be available in the upcoming release v0.6.9 (Stereopony)

For quick fix, please download the attached file and paste it in the `/usr/share/webapps/restyaboard/server/php/R` folder path and rename the file from `r.txt` to `r.php`

[r.txt](https://github.com/RestyaPlatform/board/files/4957911/r.txt)
