### ISSUE TITLE
Can not change language

### ISSUE THREAD

**Issue by Goepfie** [RestyaPlatform/board#4123]
## Description
Admin->Settings: Setting Locale List is empty, even though folder with jsons is accessible. Triple checked, for testing the path was even reachable by url, json readable. Restarted Nginx serveral times. Restarted php7-fpm. Logged out/Logged in. Refreshed with cleared Browser cache. The english translation is loaded and usable though, admin or user account just can't change anything.

## Expected Behavior
The list for languages/locales to be populated. The Timezone list is working properly.

## Current Behavior
The list is empty and has no selection, not even the currently used en locale is showing.

## Screenshots (if appropriate):
Diagnosis.php is completely fine, I can attach if you want. IMAP is not configured though.
Error log is empty.

## Possible Solution
I have no idea.

## Steps to Reproduce (for bugs)
Selfhosted board with sensitive information. I might be able to setup a new one with remote access.

## Context
I want my users to be able to chose the "german" de_DE locale.

## Your Environment
* Version used: 0.6.8
* Environment name and version (e.g. OS, PHP, PostgreSQL):
- PHP7.4 (Latest stable)
- PostgreSQL (Latest Stable)
- Remote Proxy throug NGINX (latest stable)
* Operating System and version (desktop or mobile): 
- Raspberry Pi 4B with 8G
- Alpine Linux 3.12 (Latest stable) -> Running from ram, (/media) Card data is on a local NFS Share
- Accessed through Firefox Desktop (latest stable)
* Link to your project: --

**Comment by sridhar391** [comment]
@Goepfie For some server the readable permission is 755 or 777, please choose the correct permission and apply to the files, E.g., `chmod -R 755 /usr/share/nginx/html/restyaboard/client/locales`

**Comment by sridhar391** [comment]
@Goepfie We have fixed the issue in the commit https://github.com/RestyaPlatform/board/commit/66762732363481b97d7563d61a3f88b61956b4a2 and the fix will be available in the upcoming release v0.6.9 (Stereopony)

For quick fix, please download the attached file and paste it in the `/usr/share/webapps/restyaboard/server/php/R` folder path and rename the file from `r.txt` to `r.php`

[r.txt](https://github.com/RestyaPlatform/board/files/4957913/r.txt)

**Comment by Goepfie** [comment]
Thank you! Worked like a charm.
