### ISSUE TITLE
Fix hardcoded domain in Image SRC URLs and call img directory only

### ISSUE THREAD

**Issue by manakill** [RestyaPlatform/board#4125]
Changed Board Background Image.

Expected behavior:
The image loads properly no matter if connected on local net IP or remote IP

Actual behavior:
When connected locally(192.168...) I can see background images. When connected via subdomain.host.com the background images get broken. Also fixed while connected remotely, and now local connection images are broken. 

**Range of scope:
Seems to be only board background images. Other images load properly no matter if connected on local IP or remote IP**

I was able to delete the domain part from the src URL and fix the background image - however upon reload it will revert(as I would expect) and not permanently fixed.

![no-background-1](https://user-images.githubusercontent.com/9597295/88463922-75779e80-ce84-11ea-95aa-0ca98e5d3eae.jpg)

![no-background-2](https://user-images.githubusercontent.com/9597295/88463925-7c9eac80-ce84-11ea-9dd2-ac24e90c171c.jpg)

Fix needed:
remove hard coded domain/IP from the Board Background IMG SRC URLs

**Comment by manakill** [comment]
I am able to fix in the database, manually, but that is not a real fix..

**Comment by sridhar391** [comment]
@manakill We have fixed the issue in the commit https://github.com/RestyaPlatform/board/commit/8f756442dbf0bb856985448ee1a7ae3b59ea12b4 and merged the code in the pull request https://github.com/RestyaPlatform/board/pull/4036 and the fix will be available in the upcoming release v0.6.9 (Stereopony)
