### ISSUE TITLE
No GitHub Donation Link!? Broken Donate link in Restyaboard also(a store is not a donation)

### ISSUE THREAD

**Issue by manakill** [RestyaPlatform/board#4126]
There is nowhere to Donate to this project!? Umm... not ok.

On TOP of that, I went to the main site to chat to someone about it and the Chat is messed up....

![bad-chat](https://user-images.githubusercontent.com/9597295/88466638-6b619a00-ce9c-11ea-86e3-9437e387db0f.jpg)

Seems like some silly mistakes are getting made. I want to donate money and you've made it impossible, from what I can tell. 
No link to it on Github, no link in the main website Footer, the link on Restyaboard links to a page on restya.com that sells junk I don't want... I just want to donate! lmao wow.

Please fix Donation issues to make it Easy for people to donate.
Please fix the website Chat's connection issues(less important imo)

**Comment by rrjanbiah** [comment]
@manakill Thank you so much for your kind words and suggestion.

Regarding the chat widget, thanks for notifying the issue. We'll escalate it to the LiveChatInc. 

Regarding the donation, our team members have experimented it couple of times, but that didn't work good. Anyway we'll internally discuss about it and work on it.

Thanks again.

**Comment by rrjanbiah** [comment]
@manakill Also, for any private comments, please feel free to email us at info at ourdomain.
