### ISSUE TITLE
Fix Due Date Time of 12:00-13:00 to show PM

### ISSUE THREAD

**Issue by manakill** [RestyaPlatform/board#4132]
## Expected Behavior
12:00 or after, shows PM

## Current Behavior
12:00-13:00 Due Date Time shows AM which is incorrect

## Screenshots (if appropriate):
![Due Date Time Wrong](https://user-images.githubusercontent.com/9597295/88492257-5f96d600-cf77-11ea-8fa7-a74046c1cc84.jpg)

## Steps to Reproduce (for bugs)
Simply set the Due Date time to 12:00

**Comment by sridhar391** [comment]
@manakill Thanks for informing us about the issue, we will fix this issue along with other issues according to the priority

**Comment by manakill** [comment]
Thanks! I'm glad to help out where I am able to. The more I use Restyaboard, the more I absolutely love it. Great work devs!!

**Comment by rrjanbiah** [comment]
@manakill Thanks for your kind words. Much appreciated!
