### ISSUE TITLE
Elastic search card results incorrect after moving list

### ISSUE THREAD

**Issue by erl4nc** [RestyaPlatform/board#4140]
## Expected Behavior
Elastic search returns results corresponding to search term

## Current Behavior
Elastic search returns results corresponding to before a list is moved

## Possible Solution
Update indexes of all cards in a list after moving the list to a different board

## Steps to Reproduce (for bugs)
1. Create 2 boards: "board 1" & "board 2"
2. Create 2 lists: "demo 1" in "board 1", "demo 2" in "board 2"
3. Create 2 cards in "board 1" "demo 1": "demo card 1", "demo card 2"
4. Move the card "demo card 1" to "board 2" "demo 2"
5. Move the list "demo 1" from "board 1" to "board 2"
6. Using elastic search bar, search for "demo". Results are
Lists: "board 2" >> "demo 1" & "board 2" >> "demo 2" (these are correct)
Cards: "demo card 1" in "board 2" "demo 2" (this is correct)
            "demo card 2" in "board 1" "demo 1" (this is incorrect) 

Cards and lists seem to be reindexed after they are moved. However, cards in the moved list are not.

## Context
Cannot locate correct cards using keywords, which renders elastic search useless

## Your Environment
* Version used: 0.6.7 & 0.6.8 with Elastic search 5.6.x

**Comment by sridhar391** [comment]
Thanks for informing us about the issue, will fix the issue along with other priority issue

**Comment by erl4nc** [comment]
Thank you. Appreciate the quick fix.
