### ISSUE TITLE
issue when install restyaboard on xampp

### ISSUE THREAD

**Issue by cuchipkg** [RestyaPlatform/board#4153]
hello all, i'm try install Restyaboard on window with Xampp and when i run localhost i have 1 message error below i dont know how fix it

![image](https://user-images.githubusercontent.com/60688301/91653410-cf463680-eaca-11ea-97c4-401cf4f597d1.png)

**Comment by sridhar391** [comment]
@cuchipkg Can you please set R_DEBUG as true on the config.inc.php file in line 15 on '/usr/share/nginx/html/restyaboard/server/php' path like https://github.com/RestyaPlatform/board/blob/dev/server/php/config.inc.php#L15 and copy the response of the Login API call http://restyaboard_url/api/v1/users/login.json.json on the Network tab of Browser developer tools and paste it here or copy the contents from your server error log and paste it here.

**Comment by sridhar391** [comment]
@cuchipkg Can you please set R_DEBUG as true on the config.inc.php file in line 15 on '/usr/share/nginx/html/restyaboard/server/php' path like https://github.com/RestyaPlatform/board/blob/dev/server/php/config.inc.php#L15 and copy the response of the Login API call http://restyaboard_url/api/v1/users/login.json.json on the Network tab of Browser developer tools and paste it here or copy the contents from your server error log and paste it here.

**Comment by sridhar391** [comment]
@cuchipkg Due to inactivity, we are closing the issue, feel free to reopen the issue if the issue occurred again
