### ISSUE TITLE
Import from monday.com to Restyaboard

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#4159]
## Context
Need to have some provision for them easy migration from monday.com to Restyaboard

**Comment by sridhar391** [comment]
For downloading the attachments, we need to login in the monday.com and there is no default unique identifier for each data, but we can add the ID field in the moday.com to add unique identifier to each data

**Comment by sridhar391** [comment]
While exporting the whole account data from the monday.com, the attachment files are in the `assets` folder and while exporting the separate board, the attachments are not not exported and the Unique ID for each row is automatically added in the export board and export account

**Comment by rrjanbiah** [comment]
*Internal note*

Have to rework so that we import from exported zip (instead from the Excel file)

1. `assets` folder has all assets. These are mapped in the excel
2. `updates` - for activities
3. `teams` - users
4. `boards` - boards ({board_id}_{board_name})

**Comment by sridhar391** [comment]
*Internal note*

On monday.com, in each project task, we can add the subitems to each task, and while exporting the monday.com details, the subitems of the tasks of the project are stored in separate Excel files, and they don't have the parent task id and the project id also.
