### ISSUE TITLE
Card count on start page is always zero

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#4167]
From https://groups.google.com/forum/#!topic/restya/I8EBwn3TCco (Leonardo R.gananca): 

Hi, I have installed restyaboard on a raspberry pi 3, it's working but, on start page, the card count is always zero, even when I have cards on the boards, Is there something that can fix this ?

**Comment by leonardothehuman** [comment]
Hardware: Raspberry pi 3
SD card size: 32 gb
uname -a: Linux raspbian 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux
Postgres version (psql -V): psql (PostgreSQL) 11.7 (Raspbian 11.7-0+deb10u1)
Browsers: Chrome  85.0.4183.83 and Firefox 80.0.1
Screenshots:
![Clipboarder 2020 09 09-002](https://user-images.githubusercontent.com/29800119/92747578-b7887100-f35a-11ea-9351-1a133986e716.png)
![Clipboarder 2020 09 09-003](https://user-images.githubusercontent.com/29800119/92747588-ba836180-f35a-11ea-98df-a8dd04a386f3.png)
![Clipboarder 2020 09 09-004](https://user-images.githubusercontent.com/29800119/92747602-be16e880-f35a-11ea-8361-0ad8a71f8e34.png)

**Comment by MaminHakim** [comment]
Hi @sridhar391 , I think this is not a bug, for having this feature you have to buy Dashboard charts from here [](https://restya.com/board/apps/r_chart)
which is available on the Pro plan.

**Comment by sridhar391** [comment]
@MaminHakim We have fixed the issue in the commit  https://github.com/RestyaPlatform/board/commit/5d5233aa4de0f60b0f252878275fdaa544969610 and the fix will be available in the upcoming release v0.7 (Scorpions)

For quick fix, please download the attached file and paste it in the `/usr/share/nginx/html/restyaboard/sql` folder path and rename the file from `trigger_function_count.txt` to `trigger_function_count.sql` and execute the SQL file on your Restyaboard database by executing the command `psql -h localhost -d restyaboard -U restya -W < /usr/share/nginx/html/restyaboard/sql/trigger_function_count.sql`


[trigger_function_count.txt](https://github.com/RestyaPlatform/board/files/5223179/trigger_function_count.txt)
