### ISSUE TITLE
TimeZone BUG !

### ISSUE THREAD

**Issue by MaminHakim** [RestyaPlatform/board#4174]
Hi !. there is some bug in the time zone I think. 
I checked in both demo and my local server. after setting the time zone. it's not working for example I've set on +4:30 and my server time zone is the same and correct. but here show me in 5 hours difference.

**Comment by sridhar391** [comment]
@MaminHakim Can you please tell us if you have set the Restyaboard server timezone in the Restyaboard admin panel site timezone

**Comment by MaminHakim** [comment]
yes, has been set in the admin panel and also set it in the ubuntu server.

**Comment by sridhar391** [comment]
@MaminHakim Can you please tell us if the user changed his local timezone in the Restyaboard user profile settings page

**Comment by MaminHakim** [comment]
I realized that when I change the TimeZone on the Server to the 0GMT, timezone in the restyaboard works well.

**Comment by sridhar391** [comment]
@MaminHakim Thanks for the confirmation of the issue fix

**Comment by rrjanbiah** [comment]
Closing this. Please feel free to reopen if this is not sorted out.
