### ISSUE TITLE
Reset the Admin password

### ISSUE THREAD

**Issue by MaminHakim** [RestyaPlatform/board#4177]
Hi, 
is there any way to reset the Admin password, when we don't have access to the email address and when the IMAP server is not working well.

**Comment by sridhar391** [comment]
@MaminHakim Sorry, currently there is no option and without email address, if the user  tries to changes the password, it will be an security issue.

**Comment by rrjanbiah** [comment]
Closing this. Please feel free to reopen if this is not sorted out.
