### ISSUE TITLE
Request: One-Click SSL with Let's Encrypt

### ISSUE THREAD

**Issue by manakill** [RestyaPlatform/board#4180]
This is a general request for an easy (or automatic) way(certbot?) to get SSL on Restya that won't throw warnings in browsers. Needs to support domains and sub-domains(maybe with wildcard). 
On-boarding users takes more time when you have to explain to them what Self Signed Certs are and why they have to go past scary warnings from the browser. One user today couldn't get through due to the browser itself! I had him use another browser and he was able to get in.

**Comment by sridhar391** [comment]
@manakill Thanks for the suggestion, we will discuss within the team about the suggestion

**Comment by sridhar391** [comment]
@manakill Fixed the installation script to get SSL certificate for the domain using the certbot on the commit https://github.com/RestyaPlatform/board/commit/db6da79ae186dec8654d8834bcae283c8da53bbb and it will be available on the upcoming release v0.7 (scorpions) and for subdomain support, we have created new issue https://github.com/RestyaPlatform/board/issues/4254
