### ISSUE TITLE
Recommended System 

### ISSUE THREAD

**Issue by MaminHakim** [RestyaPlatform/board#4181]
Hi, What is the minimum requirement system and recommended system for running restya with good performance and stability. 
like how many RAM and cpu core and etc.

**Comment by sridhar391** [comment]
@MaminHakim The recommended system for running restya with good performance and stability

8 GB RAM / 2 CPU
250 GB Hard Disk

**Comment by rrjanbiah** [comment]
Closing this. Please feel free to reopen if this is not sorted out.
