### ISSUE TITLE
Cloud flare SSL and subdomain

### ISSUE THREAD

**Issue by MaminHakim** [RestyaPlatform/board#4182]
Hi, I'm going to install the Cloudflare certificate on the server but unfortunately is not working. 
the scenario is Like this :
-We have the main Server in 100.100.100.100 and linked it to the main hostname for example www.our_company.com 
we are using Cloudflare and set ns of the Cloudflare on our domain name. 
- another server in 200.200.200.200 which we install Restyaboard on it. and point this subdomain for example board.our_company.com to this server. also in Cloudflare as A record. 
when the configuration is flexible everything is good. 
actually, this not full encrypts, all traffic form Restyaboard serves is not encrypted, and also when I received an Email form Restyaboard is not secure. 

what is the best way to using passing traffic through Cloudflare and also have access Restyaboard on our subdomain?

**Comment by rrjanbiah** [comment]
@MaminHakim This looks more of a Cloudflare related issues. I think, you can get better support in Cloudflare forums.

**Comment by MaminHakim** [comment]
let's change the scenario. Imagine that I have an SSL certificate for the server.  how should be the Nginx configurations?
all configuration is base on IP address.

**Comment by rrjanbiah** [comment]
@MaminHakim I'm not sure if we're on the same page. But, for me, it still looks specific to Cloudflare and Nginx than our code. In case, if that's not the case, can you share more information on what part of our code is blocking it?

**Comment by MaminHakim** [comment]
let's forget Cloudflare,
how should be the restyaboard.conf on conf.d folder configuration for having restyaboard on subdomain with ssl ?

**Comment by MaminHakim** [comment]
Finally,  I realized how to configure it. But not all of them with Cloudflare. 
after installing wildcard Letsenycript SSL on the server and confige Nginx. I point from the Cloudflare panel to my server IP with DNS only setting. 
the main website is proxied by Cloudflare and the Restya serve SSL is form lets encrypt :)

**Comment by rrjanbiah** [comment]
That's awesome. Thanks for sharing your note on how you fixed it. Sorry, we couldn't support you here.

Closing this now.
