### ISSUE TITLE
How to enable Parent/Child Dependency in cards and Start/End/Estimated/Completed Date in Cards

### ISSUE THREAD

**Issue by rkhapre** [RestyaPlatform/board#4183]
Hi All

I am using Restyaboard, currently in cards i can see only Due Date, how can i enable for "Completion Date", Estimated Date, Start Date, End Date etc.

Also how can i enable parent and child card dependency ?

As without this it is not useful

Please help...

Thanks

**Comment by sridhar391** [comment]
@rkhapre Please refer the link https://restya.com/board/apps/r_custom_fields for how to enable "Completion Date, Estimated Date, Start Date, End Date"

Please refer the link https://restya.com/board/apps/r_gantt_view for enabling the parent and child card dependency

**Comment by rrjanbiah** [comment]
Closing this. Please feel free to reopen if this is not sorted out.
