### ISSUE TITLE
Move a board into an organization

### ISSUE THREAD

**Issue by daryl-o** [RestyaPlatform/board#4184]
Other than modifying the database, is there an easy way to move a board into an organization?

**Comment by daryl-o** [comment]
I see that it can be changed from the GUI after all by changing the visibility.

**Comment by sridhar391** [comment]
@daryl-o You can move the board into an existing organization in Restyaboard by changing the board visiblity to organization and selecting the organization

**Comment by rrjanbiah** [comment]
Closing it as it seems to be sorted out.
