### ISSUE TITLE
IMAP documentation has to be improved for Gmail/Gsuite based IMAP email

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#4188]
Current documentation about IMAP https://restya.com/board/docs/imap/ is missing note about Gmail/Gsuite based email. Note that for Gmail, it has to be enabled explicitly in https://myaccount.google.com/lesssecureapps

**Comment by sridhar391** [comment]
Added the information for Gmail/Gsuite based email, please refer the link https://restya.com/board/docs/imap/#3
