### ISSUE TITLE
Starred Boards disappearing from user footer toolbar

### ISSUE THREAD

**Issue by manakill** [RestyaPlatform/board#4190]
Starred Boards disappearing from user footer toolbar. Still shows Starred but not showing in toolbar and not showing under Boards > Starred Boards menu

Issue showed up after Updating to version 0.6.9 from 0.6.8

![r1](https://user-images.githubusercontent.com/9597295/97378797-9ee80200-1899-11eb-906b-e5ff3c391662.jpg)
![r2](https://user-images.githubusercontent.com/9597295/97378810-a4454c80-1899-11eb-9ac6-80c01fd65edf.jpg)
![r3](https://user-images.githubusercontent.com/9597295/97378816-a7403d00-1899-11eb-9b96-b93fbcc79643.jpg)

**Comment by manakill** [comment]
I disabled and re-enabled the BoardsBar app and that made it worse. Now some show up when starred and some are unstarred and show up. When I Star a Board it deletes all the others from the toolbar lol.

**Comment by manakill** [comment]
I think I fixed it by Disabling "BoardsBar" App then Un-Starring all boards. Then Enabling "BoardsBar" and Starring the Boards again. That seems to be working now..

**Comment by manakill** [comment]
Also clicking the Starred Boards icon will delete all from the footer toolbar even though they all have Stars on them
![r4](https://user-images.githubusercontent.com/9597295/97381601-cd68db80-189f-11eb-818c-4ff0bf775ff3.jpg)

**Comment by sridhar391** [comment]
The `BoardsBar` app is loaded while fully loading the page and while going to other pages, the page changes and it will not reload the page and the `BoardsBar`is not shown

**Comment by rrjanbiah** [comment]
*Internal note* Have to update in https://github.com/RestyaPlatform/r_boardsbar fork
