### ISSUE TITLE
Cannot move Cards TO or FROM  1 Board in particular

### ISSUE THREAD

**Issue by manakill** [RestyaPlatform/board#4191]
I have a "UnPaid" job board that completed jobs get moved to.

I click "move card" to "UnPaid Board" and it won't move.

The same card will move to other Client's Job Boards - but cannot move to 1 Board in particular

Moving cards to and from other Boards seem to be working fine

**Comment by manakill** [comment]
![Boarderror](https://user-images.githubusercontent.com/9597295/97380211-f3d94780-189c-11eb-836f-32f4e1da8955.jpg)

**Comment by manakill** [comment]
I may have fixed it by renaming the Board and it moves the Card back and forth again like it should - however it also deleted all the Starred Boards again as mentioned in: https://github.com/RestyaPlatform/board/issues/4190

**Comment by sridhar391** [comment]
@manakill Can you please set R_DEBUG as true on the config.inc.php file in line 15 on '/usr/share/nginx/html/restyaboard/server/php' path like https://github.com/RestyaPlatform/board/blob/dev/server/php/config.inc.php#L15 and copy the response of the move list call http://restyaboard_url/api/v1/boards/board_id/lists/list_id.json on the Network tab of Browser developer tools and paste it here or copy the contents from your server error log and paste it here.

**Comment by sridhar391** [comment]
@manakill Can you please set R_DEBUG as true on the config.inc.php file in line 15 on '/usr/share/nginx/html/restyaboard/server/php' path like https://github.com/RestyaPlatform/board/blob/dev/server/php/config.inc.php#L15 and copy the response of the move list call http://restyaboard_url/api/v1/boards/board_id/lists/list_id.json on the Network tab of Browser developer tools and paste it here or copy the contents from your server error log and paste it here.

**Comment by manakill** [comment]
Sorry it took me so long to reply! I haven't been having this issue for some time now everything has been smooth. I turned on the debug flag now and only have gotten this error:
2021/01/31 14:16:01 [error] 621#621: *446208 "/usr/share/nginx/html/restyaboard/client/HNAP1/index.$
2021/01/31 17:03:55 [error] 624#624: *447376 FastCGI sent in stderr: "PHP message: PHP Warning:  ar$
2021/01/31 17:04:05 [error] 624#624: *447376 FastCGI sent in stderr: "PHP message: PHP Warning:  ar$
2021/01/31 17:04:13 [error] 624#624: *447376 FastCGI sent in stderr: "PHP message: PHP Warning:  ar$
2021/01/31 17:07:22 [alert] 621#621: *447406 open socket #17 left in connection 5
2021/01/31 17:07:22 [alert] 621#621: aborting

Next time I'll try to remember to get the error log details before attempting to fix it lol

**Comment by sridhar391** [comment]
@manakill while moving the card, please copy the response of the move list call http://restyaboard_url/api/v1/boards/board_id/lists/list_id.json on the Network tab of Browser developer tools and paste it here or copy the contents from your server error log and paste it here.

**Comment by manakill** [comment]
@sridhar391 I moved cards back and forth and the only response I'm seeing is: 

HTTP/1.1 200 OK
Server: nginx/1.14.2
Date: Tue, 16 Mar 2021 18:01:05 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
x-response-url: /api/v1/boards/8/lists/242.json?token=6f1038b68bfea0a62a34e10026d50af24d6df8d2
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: *
X-RDebug: 30: v1/boards/8/lists/242.json
Content-Encoding: gzip

**Comment by sridhar391** [comment]
@manakill Please copy the response of the move list API call http://restyaboard_url/api/v1/boards/board_id/lists/list_id.json on the Network tab of Browser developer tools and paste it here

![move_list_copy_response](https://user-images.githubusercontent.com/17172525/111732611-e8160e00-889b-11eb-9dc4-6b5c1a2421d7.png)

**Comment by sridhar391** [comment]
@manakill We are closing the issue, due to inactivity, please feel free to reopen the issue, if you are facing the issue again
