### ISSUE TITLE
Boards with more than 24 Cards

### ISSUE THREAD

**Issue by manakill** [RestyaPlatform/board#4192]
We are going over 24 Cards on a Board and they are dropping off.

Need unlimited Cards on all Boards!
**CANNOT HAVE DATA LOSS**

![max24](https://user-images.githubusercontent.com/9597295/97383586-584bd500-18a4-11eb-99e3-eecdf543c30f.jpg)

**Comment by manakill** [comment]
Upon quick inspection this looks like the https://github.com/githiro/drawDoughnutChart error and not DATA LOSS. A quick look at their code, it doesn't appear to be a maximum number set, so I am guessing it is Restya code maxing out at number "24" somehow.

Please confirm no data loss is occurring and fix counter. Pie slices are less important at that high a number - but the number needs to be correct.

**Comment by rrjanbiah** [comment]
There is no such limit in Restyaboard. Also, you can see that in our demo. 

Can you please let us know if you've done any changes in the code? In case, if the database you're having doesn't have any sensitive details, please consider sharing that with our support email to debug this issue.

**Comment by manakill** [comment]
Here you go:
[dump-restyaboard-202010281330.zip](https://github.com/RestyaPlatform/board/files/5453811/dump-restyaboard-202010281330.zip)
Let me know if you need something else

**Comment by manakill** [comment]
Sorry, but I just checked my boards again and they are going past 24 now. I have no idea why or how, but this seems to be fixed now lol

**Comment by manakill** [comment]
![countmore24](https://user-images.githubusercontent.com/9597295/97479218-63e0df80-1928-11eb-8e4a-a83eb6320c6e.jpg)

**Comment by rrjanbiah** [comment]
@manakill Happy to know that.
