### ISSUE TITLE
Image uploaded in the docker is not stored in the Media directory "/usr/share/nginx/html/media"

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#4194]
## Expected Behavior
Image uploaded in the docker should be stored in the Media directory "/usr/share/nginx/html/media"

## Current Behavior
Image uploaded in the docker is not stored in the Media directory "/usr/share/nginx/html/media"

**Comment by daryl-o** [comment]
If I debugged this correctly, commit 8c14dbd5e9375314dc19fdad8969a9436457bd67  had the following:
```
-ENV ROOT_DIR=/usr/share/nginx/html \
+ENV ROOT_DIR=/var/lib/nginx/html \
```
config.inc.php has:
```
define('APP_PATH', dirname(dirname(dirname(__FILE__))));
define('DS', DIRECTORY_SEPARATOR);
define('MEDIA_PATH', APP_PATH . DS . 'media');
```
So changing the root dir seems to have changed all of the paths in config.inc.php. Which means the media isn't being saved where it was before the patch.
