### ISSUE TITLE
No Trello import available

### ISSUE THREAD

**Issue by lehnen** [RestyaPlatform/board#420]
I installed version v 0.1.6 (2015-12-23). Shell script states that there are no updates avaliable.
But my menu "Add board or organisation" contains no trello import item.

**Comment by rrjanbiah** [comment]
@lehnen Thanks for your report. We'll look into it.

**Comment by ssivachidambaram** [comment]
According to the condition Trello import will display while "Add Board" option was enabled in user roles page http://board.demo.restya.com/#/roles?

https://github.com/RestyaPlatform/board/blob/master/client/js/templates/organizations_board_form_view.jst.ejs#L5

For more details please refer, https://github.com/RestyaPlatform/board/issues/138#issuecomment-173167004
