### ISSUE TITLE
No error handling in cron.php

### ISSUE THREAD

**Issue by Aendrew87** [RestyaPlatform/board#422]
On my debian 8.3 I installed restyaboard 0.1.6 with the install script.
After that I did 'apt-get update' and 'apt-get upgrade'.
There was a new elasticsearch package available.
I installed the new version and wondered why there where no updates for elasticsearch.
'elasticsearch.last_processed_activtiy_id' increased all times.

After a little bit of debugging I found out, that elasticsearch was not running.
The curl call got a 'connection refused' but the 'elasticsearch.last_processed_activtiy_id' was updated.

Maybe the id should only be increased when a connection was possible.

**Comment by rrjanbiah** [comment]
@Aendrew87 Thanks for your report. This was already noted, but developer missed to fix it in https://github.com/RestyaPlatform/board/commit/e7a07446f40fb110891d2d254b62f9045ae58109

Thanks again, we'll fix it soon.

**Comment by ssivachidambaram** [comment]
Fixed.

**Comment by rrjanbiah** [comment]
Reopened. Still error handling not done properly https://github.com/RestyaPlatform/board/issues/704#issuecomment-231728406

**Comment by lmarikannan** [comment]
Fixed.

**Comment by rrjanbiah** [comment]
Reopened. May be OK for time being. But, code still needs many cleanup. Should use proper wrapper with error handling or use native calls for handling bulk indexing.

**Comment by lmarikannan** [comment]
Fixed
