### ISSUE TITLE
Can't view or edit cards after fresh install. 

### ISSUE THREAD

**Issue by danielwilson654** [RestyaPlatform/board#4221]
## Expected Behavior
Cards details apear as they do in the demo and I can edit them by clicking on them.

## Current Behavior
No editable card details are shown when clicking a card. only "Action" and "Add" are shown.

## Screenshots (if appropriate):
![issue with cards](https://user-images.githubusercontent.com/17303371/103606999-02627000-4f6c-11eb-81ee-5fb87700b829.png)

## Steps to Reproduce (for bugs)

1.Install using docker instructions here. https://restya.com/board/docs/install-restyaboard-docker/#0 
2.
3.
4.

## Context

I tried using multiple browsers, IPs, and users but the issue remained.

## Your Environment

* Version used: restyaplatform/restyaboard:dev
* Environment name and version docker-compose
* Operating System and version; ubuntu

**Comment by danielwilson654** [comment]
WORKAROUND:
change container version from restyaplatform/restyaboard:**dev** to restyaplatform/restyaboard:**v0.6.9**

**Comment by sridhar391** [comment]
@danielwilson654 The [Empty Data SQL](https://github.com/RestyaPlatform/board/blob/dev/sql/restyaboard_with_empty_data.sql) for the Restyaboard is not updated with the SQL changes for the upcoming Restyaboard release v0.7 (Scorpions) and now, we have updated the `Empty Data SQL` and the cards can be viewed and edited

**Comment by danielwilson654** [comment]
Great!
