### ISSUE TITLE
restyaboard_install.log

### ISSUE THREAD

**Issue by LeahPoi** [RestyaPlatform/board#4226]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sridhar391** [comment]
@LeahPoi Can you please tell us if you are facing any issues regarding the Restyaboard installation?
