### ISSUE TITLE
Edit Comment Not Save

### ISSUE THREAD

**Issue by cuchipkg** [RestyaPlatform/board#4230]
when i edit comment on card and after that i reload the page the comment not change, but the activity said i change comment 
![image](https://user-images.githubusercontent.com/60688301/105137991-d5df5400-5b26-11eb-8d15-979c621180ab.png)
![image](https://user-images.githubusercontent.com/60688301/105138079-f7d8d680-5b26-11eb-98fd-ee2fd48809f0.png)

**Comment by sridhar391** [comment]
Duplicate issue https://github.com/RestyaPlatform/board/issues/4172 and the fix will be available on the upcoming release v0.7 (Scorpions)
