### ISSUE TITLE
Postgres and the migration from 0.6.8 to 0.6.9

### ISSUE THREAD

**Issue by daryl-o** [RestyaPlatform/board#4231]
What is the preferred method to upgrade an existing database from 0.6.8 to 0.6.9 in docker? The postgres versions are incompatible so it isn't a simple matter to just stopping 0.6.8, starting 0.6.9 and running the upgrade script. My guess is the following but it does raise a few questions:

- Dump the old database
- Delete the volume
- Let 0.6.9 initialize a new database
-  Restore from the backup

The problems I see are that it might not work with the additional fields that were added and the database user has changed between the two releases.

**Comment by sridhar391** [comment]
@daryl-o Duplicate issue https://github.com/RestyaPlatform/board/issues/4115
