### ISSUE TITLE
Member of an organization with the Viewer role can still add cards, comment ect.

### ISSUE THREAD

**Issue by BenjaminNV** [RestyaPlatform/board#4235]
Hi, when I add a member to my organization then change his role to Viewer in that organization I'd expect it to impossible for him to add a new board, a new list and in general change anything in the organization.
It looks to be that the role I give him in the Members tab next to Boards has no effect what so ever. 

At the moment to change his role so he can only view the board I would have to go into that board and change his role from there which can get annoying if I have up to thirty boards in that organization.

I am not sure if this is intended behavior or not but it would be nice to be able to change the users role for all the boards in the organization without having to click inn on each board and changing his role in there.

If my question need more information or if my writing was unclear just ask and I'll try to explain further.

**Comment by rrjanbiah** [comment]
We have:

1. User role - to handle *users module* related permissions
2. Board role - to handle *board and cards* related permissions
3. Organization role - to handle *organization* pages related permissions

So, you may want to check board role.

*Internal note*

Opened #4236

**Comment by BenjaminNV** [comment]
Thanks for your answer.

Do you know if there are plans to make a organization role that act as board roles but for all the boards in the organization?

**Comment by rrjanbiah** [comment]
@BenjaminNV Sorry, currently no.

**Comment by BenjaminNV** [comment]
Thats too bad, well thanks for answering my questions.

Im going to close this issue now.
Have a nice day.

**Comment by rrjanbiah** [comment]
Reopening to provide better documentation or UI hints.

*Internal note*

Alternatively, may provide different solutions for different use cases. Looks like we may disable board creation permission for the user level and only have admin create boards.

**Comment by sridhar391** [comment]
@BenjaminNV We have explained in detailed about the user roles, board roles and organization roles, please refer the documentation link https://restya.com/board/docs/restyaboard-roles-configuration/
