### ISSUE TITLE
Documentation to explain user roles, board roles and organization roles

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#4236]
Our current documentation is not very helpful. The document explains only where we can find the roles option, but not much. Need to improve https://restya.com/board/docs/restyaboard-roles-and-permission-configuration/

**Comment by sridhar391** [comment]
Added the documentation for explanation about user roles, board roles and organization roles and the link is https://restya.com/board/docs/restyaboard-roles-configuration/
