### ISSUE TITLE
Wrong is_send_newsletter id in periodic_email_notification.php

### ISSUE THREAD

**Issue by Aendrew87** [RestyaPlatform/board#424]
In periodic_email_notification.php line 24 the id is set to '2'.
This is the falue for instant notifications.

The value has to be changed to '1' to send periodic mails.

**Comment by rrjanbiah** [comment]
@Aendrew87 Thanks a lot for this report. We'll fix it soon.

@ssivachidambaram  https://github.com/RestyaPlatform/board/blob/master/server/php/shell/periodic_email_notification.php#L25

**Comment by ssivachidambaram** [comment]
Fixed.

**Comment by Aendrew87** [comment]
Just to get sure:

The fix is not in milestone 0.2 at the moment.
Only in the dev path is a fixed version of the file.

When looking at the fixes for milestone 0.2 it is still listed:
https://github.com/RestyaPlatform/board/issues?q=milestone%3Av0.2

**Comment by ssivachidambaram** [comment]
Sorry. Milestone was changed to v0.2.1. We will release it shortly.
