### ISSUE TITLE
Blank page on server update

### ISSUE THREAD

**Issue by curiousmitchell** [RestyaPlatform/board#4246]
Hi, am running Restyaboard 0.6.7 on an Archlinux server - a recent update borked my system. Issue seems to be upgrading from php 7.4 to php 8, however having a hard time troubleshooting what's wrong. I need to either:

1. Recover my data, and migrate to a Debian Server, where I already have 0.6.9 working as an install
2. Get my Archlinux install working, so I can recover my data

I work at a small not-for-profit in Australia - I love Restyaboard, and its been a huge benefit to our charity. While I'd like to stay with Restyaboard, at this stage the chair of our board has instructed me to switch to Jira if I can't fix this.

Trying to trouble shoot, below are some log details:
/var/log/httpd/access_logs
ipaddress - - [11/Mar/2021:11:22:34 +1100] "GET /restyaboard/api/v1/oauth.json?_=1615422154355 HTTP/1.1" 500 -

/var/log/httpd/error_log
[Thu Mar 11 11:23:51.704091 2021] [php7:error] [pid 9624] [client ipaddress:19769] PHP Fatal error:  Uncaught Error: Call to undefined function pg_connect() in /srv/http/restyaboard/server/php/config.inc.php:71\nStack trace:\n#0 /srv/http/restyaboard/server/php/R/r.php(26): require_once()\n#1 {main}\n  thrown in /srv/http/restyaboard/server/php/config.inc.php on line 71, referer: https://apps.curiouslegends.com.au/restyaboard/

Thanks in advance for your help.

**Comment by sridhar391** [comment]
@curiousmitchell Can you please install the php-pgsql package for the PHP version 8 and restart  the PHP FPM as you have updated the PHP to PHP 8 version and not update the PHP packages for the PHP 8 version.

**Comment by sridhar391** [comment]
@curiousmitchell Can you please tell us if the Restyaboard login page shown after  installation of php-pgsql package for the PHP version 8

**Comment by curiousmitchell** [comment]
Apologies, will mark this as solved. The issue was indeed that I had updated my Arch linux server, and had not configured/installed the correct packages. php-pgsql is installed, and this is working correctly again. I am having other issues with upgrading this install and transferring to another server, however for now will mark this solved and close. Thanks.
