### ISSUE TITLE
Edited comments are not displayed

### ISSUE THREAD

**Issue by daryl-o** [RestyaPlatform/board#4247]
Board v0.6.9. Steps taken:
- Open a card
- Add a comment
- Edit the comment
- Close the card
- Open card again -> Original comment is displayed
- Edit comment again -> Change is reflected against the edited comment even though the original comment was displayed.

Are comments only stored in the activities table?

**Comment by sridhar391** [comment]
@daryl-o We have fixed the issue in the commit https://github.com/RestyaPlatform/board/commit/7bb7b61ee95b81261434f341c1d639519380cf02 and the fixes will be available in the upcoming Restyaboard version v0.7 (Scorpions)
