### ISSUE TITLE
Maybe a sql error in instant_email_notification.php and periodic_email_notification.php

### ISSUE THREAD

**Issue by Aendrew87** [RestyaPlatform/board#425]
In both script there are multiple sql statments that maybe incorrect.

For example:
`SELECT * FROM activities_listing WHERE id > $1 AND user_id = $2  AND board_id = ANY ($3) ORDER BY id DESC`

The results contains only changes that where made by the current user.
Changes made by other users would not be listet because of the 'AND user_id = $2'.

**Comment by rrjanbiah** [comment]
@Aendrew87 This looks like an intended behavior. We'll check them anyway. Thanks again for your kind report.

**Comment by ssivachidambaram** [comment]
Fixed.
