### ISSUE TITLE
Install script is not working on a raspberry with raspbian

### ISSUE THREAD

**Issue by Aendrew87** [RestyaPlatform/board#426]
On raspbian the command 'cat /etc/issue | awk '{print $1}' | sed 's/Kernel//g'' (install script at line 18) returns 'Raspbian'.
So the installation fails because yum is not available.

**Comment by rrjanbiah** [comment]
@Aendrew87 Thanks for your report. This definitely helps. Will fix it soon.

**Comment by ssivachidambaram** [comment]
Fixed
