### ISSUE TITLE
When dragging one card off a list, other cards disappear from original list

### ISSUE THREAD

**Issue by nsymms** [RestyaPlatform/board#4266]
## Expected Behavior
When dragging a card to another list, the remaining cards should NOT disappear

## Current Behavior
It's difficult to reproduce, but happens to me often.
In a list with 2 or more cards, I drag a card from that list to another. The other cards in the original list disappear after the notification fires. That is, 2-3 seconds later when the dragged card does its little dance and the bell appears.
A browser refresh shows the cards are still in that list, but that's not a solution or even a valid workaround.

## Screenshots (if appropriate):
I'll post a GIF of it as soon as I can reproduce it easily.

## Possible Solution
Refresh the browser often?

## Steps to Reproduce (for bugs)
1. Drag a card from a list with 2 or more cards to another list.
2. Wait for the notification to fire
3. Notice that the original list now has no cards (should have 1 or more)

## Context
This makes the application completely unreliable and unusable.

## Your Environment
* Restyaboard version: 0.6.9
* Windows 10 / Chrome 89.0.4389.114

I'm testing to get this reproducible. The only thing I've noticed so far is that it happens after leaving the window idle for awhile and the browser console has a single error (I don't know how recent it was):
GET http://my.board.my.tld/api/v1/users/3/activities.json?type=all&last_activity_id=117&direction=ASC&token=bd657a3551e812618be002b80aebf4090435b915&_=1618422936391 401 Unauthorized

I'm not sure why that one request would fail, but maybe afterward something gets messed up and causes problems later on.

**Comment by rrjanbiah** [comment]
@srileka Are we able to reproduce this issue?

**Comment by nsymms** [comment]
Yes I've reproduced several times since my original post. I made a video to illustrate but it contains some private information so I'm waiting to make another today on a test board. Here's what I do to reproduce:

- Clear all notification alerts and the notification bell button on the bottom right. (I'm not sure if this is necessary, but I do it anyway).
- Have a list with 2 cards in it, and another list to the right with 3-4 cards.
- Let the web browser sit idle for an hour or so. Usually I wait until it gets at least one 401 error requesting its periodic updates.
- Move the top card (haven't tried the bottom card) from the 2-list board onto the longer board.
- Wait for the notification to fire
- The shorter list (with only one card left) will hide its last card and now be empty.

It's very strange and has something to do with notifications.

**Comment by rrjanbiah** [comment]
@nsymms Thank you so much for explaining the issue.

**Comment by nsymms** [comment]
Here's a small GIF of the behavior. I've made it blurry to hide private information. The console window at the bottom of the browser shows 1 error, the 401 that I mentioned earlier.

![resty-issue](https://user-images.githubusercontent.com/9939843/114889575-d73fb600-9dcf-11eb-854f-84f7703d54f4.GIF)

**Comment by rrjanbiah** [comment]
@nsymms Thank you

**Comment by daryl-o** [comment]
We had a user with the same issue. Thanks for reproducing it.

**Comment by sridhar391** [comment]
@nsymms @daryl-o The timeout issue has been fixed in the commit https://github.com/RestyaPlatform/board/commit/7a9106e4d4334cf58efea669c5742c24f56ba509 and the fixes will be available on the upcoming release v0.7 (Scorpions) and we have also fixed the cards disappering issue and the fixes will be available on the upcoming release v0.7 (Scorpions)
