### ISSUE TITLE
User profile not saved in v0.7 with SSL and notifications enabled

### ISSUE THREAD

**Issue by daryl-o** [RestyaPlatform/board#4275]
I've been testing the v0.7 branch (realizing the fact that it isn't officially released yet) running in docker containers.  When notifications are enabled in the browser, clicking on the submit button to save a user's profile doesn't change the profile. There is also no notification that the profile has been changed. If I disable notifications, the profile is saved as normal.

I enabled SSL by setting up a separate Nginx container with proxy_pass to port 1234.

**Comment by daryl-o** [comment]
This might be related to #4273

**Comment by sridhar391** [comment]
@daryl-o We have fixed the issue on the commit https://github.com/RestyaPlatform/board/commit/448c958cdbd40aebf5fc57843a83fe3c7d29ae13 and the fix will be available on the upcoming release
