### ISSUE TITLE
Notification bell icon in the card is showing for the current user

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#4277]
## Expected Behavior
Current user doing any activity, Notification bell icon should not show in the card for the current user

## Current Behavior
Notification bell icon in the card is showing for the current user

## Possible Solution

1. Open the board and wait for sometime
2. After that, moving the card from one list to another list.
3. That time notification bell icon displayed for current user.
4. That while adding the task also, bell icon displayed

## Your Environment

* Version used:
* Environment name and version (e.g. OS, PHP, PostgreSQL):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by sridhar391** [comment]
related issue https://github.com/RestyaPlatform/board/issues/4277

Fixed the issue on the commit https://github.com/RestyaPlatform/board/commit/0dc70428ddb81ba24d5dd2708589fb208202d902
