### ISSUE TITLE
LDAP Error messages when login fails

### ISSUE THREAD

**Issue by Zimeon-** [RestyaPlatform/board#429]
PHP message: PHP Notice:  Use of undefined constant ERROR - assumed 'ERROR' in /usr/share/nginx/html/server/php/libs/core.php on line 468
PHP message: PHP Warning:  trigger_error() expects parameter 2 to be long, string given in /usr/share/nginx/html/server/php/libs/core.php on line 468
PHP message: PHP Notice:  Use of undefined constant ERROR_LDAP_SERVER_CONNECT_FAILED - assumed 'ERROR_LDAP_SERVER_CONNECT_FAILED' in /usr/share/nginx/html/server/php/libs/core.php on line 469
PHP message: PHP Fatal error:  Cannot use string offset as an array in /usr/share/nginx/html/server/php/R/r.php on line 1401" while reading response header from upstream, client: 192.168.120.139, server: _, request: "POST /api/v1/users/login.json?token=c280035d6422cba1a0877mmmmmmmm8b73558bd9eb085 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/restyaboard.socket:", host: "infra.dc.local", referrer: "http://hostname.domain.local/"

CentOS 6.7
php 5.3.3

**Comment by rrjanbiah** [comment]
@Zimeon- Thanks a lot for your report. Looks like an issue with php LDAP extension version issue. Will check in our end anyway.

**Comment by ssivachidambaram** [comment]
Upgrade SQL added for LDAP settings. Please refer #436.

**Comment by ssivachidambaram** [comment]
PHP warnings fixed.
