### ISSUE TITLE
Upgrade window first time displayed top. If we minimize and the maximize, it's displayed bottom

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#4315]
Upgrade window first time displayed top. If we minimize and the maximize, it's displayed bottom

**Comment by sridhar391** [comment]
@srileka Not able to reproduce the issue

**Comment by sridhar391** [comment]
@srileka We have fixed this issue in the commit https://github.com/RestyaPlatform/board/commit/2dc3b848c88708c03b2e2dce846c83c0672bccbf
