### ISSUE TITLE
Card content not loading for certain users after update to 1.7

### ISSUE THREAD

**Issue by julesfarrow** [RestyaPlatform/board#4329]
## Expected Behavior

When you click onto a card within a board, the overlay window should open and show the content of the card.

## Current Behavior

For at least one of my users (discovered so far) after the upgrade to 1.7 they are shown a partially loaded/mostly blank overlay window as per the screenshot below. They also have an error message in the js console:
`default.cache.js:1 Uncaught (in promise) TypeError: Cannot read property 'r_cssilize' of null
    at default.cache.js:1
    at default.cache.65786288.js:1`
This behaviour is unique to this user - and follows when the user account is logged into alternative devices/browsers, where logging in with another user account solves the issue.

## Screenshots (if appropriate):
![Screenshot from 2021-08-03 17-24-52](https://user-images.githubusercontent.com/9074028/128052650-00fa30f6-33b9-4bc1-a7fa-17a4dbee663d.png)

## Your Environment

* Version used: 1.7
* Environment name and version (e.g. OS, PHP, PostgreSQL): AWS AMI
* Operating System and version (desktop or mobile): Ubuntu 18.04.5

**Comment by sridhar391** [comment]
@julesfarrow In the Restyaboard latest version v1.7, In the Restyaboard admin panel, Roles page, we have added the cards tab, in which you can select the fields which you want to be shown to the particular board user role and for which board user role you don't want to show the fields

We have added the permission to view all the card details by the board user roles owner and editor and for the viewer roles, you can manage which fields by selecting for the Viewer role

![card-fields-permission](https://user-images.githubusercontent.com/17172525/128311242-64ce13d7-0a90-4981-8e27-993a29d8a3e4.png)

For more details, please refer to the documentation in the link https://restya.com/board/docs/restyaboard-manage-permission-for-card-fields/

**Comment by julesfarrow** [comment]
@sridhar391 when I visit this page from an admin account, no content shows. Perhaps an issue during the upgrade to 1.7?

![image](https://user-images.githubusercontent.com/9074028/128326538-47b405ec-1cfc-4858-aea0-4293b8423d39.png)

**Comment by sridhar391** [comment]
@julesfarrow Can you please tell us if you have updated the Restyaboard using Restyaboard installation script "restyaboard.sh" and if you have updated using the installation shell script, please send us the Restyaboard log file named "restyaboard_install.log"

For updating the Restyaboard, please execute the SQL command from the link https://github.com/RestyaPlatform/board/blob/master/sql/upgrade-0.6.9-1.7.sql on your Restyaboard database

**Comment by julesfarrow** [comment]
[restyaboard_install.log](https://github.com/RestyaPlatform/board/files/6946619/restyaboard_install.log)

@sridhar391 yes, updated using "restyaboard.sh" from the home directory. Log file attached for your reference.

Running the .sql file above as "sudo -u postgres psql -d restyaboard -f upgrade-0.6.9-1.7.sql" from the instance solved this problem, for anyone else having the same issue.

**Comment by sridhar391** [comment]
@julesfarrow We have checked the log and you have used the old Restyaboard installation script file, that's why it didn't executed the ugrade SQL file

Thanks for the confirmation of the issue fix
