### ISSUE TITLE
Docker Repo Needs Latest Release

### ISSUE THREAD

**Issue by Stoyvo** [RestyaPlatform/board#4334]
https://registry.hub.docker.com/r/restyaplatform/restyaboard/tags?page=1&ordering=last_updated

The last push to docker repository was 4 months ago and is missing tag v1.7. This is unfortunate to everyone who has not migrated to docker compose (Eg: Synology NAS applications using a UI)

**Comment by sridhar391** [comment]
@Stoyvo We have updated the Restyaboard docker image with the latest version v1.7 (Scorpians) https://hub.docker.com/r/restyaplatform/restyaboard/tags?page=1&ordering=last_updated
