### ISSUE TITLE
Mentioning a user with special characters

### ISSUE THREAD

**Issue by Zimeon-** [RestyaPlatform/board#434]
When you mention a user with @username in a card it bugs out when a username has a special character in it, for example @firstname.lastname shows @firstname as highlighted and .lastname as regular text. Mentioning a user that has @firstnamelastname (without a dob) works like exptected.

**Comment by rrjanbiah** [comment]
@Zimeon- Sorry for more issues than anticipated. Our QA seems to have overlooked these use cases. Perhaps we should release alpha version to few users before we release public beta.

**Comment by Zimeon-** [comment]
Bugs happen, none of these have been fatal or game breaking :) If anything, upgrade notes would be nice at some point. For example that LDAP bind didn't work until the LDAP settings were saved again using a local admin account.

**Comment by rrjanbiah** [comment]
@Zimeon- Thanks for your kind words. For LDAP I have opened #436 and will look into it. Thanks again.

**Comment by ssivachidambaram** [comment]
Fixed.
