### ISSUE TITLE
Popup disappears before an action can be taken

### ISSUE THREAD

**Issue by daryl-o** [RestyaPlatform/board#4348]
The following issue happens with both v0.6.9 and v1.7. Tested using restyaboard inside docker and Google Chrome web browser. Steps to reproduce:

- Click on any card
- Under actions, choose move or copy card
- Select and item in one of the drop-downs
- Popup will disappear before the action button can be pressed and nothing happens

I've noticed the problem when trying other actions as well.

**Comment by rrjanbiah** [comment]
Taken care in #4362
