### ISSUE TITLE
Import from Tello

### ISSUE THREAD

**Issue by jfreak53** [RestyaPlatform/board#4359]
Site says we can import from trello our old boards, but I'm not finding it in the documentation anywhere. How do I import boards from trello?

**Comment by sridhar391** [comment]
@jfreak53  For Trello import, please follow the below steps
1. please login Restyaboard and click the Boards option in the footer and click the "Add Board" option like the attached image "add_board.png"
![add_board](https://user-images.githubusercontent.com/17172525/139636608-535e8fc5-a42b-4e25-a7d3-4ab91e53c528.png)

2. After that, please click the "import board" option like the attached image "import_board.png"

![import_board](https://user-images.githubusercontent.com/17172525/139636643-7cd5b42c-9e05-4eb9-9e57-b2927ccf6172.png)

3. After the above steps, please click the Import from Trello option in the list of options and upload the Trello exported JSON file

**Comment by sridhar391** [comment]
Closing the issue due to inactivity
