### ISSUE TITLE
LDAP setting upgrade is not smooth

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#436]
From #434

LDAP bind didn't work until the LDAP settings were saved again using a local admin account.

**Comment by Zimeon-** [comment]
This was most likely only an issue with this version upgrade from 0.1.6 to 0.2.0 as the LDAP bind user is stored differently.

**Comment by rrjanbiah** [comment]
Zimeon- Thanks a lot for your note

**Comment by ssivachidambaram** [comment]
Fixed.
