### ISSUE TITLE
All the drop down field, after choosing the some option, it's get closed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#4362]
## Current Behavior

All the drop down field, after choosing the some option, it's get closed

## Screenshots (if appropriate):

![option_closed](https://user-images.githubusercontent.com/14290356/142588738-87702709-1bb4-45d7-9169-0f6e2fa21bbc.png)

**Comment by daryl-o** [comment]
This is the issue reported in [#4348] and [#4355]

**Comment by daryl-o** [comment]
Note that this also affects the custom field app.

**Comment by daryl-o** [comment]
I was testing out the patch associated with this issue.  It fixes the problem we were seeing but created a new one. The board drop-down at the bottom left-hand corner doesn't bring up the menu any more.

**Comment by sridhar391** [comment]
@daryl-o The custom field app issue also fixed and in the upcoming release, will send the fixed files and also fixed the board drop-down at the bottom left-hand corner doesn't bring up the menu issue in the commit https://github.com/RestyaPlatform/board/commit/e380937bf7b79002016c0d4b22b65877922c1915
