### ISSUE TITLE
Docker restyaboard version obsolete

### ISSUE THREAD

**Issue by raphaelcasimir** [RestyaPlatform/board#437]
Hello, do you plan to upgrade the Docker code for v0.2 ? Because when I put ENV restyaboard_version=v0.2 in the Dockerfile, the build process goes well but the server displays error 502.

namikingsoft has not answered any issues since october 2015, that's why I am asking this question here.

Thanks for your great support

**Comment by raphaelcasimir** [comment]
I am not alone, but still no answers from the original developper...

**Comment by rrjanbiah** [comment]
@raphaelcasimir

Is there anyway you can migrate to our new install script?

Docker version seems to be having strange issues https://github.com/RestyaPlatform/board/search?q=docker&type=Issues&utf8=✓ for that we don't have expertise. So we planned to check after our current high priority list of items.

If you can share why docker is your preference, we may consider moving up in priority order. Thanks

**Comment by raphaelcasimir** [comment]
I chose Docker because it is virtual machines, done right. It has all the things virtual machines have, like a sealed and reproductible environement, but without their drawbacks. The Docker containers are very lightweight, can use all the computing power of your server, doesn't take much ressources when idle, you now just like regular applications.
They are also pretty simple to build.

Since you can share containers on the Docker Hub, you can preconfigure them so the end user has no trouble with certain settings.

If I had a little time for me I would gladly participate and update the script, but it is 00:45 and still have some work (I have a robotics project to make).

**Comment by rrjanbiah** [comment]
@raphaelcasimir Thanks a lot for your explanation. We'll see what we can do here.

**Comment by rrjanbiah** [comment]
@raphaelcasimir Closing this as @namikingsoft has kindly upgraded it https://github.com/namikingsoft/docker-restyaboard/issues/9

**Comment by raphaelcasimir** [comment]
Thanks but it doesn't upgrade. I deleted and cloned the folder again, I get a blank page with a rapid loading bar on the top that disappears (I purged the cache). Maybe a database error,,,
