### ISSUE TITLE
Reporting security issues

### ISSUE THREAD

**Issue by emilvirkki** [RestyaPlatform/board#4374]
I've discovered several critical security issues in Restyaboard, but I can't find any guidance on how to report those confidentially. Would it be possible for you to set up a security policy for the repository or otherwise document the procedures for reporting? :)

**Comment by sridhar391** [comment]
@emilvirkki we have a contact link in our README.md file, can you please submit the critical security issues explanation from https://restya.com/contact?

**Comment by emilvirkki** [comment]
Did that - thanks for the instructions!

**Comment by sridhar391** [comment]
@emilvirkki We have fixed the issues and added the fixes in the Restyaboard latest version v1.7.1(Scorpion)
