### ISSUE TITLE
Blank page right after install

### ISSUE THREAD

**Issue by EHRETic** [RestyaPlatform/board#4398]
Hello

## Expected Behavior
Login mask to come up 😊

## Current Behavior
No login mask coming up, despite SELINUX is off.

## Steps to Reproduce (for bugs)
1. Disabled SELINUX (already before install)
2. Deployed Restya with install script and all default answers (NGINX)
3. Tried to access the page, connectivity seems OK but no login mask is coming
4. As in video : I get the same behavior with oauth.json:

![image](https://user-images.githubusercontent.com/28634810/160797164-7b8b0927-8a98-468c-9472-a9c45f58c326.png)
(But SELINUX is already off)

5. As mentioned here at the end: https://github.com/RestyaPlatform/board/issues/4282 I tried to turn R_DEBUG as true and access the api page, but didn't get any notable info in the Network tab (I might look at the wrong place)

## Your Environment
* Version used: Last one as today (install script)
* Environment name and version (e.g. OS, PHP, PostgreSQL): , all component versions are the default installed by script
* Operating System and version : Server on AlmaLinux 8.5, Client on Windows 10 with Chrome 100 & Brave 99 (empty cache to be sure)

I planned to have a dedicated VM for Restya in my lab (should replace 2 other platform), so there nothing else on that server. I plan to secure NGINX later on and configure it with my standards, but first I need to get it working first! 😉

Any hint to troubleshoot it further?

**Comment by sridhar391** [comment]
@EHRETic We need to check the errors, can you please send us the Restyaboard installation log file named `restyaboard_install.log` which is in the same folder path of the Restyaboard installation script file `restyaboard.sh`

**Comment by EHRETic** [comment]
> @EHRETic We need to check the errors, can you please send us the Restyaboard installation log file named `restyaboard_install.log` which is in the same folder path of the Restyaboard installation script file `restyaboard.sh`

Hi,

Here is the log file (host fqdn has been replaced by something else)
[restyaboard_install.log](https://github.com/RestyaPlatform/board/files/8381465/restyaboard_install.log)

Let me know if you need anything else, thanks! 😉

**Comment by EHRETic** [comment]
PS: I have a snapshot of the VM prior the install, so I can re-test it anytime! 😊

**Comment by sridhar391** [comment]
@EHRETic We have checked the Restyaboard installation log file and using the Restyaboard installation script file, we are officially supporting the Restyabooard installation on Ubuntu, Debian, LinuxMint, Raspbian, CentOS and if you want the installation support for your AlmaLinux OS, please [contact us](https://restya.com/contact)

**Comment by EHRETic** [comment]
@sridhar391 AlmaLinux is a well known distribution based on RHEL:

`CloudLinux's core product, the CloudLinux OS, is a RHEL® fork that has been in place for over ten years. More than 4,000 companies including Dell, Liquid Web, and 1&1 rely on the CloudLinux OS across more than 200,000 product installations. CloudLinux has proven experience in creating and maintaining a RHEL fork and have done so starting with RHEL release 5, right through to release 8. AlmaLinux OS is an opportunity for us to channel our expertise in RHEL into a Linux distribution that serves the broader community. Furthermore, we are including the Linux community right from the inception of AlmaLinux OS. Moving forward, community members will be on the governing board for the AlmaLinux OS project and involved in key decisions too. Finally, AlmaLinux OS will always be free and open source. The community can pick up and continue to develop AlmaLinux OS at any time.`

There is probably some subtle differences but mot packages are the same. Really not a clue where I can look? 😉
