### ISSUE TITLE
Login page field names are not displayed in IE

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#44]
Login page field names are not displayed in IE
![login page field name not displayed](https://cloud.githubusercontent.com/assets/14290356/9875861/3ebb4b44-5bcf-11e5-9dac-32cf57328875.png)

**Comment by rrjanbiah** [comment]
As placeholder is not supported in IE 9, please refer http://www.w3schools.com/tags/att_input_placeholder.asp. So we have provided title for the input identification.
