### ISSUE TITLE
Accessing a card directly with a link shows board as private

### ISSUE THREAD

**Issue by Zimeon-** [RestyaPlatform/board#443]
If a user tries to access a card directly iwith a link, the board is displayed as private.

" Board not found This board may be private. You may be able to view it by logging in."

This issue can be reproduced by copying the link and then opening a new tab to access the copied link. Link format is in http://restya.host.local/#/board/10/card/268

**Comment by ssivachidambaram** [comment]
We have used sessionStorage for authentication, so the user authentication will not work in new tab.
