### ISSUE TITLE
User logout generate  [error] 2682#0 PHP Notice:  Undefined index:apps

### ISSUE THREAD

**Issue by Zimeon-** [RestyaPlatform/board#448]
When a user logs out of restya, the following error is logged

2016/03/14 13:25:50 [error] 2682#0: *495 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: apps in /usr/share/nginx/html/server/php/R/r.php on line 4729" while reading response header from upstream, client: 192.168.nn.nn, server: restya.nn.local, request: "GET /api/v1/oauth.json?_=1457954750450 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/restyaboard.socket:", host: "restya.nn.local", referrer: "http://restya.nn.local/"

**Comment by ssivachidambaram** [comment]
Fixed.
