### ISSUE TITLE
Admin filter by LDAP user error

### ISSUE THREAD

**Issue by Zimeon-** [RestyaPlatform/board#449]
When filtering users in Admin view by LDAP generates an error:

PHP message: PHP Notice:  Trying to get property of non-object in /usr/share/nginx/html/server/php/R/r.php on line 896" while reading response header from upstream, client: 192.168.nn.nn, server: restya.ssp.local, request: "GET /api/v1/oauth/clients.json?id=2&token=6bc7ee629585b6bdc2ca84c4e6f13613d10ea483&_=1457955211099 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/restyaboard.socket:", host: "restya.nn.local", referrer: "http://restya.nn.local/"
2016/03/14 13:35:06 [error] 2682#0: *555 FastCGI sent in stderr: "PHP message: PHP Warning:  pg_query_params(): Query failed: ERROR:  column "is_ldap" does not exist
LINE 1: ...son(d) FROM (SELECT * FROM users_listing ul WHERE is_ldap = ...
                                                             ^ in /usr/share/nginx/html/server/php/R/r.php on line 989" while reading response header from upstream, client: 192.168.nn.nn, server: restya.nn.local, request: "GET /api/v1/users.json?page=1&filter=ldap&token=6bc7ee629585b6bdc2ca84c4e6f13613d10ea483&_=1457955306407 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/restyaboard.socket:", host: "restya.nn.local", referrer: "http://restya.nn.local/"

**Comment by ssivachidambaram** [comment]
Fixed.

**Comment by Zimeon-** [comment]
Need to reopen this as well. Now we see the following error:
http://restya.ssp.local/#/users?page=1&filter=ldap
404 Page not found.

Wierdly enough, nothing in the nginx log.

**Comment by ssivachidambaram** [comment]
Can you please enable debug mode in `config.inc.php` and can you please send screenshot or response got from the API call?

**Comment by rrjanbiah** [comment]
@ssivachidambaram Can we please try to reproduce it on our end?

**Comment by ssivachidambaram** [comment]
@rrjanbiah We have checked and its working fine for us.

![ldap-filter](https://cloud.githubusercontent.com/assets/91407/13870120/90939412-ed01-11e5-9078-15b3616fc827.png)

**Comment by Zimeon-** [comment]
Sorry for this, this was a mistake on my end when running the update SQL script which had not updated the users_listing view properly.

**Comment by rrjanbiah** [comment]
@Zimeon- No issues. Happy to hear that it is working for you.
