### ISSUE TITLE
Register page field names are not displayed in IE 9

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#45]
Register page field names are not displayed in IE 9
![register page field name not displayed](https://cloud.githubusercontent.com/assets/14290356/9875889/88856af2-5bcf-11e5-8448-52e75d205c8f.png)

**Comment by rrjanbiah** [comment]
As placeholder is not supported in IE 9, please refer http://www.w3schools.com/tags/att_input_placeholder.asp. So we have provided title for the input identification.
