### ISSUE TITLE
SMTP server support

### ISSUE THREAD

**Issue by Zimeon-** [RestyaPlatform/board#450]
Would love to see the option to configure a SMTP server including username+password authentication for the server.

**Comment by dfragac** [comment]
+1 here!

**Comment by rrjanbiah** [comment]
@Zimeon- @dfragac Thanks for your suggestion. We'll definitely consider that. For the timebeing:

* Windows users may try `php.ini` approach http://stackoverflow.com/questions/112190/php-ini-smtp-how-do-you-pass-username-password/6941390#6941390
* Linux users may try Postfix approach http://stackoverflow.com/questions/112190/php-ini-smtp-how-do-you-pass-username-password/31084190#31084190

**Comment by Zimeon-** [comment]
Thank you rrjanbiah for your comment. This is a good workaround but for some future release this would be a great addition.

**Comment by rrjanbiah** [comment]
@Zimeon- Yes, sure.

**Comment by ssivachidambaram** [comment]
Done in install script.

**Comment by rrjanbiah** [comment]
`php.ini` will work only for Windows. Refer above links
