### ISSUE TITLE
Paths during update from 0.1.6 to 0.2.0

### ISSUE THREAD

**Issue by Aendrew87** [RestyaPlatform/board#453]
When updating from 0.1.6 to 0.2.0 the fles are copied with 'cp -r ${DOWNLOAD_DIR} "$dir"'.
For example:
`cp -r /opt/restyaboard /usr/share/nginx/html/restyaboard`

When the destination does not exist it works.
But when the destination exists, a new folder inside the destionation would be created.

As a fix you might use something like that:
`cp -r /opt/restyaboard/. /usr/share/nginx/html/restyaboard`

**Comment by Aendrew87** [comment]
As a fix you might use something like that:
`cp -r /opt/restyaboard/. /usr/share/nginx/html/restyaboard`

**Comment by ssivachidambaram** [comment]
Fixed.
