### ISSUE TITLE
#/about still says v 0.1.6 

### ISSUE THREAD

**Issue by psyfi** [RestyaPlatform/board#455]
Hi! I upgraded from v0.1.6 to v0.2 using this instruction: https://github.com/RestyaPlatform/board/blob/master/README.md#upgrade

Things appear to be successful and I rebooted the VM. But I still get "v 0.1.6 (2015-12-23)" on the About page. No error message seen. No googling helped. What gives?

Thanks.

Peter

**Comment by psyfi** [comment]
moved around the old config.inc.php. It turned out, it should be a directory higher. But the problem now is that I am no longer able to login with the old credentials (admin or ordinary user).

**Comment by rrjanbiah** [comment]
@psyfi 

> moved around the old config.inc.php. It turned out, it should be a directory higher. But the problem now is that I am no longer able to login with the old credentials (admin or ordinary user).

Can you please enable debug mode https://github.com/RestyaPlatform/board/blob/master/server/php/config.inc.php#L15 ? and post the error/response you see in HTTP response?

**Comment by psyfi** [comment]
Enabled. Now I get this on nginx error log: "Undefined index: apps in /usr/share/nginx/html/server/php/R/r.php on line 4729" while reading response header from upstream, client:..."

Anyway, I can't spend more time on this. I'll just come back when Restya becomes more mature. 

Best wishes!

**Comment by psyfi** [comment]
For whatever its worth is, perhaps you'll consider package delivery via yum as opposed to script. Tuleap does it well. There are just so many variables that might not work, if upgrade is done via overwrite or installation is done via script. Thanks for the experience!

**Comment by rrjanbiah** [comment]
@psyfi Thanks a lot for your help and suggestions. We'll definitely consider your feedback and will improve. Thanks again.
