### ISSUE TITLE
User updated by admin shows incorrect old information

### ISSUE THREAD

**Issue by Zimeon-** [RestyaPlatform/board#458]
Here's an example of the Admin account updating a user account.	

Admin updated the profile.

**admin@restya.**userä@restya.local_local_

**Admin**User&auml;

**A**U

**Admin**

As github doesn't undestand overline (i think), I made teh red (old information) in bold and the new information (green) as normal. Note that the email feild also has the local in italic which is grayed out and should be a part of the old email. Now without looking at the code I would presume that it takes the logged in users old information (Admin) and shows that as old details instead of the actual old data while taking the form field as new information. This would only be apparent when user details are updated by someone else than the user himself.

Also note that using the scandinavian letter in the users name (for example ÄÖÅäöå) uses the ascii variant of encoding and shows it incorrectly in the log. The encoding error is only present in the page log as far as I've noticed it.

**Comment by ssivachidambaram** [comment]
Fixed.
