### ISSUE TITLE
Wrong entries in crontab when updated with restyaboard.sh

### ISSUE THREAD

**Issue by Aendrew87** [RestyaPlatform/board#469]
When using the script 'restyaboard.sh' for the update the crontab would not be updated

> echo "Changing files path for existing cron..."
> sed -i "s/server\/php\/R\/cron.sh/server\/php\/indexing_to_elasticsearch.sh/" /var/spool/cron/crontabs/root
> sed -i "s/server\/php\/R\/instant_email_notification.sh/server\/php\/instant_email_notification.sh/" /var/spool/cron/crontabs/root
> sed -i "s/server\/php\/R\/periodic_email_notification.sh/server\/php\/periodic_email_notification.sh/" /var/spool/cron/crontabs/root

In the path the directory 'shell' is missing.
> echo "Changing files path for existing cron..."
> sed -i "s/server\/php\/R\/shell\/cron.sh/server\/php\/shell\/indexing_to_elasticsearch.sh/" /var/spool/cron/crontabs/root
> sed -i "s/server\/php\/R\/shell\/instant_email_notification.sh/server\/php\/shell\/instant_email_notification.sh/" /var/spool/cron/crontabs/root
> sed -i "s/server\/php\/R\/shell\/periodic_email_notification.sh/server\/php\/shell\/periodic_email_notification.sh/" /var/spool/cron/crontabs/root

**Comment by ssivachidambaram** [comment]
Sorry for the trouble. We have fixed it in v0.2.1.
