### ISSUE TITLE
Activity popup not closed until click the close button

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#47]
Activity popup not closed until click the close button

**Comment by rrjanbiah** [comment]
Firefox and Safari close notifications automatically after a few moments (around four seconds). This may also happen at the operating system level. Some browsers don't however, such as Chrome.

Please refer this URL, https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API#Closing_notifications.
