### ISSUE TITLE
API post card label issue

### ISSUE THREAD

**Issue by stanleyliu1006** [RestyaPlatform/board#471]
Hi,

I try to test the cards_labels.json operation to add a new label, but its actually delete the labels.

![image](https://cloud.githubusercontent.com/assets/6980917/13802133/c02998a0-eb8c-11e5-89c3-7ae1724dc931.png)

And when I check the cards_labels.json file, the description shows it is a delete opeartion rather than post card label.

{ "name": "cardId",
   "description": "Card ID to delete",
   "required": true,
   "type": "integer",
   "paramType": "path"
 }

Can you please confirm if this is a bug, if so is there any way we can post the card label via rest api, rather than talk with the database directly.

Regards
Stanley

**Comment by ssivachidambaram** [comment]
Sorry for the trouble. Its an issue in API itself. We have fixed it and going to release today. So you can upgrade it through our install script.
