### ISSUE TITLE
API PUT Card.json (only partially working)

### ISSUE THREAD

**Issue by stanleyliu1006** [RestyaPlatform/board#472]
Hi Guys

The Card PUT operation is only works on the card name and position, it does not work on the archive statue and due date, no matter what values I assigned to them. Please check the diagram as below:

![image](https://cloud.githubusercontent.com/assets/6980917/13802934/e49835f4-eb94-11e5-8923-8f83be0dfe58.png)

![image](https://cloud.githubusercontent.com/assets/6980917/13802940/fab29d34-eb94-11e5-9dfb-66ceacbf9de1.png)

![image](https://cloud.githubusercontent.com/assets/6980917/13802959/1ac208c6-eb95-11e5-8f9e-f87c9e740c5a.png)

Please confirm if its a bug, or I miss something with the input parameters.

Regards
Stanley

**Comment by ssivachidambaram** [comment]
Sorry for the trouble. Its an issue in API itself. We have fixed it and going to release today. So you can upgrade it through our install script.
