### ISSUE TITLE
API POST checklists (no responding)

### ISSUE THREAD

**Issue by stanleyliu1006** [RestyaPlatform/board#473]
Hi Guys

For the API post checklist, which is running without any respond. And there's no new checklist are generated to the card (id: 111).

![image](https://cloud.githubusercontent.com/assets/6980917/13803375/36bb7b04-eb98-11e5-8b2c-eb656fefab51.png)

Not sure if there's some thing wrong with my testing, or could be an issue of the API itself.

Regards
Stanley

**Comment by ssivachidambaram** [comment]
Sorry for the trouble. Its an issue in API itself. We have fixed it and going to release today. So you can upgrade it through our install script.
