### ISSUE TITLE
Continue with API issue

### ISSUE THREAD

**Issue by stanleyliu1006** [RestyaPlatform/board#479]
Hi Guys

I just overwrite the api_explorer folder with the new release (without upgrade to v0.21), the API explorer is loading without end, is this because i have not upgrade to the latest version? or is there any other reason to cause it. If so can you also provide the link of the build version of the restyaboard v0.21?

![image](https://cloud.githubusercontent.com/assets/6980917/13832346/9b835db2-ec2f-11e5-9404-7482ffe278d7.png)

Kind regards
Stanley

**Comment by stanleyliu1006** [comment]
Hi,

I have updated the version to V0.21, but the api_explorer still running without respond, as shown in the diagram below, you can also go to the api_explorer in this link to have a test: https://emailmanagement.acfonline.org.au/client/api_explorer/

![image](https://cloud.githubusercontent.com/assets/6980917/13833517/b0e4eeae-ec3a-11e5-9d87-db286566b0a6.png)


Regards
Stanley

**Comment by ssivachidambaram** [comment]
You can upgrade it through the install script. https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh

**Comment by stanleyliu1006** [comment]
Thanks ssivachidambaram, I have successfully upgraded to the new version.

But the second screenshot still shows the API is loading without any response back, can you please have a check on that as well.

Thanks
Stanley

**Comment by espantosdarren** [comment]
We have tested in our demo site http://board.demo.restya.com/api_explorer/#!/users/loginUser and login is working fine. Can you please enable debug mode in this file https://github.com/RestyaPlatform/board/blob/master/server/php/config.inc.php#L15 and check the network tab in chrome and attach the screenshot?

**Comment by stanleyliu1006** [comment]
Hi espantosdarren,

I have enable the debug mode to true, not sure why the api_explorer shows error like below:

https://emailmanagement.acfonline.org.au/client/api_explorer/


![image](https://cloud.githubusercontent.com/assets/6980917/13837556/8c1fc708-ec60-11e5-81f0-58e83a0c2276.png)

**Comment by stanleyliu1006** [comment]
And I have re-configure my Nginx.conf as below, but the same error still shows up.

server {
        listen       443 ssl;
        server_name  emailmanagement.acfonline.org.au;
        root C:/WPN-XM/server/www/restyaboard;
        ssl                  on;
        ssl_certificate      C:\Certs\acfonline.org.au_Wildcard.crt;
        ssl_certificate_key  C:\Certs\acfonline.org.au_Wildcard_key.pem;
    
    
        ssl_session_timeout  5m;
        ssl_session_cache    shared:SSL:50m;
        ssl_protocols              TLSv1.1 TLSv1.2;
	ssl_prefer_server_ciphers  on;
    #   ssl_ciphers                HIGH:!aNULL:!MD5;
    	ssl_ciphers "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4:!SEED";
#	ssl_ciphers EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH RSA+AESGCM RSA+AES !RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS;
	#
    #    HSTS
    #     add_header Strict-Transport-Security max-age=15768000;
    #
    #    OCSP Stapling ---
    #    fetch OCSP records from URL in ssl_certificate and cache them
         ssl_stapling on;
    	ssl_trusted_certificate C:\Certs\geotrust_ssl_ca_g2.crt;
    #     ssl_stapling_verify on;
    
    #    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9100
    #    #
 index  index.html index.php index.htm;

	gzip on;
	gzip_disable "msie6";

	gzip_comp_level 6;
	# gzip_comp_level 9;
	gzip_min_length  1100;
	gzip_buffers 16 8k;
	gzip_proxied any;
	# gzip_http_version 1.1;
	gzip_types       text/plain application/xml text/css text/js text/xml application/x-javascript text/javascript application/json application/xml+rss;

	client_max_body_size 300M;

	rewrite ^/oauth/authorize$ /server/php/authorize.php last;
	rewrite ^/oauth_callback/([a-zA-Z0-9_\.]*)/([a-zA-Z0-9_\.]*)$ /server/php/oauth_callback.php?plugin=$1&code=$2 last;
	rewrite ^/download/([0-9]*)/([a-zA-Z0-9_\.]*)$ /server/php/download.php?id=$1&hash=$2 last;
	rewrite ^/ical/([0-9]*)/([a-z0-9]*).ics$ /server/php/ical.php?id=$1&hash=$2 last;
	rewrite ^/api/(.*)$ /server/php/R/r.php?_url=$1&$args last;
	rewrite ^/api_explorer/api-docs/$ /client/api_explorer/api-docs/index.php last;


	location / {
		root C:/WPN-XM/server/www/restyaboard;
	}	

	location ~ \.php$ {
		try_files $uri =404;
		include fastcgi_params;
		fastcgi_pass	php;
		fastcgi_index   index.php;
		fastcgi_param	SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PHP_VALUE "upload_max_filesize = 300M \n post_max_size=301M";
	}

	location ~* \.(css|js|less|html|ttf|woff|jpg|jpeg|gif|png|bmp|ico) {
		root C:/WPN-XM/server/www/restyaboard;
		if (-f $request_filename) {
			break;
		}
		rewrite ^/img/([a-zA-Z_]*)/([a-zA-Z_]*)/([a-zA-Z0-9_\.]*)$ /server/php/R/image.php?size=$1&model=$2&filename=$3 last;
		add_header        Cache-Control public;
		add_header        Cache-Control must-revalidate;
		expires           7d;
	}
     }

**Comment by ssivachidambaram** [comment]
Update your root folder upto `client` folder in the below mentioned places. Please refer,
https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf#L29
https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf#L42

And then access the URL without `client` like https://emailmanagement.acfonline.org.au/api_explorer/

**Comment by stanleyliu1006** [comment]
Thanks ssivachidambaram , the /api_explorer is getting back. But the api call stills stuck as the diagram below:

I have enabled the debug mode in the config file, but no errors throws out.

![image](https://cloud.githubusercontent.com/assets/6980917/13838416/08d062a6-ec68-11e5-844c-254c30da911b.png)


 */
define('R_DEBUG', true);
ini_set('display_errors', R_DEBUG);
define('R_API_VERSION', 1);
if (!defined('JSON_PRETTY_PRINT')) {
    define('JSON_PRETTY_PRINT', 128);
}
define('APP_PATH', dirname(dirname(dirname(__FILE__))));
// While changing below oAuth credentials, have to update in oauth_clients table also.
if (isset($_SERVER['PHP_AUTH_USER']) && isset($_SERVER['PHP_AUTH_PW'])) {
    define('OAUTH_CLIENTID', $_SERVER['PHP_AUTH_USER']);
    define('OAUTH_CLIENT_SECRET', $_SERVER['PHP_AUTH_PW']);
} else {
    define('OAUTH_CLIENTID', '7742632501382313');
    define('OAUTH_CLIENT_SECRET', '4g7C4l1Y2b0S6a7L8c1E7B3K0e');
}
$default_timezone = 'Europe/Berlin';
if (ini_get('date.timezone')) {
    $default_timezone = ini_get('date.timezone');
}
date_default_timezone_set($default_timezone);
define('R_DB_HOST', 'localhost');
define('R_DB_USER', 'restya');
define('R_DB_PASSWORD', 'hjVl2!rGd');
define('R_DB_NAME', 'restyaboard');
define('R_DB_PORT', 5432);
define('SECURITYSALT', 'e9a556134534545ab47c6c81c14f06c0b8sdfsdf');
if (!file_exists(APP_PATH . '/tmp/cache/site_url_for_shell.php')) {
    $fh = fopen(APP_PATH . '/tmp/cache/site_url_for_shell.php', 'a');
    fwrite($fh, '<?php' . "\n");
    fwrite($fh, '$_server_domain_url = \'' . $_server_domain_url . '\';');
    fclose($fh);
}
$db_lnk = pg_connect('host=' . R_DB_HOST . ' port=' . R_DB_PORT . ' dbname=' . R_DB_NAME . ' user=' . R_DB_USER . ' password=' . R_DB_PASSWORD . ' options=--client_encoding=UTF8') or die('Database could not connect');
$settings = pg_query_params($db_lnk, 'SELECT name, value FROM settings WHERE setting_category_id in (1,2,3,10) OR setting_category_parent_id in (1,2,3)', array());
while ($setting = pg_fetch_assoc($settings)) {
    if ($setting['name'] == 'LDAP_LOGIN_ENABLED' || $setting['name'] == 'STANDARD_LOGIN_ENABLED') {
        $setting_array = array(
            'true'
        );
        $setting_val = strtolower($setting['value']);
        $setting['value'] = (in_array($setting_val, $setting_array)) ? true : false;
    }
    define($setting['name'], $setting['value']);
}
$thumbsizes = array(
    'User' => array(
        'micro_thumb' => '16x16',
        'small_thumb' => '32x32',
        'normal_thumb' => '64x64',
        'medium_thumb' => '153x153'
    ) ,
    'Organization' => array(
        'medium_thumb' => '153x153',
        'small_thumb' => '32x32'
    ) ,
    'Board' => array(
        'micro_thumb' => '16x16',
        'small_thumb' => '32x32',
        'medium_thumb' => '153x153',
        'extra_large_thumb' => '2000x1263'
    ) ,
    'CardAttachment' => array(
        'small_thumb' => '108x78',
        'medium_thumb' => '153x153',
        'large_thumb' => '202x151'
    )
);
$aspect['CardAttachment']['large_thumb'] = 1;

**Comment by stanleyliu1006** [comment]
There's only some access logs as below:

192.168.80.91 - - [17/Mar/2016:17:49:05 +1100] "GET /api_explorer/lib/marked.js HTTP/1.1" 304 0 "https://emailmanagement.acfonline.org.au/api_explorer/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"
192.168.80.91 - - [17/Mar/2016:17:49:05 +1100] "GET /api_explorer/lib/highlight.7.3.pack.js HTTP/1.1" 304 0 "https://emailmanagement.acfonline.org.au/api_explorer/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"
192.168.80.91 - - [17/Mar/2016:17:49:05 +1100] "GET /api_explorer/lib/jsoneditor.min.js HTTP/1.1" 304 0 "https://emailmanagement.acfonline.org.au/api_explorer/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"
192.168.80.91 - - [17/Mar/2016:17:49:05 +1100] "GET /api_explorer/lib/swagger-oauth.js HTTP/1.1" 304 0 "https://emailmanagement.acfonline.org.au/api_explorer/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"
192.168.80.91 - - [17/Mar/2016:17:49:05 +1100] "GET /api_explorer/css/print.css HTTP/1.1" 304 0 "https://emailmanagement.acfonline.org.au/api_explorer/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"
192.168.80.91 - - [17/Mar/2016:17:49:05 +1100] "GET /api_explorer/images/logo_small.png HTTP/1.1" 304 0 "https://emailmanagement.acfonline.org.au/api_explorer/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"
192.168.80.91 - - [17/Mar/2016:17:49:05 +1100] "GET /api_explorer/api.json HTTP/1.1" 304 0 "https://emailmanagement.acfonline.org.au/api_explorer/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"
192.168.80.91 - - [17/Mar/2016:17:49:06 +1100] "GET /api_explorer/images/favicon-16x16.png HTTP/1.1" 200 645 "https://emailmanagement.acfonline.org.au/api_explorer/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"
172.16.1.253 - - [17/Mar/2016:17:49:06 +1100] "GET /api/v1/users/1/activities.json?type=all&last_activity_id=563&token=0e861369d9721cc9df3af010bbfaa8b4b80fb715&_=1458197345864 HTTP/1.1" 200 116 "https://emailmanagement.acfonline.org.au/client/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"

**Comment by ssivachidambaram** [comment]
Can you please change the below code in this line and try?

https://github.com/RestyaPlatform/board/blob/master/api_explorer/index.html#L31

url = "/api_explorer/api.json";

=>

url = "https://emailmanagement.acfonline.org.au/api_explorer/api.json";

**Comment by ssivachidambaram** [comment]
Also change `http` to `https` in `api.json` file in this line https://github.com/RestyaPlatform/board/blob/master/api_explorer/api.json#L4489

**Comment by rrjanbiah** [comment]
@stanleyliu1006 The issue was that `http` API requests failed to get called when loaded in `https`. So, please check if above fixes work for you. 

I have opened a separate ticket for this #485

**Comment by stanleyliu1006** [comment]
Hi Guys

It has been fixed now, thanks so much.
