### ISSUE TITLE
Failed to load resource: the server responded with a status of 401 (Authentication failed)

### ISSUE THREAD

**Issue by edouard-lopez** [RestyaPlatform/board#487]
After registering as a new user, I received the validation email but can't authenticate. 

### Request 

    http://x.x.x.x:1234/api/v1/users/8/activation.json?token=150af9f862e50131762d1770d11f1aa611f0baea

###  Error 

I got from console log

    Failed to load resource: the server responded with a status of 401 (Authentication failed)

**Comment by ssivachidambaram** [comment]
Sorry for the trouble. We are working on it and will update you shortly.

**Comment by ssivachidambaram** [comment]
We have fixed this in dev branch. You can update the `r.php` file with changes mentioned here https://github.com/RestyaPlatform/board/pull/489/files.
