### ISSUE TITLE
Warning: pg_query_params(): Query failed: ERROR:  bind message supplies 1 parameters

### ISSUE THREAD

**Issue by meganathans** [RestyaPlatform/board#500]
Warning: pg_query_params(): Query failed: ERROR:  bind message supplies 1 parameters, but prepared statement "" requires 0 in /home/boardd/html/server/php/R/r.php on line 888
Warning: pg_fetch_object() expects parameter 1 to be resource, boolean given in /home/boardd/html/server/php/R/r.php on line 889
Notice: Trying to get property of non-object in /home/boardd/html/server/php/R/r.php on line 892
Notice: Trying to get property of non-object in /home/boardd/html/server/php/R/r.php on line 893
Notice: Trying to get property of non-object in /home/boardd/html/server/php/R/r.php on line 893
Notice: Trying to get property of non-object in /home/boardd/html/server/php/R/r.php on line 896

**Comment by ssivachidambaram** [comment]
Fixed.
