### ISSUE TITLE
Install Restya Board on Windows

### ISSUE THREAD

**Issue by GitterHubber** [RestyaPlatform/board#509]
Is there any  installation guide to install Restya Board on Windows?

**Comment by rrjanbiah** [comment]
@GitterHubber You may try https://github.com/RestyaPlatform/board/issues/224#issuecomment-184282834 Please note that the attached files are outdated now

**Comment by rrjanbiah** [comment]
@GitterHubber Were you able to get it installed?

**Comment by GitterHubber** [comment]
Sorry for the late reply! Haven't had the time yet to start the whole 
process. Will possibly try it out over the weekend.
Many Thanks.

**Comment by rrjanbiah** [comment]
@GitterHubber No problem. Please let us know how it goes.

Closing this for now. If you get any issues, please feel free to reopen.

**Comment by GitterHubber** [comment]
Hello again.
I successfully installed restyaboard however when I visit localhost:8084 in a browser it says unable to connect any idea what would be going wrong.

During installation i faced a few issues, documenting them here so other's can refer to it later.
I downloaded  [WPNXM-0.8.6-Full-Setup-php56-w64.exe](https://github.com/WPN-XM/WPN-XM/releases/tag/v0.8.6) and installed it during the end of installating it said 

**`msvcr120.dll is missing and you would need to reinstall the app again`**

For this i had to install 

**`VC++ 2013 runtime 64 bit`**

After that i clicked the start button on the WPN XM control panel hower `nginx `failed to start

**Comment by ghstshdw** [comment]
im also running into the same problem

**Comment by rrjanbiah** [comment]
@GitterHubber Looks like we missed your reply. So reopening it.

**Comment by rrjanbiah** [comment]
@ghstshdw What exact issue are you facing? Can you attach some screenshots or so?

**Comment by GitterHubber** [comment]
I was facing 3 issues 
1. Restya not connecting to local server from browser
2. Images not displaying
3. Timeline showing squished.
If i remember correctly I could solve 1 and 2 but  couldn't manage 3.

Solutions
1. set 'always_populate_raw_post_data' to '-1'. (see stanleyliu1006 [comment](https://github.com/RestyaPlatform/board/issues/224#issuecomment-184898987)
2. had to change restyaboard.conf line 43 from
`rewrite ^/img/([a-zA-Z_]*)/([a-zA-Z_]*)/([a-zA-Z0-9_\.]*)$ /server/php/R/image.php?size=$1&model=$2&filename=$3 last;` to
`rewrite ^/img/([a-zA-Z_]*)/([a-zA-Z_]*)/([a-zA-Z0-9_\.]*)$ /server/php/image.php?size=$1&model=$2&filename=$3 last;`
3. No solution found.

**Comment by rrjanbiah** [comment]
@GitterHubber Thanks for your helpful notes. We'll check and reply.

**Comment by ssivachidambaram** [comment]
@GitterHubber Can you please check this issue #433 and confirm that you are also mentioning the same issue?

**Comment by ghstshdw** [comment]
@rrjanbiah @ssivachidambaram i followed all the steps in issue #443 and executed them without errors but still the site couldn't be reached 
![forgithub](https://cloud.githubusercontent.com/assets/8027947/15324969/4f5abe9c-1c51-11e6-9241-6f27863a22fd.PNG)

**Comment by GitterHubber** [comment]
On 5/17/2016 3:36 PM, S. Sivachidambaram wrote:
>
> @GitterHubber <https://github.com/GitterHubber> Can you please check 
> this issue #433 <https://github.com/RestyaPlatform/board/issues/433> 
> and confirm that you are also mentioning the same issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/RestyaPlatform/board/issues/509#issuecomment-219674521>
>
Have been busy lately will find some time over the weekend and check it out.

**Comment by rrjanbiah** [comment]
@GitterHubber 

> Have been busy lately will find some time over the weekend and check it out.

No problem. Please take your time.

**Comment by rrjanbiah** [comment]
@ghstshdw

> i followed all the steps in issue #443 and executed them without errors but still the site couldn't be reached 

It is most likely that your nginx has not started. Can you please double check that?

**Comment by lmarikannan** [comment]
@ghstshdw We are waiting for your reply

**Comment by ghstshdw** [comment]
my nginx has started i double checked severally

**Comment by ghstshdw** [comment]
@rrjanbiah my bad i took long to reply

**Comment by rrjanbiah** [comment]
@ghstshdw No problem. But, unfortunately, we're out of idea, why you're not getting output when nginx is up. Probably, your nginx is on a different port?

FWIW, you may also try http://stackoverflow.com/questions/21524373/nginx-connect-failed-111-connection-refused-while-connecting-to-upstream and share your feedback. But, it may not be the case.

**Comment by lmarikannan** [comment]
@ghstshdw We are waiting for your reply

**Comment by lmarikannan** [comment]
@ghstshdw  Closing this for now. If you get any issues, please feel free to reopen.
