### ISSUE TITLE
API to post checklist and items

### ISSUE THREAD

**Issue by stanleyliu1006** [RestyaPlatform/board#511]
Hi Guys

I am trying to use the API to insert the checklist and checklist items in my own customized code, but is there a way to get the checklist id from api or any method after post a new checklist, because I am using it for the checklistitem post api (used as input parameter), similar concept to the lastinsertid in the DB function.

It would be best to return the id of each post API operation, which can be used for the next post or put operation.

Regards
Stanley

**Comment by ssivachidambaram** [comment]
We have tested checklist add via API explorer and the id of the checklist is returning in response. Please find the attached screenshot.

![checklist_add](https://cloud.githubusercontent.com/assets/91407/13943498/f3e1c54c-f022-11e5-84d2-d9d48cfff8ec.png)

**Comment by rrjanbiah** [comment]
@stanleyliu1006 Are you expecting anything else? Or, is your setup showing different behavior than expected?

**Comment by stanleyliu1006** [comment]
thanks guys, the issue is fixed, please close this ticket

**Comment by ssivachidambaram** [comment]
Thanks for confirming.

**Comment by rrjanbiah** [comment]
@stanleyliu1006 

> thanks guys, the issue is fixed, please close this ticket

If possible, can you please share information on what fixed or caused this?
