### ISSUE TITLE
advanced LDAP account filter

### ISSUE THREAD

**Issue by Mad-Onion** [RestyaPlatform/board#512]
Hi everyone,

we would like to filter for a user's group-membership on ldap-login. In another php-based software we use filters like `(&(objectClass=user)(memberOf=CN=foo,OU=groups,dc=bar,dc=baz))`. In restya, those filters produce errors:

```
ldap_search(): Search: Bad search filter in /srv/www/restyaboard/server/php/libs/core.php on line 467
ldap_get_entries() expects parameter 2 to be resource, boolean given in /srv/www/restyaboard/server/php/libs/core.php on line 468
```

Should these kind of filters work?

**Comment by rrjanbiah** [comment]
@Mad-Onion I think, `memberOf` is not supported natively in PHP. If you can mention that software name, it will help us to compare (Probably they could have used different LDAP implementation)

**Comment by Mad-Onion** [comment]
@rrjanbiah `memberOf` is an ActiveDirectory-attribute showing group-membership from an object's point of view. 
The application is closed-source, but also written in php.

**Comment by rrjanbiah** [comment]
@Mad-Onion Thanks for your note. We'll see what we can do here.

**Comment by Mad-Onion** [comment]
@rrjanbiah I would prefer a text-input where I can enter a completely custom filter-string (and access the username via a variable) which is passed 1:1 to the server.
So you are flexible and can use any ldap-server you want: AD, OpenLDAP, ...

**Comment by rrjanbiah** [comment]
@Mad-Onion 

> access the username via a variable

> So you are flexible and can use any ldap-server you want: AD, OpenLDAP,

Sorry, these 2 points are not clear. Can you please consider rephrasing or add examples?

**Comment by Mad-Onion** [comment]
I'd prefer an input-field in the LDAP-setting where I can enter something like this: `(&(objectClass=user)(sAMAccountName=$username)(memberOf=CN=foo,OU=groups,dc=bar,dc=baz))`.
`$username` will be replaced by the username entered in the login-form and the whole string will be passed as the filter to the LDAP-server.
I hope this is better to understand :)

**Comment by rrjanbiah** [comment]
@Mad-Onion Yes, thank you.

**Comment by lmarikannan** [comment]
Fixed on this commit https://github.com/RestyaPlatform/board/pull/1128/commits/ee265f7329b8d0a3db62a55175e670292d7d8a48.
