### ISSUE TITLE
Organization Permissions

### ISSUE THREAD

**Issue by thesourcer** [RestyaPlatform/board#518]
I love what you have done with Restyaboard so far!  However, as I am trying to configure it for use within an organization, I still am not able to get around certain issues.  Before v0.2.0 was published, I downloaded v0.1.6, but boards which had organization scope were unaccessible by organization members.  

With v0.2.1 (what I am running now), this problem is resolved, but there is a new problem with too much access.  If I set all organization members to have only "viewer" status, and revoke all permissions to edit/add/delete boards or lists, but leave those permissions enabled for "editors" (even though in reality there are no users in my system with editor status), then the organization members are still able to edit/add/delete lists.  However, if I remove the permissions for "editors" to be able to edit/add/delete lists also, then the organization members can no longer make those changes.

It seems that somehow any "user" in the system is being automatically given "editor" status within the organization, even if I explicitly set them to only have "viewer" status.  Is this intentional?  If so, the layout of the "Roles" page is rather unclear, since it seems to be saying that you can give a user any editor/owner/viewer status.  Ideally, I really need to have some organization members able to edit, while others should not, so removing all editor permissions as I did above is not a viable option.  

If you have any thoughts on what might be causing this issue, or how I could configure it so that some users can make edits while others are truly only "viewers" it would be greatly appreciated.

Thanks and keep up the good work!

**Comment by rrjanbiah** [comment]
@thesourcer Thanks a lot for your report. We'll check and update you on that.

**Comment by ssivachidambaram** [comment]
@thesourcer Currently a member can different roles in organization and board. So can you please check member permission in board like mentioned in the attached screenshot?

![board-member-permission](https://cloud.githubusercontent.com/assets/91407/14014199/1a5cb53c-f1d7-11e5-9d6e-70bd7ab79c25.png)

**Comment by ssivachidambaram** [comment]
Currently we are closing this. If you have any feedback/issues, please feel free to reopen.
