### ISSUE TITLE
Comments are not shown when moving a card to another list 

### ISSUE THREAD

**Issue by lhooge** [RestyaPlatform/board#522]
Hi,

I've tried to add some comments to a card, when moving this card to another list the comments are not shown anymore. It seems that the listid in the activities table is not updated.

**Comment by rrjanbiah** [comment]
@lhooge Thanks for reporting this critical issue. We'll fix it as soon as possible.

Does it happen always? If so, can you please share more information about your setup? (if this is upgraded from previous version or setup latest version?)

**Comment by lhooge** [comment]
@rrjanbiah I've updated from 0.16 to 0.21 (manual). PHP version is 5.5.9 (from Ubuntu 14.04 It's always reproducable. If you need more information, please let me know.

**Comment by lhooge** [comment]
Here is the request, if I move the card to the list with id 206 (seems to be sent correctly): 

PUT /api/v1/boards/3/lists/205/cards/47.json?token={{token}}
   - {"list_id":206,"position":1}

```
{
   "activity":{
      "id":"564",
      "created":"24-MAR-16 10:22:55.205",
      "modified":"24-MAR-16 10:22:55.205",
      "board_id":"3",
      "list_id":"206",
      "card_id":"47",
      "user_id":"1",
      "foreign_id":"47",
      "type":"change_card_position",
      "comment":"##USER_NAME## moved this card ##CARD_LINK## from Todo list to Doing.",
      "revisions":"a:2:{s:9:\"old_value\";a:2:{s:7:\"list_id\";s:3:\"205\";s:8:\"position\";s:1:\"1\";}s:9:\"new_value\";a:1:{s:7:\"list_id\";i:206;}}",
      "root":"0",
      "freshness_ts":"24-MAR-16 10:07:57",
      "depth":"0",
      "path":"P564",
      "materialized_path":"000000fo",
      "board_name":"Testboard",
      "list_name":"Doing",
      "card_name":"test",
      "username":"admin",
      "full_name":"New Admin",
      "profile_picture_path":"media\/User\/1\/test.jpg",
      "initials":"PA",
      "label_name":null,
      "card_description":null,
      "user_role_id":"1",
      "checklist_item_name":null,
      "checklist_item_parent_name":null,
      "checklist_name":null,
      "organization_id":null,
      "organization_name":null,
      "organization_logo_url":null,
      "difference":[
         "<del>205<\/del><ins>206<\/ins>"
      ]
   }
}
```

**Comment by ssivachidambaram** [comment]
@lhooge Thanks for your detailed explanation. We have fixed this in our dev branch and you can update `r.php` changes from this pull request https://github.com/RestyaPlatform/board/pull/527/files.

**Comment by lhooge** [comment]
@ssivachidambaram Thanks for providing the patch. Unfortunately I'm not able to see the comments when moving the card to another list. Is there somewhere I can add some logging?

**Comment by ssivachidambaram** [comment]
@lhooge Sorry for the trouble. Can you please update the below two changes as well?

1. https://github.com/RestyaPlatform/board/commit/3d46b0e49aef6ddfd47bc65662ee7750d6051abe
2. https://github.com/RestyaPlatform/board/commit/c421b33e214b12c03857674a8366355477bb8c93

**Comment by lhooge** [comment]
@ssivachidambaram Thanks for your help! I can see the comments now.
