### ISSUE TITLE
Can't open board with a card that contains a due date in firefox

### ISSUE THREAD

**Issue by lhooge** [RestyaPlatform/board#525]
If I add a card and set for this card a due date I can't open the board in Firefox 45.0.1 (Restyaboard version: 0.2.1). Google Chrome is working fine.

This one is thrown in the developer console: 

> SyntaxError: invalid date
> 	
> ...Date(new_date):new Date,isNaN(e))throw SyntaxError("invalid date");f=String(h.ma...
> 	
> default...c8c3.js (Zeile 19, Spalte 15405)

**Comment by ssivachidambaram** [comment]
Related to #433. We couldn't reproduce the environment here. So we have updated with common workaround for all machines in our `dev` version.
