### ISSUE TITLE
Problem upgrading

### ISSUE THREAD

**Issue by skonvols2k** [RestyaPlatform/board#530]
Hi,
upgrading from 0.1.6 to 0.2.1 i have this error:
psql:/usr/share/nginx/html/restyaboard/sql/v0.2.1.sql:95: ERROR:  column boards_users.board_user_role_id does not exist
LINE 51:                     boards_users.board_user_role_id,
                             
can you please help?
Thanks

**Comment by ssivachidambaram** [comment]
Can you please update the below SQL manually to upgrade database 0.1.6 to 0.2?

https://github.com/RestyaPlatform/board/blob/master/sql/upgrade-0.1.6-0.2.sql

**Comment by skonvols2k** [comment]
Hi,
i executed upgrade 0.1.6-0.2 than upgrade with script than execute 0.2-0.2.1 script too.
the board is working but every attachment to cards i try to open give me 404.
Please help
Thanks

**Comment by ssivachidambaram** [comment]
Can you please check/update nginx configuration from line 21 to 26?
https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf#L21

**Comment by skonvols2k** [comment]
Hi,
i installed the nginx configuration indicated but nothing changed: portal
works but download of the attachment doesn't.

i do: tail -f /var/log/php-fpm/*.log /var/log/nginx/*.log but i can't any
error.

Thanks

---------------------------------------
Marco Sommella
marco.sommella@gmail.com
---------------------------------------

2016-03-25 7:42 GMT+01:00 S. Sivachidambaram <notifications@github.com>:

**Comment by ssivachidambaram** [comment]
Can you please send the attachment download URL to check generated hash are correct?

**Comment by skonvols2k** [comment]
http://board.myserver.it/download/309/44ffb95c6c45ce91adb61c0943c01305
thanks

---------------------------------------
Marco Sommella
marco.sommella@gmail.com
---------------------------------------

2016-03-25 12:07 GMT+01:00 S. Sivachidambaram <notifications@github.com>:

**Comment by ssivachidambaram** [comment]
Hash are correct. Actually we have changed `R` folder structure and moved all files to `php` folder. Can you please check once again the nginx configuration without `R` folder like this `/server/php/download.php?id=$1&hash=$2`? Also if possible post your nginx configuration too.

**Comment by skonvols2k** [comment]
Hi,
there was indeed a R folder i moved everything up one level so now i have:
[root@board php]# pwd
/usr/share/nginx/html/server/php
[root@board php]# ls
config.inc.php  download.php  ical.php  image.php  libs  README.md  r.php
shell

now the board doesn't works !!!

my nginx conf is below, i notice that in config there are refence to files
which are missing in my folder (for ex. authorize.php) should i copy those
from github?

server {
        listen 80;
        server_name "board.myserver.it";

        root /usr/share/nginx/html;
        index  index.html index.php;

        gzip on;
        gzip_disable "msie6";

        gzip_comp_level 6;
        # gzip_comp_level 9;
        gzip_min_length  1100;
        gzip_buffers 16 8k;
        gzip_proxied any;
        # gzip_http_version 1.1;
        gzip_types       text/plain application/xml text/css text/js
text/xml application/x-javascript text/javascript application/json
application/xml+rss;

        client_max_body_size 300M;

        rewrite ^/oauth/authorize$ /server/php/authorize.php last;
        rewrite ^/oauth_callback/([a-zA-Z0-9_\.]*)/([a-zA-Z0-9_\.]*)$
/server/php/oauth_callback.php?plugin=$1&code=$2 last;
        rewrite ^/download/([0-9]*)/([a-zA-Z0-9_\.]*)$
/server/php/download.php?id=$1&hash=$2 last;
        rewrite ^/ical/([0-9]*)/([a-z0-9]*).ics$
/server/php/ical.php?id=$1&hash=$2 last;
        rewrite ^/api/(.*)$ /server/php/R/r.php?_url=$1&$args last;
        rewrite ^/api_explorer/api-docs/$
/client/api_explorer/api-docs/index.php last;

        location / {
                root /usr/share/nginx/html/client;
        }

        location ~ \.php$ {
                try_files $uri =404;
                include fastcgi_params;
                fastcgi_pass    unix:/var/run/php5-fpm.sock;
                fastcgi_index   index.php;
                fastcgi_param   SCRIPT_FILENAME
$document_root$fastcgi_script_name;
                fastcgi_param PHP_VALUE "upload_max_filesize=9G \n
post_max_size=9G \n max_execution_time=200 \n max_input_time=200 \n
memory_limit=256M";
        }

        location ~* \.(css|js|less|html|ttf|woff|jpg|jpeg|gif|png|bmp|ico) {
                root /usr/share/nginx/html/client;
                if (-f $request_filename) {
                        break;
                }
                rewrite ^/img/([a-zA-Z_]*)/([a-zA-Z_]*)/([a-zA-Z0-9_\.]*)$
/server/php/image.php?size=$1&model=$2&filename=$3 last;
                add_header        Cache-Control public;
                add_header        Cache-Control must-revalidate;
                expires           7d;
        }
}

thanks

---------------------------------------
Marco Sommella
marco.sommella@gmail.com
---------------------------------------

2016-03-25 12:53 GMT+01:00 S. Sivachidambaram <notifications@github.com>:

**Comment by ssivachidambaram** [comment]
While upgrade those files will automatically update. Can you please upgrade files once again? Also in this `r.php` and `README.md` files should be inside `R` folder.

You can update it through shell script or download board-v0.2.1.zip from here https://github.com/RestyaPlatform/board/releases and update.

**Comment by skonvols2k** [comment]
Hi,
i done it again and everything works except the download of files when
filename contains spaces (i suppose - other download works fine).
For example:

http://board.myserver.it/download/308/757f3b2f592d455fb1ba3c13ed2b2262

SELECT * FROM "card_attachments" where id=308

id,created,modified,card_id,name,path,list_id,board_id,mimetype,link
308,2016-02-04T13:20:23.545Z,2016-02-04T13:20:23.545Z,261,701_CPAT4504_REV
1 _011215_NOVI LIGURE.pdf,media/Card/200/701_CPAT4504_REV 1 _011215_NOVI
LIGURE.pdf,288,11,application/pdf,

[root@board 200]# pwd
/usr/share/nginx/html/media/Card/200
[root@board 200]# ll
total 864
-rw-r--r-- 1 apache apache 373916 Feb  4 14:20 411_Allegato A 4504-VG  NOVI
LIGURE.pdf
-rw-r--r-- 1 apache apache 506203 Feb  4 14:20 701_CPAT4504_REV 1
_011215_NOVI LIGURE.pdf


---------------------------------------
Marco Sommella
marco.sommella@gmail.com
---------------------------------------

2016-03-25 13:48 GMT+01:00 S. Sivachidambaram <notifications@github.com>:

**Comment by ssivachidambaram** [comment]
We have uploaded a sample pdf by the name provided by you and its working fine in our demo. Please refer http://board.demo.restya.com/#/board/62/card/862 (admin // restya)

**Comment by skonvols2k** [comment]
Hi,
some attachment didn't download, i just have a white page!
And i have another problem: the admin CP show only activities and boards
menu on top
Thanks

---------------------------------------
Marco Sommella
marco.sommella@gmail.com
---------------------------------------

2016-03-25 14:15 GMT+01:00 S. Sivachidambaram <notifications@github.com>:

**Comment by ssivachidambaram** [comment]
Can you please clear all browser cache or check in incognito/private window?

**Comment by skonvols2k** [comment]
indeed was a cache problem, thanks.

---------------------------------------
Marco Sommella
marco.sommella@gmail.com
---------------------------------------

2016-03-28 7:36 GMT+02:00 S. Sivachidambaram <notifications@github.com>:

**Comment by ssivachidambaram** [comment]
Is download attachment working or only admin CP menu is working?

**Comment by skonvols2k** [comment]
Hi,
only admin CP.

---------------------------------------
Marco Sommella
marco.sommella@gmail.com
---------------------------------------

2016-03-28 13:46 GMT+02:00 S. Sivachidambaram <notifications@github.com>:

**Comment by ssivachidambaram** [comment]
We cannot able to reproduce the issue. Can you please enable debug mode in this file https://github.com/RestyaPlatform/board/blob/master/server/php/config.inc.php#L15. and send the error message?

**Comment by skonvols2k** [comment]
Hi,
where error should be visualized?
in /var/log/php-fpm/www-error.log i found this, can be related?
[31-Mar-2016 12:59:09] PHP Warning:  pg_query_params(): Query failed:
ERROR:  invalid input syntax for integer: "6,7,8,10" in
/usr/share/nginx/html/server/php/libs/core.php on line 625
[31-Mar-2016 12:59:09] PHP Warning:  pg_num_rows() expects parameter 1 to
be resource, boolean given in
/usr/share/nginx/html/server/php/libs/core.php on line 626
[31-Mar-2016 12:59:12] PHP Warning:  pg_query_params(): Query failed:
ERROR:  invalid input syntax for integer: "6,7,8,10" in
/usr/share/nginx/html/server/php/libs/core.php on line 625
[31-Mar-2016 12:59:12] PHP Warning:  pg_num_rows() expects parameter 1 to
be resource, boolean given in
/usr/share/nginx/html/server/php/libs/core.php on line 626
[31-Mar-2016 13:44:30] PHP Warning:  pg_query_params(): Query failed:
ERROR:  invalid input syntax for integer: "5,12,18,11,21" in
/usr/share/nginx/html/server/php/libs/core.php on line 625
[31-Mar-2016 13:44:30] PHP Warning:  pg_num_rows() expects parameter 1 to
be resource, boolean given in
/usr/share/nginx/html/server/php/libs/core.php on line 626
[31-Mar-2016 16:50:53] PHP Warning:  pg_query_params(): Query failed:
ERROR:  invalid input syntax for integer: "6,7,8,10" in
/usr/share/nginx/html/server/php/libs/core.php on line 625
[31-Mar-2016 16:50:53] PHP Warning:  pg_num_rows() expects parameter 1 to
be resource, boolean given in
/usr/share/nginx/html/server/php/libs/core.php on line 626
[31-Mar-2016 17:23:08] PHP Warning:  pg_query_params(): Query failed:
ERROR:  invalid input syntax for integer: "5,12,18,11,21" in
/usr/share/nginx/html/server/php/libs/core.php on line 625
[31-Mar-2016 17:23:08] PHP Warning:  pg_num_rows() expects parameter 1 to
be resource, boolean given in
/usr/share/nginx/html/server/php/libs/core.php on line 626

Thanks

---------------------------------------
Marco Sommella
marco.sommella@gmail.com
---------------------------------------

2016-03-31 14:35 GMT+02:00 S. Sivachidambaram <notifications@github.com>:

**Comment by ssivachidambaram** [comment]
After enable debug mode access the attachment download URL http://board.myserver.it/download/308/757f3b2f592d455fb1ba3c13ed2b2262 and error will display in page.

**Comment by vince68** [comment]
I have the same error in log when I add a new card, error in /usr/share/nginx/html/server/php/libs/core.php on line 625

**Comment by skonvols2k** [comment]
Hi,
after setting debug mode to true, restart nginx and php-fpm services and
clean browser cache, opening the attach result in a white page, no errors
are shown.
Thanks a lot
Regards

---------------------------------------
Marco Sommella
marco.sommella@gmail.com
---------------------------------------

2016-04-01 12:25 GMT+02:00 S. Sivachidambaram <notifications@github.com>:

**Comment by ssivachidambaram** [comment]
We have fixed the PHP warnings logged in error log file. Please refer https://github.com/RestyaPlatform/board/commit/c64a2edc06ddf8716b52618c029bb0a043800989.
