### ISSUE TITLE
Source code customization

### ISSUE THREAD

**Issue by stanleyliu1006** [RestyaPlatform/board#558]
Hi Guys

Can you please advise how to customize the source code to add an external link in the card panel as shown in the diagram below:

![image](https://cloud.githubusercontent.com/assets/6980917/14128093/5237f9d0-f669-11e5-87e3-d5bf3295620e.png)

Kind regards
Stanley

**Comment by ssivachidambaram** [comment]
You can add links in this file https://github.com/RestyaPlatform/board/blob/master/client/js/templates/modal_card_view.jst.ejs#L213

**Comment by stanleyliu1006** [comment]
Hi ssivachidambaram 

Thanks for your reply, I am using the latest built package (not the source package) which does not contain the js file you mentioned. Does this mean I need to change the source code, re-build and upload the entire project to the server, can you use the source package instead of the built one?

![image](https://cloud.githubusercontent.com/assets/6980917/14164400/1b0b479a-f74b-11e5-80d1-99b37d81e912.png)

Regards
Stanley

**Comment by ssivachidambaram** [comment]
Yes. You have to rebuild and upload.

**Comment by stanleyliu1006** [comment]
Hi ssivachidambaram

Thanks so much for your reply, I follow the instruction above to modify the modal_card_view.jst file. and add the link in both line 213 and 216, and build the js and css file, and redeploy the project, but it still shows nothing on the card details panel.

The template file is attached below, already reboot the nginx, still not helpful, Please let me know if I miss some steps on the customization.

[modal_card_view.jst.zip](https://github.com/RestyaPlatform/board/files/201746/modal_card_view.jst.zip)


Regards
Stanley

**Comment by stanleyliu1006** [comment]
And when I check the source element after click F12 on the chrome, there shows nothing of my customization code. <a href> etc.

**Comment by ssivachidambaram** [comment]
Whether you have run this command `grunt build:live` to generate a zip file to upload?

**Comment by stanleyliu1006** [comment]
Hi ssivachidambaram

Yes I have done that step, as shown in the diagram below, is there any possible I can check it from the built files?

![image](https://cloud.githubusercontent.com/assets/6980917/14266902/0b245f34-fb0f-11e5-97c5-ff80a9e2081b.png)


Any advise would be appreciated.

Regards
Stanley

**Comment by ssivachidambaram** [comment]
While run build, a new file will created in this path `client/js/default.cache.xxxxx.js`. Can you please check whether the code available in that file?

**Comment by stanleyliu1006** [comment]
Hi ssivachidambaram

There are three default.cache.xxxxx.js , and two files have my external link code, as the file shows below, any ideas?

[default.cache.dc3bae19.zip](https://github.com/RestyaPlatform/board/files/203897/default.cache.dc3bae19.zip)

Kind regards
Stanley

**Comment by ssivachidambaram** [comment]
In `index.html` its pointing the old javascript `js/default.cache.d23b7dec.js` file.

**Comment by stanleyliu1006** [comment]
Hi ssiva

I think I am getting close, but when I update the index.html with the new js file as below, and clear the browser cache, it stills shows up the old js file, is there any way to clear the cache in the restyaboard?

<!DOCTYPE html><html class="no-js" lang="en" manifest="default.appcache"><head><meta charset="utf-8"><title>Restyaboard powered kanban board</title><meta name="description" content="Restyaboard powered kanban board. Download open source from http://restya.com/board/"><meta name="keywords" content="Restyaboard, http://restya.com/board/"><meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1"><link rel="manifest" href="manifest.json"><link href="//fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css"><link rel="stylesheet" href="css/default.cache.a4664637.css"><link id="favicon" rel="shortcut icon" href="favicon.ico"><link rel="apple-touch-icon" href="apple-touch-icon.png"><link rel="apple-touch-icon" sizes="72x72" href="apple-touch-icon-72x72.png"><link rel="apple-touch-icon" sizes="114x114" href="apple-touch-icon-114x114.png"></head><body style="cursor: auto"><div id="main" class="content"><div class="wrapper"><header id="header" class="clearfix"><span id="title"></span></header><main id="content" class="container-fluid"><div id="life"></div></main><div class="text-center"><a target="_blank" class="company hide" href="http://restya.com/board/?utm_source=Restyaboard&utm_medium=web&utm_campaign=login_footer" title="Open source. Trello like kanban board." rel="generator">Powered by Restyaboard</a></div></div><footer id="footer" class="navbar-fixed-bottom container-fluid footer"></footer></div><script>var api_url = '/api/v1/';
  var template_url = '/client/';</script><script>window.addEventListener('load', function(e){window.applicationCache.addEventListener('updateready', function(e){if (window.applicationCache.status == window.applicationCache.UPDATEREADY){window.applicationCache.swapCache();if (confirm('A new version of this site is available. Load it?')){window.location.reload();}}}, false);}, false);</script><script src="js/default.cache.dc3bae19.js"></script></body></html>


Regards
Stanley

**Comment by ssivachidambaram** [comment]
In `index.html` we have already written reload if any new application cache available. To clear application cache manually in chrome, run this `chrome://appcache-internals/` in new tab and remove item and clear browser cache as well.

**Comment by stanleyliu1006** [comment]
Hi ssivachidambaram

It works now, thanks.

Please close this ticket.

Regards
Stanley

**Comment by ssivachidambaram** [comment]
Thanks for confirming.
