### ISSUE TITLE
Forgot Password function broken (and possibly others)

### ISSUE THREAD

**Issue by zgambino** [RestyaPlatform/board#560]
As you can see in the demo (and I've seen it in my own install), if a user were to try and reset their password, nothing happens.

I've traced it down to a bad if statement in r.php.
When I fixed the logic, I was able to get my password reset email.

I'm not sure, but this issue could affect more API commands.

Attached is a patch file illustrating the change.
[r.php.patch.txt](https://github.com/RestyaPlatform/board/files/196744/r.php.patch.txt)

**Comment by ssivachidambaram** [comment]
Thanks for reporting and sorry for the trouble. We have fixed this in our dev branch.

Please refer,
https://github.com/RestyaPlatform/board/pull/489/files
https://github.com/RestyaPlatform/board/pull/524/files#diff-9812550cecc4e99d42faa21f771c0b8cR4661
