### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by farfeduc** [RestyaPlatform/board#57]
Hello, 

I might have done something bad but I just have a blank page when I check the url just after my install.

I run on nginx and I used : http://restya.com/board/install.html#selfhosted

Here is the url : http://myurl.com

thanks for your help

**Comment by rrjanbiah** [comment]
@farfeduc Currently http://board.girardeau.me/ is not loading (not getting blank screen). So, we can't able to understand what is going on.

Have you configured nginx with https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf ?

Once the page is loading and if you get blank screen, enable API debug mode https://github.com/RestyaPlatform/board/blob/master/server/php/R/config.inc.php#L15 so that we can check what is going on.

**Comment by farfeduc** [comment]
Thank you for your answer !
Yes, I have configured nginx with this config.

Here is a link to pastebin with my config : http://pastebin.com/TyWgCfz4

I've set the debugging mode but no luck there, nothing is printing on the page :-(

**Comment by rrjanbiah** [comment]
@farfeduc As the site is not returning anything, it is difficult to guess any issues. Can you check nginx log?

**Comment by farfeduc** [comment]
@rrjanbiah I have emptied the logs and retried to access the app. Here is what I get :

In the error log : 
```
2015/10/05 21:03:04 [error] 15046#0: *172 FastCGI sent in stderr: "PHP message: PHP Warning:  pg_last_error() expects parameter 1 to be resource, boolean given in /var/www/board/server/php/R/config.inc.php on line 40
PHP message: PHP Warning:  pg_query_params() expects parameter 1 to be resource, boolean given in /var/www/board/server/php/R/config.inc.php on line 42
PHP message: PHP Warning:  pg_fetch_assoc() expects parameter 1 to be resource, null given in /var/www/board/server/php/R/config.inc.php on line 43" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: board.girardeau.me, request: "GET /api/v1/oauth.json?_=xxxxxxxxxxx HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "board.girardeau.me", referrer: "http://board.girardeau.me/"```

**Comment by farfeduc** [comment]
I think I might have an issue with postgresql config in fact...

I installed it through the repositories (I'm on Debian Jessie).
Then I followed some webpage to create a user and a base.

Then I used "pgsql mydatabase < dump.sql" with each file in the right order.

Was there something else to do ? (In the configuration of PostgreSQL or something else ?)

**Comment by rrjanbiah** [comment]
@farfeduc The error shows that DB connection is failing. So, please double check your DB credentials https://github.com/RestyaPlatform/board/blob/master/server/php/R/config.inc.php#L32

**Comment by farfeduc** [comment]
Thanks ! Issue solved. The user I created did not had the possibility to "login".

I had to alter the role to add the capability to login. Now it's working.

@rrjanbiah  Could you change the url to my restyboard install in you comment above ? Thanks !

**Comment by rrjanbiah** [comment]
@farfeduc That's a good news :-)  Updated URL
