### ISSUE TITLE
option to disable freegeoip.net

### ISSUE THREAD

**Issue by oOHenry** [RestyaPlatform/board#570]
Hey Guys,

is it possible to disable freegeoip.org? The service is not online at the moment and my browser is loading and loading. 

Thanks :)

**Comment by ssivachidambaram** [comment]
You can remove the whole `if` block in this file https://github.com/RestyaPlatform/board/blob/master/client/js/common.js#L19 and rebuild files then deploy.

**Comment by ssivachidambaram** [comment]
In upcoming release, it will work with PHP built in function http://php.net/manual/en/book.geoip.php.
