### ISSUE TITLE
User activation not working

### ISSUE THREAD

**Issue by katiemacintyre** [RestyaPlatform/board#571]
Hi there,
Just done a fresh install of restyaboard using the install script, so far I can log into the admin panel using the default admin credentials and all seems to work fine. However, when trying to register a new user it all goes well until it comes to activating that user. The activation link brings up a blank Restyaboard screen with "Register" and "Login" at the top, neither of which do anything. Logging in as admin I can see the user is created and listed as unconfirmed and blocked, unblocking the user from here allows them to log in, so it looks like the user creation is working fine, just the user activation is struggling somewhere.
This is a completely clean build of Ubuntu 14.04 LTS, everything (nginx, postgres, postfix, php etc) was installed via the restyaboard install script. I've attached the install log, any light anyone can shed on it would be much appreciated.
[restyaboard_install.log.txt](https://github.com/RestyaPlatform/board/files/202182/restyaboard_install.log.txt)

**Comment by ssivachidambaram** [comment]
Sorry for the trouble. Related to #487. You can update the `r.php` file with changes mentioned here https://github.com/RestyaPlatform/board/pull/489/files.

**Comment by katiemacintyre** [comment]
Working perfectly now! Thanks very much!
