### ISSUE TITLE
gantt chart error

### ISSUE THREAD

**Issue by jwentwistle** [RestyaPlatform/board#576]
The date area resizes and displays: 

_NaN, undefined_

Then an error appears that says: 

_A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: http://localhost/js/default.cache.a331c8c3.js:25_

**Comment by rrjanbiah** [comment]
@jwentwistle Can you please mention your browser and Restyaboard version?

**Comment by jwentwistle** [comment]
Yeah, no problem.

Restyaboard version: v 0.2.1 (2016-03-16)
Firefox version: 45.0.1

**Comment by ssivachidambaram** [comment]
Related to #433.
