### ISSUE TITLE
LDAP TLS

### ISSUE THREAD

**Issue by didierm** [RestyaPlatform/board#577]
Am I right in assuming there are currently no provisions for LDAP with TLS ?
[http://php.net/manual/en/function.ldap-start-tls.php](url)

**Comment by rrjanbiah** [comment]
@didierm 

> Am I right in assuming there are currently no provisions for LDAP with TLS ?
> http://php.net/manual/en/function.ldap-start-tls.php

Yes, currently no. We do accept PR for that.

**Comment by lmarikannan** [comment]
@didierm Closing this for now. If you get any issues, please feel free to reopen.
