### ISSUE TITLE
Permission is not working properly.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#58]
Steps to reproduce:
--------------------------
1.Login as restya001 // testing
2.Create a board.
3.For that board add cards.
4.For any one card add member restya002.
5.Login to restya002 // testing
6.All the cards are displayed.
7.Click any card and add member restya001 (Owner).Its added.
8.Permission not working properly

Refer the attachment
![permission issue](https://cloud.githubusercontent.com/assets/14290356/10275215/5cd9fa5a-6b63-11e5-883a-7baec5f3b726.png)
![permission not working properly](https://cloud.githubusercontent.com/assets/14290356/10275216/5d2be496-6b63-11e5-8899-7e4d4a58964e.png)

**Comment by rrjanbiah** [comment]
Not an issue. In Trello also its working like this.
