### ISSUE TITLE
automated Login

### ISSUE THREAD

**Issue by carazzim0** [RestyaPlatform/board#581]
Hi guys,

first thing I noticed after setting up our own Restyaboard was, that I had login again after I closed my browser.

Is there already an implementation of a "remember me"-checkbox?

Could you otherwise consider implementing this function?

Thank you for your help :)

cheers,
carazzim0

**Comment by rrjanbiah** [comment]
@carazzim0 Thanks a lot for your suggestion. We'll see what we can do here.

**Comment by oOHenry** [comment]
+1 any updates on this ?

**Comment by lmarikannan** [comment]
Now the login data are stored in cookies, so the session will persist while reopen browser (if the cookies are not deleted on close browser).

**Comment by lmarikannan** [comment]
Refer #714.
