### ISSUE TITLE
SSL Connection in Docker

### ISSUE THREAD

**Issue by SilentHunter124** [RestyaPlatform/board#582]
I have no Idea how to secure this nginx inside a docker container with an ssl certificate. I tried editing the resyaboard.conf file with ssl on but it has no effect. How to do that?

**Comment by rrjanbiah** [comment]
@SilentHunter124 Docker version is kindly provided by @namikingsoft 

We don't have much expertise in Docker (and so, we planned to check Docker once all planned items are done). If you report it in https://github.com/namikingsoft/docker-restyaboard you may get better reply.

**Comment by lmarikannan** [comment]
Closing this for now. If you get any issues, please feel free to reopen.
