### ISSUE TITLE
Add cards via Email - imap not working?

### ISSUE THREAD

**Issue by darkree** [RestyaPlatform/board#583]
**Symptom**
Restyaboard is not successfully accessing an IMAP mailbox and/or consuming the email to a list/card/etc..

**Environment:**
- Fresh installation of Ubuntu 14.04 LTS
- Restyaboard Installed from the Restyaboard.sh
- IMAP mailbox is functional / accessible by mozilla thunderbird.
- Restyaboard seems to be functioning normally (adding cards, lists, boards).

**Tried**
and got the following result when manually running imap.sh:> sudo ./imap.sh
_2016-04-13 07:08:57 #################################################
successfully acquired lock: /usr/share/nginx/html/restyaboard/server/php/shell/imap_sh.lock
**IMAP PHP extension not available on this server. Bounced email functions will not work.**AAAA@ubuntu:/usr/share/nginx/html/restyaboard/server/php/shell$_

**Assumption**
The PHP IMAP module is not installed.
Tried to install PHP as directed by the following forum [ask ubuntu](http://askubuntu.com/questions/484921/php5-imap-on-ubunut-14-04-is-not-enabled).

- apt-get install php5-imap
- php5enmod imap

**sudo apt-get install php5-imap results in:**
_Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php5-imap : Depends: phpapi-20100525
             Depends: php5-common (= 5.4.45-0+deb7u2) but 5.5.9+dfsg-1ubuntu4.14 is to be installed
E: Unable to correct problems, you have held broken packages._

**When checking the Restyaboard_install.log** getting the same error:
_Setting up ttf-dejavu-core (2.34-1ubuntu1) ...
+ echo Checking PHP imap extension...
Checking PHP imap extension...
+ grep imap
+ php -m
+ [ 1 -gt 0 ]
+ echo Installing php5-imap...
Installing php5-imap...
+ apt-get install -y php5-imap
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php5-imap : Depends: phpapi-20100525
             Depends: php5-common (= 5.4.45-0+deb7u2) but 5.5.9+dfsg-1ubuntu4.14 is to be installed
E: Unable to correct problems, you have held broken packages._

**Tried** the accepted answer at [askubuntu](http://askubuntu.com/questions/540423/libapache2-mod-php5-depends-php5-common)

- sudo add-apt-repository --remove ppa:ondrej/php5-oldstable
- sudo add-apt-repository --remove ppa:ondrej/php5
- sudo add-apt-repository universe
- sudo add-apt-repository multiverse
- sudo apt-get update
- sudo apt-get install libapache2-mod-php5
- sudo apt-get remove php5 php5-common php5-mysql php5-xmlrpc php5-cgi php5-curl php5-gd php5-cli php5-fpm php-apc php-pear php5-dev php5-imap php5-mcrypt
- sudo apt-get install php5 php5-common php5-mysql php5-xmlrpc php5-cgi php5-curl php5-gd php

5-cli php5-fpm php-apc php-pear php5-dev php5-imap php5-mcrypt

with the same dependency error message.

Thank you for your attention to this.

**Comment by rrjanbiah** [comment]
@darkree Many thanks for your very helpful/detailed issue report. We'll look into it.

**Comment by ssivachidambaram** [comment]
If possible, please share your install log. (Please review the content of the file and remove any sensitive data like password, etc before posting here).

**Comment by darkree** [comment]
Please see attachment.
[restyaboard_install.txt](https://github.com/RestyaPlatform/board/files/223857/restyaboard_install.txt)

**Comment by rrjanbiah** [comment]
@ssivachidambaram For your attention...

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/0ad7f8f0938eb6ea9bc85ae9a2db67506821cc5f
