### ISSUE TITLE
registration not possible

### ISSUE THREAD

**Issue by Aendrew87** [RestyaPlatform/board#584]
i updated from 0.1.6 to 0.2.0 and then to 0.2.1.

Old users are still able to login but new users could not register.
In the access.log of nginx i found this:
> myip - - [13/Apr/2016:20:37:54 +0200] "PUT
/api/v1/users/60/activation.json?token=0a90b3bd753df525dba6bcaf10a147cd91212962
HTTP/1.1" 401 5 "https://myserver/" "Mozilla/5.0 (Windows NT 10.0; WOW64;
rv:45.0) Gecko/20100101 Firefox/45.0"

The '401' does not look good to me.

Any ideas how to solve it?

**Comment by rrjanbiah** [comment]
Probably duplicate of #560 and #571 (?)

@Aendrew87 Can you please confirm?

**Comment by Aendrew87** [comment]
**@rrjanbiah** yes, looks like that - i checked only the last tickets - i will tests and give you feedback

**Comment by Aendrew87** [comment]
great, it works - thanks a lot
