### ISSUE TITLE
Can't activate email

### ISSUE THREAD

**Issue by c4xp** [RestyaPlatform/board#589]
Hi guys,
Once registered, I received an email correctly:
http://foo.bar/#/users/activation/3/ad158e1a1d5796b3cdde2c40366fd268

But nothing happens (blank page with only header) [replaced my hostname with foo.bar and ip 1.2.3.4]

Nginx 2 Errors:
2016/04/19 14:56:17 [error] 21439#21439: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /foo/bar/server/php/R/r.php on line 4713" while reading response header from upstream, client: 1.2.3.4, server: foo.bar, request: "GET /api/v1/oauth.json?_=1461066804433 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "foo.bar", referrer: "http://foo.bar/"

2016/04/19 14:56:17 [error] 21439#21439: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /foo/bar/server/php/R/r.php on line 801" while reading response header from upstream, client: 1.2.3.4, server: foo.bar, request: "GET /api/v1/settings.json?token=795ef790d839391dbe17a15039272555a787a50f&_=1461066804529 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "foo.bar", referrer: "http://foo.bar/"

This is happening for version 0.2.1
Any advice?
Thanks

**Comment by ssivachidambaram** [comment]
Sorry for the trouble. Related to #487. You can update the `r.php` file with changes mentioned here https://github.com/RestyaPlatform/board/pull/489/files & https://github.com/RestyaPlatform/board/pull/524/files#diff-9812550cecc4e99d42faa21f771c0b8cR4661.

**Comment by c4xp** [comment]
Thank you :)
