### ISSUE TITLE
Displaying the username as a hover in member panel and profile name as a hover in notification panel

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#60]
1. Login as a user[rest01/testing]
2. In member panel=>> It display the username as a hover

Expected result:
In hover, it should display profile name.
![profile_name](https://cloud.githubusercontent.com/assets/14884895/10306988/899cf41c-6c48-11e5-9806-a6be1f122978.png)

**Comment by rrjanbiah** [comment]
fixed
