### ISSUE TITLE
(UI/UX) Search text-input bar should be visible by default

### ISSUE THREAD

**Issue by KerimG** [RestyaPlatform/board#602]
I don't understand why the search button at the bottom edge needs to be clicked to open up the text-input bar.

**Comment by rrjanbiah** [comment]
@KerimG Idea is to avoid page clutter. If you have any suggestions, please feel free to share.

**Comment by KerimG** [comment]
The bottom bar is there anyway, I don't think the text-input area (for the search) should need to be clicked visible via the magnifying glass button before searching. In the mobile version it's visible by default, that's perfect.

**Comment by lmarikannan** [comment]
@KerimG Thank you very much for your suggestion. We will consider this when we get more request for this UX changes.
