### ISSUE TITLE
(UI/UX) image viewer for attachements

### ISSUE THREAD

**Issue by KerimG** [RestyaPlatform/board#603]
Downloading the images before being able to open them is a bit of a nuisance.

**Comment by rrjanbiah** [comment]
@KerimG Thanks for your report. We will fix it ASAP

**Comment by KerimG** [comment]
Oh? I didn't know it was already  built-in. Awesome!

**Comment by ssivachidambaram** [comment]
Fixed to show in browser itself as separate tab instead of download.

**Comment by keky** [comment]
@ssivachidambaram Could u show me how to fix it, I am looking forward to the feature.

**Comment by ssivachidambaram** [comment]
Image preview will display in browser like like attached image.

![image-preview](https://cloud.githubusercontent.com/assets/91407/15208404/f82eb9cc-1848-11e6-964d-02d3a6916d40.png)

**Comment by keky** [comment]
In which version of restya can I use this feature? thx！

**Comment by rrjanbiah** [comment]
@keky This will be available in upcoming version. Code already pushed in `dev` branch.
