### ISSUE TITLE
(UI/UX) A button in the organization view to create organization boards would be great

### ISSUE THREAD

**Issue by KerimG** [RestyaPlatform/board#604]
I searched for quite a while until I figured out how to create an organization board, and I think if you look at the following [image](http://i.imgur.com/XW3ZpB8.png) showing the organizations list of the demo, you can see that other people are struggling with the same issue.

**Comment by lmarikannan** [comment]
@KerimG Sorry for the delayed response. We will implement this in our future version.

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/d9fe36a421f283a3dfe51ec3e4686db3d873c4f4
