### ISSUE TITLE
RestyaBoard button on bottom left should open "My Boards" view

### ISSUE THREAD

**Issue by KerimG** [RestyaPlatform/board#606]
I don't think anybody really cares enough about whatever tech has been used to create RestyaBoard for it to warrant a permanent button at such an important position. Instead why not place a button there that takes the user directly to their "My Boards" view?

**Comment by rrjanbiah** [comment]
@KerimG In that case where do you think that "About" link will be appropriate?

**Comment by d0dman** [comment]
While an About link is important, I have to agree with KerimG about the need for a "My Boards" button.  When inside a board there is no direct route back to "My Boards" except "Boards -> Boards" (which ocassionally does nothing - haven't been able to determine what steps lead to it not working).  Going back to "My Boards" is something that should be accomplished with a single click and be self evident (ie, the software logo, which almost universally means Home).  I believe the About section is usually listed with Help, so maybe a ? or something along that line would be more appropriate.

**Comment by rrjanbiah** [comment]
@d0dman Thanks a lot for your suggestion. Currently, we're also showing online/offline/sync status in the logo and so thought it would be ideal to lead it to "About" page. Anyway will definitely consider your feedback. Thanks

**Comment by lmarikannan** [comment]
Closing this for now.
