### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#608]
From Matthias Dietel in forum https://groups.google.com/forum/#!topic/restya/vlAYhEIKbW0 :

Is there an session timeout? Sometimes I get logged out after an indefinite time of inactivity.

**Comment by HatBeardZero** [comment]
I've been poking at PHP session timeout from an OS standpoint.  I know I run mine on Ubuntu.  I'm not wholly familiar with PHP but I wonder if this could be a thing?

[Session Timeout](https://solutionfactor.net/blog/2014/02/08/session-files-unexpectedly-deleted/)

**Comment by rrjanbiah** [comment]
@HatBeardZero Yes, we think it may be a browser thing as I'm getting in XP Chrome.

**Comment by ssivachidambaram** [comment]
Fixed.
