### ISSUE TITLE
Add a members to a card. if u click multiple times on members. its keep on duplicating the member names.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#61]
1. Login as user.
2. open a board which has more members,
3. Add 3 members in a card and click multiple times on members.
4. Its adding or duplicating the same member again and again.

Refer the attachment.
![member_duplicate](https://cloud.githubusercontent.com/assets/14884895/10307207/7f89fa7c-6c4a-11e5-9702-34fc1f657b23.png)

**Comment by rrjanbiah** [comment]
Fixed
