### ISSUE TITLE
Card history dissapairs when moved from one list to another

### ISSUE THREAD

**Issue by Zimeon-** [RestyaPlatform/board#611]
We've noticed a bug that removes any previous comments and actions from a card when it's moved from one list to another. When the card is moved back to it's original list, the comments and actions return to the card history.

**Comment by rrjanbiah** [comment]
@Zimeon- Welcome back!

I think, it is fixed already. Anyway, will check and fix them ASAP. Thanks for your report.

**Comment by ssivachidambaram** [comment]
Please refer #522. Can you please update the below changes in `r.php`?

1. https://github.com/RestyaPlatform/board/commit/3d46b0e49aef6ddfd47bc65662ee7750d6051abe
2. https://github.com/RestyaPlatform/board/commit/c421b33e214b12c03857674a8366355477bb8c93
3. https://github.com/RestyaPlatform/board/pull/527/files

**Comment by Zimeon-** [comment]
Hello,

sorry for not checking previously closed tickets, yes, this fixed the issue :) Glad to have an early fix ;)

**Comment by dfragac** [comment]
+1

Worked for me too.
