### ISSUE TITLE
Unable to save new card on new board

### ISSUE THREAD

**Issue by chrisurban** [RestyaPlatform/board#612]
Adding a card with Instant Add Card does not allow Save; instead the search window at top left opens, with either the project, or List as a search term.

Chrome 49

**Comment by rrjanbiah** [comment]
@chrisurban I can't seem to reproduce it in our demo. Are you able to reproduce it in your demo?

Also, can you please mention your version? Also, can you check it in incognito window?

**Comment by chrisurban** [comment]
Quit and restarted Chrome, and after logging back in was no longer able to reproduce.
