### ISSUE TITLE
unable to install restya properly on centos 7 with script 

### ISSUE THREAD

**Issue by tusharvanzara** [RestyaPlatform/board#616]
Unable to access link with 80 port, it might be some installation issue, i am attaching logs..kindly go through it and pls let me know. also tell me what could be changes in .sh file

and i think postgresql was not installed correctly
[restyaboard_install.txt](https://github.com/RestyaPlatform/board/files/240059/restyaboard_install.txt)

**Comment by rrjanbiah** [comment]
@tusharvanzara Can you please edit your description with your note and "attach" the install log as an attachment?

Quick look at above suggests that you may be using a system without internet connection to install Restyaboard as connection to restya.com seems to have failed.

**Comment by tusharvanzara** [comment]
I Did It.

-- 
Thanks & Regards,
Tushar Vanzara


On 04/28/2016 01:29 PM, R. Rajesh Jeba Anbiah wrote:
>
> @tusharvanzara <https://github.com/tusharvanzara> Can you please edit 
> your description with your note and "attach" the install log as an 
> attachment?
>
> Quick look at above suggests that you may be using a system without 
> internet connection to install Restyaboard as connection to restya.com 
> seems to have failed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/RestyaPlatform/board/issues/616#issuecomment-215340694>
>


This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email. Pandit Ventures Private Limited, 9th Floor, Sambhaav House, Judges Bunglow Cross Roads, Bodakdev, Ahmedabad-380015, Phone:0091-79-30215316

**Comment by rrjanbiah** [comment]
@tusharvanzara 

> Unable to access link with 80 port, it might be some installation issue, i am attaching logs..kindly go through it and pls let me know. also tell me what could be changes in .sh file

Possible guesses: you don't have internet connection for that machine or you have some firewall settings that is blocking access to restya.com. Can you please check if you can curl to other sites?

**Comment by tusharvanzara** [comment]
My internet is connected and its up.we are having some proxy settings 
but i don't think it might have occurred this issue.


-- 
Thanks & Regards,
Tushar Vanzara


On 04/28/2016 01:38 PM, R. Rajesh Jeba Anbiah wrote:
>
> @tusharvanzara <https://github.com/tusharvanzara>
>
>     Unable to access link with 80 port, it might be some installation
>     issue, i am attaching logs..kindly go through it and pls let me
>     know. also tell me what could be changes in .sh file
>
> Possible guesses: you don't have internet connection for that machine 
> or you have some firewall settings that is blocking access to 
> restya.com. Can you please check if you can curl to other sites?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/RestyaPlatform/board/issues/616#issuecomment-215342625>
>


This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email. Pandit Ventures Private Limited, 9th Floor, Sambhaav House, Judges Bunglow Cross Roads, Bodakdev, Ahmedabad-380015, Phone:0091-79-30215316

**Comment by rrjanbiah** [comment]
@tusharvanzara 

> My internet is connected and its up.we are having some proxy settings but i don't think it might have occurred this issue

Are you having issues only with connecting to restya.com? Can you check connecting to other websites through curl?

**Comment by tusharvanzara** [comment]
when i try to call that url with curl, i.e curl http://IP, then i get 
the response

ok let it be, if you can tell me that where should i copy restyaboard 
folder which contains client,media,server and all folder (My OS is 
CentOS)....and where should i put restyaboard.conf file..in 
/etc/nginx/conf.d ???



-- 
Thanks & Regards,
Tushar Vanzara



On 04/28/2016 02:30 PM, R. Rajesh Jeba Anbiah wrote:
>
> @tusharvanzara <https://github.com/tusharvanzara>
>
>     My internet is connected and its up.we are having some proxy
>     settings but i don't think it might have occurred this issue
>
> Are you having issues only with connecting to restya.com? Can you 
> check connecting to other websites through curl?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/RestyaPlatform/board/issues/616#issuecomment-215358196>
>


This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email. Pandit Ventures Private Limited, 9th Floor, Sambhaav House, Judges Bunglow Cross Roads, Bodakdev, Ahmedabad-380015, Phone:0091-79-30215316

**Comment by rrjanbiah** [comment]
@tusharvanzara 

> ok let it be, if you can tell me that where should i copy restyaboard folder which contains client,media,server and all folder (My OS is CentOS)....and where should i put restyaboard.conf file..in
> /etc/nginx/conf.d ???

Your restyaboard directory can be anything. You may better check the steps in the install script itself https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh

**Comment by tusharvanzara** [comment]
I did the same, but when i try to open link , then round and round, 
round and round and then it gives up. :) it leave with blank page, can 
see only favicon.

On 04/28/2016 03:20 PM, R. Rajesh Jeba Anbiah wrote:
>
> @tusharvanzara <https://github.com/tusharvanzara>
>
>     ok let it be, if you can tell me that where should i copy
>     restyaboard folder which contains client,media,server and all
>     folder (My OS is CentOS)....and where should i put
>     restyaboard.conf file..in
>     /etc/nginx/conf.d ???
>
> Your restyaboard directory can be anything. You may better check the 
> steps in the install script itself 
> https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/RestyaPlatform/board/issues/616#issuecomment-215371803>
>

-- 
Thanks & Regards,
Tushar Vanzara


This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email. Pandit Ventures Private Limited, 9th Floor, Sambhaav House, Judges Bunglow Cross Roads, Bodakdev, Ahmedabad-380015, Phone:0091-79-30215316

**Comment by rrjanbiah** [comment]
@tusharvanzara Sorry missed your reply here.

Can you check developer console and find HTTP requests?

Common issues:

1. 502 status usually means that php-fpm has not started
2. 404 or 401 status usually means that database credentials are wrong. You may check further errors by enabling debug mode in https://github.com/RestyaPlatform/board/blob/master/server/php/config.inc.php#L15 and by checking HTTP response headers.

**Comment by tusharvanzara** [comment]
pls find below php-fpm's www-error logs, by enabling through debugging mode its shows 500 internal server error.


[29-Apr-2016 17:18:46 Europe/Berlin] PHP Warning:  pg_query_params(): Query failed: ERROR:  permission denied for relation settings in /usr/share/nginx/html/server/php/config.inc.php on line 48
[29-Apr-2016 17:18:46 Europe/Berlin] PHP Warning:  pg_fetch_assoc() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/server/php/config.inc.php on line 49
[29-Apr-2016 17:18:46 Europe/Berlin] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  permission denied for relation oauth_scopes' in /usr/share/nginx/html/server/php/libs/vendors/OAuth2/Storage/Pdo.php:350
Stack trace:
#0 /usr/share/nginx/html/server/php/libs/vendors/OAuth2/Storage/Pdo.php(350): PDOStatement->execute(Array)
#1 /usr/share/nginx/html/server/php/libs/vendors/OAuth2/Scope.php(87): OAuth2\Storage\Pdo->getDefaultScope('774263250138231...')
#2 /usr/share/nginx/html/server/php/libs/vendors/OAuth2/Controller/TokenController.php(189): OAuth2\Scope->getDefaultScope('774263250138231...')
#3 /usr/share/nginx/html/server/php/libs/vendors/OAuth2/Controller/TokenController.php(49): OAuth2\Controller\TokenController->grantAccessToken(Object(OAuth2\Request), Object(OAuth2\Response))
#4 /usr/share/nginx/html/server/php/libs/vendors/OAuth2/Server.php(256): OAuth2\Controller\TokenController->handleTokenRequest(Object(OAuth2\Request), Object(OAuth2\Response))
#5 /usr/share/nginx/html/server/php/libs/ in /usr/share/nginx/html/server/php/libs/vendors/OAuth2/Storage/Pdo.php on line 350
