### ISSUE TITLE
Problem with indexing_to_elasticsearch.php

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#617]
From Huang Yangchao in forum https://groups.google.com/forum/#!topic/restya/M7Mxaqib818

I followed the install guide:

- Setup cron for every 5 minutes to update ElasticSearch indexing `*/5 * * * * /path/to/server/php/shell/indexing_to_elasticsearch.sh`
- Setup cron for every 5 minutes to send HTTP POST payload to the webhook's configured URL `*/5 * * * * /path/to/server/php/shell/webhook.sh`

when I manually executed the script "/path/to/server/php/shell/indexing_to_elasticsearch.sh" There were some error outputs:
```
----------------------------------
Error:: <url> malformed
Not Found.
---------------------------------

```
I found there should be two parameters ( $1 $2 ）passed to the script, But they were not defined.
```
-------------------------------------------------------------
$result = pg_query_params($db_lnk, 'SELECT value FROM settings WHERE name = $1', $qry_val_arr);
$result = pg_query_params($db_lnk, "SELECT id, card_id FROM activities WHERE id > $1 AND card_id != $2 AND card_id IS NOT NULL ORDER BY id ASC", $qry_val_arr);
-------------------------------------------------------------------

```
Any suggestion on how to fixed it,thx！

**Comment by ssivachidambaram** [comment]
Here https://github.com/RestyaPlatform/board/blob/master/server/php/shell/indexing_to_elasticsearch.php#L24 you can find the two parameters value.

Can you please check whether you have configured settings in admin side like this http://board.demo.restya.com/#/settings/1?

**Comment by rrjanbiah** [comment]
As he has deleted this message in forum, it may not be an issue anymore.
