### ISSUE TITLE
How to Empty database

### ISSUE THREAD

**Issue by happyfredo** [RestyaPlatform/board#619]
Hi, 

We test several trello import and i wish to delete my test.
When i  try to delete board in administration, there is some old data still present (in search).

Do you have a script or a tips to erase all data ?

Best regards

Fred

**Comment by ssivachidambaram** [comment]
[delete_elasticsearch_index.txt](https://github.com/RestyaPlatform/board/files/243496/delete_elasticsearch_index.txt)

We have written a ElasticSearch index delete in the attached file. Rename the extension of the file to php and upload in this path `server/php` and run like this `http://yourdomain.com/server/php/delete_elasticsearch_index.php`. After cron run the fresh data will re-index in ElasticSearch.

**Comment by happyfredo** [comment]
Excellent !

Thank you

**Comment by ssivachidambaram** [comment]
You are always welcome.
