### ISSUE TITLE
After added due date and time closed and open the same card due time is not displayed.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#62]
1. While adding a due date, i have added a date and time, then close the card. 
2. Again opened the card, while checking the due time. Due time field is empty.  

Refer the attachment
![due_time](https://cloud.githubusercontent.com/assets/14884895/10307463/e4addfca-6c4c-11e5-8f9f-13a5277e6497.png)

**Comment by rrjanbiah** [comment]
Fixed
