### ISSUE TITLE
Something wrong with LDAP authentification

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#620]
From Huang Yangchao in forum https://groups.google.com/forum/#!topic/restya/bgEwJREaCEg

When I set up LDAP  authentification, The users' account could be imported,
But when I use LDAP user to login, It through out 
"Email not associated for this LDAP account."

Is there anything others that I should set up either.

**Comment by raven-oscar** [comment]
Had the same problem few days ago. 
I assume using userPrincipalName as Account Filter fixed it. Anyway please show your auth config.

**Comment by HatBeardZero** [comment]
Mine was working, and just stopped after getting inexplicably logged out.

**Comment by keky** [comment]
I've solved the Problem by fixed Account Filter from "(&(objectClass=person)(objectClass=user))" to "sAMAccountName".

But there seems to be no relationship with Email. Can anybody fix the warning tips.  thx for ur work.!

**Comment by rrjanbiah** [comment]
@raven-oscar @HatBeardZero @keky Sorry about the issues you're facing. Our team will look into it by tomorrow as we're working in other high priority items.

Probably, you didn't have users' email in LDAP?

**Comment by keky** [comment]
@rrjanbiah   The emails already been here.

**Comment by HatBeardZero** [comment]
@rrjanbiah also confirming here the emails have been.  I get the error once it seems, then it lets me log in.

**Comment by rrjanbiah** [comment]
@HatBeardZero Thanks for your note. Much appreciated.

**Comment by ssivachidambaram** [comment]
@HatBeardZero @raven-oscar @keky 

We have tried this issue in fresh installation in VMware Ubuntu 14.04 32 bit OS. After proper configuration of LDAP, login is working fine for us.

**Comment by rrjanbiah** [comment]
@ssivachidambaram Can it happen due to connection timeout ?

**Comment by ssivachidambaram** [comment]
@rrjanbiah If LDAP connect was not performed then we will throw this error "LDAP server connection failed".

**Comment by lmarikannan** [comment]
Closing this for now
