### ISSUE TITLE
Changing public DNS URL

### ISSUE THREAD

**Issue by recordnotfound** [RestyaPlatform/board#622]
How can i change the Public DNS URL or IP in Restya Board. Asked by @geje2005 on https://recordnotfound.com/board-RestyaPlatform-10262

**Comment by rrjanbiah** [comment]
@geje2005 Closing as this looks like a spam from @recordnotfound 

@geje2005 If you have any valid questions, please post them in forum and or here. Thanks

**Comment by recordnotfound** [comment]
Its ok to close, but this is not spam. Its a valid question by a user of your project. If you have an answer, please post that. If not, then I guess @geje2005 has to post the question on this forum: https://groups.google.com/forum/#!forum/restya 

Please correct me if I am wrong.
