### ISSUE TITLE
Not displaying the correct board name, if we add a card in instant add card

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#63]
1.Login as a user[rest01/testing]
2.Add a card via instant add card
3.While selecting the board name=>> It display some html code along with the board name

Refer the attachment.
![board_name](https://cloud.githubusercontent.com/assets/14884895/10307714/86ef0f6a-6c4e-11e5-84e3-51644a5b2a52.png)

**Comment by rrjanbiah** [comment]
Fixed
