### ISSUE TITLE
getting scope error 

### ISSUE THREAD

**Issue by lilbro1062000** [RestyaPlatform/board#633]
Getting a scope error on nginx cant login, I get the following below meaning i am authenticated but cant access anypage due to scope errors.  Fresh install version 0.2.1

no php errors i can see.

>  error:"invalid_scope" error_description:"An unsupported scope was requested" id :"1" 

> {id: "1", role_id: "1", username: "admin", email: "board@restya.com", full_name: "New Admin"

The scope sent is 
`scope:"read read" token_type:"Bearer"`

**Comment by lilbro1062000** [comment]
fixed the issue turns out the oauth_scopes table had two defaults which were the read scope.

**Comment by ssivachidambaram** [comment]
While we check the default empty SQL in GitHub its having read and write scopes only. Please refer https://github.com/RestyaPlatform/board/blob/master/sql/restyaboard_with_empty_data.sql#L4919.

We are closing this issue as its fixed by @lilbro1062000.
