### ISSUE TITLE
Something Wrong with the Attachments

### ISSUE THREAD

**Issue by keky** [RestyaPlatform/board#634]
Shown up many times:
![attatchment](https://cloud.githubusercontent.com/assets/548338/15062861/42b73c98-1377-11e6-9c68-39df3c6a1bc6.png)
The other cards of the same list:
![att01](https://cloud.githubusercontent.com/assets/548338/15062976/9c2c1158-1378-11e6-8b96-74ef9b952d3d.png)

When I uploaded the picture from snapshot,It shown up many times in the card.
And are also shown up in the other cards of the same list.

**Comment by ssivachidambaram** [comment]
@keky We are trying to replicate this issue. If possible can you please send steps to reproduce this issue?

**Comment by keky** [comment]
Yes, After tested,I found that If two cards are opened at the same time,When u upload snapshot by CTRL-V  whenever one, All the cards would have the same upload picture.Sometimes it even shown up many time in a card
1\as shown blow,There are three card 1\12\123
![000](https://cloud.githubusercontent.com/assets/548338/15113972/197ddac0-162a-11e6-9167-acec3dc2b8f7.png)

2\When I open card [123]  and upload a snapshot,Everything seems all right.
![001](https://cloud.githubusercontent.com/assets/548338/15113998/3cae4796-162a-11e6-854c-a24944d99f38.png)

3\When I open cad 12\123 at the same time,and upload snapshot in card 123
The picture shown up in the two card

![Uploading 002.png…]()

**Comment by rrjanbiah** [comment]
@keky Thanks for explaining the steps to reproduce the issue.

So, reopening it.

**Comment by keky** [comment]
@rrjanbiah  Sorry,Just miss touched the closed button.

**Comment by rrjanbiah** [comment]
@keky No, problem. Thanks

**Comment by ssivachidambaram** [comment]
Fixed.

**Comment by keky** [comment]
well done, thx!

**Comment by rrjanbiah** [comment]
@keky It's a pleasure
