### ISSUE TITLE
Trello import is importing label color instead of label text

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#637]
From Rudiger Wolf through forum https://groups.google.com/d/msg/restya/qvMb8EDcD6E/5gFwrE7eBwAJ

created from Trello export. Note the Label with text "yellow"
And in Trello, the label, is yellow but its text is "Informational". It would be great if the import loaded the label with the Trello Text value rather than the name of the colour.

**Comment by ssivachidambaram** [comment]
Fixed.
