### ISSUE TITLE
401 Authenticaion failed on Activation

### ISSUE THREAD

**Issue by graebermedien** [RestyaPlatform/board#639]
Hi,

restyaboard is up and running, 1) added a new user, 2) got activation mail. 
3) Opened the Link in this mail leads me to the following error in dev console:

401 Authentication failed on Request (token removed):

http://restya.my-domain.de/api/v1/users/5/activation.json?token=TOKEN-HERE

Any suggestions why this is happening? Whats wrong ? Do i need to configure someting special?!

**Comment by graebermedien** [comment]
Another question: in my temp/cache folder there is a new file called "site_url_for_shell.php", content is this: 

```
<?php
$_server_domain_url = '';

```

Do i need to change url?! value?!

**Comment by graebermedien** [comment]
Here is my error-log:


```

PHP message: PHP Warning:  pg_num_rows() expects parameter 1 to be resource, boolean given in /var/www/vhosts/my-domain.de/restya.my-domain.de/server/php/libs/core.php on line 626" while reading response header from upstream, client: 87.159.183.203, server: restya.my-domain.de, request: "PUT /api/v1/users/5.json?token=3a60d1610f2651aca273gd3b764b2daa2965fe85 HTTP/1.1", upstream: "fastcgi://unix:///var/www/vhosts/system/restya.my-domain.de/php-fpm.sock:", host: "restya.my-domain.de", referrer: "http://restya.my-domain.de/"
2016/05/17 11:19:52 [error] 5064#0: *2551 FastCGI sent in stderr: "PHP message: PHP Warning:  pg_query_params(): Query failed: FEHLER:  Binden-Nachricht enthält 2 Parameter, aber vorbereitete Anweisung „“ erfordert 0 in /var/www/vhosts/my-domain.de/restya.my-domain.de/server/php/R/r.php on line 888
PHP message: PHP Warning:  pg_fetch_object() expects parameter 1 to be resource, boolean given in /var/www/vhosts/my-domain.de/restya.my-domain.de/server/php/R/r.php on line 889
PHP message: PHP Notice:  Trying to get property of non-object in /var/www/vhosts/my-domain.de/restya.my-domain.de/server/php/R/r.php on line 892
PHP message: PHP Notice:  Trying to get property of non-object in /var/www/vhosts/my-domain.de/restya.my-domain.de/server/php/R/r.php on line 893
PHP message: PHP Notice:  Trying to get property of non-object in /var/www/vhosts/my-domain.de/restya.my-domain.de/server/php/R/r.php on line 893
PHP message: PHP Notice:  Trying to get property of non-object in /var/www/vhosts/my-domain.de/restya.my-domain.de/server/php/R/r.php on line 896" while reading response header from upstream, client: 87.159.183.203, server: restya.my-domain.de, request: "GET /api/v1/oauth/applications.json?token=3a60d1610f2651aca273gd3b764b2daa2965fe85&_=1463476785048 HTTP/1.1", upstream: "fastcgi://unix:///var/www/vhosts/system/restya.my-domain.de/php-fpm.sock:", host: "restya.my-domain.de", referrer: "http://restya.my-domain.de/"

```

Any suggestions what i could try/do?! Please help! Thanks!

**Comment by ssivachidambaram** [comment]
Sorry for the trouble. Related to #487. You can update the r.php file with changes mentioned here https://github.com/RestyaPlatform/board/pull/489/files & https://github.com/RestyaPlatform/board/pull/524/files#diff-9812550cecc4e99d42faa21f771c0b8cR4661.

**Comment by ssivachidambaram** [comment]
Can you please update the `config.inc.php` file with changes mentioned here https://github.com/RestyaPlatform/board/commit/ae0ce52ba617a2f53ccd070c7cfc5bce3d4894b1. Then delete the file `tmp/cache/site_url_for_shell.php` and run your URL in browser, then the file will create again.

**Comment by graebermedien** [comment]
@ssivachidambaram THANK YOU! Now it works! 

-> Maybe a new release should be made, including this changes and an update of the "manual install"-section on the restya website (including a hint to create the /app folder or including a default/empty app in the release package for manual install (see https://github.com/RestyaPlatform/board/issues/638 )

THANKS again!

**Comment by graebermedien** [comment]
Nearly ... now there is another error on Login:


`<br />
<b>Notice</b>:  Undefined variable: scope in <b>/var/www/vhosts/my-domain.de/restya.my-domain.de/server/php/R/r.php</b> on line <b>4762</b><br />
<br />
<b>Warning</b>:  in_array() expects parameter 2 to be array, null given in <b>/var/www/vhosts/my-domain.de/restya.my-domain.de/server/php/R/r.php</b> on line <b>4762</b><br />`

**Comment by ssivachidambaram** [comment]
@graebermedien In http://restya.com/board/apps apps page, we have mentioned how to install new apps in Restyaboard. Also we will add a check in `r.php` if no apps available as mentioned in #638.

Mentioned notice and warnings are fixed in our `dev` branch and it will be available in upcoming release. Can you please change debug mode to false in `config.inc.php` and run?

**Comment by graebermedien** [comment]
@ssivachidambaram thanks again - i forgot to disable the debug mode...my fault :)

Thank you again for your nice and fast support!

**Comment by ssivachidambaram** [comment]
@graebermedien It's a pleasure.
