### ISSUE TITLE
When admin updated the user profile, it display the notification message as admin updated the profile.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#64]
1.Login as a admin
2.Update the user profile
3.In notification panel=>> It will display the message as admin update the profile.

Refer the attachment
![admin_update_profile](https://cloud.githubusercontent.com/assets/14884895/10307759/d80e2638-6c4e-11e5-8274-a05feeb16ff8.png)

**Comment by rrjanbiah** [comment]
Fixed
