### ISSUE TITLE
Installed Restyaboard, was simple, but now I can't log in.

### ISSUE THREAD

**Issue by jtbrehmny** [RestyaPlatform/board#641]
the install was great compared to the headache of trying to install Wekan.  It gave me a username and password during the install, which I thoguht I would use to log into the site once it completed but it didn't work.  Further, I tried registering a user but I didn't set up email functionality, so I can't get the activation email and thus can't log in...is there anyway to create a local admin user to get into the system?

**Comment by rrjanbiah** [comment]
@jtbrehmny Thanks for your kind words. 

Can you please attach your install log, that will help us to understand if everything properly installed.

Can you try `admin` username with `restya` as password?

**Comment by nbalithya** [comment]
hi !

we have same issue.

and when i try with admin username with restya as password, i have this error message:

"Sorry, login failed. Either your username or password are incorrect or admin deactivated your account."

**Comment by rrjanbiah** [comment]
@nbalithya You may find the logic of storing encrypted password in DB here https://github.com/RestyaPlatform/board/blob/master/server/php/libs/core.php#L99

>  the link in validation email doesn't work

Can you please share what error did you get?

**Comment by nbalithya** [comment]
i don't have error but when i click on it and i check in DB, this status is always " f ".
so the user isn't activated and email not validated

**Comment by rrjanbiah** [comment]
@nbalithya Can you please check HTTP response and post here?

**Comment by jtbrehmny** [comment]
@rrjanbiah I'm not at the site where I installed it today, I will try to grab the install log remotely.  My errors were the same as nbalithya though.

@nbalithya thanks for posting, good to know I'm not the only one :smile:

**Comment by nbalithya** [comment]
i have this in access.log when i click on email validation link

XXX.XXX.XXX.XXX server 0.029 [20/May/2016:09:01:00 +0000] "GET /api/v1/oauth.json?_=1463734860223 HTTP/1.1" 200 388 "http://server/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36" "-"
XXX.XXX.XXX.XXX server 0.016 [20/May/2016:09:01:00 +0000] "GET /api/v1/settings.json?token=8d13b63e4889676d328ac0d4e6c39273dd669d2e&_=1463734860263 HTTP/1.1" 200 192 "http://server/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36" "-"
XXX.XXX.XXX.XXX server 0.016 [20/May/2016:09:01:00 +0000] "PUT /api/v1/users/7/activation.json?token=8d13b63e4889676d328ac0d4e6c39273dd669d2e HTTP/1.1" 401 5 "http://server/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36" "-"

**Comment by rrjanbiah** [comment]
@nbalithya Thanks for the information. Are you able to reproduce it in incognito/private window too?

**Comment by nbalithya** [comment]
XXX.XXX.XXX.XXX server 0.000 [20/May/2016:10:48:25 +0000] "GET / HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/YYY.YYY.YYY.YYY Safari/537.36" "-"
XXX.XXX.XXX.XXX server 0.009 [20/May/2016:10:48:25 +0000] "GET /css/default.cache.a4664637.css HTTP/1.1" 200 45638 "http://server/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/YYY.YYY.YYY.YYY Safari/537.36" "-"
XXX.XXX.XXX.XXX server 0.131 [20/May/2016:10:48:25 +0000] "GET /js/default.cache.3b6d24ac.js HTTP/1.1" 200 1742899 "http://server/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/YYY.YYY.YYY.YYY Safari/537.36" "-"
XXX.XXX.XXX.XXX server 0.000 [20/May/2016:10:48:26 +0000] "GET /favicon.ico HTTP/1.1" 200 32988 "http://server/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/YYY.YYY.YYY.YYY Safari/537.36" "-"
XXX.XXX.XXX.XXX server 0.028 [20/May/2016:10:48:26 +0000] "GET /api/v1/oauth.json?_=1463741305488 HTTP/1.1" 200 388 "http://server/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/YYY.YYY.YYY.YYY Safari/537.36" "-"
XXX.XXX.XXX.XXX server 0.014 [20/May/2016:10:48:26 +0000] "GET /api/v1/settings.json?token=8ae32ff31b09fbf46640e9c20a3bb1457013363e&_=1463741305526 HTTP/1.1" 200 192 "http://server/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/YYY.YYY.YYY.YYY Safari/537.36" "-"
XXX.XXX.XXX.XXX server 0.000 [20/May/2016:10:48:26 +0000] "GET /locales/en_US/translation.json HTTP/1.1" 200 8804 "http://server/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/YYY.YYY.YYY.YYY Safari/537.36" "-"
XXX.XXX.XXX.XXX server 0.000 [20/May/2016:10:48:26 +0000] "GET /img/logo.png HTTP/1.1" 200 4461 "http://server/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/YYY.YYY.YYY.YYY Safari/537.36" "-"
XXX.XXX.XXX.XXX server 0.013 [20/May/2016:10:48:26 +0000] "PUT /api/v1/users/7/activation.json?token=8ae32ff31b09fbf46640e9c20a3bb1457013363e HTTP/1.1" 401 5 "http://server/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/YYY.YYY.YYY.YYY Safari/537.36" "-"

**Comment by rrjanbiah** [comment]
@ssivachidambaram Looks like an issue that we already fixed. Can you please confirm?

**Comment by ssivachidambaram** [comment]
@rrjanbiah Yes. It is related to #487. 

@nbalithya @jtbrehmny Can you please update the r.php file with changes mentioned here https://github.com/RestyaPlatform/board/pull/489/files & https://github.com/RestyaPlatform/board/pull/524/files#diff-9812550cecc4e99d42faa21f771c0b8cR4661.

**Comment by jtbrehmny** [comment]
I am working on this again today, I cannot find the r.php file, the paths
listed on the sites you linked to don't seem to exist on my restyaboard
install.  Any ideas?

Thanks,
John

Thanks,
John Brehm
Computer Support Specialist
HPM Tech Services, a division of ActionXL
P:607-319-4776
E:jbrehm@hpmtechservices.com <jbrehm@hpmtechservices.com>

**Comment by rrjanbiah** [comment]
@jtbrehmny Probably you didn't have root when you installed? Can you please share install log?

**Comment by Wintaru** [comment]
This is happening to me as well. It took me several tries to get it installed so my log is longer than usual.
[restyaboard_install_worked.txt](https://github.com/RestyaPlatform/board/files/285526/restyaboard_install_worked.txt)

**Comment by ssivachidambaram** [comment]
@Wintaru `r.php` file will available in this path, `/var/www/abandonedbits.com/restyaboard/server/php/R/` (taken from the log) and do the below changes,

https://github.com/RestyaPlatform/board/pull/489/files & https://github.com/RestyaPlatform/board/pull/524/files#diff-9812550cecc4e99d42faa21f771c0b8cR4661.

**Comment by nbalithya** [comment]
Hi !
It's ok for me. thanks for your help.

**Comment by petman** [comment]
Hi, 

I have install restyaboard on centos 6.7 with the Recommended install script linux on the main website http://restya.com/

First, the activation link was not functionnal. I have done manually the modification: 

https://github.com/RestyaPlatform/board/pull/489/files & https://github.com/RestyaPlatform/board/pull/524/files#diff-9812550cecc4e99d42faa21f771c0b8cR4661.

and 

https://github.com/RestyaPlatform/board/pull/489/files & https://github.com/RestyaPlatform/board/pull/524/files#diff-9812550cecc4e99d42faa21f771c0b8cR4661.

I can activate my account. The entry is present on database on active.

But now the interface indicate me for all my accounts this :
"Sorry, login failed. Either your username or password are incorrect or admin deactivated your account."

What must I do ?? 

regards

**Comment by rrjanbiah** [comment]
@petman Are your other accounts able to login to the system? IOW, are you facing issues with your manually activated accounts alone? Also, are you aware that the passwords in DB are encrypted using Bluefish?

**Comment by petman** [comment]
@rrjanbiah Yes, all my acconts are activable but the password don't work.

So for the bluefish encryption, what I must know or do ?? 

Regards

**Comment by petman** [comment]
Hi, The install on centos is very chaotic. I have change the distribution for Debian.

Good on the first time with the patch: 
https://github.com/RestyaPlatform/board/pull/489/files

**Comment by petman** [comment]
so I have an error message on ldap authentication :

2016/06/17 15:24:28 [error] 24977#0: *2954 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: scope in /var/www/board/server/php/R/r.php on line 4762
PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/www/board/server/php/R/r.php on line 4762" while reading response header from upstream, client: 172., server: board, request: "POST /api/v1/users/login.json?token=c6df2b9bf2b6a96f7c7f183630be4b61fa0e2827 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "board", referrer: "http://board/"

It is a line that we have modify on the previous patch : 
/var/www/board/server/php/R/r.php on line 4762

if ((in_array('write', $scope) && ((!empty($authUser)) || (in_array($r_resource_cmd, $exception_url) && empty($authUser)))) || in_array($r_resource_cmd, $scope_exception_url)) {

Perhaps a bug ??

**Comment by rrjanbiah** [comment]
@petman Sorry, we completely missed your messages.

Yes, this could be a bug. We'll check and update.

> The install on centos is very chaotic

If possible, please elaborate this as that may help us to fix issues. Thanks again

**Comment by petman** [comment]
Hi, 

Do you have fins some fix about these issues ? 

Regards

**Comment by rrjanbiah** [comment]
@petman 

> Do you have fins some fix about these issues ?

Yes, can you please check v0.3 and let us know if you're still having this issue?

**Comment by jmutkawoa** [comment]
@rrjanbiah @petman @sridhar391 I encountered similar issue when deploying Restyaboard from the script on the Centos 7 fresh server, i.e; when login for the first time the page keeps on looping and the nginx acces log keeps on giving a http 200

The nginx error log gave the following message:

2018/06/28 03:13:30 [error] 1009#1009: *2 directory index of "/usr/share/nginx/html/restyaboard/" is forbidden, client: 10.239.44.114, server: localhost, request: "GET /restyaboard/ HTTP/1.1", host: "10.239.44.166"

It was solved on my side by simply disabling selinux and rebooted the machine.

kind regards
Nitin - tunnelix.com / hackers.mu

**Comment by sridhar391** [comment]
Thanks for your information

**Comment by sridhar391** [comment]
We have mentioned the steps on the video about the Restyaboard Installation on CentOS https://youtu.be/hcnIHZnS1o8?t=150. We will add it in docs also.
