### ISSUE TITLE
Error when clicking link in activation email

### ISSUE THREAD

**Issue by kramer65** [RestyaPlatform/board#647]
I've just installed restyaboard on a fresh Debian server using the (indeed incredibly easy) install script. It all works quite good, except for when I register as a new user and click the activation link in the email I get a page with only the restyaboard header and in te console I get an error (see below).

Any idea what could be wrong here?

![activation_link_error](https://cloud.githubusercontent.com/assets/596581/15431830/e07f534a-1eab-11e6-9859-97cbdc74beb5.png)

**Comment by rrjanbiah** [comment]
@kramer65 Probably duplicate of #487 Can you please check that?

**Comment by kramer65** [comment]
@rrjanbiah - Thanks that was it indeed. When will the version including this fix be released so that it is automatically installed with the Linux installation script?

**Comment by rrjanbiah** [comment]
@kramer65 Glad to know that. 

Unfortunately, we're much behind the deadlines, as few other things are dragging us. Hopefully this week will be the right time for us.
