### ISSUE TITLE
Cant able to add a card via instant add card, if we give due date while adding

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#65]
![card_not_add](https://cloud.githubusercontent.com/assets/14884895/10308828/296979f4-6c56-11e5-975a-5f880cc651ad.png)

1.Login as user[rest01/testing]
2.Add a card via instant add card =>> and also give due date for the card
3.And click save =>> It will display one search key in the right corner of the
screen
4.And we cant able to add the Card in board

Refer the attachment

Note: Check this issue in FF.

**Comment by rrjanbiah** [comment]
Fixed.
