### ISSUE TITLE
Debian wheezy Installation problem

### ISSUE THREAD

**Issue by donat1** [RestyaPlatform/board#655]
We have discovered restya and it seems exactly that, what we are searching. Great work!

By installing with the automatic script we had following issues:
1. exim mail server was uninstalled. I could manage it to work it again. -> is okay for now.
2. The database table I had to install it separately, since there was an issue with the user ident. -> is okay for now.
3. We use apache as server and nginx as proxy (default configuration with vestacp). So I installed .htacess and it seems that the browser is working, since the .ico is enabled in the browser tab and some code is loaded. But the page remains blank. So what else is missing now? I can't see anything in the apache.error.log. 
4. There is also a restyaboard.conf in /opt/restyaboard and the same (?) in www root? Which one and how is it to configure.

Can you help us with any advice. Kind regards.

[restyaboard_install.txt](https://github.com/RestyaPlatform/board/files/286879/restyaboard_install.txt)

**Comment by lmarikannan** [comment]
@donat1 Can you please enable debug mode in https://github.com/RestyaPlatform/board/blob/master/server/php/R/config.inc.php#L15 and post HTTP response header and response (In Firebug or Chrome's Developer tool)

**Comment by donat1** [comment]
We have following Warning in apache_error_log:

```
PHP Warning:  pg_query_params(): Query failed: FEHLER:  Relation \xc2\xbbrole_links_listing\xc2\xab existiert nicht\nLINE 1: SELECT * FROM role_links_listing WHERE id = $1\n                      ^ in /home/vfmg/web/project.vfmg.ch/public_html/server/php/libs/core.php on line 625, referer: http://project.vfmg.ch/
[Sat May 28 20:35:34 2016] [error] [client 80.219.178.147] PHP Warning:  pg_num_rows() expects parameter 1 to be resource, boolean given in /home/vfmg/web/project.vfmg.ch/public_html/server/php/libs/core.php on line 626, referer: http://project.vfmg.ch/
[Sat May 28 20:35:34 2016] [error] [client 80.219.178.147] PHP Warning:  array_merge(): Argument #2 is not an array in /home/vfmg/web/project.vfmg.ch/public_html/server/php/R/r.php on line 4696, referer: http://project.vfmg.ch/
```
And in the console of firebug I have following error:
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
default...c8c3.js (Zeile 72, Spalte 3797)
```
I'm not sure what you mean with response header of firebug. Is it the header section of the html?

**Comment by lmarikannan** [comment]
We checked your apache_error_log, it seems your database user permission is denied. Can you please grant permission to your database user. 

ex:
If your database user is `restya`,
```
ALTER DATABASE restyaboard OWNER TO restya; 
GRANT ALL PRIVILEGES ON DATABASE restyaboard TO restya; 
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO restya; 
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO restya;
```

**Comment by donat1** [comment]
Thans for your suggestion. I made this, but it didn't change the error.

When I execute `SELECT * FROM role_links_listing` in the phpPgAdmin I get the same error. So it seem's, that is not a problem of the privilege but a problem, that the view is missing.
Error message:
```
FEHLER:  Relation »role_links_listing« existiert nicht
LINE 1: SELECT * FROM role_links_listing
```
Shouldn't role_links_listing be a table resp. a view in postgresql?

When I install with the pgsql command, I have some error messages in the console (maybe there are more):
psql:/home/vfmg/web/project.vfmg.ch/public_html/sql/restyaboard_with_empty_data.sql:6354: FEHLER:  Relation »checklists_listing« existiert nicht
psql:/home/vfmg/web/project.vfmg.ch/public_html/sql/restyaboard_with_empty_data.sql:6355: FEHLER:  Relation »checklists_listing« existiert nicht
psql:/home/vfmg/web/project.vfmg.ch/public_html/sql/restyaboard_with_empty_data.sql:6356: FEHLER:  Relation »checklists_listing« existiert nicht

**Comment by lmarikannan** [comment]
Can you please drop the database, and create newly. Then execute the `restyaboard_with_empty_data.sql` file manually?

**Comment by donat1** [comment]
I made this and the errors in the console in the previous post are from this command. So there seems to be a bug within this database dump?

**Comment by lmarikannan** [comment]
Here, we checked again more than once with dump. There is no bug in  database dump.  So please execute the missing `views` manually, and check again

**Comment by donat1** [comment]
Okay, I made it manually again. Here is the log file of the putty-shell attached with the messages of the sql. Maybe there will be a hint to solve my problem.

[putty.txt](https://github.com/RestyaPlatform/board/files/289400/putty.txt)

**Comment by rrjanbiah** [comment]
> unktion row_to_json(record) existiert nicht
> function row_to_json (record) does not exist

@lmarikannan Looks like PostgreSQL version issue.

**Comment by lmarikannan** [comment]
@rrjanbiah Yes, row_to_json() function was introduced in 9.2.

@donat1 Can you please check your PostgreSQL version

**Comment by donat1** [comment]
Thank you for your information. It was postgresql version 9.1 and I have updated to 9.5.
Now it seems to work!

**Comment by rrjanbiah** [comment]
@donat1 Thanks for confirming. Glad to know that you've got it working

@lmarikannan Can we add version check in install script?

**Comment by lmarikannan** [comment]
PostgerSQL version check and upgrade code added in this commit https://github.com/RestyaPlatform/board/commit/8f5993fb1349e3c2b6e88d34fe9ec027fdc7d201
