### ISSUE TITLE
¿When the week begins?

### ISSUE THREAD

**Issue by dfragac** [RestyaPlatform/board#656]
Hi!

I'm writing this issue to make a "feature suggestion":

In calendar wiew, first day of the week is Sunday but here (I'm writing from Spain), first day of the week is Monday.

¿How you see the possibility to implement some "first day of the week" in configuration for this view?

Thanks in advance for everything!

**Comment by lmarikannan** [comment]
@dfragac Currently, this option is not available in admin settings. But we can change the firstday of the week in calendar view, by insert a code `firstDay: 1,` after this line https://github.com/RestyaPlatform/board/blob/master/client/js/views/board_header_view.js#L924.

**Comment by lmarikannan** [comment]
Hi, did you update in your calendar view as first day of the week is Monday?

**Comment by dfragac** [comment]
I'm using docker version and I don't have that file (Restya v0.2.1) under client/js so I can't. It's only:

- authorize.cache.js

- default.cache....js

- workflow_templates/

**Comment by lmarikannan** [comment]
You can change the firstday of the week in calendar view, by insert a code firstDay: 1, after this code  
`header:{left:"prev,next today",center:"title",right:"month,basicWeek,basicDay"},` on `default.cache....js`

ex:
`header:{left:"prev,next today",center:"title",right:"month,basicWeek,basicDay"},firstDay:1,`

**Comment by dfragac** [comment]
I've done the changes @lmarikannan and everything is OK. Thanks!

**Comment by rrjanbiah** [comment]
@dfragac Thanks for confirming. Closing this for now. If we get more such requests, we'll consider that.

**Comment by dfragac** [comment]
This change is for week template but... how I change the same for "due date" datapicker?

**Comment by dfragac** [comment]
Worked! Thx! :+1:
