### ISSUE TITLE
LDAP filter

### ISSUE THREAD

**Issue by nicolas-r** [RestyaPlatform/board#658]
Hi

I'm trying the LDAP functionality of Restyaboard and I have some issues :
- I get an error of sizelimit exceeded because with my setup, more than 1000 results are returned and you don't deal with that.  
- I can't specify advanced filter to limit the number of results. I have tried to put one in the account filter field but I get an error in the log about bad filter. I have read the code and see that and that explain why my filters are not working:
  $search_filter = '(&(objectCategory=person)(' . LDAP_UID_FIELD . '=*))';
  After some modification to this line to add a custom filter, I have was able to only import the users I want.
- But as the users have no email address associated (I reuse a specific branch in an Active Directory), they can't login and get a message about the fact that there is no email associated to this ldap account. Even after adding manually an email address inside restyaboard, they can't login. I have to add an email address to a user in the AD to allow then to connect.

Do you have plan to add more functionalities to the LDAP part, like advanced filters or group filtering ?

Do you plan to change the way ldap account are managed and the fact that an email attribute is mandatory ?

Thanks

Nicolas

**Comment by rrjanbiah** [comment]
@lmarikannan I get an error of sizelimit exceeded because with my setup, more than 1000 results are returned and you don't deal with that.

**Comment by rrjanbiah** [comment]
@nicolas-r 

> $search_filter = '(&(objectCategory=person)(' . LDAP_UID_FIELD . '=*))';
> After some modification to this line to add a custom filter, I have was able to only import the users I want.

If you can share that code and or contribute to this open source, it will be easy to make progress.

> Do you have plan to add more functionalities to the LDAP part, like advanced filters or group filtering ?

We're definitely committed to improved Restyaboard with any necessary additions. But, we need clear list of requirements here

> Do you plan to change the way ldap account are managed and the fact that an email attribute is mandatory ?

We may less likely to remove mandatory option for email, as it is essential for email notifications.

**Comment by nicolas-r** [comment]
1. An example of my modification to allow only the member of group xxx to be returned
$search_filter = '(&(objectCategory=person)(memberOf=xxx)(' . LDAP_UID_FIELD . '=*))';
The idea is to offer the users an input box to enter a custom filter that will be use in this function as is. If they don't want, they just enter the name of the LDAP_UID_FIELD like the current implementation

2. For me the most missing part is the lack of custom filter like I said

3. I mean mandatory in the LDAP, not in Restyaboard. I don't expect that your remove the email but maybe, you can implement something to allow users imported from an LDAP server without an email to be able to login and add an email to their profile.

**Comment by rrjanbiah** [comment]
@nicolas-r Thanks for clarifying. We'll see what we can do here.

**Comment by lmarikannan** [comment]
Fixed on this commit ee265f7.
