### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by nbalithya** [RestyaPlatform/board#660]
It's possible to choose label's color or edit the label's name ?

**Comment by lmarikannan** [comment]
Thanks for your note. We'll see what we can do here.

**Comment by rrjanbiah** [comment]
@nbalithya Can you please check https://groups.google.com/d/msg/restya/qvMb8EDcD6E/CxakzdK-BwAJ if that answers your question?

**Comment by nbalithya** [comment]
no sorry.

i can create labels, but i would like know if you have a solution to choose label's color or modifie/edit labels like in trello.

if i need to edit in DB it's not a problem.

**Comment by rrjanbiah** [comment]
@nbalithya Sorry, currently it is not possible... as we have adopted auto label color generation from label text.

**Comment by lmarikannan** [comment]
Closing this for now. If you get any issues, please feel free to reopen.
