### ISSUE TITLE
Large Checklist makes the website unresponsive

### ISSUE THREAD

**Issue by Samunosuke** [RestyaPlatform/board#661]
I have tried to use checklists but they make website very unresponsive - the browser did already run into timeouts.
The used ubuntu server is almost idle - so it has nothing to do with heavy workload of the server.
The checklist has 45 Entries.

**Comment by rrjanbiah** [comment]
@Samunosuke Can you please mention the browser and version?

**Comment by Samunosuke** [comment]
@rrjanbiah I am using Firefox V 46.0.1 and I have tried to use Google Chrome V 50.0.2661.102.
The restyaboard version = v 0.2.1 (2016-03-16)

**Comment by lmarikannan** [comment]
@Samunosuke Thanks for your note. We'll check and fix

**Comment by Zimeon-** [comment]
We have the same issue, and if you change the order for an item in the checklist it gets even worse. Website freezes for a considerable amount of time until the move is completed.

**Comment by rrjanbiah** [comment]
@Zimeon- Thanks for your note. Will definitely look into it.

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/pull/854/commits/65a4b9bb1d6a0363c997d117fca4f407c2468b67
