### ISSUE TITLE
Search members is inconsistent

### ISSUE THREAD

**Issue by Samunosuke** [RestyaPlatform/board#662]
The member search function for the board does search by username and email address...
![membersearch](https://cloud.githubusercontent.com/assets/1368406/15673757/05c6ad0c-2739-11e6-87d3-3126611bf340.png)
but the member search function within a card does only search by their email addresses...
![membersearchincards](https://cloud.githubusercontent.com/assets/1368406/15673784/3c965f58-2739-11e6-9dd6-2b1e0942ee51.png)
here it should also search by email and username!

**Comment by lmarikannan** [comment]
Thanks for reporting this. We'll check and update.

**Comment by lmarikannan** [comment]
Fixed in dev branch

**Comment by lmarikannan** [comment]
Closing this for now. If you get any other issues related this, please feel free to reopen.
