### ISSUE TITLE
Show only "comments"

### ISSUE THREAD

**Issue by dfragac** [RestyaPlatform/board#663]
It's too tedious to find comments and follow them on the "timeline" of a card and it's so repetitive to click de "comments" filter button on top right... ¿maybe an option to select what to see by default? (comments, activities, both)

**Comment by rrjanbiah** [comment]
@dfragac Yes, that's looks like a nice suggestion.

**Comment by LukeHartcher** [comment]
Can I suggest keeping them separate i.e. a one list of "Comments" (with an input box) and a second list for "Activity".

**Comment by ssivachidambaram** [comment]
Filter by activities and comments implemented in v0.3.
