### ISSUE TITLE
How to cancle email-confirm after sign up

### ISSUE THREAD

**Issue by huhuyou2** [RestyaPlatform/board#666]
hi, 
    Restyaborad is very nice for me, and I`ll took her for my personal work trace. 
    So, email-confirm becomes a needless action.
    Is there a way to realize my idea?

**Comment by rrjanbiah** [comment]
@huhuyou2 Were you able to find solution?

**Comment by huhuyou2** [comment]
> Were you able to find solution?

No, I can`t find the way for my idea.
Instead, I add user directly by Admin role.
