### ISSUE TITLE
Delete members as board owner not possible

### ISSUE THREAD

**Issue by donat1** [RestyaPlatform/board#669]
I have following Error, when deleting a member from a board, which I own by myself:

PHP Notice:  Undefined variable: scope in /home/web/server/php/R/r.php on line 4787, referer: http://example.com/
PHP Warning:  in_array() expects parameter 2 to be array, null given in /home/web/server/php/R/r.php on line 4787, referer: http://example.com/

And the member remains listed.

**Comment by rrjanbiah** [comment]
@donat1 Thanks for reporting this error. We'll check and fix it soon.

**Comment by lmarikannan** [comment]
@donat1 We have tried to reproduce this issue in local but we cannot able to reproduce it. Can you please double check that?

**Comment by donat1** [comment]
I reinstalled restyaform and now it works perfect. I don't know if there was a problem with the first installation.

Thanks!
