### ISSUE TITLE
"This board may be private" Need to align it in center.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#67]
"This board may be private" Need to align it in center.

Refer the attachment.

![aligment_issue](https://cloud.githubusercontent.com/assets/14884895/10309798/2cae74d8-6c5c-11e5-9012-c11a507f819c.png)

**Comment by rrjanbiah** [comment]
Fixed. As the page has to  fix in responsive design, this is not moved to center but moved downward for some extent.
