### ISSUE TITLE
Colaboration on translation

### ISSUE THREAD

**Issue by dfragac** [RestyaPlatform/board#670]
Hi!

I was looking for translations for restyaboard and i found that current Spanish translation it's no so accurate ;-).

¿How can I colaborate? ¿Do I need to fork the project and do a pull request or there is some way to colaborate in translations without doing that?

I can colaborate with translation to spanish and galician.

**Comment by rrjanbiah** [comment]
@dfragac Thanks for your interest in translating Restyaboard. You may join here https://www.transifex.com/restya/restyaboard/ and update translation.

**Comment by dfragac** [comment]
OK, thx!

**Comment by rrjanbiah** [comment]
You're welcome. Closing this for now.
