### ISSUE TITLE
Activities history missing fro card

### ISSUE THREAD

**Issue by nicolas-r** [RestyaPlatform/board#671]
Hi

In the board, I can see that a card has 4 comments but when I click on it, I can only see two of them.

Moreover, I have move the card to a new place and one more comment has disappear.

I can find the comment contents via the search feataure or by clicking on the ring in the lower corner

Nicolas

**Comment by rrjanbiah** [comment]
@lmarikannan Looks like the issue that we have already fixed?

**Comment by nicolas-r** [comment]
The version I'm using is 0.2.1

**Comment by nicolas-r** [comment]
I have searched the closed bugs and found #611. I have applied the three commits manually and now I can see all the comments

**Comment by rrjanbiah** [comment]
@nicolas-r Sorry and thanks!
