### ISSUE TITLE
Multi-User - Boards not Updating Live

### ISSUE THREAD

**Issue by LukeHartcher** [RestyaPlatform/board#672]
When multiple people are using the same board, changes by one user are not updated on the board of the second user and a manual refresh is required to see the changes.

Confirmed on http://board.demo.restya.com/ across two browsers.

**Comment by rrjanbiah** [comment]
@LukeHartcher Many thanks for your report. We'll fix it soon.

Side note: It looks like when a label is getting added, it is breaking the whole updates. Also, it also seems to be breaking how users are associated to board.

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/58471a91dd828a691414f351b8ef414a6b714f67
