### ISSUE TITLE
Request - Separate Comments and Activity

### ISSUE THREAD

**Issue by LukeHartcher** [RestyaPlatform/board#673]
Currently adding a Comment gets lost in the Activity as soon as you do something the comment is pushed down the list and it is not clear what is a comment and what is an activity. Activity is really an audit log and should be separate from comments.

Request - separate Comments and Activity so that Comments are easily identified and viewed. Comment changes can still be shown in Activity.

I have just realised the latest version has a "comments filter icon" but I think it would be better to separate these lists completely i.e. one list of "Comments" (with an input box) and a second list for "Activity".

**Comment by dfragac** [comment]
Similar to #663

**Comment by rrjanbiah** [comment]
@LukeHartcher Many thanks for your suggestions. We'll definitely see what we can do here.

Currently half of the users are coming from Trello and they expect similar features. That's the only concern for now. But, we can definitely push what is best for everyone.

**Comment by ssivachidambaram** [comment]
Filter by activities and comments implemented in v0.3.
