### ISSUE TITLE
Stats on boards, cards....

### ISSUE THREAD

**Issue by dfragac** [RestyaPlatform/board#674]
Hi!

I'm here to propose a new feature :-)

¿Is it possible to create some statistics about boards or cards in boards?

Ex:
 - Average time to close a card (A card is considered closed from creation to archive)
 - Average time between states (To measure time from "in progress" to "done")
 - Average count of times when a card moves between states
 - Average count of statechange

etc etc...

**Comment by rrjanbiah** [comment]
@dfragac Thanks a lot for your suggestions. Some of these are already pushed into our `dev` branch :)

**Comment by dfragac** [comment]
Great! ;-)

**Comment by lmarikannan** [comment]
Closing this for now. If you get any issues, please feel free to reopen.
