### ISSUE TITLE
Config attachment file dir manually on website?

### ISSUE THREAD

**Issue by huhuyou2** [RestyaPlatform/board#675]
I found the files here what I uploaded from website
`/usr/share/nginx/html/restyaboard/media/Card`
And, It is not big enough sometimes in future.
Therefore, is there a way to set attachment file dir to dir that mounts storage.

**Comment by rrjanbiah** [comment]
@huhuyou2 Wouldn't symlink work in that case?

**Comment by huhuyou2** [comment]
@rrjanbiah yes, I try 'ln' commands for this demand, and it`s ok for now. 

Thank you very much.

**Comment by rrjanbiah** [comment]
@huhuyou2 Thank you.

Closing this for now.
