### ISSUE TITLE
No comments after moving card to another list

### ISSUE THREAD

**Issue by Aendrew87** [RestyaPlatform/board#678]
Hi,

i have the same probleme as described in #629 but the solution did not work for me.

Any other ideas how to solve this?
Thanks.

**Comment by Aendrew87** [comment]
Any ideas? Do you need more information?

**Comment by rrjanbiah** [comment]
Yes @Aendrew87 

Have you tried all patches from https://github.com/RestyaPlatform/board/issues/611#issuecomment-214993918 ?

**Comment by Aendrew87** [comment]
@rrjanbiah, yes, i tried all patches but it still does not work

**Comment by rrjanbiah** [comment]
@Aendrew87 Strange. Have you cleared cache and or tried in incognito window?

If so, please give us some time to understand the issue.

**Comment by Aendrew87** [comment]
@rrjanbiah: After changing the sources i restarted nginx. I checked the fix on several browsers on multible systems. Allways the same result: Moving the card back to the old list i could see the comments, moving to another list the comments would not be displayed.

**Comment by rrjanbiah** [comment]
@Aendrew87 Really sorry for the trouble you are having. So this looks like an edge case. Will definitely try to reproduce it here. Sorry again.

Over the top of the head I think, it may be something to do with Unicode. Will check that too.

**Comment by rrjanbiah** [comment]
@Aendrew87 OK sure

**Comment by Aendrew87** [comment]
@rrjanbiah Yesterday I found the issue... I updated the files in /opt/ but since 0.2.1 it seems that the files are no longer stored in /opt - I Updated the right r.php and now it works - Sorry for the trouble
