### ISSUE TITLE
Time stamp displayed some irrelevant information.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#68]
Time stamp displayed some irrelevant information.

Refer the attachment
![time_stamp_issue](https://cloud.githubusercontent.com/assets/14884895/10309971/15f25434-6c5d-11e5-9b0e-249a58866b03.png)

**Comment by sathya313** [comment]
![time_stamp](https://cloud.githubusercontent.com/assets/14884895/10331002/5181e16c-6cef-11e5-9c3a-0e831e8241ec.png)

**Comment by rrjanbiah** [comment]
Fixed
