### ISSUE TITLE
Make a filter permanent

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#681]
From Vicente Gonzalez in forum https://groups.google.com/forum/#!topic/restya/7-siUv7msVw

I lost my filters if, for example, reload the web or close a card. Is it possible to make permanent that filter?

**Comment by Zimeon-** [comment]
Sounds like a good idea

**Comment by rrjanbiah** [comment]
@Zimeon- Sure

**Comment by lmarikannan** [comment]
Fixed in this commit d9fe36a
