### ISSUE TITLE
Install Restyaboard

### ISSUE THREAD

**Issue by superjuve** [RestyaPlatform/board#682]
#Hi, 
I cant install Restyboard. I followed this manual http://restya.com/board/install#Installscript.

##  Here is what I did:
1) **Installed Ubuntu Server** 16.04 on my VM Virtual Box.
2) **wget https://github.com/RestyaPlatform/board/raw/master/restyaboard.sh --no-check-certificate**
3) **Execute chmod +x restyaboard.sh**
4) **Execute restyaboard.sh**  - It was ok.

5) I Downloaded https://github.com/RestyaPlatform/board/releases/tag/v0.2.1
   a) **sudo apt-get install unzip**
   b) **unzip file.zip -d destination_folder**

What I have to do next step?

Thank you very much for help.

**Comment by rrjanbiah** [comment]
@superjuve Can you attach install log?

Do you have `root` access?

**Comment by superjuve** [comment]
Yes I have root access.

**Comment by rrjanbiah** [comment]
@superjuve Please attach install log? If you don't have install log, please attach some screenshot to show what error are you getting

**Comment by superjuve** [comment]
@rrjanbiah Last point I did was **Execute: sh restyaboard.sh** 
I am not sure if I did properly. I set server: 192.10.10.1
and I set directory: /usr/share/nginx/html/restyaboard

Where I can see if I did correctly?

**Comment by superjuve** [comment]
I think problem is in, I have to change everything insteas DBPORT?

POSTGRES_DBHOST=localhost
POSTGRES_DBNAME=restyaboard
POSTGRES_DBUSER=restya
POSTGRES_DBPASS=hjVl2!rGd
POSTGRES_DBPORT=5432

**Comment by rrjanbiah** [comment]
@superjuve Looks like you've fixed above issues? What was the culprit?

**Comment by superjuve** [comment]
@rrjanbiah I tried delete installation and installed again.
