### ISSUE TITLE
Card divider is missing in windows 8.1

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#69]
Card divider is missing in windows 8.1

Refer the attachment
![card_divider](https://cloud.githubusercontent.com/assets/14884895/10310433/9701e11e-6c5f-11e5-8432-da3cea3a419b.png)

**Comment by ktdmedia** [comment]
Also missing in Chrome OS X. 

You can click the full screen icon next to the X for a quick fix though.

**Comment by rrjanbiah** [comment]
@ktdmedia Thanks for your report.

@sathya313 Please make a note on it.

**Comment by rrjanbiah** [comment]
Fixed
