### ISSUE TITLE
Empty page after installation

### ISSUE THREAD

**Issue by rootAmeen** [RestyaPlatform/board#691]
Hi. 
I did the installation from the bash script, and after accessing the website I see the title and favicon (restyaboard powered kanban board), but the page is empty. 

Attached is the installation output.

Thanks.

[restyaboard_install.log.txt](https://github.com/RestyaPlatform/board/files/326815/restyaboard_install.log.txt)

**Comment by rrjanbiah** [comment]
@rootAmeen Sorry for the delay, we're busy with release process...

Can you check developer console and find HTTP requests?

### Common issues:

- 502 status usually means that php-fpm has not started
- 404 or 401 status usually means that database credentials are wrong. You may check further errors by enabling debug mode in https://github.com/RestyaPlatform/board/blob/master/server/php/config.inc.php#L15 and by checking HTTP response headers.

**Comment by rootAmeen** [comment]
hi @rrjanbiah ...
In the log I've already attached, php-fpm was already started by your installation script (lines 420-435):

`  Verifying  : automake-1.11.1-4.el6.noarch                                 1/4 
  Verifying  : php-devel-5.3.3-47.el6.x86_64                                2/4 
  Verifying  : php-fpm-5.3.3-47.el6.x86_64                                  3/4 
  Verifying  : autoconf-2.63-5.1.el6.noarch                                 4/4 

Installed:
  php-devel.x86_64 0:5.3.3-47.el6         php-fpm.x86_64 0:5.3.3-47.el6        

Dependency Installed:
  autoconf.noarch 0:2.63-5.1.el6         automake.noarch 0:1.11.1-4.el6        

Complete!
++ service php-fpm start
Starting php-fpm: [60G[[0;32m  OK  [0;39m]
++ chkconfig --levels 35 php-fpm on`

For database credentials, I used the default ones provided by your script too because I'm currently testing this product on a VM (line 3158-3160) in the log:

`++ echo 'Creating PostgreSQL user and database...'
Creating PostgreSQL user and database...
++ psql -U postgres -c 'CREATE USER restya WITH ENCRYPTED PASSWORD '\''hjVl2!rGd'\'''`

For debugging, I've set:
`define('R_DEBUG', true);`
in /usr/share/nginx/html/restyaboard/server/php/config.inc.php

But still when I open the page I get a white page. 

HTTP Headers when accessing the page:

`Request URL:http://172.16.50.128/
Request Method:GET
Status Code:200 OK
Remote Address:172.16.50.128:80
Response Headers
view source
Cache-Control:must-revalidate
Cache-Control:public
Cache-Control:max-age=604800
Connection:keep-alive
Content-Encoding:gzip
Content-Type:text/html
Date:Wed, 22 Jun 2016 14:10:10 GMT
Expires:Wed, 29 Jun 2016 14:10:10 GMT
Last-Modified:Tue, 21 Jun 2016 22:19:45 GMT
Server:nginx/1.0.15
Transfer-Encoding:chunked
Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8,ar;q=0.6
Cache-Control:no-cache
Connection:keep-alive
Cookie:gsScrollPos=
DNT:1
Host:172.16.50.128
Pragma:no-cache
Upgrade-Insecure-Requests:1`

**Comment by rootAmeen** [comment]
Any update @rrjanbiah

**Comment by rrjanbiah** [comment]
@rootAmeen Sorry, will update you by Monday

**Comment by lmarikannan** [comment]
@rootAmeen We checked your restyaboard_install.log, We can't find any issues on that. Can you post your HTTP responses and requests?

**Comment by lmarikannan** [comment]
@rootAmeen Closing this for now. If you get any issues, please feel free to reopen.
