### ISSUE TITLE
In organization page, If we click activities got an 404 error page.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#70]
In organization page, If we click activities got an 404 error page.

1.login as hanith/testing
2.In home page==>click organization page
3.click "party organization"
4.In members option==>if we click activities
5.Got an 404 error page

Refer the attachment
![404_err_page](https://cloud.githubusercontent.com/assets/14884895/10310880/d46778c8-6c61-11e5-9e6b-ea6c126d3e26.png)

**Comment by rrjanbiah** [comment]
Fixed
