### ISSUE TITLE
Start date to accompany due date

### ISSUE THREAD

**Issue by Zimeon-** [RestyaPlatform/board#701]
Now that the gant chart work with version 0.3 i received a request from our users that a start date to accompany the due date would be greatly appreciated. This way team members could add a card, set a start and due date to follow them up.

**Comment by rrjanbiah** [comment]
@Zimeon- That will be a good feature. Thanks for your suggestion.

**Comment by julienmoinard** [comment]
Yes it will be very usefull. Thank you

**Comment by lmarikannan** [comment]
Done in our dev branch.
