### ISSUE TITLE
Boards : 404 Page not found.

### ISSUE THREAD

**Issue by tsebastien** [RestyaPlatform/board#703]
Hello !
Since the update to 0.3, here is my issue:

the page boards/list?page=1 give me a 404 error.
and the logs: 

[error] 1484#0: *239 FastCGI sent in stderr: "PHP message: PHP Warning:  pg_query_params(): Query failed: ERROR:  relation &quot;admin_boards_listing&quot; does not exist
LINE 1: SELECT row_to_json(d) FROM (SELECT * FROM admin_boards_listi...
                                                  ^ in /usr/share/nginx/html/server/php/R/r.php on line 1309" while reading response header from upstream

the board is running on ubuntu 14.04.

Thank you,

Seb

**Comment by rrjanbiah** [comment]
@tsebastien Sorry notice this issue just now. Were you able to figure out the issue? If so, what was the issue?

**Comment by tsebastien** [comment]
Hello,
Thank you for your answer.

The error was that the installation of GeoIP package on ubuntu creates a new folder, and that the installation script checks "mkdir  /usr/share/GeoIP" result which gives an error because the folder was created automatically earlier. Because everything seemed to work and because the "about" page was updated, I though that the upgrade was complete and that I was facing an issue to post.

After commenting 
```
                               if [ $? != 0 ]                                                                                        
                               then                                                                                                  
                                       echo "GeoIP folder creation failed with error code 52"                                        
                                       exit 1                                                                                        
                               fi 
```

the script ran till the end and resolve the issue.

Thank you for your concerns,

ST
