### ISSUE TITLE
search not working after update to 0.3

### ISSUE THREAD

**Issue by tsebastien** [RestyaPlatform/board#704]
Hello,

After the update, the search is not working anymore... here are my logs:

PHP message: PHP Notice:  Undefined index: aggregations in /usr/share/nginx/html/server/php/R/r.php on line 932
PHP message: PHP Notice:  Undefined index: aggregations in /usr/share/nginx/html/server/php/R/r.php on line 934
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/html/server/php/R/r.php on line 934
PHP message: PHP Notice:  Undefined index: aggregations in /usr/share/nginx/html/server/php/R/r.php on line 958
PHP message: PHP Notice:  Undefined index: aggregations in /usr/share/nginx/html/server/php/R/r.php on line 960

Thank you for your help,
ST

**Comment by rrjanbiah** [comment]
@tsebastien Sorry for the issue you're facing. We'll check tomorrow and will update you.

**Comment by lmarikannan** [comment]
@tsebastien Can you please check `indexing_to_elasticsearch` cron is running or not?

**Comment by tsebastien** [comment]
Thank you for your fast answers.

There is no indexing_to_elasticsearch in the crontab. 
I added it, and nothing changed...

**Comment by lmarikannan** [comment]
@tsebastien please check server URL, index name is filled on your restyaboard elasticsearch settings page. And then execute `https://github.com/RestyaPlatform/board/blob/master/server/php/shell/instant_email_notification.sh` file manually on your server

**Comment by tsebastien** [comment]
Thank for your answer.
After changing updating my configuration here are my logs when i try to search something:

2016/07/08 12:44:24 [error] 3636#0: *1468 open() "/usr/share/nginx/html/client/restya/cards/_search" failed (2: No such file or directory), client: _myip_, server: _, request: "POST /restya/cards/_search?size=10 HTTP/1.1", host: "_myhost_"

etc.

2016/07/08 12:44:24 [error] 3636#0: *1244 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: aggregations in /usr/share/nginx/html/server/php/R/r.php on line 932
PHP message: PHP Notice:  Undefined index: aggregations in /usr/share/nginx/html/server/php/R/r.php on line 934
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/html/server/php/R/r.php on line 934
PHP message: PHP Notice:  Undefined index: aggregations in /usr/share/nginx/html/server/php/R/r.php on line 958
PHP message: PHP Notice:  Undefined index: aggregations in /usr/share/nginx/html/server/php/R/r.php on line 960
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/html/server/php/R/r.php on line 960" while reading response header from upstream, client: _myip_, server: _, request: "GET /api/v1/search.json?q=test&token=469455049aedbef432551b2b7f85ce817dc10ff6 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "_myhost_", referrer: "_my_adress_"

**Comment by lmarikannan** [comment]
We have tried to reproduce this issue in local but we cannot able to reproduce it. Can you please double check that?

>  And then execute https://github.com/RestyaPlatform/board/blob/master/server/php/shell/instant_email_notification.sh file manually on your server

Please execute `instant_email_notification.sh` file manually on your server

**Comment by tsebastien** [comment]
I did a double check on the instant_email_notification.sh. No error appears at the execution of the script.

When cron runs indexing_to_elasticsearch, here are my logs:

2016/07/08 15:16:57 [error] 15443#0: *933 "/usr/share/nginx/html/client/restya/cards/index.html" is not found (2: No such file or directory), client: _myip_, server: _, request: "POST /restya/cards/ HTTP/1.1", host: "_myhost_"
2016/07/08 15:16:57 [error] 15443#0: *934 open() "/usr/share/nginx/html/client/restya/cards/22" failed (2: No such file or directory), client: _myip_, server: _, request: "POST /restya/cards/22 HTTP/1.1", host: "_myhost_"
..
..
etc.

**Comment by lmarikannan** [comment]
Can you please execute the url `http://{your_host}/server/php/shell/indexing_to_elasticsearch.php` manually and check

**Comment by tsebastien** [comment]
Here is my result for executing manually http://{your_host}/server/php/shell/indexing_to_elasticsearch.php:

Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found. Not Found.

**Comment by rrjanbiah** [comment]
Internal note: Issue related to #422 Can't diagnose error without proper error handling.

**Comment by rrjanbiah** [comment]
@tsebastien Sorry for the issue. We'll need to add error handling in the script so as to diagnose the issue. We'll push fixed version and from there you may be able to figure out the issue easily.

**Comment by MaDie** [comment]
I'm facing the same issue, elastic search is installed, the shell script output "Successfully saved".

It seems that the error only appears when searching without a key like "test". With "name:test" it works.

**Comment by rrjanbiah** [comment]
> I'm facing the same issue, elastic search is installed, the shell script output "Successfully saved".
> 
> It seems that the error only appears when searching without a key like "test". With "name:test" it works.

@MaDie That looks like a different issue. Anyway, will check that too

**Comment by keky** [comment]
anyway to solve this problem?thx

**Comment by rrjanbiah** [comment]
@lmarikannan FYI...

**Comment by lmarikannan** [comment]
Added additional handling for indexing ElasticSearch in this commit https://github.com/RestyaPlatform/board/commit/fdffe1f5809af718567798e16134cce5a94269c9 and handled undefined problem in this commit https://github.com/RestyaPlatform/board/commit/f0eff389a8f72fcf2c8a269a0c72afc2151ee132.
