### ISSUE TITLE
#/settings/3 not working after update to 0.3

### ISSUE THREAD

**Issue by tsebastien** [RestyaPlatform/board#705]
Hello,

Since my update to 0.3, the page #/settings/3 is not working anymore.
Do you have any ideas about the problem ?
Here are my logs:
 

message: PHP Notice:  Constant BOSH_SERVICE_URL already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice:  Constant JABBER_HOST already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice:  Constant XMPP_CLIENT_RESOURCE_NAME already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice:  Constant BOSH_SERVICE_URL already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice:  Constant JABBER_HOST already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice:  Constant XMPP_CLIENT_RESOURCE_NAME already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice:  Constant DEFAULT_CARD_VIEW already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice:  Constant TODO already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice:  Constant DOING already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice:  Constant DONE already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62" while reading response header from upstream, client: 178.234.45.5, server: _, request: "GET /api/v1/settings.json?token=fda564cc44520d16da55940ee3994f4c45a86949&_=1467969980270 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "myhost.com", referrer: "http://myhost.com/"
2016/07/08 11:26:17 [error] 3638#0: *381 FastCGI sent in stderr: "PHP message: PHP Notice:  Constant DEFAULT_CARD_VIEW already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62

Thank you so much for your help,
ST

**Comment by lmarikannan** [comment]
@tsebastien Really sorry for the trouble you are having. 

> message: PHP Notice: Constant BOSH_SERVICE_URL already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice: Constant JABBER_HOST already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice: Constant XMPP_CLIENT_RESOURCE_NAME already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice: Constant BOSH_SERVICE_URL already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice: Constant JABBER_HOST already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice: Constant XMPP_CLIENT_RESOURCE_NAME already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice: Constant DEFAULT_CARD_VIEW already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice: Constant TODO already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice: Constant DOING already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62
PHP message: PHP Notice: Constant DONE already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62" while reading response header from upstream, client: 178.234.45.5, server: , request: "GET /api/v1/settings.json?token=fda564cc44520d16da55940ee3994f4c45a86949&=1467969980270 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "myhost.com", referrer: "http://myhost.com/"
2016/07/08 11:26:17 [error] 3638#0: *381 FastCGI sent in stderr: "PHP message: PHP Notice: Constant DEFAULT_CARD_VIEW already defined in /usr/share/nginx/html/server/php/config.inc.php on line 62

Can you please execute the following queries on your postgres server

`delete from settings where name in ('TODO', 'DOING', 'DONE') and setting_category_id = 3;
delete from settings where id in (select id from settings where name = 'DEFAULT_CARD_VIEW' and setting_category_id = 3 order by id desc limit 1);
delete from settings where id in (select id from settings where name  in ('XMPP_CLIENT_RESOURCE_NAME', 'JABBER_HOST', 'BOSH_SERVICE_URL') and setting_category_id = 11 order by id desc limit 3);
delete from settings where id in (select id from settings where name = 'chat.last_processed_chat_id' and setting_category_id = 0 order by id desc limit 1);
delete from setting_categories where id in (select id from setting_categories where name = 'Cards Workflow' order by id desc limit 1);`

**Comment by tsebastien** [comment]
Thank for your help, It worked perfectly.
