### ISSUE TITLE
PHP notices in recent versions

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#706]
Undefined index and similar notices in recent versions.

**Comment by lmarikannan** [comment]
https://github.com/RestyaPlatform/board/commit/915fee746c927bd43bf4613391e8eaa5ea3d48fd 

https://github.com/RestyaPlatform/board/commit/0791d9bdd3631088c163b02d0315396acb95e9b7

Fixed in dev branch
