### ISSUE TITLE
Install on Xampp (Windows 10)

### ISSUE THREAD

**Issue by eddyemmer** [RestyaPlatform/board#707]
Hi,

I moved the files to my Xampp root directory and the only thing I see is a white screen.

Can somebody help me step by step with installing Restya Board on Xampp or Wampserver?

Thanks a lot!!

**Comment by rrjanbiah** [comment]
@eddyemmer In Windows 10, it shouldn't be an issue. Can you enable debug mode and check for any errors in HTTP header and response?

**Comment by lmarikannan** [comment]
@eddyemmer We are waiting for your reply

**Comment by lmarikannan** [comment]
@eddyemmer You may try this https://github.com/RestyaPlatform/board/issues/224#issuecomment-184282834 (Please note that the attached files are outdated now) and also refer #509.

Closing this for now. If you get any issues, please feel free to reopen.

**Comment by KhomRud** [comment]
@lmarikannan @rrjanbiah 
Could you explain where I need to put configuration files?
For Win10, XAMPP (Apache).

I download latest built file to root directory
Then where must be .htaccess file and restyaboard.conf?
In http://restya.com/board/docs/windows you use PostgreSQL, could you say what to do with MySQL in XAMPP?

Sorry for stupid questions.

**Comment by rrjanbiah** [comment]
Reopening missed out question due to status

**Comment by lmarikannan** [comment]
Updated on restya.com windows documentation - http://restya.com/board/docs/windows

**Comment by tgly307** [comment]
the link is 404 ...

**Comment by lmarikannan** [comment]
@tgly307 Sorry for that, now the issue is fixed

**Comment by tgly307** [comment]
Thx reply and work




| |
tgly307
邮箱：tgly307@163.com
|

签名由 网易邮箱大师 定制

On 04/09/2018 14:07, lmarikannan wrote:

@tgly307 Sorry for that, now the issue is fixed
