### ISSUE TITLE
Migration Debian v0.2.1 to v0.3

### ISSUE THREAD

**Issue by petman** [RestyaPlatform/board#708]
Hi, 

I have try to migrate v0.2.1 to v0.3 and I have some issue. 

I have change :
* my directory /var/www with the new files
* Update the script /sql/upgrade-0.2.1-0.3.sql
* Run the sql command on https://github.com/RestyaPlatform/board/issues/705

My error file /var/log/nginx/error.log is telling me : 

"/var/www/board/client/css/bootstrap.css" failed (2: No such file or directory)
"/var/www/board/client/js/templates/templates.js" failed (2: No such file or directory)
"/var/www/board/client/js/templates/templates.js" failed (2: No such file or directory)
"/var/www/board/client/restyaboard/api/v1/settings.json" failed (2: No such file or directory)

The file really not exist on the master file.zip or on tag 0.3 file.zip.

I have done initialy the install from front website : 
https://raw.githubusercontent.com/RestyaPlatform/board/master/restyaboard.sh

with the version 0.2.1 there is few days.

Can you advise ? 

Regards

**Comment by lmarikannan** [comment]
Hi, you can also update restyaboard with this script `https://raw.githubusercontent.com/RestyaPlatform/board/master/restyaboard.sh`. Execute this script  `https://raw.githubusercontent.com/RestyaPlatform/board/master/restyaboard.sh`, and it will ask `A newer version ${RESTYABOARD_VERSION} of Restyaboard is available. Do you want to get it now y/n?`.  So please try to migrate with above script.

**Comment by rrjanbiah** [comment]
@petman Was above note helpful?

**Comment by petman** [comment]
Yes it is work !! 

thanks
