### ISSUE TITLE
Issue with default admin login and user login

### ISSUE THREAD

**Issue by fubujo** [RestyaPlatform/board#709]
I just installed restyaboard 0.3. 

I attempt to login as admin/restya and I get the "login failed" modal.
I create and activate a user (via the standard email processes), but then try to login and get the "login failed" modal.

I've checked the database and the users exist.

Any suggestions?

**Comment by rrjanbiah** [comment]
@fubujo As replied in the forum https://groups.google.com/forum/#!topic/restya/tJ050sUq4U0

Have you modified the security salt?

**Comment by fubujo** [comment]
No. The SECURITY SALT in config.inc.php was not changed.  In fact all install was done with default values (no modifications to files).  

It's not production.  I don't mind dropping the database and rebuilding the DB from scripts.  Is that a recommended suggestion?   Would that just be running restyaboard_with_empyt_data.sql and v0.3.sql ... and that is it?

**Comment by rrjanbiah** [comment]
@fubujo Yes, resetting DB should also work

**Comment by fubujo** [comment]
Thanks. I will give a try and report back in case it helps other users. Sorry for the double post - wasn't sure how the team preferred discussion points.  Will report back soon.

**Comment by rrjanbiah** [comment]
@fubujo No problem. You're always welcome.

**Comment by lmarikannan** [comment]
@fubujo Were you able to find solution?

**Comment by lmarikannan** [comment]
@fubujo Closing this for now. If you get any issues, please feel free to reopen.
