### ISSUE TITLE
due dates not imported from Trello

### ISSUE THREAD

**Issue by rozcietrzewiacz** [RestyaPlatform/board#711]
I have a lot of cards with due days assigned in Trello, but unfortunately it seems that RestyaBoard does not understand them when importing :(

**Comment by rrjanbiah** [comment]
@rozcietrzewiacz Is it happening for all cards? Or only for few cards?

**Comment by rozcietrzewiacz** [comment]
@rrjanbiah Yes, so far it seems the problem affects all cards. I did another test with additional cards and lists with and without special characters (thought may be related to #710), but none of the dates appeared in calendar.

**Comment by rrjanbiah** [comment]
@rozcietrzewiacz Strange. Will look into it as soon as possible.

**Comment by lmarikannan** [comment]
Fixed in dev branch
