### ISSUE TITLE
Can't login after executation of the sql upgrade script!

### ISSUE THREAD

**Issue by Samunosuke** [RestyaPlatform/board#713]
The database script did create doubled entries and I was not able to login.
There are many tables which have doubled entries because they do not use a primary key!!!

organization_user_roles
acl_organization_links_organizations_user_roles
acl_links_roles
acl_links
board_stars
...

I did check the tables manually with an SQL tool and I did remove the doubled entries - after that I was able to login again.
So please alter the tables to use primary keys - this will prevent headache for a lot of users for now and in future

**Comment by Samunosuke** [comment]
I have also found out that there are already doubled entries in the db create script. So please check and clean them. Better... Use primary keys - this would simply be impossible.

**Comment by lmarikannan** [comment]
@samunosuke Really sorry for the trouble you are having. It is related to issue #705. Can you please refer this issue #705

**Comment by lmarikannan** [comment]
https://github.com/RestyaPlatform/board/commit/915fee746c927bd43bf4613391e8eaa5ea3d48fd Fixed in dev branch.

**Comment by donat1** [comment]
Can you tell me, which tool you used, since I have the same problem. I can't remove double entrys without primary key in the phppgadmin.

**Comment by lmarikannan** [comment]
@donat1 We have not used any tool to identify the double entries and we have provided solution query based on your error log.
