### ISSUE TITLE
Session info is stored per tab

### ISSUE THREAD

**Issue by darkblinded** [RestyaPlatform/board#714]
This is one of the biggest usability issues for me: The access_token is stored in the session storage and therefor exists on a per tab basis. This means one has to log in again for every new tab.

**Comment by darkblinded** [comment]
Any thoughts on this issue? I consider this a **major** usability flaw. Basically this is the main reason (aside from #672), why I currently choose Wekan over Restyaboard.

**Comment by rrjanbiah** [comment]
@darkblinded Moving from sessionStorage to cookie may be a simple fix. But, few of our enterprise users prefer this behavior as it allows login to multiple accounts easily. Moreover may people prefer to use it within the dockmodal--instead of opening cards in another tab. One workaround in Chrome is that you have to "duplicate" the tab. 

Having said, we may change this behavior only when there is more demand.

**Comment by darkblinded** [comment]
Do your enterprise customers know they can use multiple accounts their your browser's incognito mode?

This is not about opening cards in new tabs - it is about a behaviour **every other web application** offers. You could place an option to disable session cookies in the settings, but I really think you should make session cookies the default choice as it is the expected behaviour.

**Comment by rrjanbiah** [comment]
@darkblinded Thanks for your concern. If you're so particular about the behavior, replacing `sessionStorage` with `localStorage` across all files may bring such behavior. Please note that this suggestion is not tested, so take a backup before you replace.

**Comment by Phanvyvt** [comment]
Hi @rrjanbiah, @darkblinded,
Can you instruct me to replace sessionStorage with localStoraga? Where am I supposed to replace it? Many thanks!

**Comment by darkblinded** [comment]
@Phanvyvt  you really should not to this. This stuff belongs in session cookies for good reasons. I hope @rrjanbiah will reconsider this.

**Comment by rrjanbiah** [comment]
@darkblinded @Phanvyvt We have decided to add this support. Please stay for next update.

**Comment by Phanvyvt** [comment]
@rrjanbiah: Thank you so much ^^

**Comment by lmarikannan** [comment]
Stored login data in cookies.
