### ISSUE TITLE
"Copy Checklist From" feature stores list items in wrong card/list

### ISSUE THREAD

**Issue by darkblinded** [RestyaPlatform/board#715]
When I add a new checklist to a card A using the "Copy Checklist From" feature to copy the checklist from a card B, everything seems to work fine untill I refresh the page. Afterwards there is no "checklist flag" on card A and the flag on card B shows doubled items. If I open card A there is an empty checklist (also showing progress if I checked items before refreshing) and on card B there is the same checklist as before. If I then remove the empty checklist of card A and refresh, card B shows the the right amount of items.

**Comment by lmarikannan** [comment]
Fixed in dev branch
