### ISSUE TITLE
Can not delete comment after added

### ISSUE THREAD

**Issue by Phanvyvt** [RestyaPlatform/board#716]
After added comment, I click 'Delete' button. But nothing to do.

![deletecomment](https://cloud.githubusercontent.com/assets/20571434/17011623/f7b4d530-4f39-11e6-83c1-f495151eb962.png)

**Comment by BlackDuck888** [comment]
Same at my installation, ubuntu 16.04, php7 release 0.30

**Comment by lmarikannan** [comment]
Fixed in dev branch
