### ISSUE TITLE
Latest release (0.30) containing old translations

### ISSUE THREAD

**Issue by BlackDuck888** [RestyaPlatform/board#719]
The Translation distributed in 0.30 does not reflecting the current or older state of transiflex.

**Comment by lmarikannan** [comment]
Changes done.

**Comment by BlackDuck888** [comment]
From where did you took the german translation? I did a pull request with the current state of transiflex with a good state of translation.

The translation which is used by you is realy bad. Some examples.

"(current)": "(Strom)",  -> the translation from current to Strom is correct in context of electricity current = Strom, voltage = Spannung
"About": "Etwa",  Etwa is more meaning approximately than about, correct word ist Über
"Count": "Graf", realy funny. Graf = earl
"Due in the next month": "Durch in den nächsten Monat",  durch = through

**Comment by rrjanbiah** [comment]
@lmarikannan Ready above note, FYI

**Comment by lmarikannan** [comment]
@BlackDuck888  We are not able to merge your pull request due to conflicts. Can you please resolve the conflicts and update?

**Comment by BlackDuck888** [comment]
>This branch has conflicts that must be resolved
>Only those with write access to this repository can merge pull requests.

i can't i have no write access to your repository

copy the file manually, it is just one file https://github.com/BlackDuck888/board/tree/contrib/translation/ger/client/locales/de

**Comment by lmarikannan** [comment]
@BlackDuck888 Fixed in dev branch
