### ISSUE TITLE
ejabber.yml is not included in Release 0.30

### ISSUE THREAD

**Issue by BlackDuck888** [RestyaPlatform/board#720]
The install script tries to copy the jabber config, but it is not included in this release file.

https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh#L1403

**Comment by Aendrew87** [comment]
Could confirm that

When downloading the package (master) vom github it is included.
The installer downloades the package from 'http://restya.com/download.php?app=board&ver=v0.3' and here the file is missing.

There are many other files missing or different between the both packages.

**Comment by lmarikannan** [comment]
https://github.com/RestyaPlatform/board/blob/dev/ejabberd.yml included in dev branch

**Comment by lmarikannan** [comment]
Closing this for now

**Comment by Aendrew87** [comment]
@lmarikannan just to get sure: in the main branch the file allready exists since two months but it does not exist in the board-v0.3.zip

**Comment by BlackDuck888** [comment]
correct, it is missing in the release packed, an if you run the installer it yield some error messages

**Comment by Aendrew87** [comment]
so I dont know if this issue is really solved yet

**Comment by BlackDuck888** [comment]
no it is not, the current release zip does not contain the yml, or the other way is to change the restyaboard.sh to download the yml direct from github.

**Comment by Aendrew87** [comment]
@lmarikannan could you please verify if your solution works or reopen the ticket. thanks.

**Comment by lmarikannan** [comment]
@Aendrew87, @BlackDuck888  Yes, current release zip does not contain the ejabberd.yml. In our next release, we should be wrap with ejabberd.yml. So please download it from master branch and setup this manually now. thanks.
