### ISSUE TITLE
restyaboard.sh fails on ubuntu 14.04 VM

### ISSUE THREAD

**Issue by sixmokes** [RestyaPlatform/board#721]
Hello,

We were installing restyaboard for testing when the restyaboard.sh script failed:

The following packages have unmet dependencies:
 php5-imap : Depends: phpapi-20100525
             Depends: php5-common (= 5.4.45-0+deb7u4) but 5.5.9+dfsg-1ubuntu4.17 is to be installed
E: Unable to correct problems, you have held broken packages.
++ '[' 100 '!=' 0 ']'
++ echo 'php5-imap installation failed with error code 11'
php5-imap installation failed with error code 11
++ exit 1

The script was run as root on a virtual machine with a fresh install of Ubuntu 14.04 server.

Please advise.

[restyaboard_install_log.txt](https://github.com/RestyaPlatform/board/files/385028/restyaboard_install_log.txt)

**Comment by rrjanbiah** [comment]
@sixmokes Sorry for the trouble. We came to know that of late Ubuntu is shipping php7 by default and so this is related to that. We're working to test it in Ubuntu.

**Comment by sixmokes** [comment]
Thank you for the reply. Is there a recommended Linux distribution?

**Comment by rrjanbiah** [comment]
@sixmokes Sorry, should work on any Linux (that's what we're aiming for). BTW, we're on Fedora

**Comment by sixmokes** [comment]
Thank you for the reply. Here is the result of running the  restyaboard.sh script, run as root on a Fedora Server machine ( the image used was Fedora-Server-dvd-x86_64-24-1.2.iso)

++ yum install -y http://yum.postgresql.org/9.4/redhat/rhel-6.6-x86_64/pgdg-centos94-9.4-1.noarch.rpm
Yum command has been deprecated, redirecting to '/usr/bin/dnf install -y http://yum.postgresql.org/9.4/redhat/rhel-6.6-x86_64/pgdg-centos94-9.4-1.noarch.rpm'.
See 'man dnf' and 'man yum2dnf' for more information.
To transfer transaction metadata from yum to DNF, run:
'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'

Last metadata expiration check: 0:40:21 ago on Thu Jul 28 16:06:40 2016.
Error: nothing provides centos-release needed by pgdg-centos94-9.4-1.noarch
(try to add '--allowerasing' to command line to replace conflicting packages)
++ '[' 1 '!=' 0 ']'
++ echo 'Installing PostgreSQL 64 fail with error code 28'
Installing PostgreSQL 64 fail with error code 28
++ exit 1

**Comment by rrjanbiah** [comment]
@lmarikannan FYI

**Comment by mirhat** [comment]
@sixmokes Did you solve your problem on Ubuntu 14.04?

**Comment by lmarikannan** [comment]
@mirhat Sorry for the trouble. We are working on it and will update you shortly.

**Comment by fwolfst** [comment]
@rrjanbiah Some issue here. Note that the issue occurs on ubuntu 14.04 which ships with php5, afaik.

There are three versions of php5-imap found by my bare ubuntu 14.04 VM. I tried the following:
  
- install a non-conflicting php5-imap version manually with
  `sudo apt install php5-imap="5.4.6-0ubuntu5"`
- commented out all the parts of the install-script that were run already (including the php5-imap installation) and rerun it. I will update this post when process is finished.

**Comment by lmarikannan** [comment]
@sixmokes Regarding PostgreSQL installation on Fedora, please refer this URL  http://tecadmin.net/install-postgresql-on-centos-rhel-and-fedora/ and change the URL in line number `1089` in this file `restyaboard.sh` for your Fedora version and run the script again.

@fwolfst We have changed install script using this command to install PHP IMAP `sudo apt-get install php5-imap="5.4.6-0ubuntu5"`.

**Comment by lmarikannan** [comment]
@sixmokes Closing this for now. If you get any issues, please feel free to reopen.
