### ISSUE TITLE
Install script (Linux)

### ISSUE THREAD

**Issue by Aendrew87** [RestyaPlatform/board#726]
Some times you use 'apt-get install -y' but there are many cases were you only use 'apt-get install' so the user has to enter 'y' to continue.

Maybe you should put the '-y' to every apt-get command.

**Comment by lmarikannan** [comment]
@Aendrew87 Sorry for delay... 

apt-get install `-y` added in some places on `restyaboard.sh` file.

Fixed in dev branch
