### ISSUE TITLE
SMTP configuration - missing set +x

### ISSUE THREAD

**Issue by Aendrew87** [RestyaPlatform/board#727]
When installing the output is

> ++ echo 'Do you want to setup SMTP configuration (y/n)?'
> Do you want to setup SMTP configuration (y/n)?
> ++ read -r answer

Seams that the 'set +x' ist missing in the installation script.

Current version:
`echo "Do you want to setup SMTP configuration (y/n)?"`
`read -r answer`

Fixed version:
`set +x`
`echo "Do you want to setup SMTP configuration (y/n)?"`
`read -r answer`
`set -x`

**Comment by lmarikannan** [comment]
Changes done
