### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by jofr49** [RestyaPlatform/board#728]
I have an error during installation of nginx 

There is the error code= echo 'nginx installation failed with error code 2'

Maybe an error with authentication keys on repository ?

The try has been dogin with a vm (virtualbox) on ubuntu server 16-04

**Comment by Aendrew87** [comment]
@jofr49 what happens when you execut the following command
`apt-get install -y cron nginx`

Please attach install log of restyaboard.sh too.

**Comment by rrjanbiah** [comment]
@Aendrew87 Thanks for your help. Much appreciated.

**Comment by jofr49** [comment]
Sorry for delay. Thank you for your help, I can't try for now but I come back soon here to test your suggestion.

**Comment by BlackDuck888** [comment]
@Aendrew87 the installscript does not work with Ubuntu 16.10 very well, because 16.10 use newer packes as example php7. 

@jofr49 i'am working on a install script which is working with Ubuntu 16.01/15.10, Debian 8.5 and Rasbian 8. 

it will use apache.

i have to fix some problems with cron and ejabber settings right now, maybe mid next week i am ready for deploy.

**Comment by Aendrew87** [comment]
@BlackDuck888 in this case it is Ubuntu 16.4, not Ubuntu 16.10

**Comment by BlackDuck888** [comment]
@Aendrew87 i missed that Ubuntu 16.4 was named, but 16.4 packages more similar to 16.10 then 15.10. It uses php7 to like 16.10
 
@jofr49 what did `lsb_release -r -s` i need this information for my install script.

**Comment by jofr49** [comment]
@BlackDuck888  The lsb_release -r -s returned ubuntu 16.04.
Effectively I have tried to install restyaboard on debian 8.5, and don't have this trouble. I did not go further after installation but I can say that at least.

**Comment by michaelmcdonald** [comment]
I ran into the same problem as jofr49 and ran the command that aendrew87 requested. Here is the output of that command:

```
root@restyaboard:~# apt-get install -y cron nginx
Reading package lists... Done
Building dependency tree
Reading state information... Done
cron is already the newest version (3.0pl1-128ubuntu2).
The following additional packages will be installed:
  fontconfig-config fonts-dejavu-core libfontconfig1 libgd3 libjbig0 libjpeg8 libtiff5 libvpx3 libxpm4 nginx-common nginx-core
Suggested packages:
  libgd-tools fcgiwrap nginx-doc
The following NEW packages will be installed:
  fontconfig-config fonts-dejavu-core libfontconfig1 libgd3 libjbig0 libjpeg8 libtiff5 libvpx3 libxpm4 nginx nginx-common nginx-core
0 upgraded, 12 newly installed, 0 to remove and 9 not upgraded.
Need to get 2,875 kB of archives.
After this operation, 9,186 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libjpeg8
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
```

Also attached the log.
[restyboard_install.txt](https://github.com/RestyaPlatform/board/files/442504/restyboard_install.txt)

**Comment by BlackDuck888** [comment]
@michaelmcdonald you can try my installscript from https://github.com/BlackDuck888/board/tree/contrib/installscript/install maybe this work better for you

**Comment by lmarikannan** [comment]
Install script upgraded to PHP 7 and fixed in this commit https://github.com/RestyaPlatform/board/commit/14c8d56818098b3ed56709e419d8e04ab29a3e44, https://github.com/RestyaPlatform/board/commit/d0356b2231c061b6c8adc804f691de0e63937f2b
