### ISSUE TITLE
If we move any card with attachment to another board, The attachment doesn't display in another board list page.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#73]
1.login as parthi/testing1
2.In home page==>demo board
3.In listing page==>status "new" card==>add any card with attachment image
4.After adding the card==>click settings==>actions==>move option
5.If we move the card to trello board listing page
6.The attached image doesn't display in trello listing page

**Comment by rrjanbiah** [comment]
Fixed
