### ISSUE TITLE
No medium_thumb

### ISSUE THREAD

**Issue by Aendrew87** [RestyaPlatform/board#733]
I upgraded from 0.2.1 to 0.3.0 and the medium_thumb after the login is missing.

So I tried to update my profile picture but the medium_thumb does still not exist.

What can I do to create it?

**Comment by lmarikannan** [comment]
@Aendrew87 Sorry for the delay...

Thumbnail creation requires ImageMagick or GD. Probably, you may be missing them. Or, there may be some memory issue when it creates thumbnail. Try increasing the memory limit.

Also, img folder needs write permission for saving thumbnails.

Please try enabling debug mode and see if you're getting any error message in the page or in HTTP header.

**Comment by Aendrew87** [comment]
@lmarikannan How to enable debug mode?

**Comment by lmarikannan** [comment]
To enable debug mode, please udpate `false` to `true` in https://github.com/RestyaPlatform/board/blob/master/server/php/config.inc.php#L15 and post HTTP response header and response (In Firebug or Chrome's Developer tool)

**Comment by Aendrew87** [comment]
@lmarikannan thx, i will check that tomorrow

**Comment by Aendrew87** [comment]
@lmarikannan there where a few wrong permissions - I changed them but the medium_thumb on my boards overview was still missing - After updating my profile image the medium_thumb was displayed

Is this working as designed?

**Comment by lmarikannan** [comment]
@Aendrew87 Yes, this is working as designed. Because medium_thumb did not created without permissions. So need to update profile image, then only it'll be display

**Comment by Aendrew87** [comment]
ok, thx
