### ISSUE TITLE
slow rendering

### ISSUE THREAD

**Issue by MaDie** [RestyaPlatform/board#738]
we use restyaboard now since version 0.1.3 and have in sum 800 cards in 14 boards. it seems that the client is getting slower and slower.  when i click on a checklist item to mark it done, i have to wait up to 10 seconds until the click is executed.

i attached a screenshot of the chrome javascript profiler to show what i mean. perhaps there is a possibility to improve the client performance.

![image](https://cloud.githubusercontent.com/assets/4627758/17365658/a16181ee-5987-11e6-9890-6073fa8af811.png)

**Comment by rrjanbiah** [comment]
@MaDie Do you have any plugins activated? Can you please check if disabling any plugins improve the performance?

**Comment by MaDie** [comment]
@rrjanbiah thats a screenshot with a chrome without any plugins

![image](https://cloud.githubusercontent.com/assets/4627758/17392095/39a1df92-5a1b-11e6-9d15-dbf4f8c34a27.png)

**Comment by lmarikannan** [comment]
@MaDie Sorry for delay, and thanks for your report. We'll fix it soon.

**Comment by lmarikannan** [comment]
Related to #661. Fixed in this commit https://github.com/RestyaPlatform/board/pull/854/commits/65a4b9bb1d6a0363c997d117fca4f407c2468b67.
