### ISSUE TITLE
instant add card / add members

### ISSUE THREAD

**Issue by MaDie** [RestyaPlatform/board#739]
When adding members in the instant add card screen, the filter textfield is hidden because of to many members. perhaps limit the member list?

![image](https://cloud.githubusercontent.com/assets/4627758/17365798/6c362924-5988-11e6-8f09-860a71f7756d.png)

**Comment by rrjanbiah** [comment]
@MaDie Thanks for your report. We'll look into it.

@lmarikannan Please crosscheck with trello about this behavior

**Comment by lmarikannan** [comment]
Fixed in dev branch
