### ISSUE TITLE
Mail encoding with Non-ASCII characters and datetime

### ISSUE THREAD

**Issue by Zimeon-** [RestyaPlatform/board#742]
Here's what you missedâ€¦
MÃ– 
Mi Ã–ster updated item name as nnnnnn, -> SiirretÃ¤Ã¤n syyskuuulle.

should be:

MÖ
Mi Öster updated item name as nnnnnn. -> Siirretään syyskuulile.

Just a guess, missing headers with charset?

Also date seems to be epoch, the subject shows as following:
2 new notifications since 01:00 AM (January 1, 1970)

**Comment by Zimeon-** [comment]
The time seems to have it's root cause from the user not having a timezone set, mayby add a fallback timezone?
Line 345 on instant_email_notification.php
$emailFindReplace['##SINCE##'] = date("h:i A (F j, Y)", strtotime($user['timezone']));

**Comment by rrjanbiah** [comment]
@Zimeon- Thanks for your report. We'll fix it soon.

**Comment by lmarikannan** [comment]
> 
> 
> Here's what you missedâ€¦
> MÃ–
> Mi Ã–ster updated item name as nnnnnn, -> SiirretÃ¤Ã¤n syyskuuulle.
> 
> should be:
> 
> MÖ
> Mi Öster updated item name as nnnnnn. -> Siirretään syyskuulile.
> 
> Just a guess, missing headers with charset?
> 
> Also date seems to be epoch, the subject shows as following:
> 2 new notifications since 01:00 AM (January 1, 1970)
> 

Fixed in dev branch

> The time seems to have it's root cause from the user not having a timezone set, mayby add a fallback timezone (server timezone)?
> Line 345 on instant_email_notification.php
> $emailFindReplace['##SINCE##'] = date("h:i A (F j, Y)", strtotime($user['timezone']));

already we've added `user_timezone` field in users table `https://github.com/RestyaPlatform/board/blob/master/sql/upgrade-0.2.1-0.3.sql#L1273` on previous release `https://github.com/RestyaPlatform/board/blob/master/sql/upgrade-0.2.1-0.3.sql`. So please execute the query `https://github.com/RestyaPlatform/board/blob/master/sql/upgrade-0.2.1-0.3.sql#L1273` manually.

**Comment by Zimeon-** [comment]
Did you add the headers for encoding?

**Comment by lmarikannan** [comment]
@Zimeon- Already We've added header https://github.com/RestyaPlatform/board/blob/master/server/php/libs/core.php#L679. Now we add meta tag `<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />` in email_templates table
