### ISSUE TITLE
adding users via webui not possible?

### ISSUE THREAD

**Issue by tchncs** [RestyaPlatform/board#743]
Hi there, i just installed restyaboard and everything is working well so far.
But i cannot find any option to manually create a new user / enable sign ups.

Is this a pro-feature or just not implemented yet? Is the only way trello / ldap / psql shell?

Regards

**Comment by Aendrew87** [comment]
@tchncs login with user 'admin' and password 'restya' after that you find a button 'Admin' on the bottom - there click on the top on 'Users' after that you find 'Add User' on the top

![add_user](https://cloud.githubusercontent.com/assets/13086377/17651793/df24fc7e-626d-11e6-8ede-747e51801a9d.png)

**Comment by tchncs** [comment]
Thanks for your answer, this buttons was not there.
I choosed wekan for now for several reasons, but miss some cool features.

However, i will give restya another try somewhen.
I used the latest release if it helps btw.

**Comment by rrjanbiah** [comment]
@tchncs Sorry for the delay. Thanks @Aendrew87 for helping.

Probably, you've enabled LDAP login? Adding user is currently not possible when you enable LDAP. If this is a common requirement, we'll need to address that too.

**Comment by tchncs** [comment]
Thank you very much for explanation, yes, i had LDAP enabled, since i started to playing around with openldap.
So this can be closed. :)

**Comment by Polycris** [comment]
Hi! I had LDAP enabled once time and later I can't unfix anymore. Why? How can I disable this option?

![screen 1 ldap disabled](https://cloud.githubusercontent.com/assets/23239422/20717603/273b2ef2-b63d-11e6-848d-27353e643279.jpg)
![screen 2 doesn t fixed](https://cloud.githubusercontent.com/assets/23239422/20717604/273c697a-b63d-11e6-97af-ad4517ae14c1.jpg)
