### ISSUE TITLE
randomly missing thumbnails in webui (pc)

### ISSUE THREAD

**Issue by tchncs** [RestyaPlatform/board#745]
Hi there, i tested with Vivaldi and Firefox.
In Vivaldi where the thumbnails broken since the beginning,
in Firefox i had them for some time but their lost again.

I never had this problem with Firefox on Android 'til now, there looks everything as expected.

Since i didn't saw anything helpful in the nginx log, i thought it might be a good idea to create an issue.
I am using the latest board release.

![2016-08-06-205043_1920x1200_scrot](https://cloud.githubusercontent.com/assets/10698140/17458632/52dd078a-5c18-11e6-9941-fd3fd16f34ac.png)

**Comment by rrjanbiah** [comment]
@tchncs Sorry for the delay...

Thumbnail creation login requires ImageMagick or GD. Probably, you may be missing them. Or, there may be some memory issue when it creates thumbnail. Try increasing the memory limit.

Also, `img` folder needs write permission for saving thumbnails. 

Please try enabling debug mode and see if you're getting any error message in the page or in HTTP header.

**Comment by lmarikannan** [comment]
@tchncs Were you able to find solution?

**Comment by tchncs** [comment]
Sorry for my delay.

> Thumbnail creation login requires ImageMagick or GD. Probably, you may be missing them. Or, there may be some memory issue when it creates thumbnail. Try increasing the memory limit.
>
>Also, img folder needs write permission for saving thumbnails. 

The dependencies where installed. I am unsure about the memory limit but i can say, that the images where there on some browsers for a short time, and any time using mobile browsers.

>@tchncs Were you able to find solution?

No. After a while i became angry and switched to wekan since i needed a reliable solution.
But i am looking forward to come back to restya somewhen.

I needed i can make another restya instance for reverse checking...

**Comment by rrjanbiah** [comment]
@tchncs Sorry about that. Closing this for now. If you still face this issue, please feel free to reopen.
