### ISSUE TITLE
Problem Install on Ubuntu 16.04

### ISSUE THREAD

**Issue by tititestor** [RestyaPlatform/board#749]
Hello,

Could you help me ?
This is my install log.

Sorry for my english
Best regards,
Titi

[restyaboard_install.zip](https://github.com/RestyaPlatform/board/files/415124/restyaboard_install.zip)

**Comment by tititestor** [comment]
Resolved,

I made manually installation on Ubuntu 14.04 using nginx

**Comment by rrjanbiah** [comment]
@tititestor Glad to know. And sorry for not able to help you properly.
