### ISSUE TITLE
Board owner cannot leave the board. Remove the "Leave from board" option  for owners or Hide it.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#75]
Board owner cannot leave the board. Remove the "Leave from board" option  for owners

Refer the attachment.
![leave_board_owner](https://cloud.githubusercontent.com/assets/14884895/10331112/251dbdfc-6cf0-11e5-94c3-61bf5091bf9c.png)

**Comment by rrjanbiah** [comment]
Fixed
