### ISSUE TITLE
Add an option to Save Login Data (cookie/session) or login by url with credentials

### ISSUE THREAD

**Issue by graebermedien** [RestyaPlatform/board#750]
Hi,

would it be possible to Add an option to Save Login Data (cookie/session) or login by url with credentials ?

I am using the board in an iframe and i need to re-login all the time ...can we implement some session-management or direct-login configuration possibility?!

Thanks!

**Comment by rrjanbiah** [comment]
This is possible. Probably, you're asking for #714 ?

**Comment by graebermedien** [comment]
Yes, this AND maybe it could be possible to add an manual configuration option for an url with auto-http-login so that if someone uses an url like:

https://Aladdin:OpenSesame@www.example.com/index.html 

(or similar) automatically gets logged in into a board X ?

**Comment by lmarikannan** [comment]
@graebermedien  That will be a good feature. Thanks for your suggestion.

**Comment by lmarikannan** [comment]
Stored login data in cookies.

**Comment by lmarikannan** [comment]
Refer #714.
