### ISSUE TITLE
Maximum length of a username

### ISSUE THREAD

**Issue by Aendrew87** [RestyaPlatform/board#751]
I tried to create a few users with long names and got the error 'Username. Minimum 3 characters'.
Nice to know the minimum but what is the maximum?

For example i tried something like that 'thisismydemouser'.

The maximum seams to be 15 characters but this information is missing.

**Comment by rrjanbiah** [comment]
Thanks for your report. We'll fix it soon.

**Comment by lmarikannan** [comment]
Fixed in dev branch
