### ISSUE TITLE
Creation of new user role does nothing

### ISSUE THREAD

**Issue by sampavone** [RestyaPlatform/board#753]
When adding a new user role, the column is created in the settings page but you are unable to give any user permissions to the new role. Additionally, when creating a new user, you are unable to assign a newly created role to that user.

**Comment by lmarikannan** [comment]
@sampavone Thanks for your report. We'll fix it soon.

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/pull/865/commits/46d317600bd0f9b3c7e198ae94c6cca8fef637f6
