### ISSUE TITLE
When un-archiving card with checklist, progress bar does not update

### ISSUE THREAD

**Issue by sampavone** [RestyaPlatform/board#754]
Create a card, add a checklist to the card with at least one item. Check the item and see the progressbar update (fill in green). Then archive the card and unarchive - status of checklist is correct but green bar in checklist does not update until checklist items are changed.

**Comment by lmarikannan** [comment]
@sampavone Thanks for your report. We'll fix it soon.

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/pull/854/commits/65a4b9bb1d6a0363c997d117fca4f407c2468b67
