### ISSUE TITLE
SQL creation script creates two "Cards Workflow" tabs

### ISSUE THREAD

**Issue by sampavone** [RestyaPlatform/board#755]
Running the fresh install sql script creates two "Cards Workflow" tabs:

offending line is line 5169 of restyaboard_with_empty_data.sql:
13	2016-06-28 07:47:21.765	2016-06-28 07:47:21.765	\N	Cards Workflow	\N	7

**Comment by rrjanbiah** [comment]
Possible duplicate of https://github.com/RestyaPlatform/board/issues/705#issuecomment-231329066

**Comment by sampavone** [comment]
Will close as duplicate, although [#705](https://github.com/RestyaPlatform/board/issues/705#issuecomment-231329066) is a symptom of the sql duplication?
