### ISSUE TITLE
SQL creation script creates two instances of option "Default Card Open"

### ISSUE THREAD

**Issue by sampavone** [RestyaPlatform/board#756]
line 5228 in SQL potentially duplicates line 5227: 

57	3	0	DEFAULT_CARD_VIEW	Maximized	\N	select	Maximized,Normal Dockmodal	Default Card Open	7

**Comment by rrjanbiah** [comment]
Possible duplicate of https://github.com/RestyaPlatform/board/issues/705#issuecomment-231329066

**Comment by sampavone** [comment]
Will close as duplicate, although [#705](https://github.com/RestyaPlatform/board/issues/705#issuecomment-231329066) is a symptom of the sql duplication?
