### ISSUE TITLE
Dublicate menu

### ISSUE THREAD

**Issue by iacsvrn** [RestyaPlatform/board#758]
/ Admin CP / Settings  --> double "Cards Workflow" menu. One of then are empty.

**Comment by sampavone** [comment]
Duplicate of [#755](https://github.com/RestyaPlatform/board/issues/755)

**Comment by rrjanbiah** [comment]
Possible duplicate of https://github.com/RestyaPlatform/board/issues/705#issuecomment-231329066

**Comment by rrjanbiah** [comment]
If this is not a duplicate of https://github.com/RestyaPlatform/board/issues/705#issuecomment-231329066 please feel free to reopen with more information.
