### ISSUE TITLE
If clicked on change permissions for board owner, no dialog window is opened or hide the "Change permissions"

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#76]
If clicked on change permissions for board owner, no dialog window is opened.

Refer the attachment.
![change_permissions](https://cloud.githubusercontent.com/assets/14884895/10331413/b7ff3b30-6cf2-11e5-9a9f-9174418f1599.png)

**Comment by rrjanbiah** [comment]
Fixed
