### ISSUE TITLE
Unable to Login after installation

### ISSUE THREAD

**Issue by PZalacain** [RestyaPlatform/board#761]
Hi RESTYA team.
I've installed manually Restyaboard on an Apache Server with CentOS6.

Actually the board looks like is working, I can access to the Login page, but is unable to Login: http://restya.wedev.es/

The strange thing is that when I use good credentials like "user/restya" I receive this message "wrong password or used deasctivated", then (after error message) if I click on any link, the main menu gets loaded but not clickable, my board is not working properly, I looked for lot of things.

Any similar issue? Some answer for me?
Thank you a million!
![restya01](https://cloud.githubusercontent.com/assets/7887560/17715976/0bd6415c-6407-11e6-906a-c4f1041930ae.png)
![restya02](https://cloud.githubusercontent.com/assets/7887560/17715977/0bd92af2-6407-11e6-9aed-afd11ef53fc7.png)

**Comment by lmarikannan** [comment]
@PZalacain Can you please enable debug mode in https://github.com/RestyaPlatform/board/blob/master/server/php/config.inc.php#L15 and post HTTP response header and response (In Firebug or Chrome's Developer tool)

**Comment by PZalacain** [comment]
Hello @lmarikannan 
I've put debug mode, and here is the data... (Apologize my English)

**Response headers:**
Connection:Keep-Alive
Date:Fri, 19 Aug 2016 19:06:34 GMT
ETag:"13e9fe-871-53a0a6cfa9a00"
Keep-Alive:timeout=5, max=100
Server:Apache/2.2.31 (Unix) mod_ssl/2.2.31 OpenSSL/1.0.1e-fips DAV/2 SVN/1.8.16 mod_bwlimited/1.4

**Response:**
<!DOCTYPE html><html class="no-js" lang="en"><head><meta charset="utf-8"><title>Restyaboard powered kanban board</title><meta name="description" content="Restyaboard powered kanban board. Download open source from http://restya.com/board/"><meta name="keywords" content="Restyaboard, http://restya.com/board/"><meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1"><meta name="theme-color" content="#f47564"><link rel="manifest" href="manifest.json"><link href="//fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css"><link rel="stylesheet" href="css/default.cache.b1ada593.css" media="screen"><link id="favicon" rel="shortcut icon" href="favicon.ico"><link rel="apple-touch-icon" href="apple-touch-icon.png"><link rel="apple-touch-icon" sizes="72x72" href="apple-touch-icon-72x72.png"><link rel="apple-touch-icon" sizes="114x114" href="apple-touch-icon-114x114.png"><link rel="icon" sizes="192x192" href="img/logo-192x192.png"></head><body style="cursor: auto"><div id="main" class="content"><div class="wrapper"><header id="header" class="clearfix"><span id="title"></span></header><main id="content" class="container-fluid"><div id="life"></div></main><div class="text-center"><a target="_blank" class="company hide" href="http://restya.com/board/?utm_source=Restyaboard&utm_medium=web&utm_campaign=login_footer" title="Open source. Trello like kanban board." rel="generator">Powered by Restyaboard</a></div></div><footer id="footer" class="navbar-fixed-bottom container-fluid footer"></footer></div><script>var api_url = '/api/v1/';
  var template_url = '/client/';</script><script>window.addEventListener('load', function(e){window.applicationCache.addEventListener('updateready', function(e){if (window.applicationCache.status == window.applicationCache.UPDATEREADY){window.applicationCache.swapCache();if (confirm('A new version of this site is available. Load it?')){window.location.reload();}}}, false);}, false);</script><script src="js/default.cache.5b71cf1d.js"></script></body></html>

Is it what you demand?
With debug mode Restyaboard writes any log?

Thank you for answering!

**Comment by PZalacain** [comment]
Even user data after login:
`{"id":"2","links":"[{\"slug\":\"unstarred_board\"},{\"slug\":\"unstarred_board\"},{\"slug\":\"add_user_profile_picture\"},{\"slug\":\"add_user_profile_picture\"},{\"slug\":\"view_board\"},{\"slug\":\"view_board\"},{\"slug\":\"view_webhooks\"},{\"slug\":\"view_webhooks\"},{\"slug\":\"add_board\"},{\"slug\":\"add_board\"},{\"slug\":\"add_organization\"},{\"slug\":\"add_organization\"},{\"slug\":\"add_webhook\"},{\"slug\":\"add_webhook\"},{\"slug\":\"view_board_search\"},{\"slug\":\"view_board_search\"},{\"slug\":\"view_board_visibility\"},{\"slug\":\"view_board_visibility\"},{\"slug\":\"edit_webhook\"},{\"slug\":\"edit_webhook\"},{\"slug\":\"view_workflow_templates\"},{\"slug\":\"view_workflow_templates\"},{\"slug\":\"delete_connected_applications\"},{\"slug\":\"delete_connected_applications\"},{\"slug\":\"view_search\"},{\"slug\":\"view_search\"},{\"slug\":\"view_board_listing\"},{\"slug\":\"view_board_listing\"},{\"slug\":\"view_organization\"},{\"slug\":\"view_organization\"},{\"slug\":\"view_organization_listing\"},{\"slug\":\"view_organization_listing\"},{\"slug\":\"view_board_star\"},{\"slug\":\"view_board_star\"},{\"slug\":\"view_user\"},{\"slug\":\"view_user\"},{\"slug\":\"activities_listing\"},{\"slug\":\"activities_listing\"},{\"slug\":\"view_my_boards\"},{\"slug\":\"view_my_boards\"},{\"slug\":\"view_closed_boards\"},{\"slug\":\"view_closed_boards\"},{\"slug\":\"view_connected_applications\"},{\"slug\":\"view_connected_applications\"},{\"slug\":\"view_organization_visibility\"},{\"slug\":\"view_organization_visibility\"},{\"slug\":\"view_user_activities\"},{\"slug\":\"view_user_activities\"},{\"slug\":\"view_user_board\"},{\"slug\":\"view_user_board\"},{\"slug\":\"view_user_cards\"},{\"slug\":\"view_user_cards\"},{\"slug\":\"view_user_search\"},{\"slug\":\"view_user_search\"},{\"slug\":\"view_stared_boards\"},{\"slug\":\"view_stared_boards\"},{\"slug\":\"board_star\"},{\"slug\":\"board_star\"},{\"slug\":\"user_changepassword\"},{\"slug\":\"user_changepassword\"},{\"slug\":\"starred_board\"},{\"slug\":\"starred_board\"},{\"slug\":\"load_settings\"},{\"slug\":\"load_settings\"},{\"slug\":\"delete_webhook\"},{\"slug\":\"delete_webhook\"},{\"slug\":\"edit_user_details\"},{\"slug\":\"edit_user_details\"},{\"slug\":\"user_detail\"},{\"slug\":\"user_detail\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"unstarred_board\"},{\"slug\":\"unstarred_board\"},{\"slug\":\"add_user_profile_picture\"},{\"slug\":\"add_user_profile_picture\"},{\"slug\":\"view_board\"},{\"slug\":\"view_board\"},{\"slug\":\"view_webhooks\"},{\"slug\":\"view_webhooks\"},{\"slug\":\"add_board\"},{\"slug\":\"add_board\"},{\"slug\":\"add_organization\"},{\"slug\":\"add_organization\"},{\"slug\":\"add_webhook\"},{\"slug\":\"add_webhook\"},{\"slug\":\"view_board_search\"},{\"slug\":\"view_board_search\"},{\"slug\":\"view_board_visibility\"},{\"slug\":\"view_board_visibility\"},{\"slug\":\"edit_webhook\"},{\"slug\":\"edit_webhook\"},{\"slug\":\"view_workflow_templates\"},{\"slug\":\"view_workflow_templates\"},{\"slug\":\"delete_connected_applications\"},{\"slug\":\"delete_connected_applications\"},{\"slug\":\"view_search\"},{\"slug\":\"view_search\"},{\"slug\":\"view_board_listing\"},{\"slug\":\"view_board_listing\"},{\"slug\":\"view_organization\"},{\"slug\":\"view_organization\"},{\"slug\":\"view_organization_listing\"},{\"slug\":\"view_organization_listing\"},{\"slug\":\"view_board_star\"},{\"slug\":\"view_board_star\"},{\"slug\":\"view_user\"},{\"slug\":\"view_user\"},{\"slug\":\"activities_listing\"},{\"slug\":\"activities_listing\"},{\"slug\":\"view_my_boards\"},{\"slug\":\"view_my_boards\"},{\"slug\":\"view_closed_boards\"},{\"slug\":\"view_closed_boards\"},{\"slug\":\"view_connected_applications\"},{\"slug\":\"view_connected_applications\"},{\"slug\":\"view_organization_visibility\"},{\"slug\":\"view_organization_visibility\"},{\"slug\":\"view_user_activities\"},{\"slug\":\"view_user_activities\"},{\"slug\":\"view_user_board\"},{\"slug\":\"view_user_board\"},{\"slug\":\"view_user_cards\"},{\"slug\":\"view_user_cards\"},{\"slug\":\"view_user_search\"},{\"slug\":\"view_user_search\"},{\"slug\":\"view_stared_boards\"},{\"slug\":\"view_stared_boards\"},{\"slug\":\"board_star\"},{\"slug\":\"board_star\"},{\"slug\":\"user_changepassword\"},{\"slug\":\"user_changepassword\"},{\"slug\":\"starred_board\"},{\"slug\":\"starred_board\"},{\"slug\":\"load_settings\"},{\"slug\":\"load_settings\"},{\"slug\":\"delete_webhook\"},{\"slug\":\"delete_webhook\"},{\"slug\":\"edit_user_details\"},{\"slug\":\"edit_user_details\"},{\"slug\":\"user_detail\"},{\"slug\":\"user_detail\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"}]","error":"invalid_scope","error_description":"An unsupported scope was requested","user":{"id":"2","role_id":"2","username":"user","email":"board+user@restya.com","full_name":"User","initials":"U","about_me":null,"profile_picture_path":null,"notification_frequency":null,"is_allow_desktop_notification":"0","is_active":"1","is_email_confirmed":"1","created_organization_count":"0","created_board_count":"0","joined_organization_count":"0","list_count":"0","joined_card_count":"0","created_card_count":"0","joined_board_count":"0","checklist_count":"0","checklist_item_completed_count":"0","checklist_item_count":"0","activity_count":"0","card_voter_count":"0","is_productivity_beats":"0","organizations":null,"last_activity_id":"0","boards_stars":null,"boards_users":null,"last_login_date":"2016-08-19 21:38:27.864399","last_login_ip":"81.184.232.192","login_city_name":null,"login_state_name":null,"login_country_name":null,"login_country_iso2":null,"registered_ip":null,"register_city_name":null,"register_state_name":null,"register_country_name":null,"register_country_iso2":null,"login_type":"Normal","created":"2014-07-05T11:46:40","user_login_count":"10","is_send_newsletter":"0","last_email_notified_activity_id":"0","owner_board_count":"0","member_board_count":"0","owner_organization_count":"0","member_organization_count":"0","language":null,"is_ldap":"0","timezone":null,"notify_count":"0"}}`

Thanks again!

**Comment by lmarikannan** [comment]
@PZalacain `"error":"invalid_scope","error_description":"An unsupported scope was requested","user"`. Can you please delete the current database, and create a new one, then execute the `https://github.com/RestyaPlatform/board/blob/master/sql/restyaboard_with_empty_data.sql` sql file manually?

**Comment by PZalacain** [comment]
Wow! I am blind... Of course, I will do right now!
Thanks, let me check and I will post a feedback.

**Comment by PZalacain** [comment]
Lovely, it's working right now, I could see Admin Panel once, but I'm getting another error right now.
This time from PHP. 

Something like:
`[22-Aug-2016 16:49:13 UTC] PHP Warning:  Division by zero in www.restya.wedev.es/server/php/R/r.php on line 1211`

boards.json:
`<br />
<b>Warning</b>:  Division by zero in <b>/home/wedev/public_html/www.restya.wedev.es/server/php/R/r.php</b> on line <b>1211</b><br />
{"_metadata":{"noOfPages":0,"total_records":"0","limit":"0","offset":0,"showing":"0","maxSize":5},"filter_count":{"closed":"0","open":"0","private":"0","public":"0","organization":"0"},"board_user_roles":[{"id":"1","name":"Owner"},{"id":"2","name":"Editor"},{"id":"3","name":"Viewer"}]}`

Do I have to execute **v0.3.sql** too?
Thank you.

**Comment by lmarikannan** [comment]
@PZalacain, Do not execute v0.3 sql. And please disable debug mode in https://github.com/RestyaPlatform/board/blob/master/server/php/config.inc.php#L15

**Comment by PZalacain** [comment]
Perfect! Now is working good!
So, the solution is; **Never exesute sql script from phpPgAdmin**

One question more: Where are the language files? I'm trying to fix some Spanish issues.
Thank you.

**Comment by PZalacain** [comment]
Oh sorry!
Second question, can I change the value of email templates properties?

##SITE_URL## is pointing to my domain, it should point to my **sub**domain.
Restyaboard logo is not loading in the emails.

Thanks again.

**Comment by lmarikannan** [comment]
@PZalacain languages files are in `https://github.com/RestyaPlatform/board/tree/master/client/locales`. Closing this for now. If you get any other issues related this, please feel free to reopen.
