### ISSUE TITLE
cronjob fail on postgresql-9.5

### ISSUE THREAD

**Issue by MrManor** [RestyaPlatform/board#768]
Running card_due_notification.sh output is:
`root@board:/var/www/restyaboard/server/php/shell# /var/www/restyaboard/server/php/shell/card_due_notification.sh
2016-08-19 15:07:00 #################################################
successfully acquired lock: /var/www/restyaboard/server/php/shell/card_due_notification.lock
PHP Warning:  pg_query_params(): Query failed: ERROR:  operator does not exist: text >= timestamp with time zone
LINE 1: SELECT * FROM cards_listing WHERE due_date BETWEEN ((now() +...
                                                   ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts. in /var/www/restyaboard/server/php/shell/card_due_notification.php on line 24
PHP Warning:  pg_fetch_assoc() expects parameter 1 to be resource, boolean given in /var/www/restyaboard/server/php/shell/card_due_notification.php on line 25`
Any ideas?

**Comment by lmarikannan** [comment]
@MrManor Thanks for your report. We'll fix it soon.

**Comment by lmarikannan** [comment]
Fixed in dev branch

**Comment by MrManor** [comment]
Thank you. That was quick. 
Can I possible test it by backporting to my current install? (I can replace the changed php file, but how about the file containing changes til to the database)

**Comment by lmarikannan** [comment]
@MrManor Yes, you can. please execute the changes from this line https://github.com/RestyaPlatform/board/commit/fc58669867877b4ec43793eb14af0ffbbf8914e8#diff-ee2d3f3d96a2f5da2c97cdebbf9944d5R176 to https://github.com/RestyaPlatform/board/commit/fc58669867877b4ec43793eb14af0ffbbf8914e8#diff-ee2d3f3d96a2f5da2c97cdebbf9944d5R271 on your database.
