### ISSUE TITLE
psql: FATAL:  Peer authentication failed for user "postgres"

### ISSUE THREAD

**Issue by KojoePi** [RestyaPlatform/board#774]
Hello!
I have an issue during installation on a Debian 8 Server.
Here is the Install log:

[restyaboard_install.txt](https://github.com/RestyaPlatform/board/files/431411/restyaboard_install.txt)

Thanks for your help in advance

**Comment by Aendrew87** [comment]
@KojoePi the command `psql -U postgres -c "\q"` returned '2'.

From the psql documentation (https://www.postgresql.org/docs/9.3/static/app-psql.html):
> psql returns ... 2 if the connection to the server went bad...

Is postgresql running?
Could you execute the command `psql -U postgres -c "\q"` by yourselfe?

**Comment by lmarikannan** [comment]
@KojoePi It is related to https://github.com/RestyaPlatform/board/issues/262. 

Can you please check the database user has privileges for the restyaboard database?

To grant privileges to database,
GRANT ALL PRIVILEGES ON DATABASE restyaboard TO restya;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO restya;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO restya;

**Comment by rrjanbiah** [comment]
@KojoePi Closing this for now If you're still facing issue, please feel free to reopen.
