### ISSUE TITLE
PostgresQL authentication issue for the user postgres while script installation

### ISSUE THREAD

**Issue by Oxis99** [RestyaPlatform/board#775]
Hi there,
I've tried to run the script install', all worked but at the line someting went wrong:
++ psql -U postgres -c '\q'
psql: FATAL:  authentification peer échouée pour l'utilisateur « postgres »
++ '[' 2 '!=' 0 ']'
++ echo 'PostgreSQL Changing the permission failed with error code 34'
PostgreSQL Changing the permission failed with error code 34

For info, I've manually created the database, the user and assigned passwords with sql commandline before running the script...:sudo -u postgres psql
postgres=# CREATE USER "" WITH PASSWORD '';
postgres=# CREATE DATABASE database WITH OWNER "";
postgres=# \quit
After these commandlines, I've changed the variables in the restyaboard.sh
So, what could have been done wrong ?
Thanks for helping, you've done a great job with restyaboard (I've tested it on the demo).
Cheers

**Comment by rrjanbiah** [comment]
Thanks for your kind words. Can you please share your install log? (That will help us to understand what went wrong)

Also, it looks like you've issue with the DB user. Can you please check if you've properly created users and rights?

**Comment by Oxis99** [comment]
Hi there,
I wrote these commandlines in the debian shell:
$sudo -u postgres psql
postgres=# CREATE USER "user-restya" WITH PASSWORD 'mypass';
postgres=# CREATE DATABASE restya WITH OWNER "user";
postgres=# \quit

I also, tested to connect the postgres user with this command from your script installation:
$psql -U postgres -c "\q"
psql: FATAL:  authentification peer échouée pour l'utilisateur « postgres »

Have I done something wrong?

**Comment by Oxis99** [comment]
Maybe I have found something to resolve the issue:
$psql -h 127.0.0.1 -U user-restya mypass -W

**Comment by Oxis99** [comment]
I broke my postgresql install...I'll try with a new one.

**Comment by rrjanbiah** [comment]
@Oxis99 Please let us know how it goes

**Comment by Oxis99** [comment]
Hi there, I've run the install script on a debian VM (virtualbox on my Mac), and all gone OK !
On my testing server, even after postgresql reinstallation, the script install failed...
Do you want me to send you the log file ?

**Comment by rrjanbiah** [comment]
@Oxis99 Yes, please if possible. That will help us to debug easily.

**Comment by lmarikannan** [comment]
@Oxis99 We're waiting for your reply

**Comment by lmarikannan** [comment]
PostgreSQL authentication issue fixed in this commit https://github.com/RestyaPlatform/board/commit/14c8d56818098b3ed56709e419d8e04ab29a3e44, https://github.com/RestyaPlatform/board/commit/d0356b2231c061b6c8adc804f691de0e63937f2b
