### ISSUE TITLE
Gantt charts enhancements

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#776]
From David Bourgeois via from at https://groups.google.com/d/msg/restya/xdbpj9crdFc/P8BInKgAFQAJ

Not being able to define a start date makes Gantt charts quite unusable. Without going too complicated, simply adding a 'Start Date' would at least show something more relevant as a project schedule overview.

Now my suggestion would be to add a field with the following options:
- OFF: doesn't show the task on the Gantt chart
- Start Date: Shows the task from Start to Due on the Gantt chart
- Milestone: shows as a diamond and use the Due date only

On 'Kanboard' and some other applications, dragging the task moves it on the gantt chart, adjusting the Start and Due dates automatically, while dragging the edges adjust the Start or Due dates only.

I think these only would make the Gantt chart much more useful.

**Comment by Zimeon-** [comment]
Partly similar to previous issue: https://github.com/RestyaPlatform/board/issues/701

**Comment by julienmoinard** [comment]
I agree with

**Comment by sridhar391** [comment]
We have updated the Gantt view app in the Restyaboard latest version 0.6.6
