### ISSUE TITLE
Can there show up the real timestamp?

### ISSUE THREAD

**Issue by keky** [RestyaPlatform/board#777]
![image](https://cloud.githubusercontent.com/assets/548338/17996166/a581314c-6b99-11e6-8614-ca455d9436c8.png)

**Comment by rrjanbiah** [comment]
@keky Yes this is possible. But, this is a common "enhancement" requirement these days :-)

**Comment by lmarikannan** [comment]
@keky  Closing this for now. If you get any other issues related this, please feel free to reopen.

**Comment by keky** [comment]
Is there any solution now?

**Comment by rrjanbiah** [comment]
@lmarikannan Can you please mention how to disable it for @keky ?

**Comment by lmarikannan** [comment]
@keky You can show up the real timestamp by remove `timeago` class from this line https://github.com/RestyaPlatform/board/blob/master/client/js/templates/activity.jst.ejs#L89.

**Comment by keky** [comment]
@lmarikannan very thx for your help!

**Comment by lmarikannan** [comment]
@keky 

You can show up the real timestamp by remove timeago class from these 2 lines `Line: 50, Column:20477`  and `Line: 51, Column:2021` on `/board-v0.3/client/js/default.cache.5b71cf1d.js` file.
