### ISSUE TITLE
again and again asking for New version update

### ISSUE THREAD

**Issue by lmarikannan** [RestyaPlatform/board#778]

**Comment by lmarikannan** [comment]
Fixed.

**Comment by rrjanbiah** [comment]
Reopened. Code changed and got reverted. Not sure how will it fix the issue...

**Comment by baskar383** [comment]
In the second commit only the url is reverted as it was committed wrongly in the first commit. The remaining changes in the first commit is the code for fixing the issue and it is not reverted in the second commit.
