### ISSUE TITLE
Attachments are not working

### ISSUE THREAD

**Issue by amjadpkteam** [RestyaPlatform/board#78]
When I drag and drop files to 'Drop files to upload' button, it displays a progress bar under it forever, and do nothing. Not working at demo too.. 
http://board.demo.restya.com/#/organization/63

**Comment by rrjanbiah** [comment]
@amjadpkteam I have got it uploaded; please refer http://board.demo.restya.com/#/organization/63

Can you please share your browser and OS?

**Comment by amjadpkteam** [comment]
my browser 'firefox'
OS 'ubuntu 14.04'

**Comment by rrjanbiah** [comment]
@amjadpkteam Thanks for sharing the details.

@srileka Please test and see if you can duplicate this behavior in above environment.

**Comment by amjadpkteam** [comment]
cool, how you fixed that

**Comment by rrjanbiah** [comment]
@amjadpkteam 

> cool, how you fixed that

Not done anything. It worked as it is. I'm on Chrome/XP though.

**Comment by srileka** [comment]
Its working fine for us.(Firefox, chrome) in Win 8.1, 7, Xp and Mac.

Need to check in firefox, OS 'ubuntu 14.04'

**Comment by rrjanbiah** [comment]
> Need to check in firefox, OS 'ubuntu 14.04'

@srileka Any update on above?

**Comment by srileka** [comment]
Checked in firefox, OS 'ubuntu 14.04'. Now attachments are working fine.

**Comment by rrjanbiah** [comment]
Closing this as @srileka confirmed that it is working in Ubuntu too.

@amjadpkteam If you're still facing this issue, please reopen.
