### ISSUE TITLE
xmpp chat is broken for ldap users

### ISSUE THREAD

**Issue by tauu** [RestyaPlatform/board#784]
I noticed that if a ldap user logs into restyaboard, the chat is not able to connect and the folllowing error message is logged to the webservers error.log : 

> FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught XmppPrebindConnectionException: Invalid challenge response received in /srv/restyaboard/server/php/libs/vendors/xmpp-prebind-php/XmppPrebind.php:421

After investigating the issue and searching through the code, I think that restyaboard does not even try to create a xmpp account during the first login of an ldap user.  Therefore initializing the chat later on will never work. Please see [r.php, lines 1844 - 1861 ](https://github.com/RestyaPlatform/board/blob/master/server/php/R/r.php#L1844)

Could part of the code from the user registration  [r.php, lines 1798 - 1816 ](https://github.com/RestyaPlatform/board/blob/master/server/php/R/r.php#L1798) be used to create the xmpp account?

**Comment by lmarikannan** [comment]
@tauu Thanks for your report. We'll fix it soon.

**Comment by lmarikannan** [comment]
Fixed in dev branch
