### ISSUE TITLE
GET - NetworkError: 404 Not Found - /api/v1/oauth.json

### ISSUE THREAD

**Issue by Pobux** [RestyaPlatform/board#791]
It seems I have similar issue related to the blank screen.

I'm using Ubuntu 16.04 Server and apache2.

Here's my apache conf : 
```
        DocumentRoot /var/www/restyaboard

        <Directory /var/www/restyaboard>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order Allow,Deny
                Allow from all
        </Directory>
```
Which bring me to client / media / server / sql / tmp root folder.
api_explorer is working fine.

Clicking on "client" triggers the error : 
`"NetworkError: 404 Not Found - http://apps.clibre.uqam.ca/api/v1/oauth.json?_=1473174574861"`

I do not know what to do, I read all the other issues related to oauth and blank screen, I have no errors in apache2 logs.

PHP:
`PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )`
I also installed php7.0-fpm

You can see the problem at apps.clibre.uqam.ca

I used this installation script : 
https://github.com/BlackDuck888/board/blob/contrib/installscript/install/restyaboard_apache.sh

**Comment by Pobux** [comment]
I figured out that the restyaboard_apache.sh seems to not pull the .htaccess from the repo. Which was a partial cause of the problem.

I then needed to fix apache2 and enable mod_rewrite.

My new apache configuration looks like this : 
```
        DocumentRoot /var/www/restyaboard

        <Directory /var/www/restyaboard>
                Options Indexes FollowSymLinks
                AllowOverride All
                Require all granted
                #Order Allow,Deny
                #Allow from all
        </Directory>
```

I needed to edit my .htaccess since it was throwing errors related to php_value
```
DirectoryIndex index.html index.php
Options -Indexes

<IfModule mod_rewrite.c>
        RewriteEngine On
        # If installed in local or under a path say /restyaboard        /: (otherwise, doesn't need RewriteBase)
        RewriteBase /
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^client/img/([a-zA-Z_]*)/([a-zA-Z_]*)/([a-zA-Z0-9_\.]*)$ server/php/image.php?size=$1&model=$2&filename=$3 [L]
        RewriteRule ^ical/([0-9]*)/([a-zA-Z0-9]*).ics$ server/php/ical.php?id=$1&hash=$2 [L]
        RewriteRule ^download/([0-9]*)/([a-zA-Z0-9_\.]*)$ server/php/download.php?id=$1&hash=$2 [QSA,L]
        RewriteRule ^oauth_callback/([a-zA-Z0-9_\.]*)/([a-zA-Z0-9_\.]*)$ server/php/oauth_callback.php?plugin=$1&code=$2 [L]
        RewriteRule ^oauth/authorize$ server/php/authorize.php [QSA,L]
        RewriteRule ^api/(.*)$ server/php/R/r.php?_url=$1 [QSA,L]
        RewriteRule ^$ client/ [QSA,L]
        RewriteRule ^(css|js|img|font|apps|locales)/(.*)$ client/$1/$2 [QSA,L]
        RewriteRule ^favicon.ico$ client/favicon.ico [L]
        RewriteRule ^manifest.json$ client/manifest.json [L]
        RewriteRule ^apple-touch-icon(.*)$ client/apple-touch-icon$1 [L]
</IfModule>

#php_value upload_max_filesize 9G
#php_value post_max_size 9G
#php_value max_execution_time 200
#php_value max_input_time 200
#php_value memory_limit 256M
```
As for now I still have a problem. 
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

I'm looking into this.

**Comment by BlackDuck888** [comment]
@Pobux for me this config is working [https://github.com/BlackDuck888/board/blob/contrib/installscript/install/restyaboard.conf](url)

i think it must be a vhost config! This meas you need the servername var in my config!

i did install just today a new 16.04 for a test, and it worked, did you change anything? you have to access the page over fqdn / vhost name.

**Comment by Pobux** [comment]
Hey thanks BlackDuck for the reply. It might have been the apache configuration. I did switch to the docker option which was a bit simplier for me. So as for now I can't follow up on this issue since I can't replicate it.

Thanks for the apache fork by the way.
