### ISSUE TITLE
 Limits for LDAP import

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#792]
By Klaus Vink Slott through forum https://groups.google.com/d/msg/restya/j24ykpSWJlg/CCLUTtXmAgAJ 

We are currently running a small test installation on our campus. If it turns out well we might expand usage to  larger parts of the University.

We have successfully connected to our LDAP and are able to login with username/password from LDAP. Profile -> settings -> Name and other data is not imported though.

I see there is a "Import users" button, and that really scares me: In our LDAP we currently have more that 125000 users (75000 active accounts) , and more that 3000 groups. I am no programmer but by looking at the code I guess that if I hit that button, Restyaboard will attempt to import and send mail to all users -  and (if selected) create more that 3000 organizations. Even before my little test setup runs out of disk space, - sending mail invitations to lot of staff and students would be very unpopular. 

So I would really like some way of limiting who is imported and which groups is imported. 

My suggestions would be 
- to import/update the users profile data every time a user logs in.  
- only import users which is member of a group specified in the LDAP settings interface.
- only import groups based on which groups the account specified to search the LDAP is a member of.

**Comment by lmarikannan** [comment]
Related to #512, #658

**Comment by lmarikannan** [comment]
@rrjanbiah Now we're filter users using with Advanced Filter option. We can import or filter particular Groups or particular user wise with this option.
