### ISSUE TITLE
User can't confirm the Registration

### ISSUE THREAD

**Issue by Merlin90** [RestyaPlatform/board#793]
Hello,

My users can not use the automatic link to activate their account. The screen just stays white. In the Admin Penal user are always displayed as "unconfirmed" and they can't add other users to their boards.

greetings
Merlin

**Comment by rrjanbiah** [comment]
@Merlin90 

Can you please check if you're referring to #487 ?

**Comment by Merlin90** [comment]
@rrjanbiah i diddn't got an error, only 2 warnings:
`mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create default.cache.a331c8c3.js:31:19039`

`getPreventDefault() should no longer be used. Use defaultPrevented instead.`

**Comment by lmarikannan** [comment]
@Merlin90 Thanks for your report. We'll fix it soon.

**Comment by lmarikannan** [comment]
@Merlin90 We tried in our local, But we can not able to reproduce this. Can you please share your browser Network and console tab screen-shots for checking HTTP request calls and their error logs (In Firebug or Chrome's Developer tool)

**Comment by lmarikannan** [comment]
@Merlin90 Please feel free to reopen, if you still face any issues.
