### ISSUE TITLE
Admin change password

### ISSUE THREAD

**Issue by Merlin90** [RestyaPlatform/board#794]
Hello,

i want, as an admin, change the passwords of my user. Is this possible?

Greetings

**Comment by rrjanbiah** [comment]
@Merlin90 Sorry, currently not possible

**Comment by Merlin90** [comment]
@rrjanbiah why? Isn't it enough, if the admin had permission to edit the profiles of all users?

**Comment by rrjanbiah** [comment]
@Merlin90 This feature can be added. But, for majority of the users, this may not be a needed features. Anyway, will consider that too.

**Comment by Adysone** [comment]
Hello,
I think this feature is required for security reason. Any user should be able to change his password!

**Comment by kirtangajjar** [comment]
Agreed. Even I was thinking about the same thing

**Comment by lmarikannan** [comment]
Implemented in this commit https://github.com/RestyaPlatform/board/commit/cacde290ddf11862a3dcb7f61e7a81f18a8bdf4a
