### ISSUE TITLE
Ubuntu 16.04 64bit

### ISSUE THREAD

**Issue by Budo1** [RestyaPlatform/board#795]
Hi,
I have fresh Ubuntu 16.04 64bit LTS installed on VMWare Player (Virtual Machine).
Then I got the script:
wget https://github.com/RestyaPlatform/board/raw/master/restyaboard.sh --no-check-certificate
then
chmod +x restyaboard.sh
then
sudo ./restyaboard.sh

log below:
./restyaboard.sh: 10: ./restyaboard.sh: [[: not found
+ whoami
root
+ cat /etc/issue
+ echo Ubuntu 16.04 LTS \n \l
Ubuntu 16.04 LTS 
 \l
+ sed s/^.*Raspbian.*$/Raspbian/g
+ sed s/^.*Debian.*$/Debian/g
+ sed s/^.*Debian.*$/Debian/g
+ sed s/^.*Ubuntu.*$/Ubuntu/g
+ grep Ubuntu\|Debian\|Raspbian
+ cat /proc/version
+ OS_REQUIREMENT=Ubuntu
+ [ Ubuntu = Ubuntu ]
+ apt-get install -y curl unzip
Reading package lists...
Building dependency tree...
Reading state information...
unzip is already the newest version (6.0-20ubuntu1).
unzip set to manually installed.
The following packages will be upgraded:
  curl libcurl3-gnutls
2 upgraded, 0 newly installed, 0 to remove and 361 not upgraded.
Need to get 322 kB of archives.
After this operation, 2,048 B of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 curl amd64 7.47.0-1ubuntu2.1 [138 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libcurl3-gnutls amd64 7.47.0-1ubuntu2.1 [183 kB]
Fetched 322 kB in 2s (147 kB/s)
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 172343 files and directories currently installed.)
Preparing to unpack .../curl_7.47.0-1ubuntu2.1_amd64.deb ...
Unpacking curl (7.47.0-1ubuntu2.1) over (7.47.0-1ubuntu2) ...
Preparing to unpack .../libcurl3-gnutls_7.47.0-1ubuntu2.1_amd64.deb ...
Unpacking libcurl3-gnutls:amd64 (7.47.0-1ubuntu2.1) over (7.47.0-1ubuntu2) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Setting up libcurl3-gnutls:amd64 (7.47.0-1ubuntu2.1) ...
Setting up curl (7.47.0-1ubuntu2.1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
+ curl --silent https://api.github.com/repos/RestyaPlatform/board/releases
+ sed -e s/[^v0-9.]//g
+ awk {print $2}
+ grep tag_name -m 1
+ RESTYABOARD_VERSION=v0.3
+ POSTGRES_DBHOST=localhost
+ POSTGRES_DBNAME=restyaboard
+ POSTGRES_DBUSER=restya
+ POSTGRES_DBPASS=hjVl2!rGd
+ POSTGRES_DBPORT=5432
+ EJABBERD_DBHOST=localhost
+ EJABBERD_DBNAME=ejabberd
+ EJABBERD_DBUSER=ejabb
+ EJABBERD_DBPASS=ftfnVgYl2
+ EJABBERD_DBPORT=5432
+ DOWNLOAD_DIR=/opt/restyaboard
+ [ -d /opt/restyaboard ]
+ set +x
Is Restyaboard already installed y/n?
+ [ Ubuntu = Ubuntu ]
+ set +x
Setup script will install version v0.3 and create database restyaboard with user restya and password hjVl2!rGd. To continue enter "y" or to quit the process and edit the version and database details enter "n" (y/n)?
+ echo deb http://mirrors.linode.com/debian/ wheezy main contrib non-free
+ echo deb-src http://mirrors.linode.com/debian/ wheezy main contrib non-free
+ echo deb http://mirrors.linode.com/debian-security/ wheezy/updates main contrib non-free
+ echo deb-src http://mirrors.linode.com/debian-security/ wheezy/updates main contrib non-free
+ echo deb http://mirrors.linode.com/debian/ wheezy-updates main
+ echo deb-src http://mirrors.linode.com/debian/ wheezy-updates main
+ sed -i -e s/deb cdrom/#deb cdrom/g /etc/apt/sources.list
+ apt-key update
gpg: key 437D05B5: "Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>" not changed
gpg: key FBB75451: "Ubuntu CD Image Automatic Signing Key <cdimage@ubuntu.com>" not changed
gpg: key C0B21F32: "Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>" not changed
gpg: key EFE21092: "Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>" not changed
gpg: Total number processed: 4
gpg:              unchanged: 4
+ apt-get update
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Ign:3 http://mirrors.linode.com/debian wheezy InRelease
Get:4 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [95.7 kB]
Get:5 http://mirrors.linode.com/debian-security wheezy/updates InRelease [40.6 kB]
Ign:5 http://mirrors.linode.com/debian-security wheezy/updates InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:7 http://mirrors.linode.com/debian wheezy-updates InRelease [153 kB]
Ign:7 http://mirrors.linode.com/debian wheezy-updates InRelease
Get:8 http://mirrors.linode.com/debian wheezy Release [191 kB]
Get:9 http://mirrors.linode.com/debian-security wheezy/updates/main Sources [281 kB]
Get:10 http://mirrors.linode.com/debian-security wheezy/updates/contrib Sources [14 B]
Get:11 http://mirrors.linode.com/debian-security wheezy/updates/non-free Sources [14 B]
Get:12 http://mirrors.linode.com/debian-security wheezy/updates/main amd64 Packages [430 kB]
Get:13 http://mirrors.linode.com/debian-security wheezy/updates/main i386 Packages [433 kB]
Get:14 http://mirrors.linode.com/debian-security wheezy/updates/main Translation-en [236 kB]
Get:15 http://mirrors.linode.com/debian-security wheezy/updates/contrib amd64 Packages [14 B]
Get:16 http://mirrors.linode.com/debian-security wheezy/updates/contrib i386 Packages [14 B]
Get:17 http://mirrors.linode.com/debian-security wheezy/updates/contrib Translation-en [14 B]
Get:18 http://mirrors.linode.com/debian-security wheezy/updates/non-free amd64 Packages [14 B]
Get:19 http://mirrors.linode.com/debian-security wheezy/updates/non-free i386 Packages [14 B]
Get:20 http://mirrors.linode.com/debian-security wheezy/updates/non-free Translation-en [14 B]
Get:21 http://mirrors.linode.com/debian wheezy-updates/main Sources [5,505 B]
Get:22 http://mirrors.linode.com/debian wheezy-updates/main amd64 Packages [7,047 B]
Get:23 http://mirrors.linode.com/debian wheezy-updates/main i386 Packages [7,051 B]
Get:24 http://mirrors.linode.com/debian wheezy-updates/main Translation-en [4,879 B]
Get:25 http://mirrors.linode.com/debian wheezy Release.gpg [2,373 B]
Ign:25 http://mirrors.linode.com/debian wheezy Release.gpg
Get:26 http://mirrors.linode.com/debian wheezy/main Sources [5,993 kB]
Get:27 http://mirrors.linode.com/debian wheezy/contrib Sources [47.7 kB]
Get:28 http://mirrors.linode.com/debian wheezy/non-free Sources [93.4 kB]
Get:29 http://mirrors.linode.com/debian wheezy/main amd64 Packages [5,839 kB]
Get:30 http://mirrors.linode.com/debian wheezy/main i386 Packages [5,857 kB]
Get:31 http://mirrors.linode.com/debian wheezy/main Translation-en [3,846 kB]
Get:32 http://mirrors.linode.com/debian wheezy/contrib amd64 Packages [42.0 kB]
Get:33 http://mirrors.linode.com/debian wheezy/contrib i386 Packages [42.3 kB]
Get:34 http://mirrors.linode.com/debian wheezy/contrib Translation-en [34.8 kB]
Get:35 http://mirrors.linode.com/debian wheezy/non-free amd64 Packages [80.8 kB]
Get:36 http://mirrors.linode.com/debian wheezy/non-free i386 Packages [77.6 kB]
Get:37 http://mirrors.linode.com/debian wheezy/non-free Translation-en [66.1 kB]
Fetched 23.9 MB in 1min 7s (352 kB/s)
Reading package lists...
W: GPG error: http://mirrors.linode.com/debian-security wheezy/updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9D6D8F6BC857C906  NO_PUBKEY 8B48AD6246925553
W: The repository 'http://mirrors.linode.com/debian-security wheezy/updates InRelease' is not signed.
W: There is no public key available for the following key IDs:
9D6D8F6BC857C906  NO_PUBKEY 8B48AD6246925553  
W: GPG error: http://mirrors.linode.com/debian wheezy-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553  NO_PUBKEY 7638D0442B90D010
W: The repository 'http://mirrors.linode.com/debian wheezy-updates InRelease' is not signed.
W: There is no public key available for the following key IDs:
8B48AD6246925553  NO_PUBKEY 7638D0442B90D010  
W: GPG error: http://mirrors.linode.com/debian wheezy Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553  NO_PUBKEY 7638D0442B90D010  NO_PUBKEY 6FB2A1C265FFB764
W: The repository 'http://mirrors.linode.com/debian wheezy Release' is not signed.
W: There is no public key available for the following key IDs:
8B48AD6246925553  NO_PUBKEY 7638D0442B90D010  NO_PUBKEY 6FB2A1C265FFB764  
+ apt-get install debian-keyring debian-archive-keyring
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  debian-archive-keyring debian-keyring
0 upgraded, 2 newly installed, 0 to remove and 364 not upgraded.
Need to get 32.2 MB of archives.
After this operation, 34.5 MB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 debian-archive-keyring all 2014.3 [39.3 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 debian-keyring all 2016.01.20 [32.2 MB]
Fetched 32.2 MB in 1min 11s (453 kB/s)
Selecting previously unselected package debian-archive-keyring.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 172343 files and directories currently installed.)
Preparing to unpack .../debian-archive-keyring_2014.3_all.deb ...
Unpacking debian-archive-keyring (2014.3) ...
Selecting previously unselected package debian-keyring.
Preparing to unpack .../debian-keyring_2016.01.20_all.deb ...
Unpacking debian-keyring (2016.01.20) ...
Setting up debian-archive-keyring (2014.3) ...
Setting up debian-keyring (2016.01.20) ...
+ [ 0 != 0 ]
+ apt-get update -y
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Ign:3 http://mirrors.linode.com/debian wheezy InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease
Get:5 http://mirrors.linode.com/debian-security wheezy/updates InRelease [40.6 kB]
Hit:6 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:7 http://mirrors.linode.com/debian wheezy-updates InRelease [153 kB]
Hit:8 http://mirrors.linode.com/debian wheezy Release
Get:9 http://mirrors.linode.com/debian wheezy Release.gpg [2,373 B]
Fetched 196 kB in 2s (75.0 kB/s)
Reading package lists...
+ apt-get upgrade -y
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages were automatically installed and are no longer required:
  libjpeg-turbo8 libpango1.0-0 libpangox-1.0-0
Use 'sudo apt autoremove' to remove them.
The following packages have been kept back:
  libtext-charwidth-perl linux-generic linux-headers-generic
  linux-image-generic ubuntu-core-launcher
The following packages will be upgraded:
  accountsservice adium-theme-ubuntu adwaita-icon-theme app-install-data
  apparmor apport apport-gtk appstream apt apt-transport-https apt-utils
  apturl apturl-common bamfdaemon base-files bash bash-completion bind9-host
  binutils brltty bsdutils command-not-found command-not-found-data compiz
  compiz-core compiz-gnome compiz-plugins-default console-setup
  console-setup-linux cpp-5 cups-browsed cups-filters
  cups-filters-core-drivers dh-python distro-info-data dmidecode dnsmasq-base
  dnsutils dosfstools dpkg dpkg-dev eog file-roller firefox fontconfig
  fontconfig-config fonts-noto-cjk fonts-opensymbol fuse fwupd g++-5 gcc-5
  gcc-5-base gdb gdbserver gir1.2-gst-plugins-base-1.0 gir1.2-gstreamer-1.0
  gir1.2-gtk-3.0 gir1.2-javascriptcoregtk-4.0 gir1.2-packagekitglib-1.0
  gir1.2-soup-2.4 gir1.2-unity-5.0 gir1.2-webkit2-4.0 glib-networking
  glib-networking-common glib-networking-services gnome-calendar
  gnome-font-viewer gnome-menus gnome-session-bin gnome-session-common
  gnome-settings-daemon-schemas gnome-software gnome-software-common
  gnome-sudoku gnome-system-monitor gnupg gpgv grep grub-common grub-pc
  grub-pc-bin grub2-common gstreamer1.0-alsa gstreamer1.0-plugins-base
  gstreamer1.0-plugins-base-apps gstreamer1.0-plugins-good
  gstreamer1.0-pulseaudio gstreamer1.0-tools gstreamer1.0-x
  gtk2-engines-murrine gvfs gvfs-backends gvfs-bin gvfs-common gvfs-daemons
  gvfs-fuse gvfs-libs imagemagick imagemagick-6.q16 imagemagick-common
  indicator-bluetooth init init-system-helpers initramfs-tools
  initramfs-tools-bin initramfs-tools-core isc-dhcp-client isc-dhcp-common
  keyboard-configuration klibc-utils language-selector-common
  language-selector-gnome less libaccountsservice0 libapparmor-perl
  libapparmor1 libappstream-glib8 libappstream3 libapt-inst2.0 libapt-pkg5.0
  libarchive13 libasan2 libatomic1 libbamf3-2 libbind9-140 libblkid1
  libboost-date-time1.58.0 libboost-filesystem1.58.0 libboost-iostreams1.58.0
  libboost-system1.58.0 libbrlapi0.6 libcc1-0 libcilkrts5 libcompizconfig0
  libcupsfilters1 libcurl3 libdecoration0 libdfu1 libdns-export162 libdns162
  libdpkg-perl libdrm-amdgpu1 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1
  libdrm2 libegl1-mesa libexpat1 libfdisk1 libfontconfig1 libfontembed1
  libframe6 libfuse2 libfwupd1 libgail-3-0 libgbm1 libgcc-5-dev libgcrypt20
  libgd3 libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libglib2.0-0
  libglib2.0-bin libglib2.0-data libgnome-menu-3-0 libgnutls-openssl27
  libgnutls30 libgomp1 libgstreamer-plugins-base1.0-0
  libgstreamer-plugins-good1.0-0 libgstreamer1.0-0 libgtk-3-0 libgtk-3-bin
  libgtk-3-common libharfbuzz-icu0 libharfbuzz0b libidn11 libimobiledevice6
  libisc-export160 libisc160 libisccc140 libisccfg140 libitm1
  libjavascriptcoregtk-4.0-18 libjpeg8 libklibc libksba8 libldap-2.4-2
  liblightdm-gobject-1-0 libllvm3.8 liblsan0 liblwres141 libmagickcore-6.q16-2
  libmagickcore-6.q16-2-extra libmagickwand-6.q16-2 libmetacity-private3a
  libmount1 libmpx0 libnautilus-extension1a libndp0 libnm-glib-vpn1
  libnm-glib4 libnm-gtk-common libnm-gtk0 libnm-util2 libnm0 libnma-common
  libnma0 libnspr4 libnss3 libnss3-nssdb libnux-4.0-0 libnux-4.0-common
  liboxideqt-qmlplugin liboxideqtcore0 liboxideqtquick0 libp11-kit0
  libpackagekit-glib2-16 libpam-systemd libplymouth4 libpoppler-glib8
  libpoppler58 libpython2.7 libpython2.7-minimal libpython2.7-stdlib
  libpython3.5 libpython3.5-minimal libpython3.5-stdlib libqt5core5a
  libqt5dbus5 libqt5gui5 libqt5network5 libqt5opengl5 libqt5printsupport5
  libqt5sql5 libqt5sql5-sqlite libqt5test5 libqt5widgets5 libqt5xml5
  libquadmath0 libsmartcols1 libsmbclient libsoup-gnome2.4-1 libsoup2.4-1
  libssl1.0.0 libstdc++-5-dev libstdc++6 libsystemd0 libtasn1-6 libtevent0
  libtsan0 libubsan0 libudev1 libunity-control-center1 libunity-core-6.0-9
  libunity-protocol-private0 libunity-scopes-json-def-desktop
  libunity-settings-daemon1 libunity9 libupower-glib3 libusbmuxd4 libuuid1
  libwayland-egl1-mesa libwbclient0 libwebkit2gtk-4.0-37
  libwebkit2gtk-4.0-37-gtk2 libwhoopsie0 libxatracker2 libxml2 light-themes
  lightdm linux-firmware linux-libc-dev lsb-base lsb-release lshw
  metacity-common mount mtools mtr-tiny nautilus nautilus-data network-manager
  network-manager-gnome nux-tools openssh-client openssl oxideqt-codecs
  p11-kit p11-kit-modules plymouth plymouth-label plymouth-theme-ubuntu-logo
  plymouth-theme-ubuntu-text poppler-utils printer-driver-brlaser python2.7
  python2.7-minimal python3-apport python3-brlapi python3-commandnotfound
  python3-distupgrade python3-problem-report python3-pyparsing
  python3-software-properties python3-urllib3 python3.5 python3.5-minimal
  samba-libs sbsigntool shared-mime-info snapd software-properties-common
  software-properties-gtk sudo suru-icon-theme systemd systemd-sysv thermald
  tzdata ubuntu-artwork ubuntu-docs ubuntu-drivers-common ubuntu-mobile-icons
  ubuntu-mono ubuntu-release-upgrader-core ubuntu-release-upgrader-gtk
  ubuntu-session ubuntu-software udev unity unity-control-center
  unity-control-center-faces unity-lens-applications unity-schemas
  unity-scopes-runner unity-services unity-settings-daemon uno-libs3
  update-notifier update-notifier-common upower upstart ure util-linux
  uuid-runtime vim-common vim-tiny vino wget whoopsie xbrlapi xdiagnose xinit
  xserver-common xserver-xorg-core xserver-xorg-video-intel
359 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Need to get 382 MB of archives.
After this operation, 28.1 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libjpeg8 app-install-data
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
+ echo Checking nginx...
Checking nginx...
+ which nginx
+ echo nginx not installed!
nginx not installed!
+ set +x
Do you want to install nginx (y/n)?
+ echo Installing nginx...
Installing nginx...
+ apt-get install -y cron nginx
Reading package lists...
Building dependency tree...
Reading state information...
cron is already the newest version (3.0pl1-128ubuntu2).
The following additional packages will be installed:
  nginx-common nginx-core
Suggested packages:
  fcgiwrap nginx-doc
The following NEW packages will be installed:
  nginx nginx-common nginx-core
0 upgraded, 3 newly installed, 0 to remove and 364 not upgraded.
Need to get 457 kB of archives.
After this operation, 1,480 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 nginx-common all 1.10.0-0ubuntu0.16.04.2 [25.6 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 nginx-core amd64 1.10.0-0ubuntu0.16.04.2 [428 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 nginx all 1.10.0-0ubuntu0.16.04.2 [3,498 B]
Fetched 457 kB in 2s (204 kB/s)
Selecting previously unselected package nginx-common.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 172366 files and directories currently installed.)
Preparing to unpack .../nginx-common_1.10.0-0ubuntu0.16.04.2_all.deb ...
Unpacking nginx-common (1.10.0-0ubuntu0.16.04.2) ...
Selecting previously unselected package nginx-core.
Preparing to unpack .../nginx-core_1.10.0-0ubuntu0.16.04.2_amd64.deb ...
Unpacking nginx-core (1.10.0-0ubuntu0.16.04.2) ...
Selecting previously unselected package nginx.
Preparing to unpack .../nginx_1.10.0-0ubuntu0.16.04.2_all.deb ...
Unpacking nginx (1.10.0-0ubuntu0.16.04.2) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for ufw (0.35-0ubuntu2) ...
Processing triggers for systemd (229-4ubuntu4) ...
Setting up nginx-common (1.10.0-0ubuntu0.16.04.2) ...
Setting up nginx-core (1.10.0-0ubuntu0.16.04.2) ...
Setting up nginx (1.10.0-0ubuntu0.16.04.2) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for systemd (229-4ubuntu4) ...
Processing triggers for ufw (0.35-0ubuntu2) ...
+ [ 0 != 0 ]
+ service nginx start
+ echo Checking PHP...
Checking PHP...
+ hash php
+ echo PHP is not installed!
PHP is not installed!
+ set +x
Do you want to install PHP (y/n)?
+ echo Installing PHP...
Installing PHP...
+ apt-get install -y php5 php5-common
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  apache2-mpm-prefork apache2-utils apache2.2-bin apache2.2-common libapr1
  libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap php5-cli
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  apache2.2-bin dpkg libapr1 libaprutil1 libaprutil1-dbd-sqlite3
  libaprutil1-ldap libdb5.1 libonig2 libqdbm14 php5-cgi
Suggested packages:
  php-pear
The following NEW packages will be installed:
  apache2.2-bin libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap
  libdb5.1 libonig2 libqdbm14 php5 php5-cgi php5-common
The following packages will be upgraded:
  dpkg
1 upgraded, 11 newly installed, 0 to remove and 363 not upgraded.
Need to get 9,795 kB of archives.
After this operation, 24.4 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libdb5.1
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
+ [ 100 != 0 ]
+ echo php5-common installation failed with error code 3
php5-common installation failed with error code 3
+ exit 1

---------
questions:
1. how can I install restyaboard on Ubuntu?
2. Which version of Ubuntu (12? 14? 16?)  and 32 or 64 bit is tested and 100% non-problematic to install?

regards
Bud

**Comment by BlackDuck888** [comment]
@Budo1 You can try my modded install script, whicht works much better, but i am not fully finish with it.

https://github.com/BlackDuck888/board/blob/contrib/installscript/install/restyaboard_apache.sh

**Comment by lmarikannan** [comment]
@Budo1 Sorry for the trouble. We came to know that of late Ubuntu is shipping php7 by default and so this is related to that. We're working to test it in Ubuntu.

**Comment by Budo1** [comment]
@BlackDuck888 thank you for the script.
Can you please write what is not finished or what is not working in the script? What problems may arise when I use your script?

Which version of Ubuntu did you use ? Which is the best?

regards
Bud

**Comment by BlackDuck888** [comment]
@Budo1 
One thing i did get work right now is, that i have to create a board in the installation process, because restayaboard with php7 dont work if there is no board, for these first board i am not able to create a ejabber chat channel right now. Workaround create an other board and delete the "Board" createt at installation.

I use Ubuntu 16.04. I don't know which is best, i prefer the current versions.

Some differences to the origin script are, that i use apache instead of nginx, because apache is already installed in my systems, and my script does not build ejabber or elasticsearch from source, because i use the packages from the distribution, this will help with updates in the future. 

in my next version you will be able to choose at the setup if ejabber should be installed or not, right now it will be installed, but you have to logon an enter the server details in the settings, in the next version this will be allready done by the installation process.

The script is working the not finnished things are just details, to a perfekt script, maybe i make a ncurses version of it, but not shure right now about that.

**Comment by Budo1** [comment]
@BlackDuck888 Thank you.
