### ISSUE TITLE
XSS in board comment

### ISSUE THREAD

**Issue by wruijter** [RestyaPlatform/board#796]
Hey guys, 

There is an XSS in your demo site, I think it also resides in the current version.
When opening a cart and adding an activity, the input:
`<script>alert('xss test')</script>`
will give you xss.

![426240765_82268_11656400246875368572](https://cloud.githubusercontent.com/assets/7447090/18668384/5d216732-7f35-11e6-9c01-2278a3ca1786.jpg)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/01472a539df707a2fce8042f3ed8f27405416ec0
