### ISSUE TITLE
Can't install using the auto-installer. [Debian 8.6 x64 - CentOS 7.2 x64]

### ISSUE THREAD

**Issue by eliassilvaa** [RestyaPlatform/board#797]
Hello, 

Today I wanted to install Restyaboard using the auto-installer. However, the install always ends with an error. 

Processing triggers for libc-bin (2.19-18+deb8u6) ...
+ [ 0 != 0 ]
+ hash pecl/geoip
+ echo extension=geoip.so
+ mkdir -v /usr/share/GeoIP
mkdir: cannot create directory ‘/usr/share/GeoIP’: File exists
+ [ 1 != 0 ]
+ echo GeoIP folder creation failed with error code 52
GeoIP folder creation failed with error code 52
+ exit 1

I tried to install on CentOS 7 and Debian 8.6. 
Both VPS are fresh from DigitalOcean.com

What can I do?

**Comment by Merlin90** [comment]
i have the same Problem :(

**Comment by lmarikannan** [comment]
Related to #703. Fixed in this commit https://github.com/RestyaPlatform/board/commit/b49a091b785018cb426c91afd91a3137b2f01e81
