### ISSUE TITLE
[QA] After starred the boards, it duplicates the same board.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#798]
URL: http://boardalpha.demo.restya.com/#/boards/starred
## Steps to Reproduce:
1. Login as user. (board/testing)
2. After starred the boards, it duplicates the same board.

Refer the attachment.
![starred_duplicate_boards](https://cloud.githubusercontent.com/assets/14884895/18700229/badc2f56-7ff3-11e6-8271-3bc5610c5715.png)
![starred_issue9-21-2016 11-58-16 am](https://cloud.githubusercontent.com/assets/14884895/18700235/c0e83d54-7ff3-11e6-8dd1-12493918819d.png)

**Comment by lmarikannan** [comment]
@sathya313 Its a record problem in demo server and now its working fine.
