### ISSUE TITLE
[QA] In home page, dashboard, click on organizations button. need to display "No Organizations"

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#799]
In home page, dashboard, click on organizations button need to display "No Organizations"

Refer the attachment
![no_organizations9-21-2016 12-12-03 pm](https://cloud.githubusercontent.com/assets/14884895/18700467/140448c4-7ff5-11e6-83db-adb6732f1beb.png)

**Comment by lmarikannan** [comment]
Duplicate #896
