### ISSUE TITLE
Restya shows 404 Page not found on debian

### ISSUE THREAD

**Issue by JosepEscobar** [RestyaPlatform/board#80]

**Comment by rrjanbiah** [comment]
@JosepEscobar Please check if you've configured nginx properly https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf

**Comment by JosepEscobar** [comment]
I installed by docker method.

**Comment by rrjanbiah** [comment]
@JosepEscobar 

@namikingsoft has pushed some updates lately https://github.com/namikingsoft/docker-restyaboard/commit/0fbd60ad2b61f452f680be24f8046031cc868fcd

Can you try latest version?

**Comment by JosepEscobar** [comment]
Yes, its mine. 

FROM debian:wheezy-backports

# restyaboard version
ENV restyaboard_version=v0.1.3

# update & install package
RUN \


But now, i try clean SO installation.

**Comment by rrjanbiah** [comment]
> But now, i try clean SO installation.

@JosepEscobar Please let us know how it goes.

**Comment by JosepEscobar** [comment]
Now works!  my contribution:

STEP BY STEP ON DEBIAN (DOCKER MODE)

1. Install docker from : https://docs.docker.com/installation/debian/#debian-jessie-80-64-bit
* Add repo: $ apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
* deb http://apt.dockerproject.org/repo debian-jessie main
* $ sudo apt-get update
* $ sudo apt-get install docker-engine
* $ sudo service docker start
2. Install curl & git: 
* $ sudo apt-get install curl git dialog
3. Install docker-compose from: https://github.com/docker/compose/releases
* curl -L https://github.com/docker/compose/releases/download/1.4.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
* chmod +x /usr/local/bin/docker-compose
4. Install RestyaBoard: https://github.com/namikingsoft/docker-restyaboard
* git clone https://github.com/namikingsoft/docker-restyaboard.git
* cd docker-restyaboard
* docker-compose up -d

**Comment by rrjanbiah** [comment]
@JosepEscobar Awesome, thanks for your contribution
