### ISSUE TITLE
[QA] After login through github, and clicked import button. its keep on loading.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#800]
## Steps to Reproduce:
1. After login through github, and clicked import button. its keep on loading for long time.

Refer the attachment.
![github_issue9-21-2016 12-56-53 pm](https://cloud.githubusercontent.com/assets/14884895/18701930/fd8d4570-7ffc-11e6-805c-946e2f2127e9.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board-apps/pull/69/commits/da143e292efd9467733cfa4fd0d7a4e8ee6d6741
