### ISSUE TITLE
[QA] While adding members to the board. After choosen the name, taken time to close the pop up.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#802]
URL: http://boardalpha.demo.restya.com/#/board/24

Steps to Reproduce:
----------------------
1. Login as user. (board / testing)
2. While adding members to the board. After choosen the name, taken time to close the pop up.

Refer the attachment.
![after_member_chosen_pop_not_closed](https://cloud.githubusercontent.com/assets/14884895/18705115/8e6f5058-800a-11e6-8ca8-069bb3344728.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/pull/854/commits/65a4b9bb1d6a0363c997d117fca4f407c2468b67
