### ISSUE TITLE
[QA] After removed the member from the card, again refreshed the board the same member is displayed in the card.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#803]
URL: http://boardalpha.demo.restya.com/#/board/19

Steps to Reproduce:
--------------------
1. Login as user. (board / testing)
2. After removed the member from the card, again refreshed the board the same member is displayed in the card.

Refer the attachment.
![member_issue_01](https://cloud.githubusercontent.com/assets/14884895/18706153/81f24638-800e-11e6-8ed8-8f9449076e31.png)
![Uploading member_issue_02.png…]()
![Uploading member_issue_03.png…]()
![Uploading member_issue_04.png…]()

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/pull/854/commits/65a4b9bb1d6a0363c997d117fca4f407c2468b67
