### ISSUE TITLE
[QA] After the changed the organizations name, Its not updated in the organizations dropdown lists.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#804]
URL: http://boardalpha.demo.restya.com/#/organizations
## Steps to Reproduce:
1. Login as user. (board / testing)
2. After the changed the organizations name, Its not updated in the organizations drop down lists.

Refer the attachment.
![org_name_issue](https://cloud.githubusercontent.com/assets/14884895/18706897/6aec7ec4-8011-11e6-8b5a-98da6f064c43.png)
![Uploading org_name_issu.png…]()
![Uploading organization_issue_01.png…]()

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/413a9d3ae1c23a70df81a9e782866cf97ab07beb
