### ISSUE TITLE
[QA] In card activity page, after edit the comment, close icon is not working.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#806]
Steps to Reproduce:
---------------------
1. Login as user. (board / testing)
2. In card activity page, after edit the comment, close icon is not working.

Refer the attachment.
![close_icon_not_working](https://cloud.githubusercontent.com/assets/14884895/18708182/3dea2858-8017-11e6-8166-b44d6c187a16.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/d3f8113d48fdc44cb5a63f069e30efe39b070b48
