### ISSUE TITLE
[QA] Once click on user avatar icon from activities page, It redirected to an empty profile tab page.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#807]
URL: http://boardalpha.demo.restya.com/?organization_id=5#/board/24/card/773

Steps to Reproduce:
----------------------
1.  Login as user. (board / testing)
2. Once click on user avatar icon from activities page, It redirected to an empty profile tab page.

Refer the attachment.
![in_profile_laod_more_activities_issue](https://cloud.githubusercontent.com/assets/14884895/18708789/42e2f030-801a-11e6-8d30-fabc01333810.png)
![click_activity_profile_icon](https://cloud.githubusercontent.com/assets/14884895/18708790/42e69398-801a-11e6-82c5-d714e44ca3f4.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/3d3cb8a677362011a371cdace407871eee3d84c7
