### ISSUE TITLE
[QA] In signup page the email validation is not proper.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#808]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/
2.Click register
3.Enter the invalid email 
4.The user is successfully registered.
## Expected Result:

Need email validation.

Refer the attachment
![the user successfully registered](https://cloud.githubusercontent.com/assets/14290356/18709302/2335ecd0-801d-11e6-9ae8-5b70745eac63.png)
![in signup page the email validation is not proper](https://cloud.githubusercontent.com/assets/14290356/18709303/23723596-801d-11e6-88f8-2cdadab56694.png)

**Comment by lmarikannan** [comment]
@srileka We have used HTML5 email validation, so its not a problem.
