### ISSUE TITLE
[QA] While searching emoji design issue. need scroll bar in listed emoji's drop down.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#809]
URL: http://boardalpha.demo.restya.com/?organization_id=5#/board/24/card/773
## Steps to Reproduce:
1. Login as user. (board / testing)
2. While searching emoji design issue. need scroll bar in listed emoji's drop down.

Refer the attachment.
![Uploading emoji_liested_page_design_issue.png…]()
![emoji_listed_issue](https://cloud.githubusercontent.com/assets/14884895/18709345/4b96ab7e-801d-11e6-9a95-141ecdd29dd7.png)

While searching emoji design issue. need scroll bar in listed emoji's.

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/ee144d875b754911fb524d9d86d19c2ec841c242
