### ISSUE TITLE
In docker installation, domain names not work

### ISSUE THREAD

**Issue by JosepEscobar** [RestyaPlatform/board#81]
I installed with docker method, and i can login to the board with internal LAN IP (Like 192.168...). 
But I can't login with domain name (Like board.mydomainname.com).

Then show a empty dialog message at the upper left corner.

**Comment by rrjanbiah** [comment]
@JosepEscobar Are you getting any error in browser console?

**Comment by JosepEscobar** [comment]
nope, consola shows normal message:

```javascript
Document was loaded from Application Cache with manifest http://board.ticplace.com:1234/default.appcache
(index):1 Application Cache Checking event
(index):1 Application Cache NoUpdate event
```

**Comment by rrjanbiah** [comment]
@JosepEscobar Sorry, but can you look into the net tab and see responses? Please see if there's any differences when you use domain name and IP.

**Comment by JosepEscobar** [comment]
Here the screenshot:
![screenshot](http://ticplace.com/screens/Captura%20de%20pantalla%202015-10-13%20a%20les%2010.55.39.png)

**Comment by JosepEscobar** [comment]
New screenshot:
![screenshot](http://www.ticplace.com/screens/Captura%20de%20pantalla%202015-10-13%20a%20les%2013.24.20.png)

**Comment by rrjanbiah** [comment]
@JosepEscobar Can you please check the response of `settings.json` call?

Also, we're not sure from where the `main.js` and `detector.js` are getting loaded (they're not available in Restyaboard).

**Comment by JosepEscobar** [comment]
This is the network console with hostname:
![screenshot](http://ticplace.com/screens/Captura%20de%20pantalla%202015-10-13%20a%20les%2014.13.48.png)

This is the network console with IP address:
![screenshot](http://www.ticplace.com/screens/Captura%20de%20pantalla%202015-10-13%20a%20les%2014.14.08.png)

I obserbe one difrence at login with hostname, we receive a undefined token:
![screenshot](http://ticplace.com/screens/Captura%20de%20pantalla%202015-10-13%20a%20les%2014.15.04.png)

But when i log in by IP i received a real token:
![screenshot](http://ticplace.com/screens/Captura%20de%20pantalla%202015-10-13%20a%20les%2014.14.37.png)

**Comment by JosepEscobar** [comment]
settings.json call
![screenshot](http://ticplace.com/screens/Captura%20de%20pantalla%202015-10-13%20a%20les%2014.31.18.png)

**Comment by rrjanbiah** [comment]
@JosepEscobar It looks like the `oauth.json` call is failing. We'll need sometime to look into it. We'll update you tomorrow. Thanks for your understanding.

**Comment by JosepEscobar** [comment]
No problem, thanks to you!

**Comment by rrjanbiah** [comment]
(Self note: Probably related to https://github.com/namikingsoft/docker-restyaboard/issues/2 ??)

**Comment by rrjanbiah** [comment]
@JosepEscobar It looks like the HTTP request to generate token (from server side) is failing. This issue seems to be related to https://github.com/namikingsoft/docker-restyaboard/issues/2#issuecomment-147890744 Can you please check if that is resolving your issue?

**Comment by jujes** [comment]
Hi, someone know how get let's encrypt ssl https feature?
**deploy script**

```
sudo su
git clone https://github.com/letsencrypt/letsencrypt /opt/letsencrypt
cd /opt/letsencrypt/
[----> choose standalone]
  /opt/letsencrypt/letsencrypt-auto certonly
[----> certs path]
/etc/letsencrypt/live/[sitemane]
exit
git clone https://github.com/namikingsoft/docker-restyaboard.git restyaboard
cd restyaboard
[----> change 443 instead 1234 ]
nano docker-compose.yml
  ports:
    - 443:80
  volumes:
    - certs:/etc/letsencrypt/live/[sitemane]
docker-compose up -d
```

**output**

```
Successfully built d88cb20591b6
WARNING: Image for service restyaboard was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating restyaboard_data_1
Creating restyaboard_postgres_1
Creating restyaboard_elasticsearch_1
Creating restyaboard_restyaboard_1
user@ubuntu:~/dpl/restyaboard$ docker ps -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                 NAMES
f0afe7887ec8        restyaboard_restyaboard   "/docker-entrypoint.s"   4 minutes ago       Up 4 minutes        0.0.0.0:443->80/tcp   restyaboard_restyaboard_1
241655e31e66        elasticsearch             "/docker-entrypoint.s"   4 minutes ago       Up 4 minutes        9200/tcp, 9300/tcp    restyaboard_elasticsearch_1
a6abfcf020b6        postgres                  "/docker-entrypoint.s"   4 minutes ago       Up 4 minutes        5432/tcp              restyaboard_postgres_1
c797a2439de4        busybox                   "tail -f /dev/null"      4 minutes ago       Up 4 minutes                              restyaboard_data_1
```

**Comment by rrjanbiah** [comment]
Reopening the issue. Not sure how the commit will fix the issue. Also, looks like the vendor files are patched wrongly.

**Comment by lmarikannan** [comment]
@rrjanbiah Due to curl exec call this issue was happend. On this commit we're changed curl to separate function to resolve this issue
