### ISSUE TITLE
[QA] Add a member name to the edit box, by default it will display in activity comment box.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#810]
## Steps to Reproduce:
1. After edit the added comment.
2. Then delete all the content, 
3. Add a member name to the edit box, by default it will display in activity comment box.

![by_default_it_displayed_member_twice](https://cloud.githubusercontent.com/assets/14884895/18709543/49bf4148-801e-11e6-9a31-645f28179928.png)
![Uploading comment_member_name_issue.png…]()
Refer the attachment.

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/63d7b4acd6286b87c634a9010504517a9817d244
