### ISSUE TITLE
[QA] If click shortcuts the bullets displayed at the left corner.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#811]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/boards
2.Login as board002 // testing
3.If click shortcuts the bullets displayed at the left corner.

Refer the attachment
![if click shortcuts the bullets displayed at the left corner](https://cloud.githubusercontent.com/assets/14290356/18709581/7ac877e6-801e-11e6-9cc9-1cdc9a0c1480.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/4515abc22ba538133be14d282ed0e95277234c66
