### ISSUE TITLE
[QA] In settings page for timezone field, need autoloader.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#812]
URl: http://boardalpha.demo.restya.com/?organization_id=5#/user/26/settings
## Steps to Reproduce:
1. In settings page for timezone field, need auto loader.

Refer the attachment.
![time_zone_issue](https://cloud.githubusercontent.com/assets/14884895/18709921/1f98a6d2-8020-11e6-942c-668f4fa4ec8f.png)

**Comment by lmarikannan** [comment]
@sathya313 We will implement when we get more request from users.
