### ISSUE TITLE
[QA]Copy list functionality is not  working.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#813]
Copy list functionality is not  working.

Refer the attachment.
![copy_list_functionality_not_working](https://cloud.githubusercontent.com/assets/14884895/18710303/231b1252-8022-11e6-93d9-93f20c151078.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/bdb3c9fb9a76e21e6bc6b46df4629bb7f1d2a8e0
