### ISSUE TITLE
[QA] If click the chat icon the popup not opened.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#814]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/boards
2.Login as board002 // testing
3.If click the chat icon the popup not opened.

refer the attachment
![if click the chat icon the popup not opened](https://cloud.githubusercontent.com/assets/14290356/18710923/384a3e16-8025-11e6-8b1c-6f7a1a1bb7b9.png)

**Comment by lmarikannan** [comment]
Duplicate #829
