### ISSUE TITLE
[QA] In instant add card popup without fill the details click save button an error message displayed is hided.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#815]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/boards
2.Login as board002 // testing
3.Click instant add card button.
4. In instant add card popup without fill the details click save button an error message displayed is hided.

Refer the attachment
![in instant add card popup without fill the details click save button an error message displayed is hided](https://cloud.githubusercontent.com/assets/14290356/18711042/be6d361a-8025-11e6-9cb8-7a3c1207a04f.png)

**Comment by lmarikannan** [comment]
@srileka We cannot able to reproduce this issue.
