### ISSUE TITLE
[QA] In find boards by name search field if enter any letter the scroll is displayed.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#816]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/
2.Login as board002 // testing
3.Click boards dropdown in footer
4.In find boards by name search field if enter any letter the scroll is displayed.

Refer the attachment
![in find boards by name search field if enter any letter the scroll is displayed](https://cloud.githubusercontent.com/assets/14290356/18711208/74de910a-8026-11e6-9211-4d4fa4559d98.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/192b7c9aa7163dbe8087637dea35830449394516
