### ISSUE TITLE
[QA] In about page the version and date not updated.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#817]
Steps to reproduce:
-------------------------
1.URL: http://boardalpha.demo.restya.com/#/about
2.In about page the version and date not updated.

refer the attachment
![in about page the version and date not updated](https://cloud.githubusercontent.com/assets/14290356/18711601/5bf5f3b6-8028-11e6-8eb4-b3eeb8279d6b.png)

**Comment by lmarikannan** [comment]
@srileka No need to change version and date, because last version `v0.3` released on `June 30, 2016`. Please refer http://restya.com/board/changelog. So Closing this for now
