### ISSUE TITLE
[QA] In board view page if click the add a list field layout anywhere the add list should open.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#818]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/board/25
2.Login as board002 // testing
3.Click Test Board
4.In board view page if click the add a list field layout anywhere the add list should open.

refer the attachment
![in board view page if click the add a list field layout anywhere the add list should open](https://cloud.githubusercontent.com/assets/14290356/18712034/242243d4-802a-11e6-9e5c-4d11189c2a0e.png)

**Comment by lmarikannan** [comment]
@srileka We will implement when we get more request from users.
