### ISSUE TITLE
[QA] In activities messages not proper after added auto archive days. 

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#819]
Steps to Reproduce:
---------------------
1. Login as user. (board / testing)
2. In list additional settings, after added the auto archive days.
3. In activities messages not proper.

Refer the attachment.
![while-adding_auto_archive](https://cloud.githubusercontent.com/assets/14884895/18712297/6cc726da-802b-11e6-9c11-108f10de1a8e.png)
![auto_archive_activities_issue](https://cloud.githubusercontent.com/assets/14884895/18712298/6d355b28-802b-11e6-8b79-460230a26a56.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/pull/861/files
