### ISSUE TITLE
[QA] In card details page the actions menus alignments are not proper.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#820]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/board/25/card/779
2.Login as board002 // testing
3.Click Test Board
4.Click any one card
5.In card details page the actions menus alignments are not proper.
## Expected Result:

1.Need left alignment

Refer the attachment
![in card details page the actions menus alignments are not proper](https://cloud.githubusercontent.com/assets/14290356/18712406/e61f3a90-802b-11e6-8474-59dbb3251817.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/01472a539df707a2fce8042f3ed8f27405416ec0
