### ISSUE TITLE
[QA] In card detail page for copy action the keep... heading should change as copy to...

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#821]
Steps to reproduce:
-------------------------
1.URL: http://boardalpha.demo.restya.com/#/board/25/card/780
2.Click Test Board
3.Click any card
4.In card detail page for copy action the keep... heading should change as copy to...

Refer the attachment
![in card detail page for copy action the keep heading should change as copy to](https://cloud.githubusercontent.com/assets/14290356/18712767/775e1db8-802d-11e6-8a6b-58c597c2f8c3.png)

**Comment by lmarikannan** [comment]
Fixed.
