### ISSUE TITLE
[QA] If pop in the card the issue: thanks! help fix? dropdown is displayed.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#822]
Steps to reproduce:
-------------------------
1.URL: http://boardalpha.demo.restya.com/#/board/25/card/780
2.Login as board002 // testing
3.Click Test Board
4.Click any card 
5. If pop in the card the issue: thanks! help fix? the dropdown is displayed.

Refer the attachment
![in card details page click pop in](https://cloud.githubusercontent.com/assets/14290356/18713408/de64dffe-802f-11e6-8283-92ddfd15894d.png)
![if pop in the card the issue thanks help fix dropdown is displayed](https://cloud.githubusercontent.com/assets/14290356/18713409/de65cb80-802f-11e6-82dc-c24e4abf0b9a.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board-apps/pull/64/commits/20bce228f6dddf5b0049c8f119d170b577db49de
