### ISSUE TITLE
[QA] Open any card while adding checklist, after clicked add button, pop up is not closing. 

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#823]
URL: http://boardalpha.demo.restya.com/#/board/24/card/785

Steps to Reproduce:
---------------------
1. Login as user. (Board / testing)
2. Open any card while adding checklist, after clicked add button, pop up is not closing.

refer the attachment.
![checklist_issue](https://cloud.githubusercontent.com/assets/14884895/18713982/e54e3106-8031-11e6-9df8-36d7875bdbea.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/pull/854/commits/65a4b9bb1d6a0363c997d117fca4f407c2468b67
