### ISSUE TITLE
[QA] In list Subscribed icon alignment issue.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#824]
In list Subscribed icon alignment issue.

Refer the attachment.
![subscribed_alignment_issue](https://cloud.githubusercontent.com/assets/14884895/18738166/d3c7e532-80b6-11e6-92f1-4e17727d867e.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/272ee24e221ee08c13f72aa5dd76674494e05978
