### ISSUE TITLE
[QA] After keep on clicking on votes icon, it increases the votes count.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#825]
URL: http://boardalpha.demo.restya.com/#/board/24/card/785

Steps to Reproduce:
----------------------
1. Login as user. (board / testing)
2. After keep on clicking on votes icon, it increases the votes count.

Refer the attachment.
![votes_issue_9-22-2016 11-51-24 am](https://cloud.githubusercontent.com/assets/14884895/18738633/1592c212-80bb-11e6-88d7-7ecf74f8a445.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/pull/854/commits/65a4b9bb1d6a0363c997d117fca4f407c2468b67
