### ISSUE TITLE
[QA] Once deleted all the attachments, it should display information as "No attachments found"

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#826]
URL: http://boardalpha.demo.restya.com/#/board/24
## Steps to Reproduce:
1. Login as user. (board / testing)
2. Once deleted all the attachments, it should display information as "No attachments found"

Refer the attachment.
![attachments_message_issue](https://cloud.githubusercontent.com/assets/14884895/18739305/2ec0f2b8-80c0-11e6-87d7-9286a16463b6.png)
![attachments-issue](https://cloud.githubusercontent.com/assets/14884895/18739306/2ec49ee0-80c0-11e6-964e-a5c74849624e.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/eec2b7f950b93f36b8db5ddb6ac08f5dfc8e80cd
