### ISSUE TITLE
[QA] home page footer search is not working.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#827]
home page footer search is not working.

Refer the attachment.
![restyaboard_footer_search_not-working](https://cloud.githubusercontent.com/assets/14884895/18739726/398e54c6-80c3-11e6-8523-49aa6c48bd21.png)

**Comment by fwolfst** [comment]
I face the same issue and guess that elasticsearch is not correctly set up. In that case imho the interface should reflect that change (have a crossed out search icon, or get rid of it alltogether).

**Comment by rrjanbiah** [comment]
@fwolfst That's a very good suggestion

**Comment by baskar383** [comment]
Elastic search indexing has not done. So we executed the indexing and now it is working fine.

**Comment by rrjanbiah** [comment]
Reopened. Looks like @fwolfst suggestion is misunderstood.

**Comment by lmarikannan** [comment]
ElasticSearch and Chat button will disable if its not configured.
