### ISSUE TITLE
[QA] After clicking load more button everytime, its keep on loading and duplicate the same activities.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#828]
![load_more_activities_issue](https://cloud.githubusercontent.com/assets/14884895/18739963/bd8da582-80c4-11e6-8aa6-05ca26d6df54.png)
URL: http://boardalpha.demo.restya.com/#/user/26/profile

Steps to Reproduce:
---------------------
1. Login as user. (board / testing)
2. After clicking load more button everytime, its keep on loading and duplicate the same activities.

Refer the attachment.

**Comment by baskar383** [comment]
fixed in this commit
https://github.com/RestyaPlatform/board/commit/58471a91dd828a691414f351b8ef414a6b714f67
