### ISSUE TITLE
[QA] After clicked on chat, chat window is not displayed.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#829]
URL: http://boardalpha.demo.restya.com/#/user/26
## Steps to Reproduce:
1. Login as user. (board / testing)
2. After clicked on chat, chat window is not displayed.

Refer the attachment.
![chat_window_not_displayed](https://cloud.githubusercontent.com/assets/14884895/18740265/77c9e6d0-80c6-11e6-8f07-acfcee2cbb76.png)

**Comment by fwolfst** [comment]
I assume that the interplay with ejabberd is not correctly configured. If thats the case I would opt for either have a crossed-out chat icon if no chat server is configured or get rid of the icon alltogether in that case.

**Comment by rrjanbiah** [comment]
@fwolfst ejabberd may not be always the reason. We strongly believe that it is something to do with the client library we have used, as we have configured live xmpp server that we connect internally.

**Comment by lmarikannan** [comment]
Related to #732.
