### ISSUE TITLE
[QA] In archived items if there is no cards available the delete all button should be hided.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#830]
Steps to reproduce:
-------------------------
1.URL: http://boardalpha.demo.restya.com/#/board/25
2.Login as board002 // testing
3.Click Test Board
4.Click any card and archive the card.
5.In archived items if there is no cards available the delete all button should be hided.

Refer the attachment
![in archived items if there is no cards available the delete all button should be hided](https://cloud.githubusercontent.com/assets/14290356/18743719/f59b8ecc-80d7-11e6-8757-cd2146508ffc.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/c6d71e482a1f857f1185782d15665084510b08d9
