### ISSUE TITLE
[QA] In card detail page after added the activity and click the delete button its not working.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#831]
Steps to reproduce:
-------------------------
1.URL: http://boardalpha.demo.restya.com/#/board/25/card/782
2.Login as board002 // testing
3.Click Test board
4.Click any card
5.In card detail page add the comments
6.After added the comment click delete button its not working.

Refer the attachment
![in card detail page after added the activity and click the delete button its not working](https://cloud.githubusercontent.com/assets/14290356/18743934/15bc63d8-80d9-11e6-8615-d911da529025.png)

**Comment by baskar383** [comment]
Fixed in this commit
https://github.com/RestyaPlatform/board/commit/7f21132245465dd6bebabeb2caa03f612db65476
