### ISSUE TITLE
[QA] After added the comment click edit button, once the edit field opened click close icon its not working.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#832]
Steps to reproduce:
--------------------------
1.URL: http://boardalpha.demo.restya.com/#/board/25/card/782
2.Login as board002 // testing
3.Click Test board
4.Click any card
5.In card detail page add the comments
6.After added the comment click edit button.
7.Once the edit field opened click close icon its not working.

Refer the attachment
![once edit the close button not working](https://cloud.githubusercontent.com/assets/14290356/18743992/5d0f37c4-80d9-11e6-9273-5d180e912246.png)
![click the edit button the close button not working](https://cloud.githubusercontent.com/assets/14290356/18744017/8d1dc1d8-80d9-11e6-8bde-7f52011c2d70.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/d3f8113d48fdc44cb5a63f069e30efe39b070b48
