### ISSUE TITLE
[QA] In instant card after entered "a" in search field, displayed results design was broken.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#833]
URL: http://boardalpha.demo.restya.com/#/user/26/profile
## Steps to Reproduce:
1. Login as user. (board / testing)
2. In instant card, while adding member after entered "a" in search field, displayed results design was broken.

refer the attachment.
![search_design_issue](https://cloud.githubusercontent.com/assets/14884895/18744056/dd16dd00-80d9-11e6-99ae-537c8032ce1c.png)
![instant_card_search_design](https://cloud.githubusercontent.com/assets/14884895/18744057/dd213e44-80d9-11e6-8baa-42e159bf4a9b.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/ded551c2f412ac902dbbd443aafabb18e433b871
