### ISSUE TITLE
[QA] In admin dashboard for this week and last week filter need splitter lines for days identification

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#834]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/boards
2.Login as admin // restya
3.In admin dashboard for this week and last week filter need splitter lines for days identification
Refer the attachment
![in admin dashboard for this week filter need splitter lines for days identification](https://cloud.githubusercontent.com/assets/14290356/18745012/2eda7800-80de-11e6-919b-990036d44fb4.png)

**Comment by lmarikannan** [comment]
@srileka We have used jQuery Sparkline charts and splitter is available only when data is available for the date.
