### ISSUE TITLE
[QA] If one made changes in the board, its not reflected in another user for the same board, within the proper time frame.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#835]
![drag_card_list](https://cloud.githubusercontent.com/assets/14884895/18745489/fa6aeb52-80df-11e6-8df8-1451ecedb686.png)
## Steps to Reproduce:
1. Login user. (board / testing)
2. board was shared to the other member. (board01 /  testing)
3. Shared board name was "Test board" 
4. Both the users are in online and working in same board.
5. If one made changes in the board, its not reflected in another user for the same board, within the proper time frame.
   ![drag_card_issue](https://cloud.githubusercontent.com/assets/14884895/18745239/21c3470e-80df-11e6-93e8-bf790fa528ca.png)
   ![drag_card_list](https://cloud.githubusercontent.com/assets/14884895/18745489/fa6aeb52-80df-11e6-8df8-1451ecedb686.png)

refer the attachment

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/71f03ecd3efb4a2cc275240aff6442dcd0eadd19
