### ISSUE TITLE
[QA] In admin dashboard for overall block if click the filter records not displayed.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#836]
Steps to reproduce:
--------------------------
1.URL: http://boardalpha.demo.restya.com/#/boards
2.Login as admin // restya
3.In admin dashboard for overall block if click the filter records not displayed.

Refer the attachment
![in admin dashboard for overall block if click the filter records not displayed](https://cloud.githubusercontent.com/assets/14290356/18745778/355d78f0-80e1-11e6-8ed2-16e3d0a405f7.png)
![no records found is displayed](https://cloud.githubusercontent.com/assets/14290356/18745779/358f67c0-80e1-11e6-969f-0062261cdd94.png)

**Comment by baskar383** [comment]
Elastic search indexing has not done. So we executed the indexing and now it is working fine.
