### ISSUE TITLE
[QA] In overall filters and unassigned filter page if scroll down fraction of seconds all the board displayed

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#837]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/search/due:unassigned
2.Login as admin // restya
3.In overall filters and unassigned filter page if scroll down fraction of seconds all the board displayed.

Refer the attachment
![in overall filters and unassigned filter page if scroll down fraction of seconds all the board displayed](https://cloud.githubusercontent.com/assets/14290356/18745904/dec5159c-80e1-11e6-9a62-69c00ba69f7a.png)
![click any filter for overall and unassigned](https://cloud.githubusercontent.com/assets/14290356/18745905/deccb040-80e1-11e6-9bd4-c1034af6b37f.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/3ad042dd0ff36df1ba16b63563af455bf6cc85b7
