### ISSUE TITLE
[QA] After added image from google drive. Image was not displayed properly.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#838]
URL: http://boardalpha.demo.restya.com/#/board/24/card/777

Steps to Reproduce:
--------------------------
1. Login as user. (board01 / testing)
2. 
![drop_box-issue](https://cloud.githubusercontent.com/assets/14884895/18745892/d339e52c-80e1-11e6-9885-44b110a85a32.png)
After added image from google drive. Image was not displayed properly.

Refer the attachment.

**Comment by baskar383** [comment]
Functionality done as per Trello.

**Comment by rrjanbiah** [comment]
Reopened. If it is done as per Trello, why is it not working properly?

**Comment by baskar383** [comment]
If we upload an image from drop box, we  display only the drop box icon instead of image. Now it is working like this only. The query is raised why the image is not displaying. So we have replied as "It is working as like trello".
