### ISSUE TITLE
No Organizations Available

### ISSUE THREAD

**Issue by ktdmedia** [RestyaPlatform/board#84]
When clicking Organizations button as an admin it displays correctly. As a user, "No organizations available."  for any board not created by that user.

Installed using docker, ubuntu 14.04.

**Comment by ktdmedia** [comment]
When you visit the Organization manually "/#/organization/9" it works fine.

**Comment by rrjanbiah** [comment]
@srileka Kindly try to reproduce

**Comment by srileka** [comment]
Could you check whether the organization is a Public or Private? If it is public organization you can view those boards.

**Comment by rrjanbiah** [comment]
@ktdmedia Can we have your comment on @srileka note, please?:

> Could you check whether the organization is a Public or Private? If it is public organization you can view those boards.

**Comment by ktdmedia** [comment]
@rrjanbiah @srileka - The permission setting has no effect on the error. It occurs even if the Organization is Public.

**Comment by rrjanbiah** [comment]
@ktdmedia Thanks for your report. It seems to be related to https://github.com/namikingsoft/docker-restyaboard/issues/2#issuecomment-147890744 Can you please check and confirm?

**Comment by mishio** [comment]
I get this problem too (v0.1.5 on Ubuntu) though it doesn't seem to happen on your demo site.

Not sure if "/#/organization/9" works though, it sends me to #/boards.

**Comment by ssivachidambaram** [comment]
Fixed in v0.1.6.
