### ISSUE TITLE
[QA] After clicked subscribe button, there is no proper successful flash message.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#840]
URL: http://boardalpha.demo.restya.com/#/board/24/card/770

After clicked subscribe button, there is no proper successful flash message.

Refer the attachment.
![subscribe_issue](https://cloud.githubusercontent.com/assets/14884895/18747571/aeddd0c6-80eb-11e6-8178-18e8468088e1.png)

**Comment by lmarikannan** [comment]
@sathya313  For card actions, we will not provide flash message because every actions showing the changes immediately.
