### ISSUE TITLE
[QA] Once change the role permission for user its not reflected to user properly. Once logout the user only its working

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#841]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/boards
2.Login as admin // restya in one browser and login as board002 // testing in another browser.
3.In admin change the role permission for users.
4.In user refresh and ctrl + F5 the page and check the changed permission is not working properly.
5.Once logout the user only its working.

Refer the attachment
![the new board option is displayed](https://cloud.githubusercontent.com/assets/14290356/18748142/8f0d2c26-80ee-11e6-9f80-303bc5f63e21.png)
![once change the role permission for user its not reflected to user properly once logout the user only its working](https://cloud.githubusercontent.com/assets/14290356/18748144/9229db66-80ee-11e6-911d-c6a13af779d3.png)

**Comment by lmarikannan** [comment]
@srileka We are storing it in cookie to fetch the records every time from server. So if we got any requests from other user will fix this.
