### ISSUE TITLE
[QA] After clicked unassigned button, it redirected to "No Records found" page.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#842]
URL: http://boardalpha.demo.restya.com/#/boards

Steps to Reproduce:
--------------------------
1. Login as user. (board / testing)
2. From user dsashboard after clicked unassigned button, it redirected to "No Records found" page.

Refer the attachment.
![unassigned_button](https://cloud.githubusercontent.com/assets/14884895/18749409/59f1a08e-80f4-11e6-87a3-2a83a048b423.png)

**Comment by baskar383** [comment]
Elastic search indexing has not done. So we executed the indexing and now it is working fine.
