### ISSUE TITLE
[QA] In activity layout click comments icon  if no comments the message should displayed as no record found

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#843]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/board/28
2.Login as board003 // testing
3.Click the notification icon.
4.In activity layout click comments icon  if no comments the message should displayed as no record found

Refer the attachment
![if no comments the message should displayed as no record found](https://cloud.githubusercontent.com/assets/14290356/18750266/11f2016c-80f8-11e6-9901-8d795822f80a.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/2d5a36bbd679c54fe6534472e869464b2439525e
