### ISSUE TITLE
Docker installation fails at Step 13: COPY docker-entrypoint.sh /

### ISSUE THREAD

**Issue by AmirMeirbekov** [RestyaPlatform/board#844]
I am following instructions on getting up and running Restya board with docker. I receive the following error at `Step 13` of Dockerfile
````
Step 13 : COPY docker-entrypoint.sh /
ERROR: Service 'restyaboard' failed to build: stat /var/lib/docker/aufs/mnt/0d56f82e541370adcee20f68d656fdf50dc6a611688d6a26e7af5134dbb432f7/docker-entrypoint.sh: no such file or directory
```

**Comment by AmirMeirbekov** [comment]
I tried on another server and it worked, not sure what was the problem

**Comment by Xqua** [comment]
I have the same problem ... this is so weird ... the file is in the directory ...
