### ISSUE TITLE
I want to add some new field to card ?

### ISSUE THREAD

**Issue by gnoble** [RestyaPlatform/board#845]
hello, 
please let me know how can i add new fields to card , my client wants modification (php), i want to know how can i modify it 
thanks

**Comment by rrjanbiah** [comment]
@gnoble You may refer to our "Estimated Time Custom Field" app code as a starting point to use custom fields API

**Comment by gnoble** [comment]
I want to add one custom field like Question? yes / no if no then one textbox appear and it will store with card , can you help me here
thanks

**Comment by lmarikannan** [comment]
You can change/update your custom field in this app https://github.com/RestyaPlatform/board-apps/blob/master/r_auto_archive_expired_cards/json/app.json
