### ISSUE TITLE
LDAP Import Problem

### ISSUE THREAD

**Issue by 88fingerslukee** [RestyaPlatform/board#849]
Forgive me if this is answered somewhere else but I can't import LDAP users. The Import button just keeps loading and loading forever.

I installed using the docker setup so I have no idea where to view logs. Can somebody please help?

See image of settings below.

![restya ldap issue](https://cloud.githubusercontent.com/assets/2788639/19196923/3c23ad44-8c6c-11e6-8fcb-821f69b88608.PNG)

**Comment by Speed03** [comment]
Use command:
docker logs _nameOfYourContainer_ 

Add -f if you want to follow logs

Personally, using the official docker image, I had to install php5-ldap in the container to have ldap functions. If it's the same for you, you will see an error in the logs : _undedined function ldap_connect()_

**Comment by lmarikannan** [comment]
@Speed03 Thank you very much for your response.

@88fingerslukee Can you please check and let me know whether its working for you?

**Comment by lmarikannan** [comment]
@88fingerslukee Please feel free to reopen if you got issue.

**Comment by 88fingerslukee** [comment]
Sorry, I had to blow away my server and just got it up again.  I'm not seeing that error, I see this one on repeat:

`==> /var/log/nginx/error.log <==
2017/01/06 19:51:49 [error] 75#0: *3 FastCGI sent in stderr: "PHP message: PHP Warning:  fopen(/usr/share/nginx/html/tmp/cache/site_url_for_shell.php): failed to open stream: Permission denied in /usr/share/nginx/html/server/php/config.inc.php on line 42
PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/server/php/config.inc.php on line 43
PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/server/php/config.inc.php on line 44
PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/server/php/config.inc.php on line 45" while reading response header from upstream, client: 192.168.0.3, server: _, request: "GET /api/v1/users/1/activities.json?type=all&last_activity_id=2&token=dad9f585133db4b4e401b5d83a687bd48147a11a&_=1483732309742 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.1.182:1234", referrer: "http://192.168.1.182:1234/"

==> /var/log/nginx/access.log <==
192.168.0.3 - - [06/Jan/2017:19:51:49 +0000] "GET /api/v1/users/1/activities.json?type=all&last_activity_id=2&token=dad9f585133db4b4e401b5d83a687bd48147a11a&_=1483732309742 HTTP/1.1" 200 116 "http://192.168.1.182:1234/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
`

**Comment by lmarikannan** [comment]
@88fingerslukee Can you please provide write permission for this path `/usr/share/nginx/html/tmp/`?
