### ISSUE TITLE
Unable to create an Admin account. (404 Error)

### ISSUE THREAD

**Issue by ktdmedia** [RestyaPlatform/board#85]
Any account set to admin loads fine then after a few seconds on almost any page it starts displaying a 404 error. 

It seems like when it's refreshing for updates its getting stuck somewhere in the process because if you reload and quickly navigate through the site it works as intended. 

However, this doesn't apply to the default admin account created at startup. Only new ones given the Admin role.

**Comment by rrjanbiah** [comment]
@srileka Kindly try to reproduce

**Comment by srileka** [comment]
Its working fine for us.(Firefox, chrome) in Win 8.1, 7, Xp and Mac.

**Comment by ktdmedia** [comment]
I've done a fresh install, again with Docker on 14.04 and the error still occurs. I don't think it's browser related.

**Comment by rrjanbiah** [comment]
@ktdmedia Thanks for your report. It seems to be related to https://github.com/namikingsoft/docker-restyaboard/issues/2#issuecomment-147890744 Can you please check and confirm?

**Comment by cemarta7** [comment]
I think this is the same as issue #92
