### ISSUE TITLE
Use relative links in index.html

### ISSUE THREAD

**Issue by basti122303** [RestyaPlatform/board#850]
Hello, please use relative links in index.html for more flexible installations.
<link rel="stylesheet" href="./css/
var api_url = './api/v1/';
var template_url = './client/';

Best Regards,
Basti

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/c1f28afd4cef4ebf63e51786391dd292e7ef9e3b
