### ISSUE TITLE
Moving a card - as seen by other user

### ISSUE THREAD

**Issue by ssivachidambaram** [RestyaPlatform/board#851]
I have difficulty understanding the rationale behind how moving a card, is shown on other desktops. 

I my test setup I made a board and shared it with a colleague. On the board I made some lists and added a card to one list. When my colleague moves the card to another list on his view of the board, then on my view, it "shakes" and is highlighted a short while - but stays in the current list. Only when I hit browser reload it is redrawn on its new location according to my colleague action. 

I admit I am new to kanban boards, but is this how it is supposed to work?

From Klaus Vink Slott, https://groups.google.com/forum/#!topic/restya/Ng66cKzrBsM

**Comment by assionx** [comment]
Another issue based on this is that other person moved the same card to the same position.
There is an activity log created. 
In my opinion,there is nothing should happen.

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/71f03ecd3efb4a2cc275240aff6442dcd0eadd19
