### ISSUE TITLE
Script failed to install

### ISSUE THREAD

**Issue by iamnido** [RestyaPlatform/board#856]
I am installing Restyaboard in Ubuntu 16.04 LTS and got the following errors because of dependencies

> cron : PreDepends: dpkg (>= 1.15.7.2) but it is not going to be installed
>         Depends: libpam0g (>= 0.99.7.1) but it is not going to be installed
>         Depends: adduser but it is not going to be installed
>         Depends: libpam-runtime (>= 1.0.1-11) but it is not going to be installed
> init-system-helpers : Depends: perl-base (>= 5.20.1-3) but it is not going to be installed
>                        Conflicts: file-rc (< 0.8.17~) but 0.8.15 is to be installed
> nginx : Depends: nginx-core (>= 1.10.0-0ubuntu0.16.04.2) but it is not going to be installed or
>                   nginx-full (>= 1.10.0-0ubuntu0.16.04.2) but it is not going to be installed or
>                   nginx-light (>= 1.10.0-0ubuntu0.16.04.2) but it is not going to be installed or
>                   nginx-extras (>= 1.10.0-0ubuntu0.16.04.2) but it is not going to be installed
>          Depends: nginx-core (< 1.10.0-0ubuntu0.16.04.2.1~) but it is not going to be installed or
>                   nginx-full (< 1.10.0-0ubuntu0.16.04.2.1~) but it is not going to be installed or
>                   nginx-light (< 1.10.0-0ubuntu0.16.04.2.1~) but it is not going to be installed or
>                   nginx-extras (< 1.10.0-0ubuntu0.16.04.2.1~) but it is not going to be installed
> php5-cli : Depends: libssl1.0.0 (>= 1.0.0) but it is not going to be installed
>             Depends: php5-common (= 5.4.45-0+deb7u5) but it is not going to be installed
>             Depends: ucf but it is not going to be installed
>             Depends: tzdata but it is not going to be installed
> php5-fpm : PreDepends: dpkg (>= 1.16.1~) but it is not going to be installed
>             Depends: libssl1.0.0 (>= 1.0.0) but it is not going to be installed
>             Depends: php5-common (= 5.4.45-0+deb7u5) but it is not going to be installed
>             Depends: ucf but it is not going to be installed
>             Depends: tzdata but it is not going to be installed

**Comment by lmarikannan** [comment]
Install script upgraded to PHP 7 in Ubuntu 16.04 and fixed in this commit https://github.com/RestyaPlatform/board/commit/14c8d56818098b3ed56709e419d8e04ab29a3e44, https://github.com/RestyaPlatform/board/commit/d0356b2231c061b6c8adc804f691de0e63937f2b
