### ISSUE TITLE
Zapier connect doesn't work (401 Unauthorized)

### ISSUE THREAD

**Issue by kramer65** [RestyaPlatform/board#867]
I'm trying to connect my restyaboard instance with Zapier. To do this I downloaded the zapier app from http://restya.com/board/apps and unzipped it on my server into the client folder. It then shows up on the apps page:

![zapier in restya](https://cloud.githubusercontent.com/assets/596581/19519336/cc7be7dc-960b-11e6-91c0-f0d78ebb4f25.png)

And when I click on the Zapier Connect settings icon on the right and then on "Settings" I see a screen which includes a secret and a OAuth Token Url:

![zapier client secret in restya](https://cloud.githubusercontent.com/assets/596581/19519372/01d159da-960c-11e6-8948-750dae111c50.png)

I then include this info in zapier:

![zapier fill in details](https://cloud.githubusercontent.com/assets/596581/19519524/ad0f5b76-960c-11e6-8e47-6a6d0e4d12a9.png)

and click "yes continue", I get the following error:

![zapier error](https://cloud.githubusercontent.com/assets/596581/19519544/b9a5daf4-960c-11e6-925b-d8404fd6128f.png)

Does anybody know what could be wrong here?

All tips are welcome!

**Comment by lmarikannan** [comment]
@kramer65 As per your screenshot you have updated the `Zapier Client Secret` as access token in Zapier. Please follow the steps mentioned in this URL http://restya.com/board/integrations to get your Access Token to update in Zapier.

**Comment by kramer65** [comment]
@lmarikannan - I would like to, but I don't see the "Connect with Zapier" button. As you can see in my first screenshot, the only thing I see is the grey "enabled" button on the right, but if I click that nothing happens. I can only edit the "Zapier Connect settings" which you see in my second screenshot.

Do you have a tip on how I would get the "Connect with Zapier" button?

**Comment by lmarikannan** [comment]
@kramer65 Click `Apps` button in footer menu and then click "Zapier Connect" as mentioned in this screenshot http://restya.com/images/zapier_app.png.

**Comment by kramer65** [comment]
@lmarikannan 
Wait wut?! That `Apps` button wasn't in the footer menu before, but now it appeared. Alright, so I clicked that, then "Connect with Zapier", then I logged in, then clicked "Allow", and then I get a message saying "Authentication failed".

I get past the "log in" screen into the "Allow" screen just before that so I presume my username/password is accepted. Any idea what could be wrong here?

![screen shot 2016-10-19 at 15 43 14](https://cloud.githubusercontent.com/assets/596581/19521307/6a74dc9e-9613-11e6-9ed5-ae533eeed059.png)

**Comment by lmarikannan** [comment]
@kramer65 

We can't reproduce this in our demo server. So Can you please replace this file instead of  `board/server/php/oauth_callback.php` and rename the attached file format to `.php`. Once replace this file, again you need to connect zapier. After that process, log file will be created on that same path (`board/server/php/`) with the name of `zapier_errorlog.log`. 

After that, you please share that log file here

[oauth_callback.txt](https://github.com/RestyaPlatform/board/files/539318/oauth_callback.txt)

**Comment by lmarikannan** [comment]
@kramer65 We're waiting for your reply

**Comment by kramer65** [comment]
@lmarikannan - I really appreciate your answer. Today and tomorrow I'm working on a big migration, but after that I've got time for restya again and I'll get back to you with the logs.

**Comment by lmarikannan** [comment]
@kramer65 No problem. Please take your time.

**Comment by lmarikannan** [comment]
@kramer65 Please feel free to reopen, if you still face any issues.
