### ISSUE TITLE
Dev branch install fails on Debian

### ISSUE THREAD

**Issue by UrosB** [RestyaPlatform/board#871]
php7 is in Debian testing&sid, but not in Debian stable.

Also, apt-add-repository missing on "clean" debian.

++ add-apt-repository ppa:ondrej/php
./restyaboard.sh: line 192: add-apt-repository: command not found

**Comment by UrosB** [comment]
Also, apt-add-repository missing on "clean" debian.

++ add-apt-repository ppa:ondrej/php
./restyaboard.sh: line 192: add-apt-repository: command not found

**Comment by lmarikannan** [comment]
@UrosB Thank you for your suggestion.

**Comment by miniminime** [comment]
Same is true for Ubuntu 16.10. Installation fails due to php5 dependencies.

**Comment by lmarikannan** [comment]
@miniminime @UrosB Yes. We are working in the `dev` branch. Latest commit https://github.com/RestyaPlatform/board/commit/18dd4b9d04916a7706e7677af4b2a9295752dcd8. Now we are getting issue while install `php-pgsql` extension.

**Comment by lmarikannan** [comment]
We have fixed this in our `dev` version.
