### ISSUE TITLE
Emoji not working properly in edit comment form

### ISSUE THREAD

**Issue by baskar383** [RestyaPlatform/board#874]
Emoji not working properly in edit comment form. When we and then update the comment with emoji it is not changing to icons, displaying as string.
![screenshot at 2016-10-22 14 17 13](https://cloud.githubusercontent.com/assets/17172610/19618250/4db317be-9862-11e6-8eff-a731caf6ffcf.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/bc252885225a1e2d70dfdef9c8a434b9c1b17ab0
