### ISSUE TITLE
While reply comment "Add Emoji" is not displaying.

### ISSUE THREAD

**Issue by baskar383** [RestyaPlatform/board#876]
While reply comment "Add Emoji" is not displaying.
![screenshot at 2016-10-22 14 51 49](https://cloud.githubusercontent.com/assets/17172610/19618396/421d1738-9867-11e6-8b14-f51f2128bb09.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/a73db9e25f60473bb183ecfe86ac2af288a56360
