### ISSUE TITLE
Unable to import the data's from Github.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#881]
![unable_to_import_from_github](https://cloud.githubusercontent.com/assets/14884895/19647465/caf60e06-9a1b-11e6-98ae-88eecfe367ad.png)
URL: http://boardalpha.demo.restya.com/#/organizations
## Steps to Reproduce:
1. Login as user. (k.sathyaraj+restya001@agriya.in // testing)
2. Click boards and then again click on Import from GitHub.
3. After signed in through Github. Its keep on loading.

Refer the attachment.

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board-apps/pull/69/commits/da143e292efd9467733cfa4fd0d7a4e8ee6d6741
