### ISSUE TITLE
[QA] Search functionality is not working.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#882]
## Steps to Reproduce:
1. Login as user. (restya001 / testing)
2. Search functionality is not working.

Refer the attachment.
![search is not working](https://cloud.githubusercontent.com/assets/14884895/19675005/82232e28-9aa9-11e6-83db-b180e9db6bdd.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/3ad042dd0ff36df1ba16b63563af455bf6cc85b7
