### ISSUE TITLE
[QA] After blocked the subscribe menu in list, should not be clickable....

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#883]
URL: http://boardalpha.demo.restya.com/#/board/38
## Steps to Reproduce:
1. Login as user. (restya001 / testing)
2. After blocked the subscribe menu in the list, should not be clickable.

Refer the attachment.
![should_not_be_clickable](https://cloud.githubusercontent.com/assets/14884895/19676106/f4a9b2fe-9aaf-11e6-8063-753cd3b7b139.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/a9d9ec083df9495cbfcd71eebfbc7433dc1d03f8
