### ISSUE TITLE
[QA] In user login, after clicked the load more activities. Its keep on loading and repeating the same activities

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#884]
URL: http://boardalpha.demo.restya.com/#/user/35
## Steps to Reproduce:
1. Login as user. (restya001 / testing)
2. Go to user activities page, after clicked every time "Load more activities". It repeated the same activities 
   ![same_activities](https://cloud.githubusercontent.com/assets/14884895/19677900/26bd26c8-9ab9-11e6-80cd-7dd5f7558a60.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/8eed42f813c290a7e50a73aef1bf829aaa3f762d
