### ISSUE TITLE
[QA] After updated the profile image is keep on loading.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#887]
URL: http://boardalpha.demo.restya.com/#/user/35/settings
# Steps to Reproduce:
1. Login as user. (restya001 / testing)
2. After updated the profile image is keep on loading.

Refer the attachment.
![image_upload_issue](https://cloud.githubusercontent.com/assets/14884895/19684331/44e447a6-9ad4-11e6-8132-695894e2a3c8.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/da745e33f06218eed5e9f43ecc42eeabf7498208
