### ISSUE TITLE
[QA] Unable to import the QA Checklists Board. It displayed an error message as "Website QA Checklists board create failed"

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#889]
Unable to import the QA Checklists Board. It displayed an error message as "Website QA Checklists board create failed"

Refer the attachment.
![website_qa_checklist issue](https://cloud.githubusercontent.com/assets/14884895/19687170/0cb18d7c-9ae2-11e6-8530-c3a1f086b81d.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board-apps/pull/69/commits/da143e292efd9467733cfa4fd0d7a4e8ee6d6741
