### ISSUE TITLE
[QA] In move list missing, current list placeholder.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#890]
URL: http://boardalpha.demo.restya.com/#/board/37
## Steps to Reproduce:
1. Login as user. (restya001 / testing)
2. After moved all the cards from "Move all the cards" to "test"
3. Again if we try to move the same cards from "test" to "Move all the cards", It's not displayed the current place holder.

R
![missing_current_place_holder](https://cloud.githubusercontent.com/assets/14884895/19689196/2ffbed10-9aea-11e6-8108-335a15b99d38.png)
efer the attachment.

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/74184cc04ce9e545a0749b29a95cc16b903e78b5
