### ISSUE TITLE
[QA]Notification messages were not been disappeared.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#891]
Notification messages were not been disappeared. 
![notifications were not getting disappeared 10-26-2016 3-16-26 pm](https://cloud.githubusercontent.com/assets/14884895/19757366/2d3a49c6-9c40-11e6-97ef-bb9d487c3a42.png)

**Comment by baskar383** [comment]
That notification is browser compatible, so not able to fix it.
