### ISSUE TITLE
[QA] In Auto Archive Expired Cards popup the dot should be removed from the sentence.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#892]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/boards
2.Login as admin
3.Click Apps -> Auto Archive Expired Cards
4.In Auto Archive Expired Cards pop up the dot should be removed from the sentence.

Refer the attachment
![in auto archive expired cards popup the dot should be removed from the sentence](https://cloud.githubusercontent.com/assets/14290356/19715280/b152115a-9b71-11e6-93a0-17fb4b3167f9.png)

**Comment by baskar383** [comment]
Refer this commit

https://github.com/RestyaPlatform/board-apps/pull/67/commits/100c1ce6bcfa6c28ea13eb3ed261513f303b1fb9
