### ISSUE TITLE
[QA] After select estimated time, submit button is not working properly.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#893]
# Steps To Reproduce
1. Login as (saravanan.r+420@agriya.in \ testing).
2. After select estimated time, submit button is not working properly.

Refer the attachment

![estimated time 10-26-2016 11-40-54 am](https://cloud.githubusercontent.com/assets/14884895/19715319/fca913ce-9b71-11e6-8b78-24113d9c64c7.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board-apps/commit/da143e292efd9467733cfa4fd0d7a4e8ee6d6741
