### ISSUE TITLE
[QA] After opened the card unable to open the apps dropdown.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#894]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/board/33/card/833
2.Login as admin
3.click any board
4.Click any card
5.After opened the card unable to open the apps dropdown.

Refer the attachment
![after opened the card unable to open the apps](https://cloud.githubusercontent.com/assets/14290356/19715800/6c05c3ae-9b75-11e6-848b-9a9eb92adf5b.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/3f09b351029abca035621d99cad783d0171a9d04
