### ISSUE TITLE
[QA] Unable to disable the apps in admin control panel.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#895]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/apps
2.Login as admin
3.In admin control panel click apps
4.Unable to disable the apps in admin control panel.

Refer the attachment

![unable to disable the apps in admin control panel](https://cloud.githubusercontent.com/assets/14290356/19716448/6d4a2e18-9b79-11e6-88bf-d37dbf034dd0.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/4b4964277433a358f40643a10703ced9d995e0ca
