### ISSUE TITLE
[QA] After click organizations button, it displayed as no organization found.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#896]
# Steps To Reproduce
1. Login as (saravanan.r+420@agriya.in \ testing).
2. After click organizations button, it displayed as no organization found.

Refer the attachment

![organization button 10-26-2016 1-01-59 pm](https://cloud.githubusercontent.com/assets/14884895/19717106/ae290d3e-9b7c-11e6-81c8-128abdb68612.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/pull/919/commits/124bc793cfd2179a95b31d01e05dcd85f35901c6
