### ISSUE TITLE
[QA] In SEO checklist pop up if click import template button its not working.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#897]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/boards
2.Login as admin
3.In apps->Click SEO checklist
4.In SEO checklist pop up if click import template button it's not working.

Refer the attachment
![in SEO checklist pop up if click import template button its not working](https://cloud.githubusercontent.com/assets/14290356/19719280/dbb72fce-9b86-11e6-8511-f5927a54f1b1.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board-apps/commit/da143e292efd9467733cfa4fd0d7a4e8ee6d6741
