### ISSUE TITLE
[QA] In apps if click Post my comments to Slack its not working.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#898]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/boards
2.Login as admin
3.In Apps->Click Post my comments to Slack it's not working.

Refer the attachment

![in apps if click post my comments to slack its not working](https://cloud.githubusercontent.com/assets/14290356/19719408/5d531de0-9b87-11e6-9e88-5827c734a5f3.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board-apps/commit/da143e292efd9467733cfa4fd0d7a4e8ee6d6741
