### ISSUE TITLE
[QA] After click comment button, the page should be refresh. 

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#899]
# Steps To Reproduce 
1. Login as (saravan \ testing).
2. After click comment button, the page should be refresh. 

Refer the attachment

![comment button 10-26-2016 2-28-57 pm](https://cloud.githubusercontent.com/assets/14884895/19719856/5fd0a9aa-9b89-11e6-8fc4-719b8778d42c.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/2c10160a60032a74e701c0c285eae5626b928545
