### ISSUE TITLE
[QA] In apps list the Auto Archive Expired Cards apps displayed twice.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#900]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/apps
2.Login as admin
3.In admin control panel click apps
4. In apps list, the Auto Archive Expired Cards apps displayed twice.

Refer the attachment
![in apps list the auto archive expired cards apps displayed twice](https://cloud.githubusercontent.com/assets/14290356/19719853/5b934488-9b89-11e6-92f5-5c9c015d8c90.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board-apps/commit/da143e292efd9467733cfa4fd0d7a4e8ee6d6741
