### ISSUE TITLE
[QA] In apps if click Zapier Connect its not working.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#901]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/boards
2.Login as admin
3.In apps, if click Zapier Connect it's not working.

Refer the attachment
![in apps if click zapier connect its not working](https://cloud.githubusercontent.com/assets/14290356/19720019/fba83834-9b89-11e6-902d-4a4637cc7098.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board-apps/commit/da143e292efd9467733cfa4fd0d7a4e8ee6d6741
