### ISSUE TITLE
[QA] Position dropdown box overlapped taskbar menu.

### ISSUE THREAD

**Issue by sathya313** [RestyaPlatform/board#903]
Steps To Reproduce 
============
1. Login as (saravan \\ testing).
2. Position dropdown box overlapped task bar menu.

Refer the attachment

![dropdown box10-26-2016 4-30-11 pm](https://cloud.githubusercontent.com/assets/14884895/19723613/aaee8c6c-9b99-11e6-833b-4559802392d0.png)

**Comment by baskar383** [comment]
When more list is available the list will not get down inside, instead it will be shown upwards. Refer screenshot attached
![screenshot at 2016-10-26 18 08 00](https://cloud.githubusercontent.com/assets/17172610/19726281/bfc1cf1a-9ba7-11e6-9f35-e6055fe7912f.png)
