### ISSUE TITLE
[QA] Board search is not working.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#904]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/boards
2.Login as demo001 // testing
3.Board search is not working.

Refer the attachment

![board search is not working](https://cloud.githubusercontent.com/assets/14290356/19724126/3af68484-9b9c-11e6-898c-57e78f60a52f.png)
![boards page](https://cloud.githubusercontent.com/assets/14290356/19724127/3afd389c-9b9c-11e6-83dc-f5636f98283c.png)
![if search board it is displayed as no records found](https://cloud.githubusercontent.com/assets/14290356/19724128/3b243ba4-9b9c-11e6-82a3-d29864c82377.png)

**Comment by lmarikannan** [comment]
Duplicate #882
