### ISSUE TITLE
[QA] In user roles the unstar board displayed twice.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#906]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/roles
2.Login as admin
3. In user roles, the unstar board displayed twice.

Refer the attachment
![in user roles the unstar board displayed twice](https://cloud.githubusercontent.com/assets/14290356/19726117/dc7c6382-9ba6-11e6-8ddc-333fee6cc0b4.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/a6afa7674d0df92d67d9458e7893361eea32795e
