### ISSUE TITLE
[QA] In user roles, the XMPP chat login and chat history are displayed twice.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#907]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/roles
2.Login as admin
3.In user roles, the XMPP chat login and chat history are displayed twice.

Refer the attachment
![in user roles the xmpp chat login and chat history are displayed twice](https://cloud.githubusercontent.com/assets/14290356/19726260/a9444cc2-9ba7-11e6-9bef-3d7829cd5b43.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/4b0f8af44bf65c3cf1a2d7193313dbc02b270fa8
