### ISSUE TITLE
[QA] Unable to add the Add organization User Role and Board User Role.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#908]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/roles
2.Login as admin
3.Click Roles
4.Unable to add the Add organization User Role and Board User Role.

Refer the attachment
![unable to add the add organization user role and board user role](https://cloud.githubusercontent.com/assets/14290356/19726622/71161d6a-9ba9-11e6-9029-6069df98fbd6.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/2eb8d5aeef9d7165ed8ff0c4862b1b57027b9566
