### ISSUE TITLE
[QA] In roles page after added the role for user unable to delete.

### ISSUE THREAD

**Issue by srileka** [RestyaPlatform/board#909]
## Steps to reproduce:

1.URL: http://boardalpha.demo.restya.com/#/roles
2.Login as admin
3.Click Roles
4.In roles page after added the role for user unable to delete.

Refer the attachment
![in roles page after added the role for user unable to delete](https://cloud.githubusercontent.com/assets/14290356/19726685/bc863fdc-9ba9-11e6-97c8-b916ef33ee1a.png)

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/7470acfc6e7801389cbf54b0cf6032c0c46755a5
