### ISSUE TITLE
404 Page not found. activities.json

### ISSUE THREAD

**Issue by cemarta7** [RestyaPlatform/board#92]
when trigger /api/v1/users/4/activities.json I am getting 404 Page not found.
It does not happen with the default admin account but with new accounts.

server:1234/api/v1/users/4/activities.json?type=all&last_activity_id=null&token... is getting no response
from logs:

[error] 166#0: *606 FastCGI sent in stderr: "PHP message: PHP Warning:  pg_query_params(): Query failed: ERROR:  invalid input syntax for integer: &quot;null&quot; in /usr/share/nginx/html/server/php/R/r.php on line 561" while reading response header from upstream, client: XX.xxx.xx.xxx, server: _, request: "GET /api/v1/users/4/activities.json?type=all&last_activity_id=null&token=fcad1e9a85aff87955ec761671d921332f6f0e5d&_=1445011039561 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:",

def is the last_activity_id but not sure why is not putting the value there

**Comment by rrjanbiah** [comment]
@cemarta7 Sorry, we somehow missed your bug report

@srileka Please check if you can reproduce this error in latest build

**Comment by srileka** [comment]
@cemarta7  we found the issue and its reproducible.

once if we change permission, for new users as admin. this issue is occurring.

**Comment by rrjanbiah** [comment]
> We found the issue and its reproducible.
> 
> Once if we change permission, for new users as admin. this issue is occurring.

@srileka Thanks for confirming
