### ISSUE TITLE
.sh installation on Centos

### ISSUE THREAD

**Issue by danieljsc** [RestyaPlatform/board#921]
Hi,
Whilhe trying to install on Centos 6 (64 bit), the script is trying to install postgresql via a not existing repository.
Can you check/update it please?

Thanks

Log where the error is triggered:

Do you want to install PostgreSQL (y/n)?
y
++ case "${answer}" in
++ echo 'Installing PostgreSQL...'
Installing PostgreSQL...
+++ getconf LONG_BIT
++ '[' 64 = 32 ']'
+++ getconf LONG_BIT
++ '[' 64 = 64 ']'
++ yum install -y http://yum.postgresql.org/9.4/redhat/rhel-6.6-x86_64/pgdg-centos94-9.4-1.noarch.rpm
Loaded plugins: fastestmirror, presto
Setting up Install Process
Cannot open: http://yum.postgresql.org/9.4/redhat/rhel-6.6-x86_64/pgdg-centos94-9.4-1.noarch.rpm. Skipping.
Error: Nothing to do
++ '[' 1 '!=' 0 ']'
++ echo 'Installing PostgreSQL 64 fail with error code 28'
Installing PostgreSQL 64 fail with error code 28
++ exit 1

**Comment by lmarikannan** [comment]
@danieljsc  Fixed in `dev` branch. Can you please download this https://raw.githubusercontent.com/RestyaPlatform/board/dev/restyaboard.sh and try again?

**Comment by danieljsc** [comment]
hi sorry for not creating a pull request, i fixed it in the script i
downloaded and already installed.

Daniel Castro
IST - University of Lisbon
<http://pt.linkedin.com/pub/daniel-castro/17/7bb/a59>

2016-11-03 5:46 GMT+00:00 lmarikannan <notifications@github.com>:

**Comment by rrjanbiah** [comment]
@danieljsc No problem. Glad to know that you're already on Restyaboard :)
