### ISSUE TITLE
Error during installation -  PSQL_VERSION=9.5

### ISSUE THREAD

**Issue by Polycris** [RestyaPlatform/board#924]
Hi!!!
I've been tried to install restya on my server Ubuntu 16.04.1 LTS and I had problems with the version ok postgresql. 

+ psql --version
+ egrep -o [0-9]{1,}\.[0-9]{1,}
+ PSQL_VERSION=9.5
restyaboard.sh: 361: restyaboard.sh: cannot open 9.3: No such file
+ [[ 9.5 ]]
restyaboard.sh: 361: restyaboard.sh: [[: not found
restyaboard.sh: 382: restyaboard.sh: cannot open /etc/postgresql/9.4/main/pg_hba.conf: No such file
+ sed -e s/peer/trust/g -e s/ident/trust/g
+ cd /etc/postgresql/9.4/main
restyaboard.sh: 383: cd: can't cd to /etc/postgresql/9.4/main
+ exit

Is there a way to downgrade my current db or is possible to fix the script to work with the new version ok postgresql?

Thanks!
Poly

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/18dd4b9d04916a7706e7677af4b2a9295752dcd8
