### ISSUE TITLE
Blank page with no error

### ISSUE THREAD

**Issue by vurgoe** [RestyaPlatform/board#93]
I try to install RestyaBoard on my own server, the env is as follow:
OS : Redhat 6.2
postgreSQL : 9.2
Nginx : 1.8
php : 5.6.14 with php-fpm & php-pgsql

The program run and exit at line 3546 with a response in r.php, the first time I entered. However when I back to my browser, I find noting.
If I manually exit before echo, I could see the header and 404 error.

I'm sure I have dump the database and the php run and connect to database. Nginx is also working with the config file you offered(restyabroad.conf).

I've no idea, how to fix this problem. Any ideas?

**Comment by vurgoe** [comment]
I got oauth.json 200 & setting.json 200

**Comment by rrjanbiah** [comment]
@srileka Please check if you can reproduce this error in latest build

**Comment by vurgoe** [comment]
Sorry I use the source code built with grunt rather than using build version.

**Comment by rrjanbiah** [comment]
@vurgoe That shouldn't be a problem too. Anyway, we'll also check from our end on this. Thanks for your report anyway.
