### ISSUE TITLE
login failed with any user

### ISSUE THREAD

**Issue by corganhejijun** [RestyaPlatform/board#940]
the same with the situation in
https://groups.google.com/forum/#!topic/restya/tJ050sUq4U0

with debug on, i have a response of:
`
{"id":"1","links":"[{\"slug\":\"board_star\"},{\"slug\":\"board_star\"},{\"slug\":\"unstarred_board\"},{\"slug\":\"unstarred_board\"},{\"slug\":\"add_user_profile_picture\"},{\"slug\":\"add_user_profile_picture\"},{\"slug\":\"view_board\"},{\"slug\":\"view_board\"},{\"slug\":\"view_webhooks\"},{\"slug\":\"view_webhooks\"},{\"slug\":\"add_board\"},{\"slug\":\"add_board\"},{\"slug\":\"add_organization\"},{\"slug\":\"add_organization\"},{\"slug\":\"add_webhook\"},{\"slug\":\"add_webhook\"},{\"slug\":\"activities_listing\"},{\"slug\":\"activities_listing\"},{\"slug\":\"view_board_search\"},{\"slug\":\"view_board_search\"},{\"slug\":\"edit_user_details\"},{\"slug\":\"edit_user_details\"},{\"slug\":\"edit_webhook\"},{\"slug\":\"edit_webhook\"},{\"slug\":\"delete_connected_applications\"},{\"slug\":\"delete_connected_applications\"},{\"slug\":\"view_search\"},{\"slug\":\"view_search\"},{\"slug\":\"load_settings\"},{\"slug\":\"load_settings\"},{\"slug\":\"starred_board\"},{\"slug\":\"starred_board\"},{\"slug\":\"view_board_listing\"},{\"slug\":\"view_board_listing\"},{\"slug\":\"view_organization\"},{\"slug\":\"view_organization\"},{\"slug\":\"view_organization_listing\"},{\"slug\":\"view_organization_listing\"},{\"slug\":\"view_board_star\"},{\"slug\":\"view_board_star\"},{\"slug\":\"view_user\"},{\"slug\":\"view_user\"},{\"slug\":\"view_workflow_templates\"},{\"slug\":\"view_workflow_templates\"},{\"slug\":\"view_board_visibility\"},{\"slug\":\"view_board_visibility\"},{\"slug\":\"view_my_boards\"},{\"slug\":\"view_my_boards\"},{\"slug\":\"view_closed_boards\"},{\"slug\":\"view_closed_boards\"},{\"slug\":\"view_connected_applications\"},{\"slug\":\"view_connected_applications\"},{\"slug\":\"view_organization_visibility\"},{\"slug\":\"view_organization_visibility\"},{\"slug\":\"view_user_activities\"},{\"slug\":\"view_user_activities\"},{\"slug\":\"view_user_board\"},{\"slug\":\"view_user_board\"},{\"slug\":\"view_user_cards\"},{\"slug\":\"view_user_cards\"},{\"slug\":\"view_user_search\"},{\"slug\":\"view_user_search\"},{\"slug\":\"view_stared_boards\"},{\"slug\":\"view_stared_boards\"},{\"slug\":\"user_changepassword\"},{\"slug\":\"user_changepassword\"},{\"slug\":\"delete_webhook\"},{\"slug\":\"delete_webhook\"},{\"slug\":\"undo_activity\"},{\"slug\":\"undo_activity\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"role_add\"},{\"slug\":\"role_add\"},{\"slug\":\"board_user_role_add\"},{\"slug\":\"board_user_role_add\"},{\"slug\":\"organization_user_role_add\"},{\"slug\":\"organization_user_role_add\"},{\"slug\":\"role_edit\"},{\"slug\":\"role_edit\"},{\"slug\":\"board_user_role_edit\"},{\"slug\":\"board_user_role_edit\"},{\"slug\":\"organization_user_role_edit\"},{\"slug\":\"organization_user_role_edit\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"role_add\"},{\"slug\":\"role_add\"},{\"slug\":\"role_add\"},{\"slug\":\"role_add\"},{\"slug\":\"board_user_role_add\"},{\"slug\":\"board_user_role_add\"},{\"slug\":\"board_user_role_add\"},{\"slug\":\"board_user_role_add\"},{\"slug\":\"organization_user_role_add\"},{\"slug\":\"organization_user_role_add\"},{\"slug\":\"organization_user_role_add\"},{\"slug\":\"organization_user_role_add\"},{\"slug\":\"role_edit\"},{\"slug\":\"role_edit\"},{\"slug\":\"role_edit\"},{\"slug\":\"role_edit\"},{\"slug\":\"board_user_role_edit\"},{\"slug\":\"board_user_role_edit\"},{\"slug\":\"board_user_role_edit\"},{\"slug\":\"board_user_role_edit\"},{\"slug\":\"organization_user_role_edit\"},{\"slug\":\"organization_user_role_edit\"},{\"slug\":\"organization_user_role_edit\"},{\"slug\":\"organization_user_role_edit\"},{\"slug\":\"board_star\"},{\"slug\":\"board_star\"},{\"slug\":\"unstarred_board\"},{\"slug\":\"unstarred_board\"},{\"slug\":\"add_user_profile_picture\"},{\"slug\":\"add_user_profile_picture\"},{\"slug\":\"view_board\"},{\"slug\":\"view_board\"},{\"slug\":\"view_webhooks\"},{\"slug\":\"view_webhooks\"},{\"slug\":\"add_board\"},{\"slug\":\"add_board\"},{\"slug\":\"add_organization\"},{\"slug\":\"add_organization\"},{\"slug\":\"add_webhook\"},{\"slug\":\"add_webhook\"},{\"slug\":\"activities_listing\"},{\"slug\":\"activities_listing\"},{\"slug\":\"view_board_search\"},{\"slug\":\"view_board_search\"},{\"slug\":\"edit_user_details\"},{\"slug\":\"edit_user_details\"},{\"slug\":\"edit_webhook\"},{\"slug\":\"edit_webhook\"},{\"slug\":\"delete_connected_applications\"},{\"slug\":\"delete_connected_applications\"},{\"slug\":\"view_search\"},{\"slug\":\"view_search\"},{\"slug\":\"load_settings\"},{\"slug\":\"load_settings\"},{\"slug\":\"starred_board\"},{\"slug\":\"starred_board\"},{\"slug\":\"view_board_listing\"},{\"slug\":\"view_board_listing\"},{\"slug\":\"view_organization\"},{\"slug\":\"view_organization\"},{\"slug\":\"view_organization_listing\"},{\"slug\":\"view_organization_listing\"},{\"slug\":\"view_board_star\"},{\"slug\":\"view_board_star\"},{\"slug\":\"view_user\"},{\"slug\":\"view_user\"},{\"slug\":\"view_workflow_templates\"},{\"slug\":\"view_workflow_templates\"},{\"slug\":\"view_board_visibility\"},{\"slug\":\"view_board_visibility\"},{\"slug\":\"view_my_boards\"},{\"slug\":\"view_my_boards\"},{\"slug\":\"view_closed_boards\"},{\"slug\":\"view_closed_boards\"},{\"slug\":\"view_connected_applications\"},{\"slug\":\"view_connected_applications\"},{\"slug\":\"view_organization_visibility\"},{\"slug\":\"view_organization_visibility\"},{\"slug\":\"view_user_activities\"},{\"slug\":\"view_user_activities\"},{\"slug\":\"view_user_board\"},{\"slug\":\"view_user_board\"},{\"slug\":\"view_user_cards\"},{\"slug\":\"view_user_cards\"},{\"slug\":\"view_user_search\"},{\"slug\":\"view_user_search\"},{\"slug\":\"view_stared_boards\"},{\"slug\":\"view_stared_boards\"},{\"slug\":\"user_changepassword\"},{\"slug\":\"user_changepassword\"},{\"slug\":\"delete_webhook\"},{\"slug\":\"delete_webhook\"},{\"slug\":\"undo_activity\"},{\"slug\":\"undo_activity\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"role_add\"},{\"slug\":\"role_add\"},{\"slug\":\"board_user_role_add\"},{\"slug\":\"board_user_role_add\"},{\"slug\":\"organization_user_role_add\"},{\"slug\":\"organization_user_role_add\"},{\"slug\":\"role_edit\"},{\"slug\":\"role_edit\"},{\"slug\":\"board_user_role_edit\"},{\"slug\":\"board_user_role_edit\"},{\"slug\":\"organization_user_role_edit\"},{\"slug\":\"organization_user_role_edit\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"comment_card\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_board\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_list\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"subscribe_card\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"xmpp_login\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"chat_history\"},{\"slug\":\"role_add\"},{\"slug\":\"role_add\"},{\"slug\":\"role_add\"},{\"slug\":\"role_add\"},{\"slug\":\"board_user_role_add\"},{\"slug\":\"board_user_role_add\"},{\"slug\":\"board_user_role_add\"},{\"slug\":\"board_user_role_add\"},{\"slug\":\"organization_user_role_add\"},{\"slug\":\"organization_user_role_add\"},{\"slug\":\"organization_user_role_add\"},{\"slug\":\"organization_user_role_add\"},{\"slug\":\"role_edit\"},{\"slug\":\"role_edit\"},{\"slug\":\"role_edit\"},{\"slug\":\"role_edit\"},{\"slug\":\"board_user_role_edit\"},{\"slug\":\"board_user_role_edit\"},{\"slug\":\"board_user_role_edit\"},{\"slug\":\"board_user_role_edit\"},{\"slug\":\"organization_user_role_edit\"},{\"slug\":\"organization_user_role_edit\"},{\"slug\":\"organization_user_role_edit\"},{\"slug\":\"organization_user_role_edit\"}]","error":"invalid_scope","error_description":"An unsupported scope was requested","user":{"id":"1","role_id":"1","username":"admin","email":"board@restya.com","full_name":"New Admin","initials":"PA","about_me":"Added About Me","profile_picture_path":"media\/User\/1\/default-admin-user.png","notification_frequency":null,"is_allow_desktop_notification":"0","is_active":"1","is_email_confirmed":"1","created_organization_count":"0","created_board_count":"0","joined_organization_count":"0","list_count":"0","joined_card_count":"0","created_card_count":"0","joined_board_count":"0","checklist_count":"0","checklist_item_completed_count":"0","checklist_item_count":"0","activity_count":"0","card_voter_count":"0","is_productivity_beats":"1","organizations":null,"last_activity_id":"2","boards_stars":null,"boards_users":null,"last_login_date":"2016-11-17 18:30:48.745574","last_login_ip":"10.105.3.11","login_city_name":null,"login_state_name":null,"login_country_name":null,"login_country_iso2":null,"registered_ip":null,"register_city_name":null,"register_state_name":null,"register_country_name":null,"register_country_iso2":null,"login_type":"Normal","created":"2014-06-03T12:40:41","user_login_count":"23","is_send_newsletter":"0","last_email_notified_activity_id":"0","owner_board_count":"0","member_board_count":"0","owner_organization_count":"0","member_organization_count":"0","language":null,"is_ldap":"0","timezone":null,"notify_count":"0"}}`

**Comment by lmarikannan** [comment]
@corganhejijun  Can you please run the below queries?

`ALTER DATABASE restyaboard OWNER TO restya;`
`GRANT ALL PRIVILEGES ON DATABASE restyaboard TO restya;`
`GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO restya;`
`GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO restya;`

**Comment by lmarikannan** [comment]
@corganhejijun Can you please run the below queries?

`DELETE FROM oauth_scopes;`
`INSERT INTO "oauth_scopes" ("scope", "is_default") VALUES ('read', 't');`
`INSERT INTO "oauth_scopes" ("scope", "is_default") VALUES ('write', 'f');`

**Comment by lmarikannan** [comment]
@corganhejijun Please feel free to reopen if you are still having this issue?
