### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by kirtangajjar** [RestyaPlatform/board#943]
cc @ssivachidambaram  @sridhar391

From the graphs tab it looks like development activity of this project isn't as active as it used to be. Is this project still alive?

**Comment by lmarikannan** [comment]
@kirtangajjar Yes. We are working in `dev` branch, please refer https://github.com/RestyaPlatform/board/commits/dev but graphs tab showing `master` branch stats only.

**Comment by kirtangajjar** [comment]
@lmarikannan Thanks
