### ISSUE TITLE
[Bug] Instant add icon should not be visible if user does not have the right to add card

### ISSUE THREAD

**Issue by kirtangajjar** [RestyaPlatform/board#944]
Instant add icon is available to user even though the permission to do so has not been granted from backend.

The user cannot add card in the database, however, the icon on frontend should be there.

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/3ad042dd0ff36df1ba16b63563af455bf6cc85b7
