### ISSUE TITLE
[Bug] Push /board link to browser history for consistent navigation

### ISSUE THREAD

**Issue by kirtangajjar** [RestyaPlatform/board#945]
Currently, it is not being pushed for some reason.

**Comment by lmarikannan** [comment]
@kirtangajjar Is this possible to provide video/image to reproduce this issue?

**Comment by kirtangajjar** [comment]
@lmarikannan To reproduce this issue,

1.  Login as admin and go to any page
2.  Then you got to home page(`/boards`) 
3.  Goto another page
4.  Click on back button of browser
 
You will see that the you will be redirected directly to page opened on step-1 instead of redirecting on `/board`.

Sorry I do not have any picture or video for this image and my restyaboard instance is not running for some reason. I have written the above steps purely based on my memory, so if you are unable to reproduce it, ping me back. I'll see if I can do anything about it :smiley:

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/3ad042dd0ff36df1ba16b63563af455bf6cc85b7
