### ISSUE TITLE
 Auth	HTTP/1.1 502 Bad Gateway

### ISSUE THREAD

**Issue by jaiBITS** [RestyaPlatform/board#95]
![error](https://cloud.githubusercontent.com/assets/10440699/10892190/154bb37e-81c8-11e5-893a-6c503822f544.png)

I installed and configured this according to documentation. I am getting this error. I have checked configuration files. Please let me know what can be reason for this.

**Comment by rrjanbiah** [comment]
@jaiBITS Probably the php-fpm isn't running? Also, can you check your nginx error log and post relevant error part?

**Comment by jaiBITS** [comment]
Hi, 

Yes, there was some issue with php-fpm and that is resolved. Now PHP is working fine. But still i 500 internal error on page http://127.0.0.1/api/v1/oauth.json?_=1446540651021. 
I am not able to find api log file anywhere can you  please help me with that?


2015/11/05 00:48:39 [error] 31520#0: *27 open() "/usr/share/nginx/html/client/api-docs" failed (2: No such file or directory), client: 127.0.0.1, server: 127.0.0.1, request: "GET /api-docs HTTP/1.1", host: "127.0.0.1"

**Comment by jaiBITS** [comment]
I am getting this error and page gives 404 not found error.

PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  permission denied for relation oauth_clients' in /usr/share/nginx/html/server/php/R/libs/vendors/OAuth2/Storage/Pdo.php:96
Stack trace:
#0 /usr/share/nginx/html/server/php/R/libs/vendors/OAuth2/Storage/Pdo.php(96): PDOStatement->execute(Array)
#1 /usr/share/nginx/html/server/php/R/libs/vendors/OAuth2/Storage/Pdo.php(115): OAuth2\Storage\Pdo->getClientDetails('774263250138231...')
#2 /usr/share/nginx/html/server/php/R/libs/vendors/OAuth2/Controller/TokenController.php(142): OAuth2\Storage\Pdo->checkRestrictedGrantType('774263250138231...', 'client_credenti...')
#3 /usr/share/nginx/html/server/php/R/libs/vendors/OAuth2/Controller/TokenController.php(49): OAuth2\Controller\TokenController->grantAccessToken(Object(OAuth2\Request), Object(OAuth2\Response))
#4 /usr/share/nginx/html/server/php/R/libs/vendors/OAuth2/Server.php(256): OAuth2\Controller\TokenController->handleTokenRequest" while reading response header from upstream, client: 127.0.0.1, server: 127.0.0.1, request: "POST /server/php/R/token.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1"
2015/11/05 03:26:19 [error] 7681#0: *3 FastCGI sent in stderr: "PHP message: PHP Warning:  pg_query_params(): Query failed: ERROR:  permission denied for relation settings in /usr/share/nginx/html/server/php/R/config.inc.php on line 42
PHP message: PHP Warning:  pg_fetch_assoc() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/server/php/R/config.inc.php on line 43

**Comment by rrjanbiah** [comment]
@jaiBITS This looks like a database permission issue. Can you please check if the postgres user has necessary permission to access all DB tables?

Alternatively, you can use our latest install script https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh 

v0.1.5 will be pushed by this week. So, for the time being, you may change it to v0.1.4 in https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh#L10 and can try

**Comment by jaiBITS** [comment]
Hi, 
I used your latest script and it was configured successfully. I am still getting  404 not found error. 
I have attached recent error log.

2015/11/06 02:21:07 [error] 1866#0: *42 FastCGI sent in stderr: "PHP message: PHP Warning:  pg_last_error() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/server/php/R/config.inc.php on line 40
PHP message: PHP Warning:  pg_query_params() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/server/php/R/config.inc.php on line 42
PHP message: PHP Warning:  pg_fetch_assoc() expects parameter 1 to be resource, null given in /usr/share/nginx/html/server/php/R/config.inc.php on line 43" while reading response header from upstream, client: 127.0.0.1, server: 127.0.0.1, request: "GET /api/v1/settings.json HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1"

**Comment by rrjanbiah** [comment]
@jaiBITS This is clearly a DB connection failure. Is it possible for you to check DB credentials and use correct credentials?

**Comment by rrjanbiah** [comment]
@jaiBITS Were you able to resolve this?

**Comment by rrjanbiah** [comment]
@jaiBITS Closing this now. If you're still facing this issue, please feel free to reopen with more info
