### ISSUE TITLE
Installation fails on CentOS 6

### ISSUE THREAD

**Issue by miniminime** [RestyaPlatform/board#951]
Hi,

The installation fails on CentOS 6 during the PostgresSQL installation step. I have the installation log attached.

Best regards,
Minime
[restyaboard_install (copy).txt](https://github.com/RestyaPlatform/board/files/629011/restyaboard_install.copy.txt)

**Comment by miniminime** [comment]
`http://yum.postgresql.org/9.4/redhat/rhel-6.6-x86_64/pgdg-centos94-9.4-1.noarch.rpm`
doesn't exist, it should read in the installation script
`http://yum.postgresql.org/9.4/redhat/rhel-6.6-x86_64/pgdg-centos94-9.4-3.noarch.rpm`

**Comment by miniminime** [comment]
After that, the installation script runs into the next issue:

> + mkdir -v /usr/share/GeoIP
> mkdir: cannot create directory `/usr/share/GeoIP': File exists
> + '[' 1 '!=' 0 ']'
> + echo 'GeoIP folder creation failed with error code 48'
> GeoIP folder creation failed with error code 48
> + exit 1

Remove the folder and run the script again
`rm -r /usr/share/GeoIP`

[restyaboard_install (copy).txt](https://github.com/RestyaPlatform/board/files/629016/restyaboard_install.copy.txt)

**Comment by miniminime** [comment]
After that the script fails in the "ejabbered" step:

> mv: cannot stat `/usr/share/nginx/html/ejabberd.yml': No such file or directory
> chmod: cannot access `/etc/ejabberd/ejabberd.yml': No such file or directory
> sed: can't read /etc/ejabberd/ejabberd.yml: No such file or directory
> sed: can't read /etc/ejabberd/ejabberd.yml: No such file or directory
> restyaboard.sh: line 327: ejabberdctl: command not found

Now, I am a bit frustrated and I don't know how to fix this. Could you please help to fix the installation script?
[restyaboard_install (copy).txt](https://github.com/RestyaPlatform/board/files/629020/restyaboard_install.copy.txt)

**Comment by lmarikannan** [comment]
@miniminime Sorry about the delay. We have fixed this in our `dev` branch in this commit https://github.com/RestyaPlatform/board/commit/18dd4b9d04916a7706e7677af4b2a9295752dcd8.

**Comment by miniminime** [comment]
Hi, just tested with a fresh installation without success. Please see attached log.

[restyaboard_install_copy.txt](https://github.com/RestyaPlatform/board/files/646627/restyaboard_install_copy.txt)

**Comment by lmarikannan** [comment]
@miniminime Checked your install log and it looks,

`restyaboard.sh: line 18: lsb_release: command not found`
`restyaboard.sh: line 19: lsb_release: command not found`

So script could not able to find the OS & version. Need to add `exit` code in the script if not able to find the OS and version.

**Comment by miniminime** [comment]
I think, this is not the only problem. Have a look at the end of the file:

`+ rpm -Uvh http://yum.postgresql.org/9.5/redhat/rhel--x86_64/pgdg-centos95-9.5-3.noarch.rpm
curl: (22) The requested URL returned error: 404 Not Found
error: skipping http://yum.postgresql.org/9.5/redhat/rhel--x86_64/pgdg-centos95-9.5-3.noarch.rpm - transfer failed
Retrieving http://yum.postgresql.org/9.5/redhat/rhel--x86_64/pgdg-centos95-9.5-3.noarch.rpm
+ yum install -y postgresql95-server postgresql95
Loaded plugins: fastestmirror, refresh-packagekit, security
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.spreitzer.ch
 * epel: fedora-mirror01.rbc.ru
 * extras: mirror.spreitzer.ch
 * updates: mirror.spreitzer.ch
No package postgresql95-server available.
No package postgresql95 available.
Error: Nothing to do
+ '[' 1 '!=' 0 ']'
+ echo 'Installing PostgreSQL 64 fail with error code 28'
Installing PostgreSQL 64 fail with error code 28
+ exit 1`

**Comment by lmarikannan** [comment]
@miniminime Yes. We have checked and actually script will dynamically replace the OS & version to download the respective PostgreSQL software. So in your case it replace with empty string and the software not downloaded. Please refer https://github.com/RestyaPlatform/board/blob/dev/restyaboard.sh#L862.

**Comment by miniminime** [comment]
Ok, but this means that the script doesn't work as expected as I have used standard CentOS 6 and it didn't find a package. To be more precise, it didn't find the packages:

No package postgresql95-server available.
No package postgresql95 available.

Correct?

**Comment by lmarikannan** [comment]
@miniminime 

Yes. But URL not replaced properly. From your log,

> Retrieving http://yum.postgresql.org/9.5/redhat/rhel--x86_64/pgdg-centos95-9.5-3.noarch.rpm

Original URL: https://yum.postgresql.org/9.5/redhat/rhel-6.6-x86_64/pgdg-centos95-9.5-3.noarch.rpm
