### ISSUE TITLE
LDAP problem

### ISSUE THREAD

**Issue by Polycris** [RestyaPlatform/board#952]
Hi! I can't login with ldap...  There are two files r.php. When I run with the [r_creatXmmpuser_error.php.txt] file, I can't login.  When I run with the file [r.php.txt], I login with admin, but I can't login with ldap users.
The parameters of LDAP are corrects. What can I do?

[r_creatXmmpuser_error.php.txt]
(https://github.com/RestyaPlatform/board/files/631608/r_creatXmmpuser_error.php.txt)
[r.php.txt](https://github.com/RestyaPlatform/board/files/631609/r.php.txt)

2016/12/05 12:15:30 [error] 10987#10987: *9038 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function createXmppUser() in /usr/share/nginx/html/restyaboard/server/php/R/r.php:1901
Stack trace:
#0 /usr/share/nginx/html/restyaboard/server/php/R/r.php(5314): r_post('/users/login', Array, Array, Array)
#1 {main}
  thrown in /usr/share/nginx/html/restyaboard/server/php/R/r.php on line 1901" while reading response header from upstream, client: 10.74.0.89, server: _, request: "POST /api/v1/users/login.json?token=998dd75294c46c595fc9ae1b9d52ebb66fcc5d86 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "10.120.27.225", referrer: "http://10.120.27.225/"

Thanks
Poly

**Comment by lmarikannan** [comment]
@Polycris Sorry about the delay. It looks like you are using `dev` branch version but you have not updated the files properly. can you please update this function https://github.com/RestyaPlatform/board/blob/dev/server/php/libs/core.php#L1536?
