### ISSUE TITLE
Can't change app status to enabled/disabled

### ISSUE THREAD

**Issue by frapporti** [RestyaPlatform/board#953]
New installation via Amazon AMI.
Apps can not be enabled/disabled.

Steps to reproduce:
- launch a new instance using Restyaboard AMI;
- `wget` a new app into `client/apps` folder;
- unzip;
- go to admin settings and try enable/disable the app.

No apparent error (but I should specify I'm new).

Response from server:
`[{"name":"Theming\/CSSilize","description":"CSSilize, theming partner","author":"Restya","author_email":"info@restya.com","author_url":"http:\/\/restya.com\/","version":"0.1.1","price":0,"icon":"apps\/r_cssilize\/img\/cssilize.png","settings_description":"","settings":false,"assets":{"css":[],"js":["apps\/r_cssilize\/js\/app.js"]},"enabled":true,"folder":"r_cssilize"}]`

After enabling debug I get this error:
```
"<br />
<b>Warning</b>:  fopen(/usr/share/nginx/html/client/apps/r_cssilize/app.json): failed to open stream: Permission denied in <b>/usr/share/nginx/html/server/php/R/r.php</b> on line <b>2440</b><br />
<br />
<b>Warning</b>:  fwrite() expects parameter 1 to be resource, boolean given in <b>/usr/share/nginx/html/server/php/R/r.php</b> on line <b>2441</b><br />
<br />
<b>Warning</b>:  fclose() expects parameter 1 to be resource, boolean given in <b>/usr/share/nginx/html/server/php/R/r.php</b> on line <b>2442</b><br />
{\"success\":\"App updated successfully\"}"
```
Which triggers a parse error in the js.

**Comment by lmarikannan** [comment]
@frapporti Sorry about the delay. Can you please give write permission to `client/apps` folder?
