### ISSUE TITLE
Installation failed @nginx

### ISSUE THREAD

**Issue by drumpalisti** [RestyaPlatform/board#955]
This script must be run as root
./restyaboard.sh: 30: ./restyaboard.sh: [[: not found
+ whoami
root
+ cat /etc/issue
+ echo Debian GNU/Linux 8 \n \l
Debian GNU/Linux 8 
 \l
+ cat /proc/version
+ grep Ubuntu\|Debian\|Raspbian
+ sed s/^.*Ubuntu.*$/Ubuntu/g
+ sed s/^.*Debian.*$/Debian/g
+ sed+  s/^.*Debian.*$/Debian/g
sed s/^.*Raspbian.*$/Raspbian/g
+ OS_REQUIREMENT=Debian
+ [ Debian = Ubuntu ]
+ [ Debian = Debian ]
+ apt-get install -y curl unzip
Luetaan pakettiluetteloita...
Muodostetaan riippuvuussuhteiden puu...
Luetaan tilatiedot...
unzip on jo uusin versio.
curl on jo uusin versio.
0 päivitetty, 0 uutta asennusta, 0 poistettavaa ja 0 päivittämätöntä.
+ curl --silent https://api.github.com/repos/RestyaPlatform/board/releases
+ + awkgrep {print $2} tag_name
 -m 1
+ sed -e s/[^v0-9.]//g
+ RESTYABOARD_VERSION=v0.3
+ POSTGRES_DBHOST=localhost
+ POSTGRES_DBNAME=restyaboard
+ POSTGRES_DBUSER=restya
+ POSTGRES_DBPASS=hjVl2!rGd
+ POSTGRES_DBPORT=5432
+ EJABBERD_DBHOST=localhost
+ EJABBERD_DBNAME=ejabberd
+ EJABBERD_DBUSER=ejabb
+ EJABBERD_DBPASS=ftfnVgYl2
+ EJABBERD_DBPORT=5432
+ DOWNLOAD_DIR=/opt/restyaboard
+ [ -d /opt/restyaboard ]
+ set +x
Is Restyaboard already installed y/n?
+ [ Debian = Ubuntu ]
+ [ Debian = Debian ]
+ set +x
Setup script will install version v0.3 and create database restyaboard with user restya and password hjVl2!rGd. To continue enter "y" or to quit the process and edit the version and database details enter "n" (y/n)?
+ echo deb http://mirrors.linode.com/debian/ wheezy main contrib non-free
+ echo deb-src http://mirrors.linode.com/debian/ wheezy main contrib non-free
+ echo deb http://mirrors.linode.com/debian-security/ wheezy/updates main contrib non-free
+ echo deb-src http://mirrors.linode.com/debian-security/ wheezy/updates main contrib non-free
+ echo deb http://mirrors.linode.com/debian/ wheezy-updates main
+ echo deb-src http://mirrors.linode.com/debian/ wheezy-updates main
+ sed -i -e s/deb cdrom/#deb cdrom/g /etc/apt/sources.list
+ apt-key update
gpg: key B98321F9: "Squeeze Stable Release Key <debian-release@lists.debian.org>" not changed
gpg: key 473041FA: "Debian Archive Automatic Signing Key (6.0/squeeze) <ftpmaster@debian.org>" not changed
gpg: key 65FFB764: "Wheezy Stable Release Key <debian-release@lists.debian.org>" not changed
gpg: key 46925553: "Debian Archive Automatic Signing Key (7.0/wheezy) <ftpmaster@debian.org>" not changed
gpg: key 518E17E1: "Jessie Stable Release Key <debian-release@lists.debian.org>" not changed
gpg: key 2B90D010: "Debian Archive Automatic Signing Key (8/jessie) <ftpmaster@debian.org>" not changed
gpg: key C857C906: "Debian Security Archive Automatic Signing Key (8/jessie) <ftpmaster@debian.org>" not changed
gpg: Kaikkiaan käsitelty: 7
gpg:              muuttamatonta: 7
+ apt-get update
Siv http://dl.google.com stable InRelease
Löytyi http://dl.google.com stable Release.gpg
Löytyi http://dl.google.com stable Release
Löytyi https://repo.skype.com stable InRelease
Löytyi http://dl.google.com stable/main amd64 Packages
Löytyi https://repo.skype.com stable/main amd64 Packages
Nouda:1 http://security.debian.org jessie/updates InRelease [63,1 kB]
Nouda:2 https://repo.skype.com stable/main Translation-fi_FI [246 B]
Löytyi http://pkg.bunsenlabs.org bunsen-hydrogen InRelease
Nouda:3 https://repo.skype.com stable/main Translation-fi [243 B]
Siv http://httpredir.debian.org jessie InRelease
Löytyi http://httpredir.debian.org jessie-updates InRelease
Siv http://mirrors.linode.com wheezy InRelease
Nouda:4 https://repo.skype.com stable/main Translation-en [243 B]
Löytyi http://httpredir.debian.org jessie-backports InRelease
Löytyi http://pkg.bunsenlabs.org bunsen-hydrogen/main amd64 Packages
Siv http://dl.google.com stable/main Translation-fi_FI
Löytyi http://pkg.bunsenlabs.org bunsen-hydrogen/main i386 Packages
Siv http://dl.google.com stable/main Translation-fi
Nouda:5 https://repo.skype.com stable/main Translation-fi_FI [246 B]
Siv http://dl.google.com stable/main Translation-en
Nouda:6 http://mirrors.linode.com wheezy/updates InRelease [40,6 kB]
Löytyi http://httpredir.debian.org jessie Release.gpg
Nouda:7 https://repo.skype.com stable/main Translation-fi [243 B]
Nouda:8 http://httpredir.debian.org jessie-updates/main amd64 Packages/DiffIndex [6 916 B]
Nouda:9 https://repo.skype.com stable/main Translation-en [243 B]
Nouda:10 https://repo.skype.com stable/main Translation-fi_FI [246 B]
Löytyi http://httpredir.debian.org jessie-updates/contrib amd64 Packages
Nouda:11 http://security.debian.org jessie/updates/main amd64 Packages [333 kB]
Nouda:12 https://repo.skype.com stable/main Translation-fi [243 B]
Nouda:13 http://mirrors.linode.com wheezy-updates InRelease [157 kB]
Nouda:14 http://httpredir.debian.org jessie-updates/non-free amd64 Packages/DiffIndex [736 B]
Nouda:15 https://repo.skype.com stable/main Translation-en [243 B]
Siv http://pkg.bunsenlabs.org bunsen-hydrogen/main Translation-fi_FI
Nouda:16 http://httpredir.debian.org jessie-updates/main i386 Packages/DiffIndex [6 916 B]
Siv http://pkg.bunsenlabs.org bunsen-hydrogen/main Translation-fi
Siv http://pkg.bunsenlabs.org bunsen-hydrogen/main Translation-en
Nouda:17 https://repo.skype.com stable/main Translation-fi_FI [246 B]
Nouda:18 http://security.debian.org jessie/updates/contrib amd64 Packages [2 506 B]
Löytyi http://httpredir.debian.org jessie-updates/contrib i386 Packages
Nouda:19 http://security.debian.org jessie/updates/non-free amd64 Packages [14 B]
Nouda:20 https://repo.skype.com stable/main Translation-fi [243 B]
Nouda:21 http://mirrors.linode.com wheezy Release.gpg [2 373 B]
Nouda:22 http://httpredir.debian.org jessie-updates/non-free i386 Packages/DiffIndex [736 B]
Nouda:23 http://security.debian.org jessie/updates/main i386 Packages [334 kB]
Nouda:24 https://repo.skype.com stable/main Translation-en [243 B]
Löytyi http://httpredir.debian.org jessie-updates/contrib Translation-en
Nouda:25 http://security.debian.org jessie/updates/contrib i386 Packages [2 526 B]
Nouda:26 http://mirrors.linode.com wheezy/updates/main Sources [300 kB]
Nouda:27 https://repo.skype.com stable/main Translation-fi_FI [246 B]
Siv https://repo.skype.com stable/main Translation-fi_FI
Nouda:28 http://security.debian.org jessie/updates/non-free i386 Packages [14 B]
Nouda:29 http://httpredir.debian.org jessie-updates/main Translation-en/DiffIndex [2 704 B]
Nouda:30 https://repo.skype.com stable/main Translation-fi [243 B]
Siv https://repo.skype.com stable/main Translation-fi
Nouda:31 http://security.debian.org jessie/updates/contrib Translation-en [1 211 B]
Nouda:32 http://httpredir.debian.org jessie-updates/non-free Translation-en/DiffIndex [736 B]
Nouda:33 https://repo.skype.com stable/main Translation-en [243 B]
Siv https://repo.skype.com stable/main Translation-en
Nouda:34 http://security.debian.org jessie/updates/main Translation-en [176 kB]
Nouda:35 http://security.debian.org jessie/updates/non-free Translation-en [14 B]
Nouda:36 http://mirrors.linode.com wheezy/updates/contrib Sources [14 B]
Nouda:37 http://httpredir.debian.org jessie-backports/main amd64 Packages/DiffIndex [27,8 kB]
Nouda:38 http://httpredir.debian.org jessie-backports/contrib amd64 Packages/DiffIndex [20,8 kB]
Nouda:39 http://mirrors.linode.com wheezy/updates/non-free Sources [14 B]
Nouda:40 http://httpredir.debian.org jessie-backports/non-free amd64 Packages/DiffIndex [15,5 kB]
Nouda:41 http://mirrors.linode.com wheezy/updates/main amd64 Packages [456 kB]
Nouda:42 http://httpredir.debian.org jessie-backports/main i386 Packages/DiffIndex [27,8 kB]
Nouda:43 http://httpredir.debian.org jessie-backports/contrib i386 Packages/DiffIndex [21,3 kB]
Nouda:44 http://mirrors.linode.com wheezy/updates/contrib amd64 Packages [14 B]
Nouda:45 http://httpredir.debian.org jessie-backports/non-free i386 Packages/DiffIndex [14,8 kB]
Nouda:46 http://mirrors.linode.com wheezy/updates/non-free amd64 Packages [14 B]
Nouda:47 http://httpredir.debian.org jessie-backports/contrib Translation-en/DiffIndex [6 484 B]
Nouda:48 http://mirrors.linode.com wheezy/updates/main i386 Packages [459 kB]
Nouda:49 http://mirrors.linode.com wheezy/updates/contrib i386 Packages [14 B]
Nouda:50 http://httpredir.debian.org jessie-backports/main Translation-en/DiffIndex [27,8 kB]
Nouda:51 http://httpredir.debian.org jessie-backports/non-free Translation-en/DiffIndex [12,2 kB]
Nouda:52 http://mirrors.linode.com wheezy/updates/non-free i386 Packages [14 B]
Löytyi http://httpredir.debian.org jessie Release
Nouda:53 http://mirrors.linode.com wheezy/updates/contrib Translation-en [14 B]
Löytyi http://httpredir.debian.org jessie/main amd64 Packages
Löytyi http://httpredir.debian.org jessie/non-free amd64 Packages
Nouda:54 http://mirrors.linode.com wheezy/updates/main Translation-en [250 kB]
Löytyi http://httpredir.debian.org jessie/contrib amd64 Packages
Nouda:55 http://mirrors.linode.com wheezy/updates/non-free Translation-en [14 B]
Löytyi http://httpredir.debian.org jessie/main i386 Packages
Löytyi http://httpredir.debian.org jessie/non-free i386 Packages
Nouda:56 http://mirrors.linode.com wheezy-updates/main Sources [5 505 B]
Löytyi http://httpredir.debian.org jessie/contrib i386 Packages
Nouda:57 http://mirrors.linode.com wheezy-updates/main amd64 Packages [7 047 B]
Löytyi http://httpredir.debian.org jessie/contrib Translation-en
Nouda:58 http://mirrors.linode.com wheezy-updates/main i386 Packages [7 051 B]
Löytyi http://httpredir.debian.org jessie/main Translation-fi
Löytyi http://httpredir.debian.org jessie/main Translation-en
Nouda:59 http://mirrors.linode.com wheezy-updates/main Translation-en [4 879 B]
Löytyi http://httpredir.debian.org jessie/non-free Translation-en
Nouda:60 http://mirrors.linode.com wheezy Release [191 kB]
Nouda:61 http://mirrors.linode.com wheezy/main Sources [5 993 kB]
Nouda:62 http://mirrors.linode.com wheezy/contrib Sources [47,7 kB]
Nouda:63 http://mirrors.linode.com wheezy/non-free Sources [93,4 kB]
Nouda:64 http://mirrors.linode.com wheezy/main amd64 Packages [5 839 kB]
Nouda:65 http://mirrors.linode.com wheezy/contrib amd64 Packages [42,0 kB]
Nouda:66 http://mirrors.linode.com wheezy/non-free amd64 Packages [80,8 kB]
Nouda:67 http://mirrors.linode.com wheezy/main i386 Packages [5 857 kB]
Nouda:68 http://mirrors.linode.com wheezy/contrib i386 Packages [42,3 kB]
Nouda:69 http://mirrors.linode.com wheezy/non-free i386 Packages [77,6 kB]
Nouda:70 http://mirrors.linode.com wheezy/contrib Translation-en [34,8 kB]
Nouda:71 http://mirrors.linode.com wheezy/main Translation-fi [107 kB]
Nouda:72 http://mirrors.linode.com wheezy/main Translation-en [3 846 kB]
Nouda:73 http://mirrors.linode.com wheezy/non-free Translation-en [66,1 kB]
Noudettiin 25,1 Mt ajassa 10s (2 446 kt/s)
Luetaan pakettiluetteloita...
+ apt-get install debian-keyring debian-archive-keyring
Luetaan pakettiluetteloita...
Muodostetaan riippuvuussuhteiden puu...
Luetaan tilatiedot...
debian-archive-keyring on jo uusin versio.
Seuraavat UUDET paketit asennetaan:
  debian-keyring
0 päivitetty, 1 uutta asennusta, 0 poistettavaa ja 1 päivittämätöntä.
Noudettavaa arkistoa 52,4 Mt.
Toiminnon jälkeen käytetään 58,0 M t lisää levytilaa.
Haluatko jatkaa? [K/e] Nouda:1 http://httpredir.debian.org/debian/ jessie/main debian-keyring all 2015.04.10 [52,4 MB]
Noudettiin 52,4 Mt ajassa 5s (10,5 Mt/s)
Selecting previously unselected package debian-keyring.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 190224 files and directories currently installed.)
Preparing to unpack .../debian-keyring_2015.04.10_all.deb ...
Unpacking debian-keyring (2015.04.10) ...
Setting up debian-keyring (2015.04.10) ...
+ [ 0 != 0 ]
+ apt-get update -y
Siv http://dl.google.com stable InRelease
Löytyi http://dl.google.com stable Release.gpg
Löytyi http://dl.google.com stable Release
Löytyi http://dl.google.com stable/main amd64 Packages
Löytyi http://security.debian.org jessie/updates InRelease
Löytyi https://repo.skype.com stable InRelease
Löytyi http://pkg.bunsenlabs.org bunsen-hydrogen InRelease
Löytyi https://repo.skype.com stable/main amd64 Packages
Löytyi http://security.debian.org jessie/updates/main amd64 Packages
Siv http://httpredir.debian.org jessie InRelease
Löytyi http://pkg.bunsenlabs.org bunsen-hydrogen/main amd64 Packages
Siv http://mirrors.linode.com wheezy InRelease
Löytyi http://pkg.bunsenlabs.org bunsen-hydrogen/main i386 Packages
Löytyi http://security.debian.org jessie/updates/contrib amd64 Packages
Löytyi http://httpredir.debian.org jessie-updates InRelease
Nouda:1 https://repo.skype.com stable/main Translation-fi_FI [246 B]
Löytyi http://security.debian.org jessie/updates/non-free amd64 Packages
Löytyi http://mirrors.linode.com wheezy/updates InRelease
Nouda:2 https://repo.skype.com stable/main Translation-fi [243 B]
Löytyi http://httpredir.debian.org jessie-backports InRelease
Löytyi http://security.debian.org jessie/updates/main i386 Packages
Siv http://dl.google.com stable/main Translation-fi_FI
Nouda:3 https://repo.skype.com stable/main Translation-en [243 B]
Siv http://dl.google.com stable/main Translation-fi
Siv http://dl.google.com stable/main Translation-en
Löytyi http://security.debian.org jessie/updates/contrib i386 Packages
Löytyi http://mirrors.linode.com wheezy-updates InRelease
Löytyi http://httpredir.debian.org jessie Release.gpg
Nouda:4 https://repo.skype.com stable/main Translation-fi_FI [246 B]
Löytyi http://security.debian.org jessie/updates/non-free i386 Packages
Nouda:5 https://repo.skype.com stable/main Translation-fi [243 B]
Nouda:6 http://httpredir.debian.org jessie-updates/main amd64 Packages/DiffIndex [6 916 B]
Löytyi http://mirrors.linode.com wheezy Release.gpg
Löytyi http://security.debian.org jessie/updates/contrib Translation-en
Nouda:7 https://repo.skype.com stable/main Translation-en [243 B]
Löytyi http://security.debian.org jessie/updates/main Translation-en
Löytyi http://httpredir.debian.org jessie-updates/contrib amd64 Packages
Siv http://pkg.bunsenlabs.org bunsen-hydrogen/main Translation-fi_FI
Nouda:8 https://repo.skype.com stable/main Translation-fi_FI [246 B]
Löytyi http://mirrors.linode.com wheezy/updates/main Sources
Löytyi http://security.debian.org jessie/updates/non-free Translation-en
Siv http://pkg.bunsenlabs.org bunsen-hydrogen/main Translation-fi
Siv http://pkg.bunsenlabs.org bunsen-hydrogen/main Translation-en
Nouda:9 https://repo.skype.com stable/main Translation-fi [243 B]
Nouda:10 http://httpredir.debian.org jessie-updates/non-free amd64 Packages/DiffIndex [736 B]
Nouda:11 https://repo.skype.com stable/main Translation-en [243 B]
Löytyi http://mirrors.linode.com wheezy/updates/contrib Sources
Nouda:12 http://httpredir.debian.org jessie-updates/main i386 Packages/DiffIndex [6 916 B]
Nouda:13 https://repo.skype.com stable/main Translation-fi_FI [246 B]
Löytyi http://mirrors.linode.com wheezy/updates/non-free Sources
Nouda:14 https://repo.skype.com stable/main Translation-fi [243 B]
Löytyi http://httpredir.debian.org jessie-updates/contrib i386 Packages
Nouda:15 https://repo.skype.com stable/main Translation-en [243 B]
Nouda:16 http://httpredir.debian.org jessie-updates/non-free i386 Packages/DiffIndex [736 B]
Löytyi http://mirrors.linode.com wheezy/updates/main amd64 Packages
Nouda:17 https://repo.skype.com stable/main Translation-fi_FI [246 B]
Siv https://repo.skype.com stable/main Translation-fi_FI
Löytyi http://httpredir.debian.org jessie-updates/contrib Translation-en
Nouda:18 https://repo.skype.com stable/main Translation-fi [243 B]
Siv https://repo.skype.com stable/main Translation-fi
Löytyi http://mirrors.linode.com wheezy/updates/contrib amd64 Packages
Nouda:19 https://repo.skype.com stable/main Translation-en [243 B]
Siv https://repo.skype.com stable/main Translation-en
Nouda:20 http://httpredir.debian.org jessie-updates/main Translation-en/DiffIndex [2 704 B]
Löytyi http://mirrors.linode.com wheezy/updates/non-free amd64 Packages
Nouda:21 http://httpredir.debian.org jessie-updates/non-free Translation-en/DiffIndex [736 B]
Löytyi http://mirrors.linode.com wheezy/updates/main i386 Packages
Nouda:22 http://httpredir.debian.org jessie-backports/main amd64 Packages/DiffIndex [27,8 kB]
Löytyi http://mirrors.linode.com wheezy/updates/contrib i386 Packages
Nouda:23 http://httpredir.debian.org jessie-backports/contrib amd64 Packages/DiffIndex [20,8 kB]
Nouda:24 http://httpredir.debian.org jessie-backports/non-free amd64 Packages/DiffIndex [15,5 kB]
Löytyi http://mirrors.linode.com wheezy/updates/non-free i386 Packages
Nouda:25 http://httpredir.debian.org jessie-backports/main i386 Packages/DiffIndex [27,8 kB]
Löytyi http://mirrors.linode.com wheezy/updates/contrib Translation-en
Nouda:26 http://httpredir.debian.org jessie-backports/contrib i386 Packages/DiffIndex [21,3 kB]
Löytyi http://mirrors.linode.com wheezy/updates/main Translation-en
Nouda:27 http://httpredir.debian.org jessie-backports/non-free i386 Packages/DiffIndex [14,8 kB]
Nouda:28 http://httpredir.debian.org jessie-backports/contrib Translation-en/DiffIndex [6 484 B]
Löytyi http://mirrors.linode.com wheezy/updates/non-free Translation-en
Löytyi http://mirrors.linode.com wheezy-updates/main Sources
Nouda:29 http://mirrors.linode.com wheezy-updates/main amd64 Packages/DiffIndex [2 488 B]
Nouda:30 http://httpredir.debian.org jessie-backports/main Translation-en/DiffIndex [27,8 kB]
Nouda:31 http://httpredir.debian.org jessie-backports/non-free Translation-en/DiffIndex [12,2 kB]
Löytyi http://httpredir.debian.org jessie Release
Nouda:32 http://mirrors.linode.com wheezy-updates/main i386 Packages/DiffIndex [2 488 B]
Löytyi http://httpredir.debian.org jessie/main amd64 Packages
Löytyi http://httpredir.debian.org jessie/non-free amd64 Packages
Nouda:33 http://mirrors.linode.com wheezy-updates/main Translation-en/DiffIndex [736 B]
Löytyi http://httpredir.debian.org jessie/contrib amd64 Packages
Löytyi http://mirrors.linode.com wheezy Release
Löytyi http://httpredir.debian.org jessie/main i386 Packages
Löytyi http://mirrors.linode.com wheezy/main Sources
Löytyi http://httpredir.debian.org jessie/non-free i386 Packages
Löytyi http://mirrors.linode.com wheezy/contrib Sources
Löytyi http://httpredir.debian.org jessie/contrib i386 Packages
Löytyi http://mirrors.linode.com wheezy/non-free Sources
Löytyi http://httpredir.debian.org jessie/contrib Translation-en
Löytyi http://mirrors.linode.com wheezy/main amd64 Packages
Löytyi http://httpredir.debian.org jessie/main Translation-fi
Löytyi http://httpredir.debian.org jessie/main Translation-en
Löytyi http://mirrors.linode.com wheezy/contrib amd64 Packages
Löytyi http://httpredir.debian.org jessie/non-free Translation-en
Löytyi http://mirrors.linode.com wheezy/non-free amd64 Packages
Löytyi http://mirrors.linode.com wheezy/main i386 Packages
Löytyi http://mirrors.linode.com wheezy/contrib i386 Packages
Löytyi http://mirrors.linode.com wheezy/non-free i386 Packages
Löytyi http://mirrors.linode.com wheezy/contrib Translation-en
Löytyi http://mirrors.linode.com wheezy/main Translation-fi
Löytyi http://mirrors.linode.com wheezy/main Translation-en
Löytyi http://mirrors.linode.com wheezy/non-free Translation-en
Noudettiin 199 kt ajassa 5s (34,4 kt/s)
Luetaan pakettiluetteloita...
+ apt-get upgrade -y
Luetaan pakettiluetteloita...
Muodostetaan riippuvuussuhteiden puu...
Luetaan tilatiedot...
Nämä paketit päivitetään:
  libupnp6
1 päivitetty, 0 uutta asennusta, 0 poistettavaa ja 0 päivittämätöntä.
Noudettavaa arkistoa 163 kt.
Toiminnon jälkeen vapautuu 39,9 k t levytilaa.
Nouda:1 http://security.debian.org/ jessie/updates/main libupnp6 amd64 1:1.6.19+git20141001-1+deb8u1 [163 kB]
Noudettiin 163 kt ajassa 0s (210 kt/s)
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 190235 files and directories currently installed.)
Preparing to unpack .../libupnp6_1%3a1.6.19+git20141001-1+deb8u1_amd64.deb ...
Unpacking libupnp6 (1:1.6.19+git20141001-1+deb8u1) over (1:1.6.19+git20141001-1) ...
Setting up libupnp6 (1:1.6.19+git20141001-1+deb8u1) ...
Processing triggers for libc-bin (2.19-18+deb8u6) ...
+ echo Checking nginx...
Checking nginx...
+ which nginx
+ echo nginx not installed!
nginx not installed!
+ set +x
Do you want to install nginx (y/n)?
+ echo Installing nginx...
Installing nginx...
+ apt-get install -y cron nginx
Luetaan pakettiluetteloita...
Muodostetaan riippuvuussuhteiden puu...
Luetaan tilatiedot...
cron on jo uusin versio.
Seuraavat ylimääräiset paketit on merkitty asennettaviksi:
  nginx-common nginx-full
Ehdotetut paketit:
  fcgiwrap nginx-doc
Seuraavat UUDET paketit asennetaan:
  nginx nginx-common nginx-full
0 päivitetty, 3 uutta asennusta, 0 poistettavaa ja 0 päivittämätöntä.
Noudettavaa arkistoa 591 kt.
Toiminnon jälkeen käytetään 1 413 k t lisää levytilaa.
Nouda:1 http://security.debian.org/ jessie/updates/main nginx-common all 1.6.2-5+deb8u4 [88,1 kB]
Nouda:2 http://security.debian.org/ jessie/updates/main nginx-full amd64 1.6.2-5+deb8u4 [430 kB]
Nouda:3 http://security.debian.org/ jessie/updates/main nginx all 1.6.2-5+deb8u4 [72,6 kB]
Esiräätälöidään paketteja...
Noudettiin 591 kt ajassa 0s (857 kt/s)
Selecting previously unselected package nginx-common.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 190235 files and directories currently installed.)
Preparing to unpack .../nginx-common_1.6.2-5+deb8u4_all.deb ...
Unpacking nginx-common (1.6.2-5+deb8u4) ...
Selecting previously unselected package nginx-full.
Preparing to unpack .../nginx-full_1.6.2-5+deb8u4_amd64.deb ...
Unpacking nginx-full (1.6.2-5+deb8u4) ...
Selecting previously unselected package nginx.
Preparing to unpack .../nginx_1.6.2-5+deb8u4_all.deb ...
Unpacking nginx (1.6.2-5+deb8u4) ...
Processing triggers for systemd (215-17+deb8u5) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up nginx-common (1.6.2-5+deb8u4) ...
Setting up nginx-full (1.6.2-5+deb8u4) ...
Job for nginx.service failed. See 'systemctl status nginx.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript nginx, action "start" failed.
dpkg: error processing package nginx-full (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of nginx:
 nginx depends on nginx-full (>= 1.6.2-5+deb8u4) | nginx-light (>= 1.6.2-5+deb8u4) | nginx-extras (>= 1.6.2-5+deb8u4); however:
  Package nginx-full is not configured yet.
  Package nginx-light is not installed.
  Package nginx-extras is not installed.
 nginx depends on nginx-full (<< 1.6.2-5+deb8u4.1~) | nginx-light (<< 1.6.2-5+deb8u4.1~) | nginx-extras (<< 1.6.2-5+deb8u4.1~); however:
  Package nginx-full is not configured yet.
  Package nginx-light is not installed.
  Package nginx-extras is not installed.

dpkg: error processing package nginx (--configure):
 dependency problems - leaving unconfigured
Processing triggers for systemd (215-17+deb8u5) ...
Errors were encountered while processing:
 nginx-full
 nginx
E: Sub-process /usr/bin/dpkg returned an error code (1)
+ [ 100 != 0 ]
+ echo nginx installation failed with error code 2
nginx installation failed with error code 2
+ exit 1

**Comment by lmarikannan** [comment]
@drumpalisti Can you please try with our updated install script file https://github.com/RestyaPlatform/board/blob/dev/restyaboard.sh

**Comment by lmarikannan** [comment]
@drumpalisti  Please feel free to reopen if you got any issue in installation.
