### ISSUE TITLE
404 not found after login page redirects to /board

### ISSUE THREAD

**Issue by tonbar** [RestyaPlatform/board#958]
I am trying to get Restyaboard to work on an iMac using the deployable .zip. Everything seemed to be working fine, but after I log in using the default username and password, I get redirected to a page where a 404 not found error is displayed. I think that this is supposed to be the page where the boards are shown.

Looking in the nginx error log, I am receiving errors which appear the same as those raised in issue [#705](https://github.com/RestyaPlatform/board/issues/705#issuecomment-231329066), however, applying the fix mentioned there does not work for me and gives me errors in postgres as I do not have a settings relation set up.

I'm not familiar enough with web dev to know where to look for further troubleshooting so would really appreciate some advice to get this up and running.
Many thanks.

**Comment by tonbar** [comment]
Copying the error log contents here to provide more information:
2016/12/30 11:45:27 [error] 97603#0: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Constant BOSH_SERVICE_URL already defined in /usr/local/var/www/restyaboard/server/php/config.inc.php on line 62
PHP message: PHP Notice:  Constant JABBER_HOST already defined in /usr/local/var/www/restyaboard/server/php/config.inc.php on line 62
PHP message: PHP Notice:  Constant XMPP_CLIENT_RESOURCE_NAME already defined in /usr/local/var/www/restyaboard/server/php/config.inc.php on line 62
PHP message: PHP Notice:  Constant DEFAULT_CARD_VIEW already defined in /usr/local/var/www/restyaboard/server/php/config.inc.php on line 62
PHP message: PHP Warning:  Division by zero in /usr/local/var/www/restyaboard/server/php/R/r.php on line 1211" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /api/v1/boards.json?type=simple&token=f3e79c32b55e9f970fbdc2af1304f42cfe634f99&_=1483098326984 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"

**Comment by lmarikannan** [comment]
@tonbar 

Sorry for the trouble. Actually this error occur only in PHP 7. We have fixed this in our `dev` branch.

Need to change the below line in `r.php` line number 1211.

https://github.com/RestyaPlatform/board/blob/master/server/php/R/r.php#L1211

`$total_page = ceil($c_data->count / $page_count);`

to

`$total_page = !empty($page_count) ? ceil($c_data->count / $page_count) : 0;`

**Comment by tonbar** [comment]
Thank you, this has solved the problem I was having. I could see the div by 0 error but didn't know how to solve it or why it was manifesting in this way, so wasn't sure how best to correct it.
I am now able to create boards and see them. Thanks for your quick response and helpful support.
