### ISSUE TITLE
No password for new users created during Trello importing

### ISSUE THREAD

**Issue by garyfeng** [RestyaPlatform/board#96]
I tried to import from a board Trello. Importing JSON went smoothly and the board showed up, but it's under my Trello username. I cannot log using that username because it was automatically created during the importing and there was no password set for it. I tried logging in with a blank password but it wouldn't let me anywhere.

Is there a way to reset the password? And what would be a good way to handle this situation, assigning  a temporary password?

**Comment by rrjanbiah** [comment]
Default password is "restya" for Trello imported users. 

Also we cannot able to import user email from Trello. So you have to update user email in admin panel for each Trello users.

Opened #97

**Comment by rrjanbiah** [comment]
@garyfeng Closing this for now. If you get any issues, please reopen

**Comment by garyfeng** [comment]
was told the default password is "restya" for all

**Comment by rrjanbiah** [comment]
> was told the default password is "restya" for all

@garyfeng Can you please rephrase? Do you mean that it is not working?

**Comment by garyfeng** [comment]
sorry that was a mistake. I deleted the comment.
