### ISSUE TITLE
Blank Settings Page

### ISSUE THREAD

**Issue by Valiantiam** [RestyaPlatform/board#961]
After my install, I have found that some setting pages are blank entirely. Including the main "system" setting page located at /#/settings/3

![image](https://cloud.githubusercontent.com/assets/5394853/21726401/31c40d16-d402-11e6-89b4-bc46122843cb.png)

but some other ones load fine
![image](https://cloud.githubusercontent.com/assets/5394853/21726439/4f893e34-d402-11e6-894b-c4091c81fb44.png)

This is the only error caught by my web console
![image](https://cloud.githubusercontent.com/assets/5394853/21726490/82fdb1be-d402-11e6-9681-11502541b54b.png)

**Comment by lmarikannan** [comment]
@Valiantiam Can you please attach nginx `error.log` available in the path `/var/log/nginx`?

**Comment by Valiantiam** [comment]
[error.TXT](https://github.com/RestyaPlatform/board/files/691795/error.TXT)

Here you go. I grabbed the section that pops up when loading that page. I should not that its constantly filling with logs regarding the "already defined" stuff for TODO, DOING, JABBER_HOST, etc.

**Comment by lgg** [comment]
@Valiantiam this will help: https://github.com/RestyaPlatform/board/issues/705

**Comment by lmarikannan** [comment]
@Valiantiam Please feel free to reopen, if you still getting this error.

**Comment by Valiantiam** [comment]
I can confirm this worked! Thank you.
