### ISSUE TITLE
ubuntu 14.04 fails install again

### ISSUE THREAD

**Issue by kodb-avv** [RestyaPlatform/board#962]
reference #960.  Manual install of php-imap allowed script to progress until geopip when it failed.
see appended log entries:
...
Selecting previously unselected package libssl-doc.
Preparing to unpack .../libssl-doc_1.0.1t-1+deb7u1_all.deb ...
Unpacking libssl-doc (1.0.1t-1+deb7u1) ...
Selecting previously unselected package libtool.
Preparing to unpack .../libtool_2.4.2-1.7ubuntu1_amd64.deb ...
Unpacking libtool (2.4.2-1.7ubuntu1) ...
Selecting previously unselected package php-pear.
Preparing to unpack .../php-pear_5.5.9+dfsg-1ubuntu4.20_all.deb ...
Unpacking php-pear (5.5.9+dfsg-1ubuntu4.20) ...
Selecting previously unselected package shtool.
Preparing to unpack .../shtool_2.0.8-6_all.deb ...
Unpacking shtool (2.0.8-6) ...
Selecting previously unselected package php5-dev.
Preparing to unpack .../php5-dev_5.5.9+dfsg-1ubuntu4.20_amd64.deb ...
Unpacking php5-dev (5.5.9+dfsg-1ubuntu4.20) ...
Selecting previously unselected package php5-geoip.
Preparing to unpack .../php5-geoip_1.0.8-5build1_amd64.deb ...
Unpacking php5-geoip (1.0.8-5build1) ...
Selecting previously unselected package pkg-php-tools.
Preparing to unpack .../pkg-php-tools_1.11_all.deb ...
Unpacking pkg-php-tools (1.11) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for install-info (5.2.0.dfsg.1-2) ...
Setting up libunistring0:amd64 (0.9.3-5ubuntu3) ...
Setting up libgettextpo0:amd64 (0.18.3.1-1ubuntu3) ...
Setting up m4 (1.4.17-2ubuntu1) ...
Setting up autoconf (2.69-6) ...
Setting up autotools-dev (20130810.1) ...
Setting up automake (1:1.14.1-2ubuntu1) ...
update-alternatives: using /usr/bin/automake-1.14 to provide /usr/bin/automake (automake) in auto mode
Setting up libstdc++-4.8-dev:amd64 (4.8.4-2ubuntu1~14.04.3) ...
Setting up g++-4.8 (4.8.4-2ubuntu1~14.04.3) ...
Setting up g++ (4:4.8.2-1ubuntu6) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
Setting up make (3.81-8.2ubuntu3) ...
Setting up libdpkg-perl (1.17.5ubuntu5.7) ...
Setting up dpkg-dev (1.17.5ubuntu5.7) ...
Setting up build-essential (11.6ubuntu6) ...
Setting up gettext (0.18.3.1-1ubuntu3) ...
Setting up intltool-debian (0.35.0+20060710.1) ...
Setting up po-debconf (1.0.16+nmu2ubuntu1) ...
Setting up dh-apparmor (2.8.95~2430-0ubuntu5.3) ...
Setting up debhelper (9.20131227ubuntu1) ...
Setting up libfakeroot:amd64 (1.20-3ubuntu2) ...
Setting up fakeroot (1.20-3ubuntu2) ...
update-alternatives: using /usr/bin/fakeroot-sysv to provide /usr/bin/fakeroot (fakeroot) in auto mode
Setting up geoip-bin (1.6.0-1) ...
Setting up libalgorithm-diff-perl (1.19.02-3) ...
Setting up libalgorithm-merge-perl (0.08-2) ...
Setting up libasprintf-dev:amd64 (0.18.3.1-1ubuntu3) ...
Setting up libfile-fcntllock-perl (0.14-2build1) ...
Setting up libgeoip-dev (1.6.0-1) ...
Setting up libgettextpo-dev:amd64 (0.18.3.1-1ubuntu3) ...
Setting up libltdl-dev:amd64 (2.4.2-1.7ubuntu1) ...
Setting up libsys-hostname-long-perl (1.4-3) ...
Setting up libmail-sendmail-perl (0.79.16-1) ...
Setting up zlib1g-dev:amd64 (1:1.2.8.dfsg-1ubuntu1) ...
Setting up libssl-dev (1.0.1t-1+deb7u1) ...
Setting up libssl-doc (1.0.1t-1+deb7u1) ...
Setting up libtool (2.4.2-1.7ubuntu1) ...
Setting up php-pear (5.5.9+dfsg-1ubuntu4.20) ...
Setting up shtool (2.0.8-6) ...
Setting up php5-dev (5.5.9+dfsg-1ubuntu4.20) ...
update-alternatives: using /usr/bin/php-config5 to provide /usr/bin/php-config (php-config) in auto mode
update-alternatives: using /usr/bin/phpize5 to provide /usr/bin/phpize (phpize) in auto mode
Setting up php5-geoip (1.0.8-5build1) ...
Setting up pkg-php-tools (1.11) ...
Processing triggers for libc-bin (2.19-0ubuntu6.9) ...
+ '[' 0 '!=' 0 ']'
+ hash pecl/geoip
+ echo extension=geoip.so
+ mkdir -v /usr/share/GeoIP
mkdir: cannot create directory ‘/usr/share/GeoIP’: File exists
+ '[' 1 '!=' 0 ']'
+ echo 'GeoIP folder creation failed with error code 52'
GeoIP folder creation failed with error code 52
+ exit 1

**Comment by lmarikannan** [comment]
Related to #703, #797. Fixed in this commit https://github.com/RestyaPlatform/board/commit/b49a091b785018cb426c91afd91a3137b2f01e81. You can reopen this same issue, if you still facing the problem in installation.

Also we have improved our install script in our `dev` branch https://github.com/RestyaPlatform/board/blob/dev/restyaboard.sh.
