### ISSUE TITLE
Trouble with webhook.sh cron task

### ISSUE THREAD

**Issue by lgg** [RestyaPlatform/board#963]
```
2017-01-10 11:05:01 #################################################
mkdir: cannot create directory ‘/var/www/taskmanager/server/php/shell/cron_sh.lock’: File exists
cannot acquire lock, giving up on /var/www/taskmanager/server/php/shell/cron_sh.lock
```

Restyaboard installed manually.

Cron task:
`*/5 * * * * /var/www/taskmanager/server/php/shell/webhook.sh`

Other tasks work fine.

**Comment by lmarikannan** [comment]
@lgg Can you please replace the line https://github.com/RestyaPlatform/board/blob/master/server/php/shell/webhook.sh#L5?

`lockdir="${path}/cron_sh.lock"`

to

`lockdir="${path}/webhook_sh.lock"`

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/3ad042dd0ff36df1ba16b63563af455bf6cc85b7#diff-145fe7d61fd02ef6c458162d26548271
