### ISSUE TITLE
Password length

### ISSUE THREAD

**Issue by lgg** [RestyaPlatform/board#965]
In admin panel pass length is restricted by 50 symbols.

1. The warning message tells nothing about max length
>Password. Minimum 6 characters and white space not allowed

**no info about max length!!!**

Code: https://github.com/RestyaPlatform/board/blob/master/client/js/templates/users_register.jst.ejs#L16 and 
https://github.com/RestyaPlatform/board/blob/master/client/js/templates/admin_user_add.jst.ejs#L16

2. Also, why we need to restrict password length? For example, i use KeePass with default 64-symbol length password generation.

**Comment by lmarikannan** [comment]
@lgg Information issue fixed in this commit https://github.com/RestyaPlatform/board/commit/36917825b0b49302a2676f2cb683ec1fa122d0bf.

Also regarding password length 50 character is large enough and a normal user cannot able to remember more than that length.

**Comment by lgg** [comment]
1. It still not fixed in admin panel: 
https://github.com/RestyaPlatform/board/blob/master/client/js/templates/admin_user_add.jst.ejs#L16

2. Okay, most of users are okay with 50 symbols password length, but why? Why we can't increase it to 64,128,256,infinity? Any performance reasons? Special requirements of PostgreSQL?

**Comment by lmarikannan** [comment]
@lgg 

> It still not fixed in admin panel:
https://github.com/RestyaPlatform/board/blob/master/client/js/templates/admin_user_add.jst.ejs#L16

We have fixed this in `dev` branch and we will merge it in `master` branch while release next version.

> Okay, most of users are okay with 50 symbols password length, but why? Why we can't increase it to 64,128,256,infinity? Any performance reasons? Special requirements of PostgreSQL?

No such special requirements in PostgreSQL. You can increase it to any length.

**Comment by lgg** [comment]
@lmarikannan so if there are no special requirements - why we need maximum length restriction?

**Comment by lgg** [comment]
ping @lmarikannan

**Comment by lmarikannan** [comment]
@lgg Password length increased to 256 character in our `dev` branch.
