### ISSUE TITLE
Token expiration and auto-logout

### ISSUE THREAD

**Issue by xorander00** [RestyaPlatform/board#967]
Hello, love the project!  Keep up the good work :)  I'm having an issue with session logout and would like to get feedback.  Not sure if this is a bug or if it's a configuration issue on my part (probably the latter).

I keep a browser tab open, usually to a card that holds the task lists for what I'm currently working on.  The issue that I've run into is that when I go try to update the card after a period of inactivity (usually 15+ minutes), it logs me out and takes me back to the login form.  I've lost some form data this way because I wasn't expecting that.

I'm using PostgreSQL and looked at the oauth_* tables.  oauth_access_tokens currently has 3000+ rows in it, even though I'm pretty much the only user.  It accumulated this over the course of the past few weeks.  I checked the date/time/zone on the server, and it looks ok.  It looks like the token is being interpreted as invalid by the server and a new one is issued.  Is there a configuration setting I'm missing somewhere?  I'd like for tokens to live longer if possible (24-72 hours would be nice).

I'm not sure what else to look into, and I haven't had the chance yet to dig through the sources.  If you need further info about my environment, let me know.  If you can suggest what else to dig into, I can do that too.

**Comment by xorander00** [comment]
That'll teach me to not read the docs further.  I just saw and read the Known Issues page.  I suspect my issue was directly because of multiple tabs being open.

I'm going to close this issue.  Will reopen if I keep experiencing it.

**Comment by rrjanbiah** [comment]
Reopening this ticket as it has very good information to closely check

**Comment by xorander00** [comment]
I'm actually still experiencing the issue.  It happens less now because I'm not opening multiple tabs/sessions, but it does log me out randomly.

I'll dig into it further later this week.

**Comment by lmarikannan** [comment]
@xorander00 @rrjanbiah 

We have changed the session usage from browser sessionStorage to cookies. So in upcoming release, user can able to work in multiple tabs.

Also we have added a query to delete expired tokens from both `oauth_access_tokens` & `oauth_refresh_tokens`.

**Comment by xorander00** [comment]
Excellent, that should help matters.  I'll upgrade to the new release as soon as it's available and see if I still see the auto-logout issue.  I'm still getting it as of right now, even though I don't open it in multiple tabs anymore.

Also, has there been any consideration on using something like [localforage](https://github.com/localForage/localForage) for browser-local storage?  I use it in my own projects and I quite like it.  It's pretty flexible and the underlying storage mechanism can be changed pretty easily.

**Comment by rrjanbiah** [comment]
@lmarikannan 

> @xorander00 @rrjanbiah 
> 
> We have changed the session usage from browser sessionStorage to cookies. So in upcoming release, user can able to work in multiple tabs.
> 
> Also we have added a query to delete expired tokens from both `oauth_access_tokens` & `oauth_refresh_tokens`.

Looks like this doesn't address @xorander00 's concern of random logout even without opening multiple tabs

**Comment by lmarikannan** [comment]
@rrjanbiah 

> Looks like this doesn't address @xorander00 's concern of random logout even without opening multiple tabs

Random logout was not able to reproduce in current version v0.3.1. Also now we have changed it to cookie and logout will not happen in multiple tabs also.

**Comment by rrjanbiah** [comment]
@lmarikannan 

I can still able to reproduce auto logout after inactivity.

Related #1285

**Comment by lmarikannan** [comment]
@rrjanbiah We couldn't reproduce this issue on our development server. In http://board.demo.restya.com site having cron to reset its data by every one hour, so only logout will occur. But in MyRestyaboards iOS app, this issue is occurred.  so we'll update once we check with our iOS team.
