### ISSUE TITLE
PNG and JS errors after script install

### ISSUE THREAD

**Issue by Gman1988** [RestyaPlatform/board#969]
Hi i tested docker image and i loved.  But for some reason API wont worked on docker image.

So i used installation script on CentOS7 and after few modification all was go ok.

But after log in there are errors in console about wrong JS function and some png missing.

And when i enter the admin -> settings page its blang as on picture below. But when i manually edit link for 3 or other some seetings show up.

![screenshot from 2017-01-13 00-09-00](https://cloud.githubusercontent.com/assets/13338697/21912259/1342684c-d925-11e6-977f-66bdb61942cb.png)

Can you help me ?

**Comment by rrjanbiah** [comment]
@Gman1988 As noted here http://restya.com/board/install#Manualsetup you'll need write permission for `media`, `tmp/cache`, `server/php/shell/*.sh` & `client/img`

Can you please check that?

**Comment by Gman1988** [comment]
@rrjanbiah 
Unfortunatly it didnt helped, those dira was already with write permission for php, any other ideas?

It display werid name of png, i think that it should display default-admin-user.png ?

And what with those js functions ?

**Comment by lmarikannan** [comment]
@Gman1988 

> It display weird name of png, i think that it should display default-admin-user.png ?

Actually we will generate a hash using image name and create a resize image. So only it displays that name.

Also we cannot able to reproduce this issue.

Can you please upgrade to our new version and let us know your feedback?
