### ISSUE TITLE
Quoted printable subjects in IMAP mails not decoded

### ISSUE THREAD

**Issue by morphiumdeus** [RestyaPlatform/board#971]
When sending an email to a board with https://en.wikipedia.org/wiki/Quoted-printable subject, the card title is not decoded.
I proposed a fix in commit 95249e00957ada500a70fb16cbbe3e25e83c63c7 (https://github.com/morphiumdeus/board/pull/1).

**Comment by lmarikannan** [comment]
@morphiumdeus Thank you for your contribution. But it looks like the coding is not completed yet.

This line not completed.
`$title .= iconv($decoded_title[$i]->charset, "utf-8", $de$`

Also `$title` is not used anywhere. Can you please check and confirm? After that we will merge it.

**Comment by morphiumdeus** [comment]
@lmarikannan Sorry for that. That's what happens when you program in a putty console and copy-paste the result.
I corrected it.

**Comment by lmarikannan** [comment]
@morphiumdeus Thank you for your contribution. We have merged the code in our branch.
