### ISSUE TITLE
0.4 release and Android

### ISSUE THREAD

**Issue by xorander00** [RestyaPlatform/board#972]
Any status update on the 0.4 release?  I've started to slowly develop an Android client, but would like to see the changes in 0.4 before going further.  Thanks!

**Comment by rrjanbiah** [comment]
@xorander00 We are almost there. For now 

1. Working on website updates 
2. Waiting to get QA approval 
3. Looking on failing build 

So mostly will release in this week

**Comment by miniminime** [comment]
Incl. RedHat 6.5?

**Comment by rrjanbiah** [comment]
Linking "RedHat" related tickets for better understanding https://github.com/RestyaPlatform/board/search?q=redhat&type=Issues&utf8=%E2%9C%93

**Comment by xorander00** [comment]
Status update on the release?  Anything I can do to help?  I'm restructuring my workflow this week and am deciding on what to types of data to store in the different services I utilize, Restyaboard being one of them.  I'm working on my own integration server between the services that uses WebHooks.  I'd like to review the latest release to decide some of these factors.  Thanks!

**Comment by lmarikannan** [comment]
@xorander00 We have released v0.4 just now.
