### ISSUE TITLE
Restya Install Script - CentOS 6.8

### ISSUE THREAD

**Issue by vClouds** [RestyaPlatform/board#974]
Please revise the install script, several trials to install on Ubuntu 14.04, 16.04 LTS and CentOS 6.8 with no luck yet.
below are some of adjustments I have done with CentOS 6.8 to proceed further with no successful install yet.
Line 318: cd: /etc/ejabberd: No such file or directory (Please adjust)
Line 999 > yum install -y php-pear (Terminal is stopping waiting for user confirmation)
Line 1061 > yum install -y https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-3.noarch.rpm (the current download link is broken http://yum.postgresql.org/9.4/redhat/rhel-6.6-x86_64/pgdg-centos94-9.4-1.noarch.rpm)
Line 1278 > yum install -y GeoIP-devel (Terminal is stopping waiting for user confirmation)
Lines 1286-1301, results in exit because the directory /usr/share/GeoIP already there and "extension=geoip.so" is not explicitly appear anywhere.
[restyaboard_install.log.txt](https://github.com/RestyaPlatform/board/files/720848/restyaboard_install.log.txt)

**Comment by lmarikannan** [comment]
@vClouds Sorry for the inconvenience. We have revised install script in our `dev` branch https://raw.githubusercontent.com/RestyaPlatform/board/dev/restyaboard.sh and we are going to release new version shortly.

**Comment by lmarikannan** [comment]
@vClouds We have released new version v0.4 and let us know your feedback.

**Comment by miniminime** [comment]
Just tested on a fresh 6.8 installation with master v0.4:

No package postgresql95-server available.
No package postgresql95 available.
Error: Nothing to do
++ '[' 1 '!=' 0 ']'
++ echo 'Installing PostgreSQL 64 fail with error code 28'
Installing PostgreSQL 64 fail with error code 28
++ exit 1

Could you please test it with a fresh CentOS 6.8 installation? There are some rough edges before as well (errors, warnings...).

**Comment by lmarikannan** [comment]
@miniminime Can you please attach your installation log file?

**Comment by rrjanbiah** [comment]
> @miniminime Can you please attach your installation log file?

I think, he has given some hints. Can we have the QA or system admin team check it in CentOS too?

**Comment by miniminime** [comment]
Here the log file.
[restyaboard_install.log.txt](https://github.com/RestyaPlatform/board/files/726060/restyaboard_install.log.txt)

**Comment by lmarikannan** [comment]
@miniminime We have checked your installation log and it looks like `lsb_release` command was not found in your server. So we have added an additional condition if the `lsb_release` command not found then the install script will not run. Please refer https://github.com/RestyaPlatform/board/blob/master/restyaboard.sh#L19.
