### ISSUE TITLE
Commercialization Plans

### ISSUE THREAD

**Issue by xorander00** [RestyaPlatform/board#976]
What are the commercialization plans for the coming year?  I haven't yet installed v0.4 because I saw that a good chunk of functionality is converted to the commercial plan.  That's fine and understandable, but I need to decide which direction to go in terms of my own workflow and plans.

How much of it is going to stay free/open?  How much of it is going to go commercial?

**Comment by rrjanbiah** [comment]
@xorander00 As of now, we have planned to keep the core and our apps architecture under OSL, and planning to bring more paid plugins.

If you have any suggestions, please feel free to share your comments.

**Comment by hechi** [comment]
Hey @rrjanbiah i loved the board and i can understand why you but some of the plugins as a paid option. But one of the main features and for me a core functionality is gone (LDAP). This was the criteria why i choose restyaboard a year ago. All my services (cloud,email,git,...) for my family and friends uses LDAP so i don't want to change it and they are happy to only remember one login :) I hope you understand my reasons for not updating to v0.4. Nevertheless thanks for the hard work the last year and good luck.

**Comment by rrjanbiah** [comment]
@hechi Thanks for your note. In our understanding, LDAP is more enterprise centric. And, didn't realize that it will be required in home or personal use cases.

I'll also internally check and update you here about LDAP.

**Comment by hechi** [comment]
@rrjanbiah thanks
i can understand your point of few but also my IT-affine friends uses LDAP for everything at home. You can look at Wekans LDAP issue how many people would love to have it ^^ so it could be also a plus point to have it free and open. My Mom and Girlfriend would never use the services if they have to remember several accounts or at least the would ask to reset there password every week :p

**Comment by rrjanbiah** [comment]
@hechi Points noted. We need few days to figure it out. Will keep you posted.

**Comment by xorander00** [comment]
My technical comments are as follows:
- The new version does seem more performant, which is awesome! :)
- I was just about to say that changing the local storage mechanism helped, but it seems to still be broken.  In the middle of writing this, I tried to switch to another board (I had left the tab open overnight).  It directed me to /#/users/logout and a blank page.  I tried going back to the main page (which I would expect to show me the login form), but it's still redirecting me to /#/users/logout and not showing me the login form.  I checked Chrome Developer Tools and I'm getting the following messages:
  - /api/v1/settings.json?token=39680065e409559250c94486bd2de6c2d00abcde&_=1485355773489 (401 Unauthorized)
  - /api/v1/users/logout.json?_=1485355773680 (401 Authentication failed)
- Does the logout path require authentication?  If so, that's obviously an error.  I had to clear the local application storage to get it to work again.  I can see where most users wouldn't understand how to do that though.  On a positive note, it's not killing my session randomly anymore it seems (aside from what it just had to do).
- One suggestion I might have would be to have a single canonical form that utilizes the HTTP accept header and an optional API version header.  Instead of /api/v1/{action}/{params}, use /api/{action}/{params} since URIs should be permanent.  The client should specify the Accept header for the version that it accepts.  If that's missing, then the server should assume the latest version (or most compatible latest version).  There's also the option of an API-specific header that the client requests, but that's not as clean as the standard Accept header.
- Another alternative, although longer term, would be GraphQL.  I utilize both REST and GraphQL in my apps.  GraphQL would probably be more ideal for Restya as it seems to fit the usage and domain better.  Specifying the shape of the data and incremental mutations would make it a lot more performant.
- I personally don't look at the activity stream much.  It's pretty noisy and heavy though and as such slows down the application a fair amount.  I'd love to have a user-specific setting that doesn't show the activity stream unless specifically wanting to see it.
- Within a card view, resizing the two panes within the card (left side data and right side activities/comments) is buggy.  It doesn't work well when the card is expanded/modal, only when is in its normal size.
- From a UX perspective, I would suggest stacking the two panes by default, as that's the most likely use-case and the order in which users will consume information on the card at a glance.
- Not a priority issue, but being able to specify label colors would be nice.  That's a UX issue, because being able to glance at a board and seeing the expected colors that I'm used to would help me focus on the cards that are immediately important to me.  For example, I use "Priority:High", "Priority:Normal", "Priority:Low" quite a bit.  Red-Yellow-Green would be what I use for those labels, respectively.  Currently, since they're auto-assigned, they use colors that I'm not used to, so when I look at the board I have to frequently hover over the label to know which type of tag it is and what it related to.  Again, not a huge deal, but it would boost productivity quite a bit to be able to specify colored labels.

My general opinions are as follows:
- I don't use LDAP, but did use the ElasticSearch functionality every so often.  As it stands right now, I have upgraded to v0.4.  I don't mind losing the ElasticSearch functionality for now, but I may have to migrate away or downgrade later (I kept a copy of the old app + db + conf).
- When I asked about what would stay free and what would go commercial, that's what I meant.  What was previously free is now non-free.  ElasticSearch isn't a huge deal for me right now, and writing (or re-writing) a plugin for it wouldn't be too difficult.  I have several instances that I use for myself and the API for ElasticSearch is pretty straightforward and simple.
- I totally understand the need to go commercial.  I did look at the pricing though and it's quite a bit beyond what I would pay.  I'm sure some enterprises would pay, but I think at that price it's no longer targeting lower-level consumer use.  Especially considering the current bugs, performance issues, and missing options.  Not trying to be overly critical, as I understand the growing pains and complexities involved in such a project.  Just being straightforward.  Is dual-licensing out of the question?  Personal or trial use is free and includes a majority, if not all, of the features.  Commercial use is clearly defined and required for more than X number of total users?

**Comment by rrjanbiah** [comment]
@xorander00 Many thanks for your wonderful feedback. We'll need to discuss internally and need few days time to update you. Thanks again.

**Comment by rrjanbiah** [comment]
@xorander00 Also, we'll address your technical issues as early as possible.

**Comment by hechi** [comment]
@xorander00 nice review. Please don't do a "For X number of users" thing. If you do a dual-licensing i am fine to get no support or auto update stuff. If you want i can connect you with people from https://github.com/nextcloud which also do enterprise plugin development and they are really good between community and enterprise.

**Comment by xorander00** [comment]
Since it's free, it should be assumed by the user and explicitly written out by the project that there's no support.  Not providing auto-updates is ok, but it's not enough of a value to incentivize enterprise customers to pay.  In fact, most enterprise customers likely won't auto-update to begin with since most will have internal policies that require testing.  Not having auto-updates would hurt the overall ecosystem of consumers because then they wouldn't be able to push out opt-in security patches.  Not good.

Personally, I suspect something along the lines of the GitLab model would probably generate decent income to sustain development and continue to expand.  I understand why limiting the number of users in the free version would be a pain, but there has to be some compromise on how to monetize it.

Also, I see that there seems to be a focus on establishing and developing the app market.  I'd suggest working on the getting the core platform fixed and stable first before working on the mechanisms for 3rd-party extensions.  It'll just turn developers off to your platform all together if there are bugs that disallow use of extensions.  I remember a while back having some issue with the time tracking extension.  I spent a couple of hours looking into it and finally just disabled it and am now using GitLab for that.

**Comment by rrjanbiah** [comment]
@hechi & @xorander00 Sorry for the delay. Thanks a lot for your suggestions. We still need some time to figure it out properly. @hechi Will connect to you privately for your suggestions.

At this moment, we're thinking to continue dual licensing. 

For the paid plugins, thinking to provide Free for those who're listed in credits... also, for personal and educational use, thinking to provide Free for a tweet, FB share, or blog post. If you have any suggestions, please let us know.

**Comment by xorander00** [comment]
Sounds good.  I actually like the idea of free for personal use and/or a social media bump.  I don't use social media myself, but I do keep a blog.  It's not high-traffic, but I'd be more than happy to write a post about Restya.

I opened several other issues in relation to bugs.  Instead of doing that, I'll see if I can just consolidate it all into a single pull request or something.

**Comment by rrjanbiah** [comment]
@xorander00 Thanks a lot for your kind words and notes.

**Comment by hechi** [comment]
@rrjanbiah ok :) but keep in mind people only blog or tweet if the can test it (trail) and it has to be easy to go from trail to normal.

**Comment by rrjanbiah** [comment]
@hechi Thanks for your note too

**Comment by rrjanbiah** [comment]
@xorander00 Were you able to release your Android App? Or, are you waiting for us on anything?

**Comment by xorander00** [comment]
I'm not actually building it for release, but I don't really have a problem releasing it.  I do have to go through and review the code though, as it's pretty hacky.  There's no documentation, and it only supports the bare minimum of functionality that I need.

Also, nothing again this project as I still like it, but I've been using my previous system a bit more again.  The performance issues & occasional bugs were slowing me down enough to stick to my old system.  I still have my containerized instance of Restya running, so I'll be upgrading it from time-to-time to see how it's coming along.

If you guys want to work on the Android app, then I can allocate some time on my calendar to prepare it.  I have to say right now though that my schedule is packed for the next few weeks, so I won't be able to get to it until the end of this month at the earliest.

**Comment by rrjanbiah** [comment]
> I'm not actually building it for release, but I don't really have a problem releasing it. I do have to go through and review the code though, as it's pretty hacky. There's no documentation, and it only supports the bare minimum of functionality that I need.

If you're referring to web service part, we're working to migrate to Slim framework. Perhaps that would help?

> Also, nothing again this project as I still like it, but I've been using my previous system a bit more again. The performance issues & occasional bugs were slowing me down enough to stick to my old system. I still have my containerized instance of Restya running, so I'll be upgrading it from time-to-time to see how it's coming along.

Sure, please feel free to post any issues. That will help us to improve it.

> If you guys want to work on the Android app, then I can allocate some time on my calendar to prepare it. I have to say right now though that my schedule is packed for the next few weeks, so I won't be able to get to it until the end of this month at the earliest.

If you're planning for commercial release, please reach us through contact page and share your Skype handle.

**Comment by rrjanbiah** [comment]
If anyone here is waiting for a free copy of plugins, please contact us through website contact form with the plugin list you wanted. We were waiting to automate that process, but as it is sidelined due to other priorities, we'll process that manually for now.

**Comment by rrjanbiah** [comment]
http://restya.com/board/free-copy is currently implemented in our website.
