### ISSUE TITLE
URL Routing Bug

### ISSUE THREAD

**Issue by xorander00** [RestyaPlatform/board#982]
Just noticed this one.  Running v0.4.

1. Open a board and then open a card.
2. In the description section of the card, I have a link to another board.
3. Click on the link and go to the new board.
4. Close the card that was open.
5. The address bar URL contains the correct board URL (the id is right).
6. Open a card in the new board.
7. Close the card the in the new board.
8. The URL has reverted to the previous board.

I found this when testing out local storage and being able to open multiple tabs.  I opened a new tab to a different board.  Then I opened a card to make sure that it loads properly and doesn't boot me back to the login screen.  It worked fine, no issues.  Then I closed the card and hit refresh to see if the board would reload fine without booting me to the login form.  That's when I noticed that the URL was the one used for the old board.

**Comment by rrjanbiah** [comment]
@xorander00 Thanks a lot for you report. We'll fix it ASAP

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/04a1a490bfdd74b267d06cba2e4c984e88fadcbf
