### ISSUE TITLE
Ubuntu Script Fails

### ISSUE THREAD

**Issue by toddleish** [RestyaPlatform/board#983]
Hello,
I have been trying to install Restyaboard on Ubuntu 14.04, but continue to hit many errors.  The first errors were with installing NGINX and ImageMagick, so I installed those manually and then ran the script again.  

Now the script gets very far, but fails here:

Creating PostgreSQL user and database...
+ psql -U postgres -c DROP USER IF EXISTS restya;CREATE USER restya WITH ENCRYPTED PASSWORD 'hjVl2!rGd'
NOTICE:  role "restya" does not exist, skipping
CREATE ROLE
+ [ 0 != 0 ]
+ psql -U postgres -c DROP DATABASE IF EXISTS restyaboard;CREATE DATABASE restyaboard OWNER restya ENCODING 'UTF8' TEMPLATE template0
ERROR:  DROP DATABASE cannot be executed from a function or multi-command string
+ [ 1 != 0 ]
+ echo PostgreSQL database creation failed with error code 36
PostgreSQL database creation failed with error code 36
+ exit 1

I don't know what the problem is, but I am attaching the log...  The script has many problems still.
[restyaboard_install.log.txt](https://github.com/RestyaPlatform/board/files/730607/restyaboard_install.log.txt)

**Comment by rrjanbiah** [comment]
@toddleish Thanks a lot for your report. We'll fix it ASAP

**Comment by toddleish** [comment]
Thank you... I was able to install properly in Ubuntu now.  However, I get one more server error in Chrome and in the NGINX log... Can you tell me what to do with this error?

2017/02/01 11:07:25 [error] 1073#0: *6600 open() "/usr/share/nginx/html/restyaboard/client/apps/r_cssilize/css/default.cache.css" failed (2: No such file or directory), client: 192.168.1.50, server: 192.168.3.53, request: "GET /apps/r_cssilize/css/default.cache.css HTTP/1.1", host: "192.168.3.53", referrer: "http://192.168.3.53/"

**Comment by lmarikannan** [comment]
@toddleish 

Can you please download new releases of apps and unzip in this folder `/usr/share/nginx/html/restyaboard/client/apps`?

https://github.com/RestyaPlatform/board-apps/releases/tag/v1

**Comment by darko190** [comment]
I still have the same problem...

+ psql -U postgres -c \q
+ [ 0 != 0 ]
+ sleep 1
+ echo Creating PostgreSQL user and database...
Creating PostgreSQL user and database...
+ psql -U postgres -c DROP USER IF EXISTS restya;CREATE USER restya WITH ENCRYPTED PASSWORD 'hjVl2!rGd'
NOTICE:  role "restya" does not exist, skipping
CREATE ROLE
+ [ 0 != 0 ]
+ psql -U postgres -c DROP DATABASE IF EXISTS restyaboard;CREATE DATABASE restyaboard OWNER restya ENCODING 'UTF8' TEMPLATE template0
ERROR:  DROP DATABASE cannot be executed from a function or multi-command string
+ [ 1 != 0 ]
+ echo PostgreSQL database creation failed with error code 36
PostgreSQL database creation failed with error code 36

Ubuntu 16.04

**Comment by lmarikannan** [comment]
@darko190 This issue is cause due to two queries are execute in same line. So Can you please refer this commit https://github.com/RestyaPlatform/board/commit/fb2f4ffd7366a6c4f65a72f2475b2afaf3ed1ac4. Just remove `DROP DATABASE IF EXISTS ${POSTGRES_DBNAME};` from script  and run the installation script again.
