### ISSUE TITLE
Image Generation Bug

### ISSUE THREAD

**Issue by xorander00** [RestyaPlatform/board#984]
Just a quick one.  Sorry, no pull request.  I found and fixed this really quick and don't have the immediate time to generate one.

When I uploaded an image for a new board I just created it returned a 500 (internal server error).  Upon looking at the nginx log, it was complaining about Imagick::flattenImages() not being found.  I did a quick search and saw that it's deprecated in recent versions.

server/php/image.php:67 contains the line:
$new_image->flattenImages();

I replaced it with:
$new_image->mergeImageLayers(Imagick::LAYERMETHOD_FLATTEN);

Works fine now.

**Comment by rrjanbiah** [comment]
@xorander00 Thanks a lot for your fix.

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/44ffdf5b704e309dbd0a4da7689cf0a4eb8196e0
