### ISSUE TITLE
Centos 7 Script Broken

### ISSUE THREAD

**Issue by toddleish** [RestyaPlatform/board#986]
The Restyaboard script for CentOS 7 makes it almost to the end but crashes here:

Creating PostgreSQL user and database...
++ psql -U postgres -c 'DROP USER IF EXISTS restya;CREATE USER restya WITH ENCRYPTED PASSWORD '\''hjVl2!rGd'\'''
NOTICE:  role "restya" does not exist, skipping
CREATE ROLE
++ '[' 0 '!=' 0 ']'
++ psql -U postgres -c 'DROP DATABASE IF EXISTS restyaboard;CREATE DATABASE restyaboard OWNER restya ENCODING '\''UTF8'\'' TEMPLATE template0'
ERROR:  DROP DATABASE cannot be executed from a function or multi-command string
++ '[' 1 '!=' 0 ']'
++ echo 'PostgreSQL database creation failed with error code 42'
PostgreSQL database creation failed with error code 42
++ exit 1

**Comment by toddleish** [comment]
If I install PostgreSQL-9.6 manually and then run the script, it completes correctly... I have another problem now when I try to login for the first time... I will post a new report...

**Comment by lmarikannan** [comment]
Fixed in this commit https://github.com/RestyaPlatform/board/commit/fb2f4ffd7366a6c4f65a72f2475b2afaf3ed1ac4.
