### ISSUE TITLE
Blank, White Page after Install

### ISSUE THREAD

**Issue by toddleish** [RestyaPlatform/board#987]
After installing Restyaboard on Centos 7, I go to the server, 192.168.3.53.  The browser shows a blank, white page with a red bar that briefly scrolls across the top.  Then, it remains blank.  I turned on debug mode, but I see no output.

The NGINX log shows this:
2017/01/26 16:54:56 [crit] 1046#0: *1 connect() to unix:/run/php/php7.0-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.1.50, server: 192.168.3.53, request: "GET /api/v1/oauth.json?_=1485474865372 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "192.168.3.53", referrer: "http://192.168.3.53/"

The Chrome Developer Tools show this:
 Failed to load resource: the server responded with a status of 502 (Bad Gateway)   http://192.168.3.53/api/v1/oauth.json?_=1485474865372
 Uncaught SyntaxError: Unexpected token < in JSON at position 0   VM270:1
    at JSON.parse (<anonymous>)
    at default.cache.91ff0ef6.js:57
    at o (default.cache.91ff0ef6.js:12)
    at Object.d.error (default.cache.91ff0ef6.js:12)
    at l (default.cache.91ff0ef6.js:1)
    at Object.fireWith [as rejectWith] (default.cache.91ff0ef6.js:1)
    at d (default.cache.91ff0ef6.js:3)
    at XMLHttpRequest.d (default.cache.91ff0ef6.js:3)

[restyaboard_install.log.txt](https://github.com/RestyaPlatform/board/files/733952/restyaboard_install.log.txt)

**Comment by rrjanbiah** [comment]
Initial observation.. looks like php fpm is not installed properly or not running.

**Comment by toddleish** [comment]
Thank you for looking, but my system shows that php fpm is installed and running:
[root@192 ~]# systemctl status php-fpm
● php-fpm.service - The PHP FastCGI Process Manager
   Loaded: loaded (/usr/lib/systemd/system/php-fpm.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-01-26 22:49:36 MST; 13h ago
 Main PID: 930 (php-fpm)
   Status: "Processes active: 0, idle: 5, Requests: 0, slow: 0, Traffic: 0req/sec"
   CGroup: /system.slice/php-fpm.service
           ├─ 930 php-fpm: master process (/etc/php-fpm.conf)
           ├─1002 php-fpm: pool www
           ├─1003 php-fpm: pool www
           ├─1004 php-fpm: pool www
           ├─1008 php-fpm: pool www
           └─1009 php-fpm: pool www

Jan 26 22:49:36 192.168.3.53 systemd[1]: Starting The PHP FastCGI Process Ma....
Jan 26 22:49:36 192.168.3.53 php-fpm[930]: [26-Jan-2017 22:49:36] NOTICE: PH...0
Jan 26 22:49:36 192.168.3.53 php-fpm[930]: [26-Jan-2017 22:49:36] NOTICE: PH...0
Jan 26 22:49:36 192.168.3.53 systemd[1]: Started The PHP FastCGI Process Man....
Hint: Some lines were ellipsized, use -l to show in full.


The only PHP errors I see are as follows:  (Are these important?)
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/imagick.so' - /usr/lib64/php/modules/imagick.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/geoip.so' - /usr/lib64/php/modules/geoip.so: cannot open shared object file: No such file or directory in Unknown on line 0

**Comment by lmarikannan** [comment]
@toddleish While checking your install log, it looks PHP 5.4 version was installed in your system but we have referred `php7.0-fmp.sock` in nginx conf file. Please refer https://github.com/RestyaPlatform/board/blob/master/restyaboard.conf#L35. So only you are getting this error `2017/01/26 16:54:56 [crit] 1046#0: *1 connect() to unix:/run/php/php7.0-fpm.sock failed (2: No such file or directory)`. Can you please change php-fpm.sock for your PHP 5.4 version in nginx conf file and restart nginx?

**Comment by toddleish** [comment]
Okay, I did as you suggested.  Now the NGINX log shows this error instead:
2017/01/31 14:28:17 [crit] 1042#0: *1 connect() to unix:/run/php/php5.4-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.1.50, server: 192.168.3.53, request: "GET /api/v1/oauth.json?_=1485898054508 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php5.4-fpm.sock:", host: "192.168.3.53", referrer: "http://192.168.3.53/"

Are we getting closer?

**Comment by lmarikannan** [comment]
@toddleish It shows there is no such file in this path `/run/php/php5.4-fpm.sock`. Can you please check correct file name and path and update in nginx conf?

**Comment by lmarikannan** [comment]
Closing this issue. Installation was completed as per this comment https://github.com/RestyaPlatform/board/issues/983#issuecomment-276733970.
