### ISSUE TITLE
Issue linking to Google Docs (sheet)

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#99]
From Jeff
![2015-11-06_13-49-20](https://cloud.githubusercontent.com/assets/4907427/11014350/2af09a8a-8558-11e5-951b-ff315b7e177b.png)
:

When linking to a Google Doc, in this case a sheet, I get the attached error/screen. 

I made sure that the Google Sheet I was sharing was a public link.

**Comment by ssivachidambaram** [comment]
Fixed in v0.1.6.
