### ISSUE TITLE
Suggestion for Labels

### ISSUE THREAD

**Issue by xorander00** [RestyaPlatform/board#996]
When managing labels for a given card, I suggest possibly getting rid of the [+] button and replacing it with a link next to the title (maybe says "Manage") or leaving the [+] button but changing the text to "..." or something.

When I first started using Restya, I was confused as to how to remove a label from a card.  It wasn't until hit the + button that I realized it's used for generally managing the labels.

**Comment by lmarikannan** [comment]
@xorander00 We have checked with Trello and they are opening the dropdown while click on added labels also. Is this fine to open the label drop down while clicking on added labels too?

**Comment by xorander00** [comment]
It's fine.  It's not a major issue or anything.  Just a matter of preference.  The easiest way to figure it out it would be to just poll the users and ask them which way they prefer.  Personally, I'm used to a single button/drop-down for CRUD operations on any atomic unit of information (a card in this case).

A larger issue, but still nothing major, would be label colors.  Being able to assign a label color would be useful, for me at least.  I'd suggest keeping it mostly the way it is now, but add an icon next to the label management setting to pop-up a color selector.

**Comment by lmarikannan** [comment]
@xorander00 We have implemented dropdown open while click label in this PR https://github.com/RestyaPlatform/board/pull/1002.

Also in future we will consider your color management for labels.

**Comment by rrjanbiah** [comment]
Linking label color ticket #712
